### ISSUE TITLE
Custom javascript not working

### ISSUE THREAD

**Issue by lalainarahajason** [understrap/understrap#1000]
Hi,

I want to use understrap for my future theme and want to add swiperjs library to it, as said from the script official page, i have to add this from : 

    npm install swiper

After this what should i do? i have to require it from the gulpfile.js ? 

    var swiper = require('swiper');
    console.log(swiper) // output the swiper object from terminal after gulp scripts

Inside the same file (gulpfile.js) i found a line where i can add my custom js : 

        `${paths.dev}/js/skip-link-focus-fix.js`,

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        `${paths.dev}js/custom-javascript.js`,

So i added 'custom-javascript.js' with just console.log('test') and alert('test') inside my src folder, and finaly run 'gulp scripts && gulp watch'

I don't get the console.log test nor the alert printed.

Someone could help me please ?

NB : i use undestrap child theme

Thank you

**Comment by Thomas-A-Reinert** [comment]
Hi @lalainarahajason . There was a problem with a missing slash in the gulpconfig.js for the custom-javascript.js . I just pushed a fix for that. 

PS: Please post child-theme issues in the child-theme repo next time, okay?
