### ISSUE TITLE
Adding gulp-svg-sprites to gulpfile

### ISSUE THREAD

**Issue by zaccety** [understrap/understrap#1004]
Hi, I'm trying to add gulp-svg-sprites (https://www.npmjs.com/package/gulp-svg-sprites) to the gulpfile that ships with the theme but I'm not entirely sure what the right way to do it is - any chance of an example/point in the right direction. 

Cheers,

**Comment by 0dp** [comment]
Hi zaccety, in the link you sent there is a fairly straightforward example of how to do it.

Drop the variable into the top of the gulpfile together with the other includes, and drop the gulp task at the end of the gulpfile.

The only things you would want to change is the src of the files and the dest. Respectfully where the svg files come from and where the spritesheet is saved

**Comment by Thomas-A-Reinert** [comment]
Hi @zaccety - no offense intended, but this is _really_ not an UnderStrap problem. Please refer to the docs /  https://www.google.de/search?pws=0&no_sw_cr=1&hl=de&q=stackoverflow+gulp-svg-sprites or whatever.

We can´t do more for you than @0dp already did. Closing this issue as it´s not UnderStrap dependant.

**Comment by zaccety** [comment]
Cool cool,, was a stupid question on reflection, I'm just getting to grips with working with Gulp.

Thanks for taking the time to reply though.
