### ISSUE TITLE
Best method for making AJAX calls

### ISSUE THREAD

**Issue by bennettscience** [understrap/understrap#1007]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **Understrap Version:** 0.9.4
  - **OS Version:** MacOS 10.14.5
  - **Language:** PHP, Javascript/jQuery
---

I'm developing a theme and I'm trying to figure out the best way to make AJAX calls from the frontend using good WP enqueueing. Most of the docs I've seen have scripts in the template file itself so variables are available from the `$post` object. But, [this SO post](https://stackoverflow.com/questions/49341601/add-custom-js-to-understrap) said to add any custom scripting to `/src/js/custom-javascript.js`. Hard-coding the WP `admin-ajax.php` URL returned a 400 error for a bad request.

So, what's the best way to follow conventions for Understrap _and_ WordPress? Or is editing the `content.php` template file okay to do?

**Comment by GeekStreetWP** [comment]
you can bring the /loop-templates/content.php over to your child theme. Then you can modify all you want. child-theme/loop-templates/content.php will load instead of understrap/loop-templates/content.php.

**Comment by pattonwebz** [comment]
Add a new JS file and follow this answer to help you get it added to your page: https://stackoverflow.com/a/49352981/2375493

You can use `wp_localize_script()` to add data to the page for use in the JS without hardcoding it in template files: https://codex.wordpress.org/Function_Reference/wp_localize_script

Also you probably want to read up on: https://developer.wordpress.org/themes/theme-security/using-nonces/ and seems like you may also need to look into https://codex.wordpress.org/Plugin_API/Action_Reference/wp_ajax_nopriv_(action) as well so you can get your adminAjax url defined and usable frontend for logged out users.

**Comment by bennettscience** [comment]
Thanks for the suggestions. I came across the enqueue method not long after posting here. Working great now.
