### ISSUE TITLE
Issues with scss overrides (_theme.scss)

### ISSUE THREAD

**Issue by waynetoddwebDnD** [understrap/understrap#1008]
## Issue is about..
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** Windows 10
  - **Browser:**  all 
  - **Language:** S/CSS 

### Other Comments

Hello, I am having trouble with scss and bootstrap. I followed these instructions [from Github](https://understrap.github.io/ ) to set up a development environment for using Understrap. 

I was able to successfully install npm, gulp, dependencies, and then start up a `gulp watch` .

However, when I add styles to _theme.scss, they aren't applied after a refresh, even on an empty cache. The changes are being noticed and compiled by sass. It seems to be an issue with either specificity, because styles from Bootstrap are overriding my styles, most notably the variables.

Any assistance would be much appreciated. This is my first time submitting to Github.

![github-screenshot](https://user-images.githubusercontent.com/46391998/61167503-b9ac3100-a505-11e9-95eb-ca0864b9b1fd.JPG)

**Comment by holger1411** [comment]
Hi!
Could you specify what do you add to your _theme.scss file and which understrap version do you use?

**Comment by trandrew** [comment]
I'm also running into this issue. For some reason, in Inspector, _navbar.scss keeps loading before _child-theme.scss. 

in _child-theme.scss, I just have a simple:
.nav-link { color: $blue; }
but in Inspector, it loads:
.navbar-light .navbar-nav .nav-link {
    color: rgba(0,0,0,.5);
before styles that I've written.

Any idea why?

**Comment by rmleg** [comment]
@trandrew I think this is the expected behavior. Changes to the theme styles should be done by overriding variables where appropriate. Overriding the `$navbar-light-color` variable in your _child_theme_variables.scss file will cause _navbar.scss to render `.navbar-light .navbar-nav .nav-link` with the `$navbar-light-color` you specify. You can find a list of all variables in `./src/sass/bootstrap4/_variables.scss`.

I hope that helps!

**Comment by joshtankpr** [comment]
I ran into this issue also. For me it was simply a caching issue with the browser I was using. (Obviously this might not be the case for others)

Try viewing the site via a incognito or private browser version.

I also had the @trandrew mentioned with different styles loading. This I manged to get around by making a large change to the CSS file and letting gulp rebuild the sass.

**Comment by Thomas-A-Reinert** [comment]
This seems to be resolved, if I´m not all wrong.

If the problem remains, please feel free to re-open that issue.

For the "crew" and stats! – this is one of the only/last issues where @holger1411 answered!

**Comment by KRussellE** [comment]
Hi, I would like to ask a similar help. So I was working with the header.php and I tried update the sass\theme\_theme.scss file. 

`...
		<header id="wrapper-navbar">
			<div class="top-header">
				<div class="container">
					<div class="row">
						<div class="col-lg-5">
							<a href="/">
								<img src="<?php echo get_template_directory_uri(); ?>/img/logo.png" alt="logo">
							</a>
						</div>
						<div class="col-lg-7">
							<div class="top-header-contact">
								<a href="tel:"><i class="fa fa-phone"></i></a>
								<a href="mailto:"><i class="fa fa-envelope-o"></i> </a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>...`

I wrote these into:

`// This is an empty scss file for your custom styles - Please add your super duper awesome mega design styles here

$primary: #ffBC00;
$primary-500: #dfa503;
$secondary: black;
$secondary-300: #3F3F3F;

.top-header {
    background: black;
}`

But these does not write over the bootstrap. Where should I have to write there?

Thanks for the help. Probably it got updated and these changes were advised for the previous version.
Thanks
