### ISSUE TITLE
Custom CSS being overwritten

### ISSUE THREAD

**Issue by LeRattus** [understrap/understrap#1017]
- [X ] a Question
  - [X ] I need help
##issue overview
When installing my theme to Wordpress, my styles that I have written to theme.min.css disappear. When checking from SiteGround filemanager all my inputs have been overwritten. Even if I afterwards upload just the theme.min.css my code will be overwritten and disappear from the file . Once uploaded if I go and edit theme.min.css (with SiteGround filemanager) my code stays in the file and my css works on the site. (Now this a problem as if someone in the future changes something in the theme and has to be reuploaded --> all the styling disappears and probably nobody will have any idea why and no way to restore them).

With Linux Mint19 using XAMPP the theme.min.css file stays untouched and works without a problem when reuploading the theme.

So is this a problem related to SiteGround Hosting and Wordpress itself or is there something I am missing that overwrites/resets the theme.min.css file once uploaded?

(of course I can just input my styles in Wordpress Additional CSS and it works just fine, but I rather would have it inside the theme file so my clients cant go and mess things up on their own ':D ) 

## Steps to reproduce?
install an Uderstrap Theme to Siteground staging site with modified theme.min.css.

## *When* does this occur?
when installing the theme

## Expected behavior
It should stay untouched and display the webpages css styles.

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** Windows 10 [1903]
  - **Browser:**  all
  - **Language:**  S/CSS

This is my first post so I apologize if my etiquette and formatting is faulty.

**Comment by shikkaba** [comment]
Are you writing directly to that file instead of using SASS?

**Comment by Thomas-A-Reinert** [comment]
Honestly, please understand that I´m not going to get an account on sitepoint to reproduce the problem. especially when it´s not even clear which kind of account you got. On some accounts, it seems that node.js is installed in the server and I´m not able to reproduce in which cases it may get triggered (on upload?) or not.

In fact, that´s in general not the intended use-case for understrap. [Read the docs please](http://usdocu.tarthemes.com/docs/0.8.2/introduction/). These are unofficial and in some cases maybe already outdated but it´s the best you´ll be able to find about any documentation on Understrap.

In short: _you shouldn´t write anything at all **EVER**_ manually to theme.min.css (especially not to style.css in the root-dir, but that´s a different topic) - the intended way to handle that is to write any overwrites into the supplied scss-files in ./understrap/sass/theme/_theme.scss - and let gulp do the job to compile that to .css / .min.css in ./understrap/css .

In case you don´t know anything about SCSS/Gulp etc. - well yes, the easiest way then would be to use the css editor in the customizer. I won´t go into detail which disadvantages that may have over customizing your own bootstrap environment.

Please also take into account that it MAY be the node Installation on your Siteground that may recompile any SCSS (which you didn´t touch and therefore will compile back stock CSS), causing your adjustments to magically disappear.

Don´t take it personal - but that´s the first time I hear about such a thing and therefore going to close that issue.
