### ISSUE TITLE
/home1/vultusbl/public_html/wp-includes/class-wp-hook.php on line 286

### ISSUE THREAD

**Issue by rakeshayla** [understrap/understrap#1018]

**Comment by alexbogias** [comment]
Try upgrading your PHP version

**Comment by 0dp** [comment]
You posted this on wordpress.stackexchange.com
The answer is the same. You do not provide any code for us to see.

This probably not a understrap problem, but a problem with your plugin.

What is `et_tabs_admin` ?

**Comment by IanDelMar** [comment]
@UnderstrapFramework can be closed.
