### ISSUE TITLE
WC Product Gallery – image display problems within the Lightbox

### ISSUE THREAD

**Issue by S8creative** [understrap/understrap#1019]
## Environment
  - **WordPress Version:** 5.2
  - **OS Version:** MacOS 10.13.6 | iOS 11.4.1
  - **Browser:** Chrome 75.0.3770.142
Jupiter X  1.3.0
Jupiter X  1.0 Child theme
Elementor Pro  2.6.0 

---

# Issue Overview for Bugreports
I have a site to sell a single product, so I have created a shop page using WooCommerce, and I have **issues with how the images are being displayed when I use the zoom in the Lightbox mode. (the images are distorted!)**

## Steps to reproduce?
When you click on one image in the Product Gallery, it automatically opens the Lightbox.
Then you have the magnifier icon, to zoom in even more on the pictures.
IF the window is large enough, all works fine.. but IF the window is too small (for example on a 13 inch laptop), the image is distorted, shrunk horizontally.

On a smart phone (tested on IOS), the same sort of things happens.
In the Lightbox, when you zoom in on the images (using your fingers), the image gets shrunken to fit in only 1/4 of the screen width.

## Screenshots / Video
See attached!

# Todos
Does anyone have an idea on how to fix this issue?
I have 2 suggestions :
**1) Easiest would be to disable the zoom option WITHIN the Lightbox.**
Or
**2) Apply a CSS style to that particular photo gallery element, and set the max-width to "auto".
This "fix" seems to be working in development mode in Chrome, but I can't seem the find a way to add it in my custom CSS in my theme.**

![iphone-same-error](https://user-images.githubusercontent.com/47318151/62057102-4140b200-b21f-11e9-9eb7-437a0f53c106.PNG)
<img width="862" alt="mac-image is distorted whn zoomed in" src="https://user-images.githubusercontent.com/47318151/62057103-4140b200-b21f-11e9-9ec6-d47079e58e50.png">

**Comment by Thomas-A-Reinert** [comment]
If the problem remains, please feel free to re-open that issue. As there has been no bounce up for about five month I guess that issue got resolved.
