### ISSUE TITLE
Watch-bs task - async completion error

### ISSUE THREAD

**Issue by phoshenwen** [understrap/understrap#1022]
## Issue is about..
  - [X] a Bug Report
## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** [Windows 10]
  - **Browser:** [ all ]
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [V 10.15.3] | NPM [V 6.9.1-next.0]

---

# Issue Overview for Bugreports

## Steps to reproduce?
Fresh install of Understrap in VVV. When executing gulp watch-bs, I get the following error:

> [09:16:07] Using gulpfile Z:\...\test\gulpfile.js
> [09:16:07] Starting 'watch-bs'...
> [09:16:07] Starting 'browser-sync'...
> [09:16:07] Starting 'watch'...
> [09:16:10] 'browser-sync' errored after 3.22 s
> [09:16:10] Error: UNKNOWN: unknown error, watch
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
> [09:16:10] 'watch-bs' errored after 3.22 s
> [09:16:10] The following tasks did not complete: watch
> [09:16:10] Did you forget to signal async completion?

## Expected behavior
Start the watch task and use browser-sync

**Comment by chrismb75** [comment]
I ran into a similar issue today on Ubuntu 18.04.

After digging around, this managed to solve it for me and may help you. https://github.com/BrowserSync/browser-sync/issues/224

**Comment by alexbogias** [comment]
Same here but linked issue didnt help :(

**Comment by 0dp** [comment]
Firstly, what version of gulp-cli and local gulp version are you using?
`gulp-v` from within the theme folder.

I don't think this is a browser sync related issue.
Rather it is an issue with one of browser-sync gulp tasks.

Try and modify the watch task like this:
```
gulp.task('watch', function(done) {
	gulp.watch(`${paths.sass}/**/*.scss`, gulp.series('styles'));
	gulp.watch(
		[
			`${paths.dev}/js/**/*.js`,
			'js/**/*.js',
			'!js/theme.js',
			'!js/theme.min.js'
		],
		gulp.series('scripts')
	);

	//Inside the watch task.
	gulp.watch(`${paths.imgsrc}/**`, gulp.series('imagemin-watch'));
done();
});```

I haven't tested this, but read from here:
https://www.browsersync.io/docs/gulp

What I think happens is, watch-bs calls watch continuesly, but watch never signals back that it's done.

If this is not the case, the one of the browser sync related task I hanging, because of this.
The fix will most likely always be to signal the task is done with a callback.

It can also simply be because you are not running gulp v. 4x and gulp-cli v.2x

**Comment by phoshenwen** [comment]
@0dp Gulp and Gulp-cli are at their newest versions, respectively.

From the browser-sync docs:

> .init( config, cb )

With the out-of-the-box setup, the browserSync.init function in the gulpfile is receiving `cfg.browserSyncWatchFiles`, and `cfg.browserSyncOptions`. The first is an array, the second an object. The docs say that `init` expects an object as the parameter, and a function as the callback. Could it error because of the mismatch?

**Comment by sol-idsnake** [comment]
Browser-sync.init expects an object as its config. `browserSyncWatchFiles` is an array. See my pull request to [get browser-sync to work](https://github.com/understrap/understrap/pull/1038/files)

**Comment by 0dp** [comment]
@sol-idsnake I will try and verify your pull request

**Comment by 0dp** [comment]
Have any of you tried to signal async completion?

**Comment by sol-idsnake** [comment]
The question is where to include async completion ? The error comes from the watch task, so if I include done as a parameter and callback in the watch task, the error message changes from "did you signal async completion?" to 

`'browser-sync' errored after 3.85 s`
`Error: UNKNOWN: unknown error, watch`
`    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)`
`'watch-bs' errored after 3.86 s`

**Comment by 0dp** [comment]
as a callback function in the task.

I made an example earlier

**Comment by 0dp** [comment]
first up, I am unable to reproduce this issue with a fresh clone of the theme.
for debug info
```
gulp -v
CLI version 2.0.1
Local version 4.0.0
```

Even with signaling async as explained in the BS docs, and exemplified earlier. I get positive results.

So we need to dig a bit deeper.
Could you please output the results of `gulp -v`

**Comment by sol-idsnake** [comment]
CLI version: 2.2.0
Local version: 4.0.2

Fresh out the box I hit yarn install, followed by gulp watch-bs. Same async-completion error

**Comment by 0dp** [comment]
Could you for the sake of debugging try and use npm instead of yarn

**Comment by sol-idsnake** [comment]
Same with npm. I thought it may have to do something with gulp-watch, but the package shows as unused (grayed out by VS Code in gulpfile.js)?!

**Comment by 0dp** [comment]
it's used in the watch task

```
var watch = require('gulp-watch');
...
gulp.watch(`${paths.sass}/**/*.scss`, gulp.series('styles'));
	gulp.watch(
		[
			`${paths.dev}/js/**/*.js`,
			'js/**/*.js',
			'!js/theme.js',
			'!js/theme.min.js'
		],
		gulp.series('scripts')
	);

	//Inside the watch task.
	gulp.watch(`${paths.imgsrc}/**`, gulp.series('imagemin-watch'));
...

```

**Comment by sol-idsnake** [comment]
This is a little off-topic, but I'm guessing you use `gulp-watch` for it's use of chokidar? Gulp 4 already uses chokidar as a standard, so there seems to be no need for the extra package.
Also, if we were to use it I don't think the current implementation you mentioned above my comment uses the package correctly. Correct me if I'm wrong, but there is a difference between `gulp.watch`. and `watch`. The former uses Gulp's native watch event, while watch uses the gulp-watch variable declared in `var watch = ...`. 

Anyway, any other ideas how to make this work?> I have resorted to using livereload, which also doesn't fight with the same caching issues I find with browserSync at times.

**Comment by IanDelMar** [comment]
Have been able to resolve this issue? Have you tried get the watch task to work with one of the more recent versions of the master branch?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @sol-idsnake feel free to reopen it. @UnderstrapFramework please close.

**Comment by IanDelMar** [comment]
@UnderstrapFramework
