### ISSUE TITLE
Accessibility Enhancement: bootstrap navwalker aria-current="page"

### ISSUE THREAD

**Issue by LukaszJaro** [understrap/understrap#1023]
WordPress added this to core in about version 5.1 I believe:

$atts['aria-current'] = $item->current ? 'page' : '';

Reference here: https://developer.wordpress.org/reference/classes/walker_nav_menu/

This allows screen-reader users to know where they are, it's already working on paginate links.

Thanks.

**Comment by Thomas-A-Reinert** [comment]
Thanks for the info, @LukaszJaro : we´ll take this into consideration with any of our next updates! Closing this issue due to housekeeping, though. If the problem remains, please feel free to re-open that issue.
