### ISSUE TITLE
NPM peer dependency errs on install

### ISSUE THREAD

**Issue by markebolden** [understrap/understrap#1026]
NPM peer dependency errs on install
** npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

Any feedback on this?

**Comment by 0dp** [comment]
Please search the issues for related topics. This have been discussed many times.

@Thomas-A-Reinert wanna close this?

**Comment by markebolden** [comment]
@0dp You are right. I found this in another topic a while back and forgot to close. My apologies. Thanks.

**Comment by 0dp** [comment]
No problem @markebolden 👍😀
