### ISSUE TITLE
Adding a sidebar to blog post templates

### ISSUE THREAD

**Issue by EmilyP723** [understrap/understrap#1029]
## Issue is about..
   - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** [ Windows 10] |
  - **Browser:** [ all ]
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

Our site was developed by a freelance developer prior to me coming on to the team and it appears that he hardcoded a lot of unnecessary things to ensure that we have to go back to him for just about everything.

I have basic coding skills, enough to be dangerous and all I want to do is have a sidebar option for our blogs and there are none in the widgets area of the site (just the footer). What is the best way to add these to the blog? There is a page template for the main pages that has a form sidebar option which is ideally what we want. 

Is there a way to duplicate these theme to apply for blog posts?

**Comment by 0dp** [comment]
I believe you can activate sidebars under appearance->customize

**Comment by Thomas-A-Reinert** [comment]
No answer for about 6month, so I´m gonna close that issue. If the problem remains, please feel free to re-open that issue.
