### ISSUE TITLE
Including External Js Plugins

### ISSUE THREAD

**Issue by tetreaultc** [understrap/understrap#1031]
## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **OS Version:** [Windows 10] 
  - **Browser:** [ all ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

I've been trying for many hours to include external plugins like ScrollMagic or SimpleParallax to the Understrap template.  Here is what I did:
- Download the plugin on GitHub
- Drop it in the understrap/src/js/ next to the bootstrap 4 folder

Then I wasn't sure exactly what to do.  I tried:
- Using the npm function to install the nodes
- Linking the file in gulpfile.js after the paths.dev + '/js/custom-javascript.js' line
- Including the js file in the html head using a <script> tag

After all those steps, when I call my functions from custom-javascript.js, it says that it's not defined.  I've looked online and I can't find clear explications on how to include external plugins that might also refer to multiple files.

**Comment by 0dp** [comment]
If you drop the script into ./src/js you do not need to include it in the head of the.

If you want to go with that approach drop the script in the ./js folder and include it in head.

If you want to concatinate and minify the script together with other scripts. Drop the script into ./src/js
In the gulpfile include the script as you did in your description.

From terminal run `gulp scripts` you should be able to verify that it has been compiled by inspecting the is files in ./js or by instantiating the script.

It sounds like you did it right, so maybe make sure paths are correct. That the library you are including is instantiated.

If you're unsure, start with a simple script that just logs something to the console and work from there

**Comment by Thomas-A-Reinert** [comment]
If the problem remains, please feel free to re-open that issue. Closing it due to inactivity. for quite some time
