### ISSUE TITLE
How to give users option to override colors?

### ISSUE THREAD

**Issue by steveo2001** [understrap/understrap#1034]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

I can add additional color fields to the WP Customizer and would like to give users the option to override the primary color and associated styles, is anyone implementing this and how are you doing so? I've looked at using some PHP to str_replace hex codes in theme.min.css, but these are just root styles so don't seem to effect anything? I could add some inline style code but would need to provide every element to be overriden.

**Comment by 0dp** [comment]
I read about a project on css-tricks that enables you to compile parts of scss scripts.
It's experimental and can't remember the name of the project. But go to the site and look for it.

Anyways, this seems to be a little of topic 😉

**Comment by Thomas-A-Reinert** [comment]
Sorry, this is an edge case and not really an UnderStrap problem.
If you get any info on how to solve that - I guess we´d all like to know how that works out ;)

Anyway, as this is NOT an UnderStrap-caused problem, i´d like to close that issue. If the problem remains, please feel free to re-open that issue.
