### ISSUE TITLE
Understrap Version on NPM is not up to date

### ISSUE THREAD

**Issue by felix-berlin** [understrap/understrap#1037]
## Issue is about..
  - [x ] a Question
  - [x ] I need help

---

### Other Comments

Why is the understrap version on npm not up to date?

There is still version 0.9.3 and not 0.9.4.

With v 0.9.3 i get gulp errors 0.9.4 fixed it.

https://www.npmjs.com/package/understrap

**Comment by 0dp** [comment]
We only require that you use `"npm": ">=2.1.8"`
NPM is a globally installed package, and we don't have control over which one you currently have installed on your machine.

With node v10.16.2 npm is v.6.9.0

As, such I am not sure where this version number comes from. Are you refereeing to Gulp versions?

If you believe there is a reason for concerns regarding npm version, please send additional debug info.

**Comment by jchrislemmer** [comment]
I think they're abandoning this project?

Don't see any new commits in the last 3 months.

**Comment by 0dp** [comment]
I can guarantee you it's not abandoned @jchrislemmer 
But it's a free open source project, and we only have our spare time to dedicate to projects like this.

But thanks for raising your concern.

**Comment by felix-berlin** [comment]
Sorry for the late answer. I do not mean the npm version it self i mean the understrap version on nmp.
On npm i only get the older understrap version 0.9.3 and not the newest version 0.9.4.

**Comment by 0dp** [comment]
I have tagged Holger in this issue, so he can make sure it's updated.

In the meantime use the version hosted here for you projects since it's the most up to date

**Comment by jchrislemmer** [comment]
> I can guarantee you it's not abandoned @jchrislemmer
> But it's a free open source project, and we only have our spare time to dedicate to projects like this.
> 
> But thanks for raising your concern.

Thanks for the feedback. I Tweeted you guys a few times and received no feedback. So I assumed the solution was being canned.

Great to hear that it's continuing.

Thanks

**Comment by 0dp** [comment]
It goes as it goes with OS projects. We're just a bunch of happy users who contribute.

The maintainer Holger, also have busy periods so sometimes you know, things love a bit slow

**Comment by Thomas-A-Reinert** [comment]
Yes, that´s true, @felix-berlin, the npm-version ain´t up to date. 
I´m sorry to say, but WE as just CONTRIBUTORS cannot update it. Only the project maintainer is able to do that. I cannot even tell if the version on the WP Listing is up to date. And I don´t give a **** anymore. I´d LOVE to keep both of them up-to-date .. But I can´t.

We´re currently ironing out that problem and hope to find a solution to it asap. No promises being made though.

In your case, I´d stick to this repo – it should reflect the latest changes. NOT the WP-repo, neither the NPM-repo. Sorry for any inconveniences.
