### ISSUE TITLE
How to remove fontawesome from navbar

### ISSUE THREAD

**Issue by sol-idsnake** [understrap/understrap#1046]
I have been unsuccessful in removing the caret-down font-awesome icons from the navbar dropdowns. What is the proper way to dispose of them?

**Comment by 0dp** [comment]
I'm in my phone and can't really give you an exact answer.

But checkout the navwalker file in inc/ folder

**Comment by IanDelMar** [comment]
The "caret-down" does not use Font Awesome. It's just CSS applied to `.dropdown-toggle::after`. Check src/sass/bootstrap4/mixins/_caret.scss. Depending on your needs it might be sufficient to disable the caret via `$enable-caret: false;` in your _theme_variables.scss.

**Comment by Thomas-A-Reinert** [comment]
I guess I can close this issue with about 2month without an answer to a possible solution?
If the problem remains, please feel free to re-open that issue.
