### ISSUE TITLE
Not Working module es6

### ISSUE THREAD

**Issue by RaimonxDev** [understrap/understrap#1047]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ x] a Question
  - [ x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.4.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

Hello,

Good morning, I have a problem when I try to add an external js library, I try to import a library that is "**swiper.js**"

And this is what I do
Step 1
`-npm and swiper -D`
Step 2
I include in the src folder 

> "custom-javascript.js"

Step 3
In my file "custom-javascript.js" I write the following
`import Swiper from 'swiper';`
 and this is already part of my code
var mySwiper = new Swiper ('. swiper-container', {
     direction: 'vertical',
     loop: true,

     // If we need pagination
     pagination: {
       the: '.swiper-pagination',
     },

});
#Step 4
I run 
`gulp-scripts`

#Step 5
I run 
`gulp-watch-bs`

but I get this error in console "**ReferenceError: require is not defined**",
and I don't know why I can fix it, I also tried this "`var Swiper = require ('swiper');`" but it doesn't work either

**Comment by rmleg** [comment]
I found a couple links that I think might be able to point you in the right direction:

- https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined
- https://www.reddit.com/r/javascript/comments/8wrfj3/require_is_not_defined/

I hope that helps.

**Comment by Thomas-A-Reinert** [comment]
Didn´t get any feedback since october so I guess that problem got fixed.
If the problem remains, please feel free to re-open that issue.

**Comment by crisamdegracia** [comment]
Hello, this problem is still unsolved.


import |  export default   - doesnt work.
module.exports | require()  - doesnt work.

but plain Js.
