### ISSUE TITLE
Facebook Shop - Main Product image is being shown twice!

### ISSUE THREAD

**Issue by S8creative** [understrap/understrap#1048]
## Issue is about..
  - [X] a Bug Report
  - [X] I need help

## Please tell us about your environment:
- Bug happens in all environments ; )

## Steps to reproduce?
- Open the Product in the shop, and you'll see the main image shown twice!

## *Who* is the bug affecting?
- Everyone

## *How* do we replicate the issue?
- Visit my shop page on : https://www.facebook.com/AzuigoNow/
(or click here : https://www.facebook.com/pg/AzuigoNow/shop/?ref=page_internal)

- Open the Product in the Shop, and check the thumbnails on the left side.
**--> The main Product image is shown twice, and I'm 100% I uploaded it once.** 
(I double-checked afterwards, as I first thought I made the mistake)

## Screenshots / Video
![screenshot](https://user-images.githubusercontent.com/47318151/67368504-b817ed80-f577-11e9-9b8f-5227fcd57950.jpg)

# Todos
- If someone could point me in the right direction in telling me **how to get rid of this duplicate image**, it would be highly appreciated!!

### Other Comments
**Many thanks for your help !**

**Comment by gaelgerard** [comment]
Hello, the thumbnail only displays 1 and I think it was a Facebook or Woocommerce problem, rather than Understrap.

![image](https://user-images.githubusercontent.com/3606876/67374412-6f653200-f581-11e9-9b3d-0d8e838fb270.png)

**Comment by Thomas-A-Reinert** [comment]
Thanks for your feedback and letting us know. I´ll close this topic then.
Feel free to re-open it if the problem persist, okay?
