### ISSUE TITLE
October 30th framework update?

### ISSUE THREAD

**Issue by theboyk** [understrap/understrap#1053]
## Issue is about..
  - [X] a Question
  - [X] I need help

### Other Comments

Received an email (October 30th, 2019) saying the UnderStrap Theme Framework has been updated.  But it's still showing as version 0.9.4 (which was released at the end of June)?

If there's an update, shouldn't it be showing up as 0.9.5?

Thanks,
Kristin.

**Comment by 0dp** [comment]
I was thinking the same!
As far as I know nothing has been changed!
@holger1411

**Comment by Thomas-A-Reinert** [comment]
Please see #1071
