### ISSUE TITLE
Approved pull requests

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap#1056]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Question

Thanks for approving the pull request for the Woocommerce template update #1055.

I've noticed there are quite a few pull requests that are "Approved" and yet they are still showing as Open.

For the Woocommerce 3.8.0 template update I created a new fork from the UnderStrap parent repo and cloned it locally.  When I view the git log, an earlier pull request I made for the Woocommerce 3.7. 0 update, whilst marked Approved in the pull request "Open" queue is not present in the fresh fork.

Do these "Approved" pull requests still need to be merged?

Cheers,
Noel

**Comment by 0dp** [comment]
I've seen that too, and it's weird. Because try and look up the user who approved it.

**Comment by Thomas-A-Reinert** [comment]
As new commits get approved/declined almost instantly afaik this can only be a bot. Nothing I (does anyone else?) have been informed about before or know anything about its installation, what it does, what it´s good for..

**Comment by 0dp** [comment]
someone must have created @UnderstrapFramework

**Comment by Thomas-A-Reinert** [comment]
This thing is totally going rogue. bhhasdhasdnasodhas daosdoands

**Comment by noelspringer** [comment]
Are you referring to the three merged pull requests from yesterday by @UnderstrapFramework ?

**Comment by 0dp** [comment]
Who is this guy?

**Comment by Thomas-A-Reinert** [comment]
See # #1073

**Comment by Thomas-A-Reinert** [comment]
Please see #1071

**Comment by Thomas-A-Reinert** [comment]
I´d say - let´s settle him down pon the shitstorm that probably got him without prep and see how he works that out.

Sidenote: He made some though to merge any of those open pull requests on friday. Well. it IS friday and yet nothing happend. Let´s give him a week more. And see what happens until then.

@UnderstrapFramework ya listening? Are you receiving this notices at all? Would love to get a YES or NO at least that we know that you´re receiving these notices.

**Comment by UnderstrapFramework** [comment]
I did say the end of Friday, its 8am where I am

I get email notifications when someone mentions me and for threads that I have posted in, but i'm sure thats just standard for Github
