### ISSUE TITLE
Help Request with First Understrap Site Deployment

### ISSUE THREAD

**Issue by armitchell** [understrap/understrap#1059]
Please delete anything that does not apply for you!
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.4
  - **OS Version:** ]MacOS [10.14.6 Mojave] 
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

So, I've just developed my very first site using Understrap/Understrap Child Theme. Now, I'm ready to launch the site (today is the deadline, of course) and, my CSS edits aren't taking effect out on the live server (WP Engine). After searching and searching for a guide to deploy an Understrap-based site, and after reading what threads i could find, I'm thinking it isn't working because of references to my dev URL (localhost:8888/wordpress/understrap). Even when I edit the _child_theme.scss file directly in the Wordpress Admin, th changes/edits don't appear on the front-end - and no, it is not a caching issue, it's because there are steps I need to take to correctly deploy this site that I cannot find a guide to anywhere. :(

Would one of you kind folks please tell me which files need to be edited for live use after having been developed locally and using npm/gulp/browsersync?

By the way, using Understrap has rekindled my love love for web development. I have thoroughly enjoyed working with Understrap. I just need to get it launched today or my boss and the client are gonna kill me.

Here's the link to the site on WP Engine [https://vancedev.wpengine.com]

Thanks in advaance for your help, I truly do appreciate it.

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by noelspringer** [comment]
Where are you seeing the references to your local URL's on your production site?

> Even when I edit the _child_theme.scss file directly in the Wordpress Admin, the changes/edits don't appear on the front-end

If you edit a `*.scss` file, the CSS need to be recompiled for those changes to be added to the CSS file. Locally, there are Gulp watch tasks that can do that. Then you deploy the new CSS file to your production site. How you deploy your updated CSS file will depend on your workflow.

**Comment by armitchell** [comment]
Hi there, and thank you so much for taking time out to help me with this. I've pasted the list of files below that WP Engine say are referencing the local URL.

Now, given that this is literally my first build with Understrap, I have no idea which way is best to go about deploying it to a live server from local. All I know is that I was able to get Gulp running with watch and browsersync and loved working that way versus on a live server.

So far, all I have done is I made a zip file of the site and I exported the database/SQL file. I then uploaded those files to a private folder for WP Engine support and they handled getting the site up and running in an initial state. When I told them that the CSS edits weren't working and that I thought it was probably something to do with Gulp and/or other files referencing the local URL, they then scanned all the site files and sent me the list files that are referencing the local URL.

I've read that you don't even need to include the node_modules folder when you deploy an Understrap site, I've read that you need to do something called a gulp dist, and, no matter where or what I search, I cannot seem to find a real guide for deploying an Understrap-based site.

Could/would you walk me through what I need to do at this stage to get the site running correctly AND, what is the best way to deploy an Undestrap build going forward?

I'm not even sure how to go about recompiling the CSS on the live server when I edit the SCSS file.

Sorry, total rookie in need of help.

**Comment by axlright** [comment]
You shouldn't be referencing your local or remote environment in your development files. How you set up your database is a different matter and the Understrap team can't really help with that as it doesn't have to do with Understrap. It's safe to say that you shouldn't be referencing urls in your production files. You mentioned pasting a list from WP Engine but you didn't include that list...

**Comment by armitchell** [comment]
Hi! Sorry, I totally forgot to paste the list from WPE. See below.

./wp-content/ai1wm-backups/localhost-understrap-wordpress-20191107-190248-113.wpress
./wp-content/themes/understrap-child/gulpconfig.json
./wp-content/themes/understrap-child/sass/theme/understrap-database.sql
./wp-content/themes/understrap-child/footer.php
./wp-content/themes/understrap-child/css/child-theme.min.css
./wp-content/themes/understrap-child/css/child-theme.css.map
./wp-content/themes/understrap-child/css/child-theme.min.css.map
./wp-content/themes/understrap-child/css/child-theme.css
./wp-content/themes/understrap-child/node_modules/parseurl/README.md
./wp-content/themes/understrap/gulpconfig.json
./vance-database.sql
./wp-contentold/ai1wm-backups/localhost-understrap-wordpress-20191107-190248-113.wpress
./wp-contentold/themes/understrap-child/gulpconfig.json
./wp-contentold/themes/understrap-child/sass/theme/understrap-database.sql
./wp-contentold/themes/understrap-child/css/child-theme.css.map
./wp-contentold/themes/understrap-child/node_modules/parseurl/README.md
./wp-contentold/themes/understrap/gulpconfig.json

**Comment by pattonwebz** [comment]
@armitchell I've worked with WPE a lot of times. Ask them to perform a DB search/replace for you, I am shocked that they did not offer that in the first place.

**Comment by armitchell** [comment]
> @armitchell I've worked with WPE a lot of times. Ask them to perform a DB search/replace for you, I am shocked that they did not offer that in the first place.

Yeah, they did a DB search/replace and that took care of the DB. The issue I'm having is that the original local URL is being referenced in the list of files I posted above and, well, I'm a little worried about replacing/editing the local URL references in those files because 1) I'm not sure if they ALL should be replaced with my current WPE dev URL or, 2) should some of them have different URL's than others such as "/" in some, and "https:vancedev.wpengine.com" in others, etc? 

I've built and launched a LOT of sites over the last 5 years but, they were all built on live servers and none in localhost. Also, they were all either Genesis, Beaver Builder, Elementor, or Oxygen builder type sites. This is my very first site using Understrap and I'm a bit paranoid I'll screw something up on this deployment. 

I truly hate to trouble you guys with this deal. I wish there was a really nice guide out there to deploying Understrap sites from local to live so I would A) Learn for myself and B) Not feel like a jerk for troubling you guys with my first deployment of Understrap.

I will say though, I REALLY doubt I'll use anything other than Understrap going forward as development was pure joy and it was SO nice to get back to writing code and cranking out lightweight pages again.

I really appreciate all you guys for popping in and guiding me through this process. I hope like crazy I get this sorted so I can launch this site late tonight.

**Comment by ironicmoka** [comment]
Hi @armitchell,

apart from database references your problem seems to be about having full urls on your theme files. 
That's not an understrap related issue: a theme should never point to urls or it will work on one single domain.

You should serach locally in the files referenced by WP Engine for urls and rewrite using wp functions instead.

for example:
if you referenced your child-teme directory as `www.local.test/wp-content/themes/understrap-child/images/` you can use `<?php echo get_stylesheet_directory_uri(); ?>/images/` and so on.

if you referenced to full urls on your stylesheet you should use relative addresses.
for example:
`www.local.test/wp-content/themes/understrap-child/images/` should be `../images/` (assuming your css file is one directory away from the root, as in `understrap-child/css/`)

You'll find plenty of documentation on WordPress handbook for urls functions:

child theme directory
https://developer.wordpress.org/reference/functions/get_stylesheet_directory_uri/

parent theme directory
https://developer.wordpress.org/reference/functions/get_template_directory_uri/

your website url + directory (is installed in a folder)
https://developer.wordpress.org/reference/functions/site_url/

your website url
https://developer.wordpress.org/reference/functions/get_home_url/

I hope this will help.

**Comment by armitchell** [comment]
Yeah, the URL's in the theme files aren't really the big worry for me at the moment. The thing I'm completely stressed out about is not being able to edit and recompile my SCSS/CSS on the live site. I simply don't know how to recompile the CSS after I edit the _child_theme.scss file on the live site.

I think I can correct the other URL issues but, ho to edit/recompile the CSS on the live site?

**Comment by ironicmoka** [comment]
scss is not supposed to be recompiled on live stage.

Usually the workflow is to make changes on local for work and test, then upload the recompiled css files folder to production only when ready.

**Comment by pattonwebz** [comment]
> I truly hate to trouble you guys with this deal.

It is no trouble, everyone here is volunteering time of their own free will. If we did not want to help we would not have responded :)

Glad to see your making some progress. For WPE they have a nice git push to deploy system. I do Dev work locally (with gulp complex), commit my changes to local repo and then `git push staging master` and a minute later it's live in staging URL :)

**Comment by armitchell** [comment]
> scss is not supposed to be recompiled on live stage.
> 
> Usually the workflow is to make changes on local for work and test, then upload the recompiled css files folder to production only when ready.

So, when the CSS is compiled locally, does that mean it's generating a regular style.css file somewhere that I'm not seeing or don't have because of the way I just zipped the site files up along with the database SQL file and uploaded to WPE for deployment? 

I feel like I've missed an important step along the way with this and I don't know what it is.

As it stands, all I know is that I can't edit _child_theme.scss file or even the normal style.css (as an attempted override experiment) on the live site and have the edits take effect. 

Somewhere along the way, I've not done something I was supposed to and don't know what it is. Well, that's the way it feels anyway.

**Comment by armitchell** [comment]
> > I truly hate to trouble you guys with this deal.
> 
> It is no trouble, everyone here is volunteering time of their own free will. If we did not want to help we would not have responded :)
> 
> Glad to see your making some progress. For WPE they have a nice git push to deploy system. I do Dev work locally (with gulp compiling JS/CSS), commit my changes to local repo and then `git push staging master` and a minute later it's live in staging URL :)

Man, I would LOVE to have you teach me/walk me through getting set up the way your are with local dev/git/WPE. That sounds like a dream setup for dev, especially now that I've gotten a taste of what it's like to build with Understrap. Just wish I could get this deployment business sorted out in my tiny little head.

I'm really glad and very grateful to have you guys helping me learn this process. I just hope I manage to get it launched tonight.

**Comment by ironicmoka** [comment]
gulp on understrap is already set to compile `*.scss` files to the folder `undestrap/css/`, that's where the frontend actually load the css.

For reference: the theme register the css minified file on line 21 of `/inc/enqueue.php`  https://github.com/understrap/understrap/blob/91cba1ccac67b4a519db5db943c3872540a416c7/inc/enqueue.php#L21 . 

So once you compiled these files locally you'll be ready to upload the updated `/css/` content inside the live folder of your theme.

**Another hint**: `style.css` is there just to let know WordPress about theme Theme name, Author and Version, but to avoid server and browser cache you'll find very handy editing that theme version, forcing the browser to re-load the styles.

You'll notice this in the browser dev console: theme version is appended to the css files in order to let them know if an updated version is ready to be loaded.

**Comment by armitchell** [comment]
> gulp on understrap is already set to compile `*.scss` files to the folder `undestrap/css/`, that's where the frontend actually load the css.
> 
> For reference: the theme register the css _minified_ file on line 21 of `/inc/enqueue.php` , so that's what the browser load (not `theme.css` but `theme.min.css`)
> 
> https://github.com/understrap/understrap/blob/91cba1ccac67b4a519db5db943c3872540a416c7/inc/enqueue.php#L21
> 
> .
> So once you compiled these files locally you'll be ready to upload the updated `/css/` content inside the live folder of your theme.
> 
> **Another hint**: `style.css` is there just to let know WordPress about theme Theme name, Author and Version, but to avoid server and browser cache you'll find very handy editing that theme version, forcing the browser to re-load the styles.
> 
> You'll notice this in the browser dev console: theme version is appended to the css files in order to let them know if an updated version is ready to be loaded.

@ironicmoka Your reply has allowed me to start to connect all the dots! NOW I understand how my workflow should be as far as editing the SCSS locally and then pushing my edits out to the server. As I am new to Understrap, I simply didn't know where my compiled css was, as in which folder, or how the files and folders work. Just now, I made some changes to the site locally and then uploaded the child-theme.css and child-theme.min.css files and the changes/edits appeared immediately! :) 

See, I've become programmed to just edit css files in WP Admin and didn't realize the way to go with Understrap is to edit locally and then push to the live server.

Now, I can push ahead in cleaning up the site files that reference the local URL.

Now, my question is how best to handle file paths for images when building out pages locally? What should I put for image fie paths in my css and when I need an inline image in my html?

For example:

.some-class {
   background: url('/wp-content/uploads/11/2019/image_i_need.png');
   }

OR

<div class="another-class"><img src="/wp-content/uploads/11/2019/image_i_need.png"></div>

When developing locally, what's the best way to code those image paths? 

Earlier, you mentioned using <?php echo get_stylesheet_directory_uri(); ?>/images/

How best to do it that way with the way Wordpress does its uploads folders? As in /uploads/11/2019.

**Comment by axlright** [comment]
@armitchell I use a lot of locally hosted fonts and those need to be referenced with a path in the Sass stylesheets in the same way that background image paths do.
To accomplish that, I add a Sass variable with a file path like `$font-path:														"../fonts"; ` and that works great for compiling via Sass. You can then change the path to be the hard coded relative url like `/wp-content/themes/your-child-theme-name/your-directory-in-your-child-theme/fonts/` for instances like using a CDN or if you're adding CriticalCSS into the markup itself and then you just re-compile the Sass and you're done.

**Comment by axlright** [comment]
@armitchell Oh I guess it would be helpful to show how that Sass variable needs to be written so the specified path gets written out properly in the CSS. It's late so I'll just paste the font setup I have and you can hopefully translate for how you'd use it for background images...

```
@font-face {
  font-family: 'proxima-nova';
  font-display: fallback;
  src: url('#{$font-path}/proxima-nova-light.woff2') format('woff2'),
       url('#{$font-path}/proxima-nova-light.woff') format('woff');
  font-weight: 300;
  font-style: normal;
}
```

You'll see there's a specific way the Sass variable needs to be appended to `#{$font-path}` so it'll work. Hope this is helpful for your CSS paths for images
