### ISSUE TITLE
Node_Modules Folder: To upload to live site, or NOT

### ISSUE THREAD

**Issue by armitchell** [understrap/understrap#1065]
Hey guys! So, just wondering if it's even necessary to upload the node_modules folder to the live site when migrating the site from localhost to live server?

Thanks in advance for any help or answers.

**Comment by Thomas-A-Reinert** [comment]
No. DON'T. The server ain't processing them and you gonna upload a shit load of unnecessary stuff. That may even open security leaks. That's what package.json is up for.
To do an installation of all necessary pieces.

**Comment by Thomas-A-Reinert** [comment]
Set up a filter to NOT upload the node_modules folder in your ftp progg

**Comment by armitchell** [comment]
@Thomas-A-Reinert Thank you so much for clarifying this for me. This is my first deployment of Understrap so, I'm just learning the ropes. I'm marking this issue as closed. Cheers!
