### ISSUE TITLE
Is gulp dist supposed to copy gulpfile.js and gulpconfig.json to dist directory?

### ISSUE THREAD

**Issue by rmleg** [understrap/understrap#1066]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.4
  - **OS Version:** MacOS 10.14.6
  - **Node.js & NPM Versions:** Node.js [V 12.12.0] | NPM [V 6.11.3]

---

# Issue Overview for Bugreports
Is the `dist` directory that is created by running the `gulp dist` command supposed to contain `gulpconfig.json` and `gulpfile.js`? It does include those files when I run the command following the steps below, but according to issues #237 and #864, it seems that it should not include those two files.

## Steps to reproduce?
1. `git clone git@github.com:understrap/understrap.git`
2. `cd understrap`
3. `npm install`
4. `gulp dist`
5. View files in new `dist` directory

## *Who* is the bug affecting?
Developers who want to prepare their work for deployment using `gulp dist`.

## *What* is affected by this bug?
The `dist` directory.

## *When* does this occur?
When running the `gulp dist` command.

## *Where* on the platform does it happen?
In the root directory of the UnderStrap theme.

## *How* do we replicate the issue?
Follow the steps in "Steps to reproduce."

## Are there any related Issues and/or PRs?
Issues #237 and #864

## Screenshots / Video
<img width="762" alt="Screen Shot 2019-11-12 at 5 19 07 PM" src="https://user-images.githubusercontent.com/7571219/68715688-91dedf80-0570-11ea-8968-57d7a393a252.png">

## Expected behavior
I don't expect to see `gulpfile.js` and `gulpconfig.json` in the above screenshot.

### Other Comments
Thank you for your help!

**Comment by Thomas-A-Reinert** [comment]
Currently not on my own machine so I cannot really confirm it on my own environtment. But yes, I guess that´s the intended outcome.
There is:
* gulp dist-product
vs 
* gulp dist

Please see the inofficial documentation https://usdocu.tarthemes.com/docs/0.8.2/development/available-gulp-tasks/#gulp-generate-distribution - it´s confirming it.

**Comment by rmleg** [comment]
@Thomas-A-Reinert Thanks, but I read the documentation before opening the issue. From the docs, `gulp dist`:

> Creates a ./dist folder and copies all needed files for distribution as simple theme.
> Does not contain any development files (like ./src, ./sass or ./node_modules).

Gulp files are development files and are not necessary to ship as a simple theme. Therefore it seems like they should not be included, but they are. I don't think that is the expected behavior and is a bug. Would you mind looking into this further?

**Comment by gaelgerard** [comment]
@rmleg I have the same "issue" here. Did you manage to solve yours?

In fact in `Gulpfile.js ` as far as I understand the files and directories begining with a `!`shouldn't be included in the `dist `directory.

But when I run the `gulp dist` command on Windows 10, even the files with `!` are created in the `dist` directory.

`node_modules` and `sass` directory are also created but empty.

```
// Run
// gulp dist
// Copies the files to the /dist folder for distribution as simple theme
gulp.task(
	'dist',
	gulp.series(['clean-dist'], function () {
		return gulp
			.src(
				[
					'**/*',
					`!${paths.bower}`,
					`!${paths.bower}/**`,
					`!${paths.node}`,
					`!${paths.node}/**`,
					`!${paths.dev}`,
					`!${paths.dev}/**`,
					`!${paths.dist}`,
					`!${paths.dist}/**`,
					`!${paths.distprod}`,
					`!${paths.distprod}/**`,
					`!${paths.sass}`,
					`!${paths.sass}/**`,
					'!readme.txt',
					'!readme.md',
					'!package.json',
					'!package-lock.json',
					'!gulpfile.js',
					'!gulpconfig.json',
					'!CHANGELOG.md',
					'!.travis.yml',
					'!jshintignore',
					'!codesniffer.ruleset.xml',
					'*'
```

**Comment by IanDelMar** [comment]
@gaelgerard try this:
```diff
.src(
	[
		'**/*',
-		`!${paths.bower}`,
-		`!${paths.bower}/**`,
		`!${paths.node}`,
		`!${paths.node}/**`,
		`!${paths.dev}`,
		`!${paths.dev}/**`,
		`!${paths.dist}`,
		`!${paths.dist}/**`,
		`!${paths.distprod}`,
		`!${paths.distprod}/**`,
		`!${paths.sass}`,
		`!${paths.sass}/**`,
+		'./vendor',
+		'./vendor/**',
		'!readme.txt',
-		'!readme.md',
+		'!README.md',
		'!package.json',
		'!package-lock.json',
		'!gulpfile.js',
		'!gulpconfig.json',
		'!CHANGELOG.md',
		'!.travis.yml',
		'!jshintignore',
-		'!codesniffer.ruleset.xml',
+		'!phpcs.xml',
-		'*'
+		'!composer.json',
+		'!composer.lock',
	],
	{ buffer: true }
)
```
and in `gulpconfig.json`
```diff
{
	"browserSyncOptions": {
		"proxy": "localhost:8080/",
		"notify": false
	},
	"browserSyncWatchFiles": ["./css/*.min.css", "./js/*.min.js", "./**/*.php"],
	"paths": {
		"js": "./js",
		"css": "./css",
		"img": "./img",
		"imgsrc": "./src/img",
		"sass": "./sass",
-		"node": "./node_modules/",
+		"node": "./node_modules",
-		"bower": "./bower_components/",
		"dev": "./src",
		"dist": "./dist",
		"distprod": "./dist-product",
		"vendor": ""
	}
}

```
But I can't confirm that the `sass` directory in created.

**Comment by gaelgerard** [comment]
Thanks @IanDelMar,

the compressed version works like a charm. None of the previously spoted unnecessary files and directories is copied anymore but only 

>     Creates a ./dist folder and copies all needed files for distribution as simple theme.
>     Does not contain any development files (like ./src, ./sass or ./node_modules).

Sass directory isn't created neither.
