### ISSUE TITLE
Mobile Menu Help - Multi-Level Submenus

### ISSUE THREAD

**Issue by armitchell** [understrap/understrap#1067]
- [x] I need help

Hi guys!
So, I'm having trouble getting multi-level submenus working in my Understrap child theme. They "sort of" work in the sense that if I click and hold a submenu item that has children, then I can see the submenu item's child items. 

I have edited line 192 of the navwalker php file from this:

`if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && $args->depth !== 1 )`

To this:

`if ( isset( $args->has_children ) && $args->has_children && $args->depth !== 3 ) `

And I then added the following CSS to my _child_theme.scss file and recompiled it:

`ul.dropdown-menu li > ul.dropdown-menu{
    left: 100%;
    top: 0;
}
ul.dropdown-menu li:hover > ul.dropdown-menu, ul.dropdown-menu li:focus, > ul.dropdown-menu{
    display: block
}`

The problem is that when I click on the first submenu item to open its submenu (3rd level), it closes the direct parent and the aria of that parent changes from aria-expanded="true" to aria-expanded="false". So, I'm totally lost as to how to fix this behavior so that the 3rd level/grandchild items simply appear when clicking on their 2nd level parents.

I have pasted the link to the site below AND a video showing how it's behaving at the moment. Please note that NO MOBILE DEVELOPMENT has been done on tis site yet. For now i'm just trying to get the mobile menu working correctly. 

In NON-hamburger mode, the menu works fine, just needs some styling tweaks, it's hen it collapses to mobile menu that my 3rd level items go all wonky.

**Link to site:** https://vancedev.wpengine.com/

**LINK TO VIDEO OF MENU BEHAVIOR** - in this video you can see how i have to click ad hold the Motor Accidents link to get its child menu to appear. if I just click on Motor Accidents, the menu collapses and doesn't work the way it should. 

https://www.loom.com/share/3a5ead3a8c3e43fca2f35aaa86defe98

Really need you guys to show me the way so I can get this site site ready for client preview today.

**A ZILLION thanks** in advance for your help! :)

**Comment by armitchell** [comment]
Anyone have a solution to this? Would really like to do this within bootstrap and not have to use some sort of menu plugin if at all possible.

**Comment by Thomas-A-Reinert** [comment]
* Which version of Understrap is your solution build upon?
* Did you revert every CSS to it´s standard that came with the original files?
* Does the problem still persist or may it be due to some changes you made in your HTML/CSS?
* Both links above don´t work.

In general, this seems due to a problem introduced by some custom css. it´s totally possible to have multi-level submenus with understrap.

**Comment by armitchell** [comment]
> * Which version of Understrap is your solution build upon?
> * Did you revert every CSS to it´s standard that came with the original files?
> * Does the problem still persist or may it be due to some changes you made in your HTML/CSS?
> * Both links above don´t work.
> 
> In general, this seems due to a problem introduced by some custom css. it´s totally possible to have multi-level submenus with understrap.

Hi Thomas!
First of all, thank you for your reply. This site is built on the latest version of Understrap/Understrap Child theme. The only changes CSS-wise have been just for font styling and colors. The changes I mentioned above to the nav-walker file are the only more advanced changes I've made and these came from other posts about this same issue I found here and online in other sites.

Really wish I could get the menu to behave on smaller devices when it changes to hamburger menu.

P.S. I updated the links in my original post, they should work now. I appreciate any help you can offer as I truly need to get this menu working today or, Ill have to install a menu plugin such as Ubermenu or MegaMenu.

**Comment by Thomas-A-Reinert** [comment]
Hi @armitchell

1. Can you show the code you were using?
2. The thing you wanted to achieve (screenshot)?
3. A working (or not working live example)?

It´s hard to discover any bugs without delving into the code itself  ;)

**Comment by Thomas-A-Reinert** [comment]
Closing this issue due to no response.
