### ISSUE TITLE
There´s 37 Pull Requests..

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#1071]
@holger1411 @holgerkoenemann @UnderstrapFramework 

Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Suggestion
  - [x] a Question

## Please tell us about your environment:

  - Doesn´t matter for that case.

---

# Issue Overview for Bugreports

## Steps to reproduce?
Take a peep into pull requests...

## *Who* is the bug affecting?
Everyone using Understrap

## *What* is affected by this bug?
The whole projekt

## *When* does this occur?
Like since the last release

## *Where* on the platform does it happen?
No comment. Everywhere.

## *How* do we replicate the issue?
Check pull-requests.

## Are there any related Issues and/or PRs?
Yeap. A LOT. 

## Expected behavior
* Merge anything that proves to be helpful.
* Don´t merge anything untested, without speaking to people who might have already tested and/or commented.

# Todos
MERGE?

**Comment by noelspringer** [comment]
If pull requests for Woocommerce template updates are approved and merged, a new point release for WordPress.org would allow folks with UnderStrap plus Woocommerce to update, thereby fixing the Woocommerce status alert of outdated templates.

**Comment by IanDelMar** [comment]
38

**Comment by Thomas-A-Reinert** [comment]
@noelspringer @IanDelMar @0dp - Sorry to tell, but that project seems to be dead from "our stand". I´ll try to keep you posted til at least on Monday. Got info from holger and some really interesting background info about the new owner etc.

**Comment by Thomas-A-Reinert** [comment]
Hey dear reader,
within this post I´m trying to explain what the status of "Project UnderStrap" actually is.
Please notice that I may be biased but will try to stick to the facts as far as possible.

And in case you´re asking who I am - I belong to the "[Core Contributor team](https://github.com/orgs/understrap/people)" for quite some time now that tried to fulfill all of your requests and also tried to serve you in the issue tracker.

## The situation
* Holger - the original dev behind UnderStrap - has not answered **any** mention or such for about half a year+
* He did not even really react on personal mails
* There´s 36 pull requests and 36 issues open on the main theme. And some of them would really, really solve some problems, but *HEY*
* And it´s another 21 issues on the child theme and 15 pull requests
* About three months ago (~mid september) a new user under the name of "[UnderstrapFramework](https://github.com/UnderstrapFramework)" appeared, that seemed to approve random pull requests and have permissions to do everything possible with this project
* None of the core contribs knew ANYTHING about him, what it´s function is or whatever - honestly I thought it was a bot
* We really tried to get any info about "it" through various mails to the original owner, mentions of the "bot" and whatsoever.
  * And we did not get *one* reply at all from "it" – until a few days ago
  * Try that one, if you need proof: https://github.com/understrap/understrap/issues/1071 . Check it, no answer up to today.

## A short mail from the original owner
As it turns out I received an answer over the weekend from the original owner, Holger, to a last mail in which I tried to get any info about what´s going on.

In short here´s whats in it:
* Holger didn´t do anything with/for UnderStrap in the past six month
* And he won´t find the time pick up on it again so he quit the project and traded it to the new owner. Let´s call him "UnderstrapFramework" from now on

## About "UnderstrapFramework"
* [If you check his/her profile](https://github.com/UnderstrapFramework), you´ll see that it seems like a newly created account
* Please check his/her/its commit history – the only  **commit** you´ll find is an [admin widget](https://github.com/understrap/understrap/commit/ccd1075c89c56edf8cc0b3b0ce172a3038a957cc) that imports a feed from understrap.com
  * Personal opinion: A good amount of what´s posted there is all about [marketing why Understrap is THE Bootstrap WordPress theme](https://understrap.com/blog/how-big-is-understrap/)
    * And trying to convince you to get any of the five commercial child themes available there
    * The "[Bootstrap Theme Finder](https://understrap.com/bootstrap-themes/)" as it´s called somewhere else on the site is bare BS – it lists the commercial child themes for UnderStrap first ..and then some others.
* Five days ago, "UnderstrapFramework" first felt the need to [drop some words](https://github.com/understrap/understrap/pull/1073#issuecomment-562505097).
* As he states "[I'v been overseeing it for just over 3 months now](https://github.com/understrap/understrap/pull/1073#issuecomment-562540191)"

Well let´s round up what has been "overseen" so far in the past three months:
* No introduction, no announcement, nothing comparable
* The only code "*contribution*" so far has been a simple RSS Admin Widget to promote UnderStrap or to be honest - even more the commercial child themes
* 36 pull requests and 36 issues open on the main theme and another 15 pull requests and 21 issues on the child theme
* Since then **three** pull requests have been merged by him if I´m not counting wrong
* **None** of the issues on main and child theme was resolved by him in those past three months 
* There´s two issues on the official [WordPress Theme support forum for UnderStrap](https://wordpress.org/support/theme/understrap/) where he kinda jumped in - but still 3 pages full of unresolved cases

## So what´s my problem with that?
Well, I´ve seen other open source project going down that drain kinda same way:
* Strong focus on commercialization – which I really do not condemn if housekeeping is done right!
  * Quite the contrary: We all need to make a living and if it helps a dev to focus on the project, I´m really cool with that!
* No communication *at all* with the supportive community *in the past three months*
* No focus *at all* on the thing itself – code improvements, merge requests, issues etc. but a *strong* focus on all that marketing knickknack on the blog and website
* No sign of "leadership taken"
* No roadmap we knew about
* No lessons learned in my eyes when we gave him the chance to introduce himself and tell us what his roadmap concerning UnderStrap is

## My personal conclusion

Well, all that ain´t cool for an open-source project in which about a dozen of people partially invested a LOT of time developing, improving and furthermore supporting it.

I personally hate the fact that **nothing** was communicated at all (and we still don´t know much from/about UnderstrapFramework) – even though Holger warned him to **not** ignore the community, like he admitted he had done.

There is no roadmap, there´s no real "game-changers" getting merged (like the WooCommerce updates by @noelspringer , the WCAG improvements by @IanDelMar or even the security updates by @dependabot ). Some of them are "approved" by UnderstrapFramework but that alone won´t merge them..

But the worst thing is that I/we really don´t know where this will lead and if the situation will improve over time. Will the source be getting closed?

Therefore I just forked the master branch (again) as a fallback if everything goes wrong here. There has already been a lil brainstorming with some of "Team UnderStrap" in what direction to take that fork and some of those perspectives seem pretty elaborate. Feel free to join the team and setting up a roadmap about where to take the original "UnderStrap" in the future.

## Posts of interest in this context
* https://github.com/understrap/understrap/pull/1073
* https://github.com/understrap/understrap/issues/1071
* https://github.com/understrap/understrap/issues/1056
* https://github.com/understrap/understrap/issues/1053
* there may be more, but..

**Comment by noelspringer** [comment]
Hey Thomas thanks for the update and your perspective :-D. 

I think the situation is [pretty ordinary](https://www.urbandictionary.com/define.php?term=ordinary) and I share your opinions (and then some!).

Aside from those opinions, the lack of communication and inaction from the current maintainer in merging legitimate and necessary pull requests is ample evidence that UnderStrap is not currently sustainable.

Will your forked repository have an issue queue to allow comments, questions and requests for assistance?

Cheers

**Comment by MatheusMHM** [comment]
Hey guys, I'm Matheus and I have some words about all that is happening.

Long story short, I've been using UnderStrap for about 1 year in the digital marketing agency I work and can't say how much this project saved my time and helped me to understand the Wordpress Themes world with a great environment. I'm a Git/Github newbie, so I still have some problems to contribute to a repository, but with this situation going on here it was a bootstrap for me to start helping all of us and get things done.

@Thomas-A-Reinert, @0dp, and all the people that help this project are awesome.

I'm not an expert developer but I'm an expert in trying stuff. I did a lot of projects with UnderStrap that I need to do some improvements and had a lot of problems that I had to solve alone.

I love working on personal/job projects and I can't wait to be useful for this project, whatever the way it goes, here or in someone's fork.

I hope this project's idea keeps and evolving the theme.

**Comment by 0dp** [comment]
I am more than happy to put some spit and grease into a fork.

While it's normal for FOSS projects to change hands, and to take new directions.
I do feel @holger1411 could have approached this transition with a little more finesse.
That goes double for @UnderstrapFramework 

It's been my pleasure to contribute to UnderStrap and give support to fellow hackers through the years. But to be frank, what happened here grosses me out.

**Comment by pattonwebz** [comment]
Yeah I'm also open to helping out at a fork of that's what people feel is best option here :) 

I'm just here to contribute to open source and help others that I can when time allows me to. Does not matter to me where that is so long as people benefit from the contribution :)

**Comment by theboyk** [comment]
I am wondering if someone could lend some advice? I've used UnderStrap (UnderStrap Child) in a couple projects and I'm wondering how I should deal with this news in terms of supporting those sites going forward? If the project is dead, will I need to completely rebuild these sites using a new base theme? Any advice would be greatly appreciated.

**Comment by Thomas-A-Reinert** [comment]
@theboyk  - the word "dead" may have been a bit harsh from todays point of view. Anyway @UnderstrapFramework still doesn´t share any insights about where he wants to project to go. 

If I was you, I´d say freeze any updates of the main theme - your child should work forever. Until WordPress comes up with something new/deprecates functions etc.
But that could also be the same with an up-to-date parent and an outdated child-theme.

And even more likely with any commercial theme you bought on themeforest if not DIVI, The7 or any other of those..

@pattonwebz thanks for taking a stand to also contribute to a fork. You should already have received an invite. I won´t point out how helpful you´ve been in the past, cos there´s been too many occasions.

@0dp: I´m totally with you. Thanks for joining in. I also have no general resentments in a FOSS-Project changing it´s admins. But I´ve seen some of those projects going down same ways as I said before, being infected with spamware etc and a whole lot of other different cases.
But not reacting to any mentions or whatever in the past three months, where we really needed help/info, is well.. He completely f*cked it up. Sorry to say @UnderstrapFramework - but that´s a fact. Not trying to blame you for anything that´s not true. But THAT can be proved. And it leaves a sick feeling with the most of us who´ve been working with UnderStrap.

@MatheusMHM thanks for dropping in and showing your support! Really, I mean it.
And please don´t be mad at me if I kinda "refuse" your help at that point.

There´s has no real roadmap/commitments etc. been planned out so far. The whole evolution in the past days is totally blowing my mind and capacities right now. So I´d love to stick with the "established community" I know for long to figure out a basic plan at least.

Feel free to "star", follow and comment https://github.com/Thomas-A-Reinert/bootscores (name is just a placeholder, I´ll leave that decision to the community) . I´ll try to contact everyone from there who seems to work with us to work on whatever-repo.


@noelspringer you should´ve received a personal mail already. You should be able to take part / comment in the internal channels of this (yet) hidden repo.

**Comment by Thomas-A-Reinert** [comment]
Just wanted to notice that @UnderstrapFramework currently seems to find into his new "job after some.. "need of help" and "pointing him into the right direction". 

I´m honestly still watching the whole development quite critical, but so far everything seems to work out in the right direction. And I don´t wanna be unforgiving, the contrary is the case.. I just wanted to make sure that this "new leadership" is going into the right direction and not f*cking it up again.

Will add up on that again, IF it happens. So far, i´m confident. Let´s see how that worked out in half a year from today on.

**Comment by UnderstrapFramework** [comment]
As far as im concerned, UnderStrap should continue to be best at what it does and I don't want to change that

Im keeping an eye out and any help along the way is massively appreciated from the community

**Comment by axlright** [comment]
Who is @UnderstrapFramework? Is she / he the only person with permissions to approve PRs? I'm still confused about what is happening to the repo. There's a lot of activity lately into master which is awesome. I'm just out of the loop, which is admittedly almost entirely on me for being myself out of the loop. Has there been an introduction?

**Comment by noelspringer** [comment]
@axlright  https://github.com/understrap/understrap/pull/1073#issuecomment-563968372

**Comment by IanDelMar** [comment]
@UnderstrapFramework the repo completely disappeared from the website. Is there a reason for that?

**Comment by Thomas-A-Reinert** [comment]
@IanDelMar : you mean from the understrap.com website? Well, as far as I would´ve complimented @UnderstrapFramework for following our leads in the past present, he still seems to try to try  commercialize things. Which includes removing the parent from his OverStrap thingie in this case.

I wish he´d contact us FIRST before trying to do so. Or he´ll have a hard time at least twice a week. And a community that will feel pissed more and more and more..

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert yep, that's what I meant.

**Comment by Thomas-A-Reinert** [comment]
First of all - let me wish you a nice Christmas eve!

Well, what shall I say? You´re right.

- Trying to front him again? Because any question into that direction WILL lead into some kinda confrontation anyway.
- He still doesn´t get the full picture. We all WANT to help him. But be it - he still seems to go for anything alone. Which is a REAL pity, because I guess we tried to show HOW helpful we can be over the past weeks. Maybe anyone else than me can TEACH him that we´d really, really LIKE TO HELP. With ANYTHING. Even with him promoting the code  base. Anyway, I guess he won´t listen. @understrap/documentation-team do you? Are you LISTENING? Are you FOLLOWING us?

**Comment by Bruners** [comment]
What is the status now? Is there a new fork that is properly maintained somewhere? @Thomas-A-Reinert

**Comment by Thomas-A-Reinert** [comment]
Well, I keep and maintain my own fork so far. We considered to give understrapframework a chance to get this thing here sorted out somehow.

**Comment by UnderstrapFramework** [comment]
I'm waiting for the go ahead to approve requests as you informed me to do @Thomas-A-Reinert 

Hoping for a release this month onto WordPress.org - let me know if I need to do anything

**Comment by Thomas-A-Reinert** [comment]
I´ll keep a low profile until things concercing "everything understrap" change a lot. Sorry and good luck!

**Comment by UnderstrapFramework** [comment]
I have no idea what you are talking about @Thomas-A-Reinert 

I'm sure its the language barrier

**Comment by pattonwebz** [comment]
@UnderstrapFramework I believe the theme on the .org repo is still under the account of Holger, I don't remember anyone requesting a transfer of the theme on there as normally it's me that handles those transfers in the backend of the wordpress.org site.

If you need to arrange a transfer there the process is usually to ping someone (can ping me directly with the username `williampatton`) in the `theme-review` on the wordpress.org slack instance. Then I request the old owner and the new owner contact me somehow (ideally on slack again or via email) and then I transfer the theme once confirmed on both sides.

**Comment by noelspringer** [comment]
@UnderstrapFramework 

> I have no idea what you are talking about @Thomas-A-Reinert

The facts:
- there are many questions that have been asked of you that have not been answered despite confirmation that notifications are received
- the last pull request was merged on Dec 17th 2019 - 8 weeks ago.
- the last point release `0.9.4` was June 30, 2019
- Woocommerce templates have been out of date since August last year - 6 months, despite that template updates have been merged to master
- there is no roadmap and no response to recommendations for a new branch approach
- the last pull request was on 4th January - 5 weeks ago.

**Comment by noelspringer** [comment]
@pattonwebz I just checked wordpress.org and the theme is listed as "by Alex Booth", though I suppose in the backend it could still be under Holger's account.

**Comment by UnderstrapFramework** [comment]
I control the WordPress.org account yes, after purchase everything was transferred including Twitter etc., thanks @pattonwebz for the offer, if I would have known it worked that way I would have done it like that

Thomas told me not to approve anything until he authorised which I was happy to do.... but now it seems that he has jumped ship so il sort the PR myself ASAP and sort out a new release soon

What questions would people like answered? List away.

In terms of roadmap, I have no plans other than for the US framework to remain working and up to date with any important changes. In my mind the simpler and quicker US is the better - correct me if anybody thinks that wrong though :-)

**Comment by Thomas-A-Reinert** [comment]
Hm, okay, good to see that it doesn´t seem to be language but rather a cognitive barrier..

I vaguely remember saying that I´ll _try_ to approve requests _in case I find the time for that_, but cannot find it anymore. [You don´t refer to this one](https://github.com/understrap/understrap/pull/1088), do you? Anyway, it´s your repo and therefore your responsibility to quality-assure everything. Especially as you´re trying to make a business out of it. At best I offered a helping hand. If the worst comes to the worst, my business/private life has priority over that. The latter became the case as we had a pitch for some large government site.

But to help you out on some issues that I´m – and others are, too – not happy about:

1. Kinda disappointed that nearly everything leading to the open-source and freely available versions of UnderStrap and it´s child got deleted from the homepage. It´s a one-way road all leading into one direction: commercial "OverStrap".

2. UnderStrap is _not_ freely available from your website. [The need to register/leaving an email-address to get it](https://understrap.com/download/), is not an option. At least from my perspective. I don´t even know if that´s legit for FOSS-projects released under the GPL v2. At least it´s a noxious way handling it. But that may be my very own, subjective and sole point of view.

3. _Every_ note concerning it´s [team](https://github.com/orgs/understrap/people) and/or [contributors](https://github.com/understrap/understrap/graphs/contributors) got deleted from the website.
It´s withdrawing any credit to the community that originally built this thing. Which makes the usual John/Jane Doe visiting your site think that you built all that - no chance for anyone to get to Github from there to get his/her own picture.
That´s simple and plain unfair and not playing nice with the community. It´s just not the way you handle communities. Nothing that makes me want to say "_YAY - THAT´s what I wanna work my *** and private time off for!_"

4. According to what a close developer-friend of mine said, any critical comment on your blog will not be published. Criticism is *meh*, right? Even if its on point.

4. Still no updated documentation.
HINT: The [documentation-repo we worked on can be found here](https://github.com/Thomas-A-Reinert/Understrap-Documentation), a [demo for the most recent UnderStrap documentation has been setup here](https://usdocu.tarthemes.com/).
Sidenote: You´ll also find links to the team and contributor pages there. It just shows the respect and some love to the people who deserve it.

**According the / a / your Roadmap:**

1. Statement: To keep UnderStrap "working and up to date" is a minimum requirement for something you want to build a biz upon, ain´t it?
So I guess that´s something your job implies at least.

2. Question / Statement / Task: Define: "simpler and quicker".
It seems that you don´t think it is currently. So where do you see the need for improvements? What could be "simplified"? Where do you see bottlenecks in speed? How do you measure both? How do you want to improve both cases? I guess you must have an idea and/or concept for that, don´t you?
That´s like throwing "_it should be better_" into the room without being able to define where your problem is.

3. Task: Get the documentation up to par with the actual state of the theme.

4. Task: Release N°3.

5. Task: Fix the above mentioned issues in the first part.

6. Task: What´s the status with the [UnderStrap npm-package](https://www.npmjs.com/package/understrap)? It´s one minor version behind and I guess it won´t update magically..

7. Task: Get your hands dirty with some of the real WORK here.

8. Task: Install every single pull request in your dev-environment and heavily test it with [theme unit test](https://codex.wordpress.org/Theme_Unit_Test), [Theme Check](https://wordpress.org/plugins/theme-check/), Security/Vulnerability Scanners, Performance Scanners and others.

9. Task: _Manage_ the community. Deal with some issues. Help users. Once you do that you´ll get into contact with some real-world issues etc and possible improvements.. That will - for sure - get you some inspiration on how to improve your theme. And give recommendations for a roadmap.

10. Task / Suggestion: READ! Every f****g day. EVERYTHING here. Even old and also closed issues. Get up to par with the current status of the theme.
It seems that everything where you don´t get a mention is not really getting your attention. There have been pull requests including questions, suggestions etc. There were some things where improvements would break current child themes. There have been proposals on how to branch out in the future. No replies, no heads up, nothing. You lack overview and a plan. And leadership.

11. Task / Suggestion: COMMUNICATE. I personally get the impression on my end that you only start to do so if things start to burn already. You just don´t send signals, you do not suggest anything on your own. You just seem to hop from one source of fire to the next.

12. Info: I just can confirm what @noelspringer said: The last pull request is bout 5 weeks old. That´s the longest time I know about _without_ any pull request.  And that should send you a signal that even you should understand: People are slowly getting desperate on how this theme evolves. 

13. Personal recommendation:
* Refrain from an overhasty release on Wordpress.org just for having one (as it seems right now to me) unless it´s been really heavily tested (I´d suggest having a Release Candidate here on Github for about two weeks at least and let some other people do some heavy testing on non-live sites)
* Fix the above 12 things first and _then_ get a release with a sustainable _concept_ out.

Hope that´s been enough constructive input for a start.

**Comment by UnderstrapFramework** [comment]
Thanks @Thomas-A-Reinert  for that detailed reply, il hold back on the .org release - people are asking me to push for that due to WooCommerce mainly

Good points and il try to sort them ASAP. I do sit on live chat most of the day on understrap.com helping people with issues and would love to hear from your friend about his criticism if it helps with things for sure

**Comment by axlright** [comment]
@UnderstrapFramework I second a lot of the sentiments shared by @Thomas-A-Reinert 

I don't understand what your plan is, and more than that, I don't understand how you plan to incorporate the community of developers who have been working on this project for years?

Can you answer those two questions directly? What's your plan, and how are you going to incorporate the open source community of contributors?

**Comment by Thomas-A-Reinert** [comment]
@UnderstrapFramework : Well, if the reason for a new WP.org Theme release is just the Woo-Update - go for it. I assume you quality-assured it beforehand. But I´d recommend to NOT just merge every pull request (like you did before) WITHOUT testing and then push a release to WP.org.

May I ask who is asking through which channel? Haven´t seen many of those requests you mention here on Github..

In case you´re really giving support via understrap.com "_most of the day_" I guess you´re doing something terribly wrong. Either you sold a bazillion of your "Overstrap" child themes which I personally do not really believe due to their really questionable quality and redundancy as at least three of them (Overstrap Tech, Corporate and Event) look almost the same. And NONE of them gives any benefit over any of Divi´s, The7´s or whatever already fully included themes.

I guess you could take away some of the support pressure if you´d send people to the github repo, where probably almost every general problem with the base theme already got answered. Get familiar with it and send people to those issues accordingly.

Set up a free base "OverStrap" child theme which shares most of the re-usable stuff (as I said: Most of it is redundant anyway) and set up a repo for it here. So you can send ppl there and handle almost any of the recurring issues there. Setup Ads and whatever within THAT one like hell and make people opt-in for the premium version. Really we, don´t care. That´s your business and I guess we - the community - won´t focus on that. But we _may_ also be willing to improve it a bit here and there.

That´s how _I_ would sell those and get rid of most of the support thingie.

#### \<Offtopic>
"_Questionable Quality_" you say? The choice of colors, gradients, fonts and beating WCAG in the face are _one_ thing. Not even using basic html5 semantic tags (correctly) is another. But well, things are also measurable:

- OverStrap Corporate: 47 (!) validation errors, [48/81 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-corporate%2F&tab=desktop)
- OverStrap Portfolio: 16 validation errors, [68/81 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-portfolio%2F&tab=mobile)
- OverStrap Masonry: 51 (!) validation errors, [65/86 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-masonry%2F&tab=desktop)
- OverStrap Blog: Only (..) 16 validation errors! But just a [56/70 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-blog%2F&tab=desktop) Rank for such a _simple_ site!
- OverStrap Event: Only (..) 23 validation errors, but just a [60/82 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-event%2F&tab=desktop) rank.
- OverStrap Tech: 45 (!) validation errors and a [55/84 Pagespeed](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdemo.hotwpthemes.com%2Foverstrap-tech%2F&tab=desktop) rank.

If I recall correctly you once said that you paid some dev to build those themes? No wonder that you need to give support all day, just checking the base metrics. I  don´t want to know what else is going wrong with those OverStrap thingies...

NOW I really understand why you said that UnderStrap should be "simpler and quicker".
But \*hey\* my personal site - doesn´t really 100% validate too (16 errors), but was a quick shot built within three days including concept and wiring up some ACF-Plugins, does it´s job and most of the validation errors stem from plugins - has a 90/96 Pagespeed score and a 90/91 GTMetrix score. 

Activating my - currently not yet 100% stable - progressive web app plugin would improve that score even more. Something that could even be built-in within a future UnderStrap release.
#### \<\Offtopic>

**What I´d like to know is: _Where do you see yourself within "Project UnderStrap"? And which gap do you think you could fill?_ ** 
- You don´t seem to be able to quality-assure even your own "OverStrap Theme"-derivates as proven above. So I guess you´re no "Frontend-Dev".
- If you were a Backend-Dev I assume you´d be able to tweak servers, performance and whatever. Which doesn´t seem to be the case.
- You don´t seem to have a sustainable plan for the project. Prove me wrong but in case you had one I guess you´d already come up with it and taken over leadership.
(Possible language barrier here, looked that idiom up:)  We need to worm/ferret that out of you each and every time which really, really becomes annoying. And we still got no status at all.
 So I guess you´re no MD (managing director) or at least a project manager as both of them would´ve come up with a PLAN until now.
- Hm... What´s left then: Are you a Marketing Manager?
Well even if ANYTHING so far concerning "marketing" went wrong so far here on github, that´s the only imaginable job for me that you could claim. Being a "marketing manager" doesn´t mean that you´re a social/social media manager (which would be desireable though).
At least you bought the whole thing and had a plan to monetize it. Which is totally okay for me. As long as you don´t forget about the other things above.

I guess almost everyone of the core team [introduced him/herself within the team section](https://github.com/orgs/understrap/teams). With some kinda vita, personal focus and everything. Can´t remember that you joined that party and/or that you posted _anything there_ at all. That _**IS**_ an invitation to do so. You just "took over" and that was it. But that would´ve been the right place to introduce yourself.

Well, that post already took me _far_ too long already. I could´ve done something productive in that time I would´ve get paid for. Or contributed to some other FOSS-Project where ppl would profit from. Or just spent some quality time with my empress. I hope that you´ll consider that that. It seems that "Project UnderStrap" means something to me. I´m really not trying to blame you for anything because I CAN.

If that means that I be going to be a pain in your ass - that´s okay for me. Either you understand that _fast_ or your "business concept" may probably gonna die soon. We´re all here to help each other. Mainly concerning UnderStrap, but if anyone needs help/input with any personal problem/project, I´m also willing to help.

**Suggestion:** Open up a topic in the teams-area and reply there. You don´t _need_ to discuss all of the above here openly, because it´s mainyl an "inside" concern. But refer to it from here so that anyone following knows. In case you wanna reply openly to my question, I´d even prefer that.

Remember: Some of us have been here for LONG. My first commit (haven´t been comfy with git, guess I fÜcked up a lot) is from March 2016. And learned a LOT here thanks to guys like @noelspringer , @0dp , @ZacharyElkins, @GuerrillaCoder , @axlright , @typeplus, @pattonwebz   and many more from the community! (Sorry if I forgot anyone!).

Well, final notice: I´m still willing to help. But A LOT HAS GOT TO CHANGE. I hope you understood my restraints now. I guess/hope I can speak for the rest of the contributors - as far as I know they feel the same.

**Comment by Thomas-A-Reinert** [comment]
Sidenote: In case you still see a "language problem" - no problem:
As you mentioned correctly, I´m no native english speaker. Even if I got an accredited advanced b2/c1 level degree, managed english Hip-Hop Bands (without BUSINESS but "Street"-Level" degree) for bout 10+ yrs, there are still some flaws and I usually don´t speak englisch everyday. Please correct me! Really: I LOVE to learn languages. No matter if HTML5, PHP, "Oxford english" or whatever.

**Comment by noelspringer** [comment]
@UnderstrapFramework

> I have no plans other than for the US framework to remain working and up to date with any important changes.

Yes we all want that along with UnderStrap being simple and quick. So what would that look like and how would it be achieved? i.e. what are the concrete steps required for that to happen?

> What questions would people like answered? List away.

There are questions that have **already been asked** and awaiting a response and you have been tagged. Start by reading this entire thread and addressing all questions. 

I also second most of the points made by @Thomas-A-Reinert and the one I disagreed with has been subsequently clarified by Thomas. That was point 13. concerning an "overhasty release" and clarified here:

> Well, if the reason for a new WP.org Theme release is just the Woo-Update - go for it. I assume you quality-assured it beforehand. But I´d recommend to NOT just merge every pull request (like you did before) WITHOUT testing.

Also, considering that the version of UnderStrap being distributed from UnderStrap.com **is** the zipped master branch from GitHub, people obtaining that version are already getting all the merges that were completed in December.

So I see three possible courses:

1. Tag the repo in it's current state and release that on WordPress.org. That would bring UnderStrap up to date and yes it would actually be "Woocommerce ready" as stated on the home page of UnderStrap.com.
2. It seems we are at a point where even the most active contributors have hit the pause button. Perhaps this is an opportunity to properly review all the open pull requests and deal with those as required. Then  provide a new point release so those improvements are available to new and existing UnderStrap users.
3. Do both 1. and 2.

Moving forward, @0dp proposed a new branch https://github.com/understrap/understrap/issues/1089#issuecomment-570302012. Presumably a new branch would need to be created by @UnderstrapFramework. @UnderstrapFramework was tagged in a follow up comment. This is a case where a response is needed from Alex.

I would be interested in hearing from other contributors about the proposed new branch and workflow. I think it would make it easier and quicker to manage releases if the master branch is the production branch. But  I'm happy to go with the consensus of course.

**Comment by squidzink** [comment]
**Unsolicited opinion/commentary:**

I've been following this drama as a result of my previous go-to theme dying (FoundationPress). Understrap has been kept in my back pocket in the event Foundation/FoundationPress lost steam, which has happened. I'm a designer/user and not a developer. Just switching frameworks has been a challenge because I lack certain skills basic dev skills. I _need_ the base robot that I can skin. I can't really build it. 

Themes like FoundationPress and Understrap have been that naked robot, perfect for me and others who focus on the customizing the display layer of web sites, rarely going deeper into code than sass and simple php functions. 

If I had better developer chops, I'd be using Sage in a second. But it's methodology and need for real building/integrating of core components like nav walkers hurt my right brain. So I've kept coming back here to see if things have worked out because there are few other options that fit my need – blank design, built-in primary components, sass workflow.

**My takeaways as an observer of everything that has transpired here are these:**

- Beginning to use Understrap from this repo now would be a mistake.  

- I believe the long-term US team, dev community and users (me) would be better served by getting behind your own branch, maybe the one @Thomas-A-Reinert created and quit banging heads against this wall of frustration. 

Of course I say that without having a clue what that really means. Y'all clearly have invested time in this project that I can only imagine. And it isn't appreciated at all by the new admin. 

I'm bummed out that what looked to be one of the best designer friendly Bootstrap WP themes using sass appears to have become a train wreck of uncertainty and appears to be purposely obscured from public view.

I truly hope the crew here rematerializes with the previous vigor.  I'm done coming here with hope for a change in the tide...feels more like an undertow going out to sea.

**Comment by arijuki** [comment]
Already posted this under understrap-child... What is the status here? I am looking for a new starter theme / framework and thought I found what I was looking for... before reading few issue conversations here. Now it does not seem to be a safe choice :-(
