### ISSUE TITLE
How to center logo with navigation links on left and right side?

### ISSUE THREAD

**Issue by jd-graphixworks** [understrap/understrap#1077]
#172 Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.0
  - **OS Version:** MacOS Mojave
  - **Browser:** all
---

Our designer has made a mockup that has links to the left and right of a centered logo. See picture below:

![split-nav](https://user-images.githubusercontent.com/58039954/70336547-53f37500-1817-11ea-9c38-0a45a58db485.jpg)

Is there a way to easily do this in Understrap?

**Comment by joshtankpr** [comment]
@jd-graphixworks 

There are two ways I can think to do this:

1. Have two seperate menus in the backend and then pull each menu seperately in their own containers with the logo in the middle.
2. Use something like nth-of-type to hide the contents of the 6th menu item (or which ever you need it to be) and use a ":before" psudeo selector with the logo as the new content.

Image provided is option 2 that I've done on another website. For mobile just don't apply the styling using a media query and then load a seperate logo.

![preview-menu](https://user-images.githubusercontent.com/52045093/70432390-11c86e80-1a77-11ea-85bb-018417a17085.png)

**Comment by jd-graphixworks** [comment]
Awesome! Thanks @joshtankpr,

I like option #1. Is there a way I can create two separate menus within Understrap? I'm assuming somehow in functions.php, I've never done it before.

**Comment by joshtankpr** [comment]
No worries.

Again there are multiple ways to do this:
1. Easiest (but no dyanmic) edit the header.php file in your theme (or parent if you are using child) and remove the mention of "<?php wp_nav_menu ?>" then manually code it all in with hard-coded values. This would work fine if you don't plan on changing the navigation.

2. Create two menus in Apperance - Menus then reference each one seperately using the "wp_nav_menu" function - https://developer.wordpress.org/reference/functions/wp_nav_menu/
This will let you have two dynamic navigations and both will be self contained in their own respective menus. 

3. Make a single menu then pull it into an array and then split the array across the two containers. This would allow for a single dyanmic menu.

There are likely more ways but theser are the best ones I can think off the top of my head. Also it will depend on your developers skill level. But could be a nice little experiment to see what works and what doesn't.

**Comment by axlright** [comment]
I've wanted to do this for a long time but it seemed pretty hard to pull
off. Getting the dropdown menu to work showing two different menus as one
seemed tough. The way I've seen this done on other websites is using a
separate mobile menu in addition to the two (left and right) desktop menus.
I'm not a fan of all that markup!

-Alex


[image: Alex Wright Web Design and SEO]
<https://alexwright.net/?utm_source=gmail&utm_medium=email&utm_campaign=signature>

ALEX WRIGHT
WEB + SEO + DIGITAL MARKETING
ALEXWRIGHT.NET
<https://alexwright.net/?utm_source=gmail&utm_medium=email&utm_campaign=signature>
   (512) 387-2394 <15123872394>

**Comment by Thomas-A-Reinert** [comment]
@axlright – it´s actually pretty simple. Yes, you gotta know you to set up and include a second menu, but the rest is just pure bootstrap stuff.

- Make the first/left menu your "main menu" that contains ALL the links for mobile and desktop.
- Set up a second menu to show up on the right that will completely be hidden on mobile.
- Set up your links that will be hidden on the main menu on md/lg/whatever+ to "hidden-lg-up" or whatever suits your case.
- do it the other way around on the "right" menu - set css class of any link that should not be visible in that viewport to "hidden-md-down" or accordingly to your prefs.

That should:
1. make any "invisible" link (no matter if on desktop or mobile) also invisible for WCAG purposes  (not confirmed yet, need to really deeply inspect that somewhen)
2. that should leave you with two menus which is totally fine.
2. it works ;)

You can see a working example on the https://www.oakbeardcare.com/ page I did some time ago. Feel free to ask if anything there is not really clear.

Downsides:
1. Yes, you´ll have a BIT more code, but that´s totally acceptable.
2. In case you´ll take a deeper look into my solution you´ll see that I replicate both menues for the purpose of the sticky menu. Didn´t find a more elegant solution. But for the basic request mentioned above - that´s bloat and not neccessary.

Sidenote:
Another solution just came to my mind - with the https://developer.wordpress.org/reference/functions/wp_is_mobile/ function it should be possible to echo any menu just for the device demanding it. More code for the php stuff, less that will get delivered to your clients. Just don´t know how reliable that function is and how it decides what´s "mobile" and what´s not. Need to figure that out before delivering a (stable) working example.

**Comment by Thomas-A-Reinert** [comment]
@jd-graphixworks was that understandable and did it work out for you? If not, please just holla back. I´m really willing to help.

**Comment by jd-graphixworks** [comment]
@Thomas-A-Reinert I ended up making three menus:

- Menu (Left, Desktop)
- Menu (Right, Desktop)
- Full Menu (mobile)

It worked out, however on mobile, the menu doesn't trigger upon when I click the hamburger menu. 

Here's the code below:

`
		<div class="sticky-top">
			<nav class="navbar navbar-expand-lg navbar-dark hide-tablet-sm-down desktop-nav">

			<?php if ( 'container' == $container ) : ?>
				<div class="container">
			<?php endif; ?>

					<div class="row flex-it">
						<div class="col-lg-4">
							<?php wp_nav_menu(
									array(
										'theme_location'  => 'menu-left',
										'container_class' => '',
										'container_id'    => '',
										'menu_class'      => 'navbar-nav',
										'fallback_cb'     => '',
										'menu_id'         => 'main-menu',
										'depth'           => 2,
										'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
									)
								); ?>
						</div>
						<div class="col-lg-4 logo-col">
							<img class="logo" src="<?php bloginfo('template_url'); ?>/img/logo.png" alt="Totem Point Logo" />
						</div>
						<div class="col-lg-4">
						<?php wp_nav_menu(
									array(
										'theme_location'  => 'menu-right',
										'container_class' => '',
										'container_id'    => '',
										'menu_class'      => 'navbar-nav',
										'fallback_cb'     => '',
										'menu_id'         => 'main-menu',
										'depth'           => 2,
										'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
									)
								); ?>
						</div>
					</div>

					

					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="<?php esc_attr_e( 'Toggle navigation', 'understrap' ); ?>">
						<span class="navbar-toggler-icon"></span>
					</button>

				<?php if ( 'container' == $container ) : ?>
				</div>
				<?php endif; ?>

			</nav>
		</div>

		

		<nav class="navbar navbar-expand-lg navbar-dark hide-tablet-sm-up">

		<?php if ( 'container' == $container ) : ?>
			<div class="container-fluid">
		<?php endif; ?>

					
					<?php if ( ! has_custom_logo() ) { ?>

						<?php if ( is_front_page() && is_home() ) : ?>

							<h1 class="navbar-brand mb-0"><a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" itemprop="url"><?php bloginfo( 'name' ); ?></a></h1>

						<?php else : ?>

							<a class="navbar-brand" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>" itemprop="url"><?php bloginfo( 'name' ); ?></a>

						<?php endif; ?>


					<?php } else {
						the_custom_logo();
					} ?>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="<?php esc_attr_e( 'Toggle navigation', 'understrap' ); ?>">
					<span class="navbar-toggler-icon"></span>
				</button>

				
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav ml-auto',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'depth'           => 2,
						'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
					)
				); ?>
			<?php if ( 'container' == $container ) : ?>
			</div>
			<?php endif; ?>

		</nav>`

**Comment by axlright** [comment]
@Thomas-A-Reinert Thanks for detailing your solution - that's well thought out. I'll keep that in my war chest the next time a client requests it. I'm kind of a nerd in terms of not liking hidden markup, but sometimes the benefits outweigh the costs! Really appreciate the time you spent detailing your solution.

**Comment by Thomas-A-Reinert** [comment]
Hi @jd-graphixworks, just a quick shot, pon inspecting your code..
I see the following code echoed twice:
```HTML
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>`

But I don´t find a second menu especially none with that ID after the second button. Sure you´re adressing it correctly?

@axlright Yeah, i´ m kinda alike but sometimes there´s no way around it. Especially when you gotta do stuff where you cannot discuss a finished design ..  I´ll try the `wp_is_mobile` thing just for fun when I find the time. Seems smarter to me and would avoid unnecessary code.

**Comment by Thomas-A-Reinert** [comment]
Did you figure out the problem? In case you´re not answering within the next days, I´ll guess you did and gonna close that issue.

**Comment by jd-graphixworks** [comment]
Sorry @Thomas-A-Reinert for the delay!

Just removed that button code within the Desktop menu area, uploaded the files and seems like the hamburger menu still won't trigger :(

**Comment by pattonwebz** [comment]
@jd-graphixworks The target element your button acts on `'#navbarNavDropdown` doesn't exist. You need to swap that to something else that wraps the menu items you want to show/hide.

**Comment by Thomas-A-Reinert** [comment]
Well, there still is no nav-element with the ID "`#navbarNavDropdown`". Are you sure you have any menu that goes by the name of 'primary' (theme_location). I guess not. Please triple check. Would also be helpful to read through:

- https://developer.wordpress.org/reference/functions/wp_nav_menu/
- https://www.templatemonster.com/blog/how-to-build-wordpress-navigation-using-wp_nav_menu/

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert no worries, it's nice that we both independently came to the same conclusion :)

**Comment by jd-graphixworks** [comment]
@Thomas-A-Reinert @pattonwebz 

Ahh thank you guys so much! Turns out I had the old 'primary' menu in header.php being referenced, when in reality I created a new one called 'full-menu'. Swapped out full-menu into where primary was in header.php, and boom! Works!

**Comment by Thomas-A-Reinert** [comment]
No problem, glad it helped ;)

**Comment by fatima-shakeel** [comment]
Can you give me the css of this code you have added of this desktop start ? @jd-graphixworks

**Comment by HumayunE** [comment]
Hi All,
I thought it could help somebody so sharing my idea and how I made it work.
`$firstPart = floor($menuItemCount / 2);`
		`$secPart = $menuItemCount - $firstPart;`
		`$cat1 = $cat2 = $data['categories'];`
		`$data['cat2'] = array_splice($cat1, $firstPart);`
		`$data['cat1'] = array_splice($cat2, 0, $secPart-1);`

and after spliting menu into two arrays for centered logo, I used snippet from bootsnipp.com: [Snippet](https://bootsnipp.com/snippets/d2Zgj)
