### ISSUE TITLE
Themes really shouldn't be adding top level page items

### ISSUE THREAD

**Issue by pattonwebz** [understrap/understrap#1092]
In general top level page items shouldn't be added by themes. You have no options that need it so instead place any info pages as a subpage under the `Appearance` menu. Only have one page and use that page for useful information about the theme.

https://github.com/understrap/understrap/blob/9af15d7b119f5fafb848963281a9297ca2da3d32/inc/wp-admin.php#L83

**Comment by IanDelMar** [comment]
Amen
