### ISSUE TITLE
Don't think it's ok to add dashboard widgets

### ISSUE THREAD

**Issue by pattonwebz** [understrap/understrap#1096]
Dashboard widgets are not something themes really need to add. This one provides no real value to users as far as I can see - it's just a promo item. The users dashboard is not a billboard for advertisements.

https://github.com/understrap/understrap/blob/9af15d7b119f5fafb848963281a9297ca2da3d32/inc/wp-admin.php#L19

**Comment by Thomas-A-Reinert** [comment]
Personally I´d give a thumb up for an admin widget that points to github and a documentation. And in that context _maybe_ even a hint to the commercially available child-themes.
