### ISSUE TITLE
Gutenberg and Understrap

### ISSUE THREAD

**Issue by nvjacobo** [understrap/understrap#1107]
How Understrap will support new options related to Gutenberg at the same time dig deep into new approaches related to it?

**Comment by 0dp** [comment]
Anything specific you are referring to?

**Comment by nvjacobo** [comment]
thanks @0dp 

For example, shortcodes, meta-boxes, and Custom Post Types or Full Site Editing.

**Comment by nvjacobo** [comment]
Interesing resource here: 

initial documentation about the block based themes
https://github.com/WordPress/gutenberg/pull/18890/files

**Comment by Thomas-A-Reinert** [comment]
1. Did you experience any problem with the latter so far?
2. As long as you did not - this is not an ISSUE. And therefore i´m gonna close it.
3. According to my experience everything Gutenberg is supported so far.
