### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by pdmwu** [understrap/understrap#1108]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - Latest
  - Windows 10
  - Chrome Latest
  - Node 12.4 + NPM 6.13.4

---

# Issue Overview for Bugreports
When I clone this repo in as a theme (as admin using Powershell on Win 10), I get this:

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\i110mwu\Desktop\sites\wordpress-docker-compose\wp-app\wp-content\themes\understrap\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\i110mwu\\Desktop\\sites\\wordpress-docker-compose\\wp-app\\wp-content\\themes\\understrap\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\i110mwu\Desktop\sites\wordpress-docker-compose\wp-app\wp-content\themes\understrap\node_modules\node-sass
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back cross-spawn@3.0.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\i110mwu\Desktop\sites\wordpress-docker-compose\wp-app\wp-content\themes\understrap\node_modules\node-sass\node_modules'
npm WARN rollback Rolling back node-pre-gyp@0.12.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\i110mwu\Desktop\sites\wordpress-docker-compose\wp-app\wp-content\themes\understrap\node_modules\fsevents\node_modules'
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myusername\AppData\Roaming\npm-cache\_logs\2020-01-03T11_55_44_217Z-debug.log

I simply cannot install the most basic version of understrap using "npm i".

**Comment by Thomas-A-Reinert** [comment]
See #1075

**Comment by ToNamPhong** [comment]
Delete package-lock.json.
Run npm install
Its working without BUG.

**Comment by pdmwu** [comment]
Thank you @tonamphong - it works the way you describe it.
