### ISSUE TITLE
Understrap 0.9.4 error with RSS feed

### ISSUE THREAD

**Issue by davideo** [understrap/understrap#1110]
Understrap 0.9.4 is throwing the following error. Appears to be related to the RSS feed. 

Need a resolution quickly. Thanks.

David

Error Details
    =============
    An error of type E_ERROR was caused in line 24 of the file /dom29611/wp-content/themes/understrap/inc/wp-admin.php. Error message: Uncaught Error: Call to undefined method WP_Error::get_item_quantity() in /dom29611/wp-content/themes/understrap/inc/wp-admin.php:24
    Stack trace:
    #0 /wordpress-5.3.2/wp-admin/includes/template.php(1343): understrap_news_widget_render('', Array)
    #1 /wordpress-5.3.2/wp-admin/includes/dashboard.php(235): do_meta_boxes(Object(WP_Screen), 'side', '')
    #2 /wordpress-5.3.2/wp-admin/index.php(148): wp_dashboard()
    #3 {main}
      thrown

Please delete anything that does not apply for you!

## Issue is about..
  - [X ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [X ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:**  Linux 
  - **Browser:** all 
  - **Language:**  PHP

**Comment by noelspringer** [comment]
The file `inc/wp-admin.php` is no longer a part of UnderStrap. Just delete it.

**Comment by davideo** [comment]
Thanks, Noel. I just put an empty wp-admin.php in the child theme and that cleared up the issue.
