### ISSUE TITLE
Shortcodes in the_excerpt does not work

### ISSUE THREAD

**Issue by nickmccally** [understrap/understrap#1112]
Please delete anything that does not apply for you!

## Issue is about..
  - [X] a Bug Report
  - [X] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version] ALL
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports
Cannot render shortcode in the_excerpt function
## Steps to reproduce?
Adding shortcode to post and adding `add_filter( 'excerpt_more', 'do_shortcode')` to functions.php. There are no additional plugins on the site. Shortcodes miraculously work in the sidebar widgets, which typically require a filter. Can anyone provide background information as to what could be causing the conflict on the_excerpt?

**Comment by noelspringer** [comment]
@nickmccally have you tested your shortcode in another theme? i.e. is the problem with your shortcode or UnderStrap?

If it's also not working in another theme then you need to troubleshoot your shortcode.

Cheers

**Comment by Thomas-A-Reinert** [comment]
Closed due to no response. Pleae re-open if needed.
