### ISSUE TITLE
I want to hand off the understrap discord server, to a member of the team

### ISSUE THREAD

**Issue by Beaniie** [understrap/understrap#1114]
Could someone point me to the right person for handoff?
https://discord.gg/xARbF3f

**Comment by pattonwebz** [comment]
Hey @Beaniie thanks for reaching out here and thank you for managing the server until now :) 

I believe that @UnderstrapFramework is the person to speak to regarding transfer of the server as they are the repo owner here.

**Comment by UnderstrapFramework** [comment]
Thanks @pattonwebz 

Hello again @Beaniie, iv messaged you on Discord, it looks as though I was a "keymaster" from before
