### ISSUE TITLE
Adding custom font from Typekit

### ISSUE THREAD

**Issue by MannayStudios** [understrap/understrap#1115]
## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:** MacOS [10.14.3]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ PHP | HTML | S/CSS ]

---

I'm trying to add a custom font from Typekit in my Understrap theme. But simply adding the `<link rel="stylesheet" href="https://use.typekit.net/xxxxx.css">` in the header.php doesn't seem to work. I've also tried to add the following in my `enqueue.php` file : `wp_enqueue_style('adobe-fonts', 'https://use.typekit.net/jdm5sse.css', array());` but it doesn't work either.

How do you add custom Typekit fonts in an Understrap theme?

**Comment by 0dp** [comment]
Adding the stylesheet alone is not enough.

You also need to apply the font-family to some classes to work.
It should all be described on the typekit page

**Comment by MannayStudios** [comment]
> Adding the stylesheet alone is not enough.
> 
> You also need to apply the font-family to some classes to work.
> It should all be described on the typekit page

Of course i've already added the `font-family: 'Acumin', sans-serif;` in my theme.scss file, but yet it's not working

**Comment by 0dp** [comment]
Have you checked that the typekit is properly loaded and that nothing is overriding your styles?

**Comment by MannayStudios** [comment]
Allright so that was a big mistake from me, i've added the font using `font-family: 'Acumin'` when i have to use `font-family: acumin-pro`, so the issue had nothing to do with Understrap
