### ISSUE TITLE
upgrade to Bootstrap 4.4.x

### ISSUE THREAD

**Issue by chuckreynolds** [understrap/understrap#1118]
## Issue is about..
  - [X] a Feature Request
  - [X] a Suggestion

## Please tell us about your environment:

  - **WordPress Version:** `5.4-beta1`
  - **OS Version:** ubuntu 18x

---

[Current version of Bootstrap](https://github.com/twbs/bootstrap/releases) is `4.4.1`; looking to get that baked into understrap core. 

EDIT: Just realized there's already a PR for this https://github.com/understrap/understrap/pull/1104

**Comment by IanDelMar** [comment]
@UnderstrapFramework can be closed

**Comment by UnderstrapFramework** [comment]
@IanDelMar thanks
