### ISSUE TITLE
Is understrap ready for Woommerce 3.9 ?

### ISSUE THREAD

**Issue by carlo-13** [understrap/understrap#1120]
Hi everyone.

I was just wondering if Understrap was compatible with Woocommerce 3.9 ?
I saw somewhere that is was working with version 3.7, but is it compatible with the latest version too ?

Thanks.

**Comment by noelspringer** [comment]
The version of UnderStrap at WordPress.org is 0.9.4. That is not up-to-date with Woocommerce 3.9.2.

The master branch of this repository **is** up-to-date with Woocommerce 3.9.2.
If you download the zip file of the master branch from this repository and replace the version of `understrap` in your `wp-content/themes/` directory it will be up-to-date.

https://github.com/understrap/understrap/archive/master.zip

When you download the zip file and unpack it, the directory will be named `understrap-master`. Change the name of the directory to `understrap` and you are good to go.

At some point a new release will be made which incorporates the latest changes and updated at WordPress.org.

**Comment by carlo-13** [comment]
Hi @noelspringer and thank you for your reply.
I will use the version you send then. 😉

**Comment by Thomas-A-Reinert** [comment]
Well, the project maintainer promised to push a new release to the WordPress.org Theme-Repo about 12 days ago, see https://github.com/understrap/understrap/issues/1071#issuecomment-585202569 . Doesn´t seem he did find the time to do so. Or whatever the excuse may be _this_ time.

**Comment by Thomas-A-Reinert** [comment]
Update. 12+15 days == 27 days. Nothing happened.

**Comment by arieltools** [comment]
Well, I find it confusing but it's definitely not a show-stopper for me, as long as I can read proper instructions, as laid down by @noelspringer above.
