### ISSUE TITLE
BrowserSync HTTPS & SourceMaps issue.

### ISSUE THREAD

**Issue by pratham2003** [understrap/understrap#1121]
Please delete anything that does not apply for you!

## Issue is about..
a Bug Report

## Please tell us about your environment:

  - **OS Version:** Ubuntu 18.04
  - **Browser:** [ Chrome 80.0.3987.116 (Official Build) (64-bit) | Firefox developer edition 74.0b5 (64-bit) ]

---

# Issue Overview for Bugreports
CSS SourceMaps are not working in HTTPS

## Steps to reproduce?
- Add `"https": true` to `gulpconfig.json`
- Open https://localhost:3000 (or whichever URL `gulp watch-bs` tells you to open)

## *What* is affected by this bug?
Ability to see SCSS references when using BrowserSync

## *When* does this occur?
When using HTTPS with BrowserSync

## Screenshots / Video
https://i.imgur.com/h4MOORU.png

## Comments
I have tried to load the same site over HTTP and it works. So most likely it is something to do with BrowserSync and HTTPS localhost implementation being considered insecure by the browsers but I'm not 100% sure. Can someone please validate this?

**Comment by noelspringer** [comment]
What is the local url for your WordPress site on which  you have installed UnderStrap?

**Comment by axlright** [comment]
Do you have your SSL certificates specified in `gulpconfig.json`? Something like this:

```
  "browserSyncOptions" : {
    "proxy": "https://local-starter.com",
    "notify": true,
    "https": {
      "key": "/usr/local/etc/apache2/2.4/localhost.key.pem",
      "cert": "/usr/local/etc/apache2/2.4/localhost.crt.pem"
    } 
  },
```

**Comment by pratham2003** [comment]
> What is the local url for your WordPress site on which you have installed UnderStrap?
@noelspringer : example.test which is a self signed certificated issued by my own locally trusted CA (No SSL warnings reported by the browser)

> Do you have your SSL certificates specified in gulpconfig.json?
@axlright : No

**Comment by axlright** [comment]
@pratham2003 I'd try specifying the certificates. Browsersync uses a different URL so specifying the certificate locations may solve the issue.

**Comment by pratham2003** [comment]
@axlright : Which certificates do you mean? The certificates used by the webserver for example.test are issued to example.test, they would not work for localhost..

Here are my observations.
- https://example.test loads in browser without any issues (Browser sees this as a valid SSL cert since I used my own local CA which has been added at the OS level)
- https://localhost:3000 (Browsersync) works but the browser makes me add an exception for the untrusted self-signed certificate (for localhost) .. The web page loads, CSS loads, JS files & image files load. The only problem is that the browser refuses to load the .map files specifying a parse error.

I have tried manually opening the sourcemap over https://localhost and it works.. The content is also the same as https://example.test .. But the browser refuses to load it..

For the time being I have switched back to HTTP as a temporary solution.

**Comment by axlright** [comment]
In order to get browsersync to work with SSL, I had to make a set of certificates for localhost (the domain that browsersyc uses) and specify the location of those certificates as show in the prior message. Browsersync looks for content at the domain you specify but runs it through localhost, so you need to have a set of valid ssl certificates for localhost.

**Comment by noelspringer** [comment]
Are you using a Content Security Policy locally?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @pratham2003 feel free to reopen it. @UnderstrapFramework please close.
