### ISSUE TITLE
Modifying author.php

### ISSUE THREAD

**Issue by sirbene** [understrap/understrap#1122]
Hi there!

This is not an issue but maybe someone can help me with this (I hope it's okay to ask this here).
I need to customize the author.php file. I need the part below only to be visible, if the user has the user role as an admin.

author.php (extract from the default file):
```
<?php if ( ! empty( $curauth->user_url ) || ! empty( $curauth->user_description ) ) : ?>
    <dl>
        <?php if ( ! empty( $curauth->user_url ) ) : ?>
            <dt><?php esc_html_e( 'Website', 'understrap' ); ?></dt>
            <dd>
                <a href="<?php echo esc_url( $curauth->user_url ); ?>"><?php echo esc_html( $curauth->user_url ); ?></a>
            </dd>
        <?php endif; ?>

        <?php if ( ! empty( $curauth->user_description ) ) : ?>
            <dt><?php esc_html_e( 'Profile', 'understrap' ); ?></dt>
            <dd><?php esc_html_e( $curauth->user_description, 'understrap' ); ?></dd>
        <?php endif; ?>
    </dl>
<?php endif; ?>
```
So I've tried this:

```
<?php if(current_user_can('administrator')) { ?>
    <dl>
        <?php if ( ! empty( $curauth->user_url ) ) : ?>
            <dt><?php esc_html_e( 'Website', 'understrap' ); ?></dt>
            <dd>
                <a href="<?php echo esc_url( $curauth->user_url ); ?>"><?php echo esc_html( $curauth->user_url ); ?></a>
            </dd>
        <?php endif; ?>

        <?php if ( ! empty( $curauth->user_description ) ) : ?>
            <dt><?php esc_html_e( 'Profile', 'understrap' ); ?></dt>
            <dd><?php esc_html_e( $curauth->user_description, 'understrap' ); ?></dd>
        <?php endif; ?>
    </dl>
<?php } ?>
```
Unfortunately the condition is not working. How can I fix this?
Thanks in advance!

**Comment by IanDelMar** [comment]
[current_user_can()](https://developer.wordpress.org/reference/functions/current_user_can/) expects a capability as argument. 'administrator' is a [user role](https://wordpress.org/support/article/roles-and-capabilities/#summary-of-roles) not a [user capability](https://wordpress.org/support/article/roles-and-capabilities/#capabilities). Try `current_user_can( 'manage_options' )`.

**Comment by sirbene** [comment]
Thanks. I've tried it like this:

```
<?php if(current_user_can( 'manage_options' )) { ?>
    <dl>
        <?php if ( ! empty( $curauth->user_url ) ) : ?>
            <dt><?php esc_html_e( 'Website', 'understrap' ); ?></dt>
            <dd>
                <a href="<?php echo esc_url( $curauth->user_url ); ?>"><?php echo esc_html( $curauth->user_url ); ?></a>
            </dd>
        <?php endif; ?>

        <?php if ( ! empty( $curauth->user_description ) ) : ?>
            <dt><?php esc_html_e( 'Profile', 'understrap' ); ?></dt>
            <dd><?php esc_html_e( $curauth->user_description, 'understrap' ); ?></dd>
        <?php endif; ?>
    </dl>
<?php } ?>
```
Unfortunately the output still does show up on all user roles. Must be another issue. :/

**Comment by IanDelMar** [comment]
Tested. Can't confirm. The output you are trying to "hide" (the user's website and description) is not shown if the current user is no admin. What exactly are you trying to hide?

**Comment by sirbene** [comment]
Strange. With the same code as above? Even with a fresh understrap-install, it is still not working here.
Yes, I need to hide the whole div / dl-part if the current user is no admin.

**Comment by IanDelMar** [comment]
Yes, copy'n'paste.

Logged in as admin:
![admin](https://user-images.githubusercontent.com/42134098/75198454-f3623d00-5760-11ea-8cc4-35888a30e8d5.png)

Logged in as editor:
![editor](https://user-images.githubusercontent.com/42134098/75198624-653a8680-5761-11ea-8001-7588d392689f.PNG)

Not logged in:
![no-admin](https://user-images.githubusercontent.com/42134098/75198504-18ef4680-5761-11ea-81a6-822fddcd41fe.png)

**Comment by sirbene** [comment]
Thanks for the screenshot. I've described the desired approach wrong, my bad. 
See my edit above:  I need to hide the part, if the author of the post it not an admin. So I guess current_user_can is the wrong approach here (since it doesn't have to do with a logged-in-status).

**Comment by IanDelMar** [comment]
> edit: Maybe this is the mistake: I need to hide the part, if the author of the post it not an admin. So I guess current_user_can is the wrong approach here (?).

Yes, then that's the wrong approach. Try `if( ! user_can( $curauth->ID, 'manage_options' ) )`.

**Comment by sirbene** [comment]
Awesome, it is working now, thank you for helping me! (although this is not theme-related).
closed :)
