### ISSUE TITLE
Why spaces instead of tabs, in the contribution guidelines?

### ISSUE THREAD

**Issue by gillespieza** [understrap/understrap#1125]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x ] a Question
  - [ ] I need help

Can I ask why the contribution guidelines say to use _2 spaces_, instead of tabs, while the WordPress Coding Standards (https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/) prefer you to use real tabs and _not_ spaces? The available PHP Code Sniffer rules for WordPress flag spaces (instead of tabs) as a problem?

**Comment by Thomas-A-Reinert** [comment]
Hi Amanda, would you be so kind to point - at least me - to the contribution standards for UnderStrap in _USE_? Never seen/acknowledged those ever before or have seen them really being used within UnderStrap.

And yes, you´re right: the official WP Codesniffer rules DO only validate against tabs, not spaces.

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert, @gillespieza refers to [CONTRIBUTING.md](https://github.com/understrap/understrap/blob/master/.github/CONTRIBUTING.md).

When I started to use UnderStrap there were a lot of spaces which have been replaced by tabs as time went by. The [.editorconfig](https://github.com/understrap/understrap/blob/41115509cd202c9b31bbbc3a5062e5421195660e/.editorconfig#L14)  states to use tabs. Also, the [Coding Standard](https://github.com/understrap/understrap/blob/master/phpcs.xml)'s rule to use tabs was in force until #1005.
