### ISSUE TITLE
Rudimentary support for progressive web apps? 

### ISSUE THREAD

**Issue by gillespieza** [understrap/understrap#1129]
## Issue is about.
  - [x ] a Suggestion
  - [x ] a Question

Would (rudimentary?) support for PWAs be wanted? I'm about to write an exam for Progressive Web Apps. I'd be happy to add basic PWA support to this framework, if it's wanted? It would be helpful to me as I learn, and I think it might be useful in general for a starter framework. 

The idea would be to just register a service worker, and some offline files, populate a manifest so it would be installable (using the site icon, if registered), etc. 

Of course, there are numerous plugins that already do PWAs on WordPress, so I don't know if this would be needed here?

**Comment by Thomas-A-Reinert** [comment]
Well, I support the idea in general. But as you said, there are already some plugins that do a really good job there.

I hope the project maintainer can give you a satisfying answer concerning UnderStrap although I fear you wont get any at all concerning a project roadmap, general development etc.

**Comment by bacoords** [comment]
This is a cool idea, but personally, I think this is outside the context of what a theme should offer, and sounds more like plugin territory. 

Since it's a few months since this was posted, I'll close it down for now.

**Comment by Thomas-A-Reinert** [comment]
I agree to what @bacoords says. It´s kind of "out of scope" of what a starter theme should include.

But it could easily be achieved activating some plugin (had good experiences so far with https://wordpress.org/plugins/super-progressive-web-apps/ on some client sites) or by creating your own child-theme (this tut may be a good start: https://www.codeinwp.com/blog/progressive-web-apps-on-wordpress-and-woocommerce/ ).
