### ISSUE TITLE
Potentially inconsistent german translation

### ISSUE THREAD

**Issue by anuebel** [understrap/understrap#1130]
I'm new to theme development. Is the following an inconsistency or something i simply not understand yet?

https://github.com/understrap/understrap/blob/41115509cd202c9b31bbbc3a5062e5421195660e/inc/template-tags.php#L31 references a translation for 'Posted on'. However, there is no such translation in e.g. the german translation files (languages/de_DE.po). 

The only translation that is close to this is 'Posted on %s', which is to be used by e.g. sprintf. The same applies to the translation 'by' and its possible translation counterpart 'by %s'.

Is there anything i am missing? Would be great if someone could elaborate on this.

**Comment by IanDelMar** [comment]
Translations have not been updated in a while.

**Comment by Thomas-A-Reinert** [comment]
.. and will never get in case you follow @UnderstrapFramework s update policy... :/

**Comment by danemorgan** [comment]
@Thomas-A-Reinert I'd love to work with you on making German translations happen. I don't know any languages but English, but I suspect I could trust your translation edits and would be happy to get them in the repo.

**Comment by Thomas-A-Reinert** [comment]
Sure. I´ll try to keep this on my radar. Will generate a new german translation file from the code for that and do the translation.

**Comment by Thomas-A-Reinert** [comment]
Ehm. Nope. Got another focus about me sparetime. Hope you get that issue fixed without my help.

**Comment by danemorgan** [comment]
The .pot file *will* be updated in the next stable version ( 1.0.0 ) of the theme, but until we have a translator who knows German and has the time for doing the translation, the translations will remain inconsistent. Closing this until the time comes when we have a volunteer.
