### ISSUE TITLE
Submenu gets cut off in safari

### ISSUE THREAD

**Issue by zebrastribe** [understrap/understrap#1131]
In safari I get cut off of the submenu with the browser is above approx. 2100px
 
![error](https://user-images.githubusercontent.com/6557899/76291853-43d3b180-62ae-11ea-9b71-e3339350f828.png)

## Issue is about..
  - [ X] a Bug Report
  - [X ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.3.2
  - **OS Version:** MacOS [10.13.6]
  - **Browser:** Safari 12.1.1

**Comment by Thomas-A-Reinert** [comment]
Did you make sure that thing gets displayed correctly under Windows, MacOs, Android, iOs, Linux and various browsers?

**Comment by zebrastribe** [comment]
I have tried chrome(win), firefox(win), edge (win) and safari (Mac). And Safari is the only browser that shows the problem. I have Googled to find a solution but with no luck. The closest thing a found is this that it might be something with the popper.js...

**Comment by IanDelMar** [comment]
@zebrastribe Have you been able to resolve the issue? Is it still an issue?

**Comment by zebrastribe** [comment]
> @zebrastribe Have you been able to resolve the issue? Is it still an issue?
It was never fixed. The page is live with the issue.

**Comment by IanDelMar** [comment]
@zebrastribe You could updating Bootstrap to v4.5.3 a shot.

**Comment by zebrastribe** [comment]
Yeah but I am working in an other company now. So I do not have access to the source code anymore... So I guess this bug will remain a mystery 🙂
