### ISSUE TITLE
Page Specific Javascript

### ISSUE THREAD

**Issue by Perdixo** [understrap/understrap#1132]
I'm a little bit losted. How would you go about creating page specific javascript?
I've created custom js files that are all added to my main js file when outputing. What is the workaround to create page specific JS so that it only launches on specific pages?

Meaning let's say you have page 1, page 2, index.js, custom1.js and custom2.js. On page 1, you'd like to have index.js and custom1.js concatenated, on page 2 index.js adn custom2.js etc.

## Issue is about..
  - [ ] a Question
  - [ ] I need help

**Comment by Thomas-A-Reinert** [comment]
Hi @Perdixo - there is no built-in solution available within understrap. You´d need to go with some custom development using something like [require.js](https://requirejs.org/).

**Comment by Perdixo** [comment]
Hey @Thomas-A-Reinert 
Thanks for the answer! That's what i thought, i'll use require then ;)

**Comment by Thomas-A-Reinert** [comment]
No problem, @Perdixo . Glad i could kinda "not" help ;)
