### ISSUE TITLE
Recommended stable Node version for installation on Windows 10

### ISSUE THREAD

**Issue by nizz0k** [understrap/understrap#1136]
- [X ] a Bug Report
  - [X] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.3+
  - **OS Version:** [ Windows 10]
  - **Language:** [  Javascript ]
  - **Node.js & NPM Versions:** Node.js [V 10.16.1] | NPM [V6.9.0]
---

# Issue Overview for Bugreports
Understrap doesn't successfully install with the current LTS Node for Windows. This appears to be an issue with the NaN module in the V8 engine, or that was the last error that I got to. Advice from other users hitting the error was to rollback to version 10.16 at least, which also doesn't seem to work...
## Steps to reproduce?
1) Download and Install Understrap and Understrap-Child.
2) Navigate to root of child folder with terminal.
3) run 'npm install'
4) see verbose terminal output, which fails with the following:
`pm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
## *Who* is the bug affecting?
Windows based themers and developer
## *What* is affected by this bug?
Being able to install assets and node modules
## *When* does this occur?
With installation.
## *Where* on the platform does it happen?
In a projects folder close to the root of the C drive.
## *How* do we replicate the issue?
Attempt to install on a Windows 10 computer.

## Expected behavior
Successful installation

**Comment by nizz0k** [comment]
Solved this by removing the package.lock file.

**Comment by gaelgerard** [comment]
You don't have the latest versions of Node and NPM.

Here install works without error on Windows 10 / Node v12.14.1 / npm v4.13.7

Upgrade Node and npm and it will work for you 2

**Comment by Futurkind** [comment]
I am on Node v12.16.2 and npm 6.14.4 and am getting the same error.

**Comment by gaelgerard** [comment]
Can you provide the full error log because in your question, it says:

`There is likely additional logging output above.`

You also said you had older versions of node and npm. So did you make the upgrade between? Is the message exactly the same?

**Comment by Futurkind** [comment]
@gaelgerard I am not the original poster, and didn't keep track of my log (shame!).
However, I was able to solve the issue by following these steps:
https://github.com/understrap/understrap-child/issues/229#issuecomment-554858596

**Comment by gaelgerard** [comment]
Sorry @Futurkind I didn't check wether it was you who posted the question. I think your answer should help future searchers ;)
