### ISSUE TITLE
Woocommerce 4.0 compatibility

### ISSUE THREAD

**Issue by anonimoconiglio** [understrap/understrap#1138]
Hello, I was wondering if anyone try to run WooCommerce 4.0 (released just few days ago) or if you know it would be compatible with understrap. 
Thanks in advance.

**Comment by noelspringer** [comment]
@anonimoconiglio Are you already using UnderStrap? If yes what version of UnderStrap are  you using?

**Comment by anonimoconiglio** [comment]
@noelspringer yes, actually I'm planning to create a theme from the last `understrap-child` `v0.5.4`, the `understrap` parent theme is at its latest version `0.9.4`.

I have not notice problems so far but my concerns comes from the fact that new woocommerce version has updated some of its templates. Is it safe to copy and update those templates also in the understrap parent theme? Should it enough?

**Comment by noelspringer** [comment]
@anonimoconiglio UnderStrap version v0.9.4 is out of date.

I suggest you download and install the master branch from here. That will cover all template updates up to Woocommerce 3.9.2. 

Then in UnderStrap delete the file `woocommerce/global/quantity-input.php`. This is the only file changed for Woocommerce 4.0.0 compared to the master branch. That file does not provide any Bootstrap display markup except for screen readers and that is already covered by the Woocommerce default class for screen readers.

As usual, confirm by running the Woocommerce > Status check.

Cheers

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
