### ISSUE TITLE
Creating a REAL documentation for UnderStrap

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#114]
This issue is used to plan and document the documentation ;-)  :notebook_with_decorative_cover:

I planning to setup/create a dedicated doc´s page for UnderStrap.
Maybe with GitHub Pages.
Need some help, especially from some native english speaking folks.
And some input what should be in, what needs more explanation, how it should be arranged etc.

Any ideas, help and input is appreciated!

**Comment by Thomas-A-Reinert** [comment]
This may be worth to take a look at: https://github.com/PharkMillups/beautiful-docs#generating-docs

**Comment by typeplus** [comment]
Happy to help with anything I can as an english speaker. Keep in mind not a great coder here but my perspective as a designer / marketing might be useful. Any legwork needed let me know, I will jot down what I think is most important for the guide.

**Comment by holger1411** [comment]
:thumbsup: @typeplus

**Comment by Niki24** [comment]
Awesome project! I am willing to help with documentation as well. Please let me know how I can help.

**Comment by holger1411** [comment]
I setup a GitHub page with some basic doc layout here:
https://github.com/understrap/understrap.github.io
It is just a starting point, but everything else should be discussed there.

**Comment by holger1411** [comment]
Send out invitations to y all

**Comment by Thomas-A-Reinert** [comment]
As we´re currently working on it with high pressure after the release of final Bootstrap4, closing this issue. Feel free to reopen.
