### ISSUE TITLE
Stripe credit card fields in woocommerce not showing properly.

### ISSUE THREAD

**Issue by stefankroesbergen** [understrap/understrap#1141]
Issue is about..
 a Bug Report

Please tell us about your environment:
WordPress Version: 5.3.2
Browser: all
Language: PHP

Issue Overview for Bugreports
Steps to reproduce?
Enable Stripe Payment Gateway in WooCommerce Settings
Go to front-end of website, add an item to cart
Checkout, scroll down to area where Credit Card Details are entered on mobile(!)

Who is the bug affecting?
All users trying to checkout with WooCommerce and Stripe payment gateway.

What is affected by this bug?
Taking Credit Card Payments. The form fields aren't usable so no one can checkout using Stripe as their payment gateway. Screenshot: https://d.pr/free/i/baMSCV

When does this occur?
At Checkout

Where on the platform does it happen?
Enfold/wordpress/Woocommerce/Stripe

How do we replicate the issue?
Enable Stripe Payment Gateway in WooCommerce Settings
Go to front-end of website, add an item to cart
Checkout, scroll down to area where Credit Card Details are entered on mobile(!)

Screenshots / Video
https://d.pr/free/i/baMSCV

Expected behavior
Text inputs should be usable, but is not possible

Solution below does not work

.stripe-card-group,
.woocommerce-account .StripeElement,
.woocommerce-checkout .StripeElement {
width: 100%;
}

**Comment by gaelgerard** [comment]
Here is the SCSS I added to my child-theme in order to correct this bug:

```
/*Formulaire de paiement stripe */
#stripe-payment-data {
        #wc-stripe-cc-form {
                .form-row {
                        display: flex;
                        flex-direction: column;
                        .wc-stripe-elements-field {
                                max-height: 2rem;
                        }
                }
        }
        .woocommerce-SavedPaymentMethods-saveNew {
                display: inherit;
        }
}
```
Hope this will help!

**Comment by jblanco89** [comment]
I'm facing up the same issue right now, I hope this code can be useful! thank you!

**Comment by crotarito** [comment]
same problem... Hope it works, thx!!

**Comment by richardnorthcott** [comment]
Also make sure you have the S in https:// for the URL and that your certificate is valid.
https://stackoverflow.com/questions/65792332/stripe-js-element-disappering-in-woocommerce-checkout/68266717#68266717

**Comment by danemorgan** [comment]
@bacoords did you have a chance to look at this one?

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
