### ISSUE TITLE
Where's the repo for BUILDER?

### ISSUE THREAD

**Issue by mo-g** [understrap/understrap#1144]
There's a PR I need to throw up (it's missing an "echo" on the author page). The readme says it's GPL, but I can't see the host for the source.

**Comment by 0dp** [comment]
Could you try and reformulate, since I don't think it's clear what your are asking, thanks

**Comment by mo-g** [comment]
The open source wordpress theme Understrap-BUILDER, available on the Understrap website and licenced under the GPL, has a bug in it. I'm looking for the repository where the source code for the BUILDER theme is located, so I can create a pull request to fix the bug.

**Comment by 0dp** [comment]
Ohh I see.

Well this guy @UnderstrapFramework 
Has bought this theme from the previous owner and Maude it into some commercial stuff.

The previous owner made some free child themes for understrap. But I don't recall any repos for these.

You best hope is that @UnderstrapFramework sees this and takes action on it.

He is not present here very often. Seems he comes online when you ping him though. So good luck

**Comment by noelspringer** [comment]
There's also this contact form on UnderStrap.com https://understrap.com/contact/

**Comment by IanDelMar** [comment]
@UnderstrapFramework this issue is not related to this repo. Could you answer @mo-g's question and/or close the issue?

**Comment by UnderstrapFramework** [comment]
Thanks @IanDelMar, there is no public repo for BUILDER @mo-g

**Comment by 0dp** [comment]
Nice! SMH
