### ISSUE TITLE
Translation issues on Comments title and template tags Posted on time

### ISSUE THREAD

**Issue by gaelgerard** [understrap/understrap#1145]
Using the latest versions of Understrap and WordPress, some i18n strings are not translated while most of the others are.

My website in french keep displaying not translated english texts for comment title and template tags Posted on time.

I found those strings translated in the Understrap `fr_FR.po` file.

![image](https://user-images.githubusercontent.com/3606876/78673038-dbdeae00-78e1-11ea-9451-c9c20502646b.png)

And I didn't override the template files in my child theme. I still use the parent Understrap original files.
Eg. for comments.php:
```		$comments_number = get_comments_number();
			if ( 1 === (int) $comments_number ) {
				printf(
					/* translators: %s: post title */
					esc_html_x( 'One thought on &ldquo;%s&rdquo;', 'comments title', 'understrap' ),
					'<span>' . get_the_title() . '</span>'
				);
			} else {
				printf( // WPCS: XSS OK.
					/* translators: 1: number of comments, 2: post title */
					esc_html( _nx(
						'%1$s thought on &ldquo;%2$s&rdquo;',
						'%1$s thoughts on &ldquo;%2$s&rdquo;',
						$comments_number,
						'comments title',
						'understrap'
					) ),
					number_format_i18n( $comments_number ),
					'<span>' . get_the_title() . '</span>'
				);
			}
```
Did anyone managed to solve this problem already or am I the only one facing it (on every website I created with Understrap).

What should I check in my server configuration which could cause this issue??

Thanx for the help and the great WordPress theme!

**Comment by IanDelMar** [comment]
The translation files are outdated.

**Comment by gaelgerard** [comment]
I just downloaded the language files in this repo and even switched from my child-theme to Understrap on my test website. But no luck, the strings keep displaying in english.

![image](https://user-images.githubusercontent.com/3606876/79954128-2a14b500-847d-11ea-938b-1d034224379d.png)

**Comment by IanDelMar** [comment]
My PR #813 causes this. It changed `esc_html_x( 'Posted on %s', 'post date', 'understrap' ),` to `esc_html_x( 'Posted on', 'post date', 'understrap' )`. Yes, I have to admit that was not very clever :-D

If you add the translation 'Posted on' -> 'Publié le' (that's the one UnderStrap was using; see [here](https://github.com/understrap/understrap/blob/064e1d4534cf10268e0f9052e70e295fcb186162/languages/fr_FR.po#L214)), it should work again. Alternatively, put the following lines in your child theme's `functions.php`
```php
add_filter( 'understrap_posted_on', 'child_theme_posted_on' );
function child_theme_posted_on() {
	$time_string = '<time class="entry-date published updated" datetime="%1$s">%2$s</time>';
	if ( get_the_time( 'U' ) !== get_the_modified_time( 'U' ) ) {
		$time_string = '<time class="entry-date published" datetime="%1$s">%2$s</time><time class="updated" datetime="%3$s"> (%4$s) </time>';
	}
	$time_string = sprintf(
		$time_string,
		esc_attr( get_the_date( 'c' ) ),
		esc_html( get_the_date() ),
		esc_attr( get_the_modified_date( 'c' ) ),
		esc_html( get_the_modified_date() )
	);
	return sprintf(
		esc_html_x( 'Posted on %s', 'post date', 'understrap' ),
		'<a href="' . esc_url( get_permalink() ) . '" rel="bookmark">' . $time_string . '</a>'
	);
}
```
This is a quick fix but we (actually I) should fix this in UnderStraps's `inc/template-tags.php`.

I hope that works for you.

**Comment by gaelgerard** [comment]
Thanks for the reply and the quick fix but there are a few more strings impacted. 

I was looking to edit the language file but Poedit can't find source in Understrap files so I can't update it.

What do you mean by fixing it in template-tags.php? Reverting to the %s string?

Thanks for your help

**Comment by IanDelMar** [comment]
> Thanks for the reply and the quick fix but there are a few more strings impacted.

Which strings?

> What do you mean by fixing it in template-tags.php? Reverting to the %s string?

Yep.

**Comment by gaelgerard** [comment]
These are the strings which fail being translated: 

The template tags:
```
esc_html_x( 'Posted on', 'post date', 'understrap' ),
esc_html_x( 'by', 'post author', 'understrap' ) : esc_html_x( 'Posted by', 'post author', 'understrap' ),
```
And in comments.php

			if ( 1 === (int) $comments_number ) {
				printf(
					/* translators: %s: post title */
					esc_html_x( 'One thought on &ldquo;%s&rdquo;', 'comments title', 'understrap' ),
					'<span>' . get_the_title() . '</span>'
				);
			} else {
				printf( // WPCS: XSS OK.
					/* translators: 1: number of comments, 2: post title */
					esc_html( _nx(
						'%1$s thought on &ldquo;%2$s&rdquo;',
						'%1$s thoughts on &ldquo;%2$s&rdquo;',
						$comments_number,
						'comments title',
						'understrap'
					) ),
					number_format_i18n( $comments_number ),
					'<span>' . get_the_title() . '</span>'
				);
			}


There is no emergency for me as I already solved it the hard way on my customers websites by replacing with my french translation in overrided files. 

So don't take time to create childtheme function for me, thanks.

I just wanted to find a more sustainable solution.

**Comment by danemorgan** [comment]
@IanDelMar do you have the bandwidth to make this correction?

**Comment by IanDelMar** [comment]
@danemorgan I'm really busy right now. I can have a look at it somewhere from mid to end of July. What's the plan? To adapt the translatable strings to the version which is already translated or to update the po and mo files?

For the comments.php:
In commit 1319eaa57833a58b78187c01ba16662e229d0bae `esc_html_x( 'One thought on &ldquo;%s&rdquo;', 'comments title', 'understrap' ),` was introduced but no translations were added.

So a quick fix would be to strip the if-else clause and only keep the else part, i.e. reducing the if-else statement to
```php
printf(
	esc_html(
		/* translators: 1: number of comments, 2: post title */
		_nx(
			'%1$s thought on &ldquo;%2$s&rdquo;',
			'%1$s thoughts on &ldquo;%2$s&rdquo;',
			$comments_number,
			'comments title',
			'understrap'
		)
	),
	number_format_i18n( $comments_number ), // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	'<span>' . get_the_title() . '</span>'
);
```
then ''One thought on &ldquo;%s&rdquo;" would change to "1 thought on &ldquo;%s&rdquo;" which is already translated. Idk whether there are preferences for "One" over "1".

**Comment by danemorgan** [comment]
July is great @IanDelMar thanks. 

In the mean time, I'll also look into getting the mo and po updated.
