### ISSUE TITLE
Sidebar check does not check for page template

### ISSUE THREAD

**Issue by gillespieza** [understrap/understrap#1146]
## Issue is about..
  - [x ] a Bug Report

The logic in the sidebar templates that set the column width to `.col-md-3` if both sidebars are active, or `.col-md-4` if only one sidebar is active, only checks for the theme option `understrap_sidebar_position`. It does not take into account if a page has explicity chosen the `Left and Right Sidebar Layout` page template (and therefore shows _both_ sidebars as `.col-md-4`.)

**Comment by yansusanto** [comment]
I'm having an issue with this

```
<div class="<?php echo is_active_sidebar( 'right-sidebar' ) ? 'col-md-8' : 'col-md-12'; ?> content-area" id="primary">
```

And I'm not sure why when no sidebar is chosen, the class remains `col-md-8`. Shouldn't it be `col-md-12`? 

I don't think there is anything wrong with the above code, is it not?

Appreciate if anyone could point me in the right direction.

**Comment by danemorgan** [comment]
Hi @yansusanto,

I can only assume you resolved this a long time ago, but just in case, the is_active_sidebar() does not test whether you have "chosen" a sidebar, but whether the sidebar has a widget assigned in it on the dashboard widgets page.
