### ISSUE TITLE
Right Sidebar not visible on Recent Posts Page

### ISSUE THREAD

**Issue by ErikRobles** [understrap/understrap#1150]
## Issue is about.
  - [x ] a Bug Report
 
## Please tell us about your environment:

  - **WordPress Version:** 5.4
  - **OS Version:** [ Windows 10] 
  - **Browser:** [ all | Chrome XX ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 ]

---

# Issue Overview for Bugreports
Understrap calls the right sidebar widget and it takes its rightful place but is not visible on Recent Posts Page but is visible on single post pages.
## Steps to reproduce?
N/A
## *Who* is the bug affecting?
I am having this issue in production as well as in my live site.

## *What* is affected by this bug?
Unable to display recent post sidebar on Recent Posts Page.
## *When* does this occur?
100% consistent error
## *Where* on the platform does it happen?
N/A
## *How* do we replicate the issue?
Unsure
## Are there any related Issues and/or PRs?
Unsure

## Screenshots / Video
![1](https://user-images.githubusercontent.com/30667777/79159802-586c0380-7d9e-11ea-92d1-03be7aaf99d7.PNG)

## Expected behavior
Right sidebar should be visible on Recent Posts page
# Todos

 * Test
 * Documentation

### Other Comments
This is the code in question with my amendments.

```
<?php
/**
 * The main template file
 *
 * This is the most generic template file in a WordPress theme
 * and one of the two required files for a theme (the other being style.css).
 * It is used to display a page when nothing more specific matches a query.
 * E.g., it puts together the home page when no home.php file exists.
 * Learn more: http://codex.wordpress.org/Template_Hierarchy
 *
 * @package understrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

get_header();

$container = get_theme_mod( 'understrap_container_type' );
?>

<?php if ( is_front_page() && is_home() ) : ?>
	<?php get_template_part( 'global-templates/hero' ); ?>
<?php endif; ?>

<div class="wrapper" id="index-wrapper">
<div class="darkness"></div>
	<div class="<?php echo esc_attr( $container ); ?>" id="content" tabindex="-1">

		<div class="row">

			<!-- Do the left sidebar check and opens the primary div -->
			<?php get_template_part( 'global-templates/left-sidebar-check' ); ?>

			<main class="site-main" id="main">
				<h1 class="mb-3 text-uppercase">Recent Posts</h1>
				<?php if ( have_posts() ) : ?>

					<?php /* Start the Loop */ ?>

					<?php while ( have_posts() ) : the_post(); ?>

						<?php

						/*
						 * Include the Post-Format-specific template for the content.
						 * If you want to override this in a child theme, then include a file
						 * called content-___.php (where ___ is the Post Format name) and that will be used instead.
						 */
						get_template_part( 'loop-templates/content', get_post_format() );
						?>

					<?php endwhile; ?>

				<?php else : ?>

					<?php get_template_part( 'loop-templates/content', 'none' ); ?>

				<?php endif; ?>

			</main><!-- #main -->

			<!-- The pagination component -->
			<?php understrap_pagination(); ?>

			<!-- Do the right sidebar check -->
			
			<?php get_template_part( 'global-templates/right-sidebar-check' ); ?>
			

		</div><!-- .row -->

	</div><!-- #content -->

</div><!-- #index-wrapper -->
<?php get_footer();
```

**Comment by IanDelMar** [comment]
@ErikRobles Have made any other changes to theme files? Which widgets should appear in your right sidebar?

**Comment by ErikRobles** [comment]
Thank you for your reply Ian. The only thing I changed is the wrapper in the index.php file. I am calling "Right Sidebar" as specified in the array:
array(
				'name'          => __( 'Right Sidebar', 'understrap' ),
				'id'            => 'right-sidebar',
				'description'   => __( 'Right sidebar widget area', 'understrap' ),
				'before_widget' => '<aside id="%1$s" class="widget %2$s">',
				'after_widget'  => '</aside>',
				'before_title'  => '<h3 class="widget-title">',
				'after_title'   => '</h3>',
			)
I'll keep digging but at the moment, I can't seem to find where the issue might be lurking. Thank you for looking into this. It may very well be a WordPress issue so I will look there as well.

**Comment by IanDelMar** [comment]
Sorry, I can't reproduce the issue. It works setting up the search, the recent posts and the categories widgets via the Customizer.

However, looking at your first screenshot it seems as the `index.php` is doing what is supposed to do.
`<?php get_template_part( 'global-templates/left-sidebar-check' ); ?>` prevents the left sidebar from being rendered. `<?php get_template_part( 'global-templates/right-sidebar-check' ); ?>` makes the right sidebar render. What seems not to work is the `<?php dynamic_sidebar( 'right-sidebar' ); ?>` in [sidebar-templates/sidebar-right.php](https://github.com/understrap/understrap/blob/064e1d4534cf10268e0f9052e70e295fcb186162/sidebar-templates/sidebar-right.php#L24) as no widget is rendered. Have you checked whether you accidentally changed `<?php dynamic_sidebar( 'right-sidebar' ); ?>` to something else?

**Comment by noelspringer** [comment]
@ErikRobles sometimes I find sidebars and width selections in the customizer won't display correctly until I reset them in the customizer. e.g. in the Theme Layout settings switch off the sidebars altogether, publish the changes then switch the right sidebar on again.

If that doesn't work, double check that UnderStrap's original `index.php` file is working to display the sidebar.

**Comment by ErikRobles** [comment]
Thank you for your help looking into this. Yes this was my error, I had forgotten that I had changed the right-sidebar template to only display on single post pages. It was doing exactly as I told it to. My apologies. Next time before Inquiring, I will compare the master file with mine. Closing issue
