### ISSUE TITLE
In Live Preview when deleting logo image then navbar brand become empty

### ISSUE THREAD

**Issue by gentledawn** [understrap/understrap#1154]
## Issue is about..
  - [*] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.4

## Steps to reproduce?
Go to Appearance > Customize
> Site Identity > Select Logo > Select
> Remove
then navbar brand become empty.

## Expected behavior
If logo image removed then the blog title should came back.
For the better user experience.

**Comment by IanDelMar** [comment]
Are you using a child theme? Then put this in your functions.php
```php
function childthemeslug_customize_register( $wp_customize ) {
	if ( $wp_customize->get_control( 'custom_logo' ) ) {
		$wp_customize->get_setting( 'custom_logo' )->transport = 'refresh';
	}
}
```
If you are not using a child theme then add the if statement above to `understrap_customize_register()` in `inc/customizer.php`. It is not recommended to change UnderStrap without using a child theme as the next update (if there ever will be one) then overwrites your changes.

However, also the `js/customizer.js` in fact does nothing, so not even your site title gets updated in the live preview. To fix this place a copy of `js/customizer.js` in your child theme's js folder and replace 
```diff
/**
 * File customizer.js.
 *
 * Theme Customizer enhancements for a better user experience.
 *
 * Contains handlers to make Theme Customizer preview reload changes asynchronously.
 */

( function( $ ) {

	// Site title and description.
	wp.customize( 'blogname', function( value ) {
		value.bind( function( to ) {
-			$( '.site-title a' ).text( to );
+			var nava = $( '.navbar-brand a' );
+			if ( nava.length > 0 ) {
+				nava.text( to );
+			} else {
+				$( '.navbar-brand' ).text( to );
+			}
		} );
	} );
	wp.customize( 'blogdescription', function( value ) {
		value.bind( function( to ) {
			$( '.site-description' ).text( to );
		} );
	} );

	// Header text color.
	wp.customize( 'header_textcolor', function( value ) {
		value.bind( function( to ) {
			if ( 'blank' === to ) {
				$( '.site-title a, .site-description' ).css( {
					'clip': 'rect(1px, 1px, 1px, 1px)',
					'position': 'absolute'
				} );
			} else {
				$( '.site-title a, .site-description' ).css( {
					'clip': 'auto',
					'position': 'relative'
				} );
				$( '.site-title a, .site-description' ).css( {
					'color': to
				} );
			}
		} );
	} );
} )( jQuery );
```
and either put this in your child theme's functions.php
```php
function understrap_customize_preview_js() {
	$js_version = filemtime( get_stylesheet_directory() . '/js/customizer.js' );
	wp_enqueue_script(
		'understrap_customizer',
		get_stylesheet_directory_uri() . '/js/customizer.js',
		array( 'customize-preview' ),
		$js_version,
		true
	);
}
```
or this
```php
remove_action( 'customize_preview_init','understrap_customize_preview_js' );
add_action( 'customize_preview_init','childthemeslug_customize_preview_js' )
function childthemeslug_customize_preview_js() {
	$js_version = filemtime( get_stylesheet_directory() . '/js/customizer.js' );
	wp_enqueue_script(
		'childthemeslug_customizer',
		get_stylesheet_directory_uri() . '/js/customizer.js',
		array( 'customize-preview' ),
		$js_version,
		true
	);
}
```
Again you may directly change UnderStrap's `js/customizer.js` but your changes will be lost on the next theme update. If you do so, look for `understrap_customize_preview_js()` in `inc/customizer.php` and replace the version number ('20130508') with something else to break the cache.

Alternatively, you can wrap (1) `<h1 class="navbar-brand mb-0">...` and (2) `<a class="navbar-brand" ...` in the `header.php` in a container with class `.site-sitle`, i.e. `<div class="site-title">(1) or (2)</div>`. In this case, you do not have to change the `js/customizer.js` to make the site title work in the live preview.
