### ISSUE TITLE
Problem with long non-breaking text in title

### ISSUE THREAD

**Issue by IanDelMar** [understrap/understrap#1157]
Just an edge case but it occurs:

![image](https://user-images.githubusercontent.com/42134098/79947933-2da33e80-8473-11ea-9462-266090449c75.png)

It also occurs after fixing the sidebar and content area width as proposed in #1151.

![image](https://user-images.githubusercontent.com/42134098/79947447-465f2480-8472-11ea-847a-431944af3d9d.png)

**Comment by gaelgerard** [comment]
Not sure it's an Understrap issue or a HTML/CSS default behavior but you can solve this by adding a `word-wrap` directive like this (assuming your title is a `h1`):

```
h1 {
 word-wrap: break-word;
}
```

**Comment by IanDelMar** [comment]
@gaelgerard yeah, but the point is that the theme should take care of that out of the box. I'm currently checking the theme unit test data and will open issues for things that do not pass the test. Others then have the chance to help fixing those issues.

**Comment by gaelgerard** [comment]
Sorry @IanDelMar I didn't see you were the writer of the post. And now I see I made a mistake in my answer because after searching further I find that `word-wrap` property has been renamed in CSS3 with `overflow-wrap` so perhaps it should be best to use this instead.

**Comment by IanDelMar** [comment]
Ah, yeah, you're right about `overflow-wrap`. I will update my proposed fix accordingly.

**Comment by LukaszJaro** [comment]
I ran into same issue, but not only in title, so I added the bootstrap class to catch all potential cases:

`<body <?php body_class( 'text-break' ); ?>>`

Tested and seems to have worked out for me..

**Comment by gentledawn** [comment]
> I ran into same issue, but not only in title, so I added the bootstrap class to catch all potential cases:
> 
> `<body <?php body_class( 'text-break' ); ?>>`
> 
> Tested and seems to have worked out for me..

I agree with this. This will solve all long non-breaking text everywhere rather than just in the headings.

**Comment by LukaszJaro** [comment]
The current version of bootstrap in the theme doesn't have a proper IE11 fallback for text wrapping, bootstrap v4.4.2 fixes the issue adding `word-wrap: break word` to the `.text-break` utility class

https://github.com/twbs/bootstrap/pull/29325

**Comment by IanDelMar** [comment]
@LukaszJaro `bootstrap/scss/utilities/_text.scss` line 65-68 (v4.4.1)
```css
.text-break {
  word-break: break-word !important; // IE & < Edge 18
  overflow-wrap: break-word !important;
}
```

However, I'm not convinced to add `text-break` as a body class to capture headings.

@gentledawn which tags have you found to be affected? I'd prefer the `bood_class` hook to add classes to the `<body>` tag.
```php
add_filter( 'body_class', 'themeslug_body_class' );
function themeslug_body_class( $classes ) {
	$classes[] = 'text-break';
	return $classes;
}
```
But that's just my preference.

**Comment by IanDelMar** [comment]
> @LukaszJaro `bootstrap/scss/utilities/_text.scss` line 65-68 (v4.4.1)

Ah, sorry, there it is `word-break` not `word-wrap`.

**Comment by gentledawn** [comment]
If there is/are long non-breaking text(s) in a title and/or post content, problem will happen in these parts:
- Post/page title
- Widgets (latest posts and pages widget)
- Post/page content if viewed on small screen devices
- Menu (of pages).
Therefore, putting 'text-break' on body tag is preferable.
And about the method, I think your method is preferable.

**Comment by Thomas-A-Reinert** [comment]
Imho this is in general a conceptual/Content Managers problem and not a theme problem per se. It can be solved adding shy´s and/or using hyphens: auto or a js-lib doing that for you. 

You just can´t avoid any edge-case. Edge-cases are what they are - edge cases. And therefore need custom solutions. Otherwise you might f*ck up the usual use-cases.

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert I do agree that you can't capture all edge cases but there are some edge cases a theme should be able handle out of the box according to the Theme Unit Test. The case discussed here is one of them.
