### ISSUE TITLE
Error on NPM Install, seems like a broken path?

### ISSUE THREAD

**Issue by fredrikwcms** [understrap/understrap#1162]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - **OS Version:** MacOS [10.14.6] | 

  - **Node.js & NPM Versions:** Node.js [V 12.13.1] | NPM [V 6.14.4]

---

# Issue Overview for Bugreports

## Steps to reproduce?
Run "NPM Install" on a fresh clone of Understrap

## *Who* is the bug affecting?
Me, so far :D 

## *What* is affected by this bug?
The installation

## *When* does this occur?
At the end of the installation script, right after Gulp copy-assets. It seems to give me a broken path to a .js that exists (I doublechecked).

Error: File not found with singular glob: /Applications/Ampps/www/wp-tema/dag-9/wp-content/themes/understrap/**node_modulesundescores-for-npm**/js/skip-link-focus-fix.js

### Other Comments

I had 8 other persons with different environments having the same problem.

**Comment by fredrikwcms** [comment]
Here's a screenshot 
![Screenshot 2020-04-30 at 12 53 29](https://user-images.githubusercontent.com/34235516/80702779-e277d400-8ae1-11ea-97da-0fdfdf248a39.png)

**Comment by Thomas-A-Reinert** [comment]
Missing a Slash.
