### ISSUE TITLE
form-login and quantity-input templates out of date

### ISSUE THREAD

**Issue by carlosjillson** [understrap/understrap#1167]
This is a bug report.

  - **WordPress Version:** 5.4.1
  - **OS Version:** MacOS 10.11.1
  - **Browser:** Firefox 76.0.1
  - **WooCommerce Version:** 4.1.0

---

My WordPress dashboard says that my UnderStrap theme contains outdated WooCommerce template files. My WooCommerce status page says these template overrides are out-of-date:

understrap/woocommerce/global/quantity-input.php version 3.6.1 is out of date. The core version is 4.0.0, 
understrap/woocommerce/myaccount/form-login.php version 3.6.1 is out of date. The core version is 4.1.0,

**Comment by IanDelMar** [comment]
Related to #1138 and #1120 (outdated Woocommerce/Woocommerce compatibility)

@UnderstrapFramework you may want to assign the label "woocommerce" to these 3 issues.

**Comment by UnderstrapFramework** [comment]
Done, thanks @IanDelMar
