### ISSUE TITLE
moving 'understrap_theme_layout_options' customizer section inside a custom panel

### ISSUE THREAD

**Issue by mbtocalli** [understrap/understrap#1170]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.4.1
  - **OS Version:** [Windows 10]
  - **Browser:** [ all ]
  - **Language:** [ PHP]

---

I'm working with Understrap Child theme. I'm using Kirki plugin to create custom panel, sections and controls on theme customizer. I want to put Understrap defaults 'Theme Layout Settings' section inside a custom panel called 'underchild_design'.

I had tried this solution, but it didnt worked:

$wp_customize->remove_section( 'understrap_theme_layout_options' );
$wp_customize->get_section('understrap_theme_layout_options')->panel = 'underchild_design';

Can anyone help me with this?

**Comment by IanDelMar** [comment]
Try
```php
add_action( 'customize_register', 'underchild_customize_register', 20 );
function underchild_customize_register( $wp_customize ) {
	$wp_customize->get_section('understrap_theme_layout_options')->panel = 'underchild_design';
}
```

You may want to make yourself familiar with the Customizer API: https://developer.wordpress.org/themes/customize-api/customizer-objects/

(Your question is not related to UnderStrap or a child theme of UnderStrap.)

Please consider to close the issue if the answer solves your issue.

**Comment by IanDelMar** [comment]
@mbtocalli Would you give us an update on the current status of this issue?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @mbtocalli  feel free to reopen it. @UnderstrapFramework please close.

**Comment by IanDelMar** [comment]
@UnderstrapFramework

**Comment by UnderstrapFramework** [comment]
Thanks
