### ISSUE TITLE
issues in npm post-install script

### ISSUE THREAD

**Issue by ghrushneshr25** [understrap/understrap#1173]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by ghrushneshr25** [comment]
Running npm-postinstall.js
child_process.js:669
    throw err;
    ^

Error: Command failed: copy node_modules/katex/dist/katex.min.css app/katex/
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (D:\Project\Server\.scripts\npm-postinstall.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer 54 68 65 20 73 79 6e 74 61 78 20 6f 66 20 74 68 65 20 63 6f 6d 6d 61 6e 64 20 69 73 20 69 6e 63 6f 72 72 65 63 74 2e 0d 0a>,
    <Buffer >
  ],
  pid: 820,
  stdout: <Buffer 54 68 65 20 73 79 6e 74 61 78 20 6f 66 20 74 68 65 20 63 6f 6d 6d 61 6e 64 20 69 73 20 69 6e 63 6f 72 72 65 63 74 2e 0d 0a>,
  stderr: <Buffer >
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Rocket.Chat@3.3.0-develop postinstall: `node .scripts/npm-postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Rocket.Chat@3.3.0-develop postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by IanDelMar** [comment]
I think you should close this issue and open an issue at [RocketChat/Rocket.Chat](https://github.com/RocketChat/Rocket.Chat) or directly look at RocketChat/Rocket.Chat#13722...

**Comment by IanDelMar** [comment]
@UnderstrapFramework not related to UnderStrap, can be closed.
