### ISSUE TITLE
Use a `develop` branch as primary and `main` for a ready to use release.

### ISSUE THREAD

**Issue by pattonwebz** [understrap/understrap#1174]
I am just making this as a suggestion because I feel like this could simplify the workflow and allow easier contributions.

Essentially a `develop` branch would become the primary branch, changes get merged into it. When enough changes are ready a release is prepaired via a PR that merges `develop` into `master` and a version bump is done for it.

I suggest this because that way you could allow contributors (like @IanDelMar) access to merge to develop but have `master` as a protected branch only you could merge to @UnderstrapFramework.

Personally I feel like this could work out better long term for everyone involved.

**Comment by UnderstrapFramework** [comment]
Sounds great @pattonwebz, I hadn't thought of that and will action it ASAP

**Comment by IanDelMar** [comment]
@UnderstrapFramework How come you hadn't thought of that? https://github.com/understrap/understrap/issues/1089#issuecomment-570897716, https://github.com/understrap/understrap/issues/1089#issuecomment-570908886, https://github.com/understrap/understrap/issues/1089#issuecomment-590148333.

**Comment by UnderstrapFramework** [comment]
@IanDelMar I didn't think I could assign permissions different across branches like that

**Comment by nvjacobo** [comment]
Hi  @UnderstrapFramework 

Related with this issue about branches. How and when do you think next versions for understrap/understrap and understrap/child?

Thanks you in advance

**Comment by UnderstrapFramework** [comment]
Hey @nvjacobo, from my point of view there is no big changes coming along other than the next Bootstrap release so I just don't see the point in moving up a version - no one else has brought it up so i'm guessing other people feel the same?

**Comment by nvjacobo** [comment]
> Hey @nvjacobo, from my point of view there is no big changes coming along other than the next Bootstrap release so I just don't see the point in moving up a version - no one else has brought it up so i'm guessing other people feel the same?

Thanks @UnderstrapFramework 

A guiding question about how to use branches. In this case, which branch do you suggest using for production sites?

**Comment by bacoords** [comment]
I think this is a great suggestion. Visitors who just download/clone the 'master' branch should expect to get the latest functional version, correct?

Please comment here if you see any other concerns, otherwise, let's consider this part of the roadmap.

**Comment by bacoords** [comment]
This has been completed.
