### ISSUE TITLE
Gulp watch works only once..

### ISSUE THREAD

**Issue by wronahau** [understrap/understrap#1180]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] Gulp watch works only once, after restart it works correctly but any other changes are not seen.

## Please tell us about your environment:

  - **WordPress Version:**5.4.1
  - **OS Version:**  Linux  Debian 10
  - **Browser:** [ all ]
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [10.19] | NPM [6.14.5]

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by IanDelMar** [comment]
Which watch task is not working - scss, js, img? Or none? Have you checked whether it is a browser chaching issue (i.e. checked content of file on disk versus content of file in browser)?

**Comment by 0dp** [comment]
@wronahau it would be super helpful if you could fill out the bug report

**Comment by IanDelMar** [comment]
@wronahau Is this still an issue?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @wronahau feel free to reopen it. @UnderstrapFramework please close.

**Comment by IanDelMar** [comment]
@UnderstrapFramework

**Comment by UnderstrapFramework** [comment]
Thanks
