### ISSUE TITLE
NPM Install keeps failing

### ISSUE THREAD

**Issue by MarkBolden** [understrap/understrap#1195]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.4.2
  - **OS Version: Linux 18.04 (bionic)
  - **Browser:** all
  - **Language:** PHP
  - **Node.js & NPM Versions:** Node.js v8.10.0

---
## *When* does this occur? when I run npm install. I get the error:

/var/www/html/wp-content/themes/understrap$ sudo npm install

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! Linux 4.15.0-99-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/wp-content/themes/understrap/npm-debug.log

### Other Comments:
I can't remember ever getting this to run successfully. I am looking for some guidance. Maybe a suggestion or two.

Cheers!
-Mark

**Comment by IanDelMar** [comment]
Hi Mark!

Have you tried to update your npm version?

**Comment by MarkBolden** [comment]
No. I will give it a shot.

**Comment by mattyjneal87** [comment]
@MarkBolden Did upgrading fix the issue? I noticed that sometimes the latest version fails as well. Try version 10 or so.

**Comment by ShikaSan** [comment]
Figured bumping this issue, instead of creating another one. I'm having problems also with installation via NPM, please have a look at the attached log file.

[2020-07-22T16_43_17_069Z-debug.log](https://github.com/understrap/understrap/files/4961293/2020-07-22T16_43_17_069Z-debug.log)

**Comment by 0dp** [comment]
What is your version of node and npm?
This issue has been covered extensively, so please try and search the closed issues in this repo 👍

**Comment by ShikaSan** [comment]
Ah, apologies. I've read a closed issue that exactly pertains to the problem I'm facing. Fixed it now, thanks!

**Comment by 0dp** [comment]
Haha great!

**Comment by IanDelMar** [comment]
@MarkBolden Has updating node/npm solved the issue?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @MarkBolden  feel free to reopen it. @UnderstrapFramework please close.

**Comment by IanDelMar** [comment]
@UnderstrapFramework

**Comment by MarkBolden** [comment]
My apologies for the lack of response. updating node/npm never resolved the issue. I even created a VMWare VM and tried in a "clean environment" and still rec'd errs. I will close for now and continue to troubleshoot on my own.
