### ISSUE TITLE
npm install -> Failed at the node-sass@4.11.0 postinstall script.

### ISSUE THREAD

**Issue by insight47** [understrap/understrap#1197]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.4.2
  - **OS Version:** MacOS 10.15.4
  - **Browser:** Chrome
  - **Node.js & NPM Versions:** Node.js 14.2.0 | NPM 6.14.4

--

# Issue Overview for Bugreports

## Steps to reproduce?

1. Install WordPress on a local vhost.
2. Install the understrap theme through Appearance > Themes > Add New.
3. Open VS Code to the understrap folder.
4. In the VS Code command line, run `npm install`.

Receive error:

```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-83_binding.node": 
...
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## *Who* is the bug affecting?

Me, as the developer.

## *When* does this occur?

Everytime I run `npm install`.

## Expected behavior

Hope to run `npm install` without errors.

**Comment by IanDelMar** [comment]
node-nass 4.11 is not compatible with Node.js 14.2.0. Which version of UnderStrap are you using? Actually the package-lock.json in the master branch is at node-nass v4.14.

Try the following:
* Delete package-lock.json
* Run npm install again

**Comment by insight47** [comment]
Thanks Ian. Running Version: 0.9.4 of Understrap.

Deleting `package-lock.json` & running `npm install` again resolved the error.

Thanks!
