### ISSUE TITLE
Can't run browsersync on port 8080 (connection refused)

### ISSUE THREAD

**Issue by insight47** [understrap/understrap#1198]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.4.2
  - **OS Version:** MacOS 10.15.4
  - **Browser:** Chrome
  - **Node.js & NPM Versions:** Node.js 14.2.0 | NPM 6.14.4

--

# Issue Overview for Bugreports

## Steps to reproduce?

1. Edit `gulpconfig.json` to set 

```
"browserSyncOptions": {
	"proxy": "www.understrap.local:8080/",
	"notify": false
},
```
2. Run `gulp watch-bs`.
3. Open `www.understrap.local:8080` in Chrome.
4. Receive Chrome browser error:

```
This site can’t be reached
www.understrap.local refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```
The normal site runs okay @ `www.understrap.local` using AMPPS for Mac.

Help appreciated.

**Comment by IanDelMar** [comment]
Does this also happen in another browser?

**Comment by insight47** [comment]
Yes, it happens in both Chrome & Firefox.

I see `browser-sync@2.26.3`.

How would browser-sync serve the WordPress site if it is normally served by AMPPS Apache?

Thanks.

**Comment by 0dp** [comment]
1. Do you have something else running on port 8080?
Try change the port to 3000 for instance.

2. Is your firewall blocking traffic on port 8080/3000
Try and disable your firewall temporarily

**Comment by insight47** [comment]
MacOS Firewall is off.

Changing to port 3000 & 4000 produced the same error.

Thanks.

**Comment by 0dp** [comment]
And the console output is normal with no error when you run 'gulp watch-bs'?

**Comment by insight47** [comment]
Yes, that's right.

**Comment by 0dp** [comment]
Could you try and turn off ampps and check

**Comment by insight47** [comment]
Same issue. AMPPS would be required to serve from the MySQL database wouldn't it?

**Comment by insight47** [comment]
I turned off AMPPS Apache, and left AMPPS MySQL on, but the issue remained.

**Comment by 0dp** [comment]
> Same issue. AMPPS would be required to serve from the MySQL database wouldn't it?

Yes, but it was just to verify if ampps was blocking anything

**Comment by insight47** [comment]
Is browser-sync for serverless web apps?

**Comment by 0dp** [comment]
Not specifically.

**Comment by 0dp** [comment]
I don't know if you have the option, but try and do a port scan of your local machine.

**Comment by insight47** [comment]
Open TCP Port: 	88     		kerberos
	 Open TCP Port: 	445    		microsoft-ds
	 Open TCP Port: 	548    		afpovertcp
	 Open TCP Port: 	631    		ipp
	 Open TCP Port: 	3000   		hbci
	 Open TCP Port: 	3001   		redwood-broker
	 Open TCP Port: 	3283   		net-assistant
	 Open TCP Port: 	3306   		mysql
	 Open TCP Port: 	5900   		rfb
	 Open TCP Port: 	6258
	 Open TCP Port: 	6263
	 Open TCP Port: 	15292
	 Open TCP Port: 	15393

I tried running browser-sync on port 6258, but the same error occurred.

**Comment by 0dp** [comment]
So I looked at your scan, and 8080 is not open, but you tried an seemingly open and in occupied port, with no availability.

What I am fairly certain of is that it's not an issue with bs rather a host/os issue.

Just to reiterate:
Firewall is disabled,
Nothing is blocking the port (bs would also automatically choose an unoccupied port I believe),
Ampps disabled,

You tried restarting your machine just to make sure changes have been applied?

**Comment by IanDelMar** [comment]
Could you try this

```
npm uninstall browser-sync
npm install browser-sync --save-dev
```

and/or skip the port from the proxy option
```diff
"browserSyncOptions": {
-	"proxy": "www.understrap.local:8080/",
+	"proxy": "http://www.understrap.local/",
	"notify": false
},
```

**Comment by insight47** [comment]
I've done that, including removing the port from the proxy option, and the site loads, but does not auto-refresh after making changes to `_theme.scss` - is browser-sync supposed to reload after changes?

If I add the port back to `browserSyncOptions` (port 3000, or 8080), the same original error occurs (refused to connect).

**Comment by insight47** [comment]
> So I looked at your scan, and 8080 is not open, but you tried an seemingly open and in occupied port, with no availability.
> What I am fairly certain of is that it's not an issue with bs rather a host/os issue.
> 
> Just to reiterate:
> Firewall is disabled,
> Nothing is blocking the port (bs would also automatically choose an unoccupied port I believe),
> Ampps disabled,
> 
> You tried restarting your machine just to make sure changes have been applied?

Yes, that is correct. Starting machine today, and original error occurs.

**Comment by 0dp** [comment]
> @IanDelMar
> 
> I've done that, including removing the port from the proxy option, and the site loads, but does not auto-refresh after making changes to `_theme.scss` - is browser-sync supposed to reload after changes?
> 
> If I add the port back to `browserSyncOptions` (port 3000, or 8080), the same original error occurs (refused to connect).

When you removed the port number from the proxy line and ran bs the site opened in a new browser window on port 8080?

**Comment by insight47** [comment]
No, it ran without a port number.

**Comment by 0dp** [comment]
Oh.

What's special about port 8080, is that the port your webserver is running on?

**Comment by insight47** [comment]
That was the default port number specified in `gulpconfig.json` out of the box.

**Comment by 0dp** [comment]
oh ok. Not sure why that is, I've never used a port number in my `gulpconfig.json`
Could you try and change proxy to `"proxy": "localhost/"`

**Comment by IanDelMar** [comment]
> I've done that, including removing the port from the proxy option, and the site loads, but does not auto-refresh after making changes to `_theme.scss` - is browser-sync supposed to reload after changes?

@insight47 Yes, Browsersync should reload the page when you save your changes to  `_theme.scss`. Also, as @0dp said, Brwosersync should open a new browser window or tab when you run `gulp watch-bs`. Does Browsersync open a new browser window or tab?

**Comment by 0dp** [comment]
@IanDelMar I am not sure why port 8080 was added to the gulpconfig at some point. It might've been a mistake in the PR.
But from my experience there is no need to proxy through a domain like that, and it would in most cases be sufficient to use the loopback address

**Comment by IanDelMar** [comment]
@0dp It was #955.

I use WampServer and I do have to specify a directory like `localhost/projects/understrap/` where `projects/understrap/` is the directory to a WordPress install relative to the `www` directory of WampServer. `localhost` is `C:\wamp64\www`. So Browsersync needs to know where my WordPress install is located. I don't know about AMPPS for Mac setup but doesn't `localhost` on a Mac mean something like `/Users/username/Sites`? And what is localhost if you host multiple sites in `/Users/username/Sites`?

**Comment by IanDelMar** [comment]
@insight47 Given the last screenshot from https://stackoverflow.com/questions/31380981/setting-up-virtual-hosts-in-ampps try `localhost/understrap/` or whatever the project directory (i.e. the part of the domain path after ...www/) is.

**Comment by 0dp** [comment]
> @0dp It was #955.
> 
> I use WampServer and I do have to specify a directory like `localhost/projects/understrap/` where `projects/understrap/` is the directory to a WordPress install relative to the `www` directory of WampServer. `localhost` is `C:\wamp64\www`. So Browsersync needs to know where my WordPress install is located. I don't know about AMPPS for Mac setup but doesn't `localhost` on a Mac mean something like `/Users/username/Sites`? And what is localhost if you host multiple sites in `/Users/username/Sites`?

I guess it really depends on how you setup your machine. I for instance is not using the default MacOS apache setup. I've installed everything from homebrew.

But you are correct, normally you would specify the directory localhost/path/to/site so BS knows where to look.

localhost would just be the path to htdocs/www folder

**Comment by insight47** [comment]
I changed `gulpconfig.json`: `"proxy": "localhost/understrap.local/",` (the site's directory is @ `/Applications/AMPPS/www/understrap.local/`, and BS opens the site but to a 404 page @ `http://localhost:3000/understrap.local/`.

**Comment by IanDelMar** [comment]
At least we're getting closer 😄 If you run `gulp watch-bs` a new Chrome window opens but it gives a 404 page and the 404 page refreshes when you change the `_theme.scss`? Could you try to set up a new UnderStrap project but have a directory, eg. `/Applications/AMPPS/www/understrap/` (without any '.' and the like).

**Comment by insight47** [comment]
Yes, getting closer. Removing `.local` from the directory in `www` and updating `gulpconfig.json to: "proxy": "localhost/understrap/" produced the same 404 unfortunately.

**Comment by IanDelMar** [comment]
Have you updated your AMPPS setup as well or just 'renamed' the directory? Is the 404 page the theme's 404 page or the server's default 404 page?

**Comment by insight47** [comment]
Yes I've updated `vhosts.conf`. The 404 is the theme's 404 page.

**Comment by 0dp** [comment]
Have you set a default page in WordPress, and have you generated a .htaccess file?
Does this ampps have mod_rewrite enabled?
Have you tried to resolve a page in your installation you know exist with the bs port number appended like, localhost/my-page:3000

**Comment by insight47** [comment]
Yes, WordPress has a default page of www.understrap.local. I don't think WordPress understands how to interpret http://localhost:3000/understrap/

localhost:3000/understrap/known-page also produces a 404.

**Comment by ashbryant** [comment]
@insight47 I've had the same issue, however, I fixed it (for me at least) by making sure the domain name was not using https. I fell into the trap after copying the DB from a staging server where the domain is being served over https and I just did a find and replace on the subdomain using the WP CLI (staging. to dev.) and forgot to replace the https to http. 

After doing that http://localhost:3000/ works fine.

Perhaps this will help?

**Comment by insight47** [comment]
Hi @ashbryant the website was loading on http to begin with.

**Comment by IanDelMar** [comment]
@insight47 It's been a while. Have you been able to resolve the issue?

**Comment by insight47** [comment]
Hi @IanDelMar , I've not made any changes to this project in the interim, and things are running fine on http://localhost:3000/, including navigating to subpages, so it looks like WordPress has no qualms with this setup.

The only thing not working is changes to _theme.scss do not auto update in the browser.

**Comment by bacoords** [comment]
Looks like this issue was either resolved or else isolated to the user's unique local dev environment. Please re-open if that was not the case.
