### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by dokotor** [understrap/understrap#1211]
## Issue is about..
  - [ ] a Bug Report
  - [x] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

Has anyone tried using understrap with bootstrap 5 Alpha? Does it require a lot of changes?

**Comment by zachatkinson** [comment]
Was just coming on to ask about this.

**Comment by 0dp** [comment]
Well first thing first would be to read through the release information. Then look through the migration information available at current time. Make a list of all affected areas. Ie. dropping jQuery etc.
When you've done that we can look into what it would take to migrate the theme to BS5-ALPHA

**Comment by Thomas-A-Reinert** [comment]
I guess it would be a bad idea to allow automatic updates from 4.x to 5.x as it´s already been with the update from 3.x to 4.x.
Things change/d a LOT.  And it will f*ck up your site, promised. I tested it with about 3 sites and things didn´t work out. 
jQuery comes from WordPress anyway and I don´t see that they´ll drop it anytime soon though. So "everything jQuery" will prolly still work after updates. But not "the Bootstrap" way.

In my eyes it would need another fork and another theme in WordPress, so ppl would not "automatically update" their themes which would turn out fatal in most cases.

**Comment by tobyink** [comment]
Understrap need to be forked anyway as this version is woefully unmaintained. Bootstrap 5 coming out may provide a good opportunity and motivation to do so.

**Comment by LukaszJaro** [comment]
I wanted to mention, if you go to bootstrap v5 there will no longer be internet explorer support, only v4 has at least ie 11 support.

**Comment by pattonwebz** [comment]
IE support is a requirement for a vast majority of gouvernment agencies and as such they are not adopting BS5
