### ISSUE TITLE
style.css and npm in the theme not working 

### ISSUE THREAD

**Issue by zweb-ma** [understrap/understrap#1212]
hi 
Someone can help me please 
I can install the npm in vs code . note that npm and node.js work very well in my windows 10 but I can't install it in visual code editor and then the style. CSS not working I can do please

**Comment by IanDelMar** [comment]
Hi, I use VS Code as well and can't confirm any installation problems. Can you please give us more information? Which version of node.js/npm? Which version of UnderStrap? What exactly do you mean by the CSS is not working?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @zweb-ma  feel free to reopen it. @UnderstrapFramework please close.

**Comment by UnderstrapFramework** [comment]
Thanks
