### ISSUE TITLE
Lodash - Github security alert!

### ISSUE THREAD

**Issue by BadHabbit84** [understrap/understrap#1213]
Hey there.

Just want to let you know, Github gave me this security issue:

Vulnerable versions: < 4.17.19
Patched version: 4.17.19
Versions of lodash prior to 4.17.19 are vulnerable to Prototype Pollution. The function zipObjectDeep allows a malicious user to modify the prototype of Object if the property identifiers are user-supplied. Being affected by this issue requires zipping objects based on user-provided property arrays.

This vulnerability causes the addition or modification of an existing property that will exist on all objects and may lead to Denial of Service or Code Execution under specific circumstances.

Thanks.

**Comment by Thomas-A-Reinert** [comment]
10 merges within 3 minutes. It´s evident that no code-review has been done.
I´ll leave any interpretations open to the users of UnderStrap.
