### ISSUE TITLE
Gulp Watch Hanging.

### ISSUE THREAD

**Issue by benjaminthedev** [understrap/understrap#1214]
Hi folks, 

I have tried to gulp watch on my files and it just hangs:

<img width="453" alt="Screenshot 2020-08-02 at 19 44 12" src="https://user-images.githubusercontent.com/14097672/89129830-8c5b6800-d4f8-11ea-9680-40ae8e7862e1.png">

I am not sure how I should fix this, all the dev dependencies are installed and I have the latest NPM / Nodejs etc.

Any suggestions?

Cheers, 

Ben.

I am on a MacBook Pro 

<img width="235" alt="Screenshot 2020-08-02 at 19 45 31" src="https://user-images.githubusercontent.com/14097672/89129863-bc0a7000-d4f8-11ea-854a-2e7e5b058140.png">

**Comment by 0dp** [comment]
You ran `gulp watch-bs` ?

**Comment by benjaminthedev** [comment]
Hi,

So yes I can run it but I get a blank screen but I do not think that is the issue.

I made a change the css/theme.css and saved but nothing happened.   In the past gulp would work with theme.min.css etc 

Cheers, 

Ben.

<img width="423" alt="Screenshot 2020-08-03 at 06 43 42" src="https://user-images.githubusercontent.com/14097672/89149678-eb4eca80-d554-11ea-99c6-3b6026e81116.png">

**Comment by benjaminthedev** [comment]
And this is the frontend: 

<img width="1678" alt="Screenshot 2020-08-03 at 06 45 50" src="https://user-images.githubusercontent.com/14097672/89149734-0e797a00-d555-11ea-9c24-1d8ba4883acd.png">

**Comment by 0dp** [comment]
Your theme should reside in your WordPress installation.
Right now it looks like your theme is in a folder on the desktop

**Comment by benjaminthedev** [comment]
Yes it is, I normally use mamp for WP applications but just need to do some css tweaks and then upload to the server - this shouldn't effect Gulp right? Or the minifying of css right?

**Comment by benjaminthedev** [comment]
So for a bit of fun I thought I would create a new project just to see if I could get gulp working and I can not install it via VS Code terminal:

<img width="1680" alt="Screenshot 2020-08-03 at 08 09 39" src="https://user-images.githubusercontent.com/14097672/89155532-eb54c780-d560-11ea-95ff-f95296dd6ad3.png">


and 


<img width="998" alt="Screenshot 2020-08-03 at 08 09 46" src="https://user-images.githubusercontent.com/14097672/89155540-eee84e80-d560-11ea-9a25-6156a48d4408.png">

Which leads me to the question, is the issue my machine?

Also thank you for the help, gulp used to work with UnderStrap but maybe it is my mac?

**Comment by 0dp** [comment]
If you just want to change a bit of css and compile then run `gulp styles` that should be sufficient.

Your npm log looks a bit strange.
- try and install gulp Babel manually
- react-redux, Is that your own dependency?

**Comment by benjaminthedev** [comment]
Thanks for that  - yes gulp styles is fine for what I am doing but would like to get this sorted as I use UnderStrap for dev work with WP.

I will try and install manually and the react-redux, I use this for react projects maybe this is the issue!

Thank you again for your help. :)

**Comment by 0dp** [comment]
It should work OTB

**Comment by benjaminthedev** [comment]
Hey again! 

So this is odd I have written some styles in theme.css and when I run gulp styles it removes my styles from theme.css?

So odd right?!

**Comment by 0dp** [comment]
no that's not odd, that's intended.

You need to write your styles in the .scss files. These files will be compiled into a new theme.css file everytime you save a .scss file.

**Comment by benjaminthedev** [comment]
Perfect ok thanks for this, can close now :) Thank you again for your help!

**Comment by 0dp** [comment]
@benjaminthedev you can just close the issue if its resolved ;)
