### ISSUE TITLE
Bootstrap Carousel Crossfade problem

### ISSUE THREAD

**Issue by ShikaSan** [understrap/understrap#1215]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question

## Please tell us about your environment:

  - **WordPress Version:** 5.4.2
  - **OS Version:** Windows 10
  - **Browser:** [ Chrome Latest | Firefox Desktop and Mobile Latest | Mobile Chrome Latest Update | Edge (Chromium) Latest ]
  - **Language:** [PHP | HTML | S/CSS | Javascript | jQuery]
  - **Node.js & NPM Versions:** Node.js [V 12.18.3] | NPM [V 6.14.6]

---

# Issue Overview for Bugreports

## Steps to reproduce?
Implement a carousel with crossfade on any PHP page template. In my case, I've written it on the template-home.php file.

## *Who* is the bug affecting?
Me, as the developer.

## *What* is affected by this bug?
The bootstrap carousel, it just "jumps" to the next image without performing the crossfade effect

## *When* does this occur?
Just as I was trying to test and see if crossfade works. So, it happens every time after I save my changes on the template and reload the page. I've also cleared browser data and cache just to be sure it isn't just a leftover cache problem.

## *How* do we replicate the issue?
You can try to implement a carousel with .carousel-fade class on template-home.php.

## Are there any related Issues and/or PRs?
I'm not really sure, there is no other PRs related specifically to carousel crossfading.

## Expected behavior
Refer to the documentation here:
https://getbootstrap.com/docs/4.1/components/carousel/#crossfade

**Comment by axlright** [comment]
Do you have a public example we can see? I've used Bootstrap Carousels in other Understrap projects before without trouble, though I can't be certain I've used the `.carousel-fade` class.

**Comment by ShikaSan** [comment]
Apologies for the very late response, but here's a link to a public example: http://a72e07dada9c.ngrok.io/

Please refer to the very first carousel of the page.

**Comment by axlright** [comment]
You don't have the `carousel-fade` class applied. I added that in Chrome Dev-Tools and it ended up working fine as far as I can tell.

I changed `<div id="myCarouselFlavors" class="carousel slide pointer-event" data-ride="carousel">` to `<div id="myCarouselFlavors" class="carousel slide pointer-event carousel-fade" data-ride="carousel">` to get what I understand to be the desired effect and it worked well.

**Comment by ShikaSan** [comment]
Ah no, that's the second slide. There's another one with the ID `#myCarousel`. But anyhow, I also tried using Chrome dev-tools and added it myself to both the slides on that particular page. The effect still doesn't work on my end. I also made sure to disable any scriptblocker/adblocker that I'm running on my browser.

**Comment by IanDelMar** [comment]
Just tested, I can't reproduced the issue. Using `<div id="mycarousel" class="carousel slide carousel-fade" data-ride="carousel">` gives the expected result.

**Comment by IanDelMar** [comment]
@ShikaSan do you still face the problem?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @ShikaSan feel free to reopen it. @UnderstrapFramework please close.
