### ISSUE TITLE
Template out of date after updating to latest WooCommerce (4.4.0)

### ISSUE THREAD

**Issue by ShikaSan** [understrap/understrap#1218]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

---

After updating to the latest WooCommerce version, it notified about an outdated template file that understrap is using. Are there any major changes to this particular template? Can I just carry on using it as usual or do I need to delete or edit a line (or rather lines) on the template? 

**Outdated Template Warning**
`doughnut/woocommerce/cart\cart.php version 3.8.0 is out of date. The core version is 4.4.0`

**Comment by s1awek** [comment]
Is this project still maintained? Looks like it's been pretty much deserted.

**Comment by IanDelMar** [comment]
> Is this project still maintained? Looks like it's been pretty much deserted.

The latest activity of the current project owner @UnderstrapFramework was on 22 Jun. There was no response to any of my comments to merge PRs. It seems that what other contributers and I feared has now come true: UnderStrap is finally dead.

@ShikaSan I just checked the current WC template (v4.4.1) against the current UnderStrap template and I can't see any changes. It seems that the changed introduced in v4.4.0 have been reverted in v4.4.1. You can keep using the template provided by UnderStrap.

CC @Thomas-A-Reinert @0dp @noelspringer

**Comment by SteffenGeorgi** [comment]
@IanDelMar Yeah, that's very sad. Especially because there are currently no alternatives... Is there anything one can do?

**Comment by IanDelMar** [comment]
@SteffenGeorgi There have been plans to launch an alternative to UnderStrap but then came Covid...

**Comment by s1awek** [comment]
In that case I'll be moving on to SAGE. Pitty, because I really liked UnderStrap :(

**Comment by s1awek** [comment]
I don't see the need to be mean.
I just used UnderStrap in my projects so far, now I will have to switch to something else.

I don't have time to develop or fork the UnderStrap project because I work 10+ hours a day. I need something that works right now and has a future.

If the authors have abandoned work on the project, I have no problem with that - their free will. My free will is to use a different starter theme now and my favorite at the moment is SAGE.

Have a nice day.

**Comment by pixel-paul** [comment]
My comment wasn't aimed at you @s1awek :)

**Comment by IanDelMar** [comment]
> Thanks for all your hard work on this project, it must be a hard to swallow situation.
> 
> What are the blockers to forking this project to another repo? I notice this is licensed under GPL v2, so keeping that intact would allow a fork that could be distributed.

@pixel-paul A couple of contributors have planned to do just that. However, we were in the process of discussing a few basic questions about the future of the theme before Covid took over.

@s1awek If you don't mind waiting a while longer, there might be something similar to UnderStrap.

**Comment by 0dp** [comment]
I'm still here 🥰

**Comment by pixel-paul** [comment]
@IanDelMar that is great to hear. We are relative new comers to this theme framework (we had been using FoundationPress until that was deprecated), however have used it with several recent projects. I hope that we will be able to help with some PRs when you have a new repo set up.

**Comment by SteffenGeorgi** [comment]
@IanDelMar Hope to hear about a new repo soon 🥳

**Comment by s1awek** [comment]
> My comment wasn't aimed at you @s1awek :)
@pixel-paul lol, sorry :P

@IanDelMar I will wait, thanks.

**Comment by aeboi80** [comment]
I will toss my hat into the pile - happy to help with dev on the new fork.

**Comment by tobyink** [comment]
I'm not really a node.js person, but also happy to help out where I can.

**Comment by 0dp** [comment]
Great to see there is still a lot of love for the project.

**Comment by Thomas-A-Reinert** [comment]
Yup. Also kinda still there. But not able to take the lead anymore. Got a really challenging job right now, so i´d be able to help, but not to call the shots other ppl can rely to.
WP became more or less a hobby for me.

@ShikaSan - seems like the project owner found about 3mins today to merge around 10 merge requests
Please try and check if this solves your problem. I´d recommend to make a backup before.

´Cos within 3 mins I guess he cannot really have had an intensive code-review and/or install any of those merge request. So any update to the latest version may really f**ck up your installation.

**Comment by JomTansen** [comment]
Hey guys,
I just wanted to start out my web development path with understrap, but with the mixed messages here I am pretty afraid that if I would build a new website for a client with a custom theme based on understrap, I might have a hard time in the future regarding updates & compatability. Is there any other similar starter theme you would recommend? Or should I just start with understrap and hope the project gets picked up again?

**Comment by s1awek** [comment]
> Hey guys,
> I just wanted to start out my web development path with understrap, but with the mixed messages here I am pretty afraid that if I would build a new website for a client with a custom theme based on understrap, I might have a hard time in the future regarding updates & compatability. Is there any other similar starter theme you would recommend? Or should I just start with understrap and hope the project gets picked up again?

I think, at least at this stage, going with Understrap is too risky. It may or may not go back on tracks.
Take a look here: https://roots.io/sage/

**Comment by JomTansen** [comment]
> I think, at least at this stage, going with Understrap is too risky. It may or may not go back on tracks.
> Take a look here: https://roots.io/sage/

Thanks for the reply. Ah man that's unfortunate. What about the thousands of websites that are already based on understrap - It's quite a lot work to switch a custom theme to another theme, right? Or will people try to fix all the upcoming issues themselves? 

And thanks for the suggestions! Sage was already on my list. But I can't decide yet if it is what I am looking for, since there are many things I haven't used or even heard before. I liked that about understrap, seemed very beginner friendly.

**Comment by Thomas-A-Reinert** [comment]
Well, @JomTansen the (former) devs can´t do anything if the project owner doesn´t release a roadmap, doesn´t answer to questions and merges anything without quality assurance, right?

As long as you followed the advice to build up your OWN theme BASED on understrap, not built a child-theme relying on updates from the parent theme and your product doesn´t show any errors, you´re kinda good to go.

A good advice would be to fork that project and let the "Dependabot" feature run over it, you should still be kinda good to go and let you know about any dependency updates and security issues.

> Or will people try to fix all the upcoming issues themselves?
That question can´t be answered in general. Most of the "beginners" won´t even know and/or loose any thought about it until any feature on their site fails. Professionals earning their money with it prolly can and should.

> Or should I just start with understrap and hope the project gets picked up again?
Well, question is about your own level. If you feel comfy with understrap - go for it. The actual state should be good to go, thanks to @IanDelMar . At least for a short- to mid-term client.
If it´s a long-term client.. well. Can´t tell. If there´s no info/roadmap/feedback from the repo-owner AT ALL, there is no such thing as "predictability".

In case you don´t with roots/sage I´d, also recommend that, cos Sage is at least some skill-levels "up".

**Comment by JomTansen** [comment]
Hey @Thomas-A-Reinert , thanks for the helpful answers. 

> A good advice would be to fork that project and let the "Dependabot" feature run over it, you should still be kinda good to go and let you know about any dependency updates and security issues.

I wanted to develop a custom theme based on understrap and review if any critical updates would be added in the future. Haven't worked with Dependabot yet, so I don't know if I understand it correctly - but does it mean, even if the original devs won't do anything to understrap, it will help me clear out possible dependency/security updates?

> Most of the "beginners" won´t even know and/or loose any thought about it until any feature on their site fails. Professionals earning their money with it prolly can and should.

That's suprising - to me as a beginner, this is a major concern. I have an upcoming client project, a wordpress website with basic features (forms, blog, newsletter, interactive map) and a pretty custom design, and I wouldn't want to base it on something that could foreseeably cause significant problems. I'm coming from a vfx & design background with coding knowledge in Python, QT & Javascript, and have done smaller html/css/js projects. 

> In case you don´t with roots/sage I´d, also recommend that, cos Sage is at least some skill-levels "up".

You mean, you would still recommend understrap as starting point in contrast to Sage? Yea I played around with it a lot, and feel pretty comfy with it. Seeing that you have already great experience in the field, is there any similar starter theme you would recommend to look into? 

Best wishes

**Comment by Thomas-A-Reinert** [comment]
Hi @JomTansen 

> I wanted to develop a custom theme based on understrap and review if any critical updates would be added in the future. Haven't worked with Dependabot yet, so I don't know if I understand it correctly - but does it mean, even if the original devs won't do anything to understrap, it will help me clear out possible dependency/security updates?

Well, partially. It will help finding out any npm-issues. But not any WP-related security issues or further WP developments.

> That's suprising - to me as a beginner, this is a major concern. I have an upcoming client project, a wordpress website with basic features (forms, blog, newsletter, interactive map) and a pretty custom design, and I wouldn't want to base it on something that could foreseeably cause significant problems. I'm coming from a vfx & design background with coding knowledge in Python, QT & Javascript, and have done smaller html/css/js projects.

Well, props to you then. I know a whole load of so-called "_WordPress Developers_" that don´t care a bit.
Having a stable and working fork won´t cause any foreseeable significant problems though - as long as no gamechanging WP-Updates will make your theme useless. Keeping it secure may be another thing though. You´d need to follow WP-Development and patch that thing manually.

> You mean, you would still recommend understrap as starting point in contrast to Sage? Yea I played around with it a lot, and feel pretty comfy with it. Seeing that you have already great experience in the field, is there any similar starter theme you would recommend to look into?

Well, Understrap is technically a pretty good thing to start off from if you ain´t got elite(?!) developer skills (yet). From what you´ll learn mastering it you may want to take it one/two level/s higher to Sage. But yes, Sage is one or two levels up on the skill-scale.
If you can install and play around with Sage like you want to - I´d say go with Sage for now.

No, personally had a deep comparison between all "WordPress Bootstrap" themes like 4-6 yrs ago and didn´t find anything that matched my kickout-criteria. Sage was far beyond my level at that time. That´s why I started following and supporting UnderStrap.

**Comment by tobyink** [comment]
I heard of Sage in this thread, and decided to check it out. I converted by Understrap child theme to be a Sage theme in a few hours. If you're already familiar with PHP, Node.js, Bootstrap, and WordPress, it's pretty easy.

(The only thing that confused me is I kept expecting `yarn build:production` to build the entire theme into `./dist`, but it actually just builds CSS and Javascript into there; you just use the repo root directory as your theme.)

**Comment by lvidal1** [comment]
@tobyink would you mind sharing a guideline of how to migrate an `understrap-child theme` to a `sage theme`, please? I am in the same spot where I need to look for alternatives to understrap

**Comment by tobyink** [comment]
@lvidal1 yeah, why not? It'll probably be more of a "here's how to create a sage theme from scratch, if you already know understrap" thing though. But you can use that knowledge and copy-paste a bunch of your SASS, etc from understrap-child.

**Comment by tobyink** [comment]
@lvidal1  https://toby.ink/blog/2020/11/26/dummys-guide-to-roots-sage-theme-in-wordpress/

**Comment by jeff-at-livecanvas** [comment]
Excellent work Toby. Sage is super great of course with Blade templating - and I think your guide was really the missing link.

On another side I feel some folks still need a totally "plug and play" theme, more designer-oriented and less developer-oriented.

I don't know if it is acceptable to link external websites, but seeing some folks which are struggling to get a viable option, I am going to share this.

With the current situation of UnderStrap, I have decided to fork 50% of it's code and do something different - which allows SASS without command line tools, and integrating Leafo's SCSSPHP with the WordPress Customizer. 
I also ditched Bootstrap's JS code for BootstrapNative, so jQuery is not needed anymore.
I replicated a basic livereload functionality in JS too - all baked in the theme.
Single and archive templates are a bit more spiced up too.


I know it has some limits and it's very opinionated, purists will hate it but if you want to give it a shot, it's free at  [https://picostrap.com/](https://picostrap.com/)

Still no WooCommerce support, very young, you're warned. 

But the pagespeed results you can achieve with it exceed vanilla Understrap quite a bit most of the times, and directory structure is very easy to grasp & beginner friendly.

**Comment by tobyink** [comment]
@jeff-at-livecanvas looks good. I've been working on a setup (theme + composer.json that installs Wordpress and some plugins) which I'm privately calling Parsley because it's a modified Sage. Not really intended for public use; really just my way of quickly getting up and running with a site.

The ability to edit some SASS variables in the Wordpress backend and then recompile would be very nice to have.

**Comment by findozor** [comment]
https://github.com/jeff-at-livecanvas
any chance picostrap would have bs5 will be in he near future?

**Comment by jeff-at-livecanvas** [comment]
yes, and it will be called picostrap5. Currently in private beta.
 Should take just a few days to verify things with final BS5.

BTW: Picostrap just got an update to fix some outdated WooCommerce templates.

**Comment by bacoords** [comment]
@danemorgan Can we run a test for deprecated WooCommerce templates with this update?

**Comment by 0dp** [comment]
This is just an idea and nothing I've looked too much into.
But maybe we should look into how many of the templates are actually needed in the theme and see how much, if any can be replaced with hooks instead.

If possible it would ease the maintenance of woo templates in the theme?

**Comment by danemorgan** [comment]
> @danemorgan Can we run a test for deprecated WooCommerce templates with this update?
> 
> CC #1218

I think the next update, which we can start working on now. It seems like there is value in getting the 0.9.5 release into the repository quickly and establish some momentum right away.

But I'll start looking for a way to validate/repair these templates and if I can, as @0dp suggests, replace them with hooks where possible. I like that idea a lot. Not every site is going to deploy Woo, and they have a brilliant team doing great things, so we should let them as much as we can.

**Comment by bacoords** [comment]
Agreed that this can wait until after 0.9.5 is in the repo, and even after BS5 integration (unless there are actual errors that are urgent). 

Also agreed that fewer templates, maybe moving to hooks to add some basic BS classes if needed, would be preferred. Less to maintain in the long run.

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
