### ISSUE TITLE
After installation of Gulp: “no command 'gulp' found”

### ISSUE THREAD

**Issue by JishanTanvir** [understrap/understrap#1222]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
 

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

**Comment by axlright** [comment]
This is likely an issue with your local installation. The installation of gulp isn't a part of this theme.

I'd suggest trying to figure out whether / where gulp is installed on your machine. Things like `which gulp` is a good place to start.

**Comment by aeboi80** [comment]
I've run into this before on some servers. Depending on your setup, you may need to create an alias to gulp. Assuming your terminal is running Bash, try editing the .bashrc profile file in your home directory and adding a line:

`alias gulp="/home/USER/wp-content/themes/THEME-NAME/node_modules/gulp/bin/gulp.js"`

This has  worked for me on both local servers and also on cPanel servers. You're essentially just telling it where to find the Gulp binary file when you type "gulp watch". To confirm it is working after adding the alias you can run

`gulp -v`

**Comment by IanDelMar** [comment]
@JishanTanvir Have you been able to sort out this problem?

**Comment by IanDelMar** [comment]
Due to lack of feedback I suggest to close this issue. @JishanTanvir  feel free to reopen it. @UnderstrapFramework please close.

**Comment by IanDelMar** [comment]
@UnderstrapFramework

**Comment by IanDelMar** [comment]
@UnderstrapFramework
