### ISSUE TITLE
How do I pass a parameter to custom post taxonomy query?

### ISSUE THREAD

**Issue by PaoloPgn** [understrap/understrap#1223]
Hi

I got a custom post type and I need to pass a parameter to get my taxonomy have a sticky post: the parameter I have to pass to the query is

`'include_sticky_posts' => true`

Is there something I can add, maybe to the
`php while ( have_posts() ) : the_post();`
query is to do it?

[I tried with no luck with a custom query with wp_tax but I got a lot of problems to render taxonomy ID of my custom post Taxonomy, and big related problems with pagination]

Thank you

## Issue is about..
  - [x] a Question

## Please tell us about your environment:
  - **Language:** [ PHP ]

**Comment by IanDelMar** [comment]
This is a general WordPress question which is not related to UnderStrap. How did you implement sticky posts for your custom post type? (That's not a native WordPress functionality.) Is it a custom field? Then maybe do a custom query including a meta query. Is it a custom query variable? Then use the `pre_get_posts` hook to alter the query. The more code and details you provide the easier it is for others to help.

**Comment by PaoloPgn** [comment]
thank you for your answer: the fact is that I'm searching a way to display sticky posts for a custom post type: every time I find a solution that is working with my query (essentially using "tax_query" parameter), I found problems with understrap pagination, so I thought it was some how that understrad handle the post query. If is not, and you confirmed me that, I have to look back and try to find a solution that can include sticky posts for custom post type.

**Comment by IanDelMar** [comment]
So, actually, you managed to have sticky posts for your custom post type, you managed to query them, but UnderStrap's pagination does not work with your query?

**Comment by PaoloPgn** [comment]
Yes. I needed to have sticky posts in a custom category. So i thought that I can combine 2 queries to achieve that: I created a "sticky" category for the custom post type "flower_color" and the other regular category as "red", "blue", etc.
I need at that point to have 2 queries.
In the first one I used a query that show post that are in the sticky category and in the bue one (for instance):
```
			$the_query = new WP_Query( array(
			    'post_type' => 'flower_color',
			    'posts_per_page' => 5,
			    'order' => 'DESC',
			    'tax_query' => array(
			        'relation' => 'AND', 
			        array(
			            'taxonomy' => 'colors',
			            'field'    => 'slug',
			            'terms'    => array( 'sticky' ),
			            // 'operator' => 'EXISTS',
			        ),
			        array(
			            'taxonomy' => 'colors',
			            'field'    => 'term_id',
			            'terms'    => array($term->term_id),
			            // 'operator' => 'EXISTS',
			        )
			    )
			) );
```
And if ( $the_query->have_posts() ) and so on
And then the loop query. I don't need pagination for this query and this query works well.

In the second query I put and AND relationship to have colors that are not included in the stocky category.

```
					$paged = ( get_query_var( 'paged' ) ) ? get_query_var( 'paged' ) 
					$the_query = new WP_Query( array(
					    'post_type' => 'flower_color',
					    'posts_per_page' => 5,
						'paged' => $paged,
					    'order' => 'DESC',
					    'tax_query' => array(
					        'relation' => 'AND',
					        array(
					            'taxonomy' => 'colors',
					            'field'    => 'slug',
					            'terms'    => array( 'sticky' ),
					            'operator' => 'NOT IN',
					        ),
					        array(
					            'taxonomy' => 'provincia',
					            'field'    => 'term_id',
					            'terms'    => array($term->term_id),
					            'operator' => 'IN',
					        )
						    )
						) );
```
				
For this second query I need a pagination and if I put the understrap_pagination() after it, it doesn't works. So I thought I can solve it with a plugin, but the one I found needed that query to show sticky post, and I can't tell if with the workaround 'include_sticky_posts' => true can work. I'm interested more to let pagination work for the query, honestly.
