### ISSUE TITLE
Understrap Inbuilt Font Awesome Not Showing Icons?

### ISSUE THREAD

**Issue by sadume** [understrap/understrap#1224]
## Issue is about..
  - [x] a Bug Report
  - [x] a Question 

## Please tell us about your environment:

  - **WordPress Version:** 5.5.1
  - **OS Version:** [Windows 10]
  - **Browser:** [ all | Chrome XX | Firefox XX]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

Using the Understrap starter theme I am finding that Font-Awesome icons aren't showing. I installed the Font-Awesome plugin but realized that Font-Awesome is bundled with Understrap. Does anyone have some ideas on what I need to do to make this work?

@import "assets/font-awesome"; is present in theme.scss and not commented out

When i disabled the Font-Awesome plugin I can see boxes saying F015 etc instead.

## Expected behavior
Icons should show up when using the html provided on font-awesome website

# Todos

 * Test
 * Documentation

**Comment by IanDelMar** [comment]
Try:
1. Install the gulp-sass-unicode package:
`npm install --save-dev gulp-sass-unicode`
2. Add the following lines in your `gulpfile.js`.
```diff
// Defining requirements
var gulp = require( 'gulp' );
var plumber = require( 'gulp-plumber' );
var sass = require( 'gulp-sass' );
+ var sassUnicode = require( 'gulp-sass-unicode' );
var babel = require( 'gulp-babel' );
```
```diff
/**
 * Compiles .scss to .css files.
 *
 * Run: gulp sass
 */
gulp.task( 'sass', function() {
	return gulp
		.src( paths.sass + '/*.scss' )
		.pipe(
			plumber( {
				errorHandler( err ) {
					console.log( err );
					this.emit( 'end' );
				},
			} )
		)
		.pipe( sourcemaps.init( { loadMaps: true } ) )
		.pipe( sass( { errLogToConsole: true } ) )
+		.pipe( sassUnicode() )
		.pipe( postcss( [ autoprefixer() ] ) )
		.pipe( sourcemaps.write( undefined, { sourceRoot: null } ) )
		.pipe( gulp.dest( paths.css ) );
} );
```
Please close the issue if the answer solves your problem.

**Comment by sadume** [comment]
I was using Koala but installed gulp as per your wiki, and then followed the above steps, but:
Had an issue when running cssnano:

```
[root@website OSC-Custom-UnderStrap]# gulp sass
[10:23:11] Using gulpfile /var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/gulpfile.js
[10:23:11] Starting 'sass'...
[10:23:13] Finished 'sass' after 2.36 s
[root@website OSC-Custom-UnderStrap]# gulp cssnano
[10:23:21] Using gulpfile /var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/gulpfile.js
[10:23:21] Starting 'cssnano'...
[10:23:21] 'cssnano' errored after 15 ms
[10:23:21] ReferenceError: cssnano is not defined
    at /var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/gulpfile.js:106:3
    at taskWrapper (/var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

But gulp sass ran fine, i changed the stylesheet to /css/theme.css from /css/theme.min.css just to test the fontawesome but the icons still arent displaying. 
Have you seen the above error before with cssnano? I am using Centos 8.
This is the cssnano code found in gulpfile.js

```
gulp.task('cssnano', function() {
	return gulp
		.src(paths.css + '/theme.css')
		.pipe(sourcemaps.init({ loadMaps: true }))
		.pipe(
			plumber({
				errorHandler: function(err) {
					console.log(err);
					this.emit('end');
				}
			})
		)
		.pipe(rename({ suffix: '.min' }))
		.pipe(cssnano({ discardComments: { removeAll: true } }))
		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest(paths.css));
});
```

**Comment by sadume** [comment]
minifycss works though, I thought minify was supposed to ignore the theme.css file but it produces an up to date theme.min.css for me

```
[root@website OSC-Custom-UnderStrap]# gulp sass
[10:55:17] Using gulpfile /var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/gulpfile.js
[10:55:17] Starting 'sass'...
[10:55:20] Finished 'sass' after 2.52 s
[root@website OSC-Custom-UnderStrap]# gulp minifycss
[10:55:24] Using gulpfile /var/www/html/wordpress/wp-content/themes/OSC-Custom-UnderStrap/gulpfile.js
[10:55:24] Starting 'minifycss'...
[10:55:26] Finished 'minifycss' after 1.69 s
[root@website OSC-Custom-UnderStrap]#
```

**Comment by IanDelMar** [comment]
> ReferenceError: cssnano is not defined

Does your package.json contain gulp-cssnano and does your gulpfile.js contain `var cssnano = require( 'gulp-cssnano' )`? cssnano has been removed from UnderStrap a while ago (https://github.com/understrap/understrap/commit/1208774d79dc0829f34c2b28d3b1322fc8a865b0).

> the icons still arent displaying

The font files are included? Check the fonts folder whether the fonts are available. Check the referenced source urls for Font Awesome font files in theme.css. Check the console for errors: Are font files blocked from being loaded?

**Comment by sadume** [comment]
unclear if I am supposed to manually add in files or not based on what fonts I am using, the documentation is lacking information https://understrap.github.io/#about and the other documentation is apparently out of date since cssnano was removed? https://usdocu.tarthemes.com/docs/0.8.2/introduction/

Also the fontawesome version that came with the theme is v4 fontawesome is now using v5. I will just disable fontawesome in the theme and use the fontawesome plugin for wordpress instead.
