### ISSUE TITLE
Menu Doesn't Change to Hamburg Early enough and Goes Outside Borders

### ISSUE THREAD

**Issue by sadume** [understrap/understrap#1232]
## Issue is about..
  - [ ] a Bug Report
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **OS Version:** [Windows 10]
  - **Browser:** [  Firefox XX ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports
Menu Doesn't Change to Hamburg Early enough and Goes Outside Borders

## Steps to reproduce? 
Put website in responsive view mode and change to ipad etc, or just make browser window smaller, also menu must be reasonably large

## Screenshots / Video
![image](https://user-images.githubusercontent.com/8512659/100304244-68b1b580-2ff2-11eb-808c-74adb9bc2f6a.png)

## Expected behavior
Should hit the breakpoint earlier and change to hamburg menu

# Todos

 * Test
 * Documentation

### Other Comments
I have yet to figure out how to change the breakpoints for this so that it uses the hamburg menu earlier rather than just on the mobile breakpoint. Do you have any tips on what code to change to make this happen. Thanks.

**Comment by IanDelMar** [comment]
Change `navbar-expand-md` to `navbar-expand-lg` in the header.php.
https://github.com/understrap/understrap/blob/9358ee459f9a8bfe855c3a707d571ece14421f68/header.php#L33

See the Bootstrap documention for navbars: https://getbootstrap.com/docs/4.5/components/navbar/#responsive-behaviors

**Comment by IanDelMar** [comment]
@sadume Did that solve your issue?

**Comment by sadume** [comment]
Yes it did, my apologies for not updating sooner.
