### ISSUE TITLE
Gulp watch stuck

### ISSUE THREAD

**Issue by Miricon** [understrap/understrap#1234]
Hello,

after hours of unsuccesfully trying to install gulp, I finally did it.
It works when i run gulp -v, but 
when I run gulp watch it gets stuck on: Starting 'watch'...
I tried searching, googling, sadly without any success, I have never worked with these programs, I just know HTML, CSS and I'm trying to build a website for my mother's school.

I'm using vscode
gulp -v gives back:
CLI v: 2.3.0
Local v: 4.0.2

Thanks!

## Issue is about..
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.x.x
  - **OS Version:**Windows  10
  - **Node.js & NPM Versions:** Node.js [14.5.1] | NPM [6.14.8]

**Comment by IanDelMar** [comment]
Hi @Miricon,
what do you mean with 'gets stuck'?

**Comment by Miricon** [comment]
> Hi @Miricon,
> what do you mean with 'gets stuck'?

It starts, but nothing happens, tried waiting for a long time.  There is just "starting watch" without aby results.

**Comment by IanDelMar** [comment]
Gulp starts watching for changes in the scss/js and the image source folder. If you change eg. the primary color
https://github.com/understrap/understrap/blob/9358ee459f9a8bfe855c3a707d571ece14421f68/sass/theme/_theme_variables.scss#L6
and save the file, Gulp notices this change and re-compiles the css files. Have you made any changes that should have triggered re-compilation of css or js or minification of images?

**Comment by Miricon** [comment]
Well nevermind, I'm trying again and it just works again:) Maybe there was some problem with switching the accounts (from administrator to normal user) with the server or something, damn how long have I been stuck on such a stupid thing. Thanks anyway.
