### ISSUE TITLE
Yoast SEO Title broken on Homepage

### ISSUE THREAD

**Issue by EllieMaffio93** [understrap/understrap#1235]
Hi,

I recently switched theme on my Wordpress website. I'm now using Understrap with Understrap-Child.
Everything works fine, except for the Yoast SEO title on the Homepage which appears to be broken.

According to Yoast settings, the title should be **Libri | Letture.org**
But when I look for my website in Google this is what I see: **Letture.org: Libri**

Up until the switch of the theme, everything worked fine, but right after the switch the SEO title broke.
This is the second time I've noticed this issue. It happened on another website I worked on with Understrap/ Understrap-Child.

Is there a way of fixing this?

Thanks for your help.
Kind regards,

Eleonora

**Comment by IanDelMar** [comment]
Hi @EllieMaffio93,
this is a Google issue and not related to the parent or child theme. Google shows what Google thinks is best to show which may or may not overlap with what you think is best. Everything works as expected on your site. Just check the site's title in the browser tab where it is Libri | Letture.org.

May I ask you to close the issue?

**Comment by EllieMaffio93** [comment]
Hi @IanDelMar ,

Thank you for your answer.
I just don't understand how can this issue be only related to Google. Everything worked fine with the previous theme.
What made me think about an issue with Understrap theme is that every website I've built using it has the same problem now. I can provide you with another example: https://www.koodit.it/ 

I've read that some themes may not have support for ` title_tag` .
Is this the case? If yes, what can I do?

Thank you,

Eleonora

**Comment by IanDelMar** [comment]
UnderStrap supports the title_tag: https://github.com/understrap/understrap/blob/9358ee459f9a8bfe855c3a707d571ece14421f68/inc/setup.php#L44

Again, check the title in the browser tab or check the page source. For https://www.koodit.it/ the title is 
```html
<title>Soluzioni E-Commerce, Consulenza Amazon E Siti Web - Koodit</title>
```

UnderStrap does not deal with the title at all except for adding theme support for the title tag.

**Comment by IanDelMar** [comment]
Have a look at this site and check if one of the issues mentioned there applies to your site(s) and whether that may cause Google to show a different title: https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets?hl=en

**Comment by IanDelMar** [comment]
Have you been able to see for yourself that the theme outputs the correct `<title>`?
Btw, it happens to the big players as well: Google shows 
![image](https://user-images.githubusercontent.com/42134098/102391420-fa02bf00-3fd5-11eb-93a0-913b36f1e0e4.png)
while the title tag is `<title>Amazon.it: Letture Prime: Libri</title>`.

**Comment by IanDelMar** [comment]
@EllieMaffio93 as this is not related to UnderStrap would you mind closing the issue?

**Comment by IanDelMar** [comment]
@UnderstrapFramework
