### ISSUE TITLE
gulp watch stuck at "starting 'watch'..."

### ISSUE THREAD

**Issue by dennis-soet** [understrap/understrap#1239]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.6.x
  - **OS Version:** [ Windows 10]
  - **Browser:** [Chrome 87]
  - **Node.js & NPM Versions:** Node.js [V 12.20.0] | NPM [V 6.14.8]

---

# Issue Overview for Bugreports

If i run the command "gulp watch" in my visual studio code terminal its getting stuck at "starting 'watch'...".
I already tried to install some other versions of gulp and node.js but nothing is working. 

## Steps to reproduce?

I did the following command to install everything.
1.
npm install --global gulp-cli
2.
npm install
3.
gulp watch

**Comment by LukaszJaro** [comment]
That sounds like correct behavior, try saving some CSS in your sass directory and you should see the terminal start building the files.

**Comment by mattneal-stafflink** [comment]
As @LukaszJaro said, this is the default behaviour. It's working correctly. Update and save one of your SASS files and it'll start doing its magic.

**Comment by IanDelMar** [comment]
@denniss03 can you confirm that the gulp watch task is working, ie compiles the CSS files when you add update eg _theme.scss?

**Comment by c4pslock** [comment]
I'm currently having the same issue. Can't seem to fix it.

**Comment by mattneal-stafflink** [comment]
@c4pslock if you see something like:

`[09:27:11] Starting 'watch'...`

That means it's waiting for you to make changes. Try jumping into one of your SCSS files, make a change and save it, then that message should be updated with something like

`[09:30:43] Finished 'sass' after 988 ms
[09:30:43] Starting 'minifycss'...
[09:30:44] Finished 'minifycss' after 905 ms
[09:30:44] Finished 'styles' after 1.89 s`

If you don't get those following messages, it most likely means your gulp isn't watching the correct files. Let me know if that's still an issue.

**Comment by c4pslock** [comment]
@mattneal-stafflink 

Wow you're right. I thought it applied to like the whole theme files other than just the SCSS files that's why I thought it wasn't working. Haha I'm such a noob. Thank You!

**Comment by mattneal-stafflink** [comment]
No worries, glad I could help!

**Comment by IanDelMar** [comment]
@dennis-soet Has your problem been solved?

**Comment by binuboston** [comment]
> No worries, glad I could help!

for me its stuck, not working :(

**Comment by binuboston** [comment]
> @dennis-soet Has your problem been solved?

noo

**Comment by bacoords** [comment]
The latest versions of Understrap no longer use gulp as a task manager. The new build process is outlined here in the readme: https://github.com/understrap/understrap#installing-dependencies

**Comment by MaysamTashakori** [comment]
tnx work for me

**Comment by MaysamTashakori** [comment]
tnx worked for me
