### ISSUE TITLE
PluginError: sass\theme.scss Error: It's not clear which file to import for '@import "assets/bootstrap4"'.

### ISSUE THREAD

**Issue by Miricon** [understrap/understrap#1240]
Hello!

I've just got this error after literally being AFK, when I came back and continued my work, saved file - started watch, this error started to occur every time I hit save. I've tried looking into it and searching, but without any luck, or to be more specific, I found this link: https://github.com/understrap/understrap-child/blob/master/css/child-theme.min.css.map but I have no clue what to do with it.
I've pasted the error billow.
Thanks.

## Issue is about..
  - [ ] a Bug Report
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** | Windows 10]
  - **Language:**  all 
  - **Node.js & NPM Versions:** Node.js [14.15.1] | NPM [4.0.2]

---

PluginError: sass\theme.scss
Error: It's not clear which file to import for '@import "assets/bootstrap4"'.
       Candidates:
         assets/bootstrap4.scss
         assets/bootstrap4.css
       Please delete or rename all but one of these files.
        on line 2 of sass/theme.scss
>> @import "assets/bootstrap4";      // <-------- Loads Bootstrap4

   ^

    at options.error (C:\xampp\htdocs\www\wp-content\themes\understrap-master\node_modules\node-sass\lib\index.js:291:26)
    at callbackTrampoline (internal/async_hooks.js:129:14) {
  status: 1,
  file: 'C:/xampp/htdocs/www/wp-content/themes/understrap-master/sass/theme.scss',
  line: 2,
  column: 1,
  formatted: `Error: It's not clear which file to import for '@import "assets/bootstrap4"'.\n` +
    '       Candidates:\n' +
    '         assets/bootstrap4.scss\n' +
    '         assets/bootstrap4.css\n' +
    '       Please delete or rename all but one of these files.\n' +
    '        on line 2 of sass/theme.scss\n' +
    '>> @import "assets/bootstrap4";      // <-------- Loads Bootstrap4\n' +
    '\n' +
    '   ^\n',
  messageFormatted: '\x1B[4msass\\theme.scss\x1B[24m\n' +
    `Error: It's not clear which file to import for '@import "assets/bootstrap4"'.\n` +
    '       Candidates:\n' +
    '         assets/bootstrap4.scss\n' +
    '         assets/bootstrap4.css\n' +
    '       Please delete or rename all but one of these files.\n' +
    '        on line 2 of sass/theme.scss\n' +
    '>> @import "assets/bootstrap4";      // <-------- Loads Bootstrap4\n' +
    '\n' +
    '   ^\n',
  messageOriginal: `It's not clear which file to import for '@import "assets/bootstrap4"'.\n` +
    'Candidates:\n' +
    '  assets/bootstrap4.scss\n' +
    '  assets/bootstrap4.css\n' +
    'Please delete or rename all but one of these files.\n',
  relativePath: 'sass\\theme.scss',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-sass',
  showProperties: true,
  showStack: false
}
[20:10:59] Finished 'sass' after 81 ms
[20:10:59] Starting 'minifycss'...
[20:10:59] Finished 'minifycss' after 256 ms
[20:10:59] Finished 'styles' after 339 ms

**Comment by IanDelMar** [comment]
Hi! The error message is pretty clear. 

>Error: It's not clear which file to import for '@import "assets/bootstrap4"'.
Candidates:
assets/bootstrap4.scss
assets/bootstrap4.css
Please delete or rename all but one of these files.

In `C:\xampp\htdocs\www\wp-content\themes\understrap-master\sass\assets\` there are two files: bootstrap4.**S**css and bootstrap4.css. bootstrap4.css shouldn't be there. I guess you either accidentally placed that file there (if so just delete it) or you customized the [gulpfile.js](https://github.com/understrap/understrap/blob/master/gulpfile.js) in such a way that bootstrap4.**S**css compiles to bootstrap4.css in the same folder (if so please provide you gulpfile).

**Comment by Miricon** [comment]
Interesting, I deleted it and there were 2 more css files I had to delete, I could not paste them there, neither I am aware of customizing the gulpfile, makes me wonder how it happend.

But it works fine now, thank you so much for the advice!
