### ISSUE TITLE
Can I removed the node_modules before launching the site?

### ISSUE THREAD

**Issue by LukeVibes** [understrap/understrap#1248]
## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** Windows 10
  - **Browser:** All
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]
  - Development: Local by Flywheel
  

---

When using All-In-One Migration or even Duplicator I get errors with my UnderStrap website (not using Child Theme as that's not working). It seems to be happening once it gets to the node modules (a guess). On top of taking up alot of space- I also worry it could be a security risk to a website. 

Can the node_modules be deleted after I finish developing the website? What else should I be deleting? 

### Other Comments

I know this community is slowly dying and support for this theme is dead so on a side note- what is everyone switching too?

**Comment by IanDelMar** [comment]
For as long as I can remember, the child theme is out of sync.

If you are not going to work on the live theme (not recommended) then yes you can delete all files related to development (node_modules, vendor, config files).

I've started to build a new theme based on UnderStrap. Unfortunately, things are not progressing as quickly as I would like. However, I add things now and then and use parts of it in small 'projects' for friends. Some are moving on to SAGE, I think. See #1218.

**Comment by LukeVibes** [comment]
@IanDelMar thanks for the reply :)

Out of curiosity- what do you think the risk is of continuing to use UnderStrap after it is being abandoned? Why is it a "bad idea" to keep using it?

**Comment by IanDelMar** [comment]
I guess at some point there won't be hardly any support. WordPress keeps adding features, deprecating functions and so on which will not be implemented in the theme. There won't be security fixed or theme improvements. Build tools will get outdated which might lead to a situation where npm install is no longer working or gulp tasks are no longer working. Of course, this will not happen tomorrow but in the long run. I doubt that there will be Bootstrap 5 support or a Gutenberg "integration". If you are using UnderStrap as the base to build your own theme upon as you did ("not using Child Theme") and you maintain the theme yourself you will get to a point at which you will choose to build other themes based on your own theme not based on UnderStrap.

**Comment by IanDelMar** [comment]
@UnderstrapFramework please close

**Comment by UnderstrapFramework** [comment]
Thanks @IanDelMar
