### ISSUE TITLE
Unsure of best approach to control styles with the customizer

### ISSUE THREAD

**Issue by benhickson** [understrap/understrap#1252]
Issue is about:
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

Hi there, hope you're doing well!

Developing a theme with your framework that will deployed on a network of sites. Each site will want to select it's own font from a list, and control the colors of different items (background, links, text, navbar, etc). We have some controls we've built in our Customizer for these, but I'm wondering the best way to integrate them into the theme? As these will be values pulled from the database on page load, it wouldn't really be possible to use gulp/sass to compile these ahead of time.

I could certainly just make a php file that gets `require`d onto the page and parses these values into CSS, but my question is: does Understrap have a defined place for this sort of file to exist within the framework? If not, should we choose a place, and maybe add it to the docs?

Any ideas on how to optimize this so that this parsed CSS can be cached by the browser locally, and the cache busted when the values change in the Customizer? That would be a nice-to-have, but not a need-to-have.

Thanks!

**Comment by IanDelMar** [comment]
Hi!
> does Understrap have a defined place for this sort of file to exist within the framework?

No, it doesn't.

> As these will be values pulled from the database on page load, it wouldn't really be possible to use gulp/sass to compile these ahead of time.

What about writing a scss file with variables and compile the CSS with https://github.com/scssphp/scssphp on save? If you don't want to bust the whole cache on each save. You would have to split between parts of the Bootstrap scss files you want to be changeable via the Customizer and such parts that are "static". You then have to load 2 CSS files. If you compile the CSS on save you could use e.g. filemtime() for cache busting.

**Comment by IanDelMar** [comment]
@UnderstrapFramework I suggest to close this issue due to lack of feedback. @benhickson feel free to reopen it.

**Comment by UnderstrapFramework** [comment]
Thanks @IanDelMar
