### ISSUE TITLE
how to change the footer text

### ISSUE THREAD

**Issue by SRD75** [understrap/understrap#1253]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Question

---

I want to customize the text that says:

*Proudly powered by WordPress | Theme: Crown Power Understrap Child by understrap.com.(Version: 0.5.3)*

In my child theme, I have:

```
if ( ! function_exists( 'understrap_add_site_info' ) ) {
	add_action( 'understrap_site_info', 'understrap_footer_info' );

	function understrap_footer_info() {
		$site_info = sprintf('<h4>&copy; Copyright 2016 - ' . date("Y") . '.</h4>');

		echo apply_filters( 'understrap_site_info_content', $site_info );
	}
    remove_action( 'understrap_site_info', 'understrap_add_site_info');
}
```
This adds the custom text, but doesn't remove the default text. How do I remove the default text please?

Thanks.

**Comment by IanDelMar** [comment]
You can either use the filter hook or the action hook.

`remove_action( 'understrap_site_info', 'understrap_add_site_info');` will do nothing as you are trying to remove an action which actually is a filter hook.

Action hook:
```php
// Remove action
remove_action( 'understrap_site_info', 'understrap_add_site_info' );

// Add new action
function slug_add_site_info() {
  echo 'My site info';
}
```

Filter hook:
```php
add_filter( 'understrap_site_info_content', 'slug_add_site_info_content' );
function slug_add_site_info_content( $site_info ) {
    return 'My site info';
}
```

Your case with filter:
```php
add_filter( 'understrap_site_info_content', 'slug_add_site_info_content' );
function slug_add_site_info_content( $site_info ) {
    return '<h4>&copy; Copyright 2016 - ' . date("Y") . '.</h4>';
}

**Comment by SRD75** [comment]
Thanks.
