### ISSUE TITLE
How to exclude Woocommerce in final dist

### ISSUE THREAD

**Issue by dekkydog** [understrap/understrap#1256]
## Issue is about..
  - [x] a Question
  - [x] I need help

I am new to Understrap. Can anyone tell me the simplest or most effective way to exclude "Woocommerce" in my final dist? As its not required for a particular build. Any help appreciated :-)

**Comment by IanDelMar** [comment]
Delete
* Line 4 in [sass/theme.scss](https://github.com/understrap/understrap/blob/44edc3d6d13a035b84ab8698e5fbb5b26c6e4bee/sass/theme.scss#L4)
* [sass/understrap/woocommerce.scss](https://github.com/understrap/understrap/blob/master/sass/understrap/woocommerce.scss)
* the [WooCommerce folder](https://github.com/understrap/understrap/tree/master/woocommerce)
* [inc/woocommerce.php](https://github.com/understrap/understrap/blob/master/inc/woocommerce.php)
* Line 31-34 in [functions.php](https://github.com/understrap/understrap/blob/44edc3d6d13a035b84ab8698e5fbb5b26c6e4bee/functions.php#L31-L34)

Alternatively, you may
* comment out/delete line 4 in [sass/theme.scss](https://github.com/understrap/understrap/blob/44edc3d6d13a035b84ab8698e5fbb5b26c6e4bee/sass/theme.scss#L4)
* comment out/delete line line 31-34 in [functions.php](https://github.com/understrap/understrap/blob/44edc3d6d13a035b84ab8698e5fbb5b26c6e4bee/functions.php#L31-L34)
* exclude WooCommerce files from the dist task in [gulpfile.js](https://github.com/understrap/understrap/blob/44edc3d6d13a035b84ab8698e5fbb5b26c6e4bee/gulpfile.js)
```diff
// Run
// gulp dist
// Copies the files to the dist folder for distribution as simple theme
gulp.task(
	'dist',
	gulp.series( [ 'clean-dist' ], function() {
		return gulp
			.src(
				[
					'**/*',
+					'!woocommerce', // excludes WooCommerce folder
+					'!inc/woocommerce.php', // excludes WooCommerce file
					'!' + paths.node,
					'!' + paths.node + '/**',
					'!' + paths.dev,
					'!' + paths.dev + '/**',
					'!' + paths.dist,
					'!' + paths.dist + '/**',
					'!' + paths.distprod,
					'!' + paths.distprod + '/**',
					'!' + paths.sass,
					'!' + paths.sass + '/**',
					'!' + paths.composer,
					'!' + paths.composer + '/**',
					'!+(readme|README).+(txt|md)',
					'!*.+(dist|json|js|lock|xml)',
					'!CHANGELOG.md',
				],
				{ buffer: true }
			)
			.pipe( gulp.dest( paths.dist ) );
	} )
);
```
* add `'!woocommerce'`and `'!inc/woocommerce.php'` to the distprod task as well

**Comment by dekkydog** [comment]
@IanDelMar - Perfect and thank you!
