### ISSUE TITLE
UnderStrap Up For Sale

### ISSUE THREAD

**Issue by UnderstrapFramework** [understrap/understrap#1258]
Hey everybody

The owner of UnderStrap has put the whole project up for sale, including:

- The domain understrap.com
- This GitHub profile
- The WordPress.org listing for the theme and child
- The GumRoad account that sells the premium themes
- Email list of 50k live address
- Twitter account
- Pretty much everything attached to the project

If you are interested you can check out the Flippa listing here:

https://flippa.com/10806173-e-commerce-internet

Let me know if you have any questions and I'll do my best to answer them

Alex

**Comment by Thomas-A-Reinert** [comment]
This is ridiculous  in SO many aspects..

> UnderStrap was a free Bootstrap+WordPress starter theme that we took over and turned into a fremium product.
- There is no "_was_". UnderStrap weas and still is an open-source theme. 
- There is no "_we_". You bought/took over and never did anything mentionable about it. The community did.
- What you´re trying to sell here is:
  - Admin priviledges to the git-repo so that the new owner can update/merge etc.
  Stuff you never did and/or only did ´pon request/mention
  - Some "_premium (child) themes_"
  (NO "premium themes", you´re selling child themes here, in fact!)
  - "_Pretty much everything attached to the project_"
  So that includes but excludes? You´re not getting to the point here. This is pretty vague as almost every other of your statements from beginning on has been.

> Net Profit $1,496 p/mo

Really? I wish I had such a job just by doing N.O.T.H.I.N.G.
What was your investment? I really miss that point.

> Daniel Morton

Who is that  -  another member of your "mystery network"?

**Final note:**
Well I´d suggest giving up and giving that project back to the community. To any of the original contributors like @IanDelMar  or whoever. You know who. You tried to invest, you failed. Keep the premium themes and the GumRoad account for yourself. 
They´re extremely low quality anway, never got updated, got bugs galore and can´t be part of the deal therefore (According to user comments).

**Comment by pattonwebz** [comment]
Asking price of $48k is more than a tad out of the range I would be willing to invest in a community project I am afraid :(

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz  - he´s not asking the price for the community project. He claims that for the added value through (neglected) "premium child themes" and a way to (not) sell them. Based on the community project, sure. So basically that means: If noone is going to claim the (not interesting) addons, the community project will also die. And I regret, but I guess that guy will never donate anything back to the community.

**Comment by pattonwebz** [comment]
@Thomas-A-Reinert you are correct in that is what is being sold. It is not what a buyer is buying though - they are buying the community and in my view that is where the value that dictates that pricetag comes from :)

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz  - yes, that´s totally correct. And guess where the community went, when he took over? You can track that by watching pull request since 2018. Where it was there and where it went from that time on.. 
Conclusion: He´s never been into the community and/or support it and/or it´s input. And that´s exactly why he miserably failed. And another point why he didn´t value THAT from early on.

**Comment by pattonwebz** [comment]
I might be willing to pay 3x the monthly revenue but probably not more than that. There is a significant maintenance burden on it and 1.5k is not enough income to cover the costs of my family for a month.

**Comment by IanDelMar** [comment]
FYI

![image](https://user-images.githubusercontent.com/42134098/116346036-aa38cd80-a7e9-11eb-9e54-207e89ab4cf3.png)
![image](https://user-images.githubusercontent.com/42134098/116346064-c0468e00-a7e9-11eb-96ef-14db927213cf.png)

**Comment by UnderstrapFramework** [comment]
Daniel Morton is the person that owns the site, I was contracted in to help build it up until mid-2020 when I move onto something else

With the right love, the site could continue to grow (I would personally build the BS5 version of UnderStrap but its not up to me!), unfortunately I didn't set the price and if I had any money I would make a sensible offer

You can see the sites original purchase on Flippa (August 2019~) when Holger sold it:

https://flippa.com/10252986-services-internet

Surprised you guys never noticed it in the first place!

**Comment by dekkydog** [comment]
I would love to see understrap's continued development here. I would even be willing to chip in financially for the right person or people to maintain it.... but 49K! really?

**Comment by UnderstrapFramework** [comment]
You are welcome to submit offers on Flippa, do keep in mind that Holger originally sold it for $15k+ back in late 2019 so I'm sure the owner will want to at least get back that investment + the added value since

**Comment by 0dp** [comment]
Get fucked you piece of shit

**Comment by pattonwebz** [comment]
The revenue charts show a pretty scary downturn in revenues with no added value in the last year or so. Surely there were certainly higher costs than $169 in many of those months. Unless no employees are factored in and there is no value on someone's time the costs are inaccurate.

I might have been willing to put in $1500 before seeing the huge fall in the last few months. Now I would only be able to offer $975 - if someone wants to pool the values and do an ownership split let me know. Otherwise, I am not able to take the risk.

**Comment by IanDelMar** [comment]
@pattonwebz I doubt that Daniel Morton will sell it for anything like that. It seems as he bought it at $15,100.

However, I'd go for a shared ownership if all people involved mostly share the same opinions and ideas on how to proceed with the project.

**Comment by pattonwebz** [comment]
@IanDelMar Yeah I get that it's an offer unlikely to be acceptable. I am ok with that as the work needed here to increase revenues on the commercial side is pretty massive over the next year or 2. They will continue to go down in the short term so it's a long term play with a risky outcome long term.

**Comment by axlright** [comment]
No one is going to pay any substantial  money for that small amount of
declining revenue. It's a joke. I don't care what someone paid for it. That
is irrelevant. What is it worth? What's the actual inherent value. Pretty
much zero.

This is all an insult to the community of people who built the project.

It'd be cheaper and easier to start over.

**Comment by meemal** [comment]
Aw man! I picked a sucky time to start a project with this clearly!

**Comment by UnderstrapFramework** [comment]
I wouldn't worry too much, the current people offering to buy the project are talking about investing heavily in the development

**Comment by pattonwebz** [comment]
> investing heavily in the development

I hope they follow through with that :)

**Comment by HelloUnlimitedWP** [comment]
We have an interest in taking over this project. We have used Understrap on too many projects to count at our white label WP agency (https://unlimitedwp.com) We would like to contribute back to the community. 

We would love to talk with some of the core contributors over a quick Zoom. Anyone up for it? @IanDelMar @pattonwebz @axlright @0dp @stef-k @dekkydog @Thomas-A-Reinert and others.

**Comment by Thomas-A-Reinert** [comment]
@HelloUnlimitedWP  – Feel free to set a date (add timezone!) like 3 days at least in advance and I´ll try to address any of the original core contribs asap. I´ll just try to make sure they don´t miss that post/date, cos i think that _might_ be interesting.
Afaik most of us live in europe, so please take that into consideration for an appointment. Cannot assure that everyone will be present, though. And have never ever heard of anyone named @dekkydog in context of UnderStrap. Feel free to add other ppl in case you feel the need.

Zoom etc. ain´t an option for me, cos I don´t install spyware/security holes and I guess/hope the others alike.
But I still run/own the Slack-Channel at https://understrapworkspace.slack.com/archives/CBJJAUKR8 . We can also run a private chan then, if needed.

Question: Are you the one that´s "_talking about investing heavily in the development_" ? You  don´t need to answer that here.

PS: In case anyone is bidding for this repo – please take into consideration that "someone" needed less than one year to f*ck up this projects brand, roadmap, reputation and sustainability.

For me, that would be at least a 15.000£ worth loss of value.

**Comment by Thomas-A-Reinert** [comment]
Well, @HelloUnlimitedWP  - sent you mail, info via contact form etc.
And it´s accessibility is .. WELL I WOULD CONSIDER THAT CONCEPT FOR A CONTACT FORM!
(To be honest: It failed. max.)

**Comment by dekkydog** [comment]
.... And have never ever heard of anyone named @dekkydog in context of UnderStrap....

Hey, nor have I... news to me. But I do appreciate the mention :-) I am merely someone who would like to see the ongoing development of Understrap remain in the open-source community.

**Comment by HelloUnlimitedWP** [comment]
Thank you, Thomas. I emailed you.

**Comment by nico-pps** [comment]
So @HelloUnlimitedWP did buy it in the end ? i'm a bit lost here in between the great projet i used to build many sites and the commercial counterpart that is sending me newsletters... i'd be glad to have some clear vision on the future in order to decide if i start learning another framework or if i can hope to continue using this one. 
Thanks for any information ;)
Cheers from belgium

**Comment by HelloUnlimitedWP** [comment]
@nico-pps We had a genuine interest in buying and were doing our due diligence for the past few days. To the current owner, we shared some details being transparent about what we plan to do. We didn't want to monetize on paid themes (which the current owner tried and failed). 

To our surprise, there is a newsletter email sent today to all subscribers about outpress.dev being behind Understrap when the domain itself was registered yesterday for the website. They copied our entire website, model, and content word by word. I approached them and they said they are testing our model. This is so unprofessional that we will be backing out of the deal. Sorry, with our team of 54 WP developers, we thought we can really help the theme we have used 100's of times but it's too big of a risk now.

**Comment by nico-pps** [comment]
@HelloUnlimitedWP is outpress.dev the current owner of understrap.com ? 
I'm feeling more and more confused by all of this

**Comment by HelloUnlimitedWP** [comment]
@nico-pps Outpress.dev is something current owner just made up in last one day

**Comment by pattonwebz** [comment]
@HelloUnlimitedWP I am sorry to hear that the current owner of this project has cloned your website, business model and content. That is pretty much the worst thing that they could do to an interested buyer. :(

**Comment by nico-pps** [comment]
@HelloUnlimitedWP Jeez... all of this seems quite fucked up. 
I am correct if i say that understrap is based on open source elements ? Wouldn't be simpler to fork a community version ? Or am i too naive ? Sorry for all the questions but i have a personal interest in having this tool in my toolbox professionally speaking

**Comment by pattonwebz** [comment]
@nico-pps it is open source and someone could fork it and work on it in a different repo. There are already some forks that exist but I do not think they are active from my last checks.

The issue is that the community doesn't necessarily go with the new fork and new branding and awareness needs built on the new fork. It is usually simpler to start a new project in that sense.

**Comment by 0dp** [comment]
This is getting more and more absurd. @HelloUnlimitedWP  truly sorry to hear that.

@nico-pps some thought have been given to this. if people are interested, the plans can be relaunched.

**Comment by nico-pps** [comment]
@0dp @pattonwebz @HelloUnlimitedWP 
i'd be interested if this happens, of course. But i'm not good enough in coding to help in developing the project unfortunately...

**Comment by pattonwebz** [comment]
The development of code in a project is only one part. Documentation, testing and using are equally large parts :)

**Comment by nico-pps** [comment]
@pattonwebz :)
i'm good at asking questions... and up for trying things.

**Comment by axlright** [comment]
@HelloUnlimitedWP <https://github.com/HelloUnlimitedWP> that is totally
absurd. You did the right thing backing out.

I'm sincerely interested in working on a new version. I am much better at
documentation than programming.

I'd like to propose that all the interested parties here get together to
discuss what an ideal future of UnderStrap 2.0 (with a new name, or maybe
that name to help with brand recognition) looks like to everyone. What sort
of features would it have? Who is it for?

@Thomas-A-Reinert has a Slack channel we could use. I know he's suspicious
of online video meetings but perhaps we could find a video or chat platform
that works for people.

**Comment by pattonwebz** [comment]
As someone heavily involved in themes for WordPress I would like to say that I do not see forking this project and building from it as an ideal way to handle the community aspect of the project. Themes are changing (pretty substantially) towards being block-based and starting fresh (perhaps with inspiration from understap) is probably the best way forward. Just my 2-cents - I don't really have enough time right now to be a big player in any new project that gets underway.

**Comment by nico-pps** [comment]
I also was wondering if bootstrap is the right base in 2021 ? since these events, i've been reading a lot about more modern ways of making responsive design (ie tailwind)... But as i said, i'm not trained as a programmer... i'm a graphic design who ended up doing a bit of dev...

**Comment by axlright** [comment]
@pattonwebz The current block-based flow is what interests me the most. @nico-pps I think that Bootstrap is a pretty big draw for a lot of the developers who are interested in this kind of tool.

**Comment by IanDelMar** [comment]
> @nico-pps We had a genuine interest in buying and were doing our due diligence for the past few days. To the current owner, we shared some details being transparent about what we plan to do. We didn't want to monetize on paid themes (which the current owner tried and failed).
> 
> To our surprise, there is a newsletter email sent today to all subscribers about outpress.dev being behind UnderStrap when the domain (outpress.dev) itself was registered yesterday for the website. They copied our entire website, model, and content copied word by word. I approached them and they said they are testing our model. This is so unprofessional that we will be backing out of the deal. Sorry, with our team of 54 WP developers, we thought we can really help the theme we have used 100's of times but it's too big of a risk now.

This is just crazy and an absolutely disgusting behaviour. @HelloUnlimitedWP are you considering legal actions?

outpress.dev seems to be based in the UK which sounds like "Alex" as the "owner", Daniel Morton, seems to be based in Canada. @UnderstrapFramework in 2019 you, Alex, claimed to have had bought UnderStrap. 
>My name is Alex. I am 32 years old and live in the North of England. I am a self taught IT programmer working mainly in PHP. I have been working for 10~ years starting and building websites for myself or for clients. I first used Understrap 3 years ago and have used it several times since. As with other users, it saved me a lot of time and was a go to resource for me. I found it listed for sale on Flippa earlier this year and given my experience with UnderStrap thought it was a good resource to build a business on.

Do you remember? No? Then have a look at https://github.com/understrap/understrap/pull/1073#issuecomment-563968372.
Someone is a f*cking liar. I'm not interested in playing Cluedo on Github to find out who murdered UnderStrap.

@axlright Me too. I have already started working on something new which has not reached a presentable stage yet. I hope for more time in summer to more or less finish a first version.

**Comment by axlright** [comment]
@IanDelMar great to see you fired up. You deserve to be. @UnderstrapFramework is indeed a fucking liar.

@pattonwebz I wonder if _s is the right platform. Bootstrap linked with a more modern block based "empty" theme framework seems pretty compelling to me.

**Comment by HelloUnlimitedWP** [comment]
@IanDelMar no not considering any legal action at the moment. I think it will not be worth it in terms of time. Just copying the website and model is not enough anyways. It's just that I am shocked to see such a stupid act. 

Also very disappointed as we were super excited to take over in the last few days. I even emailed to @Thomas-A-Reinert  yesterday asking for time to chat as I wanted to understand where the community likes to see this project go and we were willing to take that road. We even made internal plans about a block-based theme as the new separate parent theme. We could still do that but without the name and traction that Understrap has, it would be too difficult to make it mainstream.

We will be keeping an eye on new developments and try our best to get involved.

**Comment by IanDelMar** [comment]
@HelloUnlimitedWP well, copying a website word by word sounds pretty much like a copyright infringement to me - but I'm not a lawyer. However, I do see your point.

**Comment by Thomas-A-Reinert** [comment]
Wow this really became dadaistic in the past few hours. It shows the ethos of the new owner.
Yes, it´s a copyright infringement and theft of intellectual property. I just had the [wayback machine archive](https://web.archive.org/web/20210505205236/https://outpress.dev/) the actual state of this site as proof.

What a pity that it changed to those people instead of @HelloUnlimitedWP - he answered my mail and has some serious plans for the project as it seems.

@nico-pps  - I use Tailwind daily on my job. It´s a nice CSS framework but has no built-in functionality in comparison to Bootstrap. Bootstrap also has a good focus on accessibility/WCAG that no other framework I know has. But you can also combine both, import single functions from Bootstrap for your project and style it with Tailwind. Please note that Tailwind also has a lot of downsides I won´t address right here.

**Comment by meemal** [comment]
Wow, this thread is quite confusing, has it been bought again?  Will it be maintained?!  I've used understrap (child theme) once before and thought I would try it again for a new site.  I'm probably about 14 hour dev time in which is a fair time investment but wondering whether to jump ship having seen all of this!

If you were me would you swap to another starter theme?  
Are you able to recommend a really lightweight alternative that is actually maintained?

I love the fact that understrap is just ready to go with gulp and sass as I'm not majorly confident with setting that up myself. 
 But I guess if I switch to another starter theme that uses bootstrap much of what's been developed so far can be reused.

**Comment by smirnizky** [comment]
Hello, @meemal !  You're right. I think too that Understrap in its current state seems not to be a reliable tool for implementing long-term projects .We can only wait for a new project from the same developers who created Understrap. Of course if they find the time to do this.
While waiting for "Understrap reborned" ("Understrap 2.0", "Bootscores" or another name chosen by the community ) You can try Sage theme from roots.io.

**Comment by findozor** [comment]
@meemal found this one https://github.com/craftwerkberlin/bootscore-5  its pretty good looking? but i have concerns about its development because of this comment https://github.com/craftwerkberlin/bootscore-5/issues/3

**Comment by axlright** [comment]
I love that this thread was posted by the current owner of the repo to try
to drum up sales leads and it has turned into 1) a bashing of the current
owner and 2) a discussion of other alternatives. Didn't turn out quite like
he thought it might. But that's what you get when you destroy a community
developed project and steal the entire website of the only person who might
pay good money for it. And of course, now this whole thread is archived and
comes up in search results.

#karma

**Comment by schutzsmith** [comment]
The new fork absolutely has to be named Blunderstrap!

I too am willing to help on the fork. Have used Understrap on countless high traffic websites over the years and now need to consider that all could be compromised if the parent theme is updated. Which I guess is always the case, but still, this is some next level hitchcock stuff.

**Comment by 0dp** [comment]
I have an amazing name for a new block based bootstrap theme. Unfortunately, it's seems a bit risky coming up with food ideas in here these days lol

**Comment by pattonwebz** [comment]
If someone wants to start a new project from scratch I am up for helping out with code review and submitting some patches. Feel free to ping me there is you do it :)

**Comment by 0dp** [comment]
> > > I have an amazing name for a new block based bootstrap theme. Unfortunately, it's seems a bit risky coming up with good ideas in here these days lol
> > 
> > 
> > Jockstrap?
> 
> Too obvious... in light of this feed...Carcrashstrap? I'm open to ideas!

Seatbelt

**Comment by Thomas-A-Reinert** [comment]
To be honest, I don´t feel like joing about names. Situation is too fucked up imho to joke about.
So please: Get back to business!

**Comment by 0dp** [comment]
So let's try and arrange a time and place (slack?) where we can talk realtime

**Comment by schutzsmith** [comment]
Wow, closed it!

**Comment by smirnizky** [comment]
I decided to subscribe to all the core developers. I don't think I'll miss the news this way.

**Comment by Thomas-A-Reinert** [comment]
Well, don´t get me wrong, please @smirnizky .

But I think that all of the former Core Devs have already abandoned the sinking ship.
No Roadmap/No precise instructions === No community support for this project.

Don´t get me wrong - it won´t hurt to subscribe to us. But it probably won´t help. Honestly, @IanDelMar ´s repo may be the one that´s most up to date. Don´t count on any further updates though.

**Comment by Thomas-A-Reinert** [comment]
Btw: I re-opened that issue. Let´s witness if Alex/UnderstrapFramewok dares to close it again.
Until now I guess... it must have been some kind of un-intended problem.

**Comment by noelspringer** [comment]
Yes Alex Booth is the owner of the plagiarized site and also another domain with the same plagiarized content.
https://www.linkedin.com/in/alex-presstasks/

Other uses have already eloquently echoed my sentiments e.g. https://github.com/understrap/understrap/issues/1258#issuecomment-828351035

For a block based theme [Kadence](https://wordpress.org/themes/kadence/) is worth a look:

* Well organized file architecture
* Includes sass files `assets/css/src`
* Very customizable
* Excellent Gutenberg features
*  Works with Woocommerce

Downsides:
* No Bootstrap (but still worth a look)
* Built in support for popular LMS etc. could be considered bloat (or a bonus) depending on the project.

Whether or not a well implemented, block based theme is needed depends on the requirements of the end user and the type of content they need to enter.

Personally I prefer CSS/Sass over a GUI but with the needs of the end user in mind there will be cases where a block based theme is the best solution. My 2c.

**Comment by iwasthesword** [comment]
> Btw: I re-opened that issue. Let´s witness if Alex/UnderstrapFramewok dares to close it again.
> Until now I guess... it must have been some kind of un-intended problem.

The solution was to hide the issues tab

**Comment by howarddc** [comment]
Hi all, hope you're doing well!

I'm Rob Howard, the CEO of Howard Development & Consulting, a web development firm in Denver. I've acquired the ownership/management of the UnderStrap project as of this morning, and just wrote an intro post (including my direct contact info and calendar link) as a new Issue here:

[https://github.com/understrap/understrap/issues/1268](https://github.com/understrap/understrap/issues/1268)

Also, Issues are open again 🙂   I will close this one with this comment, but I encourage you to communicate honestly and openly in Github, and we won't shut down Issues or limit reasonable communication in the future, whether it is positive or negative.

Check out the full announcement here: [https://github.com/understrap/understrap/issues/1268](https://github.com/understrap/understrap/issues/1268)
