### ISSUE TITLE
Strip out all the Contact Form 7 rules from Theme.css 

### ISSUE THREAD

**Issue by danielmrey** [understrap/understrap#1260]
## Issue is about..
  - [x] a Question

## Please tell us about your environment:

Hi:

I am using the last release of Understrap 0.9.4 and I would like to strip out all the Contact Form 7 rules from theme.css (and use it later in my child by deregister/enqueue). It seems that both sets of rules, Bootstrap 4 and Contact Form 7, are merged and intertwingled so there is no way to completely separate them in a clean way. I don't know SASS.

Is there a way of having 2 CSS's, one with "theme minus cf7" and another with "only cf7" rules?

Sorry if I posted this in the wrong area.

Thank you.

**Comment by noelspringer** [comment]
Hey @danielmrey!

Are you using UnderStrap from wordpress.org (v0.9.4) or the most up-to-date version from this repository?

**Comment by noelspringer** [comment]
If you are using this repository you could:

### Easy way

* The `sass` directory has a file `sass/theme/_contact-form7.scss`.
* This file is enqueued last in the `theme.scss` file so any code in the `_contact-form7.scss` will be compiled last.

So make whatever changes you want to the  `_contact-form7.scss` file and rebuild the css.

### Hard way

Use a child theme and copy over the relevant sass files from the parent.

1. In `sass/theme.scss` comment out line 11 `@import "theme/contact-form7";`
2. Rename `sass/theme/_contact-form7.scss` by removing the preceding underscore i.e. `contact-form7.scss`.
3. Recompile css and you will now have a separate `contact-form7.css` file.
4. Enqueue the new CF7 file in your child theme's `functions.php`

**Comment by bacoords** [comment]
I think @noelspringer has fully answered this, so I'm closing now. To recap, if you want to mess with CSS, a child theme really is your safest bet. 

https://github.com/understrap/understrap-child
