### ISSUE TITLE
Overlay menu in CORE template not scrolling properlly in mobile phones

### ISSUE THREAD

**Issue by el-sphere** [understrap/understrap#1262]
## Issue is about..
  - [ ] a Bug Report

## Steps to reproduce?

Try to scroll up and down the overlay menu of the CORE template demo with an iphone. You will notice the scrolling is sluggish and soon enough you will be scrolling the content below the menu.

Any help to fix this is welcome.

**Comment by bacoords** [comment]
This issue is related to a paid child theme, not the Understrap open source project, so I'm going to close it.

FWIW we couldn't replicate, but if you reach out here with a link to your site, we can investigate further: https://understrap.com/contact/
