### ISSUE TITLE
Replace standard mobile menu with custom

### ISSUE THREAD

**Issue by chrisjim2000** [understrap/understrap#1266]
Hey guys, I have started building a wordpress site with understrap and I want to replace the standard mobiile menu with a custom one but I can’t find any ways to do it.
Does anyone knows if it is possible and how?

thank you very much in advance.

**Comment by 0dp** [comment]
Hi friend, maybe if you show us what you'd like to accomplish we can help ya out

**Comment by chrisjim2000** [comment]
I have built a sidemenu with bootstrap (which is vertical and takes 100% of screen height) and I want to set it as the default mobile menu instead of the standard one while keeping functionallity the same. So, i would like to find the code of the original mobile menu and replace it with my own but i can't find it.

**Comment by pattonwebz** [comment]
There isn't code specifically for mobile menu and separate code for the desktop menu. It is only one menu for both and style rules + some JS handle the mobile variant.

What you'll have to do is hide the default menu and add a 2nd menu in your vertical sidebar

**Comment by chrisjim2000** [comment]
I have linked my menu to the button which opens it and I have used wp_nav_menu fucntion to recreate the menu. The issue is that the active links are not highlighted

**Comment by chrisjim2000** [comment]
Also the mobile menu that I have created is a modal which is triggered by a button. Is this a good technic or should I do something else?

**Comment by 0dp** [comment]
The modal part should be fine.
As Patton said, you need to hide the desktop menu when on mobile view. Then show the trigger for the new menu.
If you show a bit of code it might be easier to specify

**Comment by Thomas-A-Reinert** [comment]
Well why should be all be looking into our crystal balls when you could/should show us your code and a demo of your solution? That would be analyzable and you´d have a possible solution at hand prolly fast I guess.  With the info we got right now, we´re wasting time guessing.

Having a modal pop up for a menu ain´t a solution for me in 99% of all cases concerning WCAG/ADA/BITV/whatever your national accessibility initiative is called.

No demo code - no solution I´d say and would love to close that issue

**Comment by danemorgan** [comment]
This looks like a request for how to implement in a child theme, but without enough information to answer.

I'm closing this now, but if you still need help, please submit a new request with more details.

**Comment by Thomas-A-Reinert** [comment]
Well, this issue has been raised more than 1.5 months ago. No reply since then. I´d say, let´s close this issue.
There´s some part of integration/customization available though on http://usdocu.tarthemes.com/docs/0.8.2/extend/custom-menus-and-menu-areas/ . But that´s just a start, not a full solution, which could be extended easily though.
