### ISSUE TITLE
WooCommerce suggestions

### ISSUE THREAD

**Issue by cmbibby** [understrap/understrap#1290]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [X] a Suggestion
  - [ ] a Question
  - [ ] I need help

Good to see some life being breathed back into this project. I've been using Understrap sicne the early days and one of the things that attracted me in the first place was WooCommerce integration out of the box.

I have some suggestions that may be worthwhile to add to the project moving forward that would make it better for people looking for a great starter for a WC project.

1. Use the BS grids for the archive pages.
2. Extend the WC alerts to match BS alerts
3. Change the default WC Tabs in single-product to BS Accordions(??)
4. Maybe filter the BS button classes used in the template files so you don't have to remove outline in each template if you don't want to use outline buttons.

**Comment by bacoords** [comment]
Thanks! There's a few other issues about updating WooCommerce support, which I think will be a bigger focus after we've gotten better BS5 and Gutenberg support out the door. I know there's a lot of talk about moving to using more of WC's filters and less overriding of templates, so I see now issue with 2 & 4. On the other hand, that would make 1 & 3 less ideal, but who knows. That's still in discussion. 

https://github.com/understrap/understrap/issues/1218
https://github.com/understrap/understrap/issues/1138

**Comment by bacoords** [comment]
Followup on this

> Use the BS grids for the archive pages.

We don't do this on normal archives, so I'm going to say let's not do this to Woocommerce archives

> Extend the WC alerts to match BS alerts

Adding a PR for this now

> Change the default WC Tabs in single-product to BS Accordions(??)

I would say this is custom dev territory.

> Maybe filter the BS button classes used in the template files so you don't have to remove outline in each template if you don't want to use outline buttons.

I like this idea but we use two types of buttons (primary and outline-primary) so we'd actually need two separate filters, which starts to feel a little cumbersome. Interested in more thoughts on this.

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).

For any of the ideas that weren't incorporated, I'd recommend adding them to the Discussions tab.
