### ISSUE TITLE
WooCommerce 5.4.1 outdated template file form-pay

### ISSUE THREAD

**Issue by krisp3t** [understrap/understrap#1297]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.7.2
  - **WooCommerce Version:** 5.4.1

---

# Issue Overview for Bugreports
WooCommerce template file `form-pay.php` is outdated.

Error message:

> `understrap/woocommerce/checkout\form-pay.php` version 3.6.1 is out of date. The core version is 5.2.0

**Comment by danemorgan** [comment]
We have a few Woocommerce templates that are outdated. Our current goal is to have these updated in the next release.

**Comment by mindstomedia** [comment]
Does this being outdated cause a delay in adding items to cart? I’m having this problem with UnderStrap vs other themes where it takes 1-2min for items to be added whereas stock themes are instant

**Comment by bacoords** [comment]
It's possible - we're hoping to get this update out soon. Here's the latest template on the branch we're hoping to deploy: https://github.com/understrap/understrap/blob/update/woo-templates/woocommerce/checkout/form-pay.php

Feel free to just manually override it temporarily if needed.

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
