### ISSUE TITLE
Update Margins and paddings to Bootstrap $spacer

### ISSUE THREAD

**Issue by danemorgan** [understrap/understrap#1299]
## Issue is about..
  - [X] a Suggestion

# Suggestion
As it says on the tin. I think we should go through the theme and update margins and padding to use Bootstrap $spacer unless that is clearly inappropriate for the context.

For instance, alignleft and alignright are currently set with margins of 1.5rem. This should be $spacer instead.

**Comment by 0dp** [comment]
In general, where applicable 👍

**Comment by 0dp** [comment]
#1295

**Comment by 0dp** [comment]
#1294

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
