### ISSUE TITLE
The language flags of the menu items of the Polylang plugin are not visible.

### ISSUE THREAD

**Issue by ramedey** [understrap/understrap#1305]
## Issue is about..
  - [X] a Bug Report
  - [X] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.7.2
  - **Polylang Version**: 3.0.6
  - **UnderStrap Version**: 0.9.6 

---

# Issue Overview for Bugreports

The language flags of the menu items of Polylang are not visible. The menu item HTML markup is there but the image element is not.

## Steps to reproduce?
This is what I did to reproduce it:

1- Create a new fresh Wordpress site
2- Install Understrap theme
3- Install Polylang and add English and Dutch
4- Add translation to the sample page
5- Add language switcher to the top menu (with the language flag option)
6- Check the result in the Twenty Twenty One theme. The flag image is visible, everything is fine.
7- Switch to Understrap theme
8- Check the website again. This time the flag is not visible.

Could you please help?

Thank you for considering my request.

**Comment by bacoords** [comment]
Do you have this on a live site we can look at?

**Comment by ramedey** [comment]
I have created a live site that reproduces the issue:

Url: https://testunderstrap.000webhostapp.com/
user: admin
password: testunderstrap

The active theme is Twenty Twenty-One. You will see the flag in the top menu, and you can click and switch from English to Dutch. Everything works as expected.

The Understrap theme is installed, I'd suggest you activate it to se what happens. FYI, I didn't modify any file.

When you switch to the Understrap theme you will notice that the menu item is still there (you can hover over it or just check the HTML), but the actual flag image is gone.

Please let me know if you have any more questions.

Thanks for your help.

**Comment by bacoords** [comment]
I was able to track down the issue to this filter right here: 
https://github.com/understrap/understrap/blob/main/inc/extras.php#L159
```php
// Escapes all occurances of 'the_title()' and 'get_the_title()'.
add_filter( 'the_title', 'understrap_kses_title' );
```

Essentially we're stripping some HTML from the_title, which is a filter that also happens to run when building the HTML of a  navigation menu. This causes the flag image icons to be removed. You can probably fix this by either:

1 - Removing the filter in a child theme.

2 - Overwriting the function with something like this (untested) in a child theme:

```php
function understrap_kses_title( $title ){
    return $title;
}
```

3 - Or you can use the filter `understrap_kses_title` to add image tags to the array of allowed HTML.

I wonder if others think this is a bigger issue and we should reevaluate the `understrap_kses_title` function?

**Comment by ramedey** [comment]
Yes, that was the problem.

I have tried all 3 solutions, they all work. For the third solution there is one extra step. If you add the image tag to the array of allowed HTML, the image is not displayed:

```php
        /**
	 * Sanitizes data for allowed HTML tags for post title.
	 *
	 * @param string $data Post title to filter.
	 * @return string Filtered post title with allowed HTML tags and attributes intact.
	 */
	function understrap_kses_title( $data ) {
		// Tags not supported in HTML5 are not allowed.
		$allowed_tags = array(
			'abbr'             => array(),
			'aria-describedby' => true,
			'aria-details'     => true,
			'aria-label'       => true,
			'aria-labelledby'  => true,
			'aria-hidden'      => true,
			'b'                => array(),
			'bdo'              => array(
				'dir' => true,
			),
			'blockquote'       => array(
				'cite'     => true,
				'lang'     => true,
				'xml:lang' => true,
			),
			'cite'             => array(
				'dir'  => true,
				'lang' => true,
			),
			'dfn'              => array(),
			'em'               => array(),
			'i'                => array(
				'aria-describedby' => true,
				'aria-details'     => true,
				'aria-label'       => true,
				'aria-labelledby'  => true,
				'aria-hidden'      => true,
				'class'            => true,
			),
			'code'             => array(),
			'del'              => array(
				'datetime' => true,
			),
			'ins'              => array(
				'datetime' => true,
				'cite'     => true,
			),
			'kbd'              => array(),
			'mark'             => array(),
			'pre'              => array(
				'width' => true,
			),
			'q'                => array(
				'cite' => true,
			),
			's'                => array(),
			'samp'             => array(),
			'span'             => array(
				'dir'      => true,
				'align'    => true,
				'lang'     => true,
				'xml:lang' => true,
			),
			'small'            => array(),
			'strong'           => array(),
			'sub'              => array(),
			'sup'              => array(),
			'u'                => array(),
			'var'              => array(),
			'img'              => array(
				 'src' => true,
				 'alt' => true,
				 'style' => true,
				 'width' => true,
				 'height' => true,
			),
		);
		$allowed_tags = apply_filters( 'understrap_kses_title', $allowed_tags );

		return wp_kses( $data, $allowed_tags);
	}

```

The "data:" part of the base64 URI is removed:

```html
<img src="image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAFXSURBVHjaYvzPgAD/UNlYEUAAkuTgCAAIBgJggq5VoAs1qM0vdzmMz362vezjokxPGimkEQ5WoAQEKuK71zwCCKyB4c//J8+BShn+/vv/+w/D399AEox+//8FJH/9/wUU+cUoKw20ASCAWBhEDf/LyDOw84BU//kDtgGI/oARmAHRDJQSFwVqAAggxo8fP/Ly8oKc9P8/AxjiAoyMjA8ePAAIIJZ///5BVIM0MOBWDpRlZPzz5w9AALH8gyvCbz7QBrCJAAHEyKDYX15r/+j1199//v35++/Xn7+///77DST/wMl/f4Dk378K4jx7O2cABBALw7NP77/+ev3xB0gOpOHfr99AdX9/gTVASKCGP//+8XCyMjC8AwggFoZfIHWSwpwQk4CW/AYjsKlA8u+ff////v33998/YPgBnQQQQIzAaGNg+AVGf5AYf5BE/oCjGEIyAQQYAGvKZ4C6+xXRAAAAAElFTkSuQmCC" alt="Nederlands" width="16" height="11" style="width: 16px;height: 11px">
```

We need to add the "data" protocol to the array of allowed protocols because it is not included by default:

```php
function allow_data_protocol( $protocols ){
    array_push($protocols, 'data');
    return $protocols;
}
add_filter( 'kses_allowed_protocols' , 'allow_data_protocol' );
```

Now the base64 URI is correct:

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAALCAIAAAD5gJpuAAAABGdBTUEAAK/INwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAFXSURBVHjaYvzPgAD/UNlYEUAAkuTgCAAIBgJggq5VoAs1qM0vdzmMz362vezjokxPGimkEQ5WoAQEKuK71zwCCKyB4c//J8+BShn+/vv/+w/D399AEox+//8FJH/9/wUU+cUoKw20ASCAWBhEDf/LyDOw84BU//kDtgGI/oARmAHRDJQSFwVqAAggxo8fP/Ly8oKc9P8/AxjiAoyMjA8ePAAIIJZ///5BVIM0MOBWDpRlZPzz5w9AALH8gyvCbz7QBrCJAAHEyKDYX15r/+j1199//v35++/Xn7+///77DST/wMl/f4Dk378K4jx7O2cABBALw7NP77/+ev3xB0gOpOHfr99AdX9/gTVASKCGP//+8XCyMjC8AwggFoZfIHWSwpwQk4CW/AYjsKlA8u+ff////v33998/YPgBnQQQQIzAaGNg+AVGf5AYf5BE/oCjGEIyAQQYAGvKZ4C6+xXRAAAAAElFTkSuQmCC" alt="Nederlands" width="16" height="11" style="width: 16px;height: 11px">
```

Thank you very much for your help!

**Comment by bacoords** [comment]
@ramedey Thanks for digging into this!

What do others think about adding a 'Compatibility' section to the documentation where we can just track issues like this for future users? 

On a side note we've been working with WPML to test compatibility and it looks like we're in good shape there.

**Comment by piotrszczesniak** [comment]
> I was able to track down the issue to this filter right here: https://github.com/understrap/understrap/blob/main/inc/extras.php#L159
> 
> ```
> // Escapes all occurances of 'the_title()' and 'get_the_title()'.
> add_filter( 'the_title', 'understrap_kses_title' );
> ```
> 
> Essentially we're stripping some HTML from the_title, which is a filter that also happens to run when building the HTML of a navigation menu. This causes the flag image icons to be removed. You can probably fix this by either:
> 
> 1 - Removing the filter in a child theme.
> 
> 2 - Overwriting the function with something like this (untested) in a child theme:
> 
> ```
> function understrap_kses_title( $title ){
>     return $title;
> }
> ```
> 
> 3 - Or you can use the filter `understrap_kses_title` to add image tags to the array of allowed HTML.
> 
> I wonder if others think this is a bigger issue and we should reevaluate the `understrap_kses_title` function?

I used the second fix and it works just fine! Thx :)
