### ISSUE TITLE
How to limit excerpt_length?

### ISSUE THREAD

**Issue by nvjacobo** [understrap/understrap#1311]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.7

---

# How to limit excerpt_length?

I am triying with :

functions.php

```
function tn_custom_excerpt_length( $length ) {
return 50;
}
add_filter( 'excerpt_length', 'tn_custom_excerpt_length', 999 );
```

But it doesn't work. 

Thanks in advance

**Comment by danemorgan** [comment]
Are we sure it isn't working? You've only reduced it by 5 words.

**Comment by nvjacobo** [comment]
Thanks @danemorgan! 

I am sure it. I tried with 8, 10 and more combinations.

**Comment by danemorgan** [comment]
We would need some links to look at, and can you post your full functions.php? Also si your code in the base theme's functions.php or in a child theme?

**Comment by bacoords** [comment]
Actually I've had this issue. You'll need to review the `inc/setup.php` file in the theme and override or remove some of these functions, including `understrap_all_excerpts_get_more_link()` and `understrap_custom_excerpt_more()`

**Comment by IanDelMar** [comment]
@nvjacobo I just tested limiting the excerpt length both with UnderStrap 0.9.4 and 0.9.6 and can't reproduce the issue - everything works fine. @bacoords, none of the functions in [inc/setup.php](https://github.com/understrap/understrap/blob/fd7976bcb36a0f15cd846cadc61cda3edcbdd8d3/inc/setup.php) deals with the excerpt length. @danemorgan I tested putting the function in the parent's and the child's functions.php and it works for both versions.

@nvjacobo What plugins do you have activated? I guess there is another filter with priority >= 999. Try disabling all plugins and check whether your excerpt length filter works. If so, re-activate each plugin one by one and check what plugin is causing the issue.

**Comment by danemorgan** [comment]
I don't see how either of those functions would block the excerpt filter here.

**Comment by bacoords** [comment]
Is this still an open issue?

**Comment by IanDelMar** [comment]
> including `understrap_all_excerpts_get_more_link()` and `understrap_custom_excerpt_more()`

With no feedback for more than a year now this seems not to be an issue for the OP anymore.

**Comment by IanDelMar** [comment]
@bacoords I think this issue can be closed
