### ISSUE TITLE
Navbar dropdowns not working anymore

### ISSUE THREAD

**Issue by Havbaba** [understrap/understrap#1399]
### Description of the Bug
I think this bug is more related to my child theme, because it works on the main theme but maybe it's connected?
But the dropdowns in my navbar aren't working anymore.
Did something change in a recent update?
And how can I fix this?

Seems like Popper.js doesn't seem to load or is something else causing this bug?

[www.dronedepot.be](www.dronedepot.be)

Thanks in advance 😄 

### Environment
Please complete the following information:
- WordPress Version: 5.8
- Browser: all

### Additional Context
Add any other context about the problem here. E.g. Are there any related issues and/or pull requests?

**Comment by bacoords** [comment]
It looks like it's trying to find popper.min.js in the parent theme's /js/ folder. We don't actually don't normally include that file in the parent theme because it's bundled into the main JS file. It IS currently available in the child theme's JS folder, so if you're trying to enqueue it separately, you can use `get_stylesheet_directory_uri()` to ensure you're grabbing it from the child theme.

**Comment by Havbaba** [comment]
Oh okay, thought it was included, so where do I have to put this `get_stylesheet_directory_uri()` ?

> It looks like it's trying to find popper.min.js in the parent theme's /js/ folder. We don't actually don't normally include that file in the parent theme because it's bundled into the main JS file. It IS currently available in the child theme's JS folder, so if you're trying to enqueue it separately, you can use `get_stylesheet_directory_uri()` to ensure you're grabbing it from the child theme.

**Comment by bacoords** [comment]
Can you paste your child theme's functions.php file?

**Comment by Havbaba** [comment]
[functions.txt](https://github.com/understrap/understrap/files/7094684/functions.txt)

**Comment by Havbaba** [comment]
Ah I see, I think I have to change this line:
`wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), false);`

To this?
wp_enqueue_script( 'popper-scripts', get_stylesheet_directory_uri() . '/js/popper.min.js', array(), false);

**Comment by bacoords** [comment]
Yes, exactly! Let us know if it works

**Comment by Havbaba** [comment]
Yes that works perfectly, thanks! :)
