### ISSUE TITLE
Feature Request: move terser config to .terserrc file

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1400]
To track @0dp suggestion: https://github.com/understrap/understrap/pull/1380#discussion_r697297539

## Problem Statement

> Also i really think customization options for terser is important.
> Doing these hard coded flags in run tasks is doubtfully the right approach, EVEN if boostrap does just that.

> Better to leave the run tasks as static and modify them in config files.

## Priority/Severity

- [ ] High (This will bring a huge increase in performance/productivity/usability/legislative cover)
- [ ] Medium (This will bring a good increase in performance/productivity/usability)
- [x ] Low (anything else e.g., trivial, minor improvements)

**Comment by 0dp** [comment]
Let me see if i can whip something up for you tomorrow.

**Comment by bacoords** [comment]
Closing with the launch of [1.0.0](https://github.com/understrap/understrap/releases/tag/v1.0.0).
