### ISSUE TITLE
npm install no such file or directory

### ISSUE THREAD

**Issue by gettonet** [understrap/understrap#1433]
When I run npm install on my Windows machine, i receive a lot of these errors and node_modules folder remains empty.

Anyone else has this issue and what may be causing it?

**Comment by gettonet** [comment]
I have just tried on another Windows machine, the same happens.
debug.log [here](https://mega.nz/file/YLomkJYT#5cLRMJyhVUiBZN_ubeu_H1SjShnSUpfZlqxx43s4DVw)

**Comment by gettonet** [comment]
removing the line
`"postcss-understrap-palette-generator": "git+https://github.com/bacoords/postcss-understrap-palette-generator.git",`
from package.json solved the issue.

Is this dependency necessary?

**Comment by bacoords** [comment]
Can you run `git --version` and see if you have git installed at the command line as a global command?

**Comment by gettonet** [comment]
Checked, no, I do not have it installed

**Comment by gettonet** [comment]
Ok, after installing Git for Windows running npm install goes with no errors.
However, on npm run watch I get another error re this plugin:
`
> mythemeslug@1.0.0 css-postcss C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug
> postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"
Error: Loading PostCSS Plugin failed: Cannot find module 'postcss-mythemeslug-palette-generator'
Require stack:
-C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\noop.js
(@C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\src\build\postcss.config.js)
    at load (C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\node_modules\postcss-load-config\src\plugins.j
    at C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\node_modules\postcss-load-config\src\plugins.js:53:1
    at Array.map (<anonymous>)
    at plugins (C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\node_modules\postcss-load-config\src\plugin
    at processResult (C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\node_modules\postcss-load-config\src\
    at C:\Users\GetToNet\Local Sites\mywebsite\app\public\wp-content\themes\mythemeslug\node_modules\postcss-load-config\src\index.js:151:14
    at async Promise.all (index 0)`

(if this plugin needs to be installed this way, I propose that it should be included in Documentation that it is not enough only to have Node.js and run npm install, obviously not working if git is missing)

**Comment by bacoords** [comment]
We'll make a note in the docs that you need `git` installed globally (at least for now. We'll get the postcss plugin added to npm sooner if possible). 

Try adding it back to your package.json before you run `npm install` again

**Comment by bacoords** [comment]
Also postcss-mythemeslug-palette-generator should be postcss-undertrap-palette-generator in your postcss.config file.

**Comment by gettonet** [comment]
I got it.
The whole issue is because of the search/replace operation from undrestrap to mythemeslug.
This was not an issue before, so I went through my normal process when using the theme for new projects.

I think many people do the same, so they will probably run into same problems as myself - would be nice to add a note in the docs for those cases :)

**Comment by bacoords** [comment]
Great! 

We'll make a note in the docs. In the docs we do mention that we recommend using a child theme rather than modifying the parent theme, but we also know that many developers prefer customizing the parent theme, so we'll add a note for this issue.
