### ISSUE TITLE
Unable to run Understrap on Mac or Windows

### ISSUE THREAD

**Issue by Moustachey** [understrap/understrap#1450]
Hi there, I've been trying to install understrap across three different devices today (2 'Windows 10' Machines and 1 Macbook). I have had the same exact issue on all three (see screenshot):

<img width="697" alt="Screen Shot 2021-09-28 at 4 35 58 pm" src="https://user-images.githubusercontent.com/32915552/135035558-9dea52a6-25c2-4fc6-8948-ed93437f0de0.png">

To replicate this issue, do the following:
1. Unzip and paste understrap in desired theme folder
2. Run `npm install`
3. Run `npm run watch`

You should then come across the following error:
`[!] Error: Could not resolve entry module (src/build/rollup.config.js).
Error: Could not resolve entry module (src/build/rollup.config.js).`

I have tried this across different operating systems (2 of the 3 never had Node/NPM installed before attempting this). Nothing in the install docs says anything else about setting this up and I've set up understrap numerous times in the past on numerous machines.

Am I missing something or is the latest build currently broken when trying to run understrap?

Thanks!

**Comment by Moustachey** [comment]
Looks like I missed the part where custom config files need to be created. 
_(Maybe add something in the install notes for this? Previous understrap installs had predefined configs)_

**Comment by bacoords** [comment]
The config file should be included in the repo: https://github.com/understrap/understrap/blob/main/src/build/rollup.config.js

However, if you're pulling the site from the WordPress.org Theme Directory instead of GitHub, we're not allowed to include many of the config files. If developing on the parent theme, we recommend starting from the GitHub [releases](https://github.com/understrap/understrap/releases)

**Comment by Moustachey** [comment]
Thanks so much, this is definitely what the issue was! 
Maybe it's worth noting this in the official install/setup notes if the user obtains Understrap from WordPress.org? 🙂

**Comment by bacoords** [comment]
I've added a note to our [docs](https://docs.understrap.com/)! For what it's worth, we recommend using a child theme rather than editing Understrap directory BUT we understand some developer prefer that method so we try to fully support it.

**Comment by chrisjimallen** [comment]
@bacoords I'm about to start building a new theme and am trying to decide what the pros and cons of each approach is. I'm leaning towards a child theme. In terms of pagespeed/page weight, is there any difference between the two? Apologies if this does not belong here.

**Comment by howarddc** [comment]
@chrisjimallen Brian may have more thoughts on this on Monday, but in terms of performance, there should not be any difference between the two methods. The child theme dequeues the parent styles/scripts and then re-enqueues the equivalent ones within the child theme folder, so there is no double-loading of assets or anything like that.

The use of the child theme method also conforms more closely to WordPress's preferred approach, so I think unless you have a strong reason not to, using a child theme is the way to go. We know that a lot of devs were using the "modify the parent theme" approach over the past few years, so we want to keep supporting that, but I think the child theme route is ideal for new projects.

**Comment by bacoords** [comment]
@chrisjimallen We actually have a separate discussion thread here: https://github.com/understrap/understrap/discussions/1291

There's no difference in performance, we utilize the same assets. The main difference is control. If you modify the parent theme, you've locked down control over it. If you use a child theme, the parent theme still gets updated, gaining new features. However, you may not want this, you may prefer more control over the final site.
