### ISSUE TITLE
Rollup config - exclude file from tree shaking?

### ISSUE THREAD

**Issue by gettonet** [understrap/understrap#1451]
I have a function in custom-javascript.js that will not compile to theme js files!

The function is not called anywhere in the files, but it is very much needed on the website.
After investigating, I found that it's a Rollup's "tree-shaking" feature which detects unused declarations and excludes them from bundle.

Is there a workaround? It took me 3 hours to find out that Uncaught ReferenceError is caused by compiler not including my function in theme js!

**Comment by bacoords** [comment]
Try attaching your function to the global 'window' object:

```js
// Add your JS customizations here
window.test = function() {
	console.log('test');
}
```

**Comment by gettonet** [comment]
Thanks @bacoords ...it's a jQuery function, within 
```
jQuery(function($){
$(document).on(............
...and all the othe event-related functions....
...

function thisonegetslost(){
console.log('I need this function');
}

})
```
What would the syntax be in that case?
Also, all console.log instructions are removed :)

**Comment by bacoords** [comment]
You can have console log kept in by changing the variable here: https://github.com/understrap/understrap/blob/main/src/build/terser.config.json#L7 `"drop_console": false,`

You should be fine to just use the same logic, though I haven't tested it:

```js
jQuery(function($){
$(document).on(............
  ...and all the othe event-related functions....
  ...

  window.thisonegetslost = function(){
    console.log('I need this function');
  }

})
```

**Comment by gettonet** [comment]
I can confirm it works.
Many thanks for your help!

**Comment by mattneal-stafflink** [comment]
I know this is closed, but in case anyone else has an issue with functions not being compiled, you need to export them. 

For example, in my custom-javascript.js file, I had a function like this:

```
function initMap() {
 // Do some stuff
}
```

Which wasn't being compiled into my child-theme.js file. at the bottom of the custom-javascript.js file, I added 

`export { initMap }`

which solved my problem.
