### ISSUE TITLE
Feature Request: Support Script Debug

### ISSUE THREAD

**Issue by BrookeDot** [understrap/understrap#1456]
## Problem Statement
There are times where it is beneficial to load unminified assets within a theme. In order to facilitate this, WordPress core uses the `SCRIPT_DEBUG` constant. More on that [in the official documentation](https://wordpress.org/support/article/debugging-in-wordpress/#script_debug/). 

Since Understrap is already including the source files (at it should) this PR makes it possible to define `SCRIPT_DEBUG` to load the source files

## Who will benefit?
Primarily developers working locally, or in other setups where they it is beneficial to not load the minified versions of scripts.

## Benefits and risks

The benefit is that s brings Understrap more inline with best practices around provide the option to load full versions of assets. Of course the risk is if someone leaves the constant set on production it could have performance implications. But the risk is pretty small.

## Proposed solution
If `SCRIPT_DEBUG` is defined as true, then load the full scripts in `inc/enqueue.php`. The alternative would be an Understrap unique constant or setting, but since this is a dev feature relying on core makes sense to me here.

## Examples
Yes, this is common both WordPress Core and many other themes,  frameworks, and plugins. 

## Priority/Severity
- [ ] Low (anything else e.g., trivial, minor improvements)

**Comment by 0dp** [comment]
Yeah, this makes perfect sense to me. Good call!

**Comment by bacoords** [comment]
Closed with release [1.1.0](https://github.com/understrap/understrap/releases/tag/v1.1.0).
