### ISSUE TITLE
NPM RUN WATCH fails

### ISSUE THREAD

**Issue by BuzzGraphicDesign** [understrap/understrap#1473]
Hi, i tried out your latest version of the Plugin today, but the compiler fails for some reason.

I'm hosting accounts on shared hosting, the process is usually always the same:
- installed Node 16.11.0 via NVM
- run `npm install` from the plugin folder
- run `npm run watch`

But then i got some error messages:
![Screenshot 2021-10-20 at 16 48 58](https://user-images.githubusercontent.com/61582849/138127061-f8d70b83-bb03-4658-be7a-f1260148f454.png)

Used gulp before, had no problems...

Can someone help me a bit?

**Comment by 0dp** [comment]
Have you been playing around with resource allocation in node_js before?

**Comment by BuzzGraphicDesign** [comment]
so i tested it locally and it's working...

so as `0dp` mentioned might be some resource limitation problem

anyone good in Linux to give me any guidance how to check or increase system limitations on a shared hosting

cheers

**Comment by bacoords** [comment]
Closing this issue as it appears resolved. Please comment and we can re-open if needed.
