### ISSUE TITLE
@c4pslock if you see something like:

### ISSUE THREAD

**Issue by binuboston** [understrap/understrap#1490]
@c4pslock if you see something like:

`[09:27:11] Starting 'watch'...`

That means it's waiting for you to make changes. Try jumping into one of your SCSS files, make a change and save it, then that message should be updated with something like

`[09:30:43] Finished 'sass' after 988 ms`
`[09:30:43] Starting 'minifycss'...`
`[09:30:44] Finished 'minifycss' after 905 ms`
`[09:30:44] Finished 'styles' after 1.89 s`

If you don't get those following messages, it most likely means your gulp isn't watching the correct files. Let me know if that's still an issue.

_Originally posted by @mattneal-stafflink in https://github.com/understrap/understrap/issues/1239#issuecomment-800680477_

**Comment by binuboston** [comment]
yes that's still an issue for me,
:(

**Comment by c4pslock** [comment]
It's not a fix, but figured I'd mention it anyways - I switched to yarn and have been having no issues with it so far.

**Comment by bacoords** [comment]
The latest versions of Understrap no longer use gulp as a task manager. The new build process is outlined here in the readme: https://github.com/understrap/understrap#installing-dependencies
