### ISSUE TITLE
npm watch compiles again css and removes extra prefixes attributes when you stop it

### ISSUE THREAD

**Issue by alexbogias** [understrap/understrap#1495]
### The Bug

**Any idea why npm watch recompiles custom-editor-styles when you stop the task and remove autoprefixes extra attibutes?**

**To Reproduce**
npm watch (theme or child-theme)

**Expected behavior**

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/1313467/139827501-1f9ede52-ed34-4e06-8561-9c5f6111104f.png)

**Comment by bacoords** [comment]
I can't replicate this, but sometimes the autoprefixer can produce slightly different results depending on your node version, packages, etc. In this particular instance, though, box-sizing probably doesn't need that prefix any more.

**Comment by alexbogias** [comment]
Yeah, I know it's better, but it's weird that it triggers again when I stop the task. 
I made may css changes... I commit and push and when I stop task i see file changes again :(

**Comment by bacoords** [comment]
How do you stop the `watch`  command?

**Comment by alexbogias** [comment]
Like this
![image](https://user-images.githubusercontent.com/1313467/143050356-19152633-9bea-42b9-be3c-4c60988a2130.png)

**Comment by bacoords** [comment]
Ah - what tool is that? Does the issue happen when you just run it directly in the terminal and use `ctrl-c` (or the equivalent for your OS) to stop the command?

**Comment by bacoords** [comment]
Interesting! I'll close this issue, but it's always worth posting because this might help someone else who's having the same issue.
