### ISSUE TITLE
Getting a ton of errors when doing npm install

### ISSUE THREAD

**Issue by dmcgrew** [understrap/understrap#1496]
I am using Understand 0.9.4 and am trying to do npm install but keep getting a ton of errors. The very first error is the following...

npm ERR! code 1
npm ERR! path /Applications/MAMP/htdocs/website/wp-content/themes/lwf/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js

And the list of errors goes on and on.. there's probably at least 500 lines of errors. 

I had this working on my machine last week but had to do a complete factory reset yesterday and reinstall nodejs, npm, etc. I don't know much about node and npm other than they suck when they don't work. My assumption is that I'm running a newer version of node and/or npm that I was before and now the old npm packages are not supported. If that's the case what do I do in this scenario? 

Any help here would be greatly appreciated.

**Comment by 0dp** [comment]
What is the output of `node -v` ?
Are you running nvm?

**Comment by bacoords** [comment]
Closing this as it's been 28 days with no response. Feel free to comment and we can re-open.

**Comment by JamesVanWaza** [comment]
@dmcgrew also try and download the next version `1.0.1` and then test first.
