### ISSUE TITLE
While running npm watch, js compile works but css compile doesn't work

### ISSUE THREAD

**Issue by Ref34t** [understrap/understrap#1498]
while running npm watch

adding custom js makes it compile normally but when trying to write CSS
the compiler does nothing and I have to restart the script to make it compile 

I'm using MacBook air m1 machine

**Comment by bacoords** [comment]
Please give us the output of these commands:

- node -v
- git --version

**Comment by mckenziewagner** [comment]
Same issue. My js compiles fine, but my css doesn't compile.

Using Node v16.4
Using git - 2.34

**Comment by bacoords** [comment]
Please see: https://github.com/understrap/understrap/issues/1523#issuecomment-982305179

**Comment by bacoords** [comment]
Please check the updated `watch` tasks in `package.json`. Closed with release [1.1.0](https://github.com/understrap/understrap/releases/tag/v1.1.0).
