### ISSUE TITLE
How to include npm packages that use 'require'

### ISSUE THREAD

**Issue by celticwebdesign** [understrap/understrap#1500]
I am a long time user of Understrap and I am currently attempting to build a new website using the latest version of Understrap that now uses rollup.js.

Previously when using Gulp, I could import code like:
https://www.npmjs.com/package/viewport-size (old but still worked)
but now this does not work.

I have tried:
https://www.npmjs.com/package/screen-size-detector
but rollup changes the variable name of the import making the package un-useable.
I have tried rollup legacy but it still results in an error.

I have also attempted to use packages like:
https://www.npmjs.com/package/get-viewport-size
but this use the 'require' statement which the browser does not understand.

I have been looking online for solutions to this, attempting to read the rollup documentation which is difficult for me.

So my question is, how can I import js packages in to the new Understrap which uses rollup?

rollup.config.js
module.exports = {
input: [
path.resolve(__dirname, '../js/bootstrap.js'),
path.resolve(__dirname, '../js/skip-link-focus-fix.js'),
path.resolve(__dirname, '../../node_modules/viewport-js/dist/viewport.min.js'),
path.resolve(__dirname, '../../node_modules/jquery-doubletaptogo/dist/jquery.dcd.doubletaptogo.min.js'),
path.resolve(__dirname, '../../node_modules/mmenu-js/dist/mmenu.js'),
path.resolve(__dirname, '../js/custom-javascript.js')
],

custom-javascript.js
var viewport = require('viewport');
console.log(viewport.height);

Browser console always outputs:
Uncaught ReferenceError: require is not defined

Thanks

**Comment by bacoords** [comment]
I believe you need to include the `commonjs()` plugin in rollup to be able to do those types of imports. This has been added on the develop branch for the next release, but in the meantime, you can see where we added it here: https://github.com/understrap/understrap/blob/develop/src/build/rollup.config.js#L20

**Comment by celticwebdesign** [comment]
Thanks for the information.
After much struggle I do have something working now:

`'use strict'

const path = require('path')
const { babel } = require('@rollup/plugin-babel')
const { nodeResolve } = require('@rollup/plugin-node-resolve')
import commonjs from "@rollup/plugin-commonjs";
import multi from '@rollup/plugin-multi-entry'
const banner = require('./banner.js')

let fileDest = 'child-theme.js'
const external = ['jquery', 'screen-size-detector']
const plugins = [
	babel({
		// Only transpile our source code
		exclude: 'node_modules/**',
		// Include the helpers in the bundle, at most one copy of each
		babelHelpers: 'bundled'
	}),
	nodeResolve(),
	commonjs({
		include: 'node_modules/**',
	}),
	multi()
]
const globals = {
  	jquery: 'jQuery', // Ensure we use jQuery which is always available even in noConflict mode
	'popper.js': 'Popper',
	'screen': 'ScreenSizeDetector'
}

module.exports = {
	input: [
		path.resolve(__dirname, '../js/bootstrap.js'),
		path.resolve(__dirname, '../js/skip-link-focus-fix.js'),
		path.resolve(__dirname, '../../node_modules/screen-size-detector/dist/screen-size-detector.min.js'),
		path.resolve(__dirname, '../js/custom-javascript.js')
	],
	output: {
		banner,
		file: path.resolve(__dirname, `../../js/${fileDest}`),
		format: 'umd',
		globals,
		name: 'understrap'
	},
	external,
	plugins
}`

and

`(function ($) {
	"use strict";

	$(function () {
		console.log(screen.width);
`

This is using the Screen Size Detector package.
This also resolves an issue for dependencies of the external package.

Thanks
