### ISSUE TITLE
CSS not compiling

### ISSUE THREAD

**Issue by mckenziewagner** [understrap/understrap#1523]
My JS is compiling fine, but my CSS isn't without restarting the script, or running npm run css.

Further info:
Using Node - v16.4
Using git - 2.34

**Comment by bacoords** [comment]
There's an issue coming in the next release where we change line 17 of the package.json from 

`"watch-run-css": "nodemon --watch sass/ --ext scss --exec \"npm-run-all css\"",`

to 

`"watch-run-css": "nodemon --watch src/sass/ --ext scss --exec \"npm-run-all css\"",`

Let me know if that works for you?

**Comment by bacoords** [comment]
We should've caught that in the last release, so it's understandable.
