### ISSUE TITLE
Prevent scroll-to-top when adding item to WooCommerce cart?

### ISSUE THREAD

**Issue by MastaBaba** [understrap/understrap#1542]
**Describe the problem**
I'm using the one-page-checkout plugin for WooCommerce. When a user adds an item to the cart, the cart is updated and, after the cart has been updated, the page scrolls to the top, showing the message "'{item}' added to your order. Complete your order below."

I do not necessarily need this message, but, more importantly, the message is intuitively in the wrong place; it should be above the billing form, not at the top of the page.

Ideally, I would not have this message at all, and, most importantly, not have the page scroll to the top, taking the user's focus away from the form they need to fill in.

How to prevent this scroll?

**Debug Checklist**
Please include all of the following:
+ Understrap version: 1.1.0
+ I'm using a child theme.
+ I'm not using git or node for this.

**Comment by bacoords** [comment]
I'm not sure this is an understrap issue- Understrap doesn't effect any core Woocommerce functionality. Have you reached out to the developer of the plugin that you're using?

**Comment by MastaBaba** [comment]
Thanks Brian.

My first assumption was also that it was not the theme, but WooCommerce behaviour. Then I found this thread:

https://wordpress.org/support/topic/disable-auto-scroll-to-top-when-clicking-add-to-cart/

But, I just spoke to WooCommerce. Turns out this is a setting that is turned on by default. So, fixed.

Thanks again.
