### ISSUE TITLE
Bootstrap version is standard set on bootstrap4

### ISSUE THREAD

**Issue by Floris-devries** [understrap/understrap#1551]
In the header the bootstrap version is standard set on bootstrap 4. Shouldn't this be set on bootstrap 5?

$bootstrap_version = get_theme_mod( 'understrap_bootstrap_version', 'bootstrap4' ); -> should be
$bootstrap_version = get_theme_mod( 'understrap_bootstrap_version', 'bootstrap5' );

**Comment by bacoords** [comment]
Hi - For backwards compatibility, we're passing a default value of 'bootstrap4' for the version. That way any sites updating their parent theme would continue to load bootstrap4. Bootstrap5 is opt-in only.

 If a user wants to update to Bootstrap5, they can do so using the customizer or by [hardcoding the theme mod with a filter](https://docs.understrap.com/#/understrap-child/functions?id=overriding-the-parent-theme-customizer-settings)

**Comment by Floris-devries** [comment]
Allright, thank you!
