### ISSUE TITLE
Top Level Menu Item Not Clickable

### ISSUE THREAD

**Issue by benjaminsumisu** [understrap/understrap#1568]
### The Bug

**Describe the bug**
Top Level Menu Item Not Clickable

**To Reproduce**
1. Go to Dashboard > Appearance > Menus
2. Created a Nested Menu
3. Go to Home Page and Test Links
4. Child Items are clickable but the parent menu is not. 

**Expected behavior**
I don't see this same behavior in my sites running Genesis, so I believe this is not expected behavior

**Screenshots / Videos**

### The Environment

- **WordPress Version:** 5.8.3
- **OS Version:** Windows 8 | Windows 10 ] | Linux ]
- **Browser:** | Chrome XX | Firefox XX |
- **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML ]
- **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

### Additional context

Here's what I did to get this working,

In understrap/inc/class-wp-bootstrap-navwalker.php

Change the following lines:

			// If item has_children add atts to <a>.
			if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && 1 !== $args->depth ) {
				$atts['href']           = '#';
				$atts['data-toggle']    = 'dropdown';
				$atts['data-bs-toggle'] = 'dropdown';
				$atts['aria-haspopup']  = 'true';
				$atts['aria-expanded']  = 'false';
				$atts['class']          = 'dropdown-toggle nav-link';
				$atts['id']             = 'menu-item-dropdown-' . $item->ID;
			} else {
				$atts['href'] = ! empty( $item->url ) ? $item->url : '#';
				// Items in dropdowns use .dropdown-item instead of .nav-link.
				if ( $depth > 0 ) {
					$atts['class'] = 'dropdown-item';
				} else {
					$atts['class'] = 'nav-link';
				}
			}

To:

			// If item has_children add atts to <a>.
			if ( isset( $args->has_children ) && $args->has_children && 0 === $depth && 1 !== $args->depth ) {
				$atts['href'] = ! empty( $item->url ) ? $item->url : '';
				$atts['aria-haspopup'] = 'true';
				$atts['aria-expanded'] = 'false';
				$atts['class']         = 'dropdown-toggle nav-link';
				$atts['id']            = 'menu-item-dropdown-' . $item->ID;
			} else {
				$atts['href'] = ! empty( $item->url ) ? $item->url : '#';
				// Items in dropdowns use .dropdown-item instead of .nav-link.
				if ( $depth > 0 ) {
					$atts['class'] = 'dropdown-item';
				} else {
					$atts['class'] = 'nav-link';
				}
			}

Thanks for all the great work on this theme!
Benjamin Smith

**Comment by pattonwebz** [comment]
This is the expected behaviour and - while I understand it seems like it's broken if you expect a different behaviour - having top-level items that both do an action (open a dropdown) and go a place (act as a link) is an anti-pattern that makes using the menu pretty difficult for anyone with a touch interface. It also makes it more verbose for anyone that uses a screen reader as well as anyone that uses voice control to select the items in the menu.

**Comment by benjaminsumisu** [comment]
@pattonwebz 

Thanks for the quick reply. Interesting, I don't see that same pattern on my sites running Genesis, but maybe that will change.

I'll go ahead and close this out.

**Comment by pattonwebz** [comment]
> @pattonwebz
> 
> Thanks for the quick reply. Interesting, I don't see that same pattern on my sites running Genesis, but maybe that will change.
> 
> I'll go ahead and close this out.

Yeah, it is pretty common for systems to have items that act as both dropdowns and links but I wish they wouldn't lol

Bootstrap made a conscious decision that the menu should have better accessibility defaults and the wp-bootstrap-walker has always adhered to that decision they made to avoid allowing links and dropdown toggles to both be active from the same element.
