### ISSUE TITLE
Feature Request: import 'bootstrap-utilities' into the gutenberg stylesheet

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1575]
The idea is that we could use classes like 'text-primary' in the gutenberg editor if we add this to our custom editor styles: 
`@import "assets/bootstrap5/bootstrap-utilities";`

**Comment by kirannasim** [comment]
@bacoords Just tried to import 'boostrap-utilities' and tested via page edit. It seems to work well

https://github.com/understrap/understrap/pull/1614

![image](https://user-images.githubusercontent.com/11325580/155580291-99875f22-22c3-42f9-b4f7-b93d6e87e44c.png)

**Comment by IanDelMar** [comment]
@bacoords added in v1.2.0
