### ISSUE TITLE
Javascript fails on iOS10

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1576]
### The Bug

**Describe the bug**
The JS fails on iOS 10 causing the navigation to fail.

**To Reproduce**
1. Visit any Understrap site on iOS 10 in Safari

**Comment by s7media** [comment]
Is this related to:

`SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.`

that I'm getting in Safari on Mac and iOS? Indeed all bootstrap related navigation JS is bricked. Pills and navbar.

**Comment by IanDelMar** [comment]
Unlike Bootstrap4, Bootstrap 5 does not support iOS 10... 

v4: https://getbootstrap.com/docs/4.6/getting-started/browsers-devices/
v5: https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/

**Comment by bacoords** [comment]
Well that explains that! Thanks @IanDelMar. I was trying to find something in their Github issues but yeah that says it right there. 

If you need to support iOS 10, keep your Understrap site running Bootstrap 4.
