### ISSUE TITLE
The new enqueue logic for bootstrap style and script is conflicting with enqueue logic of main css and js

### ISSUE THREAD

**Issue by blackkspydo** [understrap/understrap#1584]
### The Bug

**Describe the bug**

**To Reproduce**
1. The main CSS file simply won't load.

**Expected behavior**
1. The main CSS file to load and styles to show the effect
**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

### The Environment

- **WordPress Version:** [5.9]
- **OS Version:**  MacOS [12.1] | Android [Version] | iOS [Version]
- **Browser:** [ all  ]
- **Language:** [  PHP]
- **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

### Additional context

// The code causing the conflict
    function understrap_scripts() {
		// Get the theme data.
		$the_theme         = wp_get_theme();
		$theme_version     = $the_theme->get( 'Version' );
		$bootstrap_version = get_theme_mod( 'understrap_bootstrap_version', 'bootstrap4' );
		$suffix            = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';

		// Grab asset urls.
		$theme_styles  = "/css/theme{$suffix}.css";
		$theme_scripts = "/js/theme{$suffix}.js";

		if ( 'bootstrap4' === $bootstrap_version ) {
			$theme_styles  = "/css/theme-bootstrap4{$suffix}.css";
			$theme_scripts = "/js/theme-bootstrap4{$suffix}.js";
		}

		$css_version = $theme_version . '.' . filemtime( get_template_directory() . $theme_styles );
		wp_enqueue_style( 'understrap-styles', get_template_directory_uri() . $theme_styles, array(), $css_version );

		wp_enqueue_script( 'jquery' );

		$js_version = $theme_version . '.' . filemtime( get_template_directory() . $theme_scripts );
		wp_enqueue_script( 'understrap-scripts', get_template_directory_uri() . $theme_scripts, array(), $js_version, true );
		if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
			wp_enqueue_script( 'comment-reply' );
		}
	}

**Comment by bacoords** [comment]
We recommend checking your debug log or using a plugin like Query Monitor to see what specific errors might be preventing this function from calling. Are you using a modified version of the Understrap theme?

**Comment by blackkspydo** [comment]
I think it's not a modified version, I just cloned it from the main understrap repo. I was trying to use custom scss and it was not showing the effect. While bootstrap only works fine. Are there other ways to not use bootstrap but just custom CSS? I removed the if-condition (which was checking for the bootstrap version) and it worked fine for me. Maybe I am doing it wrong.

**Comment by bacoords** [comment]
The custom scss files are compiled together with the bootstrap scss files to generate one stylesheet for the theme. Take a look at this documentation for more information on the build process: https://docs.understrap.com/#/understrap-child/npm

**Comment by benjaminsumisu** [comment]
Hi,

I'm noticing the following behavior.

If I go to _theme.scss and add  the following:
`body {

    background-color: grey;
}`
Then run **npm run css**

Now, go to Customize > Theme Layout Settings. If I select Boostrap 4, the background remains white. However, If I select Bootstrap 5, the background is grey. 

I'm using the latest version (1.1.0 ) of Understrap, not the child theme.

If I go to the Query Monitor it's not loading the following file for Bootstrap 4.

wp-content/themes/understrap/css/theme.min.css

Ben

**Comment by bacoords** [comment]
The parent theme only compiles BS5 assets by default when you're using `npm run watch`.  I thought we clarified this in the docs, but I'm not seeing it, so I'll see if we can get this better documented.

If you want to compile assets for BS4 you can run  `npm run css-bs4` and `npm run js-bs4`. If you want the `watch` command to compile bs4 instead of bs5 whenever you make updates, you can update these two lines in `package.json` and restart watch. 

```
   "watch-run-css": "nodemon --watch src/sass/ --ext scss --exec \"npm-run-all css-bs4\"",
    "watch-run-js": "nodemon --watch src/js/ --ext js --exec \"npm-run-all js-bs4\"",
```

**Comment by benjaminsumisu** [comment]
Thanks Brian!  That's working.
