### ISSUE TITLE
Block editor buttons can sometimes be inaccessible on hover

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#1597]
Gutenberg buttons default to having white text on hover. Using a white background color on a button should offer a darker color text on hover. While we can't accomodate every color option, we could at least provide a fallback for the white button on hover. 

**To Reproduce**
1. Add a button in the block editor
2. Select white as the background color and any other color as the text
3. Hover over the button on the front-end

https://github.com/understrap/understrap/blob/main/src/sass/theme/_colors.scss

**Comment by kirannasim** [comment]
@bacoords Just tried to fix the bug and opened the pull request. 
https://github.com/understrap/understrap/pull/1612

**Comment by IanDelMar** [comment]
@bacoords the corresponding fix has been merged in v1.2.0. Can we close the issue?
