### ISSUE TITLE
npm run watch changes not showing in development

### ISSUE THREAD

**Issue by sam-kallkwik** [understrap/understrap#1616]
Hi there,
I am developing a website directly in the understrap theme. I have been adding my scss to the /src/sass/theme/_theme.scss file, however any time I save my changes they are not showing in the browser. 

- I have installed the node modules 'npm install' while running node 16.
- I am watching the files 'npm run watch'.
- I am running understrap 1.1.0

Here is the output from my terminal:

<img width="1495" alt="Screenshot 2022-02-25 at 10 06 49" src="https://user-images.githubusercontent.com/46520210/155696369-cd3d6788-cbef-4c52-8a88-ae9aefbb2c86.png">
<img width="1496" alt="Screenshot 2022-02-25 at 10 07 15" src="https://user-images.githubusercontent.com/46520210/155696390-bf308b8a-b181-4cdd-b685-93ad6f2a2242.png">

If I then cancel this and run `npm run dist` it compiles fine and the updates pull. The issue is I don't want to run this every time I make a change to the file.

Can you please help find a solution to get the changes to pull through on the `npm run watch`.

Thanks

**Comment by bacoords** [comment]
Are you using Bootstrap 4 or 5?

**Comment by sam-kallkwik** [comment]
I aim to use whatever the latest release ships with. I have tried the recommended fix in #1530 and that does then include the added styles in the browser when I refresh in watch, but I guess that then means I am not taking advantage of Bootstrap 5. 

Does this then mean I have to create a child theme to be able to use Bootstrap 5?

**Comment by bacoords** [comment]
Nope You can just set the site to Bootstrap 5 in the Theme Layout Settings in the Customizer: https://docs.understrap.com/#/understrap-parent/customizer?id=theme-layout-settings

**Comment by sam-kallkwik** [comment]
I see, missed that part. Would it make more sense then to set the default in the customizer to bootstrap 5 so it matches what is being developed by default in the files? In customizer.php its currently bootstrap4.

**Comment by bacoords** [comment]
We chose to default to Bootstrap 4 since that's what most sites running Understrap are used to. Plus Bootstrap 5 has a lot less browser support, so we felt it should be opt in.

In the child starter theme we hard code the setting to Bootstrap 5.

**Comment by sam-kallkwik** [comment]
Ok understood 👍
