### ISSUE TITLE
Remove Admin Menu Design -> Background in Child Theme

### ISSUE THREAD

**Issue by DLX23** [understrap/understrap#1621]
I don't want the user to see "Design-> Background" in Admin menu.
I try "remove_theme_support('custom-background');" in functions.php in child theme, but it didn't work.
I use the latest version of understrap.
What can I do?

**Comment by bacoords** [comment]
Where do you hook into for `remove_theme_support()`? You can use the `after_setup_theme` action and maybe just use 99 priority to be sure.

**Comment by DLX23** [comment]
i use it in functions.php because theme already exist

**Comment by bacoords** [comment]
Yes but the hook you call it from will affect the priority. See the docs for a good example: https://developer.wordpress.org/reference/functions/remove_theme_support/#comment-1050

**Comment by kirannasim** [comment]
@DLX23 you can add the following code in functions.php. I hope this will work for you.

```
add_action( 'after_setup_theme', 'remove_custom_background', 11 ); 

if ( ! function_exists( 'remove_custom_background' ) ) {
	function remove_custom_background() {	
		// Remove custom background support
		remove_theme_support( 'custom-background' );
	}
}
```

**Comment by DLX23** [comment]
Works Great! Thank you very much!

**Comment by bacoords** [comment]
@DLX23 Please close this issue if you're all good here
