### ISSUE TITLE
Js issue

### ISSUE THREAD

**Issue by SuperStar-sf** [understrap/understrap#1636]
Hi there,

I tried to update Understrap child-theme .5 to 1.0.1 using Bootstrap v4. When compiling, it displays an error related to the javascript. Could you please help me to fix this? I used node version 16 and Understrap parent-theme 1.1.0.

<img width="569" alt="Screen Shot 2022-03-01 at 8 43 33 AM" src="https://user-images.githubusercontent.com/100318570/156049148-4e53c9cc-638c-43ec-ac20-ffb61ef1f259.png">

**Comment by bacoords** [comment]
It looks like terser is not installed? Can you check your package.json for terser and run `npm install` if needed?

**Comment by SuperStar-sf** [comment]
Hi @bacoords, thank you so much for quick response. This is my package.json

<img width="1267" alt="Screen Shot 2022-03-01 at 9 21 59 AM" src="https://user-images.githubusercontent.com/100318570/156053363-8697f3f7-c024-4c74-9b02-400690f67059.png">

**Comment by SuperStar-sf** [comment]
Thanks @bacoords, installed terser and all good now :)
