### ISSUE TITLE
customize front page hero slider widget

### ISSUE THREAD

**Issue by yoscbd** [understrap/understrap#1637]
Hi all,
I'm trying to design the here slider widget section.
- is there a file where i can control the slider settings with? (such as slider speed...)
- what is the best practice to customize the slider? (E.G - change its height...)
- where are the slider script files located (or we get the functionality from bootstrap js?)
Thank you all!

**Comment by bacoords** [comment]
The slider is here: 

[sidebar-templates/sidebar-hero.php](https://github.com/understrap/understrap/blob/main/sidebar-templates/sidebar-hero.php)

I also recommend reviewing the carousel docs here for the various sass variables, data attributes, etc: https://getbootstrap.com/docs/5.1/components/carousel/

**Comment by bacoords** [comment]
@yoscbd Please close this issue if your question has been answered.
