### ISSUE TITLE
Custom colors in _theme_variables.scss cause error on compile

### ISSUE THREAD

**Issue by gettonet** [understrap/understrap#1639]
In BS4 we were able to add custom colors to palette like this:

```
$custom-colors: (
  "custom-color": #900
);
// Merge the maps
$theme-colors: ();
$theme-colors: map-merge($theme-colors, $custom-colors);
```

However, in BS5 I get an error on compile, like BS's $theme-colors are not loaded.
First error is:
```
Error: The target selector was not found.
Use "@extend .alert-success !optional" to avoid this error.
   ╷
36 │     @extend .alert-success;
   │     ^^^^^^^^^^^^^^^^^^^^^^
   ╵
src\sass\theme\_woocommerce.scss 36:2  root stylesheet
```

When I add !optional it gets fixed, but then errors continue wherever we have color related class or variable.
Am I missing something - can you please help me to add new colors to palette?

**Comment by gettonet** [comment]
Found it, in BS5 _variables.scss $colors and $theme colors are missing map-merge.

**Comment by kirannasim** [comment]
Actually, $theme-colors and $colors is bootstrap variables. You can add custom colors in _colors.scss as follow

```
@each $name, $color in $colors {

	.has-#{$name}-color,
	.has-#{$name}-color:visited {
		color: $color;
	}
	.has-#{$name}-background-color {
		background-color: $color;
		border-color: $color;
	}
}
@each $name, $color in $theme-colors {

	.has-#{$name}-color,
	.has-#{$name}-color:visited {
		color: $color;
	}
	.has-#{$name}-background-color {
		background-color: $color;
		border-color: $color;
	}
}

$custom-colors: (
  "custom-color": #900
);
// Merge the maps
$theme-colors: ();
$theme-colors: map-merge($theme-colors, $custom-colors);
```

**Comment by Fedora-Man** [comment]
I got:
Error: Undefined variable.
$theme-colors: map-merge($theme-colors, $isa-brown, $isa-blue, $isa-green, $isa-gold);
When adding the following custom colors:

// Create own map
$custom-colors: (
    "isa-brown":    #5f413a,
    "isa-blue":     #6d8596,
    "isa-green":    #847b28,
    "isa-gold":     #b18952
);

// Merge the maps
$theme-colors: map-merge($theme-colors, $isa-brown, $isa-blue, $isa-green, $isa-gold);

**Comment by IanDelMar** [comment]
@Fedora-Man you have not define `$isa-brown`, `$isa-blue`, `$isa-green` or `$isa-gold`. You defined a map called `$custom-colors`. `map-merge` merges maps not maps and single colors. 

Assuming that `$theme-colors` is defined, try this
```diff
// Create own map
$custom-colors: (
  "isa-brown": #5f413a,
  "isa-blue": #6d8596,
  "isa-green": #847b28,
  "isa-gold": #b18952
);

// Merge the maps
-$theme-colors: map-merge($theme-colors, $isa-brown, $isa-blue, $isa-green, $isa-gold);
+$theme-colors: map-merge($theme-colors, $custom-colors);
```

**Comment by Fedora-Man** [comment]
I changed it as recommneded.

But what I am getting is $theme-colors undefined while it is defined in bootstrap variables!

**Comment by IanDelMar** [comment]
@Fedora-Man check the order you import files. I guess you're importing the file containing the custom color map before loading the bootstrap variables.

**Comment by Fedora-Man** [comment]
This is my child-theme.scss:

@font-face {
    font-family: 'DIN';
    src: url('../fonts/din-next-lt-arabic-light.ttf') format('truetype');
}

@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap');

@import "assets/bootstrap5/bootstrap";                             // <------- Loads Bootstrap5

@import "assets/understrap/theme/understrap";  // <------- Loads the Understrap defaults. Just a few classes to incorporate BS in WP
// @import "assets/understrap/theme/woocommerce"; // <------- Loads WooCommerce style fixes. Comment out if you aren't using WooCommerce

// Optional files - If you don´t use the corresponding scripts/fonts comment em out
//@import "assets/fontawesome/font-awesome";                           // <------- Font Awesome Icon font
@import "assets/underscores";                            // <------- Underscores media styles

// Any additional imported files //
@import "theme/child_theme_variables";              // <------- Add your variables into this file. Also add variables to overwrite Bootstrap variables here
@import "assets/understrap/theme/colors";           // <-------- This creates the necessary bootstrap color classes.
@import "assets/understrap/theme/blocks";           // <-------- This adds Bootstrap styles to blocks.
@import "assets/understrap/theme/contact-form7";    // <-------- Contact Form 7 - Bootstrap 4 support
@import "theme/archive";
@import "theme/sidebar";
@import "theme/slider";
@import "theme/rtl";
@import "theme/nav_menu";

**Comment by IanDelMar** [comment]
@Fedora-Man Check out https://github.com/understrap/understrap/pull/1640

**Comment by bacoords** [comment]
Closing this issues as it appears to be resolved with BS5.2, but please re-open if we're still having issues

**Comment by mrelliot69** [comment]
still having issues with this on bs5.2, any ideia on how i can solve it?

**Comment by IanDelMar** [comment]
> still having issues with this on bs5.2, any ideia on how i can solve it?

Can you please share your scss and errors that are reported?

**Comment by mrelliot69** [comment]
Yeah, 

```
        .ribbon-#{$color} {
            background: ($value);

            &:before {
                border-color: darken(($value), 10%) transparent transparent;
            }
```

the error that is giving when compiling is, the #fff is not a color 
i saw that this can be caused because the new bootstrap adds !default on theme_colors but im not sure how to solve it

**Comment by IanDelMar** [comment]
I guess this is wrapped in an `@each` loop like `$color, $value in $theme-colors { ... }`, right? Have you redeclared `$theme-colors` or merged another map into it?

**Comment by mrelliot69** [comment]
yeah that is on a each loop like this
`    @each $color,
    $value in $theme-colors {
        .ribbon-#{$color} {
            background: ($value);

            &:before {
                border-color: darken(($value), 10%) transparent transparent;
            }
`

i have the variables of bootstrap and then mine
`@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/mixins";

@import "variables";`

**Comment by IanDelMar** [comment]
Are you using Bootstrap 4 or 5? For Bootstrap 5 it should be
```scss
@import "functions";
@import "variables";
@import "maps"; // <--- missing
@import "mixins";
```
