### ISSUE TITLE
theme.js is inside an additional js folder on Source tab - Chrome Inspector

### ISSUE THREAD

**Issue by riccardoarca** [understrap/understrap#1641]
On Sources tab, on Chrome inspector, I can see that theme.js is inside an additional js folder.
I'm getting an error as I try to inspect the file:
"Could not load content for http://localhost:8888/woocommerce-blow-theme/wp-content/themes/understrap-master/js/js/theme.js (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)"
That's because actually the file doesn't exist under that folder.
That issue doesn't allow me to debug the file and to use the console.
No errors or warnings on the console.
Could you please help me?
Thanks

**Debug Checklist**
Please include all of the following:
- [ version": "1.1.0"] The version of Understrap you're using (located in the package.json file)
- [ ] Whether you are developing with Understrap or the Understrap child theme
- I'm developing with Understrap
- [ v16.13.1 ] The output of `node -v`
- [git version 2.17.2 (Apple Git-113) ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)
- [ ] CLI version 2.1.0 , but I'm using the last version so I'm using npm

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.
![screenshot-woo-theme](https://user-images.githubusercontent.com/74507326/156318292-2dc0d8b3-d602-4c4e-8ce0-ac9c3dd4282d.png)

**Comment by bacoords** [comment]
Can you share the `wp_enqueue_scripts` part of your functions.php file so we can see how this file is being enqueued?

**Comment by riccardoarca** [comment]
Hi, 
thanks for getting back to me, here the enqueue.php:

<?php
/**
 * Understrap enqueue scripts
 *
 * @package Understrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'understrap_scripts' ) ) {
	/**
	 * Load theme's JavaScript and CSS sources.
	 */
	function understrap_scripts() {
		// Get the theme data.
		$the_theme         = wp_get_theme();
		$theme_version     = $the_theme->get( 'Version' );
		$bootstrap_version = get_theme_mod( 'understrap_bootstrap_version', 'bootstrap4' );
		$suffix            = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';

		// Grab asset urls.
		$theme_styles  = "/css/theme{$suffix}.css";
		$theme_scripts = "/js/theme{$suffix}.js";
		if ( 'bootstrap4' === $bootstrap_version ) {
			$theme_styles  = "/css/theme-bootstrap4{$suffix}.css";
			$theme_scripts = "/js/theme-bootstrap4{$suffix}.js";
		}

		$css_version = $theme_version . '.' . filemtime( get_template_directory() . $theme_styles );
		wp_enqueue_style( 'understrap-styles', get_template_directory_uri() . $theme_styles, array(), $css_version );

		wp_enqueue_script( 'jquery' );
		wp_enqueue_script( 'select2-scripts', get_template_directory_uri() . '/js/select2.min.js', array(), $theme_version, true );
		wp_enqueue_script( 'slick-scripts', get_template_directory_uri() . '/js/slick.min.js', array(), $theme_version, true );
		wp_enqueue_script( 'wow-scripts', get_template_directory_uri() . '/js/wow.min.js', array(), $theme_version, true );
		wp_enqueue_script( 'matchheight-scripts', get_template_directory_uri() . '/js/jquery.matchHeight-min.js', array(), $theme_version, true );

		$js_version = $theme_version . '.' . filemtime( get_template_directory() . $theme_scripts );
		wp_enqueue_script( 'understrap-scripts', get_template_directory_uri() . $theme_scripts, array(), $js_version, true );
		//if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
			//wp_enqueue_script( 'comment-reply' );
		//}
	}
} // End of if function_exists( 'understrap_scripts' ).

add_action( 'wp_enqueue_scripts', 'understrap_scripts' );

**Comment by kirannasim** [comment]
@bacoords I can see this issue via Chrome inspector, but I can not see any 404 error via console. I am attaching the screenshot.

![image](https://user-images.githubusercontent.com/11325580/156774569-8ebd3d83-6a12-4716-b954-a94cacf34046.png)

**Comment by kirannasim** [comment]
This issue is happening because of the wrong source map option in the terser config JSON files.

src/build/terser.config.json
src/build-bootstrap4/terser.config.json

I fixed the issue opened PR https://github.com/understrap/understrap/pull/1649 with the updates.

**Comment by IanDelMar** [comment]
@bacoords Afaik this issue has been resolved.
