### ISSUE TITLE
Mixed license information

### ISSUE THREAD

**Issue by IanDelMar** [understrap/understrap#1651]
### The Bug

Mixed information which GPL version applies.

https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/style.css#L12
https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/package.json#L46
https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/composer.json#L5
https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/LICENSE#L1-L2

**Comment by bacoords** [comment]
We should probably sync these up. I see no reason not to use v3 for all of them.

**Comment by IanDelMar** [comment]
@bacoords fixed (all licences moved to GPL-3.0) in v1.2.0
