### ISSUE TITLE
_blocks.scss in the end of child-theme.min.scss

### ISSUE THREAD

**Issue by fuenfacht** [understrap/understrap#1690]
Hello together,

we have a strange problem.

After compiling the scss file of the child theme, understrap adds more css commands to the child theme css "/childtheme/css/child-theme.min.css?ver=1.1.0".

The following scss file is appended to the child-theme at the very end: "/childtheme/search/sass/assets/understrap/theme/_blocks.scss".

The "_blocks.scss" does not go there. It overwrites our css styles.

Does anyone know about this problem?

- **WordPress Version:** 5.9.2
- **Browser:** all
- **Understrap Version:** 1.1.0 
- **Understrap-Child Version:** 1.1.0

**Comment by bacoords** [comment]
If you don't want to include the _blocks.scss styles in your child theme, you can comment it out in 
`/src/sass/child-theme.scss` and `/src/sass/custom-editor-styles.scss`

**Comment by IanDelMar** [comment]
@bacoords No feedback for 6 month. I think the issue can be closed.
