### ISSUE TITLE
No gulpfile in this repository.  Should there be or do I need to create my own?

### ISSUE THREAD

**Issue by toddpraha** [understrap/understrap#1715]
I'm just a little confused about using gulp with this understrap theme.  After running npm install I don't get a gulpfile nor is there one in the download.  Documentation suggests there should be a gulpconfig.json, but I don't see that either.  I clearly am misunderstanding something, but do I need to create my own gulpfile.js with custom tasks or should there be one already?  Thank you

**Comment by bacoords** [comment]
@toddpraha Understrap migrated away from Gulp a while back. Can you let us know where you're seeing gulp referenced so we can clean up the documentation? 

Proper docs are available at docs.understrap.com

**Comment by toddpraha** [comment]
Ah I see now I was looking at the wrong documentation.  No gulp reference in the link you sent that I can see.  Thank you

**Comment by bacoords** [comment]
No problem - if you could share the URL you were looking at, we could potentially clean that up as well.

**Comment by toddpraha** [comment]
This one, not sure how official it is https://usdocu.tarthemes.com/docs/0.8.2/development/developing-with-npm-and-gulp/

**Comment by toddpraha** [comment]
One other quick question, when I run "npm run watch" the theme.css files and .min files get updated but nothing happens in the browser.  When I examine with dev tools I don't see a reference to theme.css or it's .min file.  My understanding is theme.scss is where I should make these changes?  Also javascript not updating even though browsersync appears to work. Do you have any thoughts on what I can try?  I'm not using the child theme, fyi.  Thanks.

**Comment by bacoords** [comment]
You'll need to run `npm run watch-bs` to use the browser sync with watch

**Comment by IanDelMar** [comment]
@bacoords No feedback or additional question for 7 month. I think the issue can be closed.
