### ISSUE TITLE
Build \ dist command - render bootstrap 5, not 4

### ISSUE THREAD

**Issue by yoscbd** [understrap/understrap#1716]
I am not using a child theme, 
I am using bootstrap 5 for my project.

in order to have bootstrap 5 compile i handed to change "watch-run-css" command on line 24 of your package.json

I am done with development and want to build my project.

i run  "run dist-build" but in my **dist** folder i get bootstrap 4 and is mess up my theme.

in package.json, lines 28-30  i see the dist commands, how sould i modify them in order to use bootstrap 5 and not 4?
```

    "dist": "npm-run-all --parallel css js css-bs4 js-bs4",
    "dist-build": "node src/build/dist-build.js",
    "dist-clean": "node src/build/dist-clean.js"


The only thing that fixes this issue is selecting "bootstrap 5" under:
Customizing >>Theme Layout Settings >>Customizing
Theme Layout Settings
in the customizer.

is there another correct way to differ bootstrap 4 & 5 while running build commands?

**Comment by yoscbd** [comment]
so i just run "npm run dist-build" and i see everything in the dist folder.

Did i do it the right way?

**Comment by bacoords** [comment]
You can modify the `dist` command to remove the bs-4 assets:
`"dist": "npm-run-all --parallel css js"`

But yes you'd still need to tell the customizer that you want bootstrap 5 not 4.  You can also force Bootstrap 5 in your theme by using this function we use in the child theme: 

```php
/**
 * Overrides the theme_mod to default to Bootstrap 5
 *
 * This function uses the `theme_mod_{$name}` hook and
 * can be duplicated to override other theme settings.
 *
 * @param string $current_mod The current value of the theme_mod.
 * @return string
 */
function understrap_default_bootstrap_version( $current_mod ) {
	return 'bootstrap5';
}
add_filter( 'theme_mod_understrap_bootstrap_version', 'understrap_default_bootstrap_version', 20 );
```

**Comment by yoscbd** [comment]
Thank you!
