### ISSUE TITLE
My site completely disappeared 

### ISSUE THREAD

**Issue by corythwa** [understrap/understrap#1723]
<!--I am using UnderStrap ChildVersion: 0.5.3

When i check the error log I see this message 

#7 {main}
  thrown in /home1/afrocen6/public_html/wp-content/themes/custom/header.php on line 61

	i attach the full error
[error_log.pdf](https://github.com/understrap/understrap/files/8533780/error_log.pdf)
g

**Comment by mattneal-stafflink** [comment]
uhh...can you give more info? lol.

**Comment by IanDelMar** [comment]
@bacoords I suggest to close this issue.
