### ISSUE TITLE
Installing GSAP and its bonus files into my understrap child theme

### ISSUE THREAD

**Issue by matt-l-82** [understrap/understrap#1742]
Hi there,

My issue relates to Gsap. I'm using an undertsrap child theme and I can't seem to get Gsap and the bonus files to work correctly. The issue or error from my console is "Cannot use import statement outside a module ". If i use "require", the console also comes up with an error. I have tried using the UMD sytax as these are highly compatible, but still no joy. I have looked through the rollup.js docs and found that you could use the file extension mjs or cjs depending on the version of node you are running but this still does not seem to work either, so I'm not sure if I've misunderstood the documentation and I have to configuring something within rollup.js? 

Any help would be most appreciated.

**Comment by bacoords** [comment]
I haven't used GSAP + Understrap specifically, but can you share some of the code imports to see how your importing it. I also saw this:

> The NPM files are ES modules, but there's also a /dist/ directory with [UMD](https://www.davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/) files for extra compatibility.
https://www.npmjs.com/package/gsap

**Comment by IanDelMar** [comment]
@bacoords No feedback since 6 month. I think the issue can be closed now.
