### ISSUE TITLE
Autoplay hero slider on Hompeage

### ISSUE THREAD

**Issue by yoscbd** [understrap/understrap#1753]
**Hi,
How can I make the Hero slider on the front page to start automatically after page load and change slides?**

I saw this thread saying it was removed?
https://github.com/understrap/understrap/pull/1430 

Thank you!

**Comment by bacoords** [comment]
You can override the template file [/sidebar-templates/sidebar-hero.php](https://github.com/understrap/understrap/blob/main/sidebar-templates/sidebar-hero.php) and change/remove that `data-interval` / `data-bs-interval` attribute

https://getbootstrap.com/docs/5.1/components/carousel/#options

**Comment by yoscbd** [comment]
Thank you, I will try that!

**Comment by IanDelMar** [comment]
@yoscbd Did changing/removing the data attribute work for you? If so, please, consider closing the issue.

**Comment by yoscbd** [comment]
Thank you!
