### ISSUE TITLE
Footer Full widget area role="footer" markup causes "[role] values are not valid" in Lighthouse testing

### ISSUE THREAD

**Issue by tristanmason** [understrap/understrap#1775]
### The Bug

**Describe the bug**

In sidebar-footerfull.php, this ARIA role markup is causing a lower accessibility score in Lighthouse:
`<div class="wrapper" id="wrapper-footer-full" role="footer">`

It reports the error: **[role] values are not valid**
and provides a link to [more information](https://www.w3.org/TR/wai-aria-1.1/#role_definitions), showing that 'footer' is not a valid ARIA role definition.

**To Reproduce**
1. Activate the Footer Full widget area in Understrap
2. In Chrome, test an Understrap page with Lighthouse
3. Look in the Lighthouse accessibility report

**Expected behavior**
Footer Full markup should use a valid ARIA role, improving accessibility and Lighthouse scores.

### The Environment

- **WordPress Version:** 6.0.0
- **Browser:** Chrome Version 102.0.5005.115 (Official Build) (x86_64)  
- **Language:** PHP / HTML

**Comment by bacoords** [comment]
This is a good point. We can just remove the role, though I'm wondering if there's any other semantic markup we should consider? For the other sidebars we just removed the roles and didn't add anything because the widgets themselves get wrapped in an aside.

**Comment by pattonwebz** [comment]
Using `role="complimentary"` is a common substitute for footer sections. `aside` may also be suitable. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/complementary_role

**Comment by IanDelMar** [comment]
@bacoords The widgets inside the "footer full" area (and the "top full" area) are _not_ wrapped in `<aside>` tags.

See https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/inc/widgets.php#L161-L171

in contrast to the left and right sidebar

https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/inc/widgets.php#L100-L123

**Comment by bacoords** [comment]
Wow- @IanDelMar  good point. Didn't even realize that.

**Comment by IanDelMar** [comment]
@bacoords fixed in v1.2.0
