### ISSUE TITLE
Plugins and themes translation doesn't fully work

### ISSUE THREAD

**Issue by AleCss81** [understrap/understrap#1782]
**Describe the problem**
Hi, I'm developing an e-commerce based on Understrap and I'm encountering problems with translation. The site is correctly translated in italian, but there are some words that aren't it. "Search" of the search pages isn't translated for example. And every try I do putting the translated .po and .mo file for plugins faults to works. I have usign the Wordpress method, putting the translation files inside /languages/plugins.

**Debug Checklist**
Please include all of the following:
- [ 1.1.0] The version of Understrap you're using (located in the package.json file)
- [Understrap child theme ] Whether you are developing with Understrap or the Understrap child theme
- [v14.16.0 ] The output of `node -v`
- [ 2.23.0] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
![image](https://user-images.githubusercontent.com/5421829/173353765-c171b0a0-77bd-491c-aec4-681304fcc190.png)
![image](https://user-images.githubusercontent.com/5421829/173353938-28e39b3f-b3d7-422f-9551-86efabd94187.png)

**Comment by pattonwebz** [comment]
I can take on giving the theme a pass and making sure strings have translation functions wrapping them. @bacoords feel free to assign this to me and I'll tackle this week :)

**Comment by IanDelMar** [comment]
@AleCss81 is this still an issue? The Italian translation for "Search..." has been added in September. The two WooCommerce strings are not part of the templates Understrap comes with. However, they both are translated:
* "[View Cart](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/it/default/?filters%5Btranslation_id%5D=48769028
)"
* "[Checkout](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/it/default/?filters%5Btranslation_id%5D=75011630)"

If you use custom source strings. You have to add the translations to your child theme yourself. Put your translation files into `wp-content/themes/my-child-theme/languages`. Then put this into your functions.php:
```php
/**
 * Loads the child theme textdomain.
 */
function my_child_theme_load_textdomain() {
    load_child_theme_textdomain( 'understrap', get_stylesheet_directory() . '/languages' );
}
add_action( 'after_setup_theme', 'my_child_theme_load_textdomain' );
```
And make sure you have added the text domain in your style.css
```css
/*
Theme Name: My Child Theme
// Other theme information goes here
Text Domain: my-child-theme
*/
```

**Comment by IanDelMar** [comment]
@bacoords No feedback; I suggest to close this issue.
