### ISSUE TITLE
understrap_wc_form_field_args() not updated for use with Bootstrap 5

### ISSUE THREAD

**Issue by IanDelMar** [understrap/understrap#1827]
### The Bug
[understrap_wc_form_field_args()](https://github.com/understrap/understrap/blob/d904a2c0c50dbcccdef7f770587932ed0f0045ab/inc/woocommerce.php#L76-L137) has not been updated to be compatible with Bootstrap 5. Classes not compatible with Bootstrap 5:
* form-group
* form-control on `<select>`
* custom-control, custom-control-*, custom-checkbox/radio

### The Environment
Does not depend on the environment.

**Comment by IanDelMar** [comment]
@bacoords I could work on this issue this weekend if it should be fixed in release v1.2.0.

**Comment by bacoords** [comment]
Sounds good

**Comment by IanDelMar** [comment]
Fixed in [v1.2.0](https://github.com/understrap/understrap/releases/tag/v1.2.0)
