### ISSUE TITLE
After MACOS Upgrade to Monterey 12.5.1 - ERR_TOO_MANY_REDIRECTS?

### ISSUE THREAD

**Issue by dekkydog** [understrap/understrap#1878]
My Setup
=======

Understrap child-theme 1.1.0
Node JS 16.15.1
NVM 0.39.1
NPM 8.11.0
git version 2.32.1 (Apple Git-133)

Problem Description
================

I recently upgraded from MAC OS 'Big Sur' to 'Monterey (12.5.1)'. When running 'npm run watch-bs' everything is compiled without any visible errors in VS Code, Chrome is launched (http://localhost:3000/mysite) but site does not load? Instead I see:

This page isn’t working
localhost redirected you too many times.
[Try clearing your cookies]
ERR_TOO_MANY_REDIRECTS

Looking in the browser developer console I see:

​ crbug/1173575, non-JS module files deprecated.

* Prior to the upgrade everything was working fine? 
* I am at a loss about what the issue(s) might be? 
* Any help or advice appreciated :-)

**Comment by IanDelMar** [comment]
Could you please check whether one of these solutions works for you as well? https://stackoverflow.com/questions/67191286/crbug-1173575-non-js-module-files-deprecated-chromewebdata-index%ea%9e%89530595551/70790501#70790501

**Comment by dekkydog** [comment]
@IanDelMar thanks for getting back to me :-) I had already been looking at and trying "some" of the solutions shown in the article - no joy yet :-( Prob the lack of understanding in this area is not helping?

**Comment by bacoords** [comment]
After upgrading - did you also delete your node_modules and package-lock.json and try re-installing via `npm install`?

**Comment by dekkydog** [comment]
> After upgrading - did you also delete your node_modules and package-lock.json and try re-installing via `npm install`?

@bacoords Thanks for responding :-) Yeah, thats prob a good idea - not tried it yet? I'll give it a go!

**Comment by dekkydog** [comment]
> After upgrading - did you also delete your node_modules and package-lock.json and try re-installing via `npm install`?

I tried.... no joy :-( Not sure what to do next?

**Comment by pattonwebz** [comment]
> > After upgrading - did you also delete your node_modules and package-lock.json and try re-installing via `npm install`?
> 
> I tried.... no joy :-( Not sure what to do next?

Could you try to clear the cache of pre-built binaries as well with `npm cache clean --force` and see if it lets you install and works after that?

**Comment by dekkydog** [comment]
> > > After upgrading - did you also delete your node_modules and package-lock.json and try re-installing via `npm install`?
> > 
> > 
> > I tried.... no joy :-( Not sure what to do next?
> 
> Could you try to clear the cache of pre-built binaries as well with `npm cache clean --force` and see if it lets you install and works after that?

Thanks @pattonwebz :-) ....I'll give that a go!

**Comment by dekkydog** [comment]
No joy @pattonwebz :-( Feel like I've hit some strange edge case? Might have to try nuclear option and start over :-/

**Comment by IanDelMar** [comment]
If everything is compiled then I guess the problem domain starts with browsersync and ends with WordPress. Have you tried different ports? Does Chrome for whatever reason try to access localhost via https? Have you tried a different browser?

**Comment by dekkydog** [comment]
> If everything is compiled then I guess the problem domain starts with browsersync and ends with WordPress. Have you tried different ports? Does Chrome for whatever reason try to access localhost via https? Have you tried a different browser?

Hi @IanDelMar ..... I'm using the default MAMP ports (I.E localhost:8888) and Chrome is def not accessing localhost via https. Tried multiple browsers inc Chrome, Safari, FF. Cleared all Caches. 

Even cutting browsersync out of the loop and visting: http://localhost:8888/mysite also instantly redirects back to http://localhost:3000/mysite (with the ERR_TOO_MANY_REDIRECTS notification)?

Visiting http://127.0.0.1:8888/mysite does show the site but with no styling and numerous 'Failed to load resource: net::ERR_CONNECTION_REFUSED' in the chrome developer console.

**Comment by IanDelMar** [comment]
Can you add a simple Hello World index.html loading a small css file to the WordPress install directory? I suspect that WordPress is the cause. You can also rule out Understrap and npm as a cause by deleting the theme and using a default theme. I'm pretty sure the redirect persists.

**Comment by IanDelMar** [comment]
Can you also please check what is stored in the database for 'siteurl' and 'home' (options table) or whether the urls are defined in your wp-config.php?

**Comment by dekkydog** [comment]
> 

Added as instructed....

http://localhost:8888/mysite - loads temporary index.html with stylesheet

http://localhost:3000/mysite - stuck in endless redirect

**Comment by dekkydog** [comment]
> Can you also please check what is stored in the database for 'siteurl' and 'home' (options table) or whether the urls are defined in your wp-config.php?

Let me have a quick look...

**Comment by IanDelMar** [comment]
> http://localhost:8888/mysite - loads temporary index.html with stylesheet

backs up that WordPress is the issue.

> http://localhost:3000/mysite - stuck in endless redirect

I wouldn't mind the redirect loop on port 3000. The problem is that 8888 redirects to 3000 which is most likely caused by WordPress.

**Comment by IanDelMar** [comment]
This might be helpful: https://wordpress.org/support/article/changing-the-site-url/#relocate-method. Maybe he upgrade to Monterey is similar to a server change.

**Comment by dekkydog** [comment]
YAY! you were right @IanDelMar looking at the WordPress DB options table.... for some reason the 'siteurl' and 'home' were set to http://localhost:3000/mysite - hence the endless redirect loop. HTF this happened is a mystery! I 100% did not change this? Any ideas?

Thanks for all your help and time @IanDelMar @pattonwebz @bacoords :-)
