### ISSUE TITLE
can't add block theme support for understrap (trying to Convert a classic understrap theme to a block theme)

### ISSUE THREAD

**Issue by yoscbd** [understrap/understrap#1885]
I'm trying to convert my classics understrap them to a block theme.

According to the [official WordPress documentation](https://developer.wordpress.org/themes/block-themes/converting-a-classic-theme-to-a-block-theme/) i need to add this to my functions.php:

1. add_theme_support( 'block-templates' );
2. include a theme.json file in the root of my theme

I have followed the guidlines and added everything yet the block theme editor functionality dosnt appear in my admin menue
Appearance > editor (beta)

How can I add block theme support to understrap? :)

**Comment by bacoords** [comment]
A block theme is fundamentally different from a classic or hybrid theme, which Understrap is. Unfortunately, a block theme can _only_ use HTML generated by the block editor, meaning we can't use the markup necessary for Bootstrap to function correctly. 

There's some stuff coming later that might allow us to use parts of the block editor to replace some of the widget areas, and we're working on using theme.json where it could make sense, but otherwise, there's no real path towards converting an Understrap theme into a block theme or turning on the full site editor with Understrap.

**Comment by yoscbd** [comment]
Thank you for your quick reply!  :)

So if I understand correctly -  At the monument the best practice to allow users to use custom/core Gutenberg blocks in order to build the **entire** post or page will be to use the "the_content()" inside the page/post template .php file - correct?

That means in my page template i will only add "the_content()" (so we can display the blocks) and all of the different sections should be written as custom Gutenberg blocks. - correct?

**Is there a better practice to achieve the goal of allowing the user to edit posts and pages with Gutenberg blocks?**

Thank you!

**Comment by bacoords** [comment]
There's no reason you can't build pages in the block editor right now. Many of our child themes are just Understrap with pages built the block editor (we even include block patterns). Here's an example of an Understrap home page built in the standard block editor: 

https://demos.understrap.com/corporate-child-theme/

**Comment by yoscbd** [comment]
Thank you for your appreciated detailed reply.
I will dig in to it. 😃🙏🏼

**Comment by anderskitson** [comment]
When you say you include block patterns, are you saying you can create patterns in your theme that can then be selected in the block editor? Do you create these patterns in PHP, do they have to go in a certain folder, how does this work?

**Comment by bacoords** [comment]
Basically you can create your own block patterns inside the block editor, then copy/paste the HTML from the editor into a function that lives in a PHP file in your theme. This is accomplished with the `register_block_pattern()` function. Then anyone using your theme would see those block patterns as options in the block editor. You can see a screenshot if you scroll down here: https://understrap.com/child-themes/


Further reading:
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern
https://developer.wordpress.org/reference/functions/register_block_pattern/

**Comment by anderskitson** [comment]
Ok perfect thanks for you help makes sense.

**Comment by anderskitson** [comment]
Also wanted to ask and maybe I should open a separate issue for this, but as a team we are deciding if we should go full site editing theme, or use understrap, do you know what the benefit of sticking with understrap would be? We are developer heavy and it seems full site editing is focused highly on building the site in the editor. Are there things you cannot do with full site editing that understrap is good at. Thanks I will pose this question somewhere else if needed.

**Comment by bacoords** [comment]
I'd recommend opening a new [discussion](https://github.com/understrap/understrap/discussions) so others can respond
