### ISSUE TITLE
Editor Area Missing Margins 

### ISSUE THREAD

**Issue by gracer100** [understrap/understrap#1905]
I'm using the Child Tech starter theme with bootstrap 5 and WordPress 6.0.2

All is sunshine & roses except for one thing I can not see how to fix.  The backend editor style has lost  left / right margins.  Somehow my styles have lost some css for elements:  editor-styles-wrapper block-editor-writing-flow  Or, perhaps it's the wp-block class. 

It's clearly something I've done / not done in my child theme, but I've spent so many hours comparing files I'm nearly blind.  

My child-theme.scss and custom-editor-style.scss are straight from the Child Tech files. 

I created one new page-template and one new sidebar-template, registered a new sidebar.  That's about the only custom changes I've made. 

Actually, everything on the front end looks perfect and exactly as I would expect. It's just really annoying that the editor window content area is full-width and flush against the column edges.   Hope you can point me to the issue that may be causing this. 

Thanks Heaps. 

  "name": "understrap-child-tech"
  "version": "1.1.0"
   node v14.18.0
   git version 2.30.2

<img width="1038" alt="sample-page" src="https://user-images.githubusercontent.com/12419494/190551732-a9897332-a450-4d20-a928-b8cb9c67308b.png">

**Describe the problem**
A clear and concise description of the problem.

**Debug Checklist**
Please include all of the following:
- [ ] The version of Understrap you're using (located in the package.json file)
- [ ] Whether you are developing with Understrap or the Understrap child theme
- [ ] The output of `node -v`
- [ ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by bacoords** [comment]
Out of curiosity - have you tried disabling every plugin one-by-one to confirm it's a problem with the theme?

**Comment by gracer100** [comment]
Great idea, just tried that.  Sadly, no change.

**Comment by gracer100** [comment]
Ok!  I found the problem.  I created a theme.json file in the main folder of the theme.   It's just for one branding color that is used everywhere.  Works fine in the block editor as a custom color. 

It must be overwriting something needed for the editor?  

This is probably getting outside of understrap and into WP, but can you point me to anyplace in understrap so I'm not overwriting?   FYI, this is my little theme.json

```
{
    "version": 2,
    "settings": {
        "color": {
            "palette": [
                {
                    "name": "DeckhandBlue",
                    "slug": "deckhand-blue",
                    "color": "#2378BD"
                }
            ]
        }
    }
}


```

**Comment by gracer100** [comment]
Success.  Dug around and updated my theme.json with a layout setting.  So far I think this is the solution, unless you tell me otherwise for some reason.  If it strikes you as an ok solution, It's probably now ok to close this. 

```
{
    "version": 2,
    "settings": {
        "color": {
            "palette": [
	        {
                    "name": "DeckhandBlue",
                    "slug": "deckhand-blue",
                    "color": "#2378BD"
		}
	    ]
        },
        "layout": {
            "contentSize": "840px",
            "wideSize": "1100px"
        }
    }
}

```

**Comment by bacoords** [comment]
Ah that's good to know! I'm still working on figuring out how to set up theme.json and get it to feel 'synced' with the bootstrap variables (colors, sizes, etc) so this is good to know.
