### ISSUE TITLE
Child theme error after site migration

### ISSUE THREAD

**Issue by pkoningsgithub** [understrap/understrap#1951]
**Describe the problem**
After we have moved our website to a new server, the child theme keeps giving me a php error not being able to find a file. I checked the path and the file it is trying to get to is indeed not even on the server, but also not on the old server.

/home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/../../../vendor/autoload.php

This "vendor" folder is nowhere to be found

**Debug Checklist**
Please include all of the following:
- [1.1.0 ] The version of Understrap you're using (located in the package.json file)
- [child] Whether you are developing with Understrap or the Understrap child theme
- [?] The output of `node -v`
- [?] The output of `git --version`
- [?] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
Warning: require(/home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/../../../vendor/autoload.php): failed to open stream: No such file or directory in /home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php on line 3

Warning: require(/home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/../../../vendor/autoload.php): failed to open stream: No such file or directory in /home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php on line 3

Fatal error: require(): Failed opening required '/home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/../../../vendor/autoload.php' (include_path='.:/opt/alt/php72/usr/share/pear') in /home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php on line 3

**Additional context**
If i rename the child theme folder I can atleast access the admin panel again, but I lose all the styling of my website, I also tried to disable all plugins after and then re-activate the child theme, but thesame error comes up after.

**Comment by IanDelMar** [comment]
What is the content of /home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php, especially of line 3?

Seems to be related to Composer. Do you use the Composer to autoload something?

**Comment by pkoningsgithub** [comment]
> What is the content of /home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php, especially of line 3?
> 
> Seems to be related to Composer. Do you use Composer to autoload something?

Hello, thank you for your response.

This is the code:

<?php

require __DIR__ . '/../../../vendor/autoload.php';

(function () {
    /** @var \Psr\Container\ContainerInterface $container */
    $container = require __DIR__ . '/../../../config/container.php';

    $app = $container->get(\Gvs\Wordpress\Application::class);

    $app->disableComments();

    $app->run();
})();

If I remove line 3, it will start complaining about line 7 next.
I'm sorry but I'm not technical enough to determine if I use composer to autoload anything... could you tell me how to verify this?

**Comment by IanDelMar** [comment]
`require __DIR__ . '/../../../vendor/autoload.php';` requires the file the error is about.

The `../` moves one directory up. Starting from the current location (/home/nous/domains/nous.nl/public_html/wp-content/themes/understrap-child/functions.php -> understrap-child) `../`  gives the themes directory, `../../` gives the wp-content directory and `../../../` gives the public_html directory. public_html is the web root for your domain. If you put myfile.html in public_html it will be accessible through www.mydomain.com/myfile.html.

public_html is also the directory which contains Composer's vendor directory. Which does not exist. Do you know whether you can  use Composer on the new server? Do you still have access to the old server? Who has set up you WordPress installation and your theme?

You could try to comment out the whole code fragment
```php
// require __DIR__ . '/../../../vendor/autoload.php';

// (function () {
//     /** @var \Psr\Container\ContainerInterface $container */
//     $container = require __DIR__ . '/../../../config/container.php';

//     $app = $container->get(\Gvs\Wordpress\Application::class);

//     $app->disableComments();

//     $app->run();
// })();
```

**Comment by pkoningsgithub** [comment]
@IanDelMar 

I am starting to slowly realise what has happened.
I think the website is based on understrap but modified by the agency who built the website.
Also they had shared hosting, so that's why there is an extra /nous/ in the path.
I contacten the original creators of the website to ask if they can help me fix it, but i'm afraid these custom lines are all troughout the website... 
Thank you for your insight, it did help me realize :)
