### ISSUE TITLE
Collapse or Offcanvas BS5 not opening mobile menu for child theme

### ISSUE THREAD

**Issue by rockyplanet** [understrap/understrap#1987]
I am a designer, not a developer. However I'm comfortable editing code when instructed what to fix.
My problem is in the mobile menu. When I change to Bootstrap 5 using the customizer and select either Collapse or Offcanvas, I am unable to open the menu when I click on the hamburger button. The templates I'm using are understrap-blog and understrap-portfolio although I have tested this out on the other child theme templates and I still have this problem. The only one that works is the parent theme.

Can someone help me out with what to edit to get this to work properly?

**Comment by bacoords** [comment]
Understrap child themes include their own CSS/JS and are typically written either for Bootstrap 4 OR Bootstrap 5 but not both. You can check the child-theme.js file to see if it's expecting 4 or 5. There's a lot of breaking changes for Bootstrap 5.

**Comment by IanDelMar** [comment]
@rockyplanet Is this still an issue?

**Comment by IanDelMar** [comment]
@bacoords No feedback. I suggest closing this issue for now.
