### ISSUE TITLE
How to add a php file 

### ISSUE THREAD

**Issue by evanskarangu** [understrap/understrap#2005]
Hi there, I have a site build using understrap child theme. I want to connect the site to MYSQL database using PHP. I have a file called `db.php.`  I want to  add the `db.php` file to a page template I have created called `blog.php` so as to retrieve posts from the database.
When I try opening the blog page I get the error 
Warning: require(/db.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\OxyBuild\wp-content\themes\oxybuild\page-templates\blog.php

Fatal error: Uncaught Error: Failed opening required '/db.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\OxyBuild\wp-content\themes\oxybuild\page-templates\blog.php:2 Stack trace: #0 C:\xampp\htdocs\OxyBuild\wp-includes\template-loader.php(106): include() #1 C:\xampp\htdocs\OxyBuild\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\OxyBuild\index.php(17): require('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\OxyBuild\wp-content\themes\oxybuild\page-templates\blog.php on line 2
There has been a critical error on this website.

my `blog.php` looks like

1`<?php
2 require('/db.php');
/**
 * Template Name: Blog
 *
 * This template can be used to override the default template and sidebar setup
 *
 * @package Understrap
 */
// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

get_header();
$container = get_theme_mod( 'understrap_container_type' );
?>`

The `db.php` file looks like 

`<?php

session_start();
$db=mysqli_connect('localhost','root','','oxybuild') or die("Database is not connected !");
?>
`

I have been experiencing the warning every time I try to create a php file. Kindly help me know how to add such files to the understrap child theme to execute backend functions.

**Comment by IanDelMar** [comment]
@evanskarangu have you tried `require_once __DIR__ . '/db.php';` or `require_once get_template_directory() . '/page-templates/db.php';`?

**Comment by evanskarangu** [comment]
yes @IanDelMar and I still get the same error

**Comment by evanskarangu** [comment]
Thanks @IanDelMar, it worked. I changed directory to stylesheet because am using understrap child theme not the parent theme.
 ` require_once get_stylesheet_directory() . '/db.php';`

**Comment by evanskarangu** [comment]
yes @IanDelMar
