### ISSUE TITLE
undestrap-child-1.1.0 problems loading child-theme.css

### ISSUE THREAD

**Issue by dev-pavelreuk** [understrap/understrap#2006]
### The Bug

**Describe the bug**

CSS files are not linked in the undestrap-child-1.1.0 theme. If I add code inside the style.css file it doesn't overwrite anything.

	$suffix = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ? '' : '.min';
	// Grab asset urls.
	$theme_styles  = "/css/child-theme{$suffix}.css";
    echo $theme_styles;
	$theme_scripts = "/js/child-theme{$suffix}.js";

**To Reproduce**
1. Update style.css by adding a new body background color.
2. Save file and check results.

**Expected behavior**
3. It should change the body background color

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

### The Environment

- **WordPress Version:** [ 5.7.x | 5.8.x ]
- **OS Version:** [ Windows 7 | Windows 8 | Windows 10 ] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
- **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
- **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML ]
- **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

### Additional context
If I remove the variable $suffix that is inside the grab asset urls inside the functions.php it will start loading the current css files. I do understand that the variable $suffix is adding .min to the url, making the full theme style url to be /css/child-theme.min.css. If I remove $suffix variable, the file /css/child-theme.css will load as it's available in the under strap-child-1.1.0 folder. There is no file with .min in that folder.

**Comment by dev-pavelreuk** [comment]
I added the code below to the _child_theme_variables.scss and still no changes. Screenshots are attached.

// File: _child_theme_variables.scss
$bg-color: #000; // black body background color
<img width="1634" alt="Screenshot 2022-11-09 at 4 31 11 PM" src="https://user-images.githubusercontent.com/89788752/200964347-706b3bbd-f632-4ed8-942c-7c0527c7d594.png">
![Screenshot-2022-11-09-at-4 31 52-PM](https://user-images.githubusercontent.com/89788752/200964606-93c4b323-bfbe-494d-84c3-f5ae46454cfc.jpg)

**Comment by IanDelMar** [comment]
Have you recompiled the CSS files with `npm run css`?

**Comment by IanDelMar** [comment]
@dev-pavelreuk Is this still an issue?

**Comment by IanDelMar** [comment]
@bacoords No feedback, I suggest to close this issue.
