### ISSUE TITLE
active links always show underline without hover

### ISSUE THREAD

**Issue by rockyplanet** [understrap/understrap#2027]
I upgraded my child themes from overstrap to understrap. I have a problem with active links. When I create a active hyperlink on a blog post, it always shows an underline even when hovering over it. When I change the text from paragraph to heading, the underline is gone until I hover the mouse over it. I have not made changes to the style.css file.

What do you suggest I do to correct this?

**Comment by bacoords** [comment]
Bootstrap 5 introduces [underlining links in paragraphs by default](https://getbootstrap.com/docs/5.2/migration/#content-reboot-etc).  In recent years we've been updating accessibility standards to make sure Understrap is `accessibility-ready` out of the box and this was one of the changes. You can definitely override this in your SASS file: 

```sass
$link-decoration:                         none !default;
```

or by adding custom CSS via the customizer (this is untested code):

```css
.entry-content p a {
  text-decoration: none;
}
```

**Comment by rockyplanet** [comment]
OK. Thanks. I wasn't aware of that accessibility standard.

**Comment by IanDelMar** [comment]
@bacoords This issue can be closed.
