### ISSUE TITLE
Feature Request: switch back to inc/editor-color-palette.json with Bootstrap 4 colors.

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#2028]
## Problem Statement

Re: https://github.com/understrap/understrap/pull/1998#issuecomment-1319491109

## Who will benefit?

Because BS4 is the default setting, the color palette should respect that. In a future feature release we can consider migrating to a default theme.json with different styles for bs4 or 5?

## Priority/Severity

- [ ] High (This will bring a huge increase in performance/productivity/usability/legislative cover)
- [ ] Medium (This will bring a good increase in performance/productivity/usability)
- [ ] Low (anything else e.g., trivial, minor improvements)

**Comment by IanDelMar** [comment]
@bacoords Should we add a inc/editor-color-palette-bootstrap4.json to avoid switching back and forth between color palettes?

**Comment by bacoords** [comment]
Yeah that makes a lot more sense.

**Comment by IanDelMar** [comment]
We switched back to inc/editor-color-palette.json with Bootstrap 4 in v1.2.2.
