### ISSUE TITLE
What do you thing about commercial UnderStrap extensions?

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#203]
Hey guys,
currently I´am thinking about providing some sort of commercial services or maybe a premium/freemium child theme or plugin for UnderStrap.

Because UnderStrap itself is (and will stay, of course) a open source project and a lot of you contribute to it I wanna hear your opinion on that topic first.

**Question: From your point of view is it okay to provide some commercial stuff/service/extension/child theme etc. around this open source project? And: Maybe you have similar plans/ideas?**

**Comment by stef-k** [comment]
Hi all and happy new year.

I believe it is ok to build a marketplace around Understrap, e.g child themes & plugins for the main framework. Many open source projects have commercial marketplaces build on top.

My main concern though is that it may be a bit early for this kind of move. For example it would be better to reach a 1.0.0 version with enough features and stability + users (the most important of all).

One example I can think of related to your idea is the Ionic Framework for cross platform mobile development. The framework itself is open source and free but there are many other tools, services and platforms which are available as commercial products. Check here:

* http://ionicframework.com/
* https://ionic.io/?_ga=1.242064320.393007298.1473440522
* https://ionic.io/products/creator?_ga=1.242064320.393007298.1473440522
* http://view.ionic.io/?_ga=1.242064320.393007298.1473440522
* http://ionic.io/enterprise?_ga=1.242064320.393007298.1473440522
* https://market.ionic.io/

**Comment by holger1411** [comment]
You are right:
Its way to early for a full fledged marketplace. 
Its more an ethical question if I might think in this direction for the future...or not.

Meanwhile, maybe I launch a "test probe" with a nice but simple child theme to check if there is any market.

Oh, and another good example is the EDD marketplace: 
https://easydigitaldownloads.com/downloads/

**Comment by michelmany** [comment]
Hi holger, I'd love to create some UnderStrap child themes. How does it work if I wanted to sell it on envato marketplace as well? 
Thanks!
Michel Moraes

**Comment by holger1411** [comment]
Hm, don´t know if Envato offers a "child themes for theme framework" subcategory. Maybe you should ask them.
But if you manage to publish a UnderStrap child theme on themeforest.net I will be happy to link to it (currently planning a child theme subpage for understrap.com, not a "marketplace" but a showcase for 3rd party resources) from https://understrap.com.
Having 3rd party developers offering professional services is defenitely a plus for a framework, so I going to promote them.

**Comment by Thomas-A-Reinert** [comment]
That´s totally cool with me, @holger1411 .

Only problem I see spawning in this issue tracker about one and a half year later: people tend to post within this or the child-theme´s issue tracker if they have any problem with the CORE theme etc. 

We - "team understrap" - only support the free, open-source version. And when we mention that, your customers don´t seem to be too amused nor are we when they´re getting angry. Please leave a note whereever, in the readme. as a note when buying or whereever that THIS is not the right place to ask for help, okay?

Closing this issue because it´s not really an issue, all questions have been resolved and it might confuse ppl looking for help.
