### ISSUE TITLE
please update woocommerce template files to latest version

### ISSUE THREAD

**Issue by paulhaskett** [understrap/understrap#2030]
Hi I am getting an error about outdated woocommerce template files , I am using understrap v 1.2.1 with a child theme but all the outdated template files are in the parent understrap theme.  
Thanks for your help
![image](https://user-images.githubusercontent.com/14015669/203044306-b3f5b6eb-b7e7-4205-86e9-7f6d6f991b2b.png)

**Comment by paulhaskett** [comment]
ok thank you

**Comment by bradleyw92** [comment]
Also watching this.

**Comment by Matt-Inventive** [comment]
Watching :)

**Comment by bacoords** [comment]
We've pushed a [release on GitHub](https://github.com/understrap/understrap/releases/tag/v1.2.2) and are working on uploading to the theme directory for broader distribution. 

Sorry for the delay on the release here!

**Comment by paulhaskett** [comment]
awesome! thank you.

**Comment by IanDelMar** [comment]
@bacoords As v1.2.2 is available in the theme directory, this issue can be closed.
