### ISSUE TITLE
Fatal Error after update to understrap 1.2.x - Uncaught Error: Call to undefined function understrap_get_select_control_class()

### ISSUE THREAD

**Issue by BKapelari** [understrap/understrap#2031]
### The Bug
 
```
Uncaught Error: Call to undefined function understrap_get_select_control_class()
in /wp-content/themes/understrap/inc/widgets.php on line 44
```

**Describe the bug**
After the update, there is a Fatal Error in several places in the backend.
So the page is broken and the only solution is to downgrade to Understrap 1.1.x

I think the problem is here:
File: https://github.com/understrap/understrap/blob/main/inc/template-tags.php#L339-L353

**To Reproduce**
1. upgrade Understrap to version 1.2.x on a site that has the Understrap-Child theme version 1.1.x installed.
2. in the wp-admin go to posts overview or edit a page
3. See error

### The Environment

- **WordPress Version:** [ 6.1.1]
- **Browser:** [ all ]
- **Language:** [ PHP]

### Screenshots

![Bildschirm­foto 2022-11-21 um 16 52 07](https://user-images.githubusercontent.com/4718590/203099140-3025238b-9eb8-40f6-838d-74e6c2fd5286.png)

**Comment by bacoords** [comment]
Is your child theme overriding the inc/template-tags.php file? If so, then you’ll need to monitor new parent theme releases for updates to that file before updating.

You can either:

1. Copy the missing function from the parent theme to your child theme: https://github.com/understrap/understrap/blob/1d84c6332271b16be49e68cf2e7404bcc9376f62/inc/template-tags.php#L347
2. Update your child theme to override individual functions not entire function files as suggested in the documentation: https://docs.understrap.com/#/understrap-child/functions

If you use the second method, your child theme will get all new functionality from the parent theme.

Let us know if this works for you.

**Comment by BKapelari** [comment]
Thank you @bacoords ! 
This has helped
