### ISSUE TITLE
Skip to content link showing in header

### ISSUE THREAD

**Issue by garryknapper** [understrap/understrap#2036]
I have recently updated my parent theme to Understap version 1.2.1 and since doing this, a skip to content link has appeared in the top right-hand corner of the header on my site. Upon investigation, I can see that the 'sr-only' and 'sr-only-focusable' classes have been removed from the 'skip-link' element in header.php.

I looked at the change log for version 1.2.0 here: https://github.com/understrap/understrap/blob/main/.github/CHANGELOG.md and I can see a fix that says: Fixes skip to content link for Bootstrap 5.

Please could you explain in more detail the reason behind this fix? Bootstrap 5 documentation suggests to use the 'visually-hidden' class or 'visually-hidden-focusable' class instead but this hasn't been added to the element. I am working on a site that is required to be highly accessible which is why I am looking for an explanation to enhance my understanding of this change. Thank you.

**Comment by IanDelMar** [comment]
The skip link is hidden by the `.skip-link` class which applies the same styles as `.visually-hidden-focusable`: https://github.com/understrap/understrap/blob/6a58dbbae4abb2ce4eaa1e315f0d5fe39e4acd50/css/theme.css#L7750-L7762

`.sr-only` and `.sr-only-focusable` are Bootstrap 4 classes. However, `.sr-only` worked for "Bootstrap 5" as well because the bundled Font Awesome css also declares `.sr-only`.

Are you using Bootstrap 5? Do you dequeue the parent theme.css and load the child theme theme.css only?
If you are using Bootstrap 5 and you have dequeued the Understrap theme.css either add `.visually-hidden-focusable` to the skip link or add
```scss
.skip-link {
  @include visually-hidden-focusable();
}

// Or alternatively:
// .skip-link {
//   @extend .visually-hidden-focusable;
// }
```
to your child-theme.scss.

**Comment by emueller** [comment]
I'm having the same issue as @garryknapper. I'm starting development on a brand-new site for a new client and earlier today downloaded fresh versions of Understrap and Understrap Child from Github. Went through my standard list of tasks to get my child theme ready to start designing (mostly just renaming "child-theme" references to the name of my client), and when I updated the header.php file to change the navbar color, I noticed the Skip to Content link. The default header and Skip to Content link are both $primary-color, so I didn't notice it at first. If I switch to the main Understrap theme, it goes away.

I came right to these Github issues and found this post. I'm using Bootstrap 5 and haven't done much out of the ordinary that I know of. I copied header.php and navbar-offcanvas-bootstrap5.php into my child theme, but even when I take those back out the Skip to Content link is still there.

For now, I added .sr-only and .sr-only-focusable back into my header.php file. But I will keep an eye on this issue to see what the resolution is.

**Comment by IanDelMar** [comment]
> For now, I added .sr-only and .sr-only-focusable back into my header.php file. But I will keep an eye on this issue to see what the resolution is.

@emueller The Bootstrap 5 utility class for this is `.visually-hidden-focusable`. Bootstrap 5 does not come with `.sr-only` or `.sr-only-focusable`. These are classes declared by Font Awesome. Once you remove Font Awesome the skip link won't be hidden. Do you load Understrap's theme.css or just your child-theme.css? If you are not loading theme.css, include 
```scss
.skip-link {
  @include visually-hidden-focusable();
}

// Or alternatively:
// .skip-link {
//   @extend .visually-hidden-focusable;
// }
```
in your child-theme.scss.

If you have removed the class `.skip-link` readd it. It will then hide the skip link again.

**Comment by garryknapper** [comment]
> Are you using Bootstrap 5? Do you dequeue the parent theme.css and load the child theme theme.css only?
> If you are using Bootstrap 5 and you have dequeued the Understrap theme.css either add .visually-hidden-focusable to the skip link or add
> 
> .skip-link {
>   @include visually-hidden-focusable();
> }
> 
> // Or alternatively:
> // .skip-link {
> //   @extend .visually-hidden-focusable;
> // }
> to your child-theme.scss.

@IanDelMar yes I'm using Bootstrap 5 and it appears that the Understrap child theme is dequeuing the parent theme styles from line 13 of functions.php:

/**
 * Removes the parent themes stylesheet and scripts from inc/enqueue.php
 */
function understrap_remove_scripts() {
	wp_dequeue_style( 'understrap-styles' );
	wp_deregister_style( 'understrap-styles' );

	wp_dequeue_script( 'understrap-scripts' );
	wp_deregister_script( 'understrap-scripts' );
}
add_action( 'wp_enqueue_scripts', 'understrap_remove_scripts', 20 );

If I comment out the action, the skip to content link is hidden again. I'm using version 1.1.0 of the Understrap child theme.

**Comment by emueller** [comment]
> Do you load Understrap's theme.css or just your child-theme.css?

@IanDelMar I didn't know this was something I was supposed to do. I have been following Understrap documentation (and I took the Instant Understrap course a year or so ago - awesome stuff!) and ended up with the issue. Thinking maybe I did something wrong, I started over to see if I could recreate the issue. I followed these simple steps:

1. I created a fresh instance of WordPress on my local machine.
2. I downloaded Understrap.
3. I downloaded Understrap Child.
4. I activated the Understrap Child theme.
5. Skip to Content appears in the upper right corner of the site. You need to hover over the link to see it, as it's the same color as the default Understrap Child navbar.
6. I didn't change any code, change anything in WP except the active theme, or do anything with npm.

Hope that helps!

**Comment by IanDelMar** [comment]
@britweb-tim You're right. That's what I just realized.

@emueller I didn't mean to imply that you did something wrong. I focus on the parent theme and was not aware that the child theme dequeue the parent theme's CSS file by default and comes with it's own "Understrap version" which is still at v1.1.0. Thanks for bringing that to my attention. I had a closer look now. For your case: The parent theme and the child theme are out of sync. A quick solution to this is to stick with Understrap v1.1.0 for now. Click this link to download v1.1.0: https://github.com/understrap/understrap/archive/refs/tags/v1.1.0.zip

**Comment by emueller** [comment]
@IanDelMar No worries! I have made stupid mistakes before on some of the basics of getting a new site up and running before I'm able to fully get into CSS and custom code, so I thought maybe that was happening again. Glad it's not me! Thanks for the link, I'll use 1.1.0.

**Comment by bacoords** [comment]
@emueller Let us know if we can close this issue for you!

**Comment by emueller** [comment]
@bacoords I haven't downloaded fresh versions of Understrap and Understrap-child since this issue. Has it been fixed in the child theme?

**Comment by bacoords** [comment]
The new child theme fixes it but also we've updated the parent theme to make sure it's fixed there as well even if you're using an older child theme

**Comment by emueller** [comment]
Awesome, thank you! Yes, this can be closed out.

**Comment by IanDelMar** [comment]
@garryknapper is this issue resolved for you as well?

**Comment by garryknapper** [comment]
@IanDelMar Yes, I've just updated my parent theme and the issue has now been resolved. Thank you for your help with this.

**Comment by IanDelMar** [comment]
@garryknapper Great!
@bacoords We can close the issue.
