### ISSUE TITLE
npm run watch crashing

### ISSUE THREAD

**Issue by gcordner** [understrap/understrap#2049]
**Describe the problem**
npm run watch crashes:
npm ERR! understrap-child@1.2.0 css-postcss: `postcss --config src/build/postcss.config.js --replace "css/*.css" "!css/*.rtl*.css" "!css/*.min.css"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap-child@1.2.0 css-postcss script.
...
npm ERR! understrap-child@1.2.0 css: `npm-run-all css-compile css-postcss css-minify`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap-child@1.2.0 css script.

Same occurs if I run in understrap (not child).

**Debug Checklist**
Please include all of the following:
- [x] The version of Understrap you're using (located in the package.json file)
        "name": "understrap",
          "version": "1.2.1",
         "name": "understrap-child",
         "version": "1.2.0",
- [x] Whether you are developing with Understrap or the Understrap child theme
        Happens in both
- [x] The output of `node -v`
         v10.24.1
- [x] The output of `git --version`
        git version 2.32.1 (Apple Git-133)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
N/A

**Additional context**
  Clean boilerplate docksal wp install. Error is the same in understrap and understrap child. theme(s) were installed via git, ran npm install, npm run watch, nothing else touched. 

It appears that css is compiling. A change made to an scss file will show in css, but minification is failing.

**Comment by IanDelMar** [comment]
Try upgrading node.js.

https://github.com/understrap/understrap/blob/6a58dbbae4abb2ce4eaa1e315f0d5fe39e4acd50/package.json#L34-L36

**Comment by gcordner** [comment]
Yep. Thanks!
