### ISSUE TITLE
Font Awesome questions, some icons not showing up

### ISSUE THREAD

**Issue by amillionmiles** [understrap/understrap#2061]
### Discussed in https://github.com/understrap/understrap/discussions/2060

<div type='discussions-op-text'>

<sup>Originally posted by **amillionmiles** January  4, 2023</sup>
Hi,
I apologize if this is a stupid question, but I'm new to Understrap (using the child theme), and some of my Font Awesome icons are not showing up without using the Font Awesome plugin. I tried using variations of .fa and .fa-solid, and that works for some of them, but not all of them. One example that doesn't work is fa-file-lines. They show up fine with the plugin. I would like to figure out how to get them to work, but I also have some more general questions:
Could someone please explain to me what the advantage of adding the font files locally in the theme is compared to using the plugin with a kit?
If I decide to go with the plugin instead, what's the best way to remove Font Awesome from the child theme?
Is there a reason the theme uses Font Awesome 4.7.0 rather than the current version? How can I update it?

I would really appreciate your help!</div>

**Comment by bacoords** [comment]
@amillionmiles Let us know if we can close this issue since the discussion has been responded too.

**Comment by IanDelMar** [comment]
@bacoords No feedback from OP, I suggest to close this issue.
