### ISSUE TITLE
My footer menu is not displaying. I have added it following the tutorial on the understrap website but it still will not show and instead my main menu is being displayed instead.

### ISSUE THREAD

**Issue by DevOps-Peace** [understrap/understrap#2062]
**Describe the problem**
A clear and concise description of the problem.
My footer menu is not displaying. I have added it following the tutorial on the understrap website but it still will not show and instead my main menu is being displayed instead.
The version of Understrap that is being used is version 0.9.1
I am using a parent theme.

**Code**
In my setup.php file i used the code to add a footer menu.

 		register_nav_menus( array(
  			'primary' => __( 'Primary Menu', 'understrap' ),
  			'footer_menu' => __( 'Footer Menu', 'understrap'),
		) );

**Additional context**
I try to create a menu and customise it to include what i would like to have in the footer menu but the footer menu remains the same regardless despite it saying i have selected the right menu.

**Comment by Web-Assembler** [comment]
Hi @DevOps-Peace once you've created the new menu, assigned it to the Footer Menu location with the checkbox it won't do anything - you have to manually output it in the code or via a widget (Appearance > Widgets). 

Widget areas are already defined inside understrap and there is one called Footer Full. If you add a Navigation menu to that and select your new footer menu you should see the items appear.

If you wanted to change where the copyright information is output in the footer, to add your menu there you would add the following inside `footer.php`:

```php
<footer class="site-footer" id="colophon">

<?php
wp_nav_menu(
	array(
		'menu' => 'footer_menu',
	)
);
?>
```

**Comment by IanDelMar** [comment]
@DevOps-Peace would you mind changing the title of this issue to "footer menu is not displaying"? Is this still an issue after @Web-Assembler's guidance?

**Comment by IanDelMar** [comment]
@bacoords I think this issue can be closed due to lack of feedback.
