### ISSUE TITLE
theme.min.js doesn't contain edits from custom-javascript.js

### ISSUE THREAD

**Issue by Web-Assembler** [understrap/understrap#2064]
### The Bug
Any edits inside `src/js/custom-javascript.js` don't appear inside theme.min.js but they do appear in theme.js.

However, when I compile with SCRIPT_DEBUG on, (i.e. `theme.js`), the custom code is in there.

**What Works**
1. Download the latest understrap 
3. Run `npm install` in the theme.
4. Add this to `src/js/custom-javascript.js`: `console.log('Custom JS here');`
5. Add `define( 'SCRIPT_DEBUG', true );` to wp-config.php
6. The console.log appears in theme.js

**The problem**
1. Download the latest understrap 
3. Run `npm install` in the theme.
4. Add this to `src/js/custom-javascript.js`: `console.log('Custom JS here');`
5. Add `define( 'SCRIPT_DEBUG', false );` to wp-config.php
6. theme.min.js does not contain the 'Custom JS here' text.

### The Environment
- **WordPress Version:** 6.1.1
- **OS Version:** MacOS Monterey 12.5 (M1 Silicon)
- **Browser:** Chrome 108
- **Node.js & NPM Versions:** Node.js [V 16.16.0] | NPM [V 8.11.0]

**Comment by IanDelMar** [comment]
terser is set to drop calls to console methods. Removing the following line from terser.config.json will make terser keep `console.log()`.

https://github.com/understrap/understrap/blob/6a58dbbae4abb2ce4eaa1e315f0d5fe39e4acd50/src/build/terser.config.json#L7

**Comment by Web-Assembler** [comment]
Thanks for this.
