### ISSUE TITLE
Understrap theme removes padding on ACF Pro WYSIWYG and WP Classic Editor

### ISSUE THREAD

**Issue by hcanning** [understrap/understrap#2072]
WP 6.1.1
ACF Pro 6.0.7
Understrap 1.2.2

Not a major issue but I thought I'd flag it. If you create a WYSIWYG Field in ACF Pro or use WP Classic Editor the padding around the text is missing. If however you use the Twenty Twenty-One theme the padding is applied. Just for neatness I'm wondering how to apply the WYSIWIG padding in Understrap.
See attached pics of Understrap WYSIWYG display vs Twenty Twenty-One
https://ibb.co/kgxgQpL
https://ibb.co/wgLfky9
Thanks

**Comment by IanDelMar** [comment]
Maybe related to #2029.

**Comment by IanDelMar** [comment]
Try this:

```php
function slug_editor_body_margin_fix( $settings ) {
	if ( isset( $settings['content_style'] ) ) {
		$settings['content_style'] .= ' body#tinymce { margin: 9px 10px; }';
	} else {
		$settings['content_style'] = 'body#tinymce { margin: 9px 10px; }';
	}
	return $settings;
}
add_filter( 'tiny_mce_before_init', 'slug_editor_body_margin_fix' );
```

`margin: 9px 10px` is taken from the [TinyMCE WP skin](https://github.com/WordPress/WordPress/blob/15af7662df05a3e3b7b5818b05dde678c2bab708/wp-includes/js/tinymce/skins/wordpress/wp-content.css#L17). The `content_style` setting is documented here: https://www.tiny.cloud/docs/tinymce/6/add-css-options/#content_style
