### ISSUE TITLE
Feature Request: page meta descriptions

### ISSUE THREAD

**Issue by joshjalopy** [understrap/understrap#2074]
I'm considering using this theme/child theme however I don't see a way to add page meta descriptions, which is very important for SEO. I don't want to install a separate plugin for this functionality. Anyway to get this added to the theme?

**Comment by IanDelMar** [comment]
You could use the excerpt for the meta description.

```php
// Enable page excerpts.
add_post_type_support( 'page', 'excerpt' );

function slug_meta_description() {
	$description = '';

	if ( is_front_page() || is_home() ) {
		$description = get_bloginfo( 'description', 'display' );
	} elseif ( is_archive() ) {
		$description = get_the_archive_description();
	} else {
		$description = get_the_excerpt();
	}

	if ( ! empty( $description ) ) {
		echo '<meta name="description" content="' . wp_strip_all_tags($description) .  '" />';
	}
}
add_action( 'wp_head', 'slug_meta_description' );
```

**Comment by joshjalopy** [comment]
Good idea, but where do I enter the post excerpt? I don't see it when I enable the Understrap theme.

**Comment by pattonwebz** [comment]
> Good idea, but where do I enter the post excerpt? I don't see it when I enable the Understrap theme.

Should be in the sidebar of the editor on the post settings panel.

**Comment by joshjalopy** [comment]
Yes, I see it in posts but not pages. Anyway to enable this for pages?

**Comment by IanDelMar** [comment]
See the first line of code in my previous comment: `add_post_type_support( 'page', 'excerpt' );`

**Comment by IanDelMar** [comment]
@joshjalopy Did it work?

**Comment by joshjalopy** [comment]
Yes, but when I inspect the HTML it is adding '[...]Read More... from Quotes"' into the excerpt. Any idea how to remove that?

`<meta name="description" content="This is my gigantic quote page. [...]Read More... from Quotes">`

**Comment by IanDelMar** [comment]
This is added via `understrap_all_excerpts_get_more_link()` which is hooked to `wp_trim_excerpt`.

https://github.com/understrap/understrap/blob/546b350b62c22d384a563a9c0ad1b77f2331e046/inc/extras.php#L240-L252

Remove the filter and add it back right after getting the excerpt.

```php
function slug_meta_description() {
	$description = '';

	if ( is_front_page() || is_home() ) {
		$description = get_bloginfo( 'description', 'display' );
	} elseif ( is_archive() ) {
		$description = get_the_archive_description();
	} else {
		remove_filter( 'wp_trim_excerpt', 'understrap_all_excerpts_get_more_link' );
		$description = get_the_excerpt();
		add_filter( 'wp_trim_excerpt', 'understrap_all_excerpts_get_more_link' );
	}

	if ( ! empty( $description ) ) {
		echo '<meta name="description" content="' . wp_strip_all_tags( $description ) . '" />';
	}
}
add_action( 'wp_head', 'slug_meta_description' );
```
