### ISSUE TITLE
npm-run-all command not found on initial child theme setup 

### ISSUE THREAD

**Issue by bibliofille** [understrap/understrap#2086]
**Describe the problem**
I installed a fresh copy of Understrap and Understrap Child v 1.2.0 on my local machine. I'm using Local to spin up my local environment. I activated the child theme, navigated to the directory via command line, ran `npm install`. Then tried to run `npm run watch` and got the following: 
`understrap-child@1.2.0 watch
 npm-run-all --parallel watch-run-*
sh: npm-run-all: command not found`

**Debug Checklist**
Please include all of the following:
- [ ] The version of Understrap you're using (located in the package.json file) 
version": "1.2.0

- [ ] Whether you are developing with Understrap or the Understrap child theme 
Undersdtrap child theme
- [ ] The output of `node -v`
v16.3.0
- [ ] The output of `git --version`
git version 2.21.0 (Apple Git-122.2)
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by IanDelMar** [comment]
Maybe this is related to Local which I have no experience with. Others also seem to have problems with npm (see [NPM Install does not install all packages](https://community.localwp.com/t/npm-install-does-not-install-all-packages/34886)). Have you checked whether the package was actually installed? Have you tried to delete the node_modules folder and reinstall the dependencies or running `npm update`?

**Comment by bibliofille** [comment]
Turns out it was as simple as running `npm update`. Of course it was something simple. Thankfully, it's fixed and I'm up and running.

**Comment by IanDelMar** [comment]
Great!

cc @bacoords

**Comment by bacoords** [comment]
I've 100% had that issue in Local as well - I typically have to start a completely fresh terminal (not through Local) to install my packages. Glad this worked out!
