### ISSUE TITLE
no footer.php in blog posts

### ISSUE THREAD

**Issue by tele81** [understrap/understrap#2088]
hi in blog posts was no footer.php included is that correct?

**Comment by IanDelMar** [comment]
What do you mean by "blog posts" exactly?

**Comment by tele81** [comment]
ok it solved, the theme dost work correct in php 8x, just 7.4x works

**Comment by IanDelMar** [comment]
If you describe in more detail what the problem was, we can work on fixing the incompatibility with PHP 8. Unfortunately, I can't spot the issue locally.

**Comment by tele81** [comment]
The footer.php is not being included or displayed on pages and post articles, and comments are also not working on php8x.

**Comment by IanDelMar** [comment]
@bacoords I can't replicate this issue. Can you?

**Comment by bacoords** [comment]
No I haven't had any issues with php8. My assumption would be that it's an issue with either: 

1. A plugin - you can try disabling each plugin to see
2. Custom code - if you have any custom code in your templates, try running a copy of the theme without any custom code

**Comment by IanDelMar** [comment]
@bacoords I think this issue can be closed due to lack of feedback.
