### ISSUE TITLE
Positional and ":" arguments may not both be used

### ISSUE THREAD

**Issue by UnaOmnia** [understrap/understrap#2090]
So, I downloaded the child theme new. I didn't add any CSS or JS. I have been using Additional CSS in WordPress Customizer for CSS and I manually added a JS file in the footer.php and I have been editing template files - of course every file I edit I place in the child theme. Again, no edits to CSS or JS via SASS in /src/ etc - nothing. 

I downloaded my theme to back it up. I did "nvm use 16" to use node version 16 and whatever npm goes with it. Then I did npm install --no-audit to avoid any errors because last time I had minor dependency errors HOWEVER I was able to get the entire compile to work several times on another site with no issues what so ever. Maybe you pushed an update or something I am not sure.

But I do npm run watch and it only compiles the JS and CSS won't work. Again, not adding anything even npm run css-compile css-postcss css-minify doesn't work - same error:

Positional and ":" arguments may not both be used

It also said:

Usage: <input.scss>:<output.css> <input/>:<output/> <dir/>

These are from "dart" I believe.
But yeah my entire project is hung up on this now because I cannot change primary back to blue from purple etc.  

I am very sad.

I sort of don't even know where to begin because I was so delicate and because there is no custom CSS or JS added yet so that really narrows it down.

**Comment by IanDelMar** [comment]
Does the path contain spaces?

**Comment by IanDelMar** [comment]
@UnaOmnia Is there any news on this issue?

**Comment by UnaOmnia** [comment]
C:/Users/OMNIBON/Desktop/understrap-child-main/

**Comment by UnaOmnia** [comment]
But yeah I had thought of that...

**Comment by UnaOmnia** [comment]
Eventually it compile but I'm not sure how or why - I think it might be cuz one time I ran the watch or compile command AFTER removing the node module folder from the theme folder - cuz I was doing a sync folders command with winscp n it takes forever unless I remove the node module first... sometimes I forget to put it back before running cmd in admin and compiling but rarely... that is the only thing I can think of that caused it to work once - I'll have to keep testing when I have time soon but this isn't my main gig just a personal project...

**Comment by UnaOmnia** [comment]
I might work on it a bit today...

**Comment by IanDelMar** [comment]
Thank you! It would be great to know what the problem was for you, in case it happens to others too.

**Comment by UnaOmnia** [comment]
I did the following which was interesting:

1. download child theme to desktop
2. open cmd in admin and try npm run watch on my child theme folder - doesn't work
3. run npm install --no-audit and then npm run watch
4. leaving everything that was already there (that was having issues and worked on time for some reason or other) and adding a change to a scss file (utilities to make font size responsive / have breakpoints); and,
5. checking the site to see if my change was there (fs-md-1 fs-3 i.e. bigger font on bigger viewports with a class) and it was so that means the recompile worked and I didn't get the same error at least. 

The thing is that I still have to check if other commands than the nodemon npm run watch command work the same as well, like npm run css-minifiy etc - but I guess since I understand how to exit nodemon now (with respect to batch termination) then I sort of don't need those either. 

MAYBE You can mark it as resolved for now until I can replicate the issue - I will use the theme again in the future and see if that happens to me again the first time I go to compile.

**Comment by IanDelMar** [comment]
Thanks for the feedback!

cc @bacoords
