### ISSUE TITLE
Plugin Conflict?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap#2093]
I'm getting some errors which seem to indicate a conflict of some sort with **The Events Calendar plugin**.

I changed my theme to Twenty Twenty Three and Twenty Twenty-Two  to see if I still got the errors, but I did not get errors with either of these themes. When I switch back to Understrap or my Understrap Child themes, both themes produce the errors again, so I concluded it must be Understrap itself causing some kind of issue, but I don't know what it could be. 

Versions are Understrap 1.2.2 and Understrap Child 1.1.0.

**I'm seeing these 2 errors in the Inspector panel:**

```
Uncaught ReferenceError: tribe_js_config is not defined
    <anonymous> http://localhost:3000/3DSOFN/wp-content/plugins/the-events-calendar/src/resources/js/tribe-events.min.js?ver=5.0.0.1:1

Uncaught ReferenceError: tribe_js_config is not defined
    <anonymous> http://localhost:3000/3DSOFN/wp-content/plugins/the-events-calendar/src/resources/js/tribe-events-ajax-calendar.min.js?ver=5.0.0.1:1
```

I Googled "Understrap conflicting with plugins" to see if I could figure out how to fix it and saw there have been conflicts with plugins in the past such as **WPML** and **Polylang**, as stated in the [Understrap 1.2.0 release notes](https://understrap.com/blog/understrap-1-2-0-release/), so I now know that's a possibility and think I must be on the right track.  

I also something apparently similar happened with the **WooCommerce Authorize.Net Gateway plugin** [over on the Wordpress forums](https://wordpress.org/support/topic/understrap-conflicts-with-the-woocommerce-authorize-net-gateway-plugin/), but the Understrap team decided it wasn't caused by Understrap and closed the thread.

The reason I say my errors seem similar to this guy's is both are javascript errors caused by things that **things are not defined** for some reason only when Understrap is the active theme.

I saw some other instances of Understrap causing conflicts with plugins and the advice from the plugins author was to de-enqueue whichever Understrap scripts are causing the conflict, but I wouldn't even know where to begin. I can copy the javascript files that the errors point to if that helps.

**Comment by currentcreative** [comment]
From the first javascript, **tribe_js_config** comes at the beginning:
`var tribe_storage,t_fail,t_uid,tribe_ev=window.tribe_ev||{},tribe_debug=tribe_js_config.debug;...`


In the second javascript, it comes at the end:
`...(window,document,jQuery,tribe_ev.data,tribe_ev.events,tribe_ev.fn,tribe_ev.state,tribe_ev.tests,tribe_js_config,tribe_debug);`

Those are the only places in the scripts where tribe_js_config exists, so I didn't think it was sensible to paste the entire code.

Do you see anything here that would be conflicting with something in Understrap?

**Comment by IanDelMar** [comment]
Which version of the events calendar plugin do you use?

**Comment by currentcreative** [comment]
It's Version 4.4.24.2...which is outdated. Maybe the update will fix everything. Need the client to buy the license again. I'll report back if/when they do. There was some talk about possibly getting rid of it, anyway. I just thought I'd try to be a genius and fix it if I could learn how/why it happens and how to fix it. I never had a plugin conflict with a theme before, so it kinda threw me for a loop and I'd love to know what steps people take to resolve such things.

**Comment by IanDelMar** [comment]
So you use the Pro version? Have you already tried to disable the Pro version?

**Comment by currentcreative** [comment]
Yes, the pro version is running on their site. I have not tried to disable it since I probably won't be able to activate it again once I do now that the license is expired. You think that's the cause of the whole problem? Just an unrenewed license?

**Comment by IanDelMar** [comment]
No, I'm just trying to narrow down the cause of the issue. But this `http://localhost:3000/3DSOFN/wp-content/plugins/the-events-calendar/src/resources/js/tribe-events.min.js?ver=5.0.0.1:1` is your local install and it's version 5.0.0, right?

**Comment by IanDelMar** [comment]
I can't reproduce the errors using Understrap in its current version, the events calendar 5.16.4 (free version) and WP 6.1.1.

**Comment by currentcreative** [comment]
Good lord, you just helped me notice they have BOTH the free and pro versions installed and activated. I guess the pro version depends on the free version.

I deactivated the pro version like you said and the error went away...but so did the calendar.
So now I'm going to try to rollback the free version and see what happens.

This is definitely NOT an Understrap error, I see. Still seems weird that the error did not produce on the Wordpress default themes, but maybe error reporting is just suppressed (or worse?) on those themes.

Thank you for helping me figure this out.

**Comment by pattonwebz** [comment]
@currentcreative I am just curious if you are running on PHP 8 or not?

**Comment by IanDelMar** [comment]
@pattonwebz I am and there is no such error.

**Comment by IanDelMar** [comment]
> I guess the pro version depends on the free version.

Yes, the pro version is like an add on.

> I deactivated the pro version like you said and the error went away...but so did the calendar.

I don't think that this should happen unless you are using a pro shortcode to display the calendar or a pro view.

> This is definitely NOT an Understrap error

That's what I think.

@currentcreative As far as I remember the pro version must be in sync with the core plugin. If the pro version is at v4.something and the core plugin is at v5.something this can also be an issue.

**Comment by currentcreative** [comment]
Makes sense. Thank you.
