### ISSUE TITLE
unable to edit gravity form in child theme

### ISSUE THREAD

**Issue by bclaw7** [understrap/understrap#2104]
**Describe the problem**
When understrap child theme is active I am unable to edit all gravity forms. None of the buttons are clickable. Cannot scroll the module section. Cannot drag and drop.

**Debug Checklist**
Please include all of the following:
- [ 1.1.0 ] The version of Understrap you're using (located in the package.json file)
- [ understrap child theme ] Whether you are developing with Understrap or the Understrap child theme
- [ 16.14.2 ] The output of `node -v`
- [ 2.38.1 ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by IanDelMar** [comment]
I have no experience with the plugin and no access to it.

* Do you work in a local development environment?
* Does the problem also occur when you use the parent theme?
* Does the problem also occur when you use a different theme?
* Are any errors displayed in the console?
* Are gravity forms edited on the backend or the frontend?

**Comment by bclaw7** [comment]
Yes, I work in local environment
No the problem doesn't occur in parent theme
No errors in console
gravity forms are edited in backend.

thank you for your help. I'll continue troubleshooting as well.

**Comment by IanDelMar** [comment]
Does your child theme load JS in the backend? If so, what exactly is loaded?

**Comment by bclaw7** [comment]
Looks like it's loading jquery

Here is the error when clicking on a form to edit: 

GET https://schlagel.local/wp-admin/admin.php?page=gf_edit_forms&id=8 500

**Comment by IanDelMar** [comment]
It's hard to tell what's going on without knowing what your child theme is doing. If this does not happen when using the parent theme it must be related to your child theme. An internal server error looks more like a PHP problem. Which PHP version do you use? You can try to install the [Query Monitor](wordpress.org/plugins/query-monitor/) plugin and see if that gives more details to narrow down the cause of the issue.

**Comment by bclaw7** [comment]
I have been using query monitor. It doesn't show anything when gravity forms editor is open.

**Comment by bclaw7** [comment]
I solved this issue by uploading a new copy of understrap-child-main theme and adding custom functions, scss, and js. Thank you for your help on this.
