### ISSUE TITLE
How would I install aos.js properly?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap#2105]
I found this thread about Scroll Magic, which someone has jumped in and asked about AOS, but it's from 2019 and he could never get it working: https://github.com/understrap/understrap/issues/772 Things have changed since then, anyway. 

So this is aos.js:
https://github.com/michalsnik/aos and it looks like everthing I need is in the 'src' folder.

I see that I probably need to add the file paths to rollup.config.js and copy-assets.js, but I really don't know how or where to put the sass and js. If there is an npm installer for aos.js, I don't know how it works overall with Understrap.

To be clear, I want to install this in my Understrap Child theme.

**Comment by IanDelMar** [comment]
Do you want to put the JS and CSS into the corresponding theme files or load them separately as aos.css and aos.js? Do you plan to customize AOS CSS? Which child theme version do you use?

If you want to put it into child-theme.js and child-theme.css without customization do the following
1. Install package by running `npm install aos@next --save-dev`
1. Add the script below to your [custom-javascript.js](https://github.com/understrap/understrap-child/blob/main/src/js/custom-javascript.js) and see https://github.com/michalsnik/aos#1-initialize-aos for available options. 
1. Add `@import "aos/src/sass/aos"` to your [child-theme.scss](https://github.com/understrap/understrap-child/blob/main/src/sass/child-theme.scss) and add `--load-path=\"node_modules/\"` to the `css-compile` script in your [package.json](https://github.com/understrap/understrap-child/blob/main/package.json#L9) 
 
Add to custom-javascript.js:
```js
import AOS from 'aos';
AOS.init();
```

**Comment by currentcreative** [comment]
I don't plan to customize anything, I just want to access the library and its scss and js. I saw that the js references the scss in a different folder, so I was not sure what is the correct way to install it so that everything builds properly with `npm run dist-build`. For a second, I thought maybe I would just enqueue the js and scss in functions.php since Understrap has so much stuff going on I really don't understand the file paths to everything, but that wouldn't probably wouldn't build correctly.

Ok, I will try what you said. Thank you. I'll report back after.

**Comment by currentcreative** [comment]
It worked! Thank you. I wish I understood how Understrap knows where to grab everything from and all the paths remain in tact. It's just magic to me at this point.

I just guessed where to put that little bit of code in the css-compile script (at the end) and it totally works, so I guess I guessed correctly. This is how it looks in package.json:

`  "css-compile": "sass --style expanded --source-map --embed-sources --no-error-css --quiet src/sass/child-theme.scss:css/child-theme.css src/sass/custom-editor-style.scss:css/custom-editor-style.css --load-path=\"node_modules/\"",`

**Comment by IanDelMar** [comment]
> For a second, I thought maybe I would just enqueue the js and scss in functions.php

That's possible as well. But if you want to enqueue the assets separately you'll need another approach.

> I just guessed where to put that little bit of code in the css-compile script (at the end) and it totally works

You can put it anywhere after "sass".

> Will --save-dev keep aos.js in the final build

Yes, the aos stuff will be compiled into child-theme.css and child-theme.css. That's what the additions in the theme.scss, the css-compile script and the custom-javascript.js are for.

> I wish I understood how Understrap knows where to grab everything

I'm afraid you have to dig into node, sass and rollup. Understrap doesn't do anything that is not standard within these environments. But I understand that it can be confusing when you start developing using these tools.

**Comment by currentcreative** [comment]
> > I'm afraid you have to dig into node, sass and rollup. Understrap doesn't do anything that is not standard within these environments. But I understand that it can be confusing when you start developing using these tools.

That makes sense—everyone follows conventions. I was totally expecting to have to add it to Understrap itself and add the aos.js file to rollup.config.js file. I can see the geniuses behind all this have made it easier to add functionality than I thought it would be, while keeping everything separated.
