### ISSUE TITLE
Shifting layout. corporate premium child theme v1.1.0

### ISSUE THREAD

**Issue by rockyplanet** [understrap/understrap#2109]
**Describe the problem**
I have a layout shift problem. I am using the corporate: understrap premium child theme v.1.1.0.
When I open the site using an iphone in any browser, the home page shifts left or right when I press on the page and move my finger to left or right. Then using the chrome app, the page is pushed up against the left side with a gap of white space on the right. I have tried changing the theme layout settings in the customizer to full or fixed width and no change. I switched to the understrap parent theme and I still have the problem. Should I delete the themes and then reinstall?

I found one other thread about a layout shift problem, but the discussion was closed and there was not a solution.

I use other v1.1.0 child themes  (blog and portfolio) on other websites with the same plugins and I don't have this problem

I don't consider myself a developer

**Debug Checklist**
Please include all of the following:
- [X] "name": "understrap-child-corporate", "version": "1.1.0",
- [ ] Whether you are developing with Understrap or the Understrap child theme
- [ ] The output of `node -v`
- [ ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by rockyplanet** [comment]
I looked at this one more time and realized that the name of the site in the header was too long and pushed the margin out to the right. I shortened the name and everything is working perfectly. I am guessing that there's nothing that can be done about this. So, I will simply close it up here.

**Comment by IanDelMar** [comment]
@rockyplanet `white-space` is set to `nowrap` for `.navbar-brand`. You can set it to `normal` and then play around with `word-wrap` or `word-break`.
