### ISSUE TITLE
Please provide a short summary of the problem (approx. 50 characters)

### ISSUE THREAD

**Issue by gridddesign** [understrap/understrap#2112]
We are using your Understrap (v 1.2.2) and the  Child Theme (v 0.5.2).  There are Woocoomerce files in your theme that are out of date. here is the list....

understrap/woocommerce/cart/cart-empty.php,
understrap-child/woocommerce/cart/cart.php version 3.8.0 is out of date. The core version is 7.8.0,
understrap-child/woocommerce/cart/mini-cart.php version 3.7.0 is out of date. The core version is 7.8.0,
understrap/woocommerce/cart/proceed-to-checkout-button.php,
understrap/woocommerce/checkout/form-checkout.php,
understrap/woocommerce/checkout/form-coupon.php,
understrap/woocommerce/checkout/form-pay.php version 7.0.1 is out of date. The core version is 7.8.0,
understrap/woocommerce/checkout/payment.php version 7.0.1 is out of date. The core version is 7.8.0,
understrap/woocommerce/global/form-login.php,
understrap-child/woocommerce/global/quantity-input.php version 4.0.0 is out of date. The core version is 7.8.0,
understrap/woocommerce/loop/orderby.php,
understrap/woocommerce/myaccount/downloads.php version 3.2.0 is out of date. The core version is 7.8.0,
understrap/woocommerce/myaccount/form-edit-account.php,
understrap/woocommerce/myaccount/form-edit-address.php,
understrap/woocommerce/myaccount/form-login.php,
understrap/woocommerce/myaccount/form-lost-password.php,
understrap/woocommerce/myaccount/form-reset-password.php,
understrap/woocommerce/myaccount/my-address.php,
understrap/woocommerce/myaccount/my-orders.php,
understrap/woocommerce/myaccount/navigation.php,
understrap-child/woocommerce/myaccount/orders.php version 3.7.0 is out of date. The core version is 7.8.0,
understrap/woocommerce/product-searchform.php,
understrap/woocommerce/single-product/add-to-cart/simple.php,
understrap/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php

Can these be updated?  Is there a newer version of the theme?

Thanks!

**Comment by IanDelMar** [comment]
I'll have a look at the templates this week and will open an PR updating the outdated templates. @bacoords will there be an update of the theme in the near future?

**Comment by IanDelMar** [comment]
@bacoords Maybe we can start by merging stuff into the develop branch. So we can spot and resolve merge conflicts.

**Comment by IanDelMar** [comment]
> @IanDelMar Yes, I think it's about time for a release. I don't know that it'll include everything in https://github.com/understrap/understrap/milestone/9 but definitely the WooCommerce fixes and Bootstrap/dependency updates, and maybe some of the tinymce/block editor stuff.

@bacoords Any news?

**Comment by bacoords** [comment]
@IanDelMar I've opened a new discussion so we could talk about the next release: https://github.com/understrap/understrap/discussions/2120
