### ISSUE TITLE
Theme contains outdated copies of Woocommerce template files

### ISSUE THREAD

**Issue by daveiho** [understrap/understrap#2115]
Hi,

With the latest update of Woocommerce, a warning appears on the top saying:

> Your theme (Inner Journey) contains outdated copies of some WooCommerce template files. These files may need updating to ensure they are compatible with the current version of WooCommerce. Suggestions to fix this:

- Update your theme to the latest version. If no update is available contact your theme author asking about compatibility with the current WooCommerce version.

- If you copied over a template file to change something, then you will need to copy the new version of the template and apply your changes again.  > 

You can see the in the screenshots below the warning and the affected templates + here the link to woocommerce instructions: https://woocommerce.com/document/template-structure/

My question is, should I follow their instructions and do it myself or are you planning to update the theme so that this is solved already?

**Debug Checklist**
Please include all of the following:
- [ 1.2.2 ] 
- [ Understrap child theme ]

**Screenshots / Videos**
<img width="1129" alt="Screenshot 2023-07-11 at 00 20 38" src="https://github.com/understrap/understrap/assets/32480112/ee6a6f76-5fc1-416a-9e1d-d2fa1bdfb7fd">
<img width="1231" alt="Screenshot 2023-07-11 at 00 21 10" src="https://github.com/understrap/understrap/assets/32480112/15e12df8-93bf-4998-8d68-9356d979d30f">

Thanks.

**Comment by IanDelMar** [comment]
We are working on this.

#2112

**Comment by daveiho** [comment]
Ok great!

Thanks.

**Comment by IanDelMar** [comment]
@bacoords needs label "woocommerce"

**Comment by PatH007** [comment]
Hi there.
Same problem with WooCommerce.
My question is: we must not update woocommerce so far, right?
What is the lats Woocommerce version that works with 1.2.2 version of parent theme?
Thanks.

**Comment by bacoords** [comment]
Closing this issue as the WooCommerce template files are updated as of [1.2.3 ](https://github.com/understrap/understrap/releases/tag/v.1.2.3)
