### ISSUE TITLE
I can't figure out a way to make tagline appear in the header area.

### ISSUE THREAD

**Issue by shivanshvermak** [understrap/understrap#2116]
Using Understrap Child theme 1.2.0 with Understrap 1.2.2.
URL: shivanshverma.ml

I can't figure out a way to make tagline appear in the header area. Does an option like this exist? I've "Ikr, barebones" set as tagline, which appears in title but not in header. 

I want the header to be something like this:
<img width="245" alt="image" src="https://github.com/understrap/understrap/assets/15206857/57bf021f-fadf-483d-b976-c8190717f198">
Instead of how it is as of now. I know CSS, and have some experience with development, if it can be added manually, can you provide instructions? I don't know the structure and where the underlying code header section is.

**Comment by IanDelMar** [comment]
In global-templates/navbar-branding.php you can do
```diff

+echo '<div class="branding">';

if ( ! has_custom_logo() ) { ?>

	<?php if ( is_front_page() && is_home() ) : ?>

		<h1 class="navbar-brand mb-0">
			<a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" itemprop="url">
				<?php bloginfo( 'name' ); ?>
			</a>
		</h1>

	<?php else : ?>

		<a class="navbar-brand" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" itemprop="url">
			<?php bloginfo( 'name' ); ?>
		</a>

	<?php endif; ?>
+
+	<span class="tagline"><?php echo get_bloginfo( 'description' ); ?></span>

	<?php
} else {
	the_custom_logo();
}
+echo '</div>';

```

**Comment by shivanshvermak** [comment]
Thank you so much! That did it!
