### ISSUE TITLE
RollupError: Unexpected character '@' 

### ISSUE THREAD

**Issue by garryknapper** [understrap/understrap#2119]
Hi,

I'm using the Understrap child theme and the Swiper node module on my site. When I try and import the swiper stylesheets using **import 'swiper/css'** in the custom-javascript.js file, I get the following build error: RollupError: Unexpected character '@'.

I've looked into what the problem may be and it appears that the Rollup file doesn't bundle css files, only js files. I understand that a Rollup plugin might be required such as rollup-plugin-postcss. Could you suggest a way please how I could bundle the css with the other stylesheets in the theme? I attempted to do this by adding the following to the rollup.config.js file but, although there were no error messages, it didn't pull the css into the front-end of the site:

const postcss = require ('rollup-plugin-postcss');

plugins: [
  postcss({
    extract: true, // Extract CSS to a separate file
    minimize: true, // Minify CSS
  }),
],

Any help is greatly appreciated. Thank you.

**Comment by garryknapper** [comment]
Yes, that works absolutely fine, thank you. That's a better and simpler solution than the one I tried to implement using rollup-plugin-postcss. Thanks again for your help, much appreciated.

**Comment by IanDelMar** [comment]
You're welcome. Can the issue be closed then?
