### ISSUE TITLE
The style.min.css file is not being linked to the page

### ISSUE THREAD

**Issue by olegtymo** [understrap/understrap#2156]
I`d like to apologize for what might be a fool question, but I really don`t know how to fix it. So, the issue is that I don't see changes after entering them into the theme.scss file. The code from theme.scss compiles into the style.min.css, but it is not being linked to the page. What am I doing wrong?

The steps I took:
1. Downloaded understrap-1.2.2.zip.
2. Unpacked to OSPanel/domains/fashion/wp-content/themes/understrap
3. 'npm install' in IDE 
4. 'npm run watch-bs'

What I got:
![image](https://github.com/understrap/understrap/assets/106606887/ab822c1a-aa87-4124-9ef7-8a4c82b23d07)
![image](https://github.com/understrap/understrap/assets/106606887/420478ac-f47a-4f97-be6d-e855702a88d4)

**Comment by Heet-Talati** [comment]
Hey there, I was having the same issue and after trying to compile everything manually I spotted that it requires the <code>css</code> as well as  <code>css-bs4</code> script to show the changes.

Here is the updated version of the script that i changed in <code>package.json</code> file:
<code>"watch-run-css": "nodemon --watch src/sass/ --ext scss --exec \"npm-run-all css css-bs4\""</code>

Just add <code>css-bs4</code> in the end and then it should work.

**Comment by olegtymo** [comment]
@Heet-Talati , your guidance so useful, it really helped me, thanks a lot!

**Comment by IanDelMar** [comment]
@olegtymo That means you're using Bootstrap 4, right?
