### ISSUE TITLE
wordpress navbar toggle not working after log out

### ISSUE THREAD

**Issue by rahulshakya1212** [understrap/understrap#2172]
**Describe the problem**
A clear and concise description of the problem.

**Debug Checklist**
Please include all of the following:
- [ ] The version of Understrap you're using (located in the package.json file)
- [ ] Whether you are developing with Understrap or the Understrap child theme
- [ ] The output of `node -v`
- [ ] The output of `git --version`
- [ ] The output of `gulp -v` (if using an Understrap version below 1.0.0)

**Screenshots / Videos**
If applicable, add screenshots/videos to help explain your problem.

**Code**
If applicable, provide code to help explain your problem.

**Additional context**
Add any other context about the problem here (e.g. related issues).

**Comment by IanDelMar** [comment]
Could you please explain the issue in more detail and at least provide the version of Understrap you are using? Are you using a child theme? Have you made any customization to the theme?

**Comment by rahulshakya1212** [comment]
Hi Sir,
Our website is jobalertsps.in

**Comment by IanDelMar** [comment]
Could you then please close the issue? Thank you!
