### ISSUE TITLE
Accessing Bootstrap javascript constructors

### ISSUE THREAD

**Issue by alexatlevel** [understrap/understrap#2178]
### The Bug

**Describe the bug**
I am having trouble accessing Bootstrap js modules. For example, when trying to initialize a carousel, I add:

<script>
	window.addEventListener('DOMContentLoaded', function(event){
		const testimonialCarousel = document.querySelector('#testimonial-carousel')
		const carousel = new bootstrap.Carousel(testimonialCarousel, {
			ride: 'carousel',
			pause: 'hover',
			interval: 5000
		})
	});
</script>

As the [documentation](https://getbootstrap.com/docs/5.3/components/carousel/#how-it-works) states "For performance reasons, carousels must be manually initialized using the carousel constructor method. Without initialization, some of the event listeners (specifically, the events needed touch/swipe support) will not be registered until a user has explicitly activated a control or indicator."

However, when I add the script above as instructed by Bootstrap documentation, I get the console error "Uncaught ReferenceError: bootstrap is not defined at xxx" where xxx points to new bootstrap.Carousel(). 

The only way I can get this to work is to add this to custom-javascript.js and re-complie:
window.bootstrap = require('bootstrap/dist/js/bootstrap.bundle.js');

But doesn't this defeat the purpose of Understrap fully loading all necessary Bootstrap javascript?

Am I missing something in calling Bootstrap javascript modules / constructors?

**To Reproduce**
1. Try to initialize or call a Bootstrap javascript module / constructor using the stock setup

**Expected behavior**
Would be able to call Bootstrap javascript module / constructors using the stock setup

### The Environment

- **WordPress Version:** 6.4.2
- **Node.js & NPM Versions:** Node.js 20.6.1 NPM 10.2.5

### Additional context
I'm actually using the Understrap child theme but the setup is the same.

**Comment by alexatlevel** [comment]
Here's some more discussion on a similar issue: https://stackoverflow.com/questions/64113404/bootstrap-5-referenceerror-bootstrap-is-not-defined

The parent Understrap theme calls the module like `export { default as Carousel } from 'bootstrap/js/src/carousel';` and the child Understrap-Child theme does it like `import Carousel from 'bootstrap/js/dist/carousel` then `export {Carousel}`

Given that, I tried:

```
    let testimonialCarousel = new bootstrap.Carousel(document.getElementById('#testimonial-carousel'));
    testimonialCarousel.show();
```

But then get "Uncaught ReferenceError: Carousel is not defined"

So how do we call Bootstrap modules?

**Comment by IanDelMar** [comment]
Is
```js
let testimonialCarousel = new bootstrap.Carousel(document.getElementById('#testimonial-carousel'));
testimonialCarousel.show();
```
a separate script or is it bundled in theme.js?

**Comment by alexatlevel** [comment]
It's in a stand alone script on the page, like the Bootstrap documentation
instructs.

**Comment by IanDelMar** [comment]
Then using `let testimonialCarousel = new understrap.Carousel(document.getElementById('#testimonial-carousel'));` instead will most likely solve the problem.

The name of the bundle is set in rollup.config.js https://github.com/understrap/understrap/blob/1a9b9afbb0dc0c6902a0277e3601584752a387f3/src/build/rollup.config.js#L76
So it might be different from "understrap" in a child theme.

**Comment by alexatlevel** [comment]
Thanks @IanDelMar and great to see your name here. That did the trick. Is this a normal / expected way to call a module wrapped up in an application like this? I ask because this flummoxed two developers for a week. Maybe we're just not that experienced, but this seems like an unexpected way of calling a packaged module.

-Alex

**Comment by IanDelMar** [comment]
Great it works!

>great to see your name here

It took me a while to figure out what this was about 😄 I didn't recognise you at first.
>Is this a normal / expected way to call a module wrapped up in an application like this?

I guess it depends on your typical use cases. This might make sense if you think of Understrap as a starter theme. Then, often, the bundle's name is irrelevant. You import the Carousel component into your js-file and use `new Carousel()` instead of `new bundleName.Carousel()`. And if you split the script into different files, you usually know the bundle's name.
If you think of Understrap as a parent theme that has to provide all of Bootstrap's JS, it would probably be best to ship the pre-built Bootstrap dist files. I have never used it as a parent theme.

**Comment by IanDelMar** [comment]
Related: #1583

**Comment by bacoords** [comment]
Closing this now that we've added a note to the docs about this. Feel free to reopen if there's anything I missed

**Comment by alexatlevel** [comment]
Thanks @bacoords 

We're still struggling with this. It seems so unnecessarily complicated!

We're now trying to initialize and show toasts.

If we add this to the footer, it works fine:

```
<script>
const sessionToastEl = document.getElementById('session-toast');
if (sessionToastEl) {
  const sessionToast = new understrap.Toast(sessionToastEl);
  sessionToast.show()
}
</script>
```

But if we add the same thing to custom-javascript.js and compile (which is what I thought was the intended workflow), it says "understrap is not defined".

Am I missing something? Why is this so complicated? Can we just call bootstrap constructors the regular way?

Thanks!

**Comment by alexatlevel** [comment]
Okay after looking more closely at [1583](https://github.com/understrap/understrap/issues/1583#issuecomment-1022444176) I have made this work in custom-javascript.js

```
import Toast from 'bootstrap/js/dist/toast'

const sessionToastEl = document.getElementById('session-toast');
if (sessionToastEl) {
  const sessionToast = new Toast(sessionToastEl);
  sessionToast.show()
}
```

Thanks for more carefully noting this. It all does seem quite confusing. I wish the process were more clear. Anywhoo, I'm not one to do the work of making it more clear, so I shouldn't complain!

-Alex

**Comment by IanDelMar** [comment]
> We're still struggling with this. It seems so unnecessarily complicated!

Sorry to hear that. Are you using a custom set of Bootstrap JS components? If not, perhaps using Bootstrap as is is an option? If so, one option would be to compile the Bootstrap source files separately and name the bundle "bootstrap". Either way would ensure that you can use Bootstrap as described in the Bootstrap documentation. Let me know if you need help setting up the build process for any of these options.
