### ISSUE TITLE
Can we customize understrap_post_nav(); so it only gets prev/next from a specific category?

### ISSUE THREAD

**Issue by currentcreative** [understrap/understrap#2181]
I'm in a custom single-member.php template and when I get to the last member on the list, I don't want understrap_post_nav(); to be linking to Meetings or some other category. I'd rather it just not have a "next" link on the last post. Same goes for the first post (no "previous" link that takes me to Events)

**Comment by currentcreative** [comment]
Maybe it shouldn't be doing this, but it is. I even reverted to standard archive.php and single.php templates with nothing in functions.php that would screw it up. I flushed permalinks. The previous and next post links of understrap_post_nav(); are just going through ALL my posts according to date and completely disregarding the category.

**Comment by pattonwebz** [comment]
@currentcreative are you saying that the nav is moving you between POST TYPES and not just moving you through categories?

**Comment by pattonwebz** [comment]
If you want to limit it to NOT move between categories, since the function is plugable, you can  redefine the function in a child theme with `true` passed to the `get_adjacent_post` function like this:

```
	function understrap_post_nav() {
		global $post;
		if ( ! $post ) {
			return;
		}

		// Don't print empty markup if there's nowhere to navigate.
		$previous = ( is_attachment() ) ? get_post( $post->post_parent ) : get_adjacent_post( true, '', true );
		$next     = get_adjacent_post( true, '', false );
		if ( ! $next && ! $previous ) {
			return;
		}
		?>
		<nav class="container navigation post-navigation">
			<h2 class="screen-reader-text"><?php esc_html_e( 'Post navigation', 'understrap' ); ?></h2>
			<div class="d-flex nav-links justify-content-between">
				<?php
				if ( get_previous_post_link() ) {
					previous_post_link( '<span class="nav-previous">%link</span>', _x( '<i class="fa fa-angle-left"></i>&nbsp;%title', 'Previous post link', 'understrap' ) );
				}
				if ( get_next_post_link() ) {
					next_post_link( '<span class="nav-next">%link</span>', _x( '%title&nbsp;<i class="fa fa-angle-right"></i>', 'Next post link', 'understrap' ) );
				}
				?>
			</div><!-- .nav-links -->
		</nav><!-- .post-navigation -->
		<?php
	}
```

**Comment by currentcreative** [comment]
Thank you. That just goes in functions.php somehow?

**Comment by pattonwebz** [comment]
Yep, just put it somewhere early in the functions.php file (it needs to be added before the actual theme would add this function itself, hence the suggestion to place it early), and it should work.

**Comment by currentcreative** [comment]
This did not work. I also tried to stick it in single.php in place of where `understrap_post_nav();` was originally. Neither worked.

**Comment by pattonwebz** [comment]
Having it added early in functions.php should have worked. Can you confirm for me if `members` `events` and `meetings` are categories on your site or if they are custom post types?

Also are you using a customized version of this theme that you edit directly or are you using a child theme?

**Comment by currentcreative** [comment]
They're just categories, although I just added a Members custom post type to try to figure out a different solution, but I have only created 1 post with it and have not used it anywhere in the templates.

**Comment by currentcreative** [comment]
It's been a really rough day trying to debug this. If you gave me pretty much everything except the add_action or add_filter part of it, could you just recommend me an example of where you think it would be early enough.

**Comment by pattonwebz** [comment]
Paste all the code I shared right here: https://github.com/understrap/understrap/blob/main/functions.php#L41

There is no need for any add_action or add_filter calls around it. Just paste the entire function definition.

Let me know if that works or not.

**Comment by currentcreative** [comment]
I'm in a child theme. I initially just posted it right at the top under `defined( 'ABSPATH' ) || exit;` with no `add_action` and it did nothing.

**Comment by pattonwebz** [comment]
Sorry I think I had a mistake in my suggested code. I just edited it and I think it's working now, if you could copy the code from this post again: https://github.com/understrap/understrap/issues/2181#issuecomment-1967923951 and retry it I expect it will work for you now.

**Comment by pattonwebz** [comment]
I can see the edit history on the comment and see the 4 lines that I changed in the latest edit. I'll paste the updated code below though as well just incase something quirky is going on with the editing.


``` php
	function understrap_post_nav() {
		global $post;
		if ( ! $post ) {
			return;
		}

		// Don't print empty markup if there's nowhere to navigate.
		$previous = ( is_attachment() ) ? get_post( $post->post_parent ) : get_adjacent_post( true, '', true );
		$next     = get_adjacent_post( true, '', false );
		if ( ! $next && ! $previous ) {
			return;
		}
		?>
		<nav class="container navigation post-navigation">
			<h2 class="screen-reader-text"><?php esc_html_e( 'Post navigation', 'understrap' ); ?></h2>
			<div class="d-flex nav-links justify-content-between">
				<?php
				if ( get_previous_post_link(null, null, true) ) {
					previous_post_link( '<span class="nav-previous">%link</span>', _x( '<i class="fa fa-angle-left"></i>&nbsp;%title', 'Previous post link', 'understrap' ), true );
				}
				if ( get_next_post_link(null, null, true) ) {
					next_post_link( '<span class="nav-next">%link</span>', _x
					( '%title&nbsp;<i class="fa fa-angle-right"></i>', 'Next post link', 'understrap' ), true );
				}
				?>
			</div><!-- .nav-links -->
		</nav><!-- .post-navigation -->
		<?php
	}
```

**Comment by currentcreative** [comment]
So you know what the code is doing, it's completely removing the prev/next post navigation. There are 10 posts in the members category, but your code seems to be determining that there are no other posts and so it just hides the nav.

**Comment by currentcreative** [comment]
I was finally able to find where I solved this problem in my last Understrap site. I copied inc/template-tags.php into my child folder and made some changes. Absolutely insane. I have no idea how I figured that out last fall and forgot all about it. I don't even understand how I figured it out, frankly.

**Comment by currentcreative** [comment]
### The solution:

Copy **template-tags.php** from understrap/inc into your understrap child inc folder.

Add `true` to the end of the `get_previous_post_link()` and `get_next_post_link()` functions like this:

```
<?php
if ( get_previous_post_link() ) {
   previous_post_link( '<span class="nav-previous">%link</span>', _x( '<i class="fa fa-angle-left"></i>&nbsp;%title', 'Previous post link', 'understrap', true ) );/* , true  = adds true for argument $in_same_term (default term is 'category').  - https://developer.wordpress.org/reference/functions/previous_post_link/ */
}

`if ( get_next_post_link() ) {
    next_post_link( '<span class="nav-next">%link</span>', _x( '%title&nbsp;<i class="fa fa-angle-right"></i>', 'Next post link', 'understrap' ), true ); /* , true  = adds true for argument $in_same_term (default term is 'category').  - https://developer.wordpress.org/reference/functions/previous_post_link/ */
?>
```

That is the boolean $in_same_term parameter. [Documentation here](https://developer.wordpress.org/reference/functions/get_previous_post_link/).


### Hot tip to myself in the future:
When trying to wrangle Understrap's custom functions, open the Understrap parent theme (not child) in VS Code and search the whole folder for the function in question. From there, you can try to break down what it's doing. In this case, **understrap_post_nav()** only appears in 2 files (**single.php** and **inc/template-tags.php**) so it was pretty easy to track down. And it was pretty easy to understand. It's just using the Wordpress functions `get_next_post_link()` and `get_previous_post_link()`.

**Comment by currentcreative** [comment]
Although this is not working on an old Divi site I am converting. I think Divi just screwed stuff up badly because it works on 2 other sites I've tested.
