### ISSUE TITLE
Release 1.2.4 Tracking Issue

### ISSUE THREAD

**Issue by bacoords** [understrap/understrap#2191]
This is a general tracking issue for a 1.2.4 release, the main goal is to get the latest WooCommerce templates out the door. Happy to include anything else that's not a major breaking change (the 1.3 milestone)

Here's my list for inclusion but if you see anything else worth adding, please comment below

- [x] #2189 
- [x] #2190 
- [x] Updating dependencies
- [x] #2089 
- [x] #2002

**Comment by bacoords** [comment]
This release is now available on GitHub - I'll wait until next week (April 1 2024) to publish on the WordPress.org theme directory.


https://github.com/understrap/understrap/releases/tag/v.1.2.4

**Comment by axi** [comment]
Thanks @bacoords , does this explain why I'm not seiing 1.2.4 version using `wpackagist-theme/understrap` ?

**Comment by bacoords** [comment]
I believe so. 1.2.4 should appear in the theme directory in the next day or so.

**Comment by axi** [comment]
Tag 1.2.4 appeared when I pressed the refresh button, and it's now available. 
https://wpackagist.org/search?q=understrap
Thanks

![image](https://github.com/understrap/understrap/assets/389340/c60ee968-5cc4-400b-8165-e3c52223c872)
