### ISSUE TITLE
Woocommerce text strings problem

### ISSUE THREAD

**Issue by Alandette** [understrap/understrap#242]
Hi there

Some text strings do not translate correctly to Spanish and remain in the original language, the error is corrected if the graphic theme is changed.

One of the text strings that are not translated are:
"Your cart is currently empty" on the Cart page
"Login and Register" on the My Account page

I currently use
Woocomerce 2.6.13
UnderStrap 0.5.4
UnderStrap Child 0.2.0

Thank you

**Comment by stef-k** [comment]
Hi, could you please provide the English and Spanish translations in a PR? If not at least post them here and hopefully a contributor with free time will add them.

Thanks.

**Comment by holger1411** [comment]
@Alandette Any help is appreciated. I don´t speak spanish by myself.
Here are the language files: https://github.com/holger1411/understrap/tree/master/languages

**Comment by navasclavero** [comment]
On several occasions I have proposed translations into Spanish, but the file is not modified :(

**Comment by Thomas-A-Reinert** [comment]
Can´t replicate. To my knowledge the latest spanish files are already merged.
