### ISSUE TITLE
Responsive not working on iPad

### ISSUE THREAD

**Issue by deeblake** [understrap/understrap#280]
I've used Understrap for a client site once before, and all media queries worked properly.

However, I'm using the latest Understrap and have found that media queries are not working properly on iPad--columns do not fill out the width of the container. This is even happening on the Understrap demo site (you can see that the columns are not going full width: https://understrap.com/understrap/ (note that on desktop it looks fine even at small browser width, but not so on actual iPad).

Please advise, I have a looming deadline!

**Comment by mkavanti** [comment]
I noticed the same issue. I was using an iPad with a 7.1 ios release (2014). Once I updated ios to the latest version the issue was resolved. Bootstrap 4 is supposed to support ios 7+ (https://v4-alpha.getbootstrap.com/migration/) so not sure if this is where the issue lies or not.

**Comment by mkavanti** [comment]
Also - I noticed that some of my earlier Understrap sites (around 0.4.7) did not have this issue whereas the newer ones (0.5.4) did. Reverting to a CSS file from the earlier version also resolved the issue.

**Comment by holger1411** [comment]
Sounds like a Bootstrap Alpha 5 to Alpha 6 problem.
Since UnderStrap 0.5.2 Bootstrap 4 Alpha 6 is in use. all earlier versions use Bootstrap 4 Alpha 5.

**Comment by axlright** [comment]
Closing this issue as it hasn't been commented on in over six months and was most likely attributed to issues with Bootstrap alpha releases. Comment if the issue persists and it can be re-opened.
