### ISSUE TITLE
Stuck with menu being pulled to the right? Help....

### ISSUE THREAD

**Issue by sebgates** [understrap/understrap#288]
Hi, pardon my ignorance, I have been using genesis for the past 5 years and I am trying to move towards Bootstrap. I have tried pull-xs-right and float-xs-right based on other forum threads I have read by the list items continue to stay left.

				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>

Where do I put the class to make the list items float right?

![what it looks like](https://cloud.githubusercontent.com/assets/7439402/25106236/54c844fe-23c0-11e7-893c-09a74b82c8e2.png)

![what i want it to look like](https://cloud.githubusercontent.com/assets/7439402/25106237/54cd66be-23c0-11e7-84bf-3de1f6499f5f.png)

**Comment by typeplus** [comment]
I am no expert on flex, but this should do the trick;

`.navbar-toggleable-md .navbar-collapse {
    justify-content: flex-end;}`

**Comment by richyrb00** [comment]
I've never actually tried float-xs-right, or pull-xs-right as these are included in Bootstrap 4 and i usually play with BS3. 

but if you wanted to add a class that would push them right i would do as follows

    <?php wp_nav_menu(
				array(
					'theme_location'  => 'primary',
					'container_class' => 'collapse navbar-collapse',
					'container_id'    => 'navbarNavDropdown',
					'menu_class'      => 'navbar-nav',
					'fallback_cb'     => '',
					'menu_id'         => 'main-menu',
					'walker'          => new WP_Bootstrap_Navwalker(),
				)
			); ?>

**Comment by typeplus** [comment]
@richyrb00 you might want to check that as it does not appear to work. I think they have been removed in favour of float-left and float-right https://v4-alpha.getbootstrap.com/migration/

**Comment by washaweb** [comment]
In Bootstrap alpha6 you'll have to add ´mr-auto´ to the navbar-nav class : ´navbar-nav mr-auto´.

**Comment by raisonon** [comment]
Just to add, you actually need to add ml-auto:

`		<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav ml-auto',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new understrap_WP_Bootstrap_Navwalker(),
					)
				); ?>`

**Comment by Thomas-A-Reinert** [comment]
I guess that has been solved by now? Closing the topic because there has been no update in more than a month now. Feel free to re-open if the problem remains, okay?
