### ISSUE TITLE
Font Awesome Fonts Not Included Properly in theme.min.css

### ISSUE THREAD

**Issue by flawiddsouza** [understrap/understrap#318]
`/wp-content/themes/understrap/css/theme.min.css?ver=0.6.0` references the fonts as 
```
@font-face{font-family:FontAwesome;src:url(fonts/fontawesome-webfont.eot?v=4.7.0);src:url(fonts/fontawesome-webfont.eot?#iefix&v=4.7.0)...and so on
```

The problem is, fonts are not situated in `/wp-content/themes/understrap/css/` but in `/wp-content/themes/understrap/fonts/`.

So I'm getting 3 "Failed to load resource: the server responded with a status of 404 (Not Found)" in my browser's console.

fontawesome-webfont.woff2 Failed to load resource: the server responded with a status of 404 (Not Found)
fontawesome-webfont.woff Failed to load resource: the server responded with a status of 404 (Not Found)
fontawesome-webfont.ttf Failed to load resource: the server responded with a status of 404 (Not Found)

Requested paths are:
```
/wp-content/themes/understrap/css/fonts/fontawesome-webfont.woff2?v=4.7.0
/wp-content/themes/understrap/css/fonts/fontawesome-webfont.woff?v=4.7.0
/wp-content/themes/understrap/css/fonts/fontawesome-webfont.woff2?v=4.7.0
```

When they actually should be:
```
/wp-content/themes/understrap/fonts/fontawesome-webfont.woff2?v=4.7.0
/wp-content/themes/understrap/fonts/fontawesome-webfont.woff?v=4.7.0
/wp-content/themes/understrap/fonts/fontawesome-webfont.woff2?v=4.7.0
```

Is this a bug or intentional or am I missing something? I'm on the latest master.

Moving the "fonts" directory into the "css" directory fixes this problem.

**Comment by holger1411** [comment]
Strange thing is it works here. As you can see it on the demo page:
https://understrap.com/understrap/
there are the small FA icons and anything is loaded properly.
Also by default the path in theme.min.css is here:
@font-face{font-family:FontAwesome;src:url(../fonts/fontawesome-webfont.eot?v=4.7.0);src:url(../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0)

As far as I could see it here FA uses a variable for there root directory in there scss file here:
src/sass/fontawesome/_variables.scss
called:
`$fa-font-path:        "../fonts" !default;`

Check if it is the same.
If not:

Make sure you have anything updated:
- Delete the /node-modules folder (just to be sure nothing is left...)
- Run `npm install` in your terminal 
- Run `gulp sass` followed by  `gulp minify-css`
- Than re-check your font path in theme.min.css

**Comment by washaweb** [comment]
Got the same issue since the last version of Understrap.
The links to the fonts are correct in `theme.css`, but they go wrong after minification process in `theme.min.css`. 
The problem seems to come from the new cleanCSS task in gulpfile.

A temporary fix is to use the non minified `theme.css` **or** to use the old `cssnano` task in place of `cleanCSS`.

**Comment by washaweb** [comment]
Also, I use a couple others fonts in my theme. 
This path issue goes the same with all my fonts assets.

**Comment by holger1411** [comment]
Very strange...
Can you run the task`gulp minify-css` ? Does it compile the theme.css into theme.min.css if you run it as stand-alone task?

**Comment by flawiddsouza** [comment]
`$fa-font-path: "../fonts" !default;` is the same.

**Comment by EricaLynnFL** [comment]
Hi - I just posted in a closed thread about my child theme seems to be minifying before compiling the sass. Using the non-minified version works .. however I ran the gulp minify-css after compiling sass .. and my changes (which was just updating $brand-primary), did not appear in the new minified version. 

I have a brand new install as of this morning .. child theme Version:      0.3.0

**Comment by holger1411** [comment]
Should be fixed with 0.3.2

**Comment by Thomas-A-Reinert** [comment]
As i´ve not seen the problem being reported since then, i´ll close the issue. Feel free to re-open if the problem remains with the latest version, okay?

**Comment by cleisonwebdesi1** [comment]
Hi. I see then font awesome webfont woff2 is not working. Font-awesome.css?
