### ISSUE TITLE
Uncaught Error: Tooltip is transitioning

### ISSUE THREAD

**Issue by umerkakar** [understrap/understrap#326]
Helllo,
Working on some other project. Found the console generating an error. "Uncaught Error: Tooltip is transitioning".
Can you look into the issue. Screenshot for reference. I just place tooltip on my content.

![screenshot_1](https://cloud.githubusercontent.com/assets/11842713/26269345/4a757c72-3d0d-11e7-8f2f-129d302cf6fc.png)

**Comment by typeplus** [comment]
Will be fixed in beta 1;

https://github.com/twbs/bootstrap/pull/21743

Cheers

**Comment by selfagency** [comment]
I was able to resolve this issue by removing `hidden-md-down` from my `navbar-menu`.

**Comment by Thomas-A-Reinert** [comment]
Haven´t seen this issue coming up for months now. So i´ll close it. Feel free to re-open if the problem persists with the latest version of UnderStrap, okay?
