### ISSUE TITLE
Woocommerce Integration - Nothing is wrapped in bootstrap classes.

### ISSUE THREAD

**Issue by pierrerocket** [understrap/understrap#328]
Hello,

Any plans for, or ideas on how to re-template woocommerce to use bootstrap grid classes?

For example, on your demo, for the product archive products are still in ul>li instead of col-md-4, same goes for single product page, things are still using woocommerce's default classes instead of bootstrap grid classes.

**Comment by umerkakar** [comment]
If you feel that you need bootstrap grid for products on archive page. Then, I will say go a head. If you need more control over understrap. Play with it as you want. As it's a basic framework.
I personally love with it. As I have done lot of projects with it, simple to complex.

**Comment by holger1411** [comment]
Close this.
Basically it might be a good idea in some cases.
But than we have to maintain a complete copy of the WooCommerce frontend.
That will cost a lot of resources we can´t spend for core features.
