### ISSUE TITLE
Collapsable Menu not staying collapsed

### ISSUE THREAD

**Issue by majanen99** [understrap/understrap#329]
Safari under ios 8 the collapsable menu keeps jumping to its original state.

**Comment by Thomas-A-Reinert** [comment]
Don´t have an IOS device to check but as I developed quite some sites based on UnderStrap in the meantime and none of my Apple-centric users ever mentioned that bug nor that the problem has been mentioned by others, I guess it has been resolved in the meantime.

Closing the issue therefore. Please feel free to re-open it if the problem persists with the latest version, okay?
