### ISSUE TITLE
When uploading the theme to a godaddy hosted website It uploads the initial state of the theme

### ISSUE THREAD

**Issue by AlexChiru** [understrap/understrap#333]
Helo, 

I just uploaded my website to the live hosting and I don't see any of the css, javascript or other code that I've added, I just see the initial understrap theme.
Do I need to do anything to compile all the code or am I missing something?

Thank you.

**Comment by holger1411** [comment]
Does it work on your local enviroment? 
And yes, you need to compile the sass changes to css.

**Comment by derekh77** [comment]
@holger1411 hey great work on the theme! I haven't used npm with a Wordpress and shared hosting before. I have a question related to this so just asking here which I hope is ok. So obviously I'm not going to have node / npm on shared hosting right. So would the workflow just go like this:

Develop locally with node / npm etc. > push to repo > then pull to remote via SSH?

I really want to use this theme for a new site as it has pretty much everything I need. Am I missing anything?

Also what should be files should I ignore? 

Thanks in advance. If you want me to create a separate issue or there is another support forum I'd be happy to do that too and hope to contribute in some way in the future too as I truly appreciate your work with this.

Thanks.

**Comment by holger1411** [comment]
@derekh77: Yes, thats right. You don´t need the whole npm/gulp stuff on your live site.
Just develop locally, than upload the result to your live server.

There is a gulp task to pack all you need (but not more) into a folder:
Run `gulp dist`
That will create a folder called /dist with all you need but without the /node-modules, /src and /sass folder and some other files like gulpfile.js.
Just upload the content of this folder to your theme folder on your live system.
You can do it by SSH, SFTP or any deployment service.

**Comment by derekh77** [comment]
@holger1411 Ok I got that done and think I'm ready. A question though:

When I develop WordPress sites I usually push the theme/s to a repo then pull them to the remote SSH. Of course there is no need to use VCS for all the WP files right. 

If I follow this workflow with this method I'd still be uploading all the theme files etc. including the dist folder right. Should I git ignore a lot of this then?

Thanks a million sir.

**Comment by Thomas-A-Reinert** [comment]
I guess that´s been solved. Feel free to re-open if the issue remains, okay?
