### ISSUE TITLE
Unused Wrapper Classes in Header

### ISSUE THREAD

**Issue by dantzlerwolfe** [understrap/understrap#334]
I'm having trouble understanding the `wrapper-fluid` and `wrapper-navbar` classes in `header.php`. I can't find any CSS/JS file where these classes are referenced.

**Comment by holger1411** [comment]
They are not in use but useful if you need a Div around the navbar. 
So you should be able to remove them if you want.

**Comment by axlright** [comment]
For the sake of cleanliness and shorter markup, I would support removing these classes, relying on the id, and changing the closing div comment to support the change.

The risk is if others have written css / sass with these classes. But that risk gets bigger the more releases the classes are included in.

@holger1411 @Thomas-A-Reinert others?

**Comment by holger1411** [comment]
@axlright: I´am with you. I implemented the classes long time ago...as a "just-in-case" container.
Feel free to remove it and open a pull request for it.
Let me know if you have no time for it. Than I will have a look at it.

**Comment by axlright** [comment]
Added pull request #608 to resolve this issue.

**Comment by holger1411** [comment]
Merged @axlright commit. Thx!
