### ISSUE TITLE
Browser scroll bar introduces page jump

### ISSUE THREAD

**Issue by misiman** [understrap/understrap#338]
Hi, and thanks for your theme.

Re: Understrap 0.6.1 with vanilla Wordpress 4.7.5 

The page alignment is different when the page length is shorter than the viewport  (i.e. no browser scroll bar) verses when the page length is longer than the viewport (and the browser needs to introduce a scrollbar).

This causes a small "jump" in the page content from right to left as the template changes it's width (and thus centre) calculation. Obviously not a major problem, but one of those little things.

Best regards.

**Comment by holger1411** [comment]
Thats your browser. It showas a scrollbar if needed and no scrollbar if not needed.
Thats why it looks like the page "jumps" if you visit a higher page after a "not-so-high" page...
A default behavior and nothing which could/should be customized by a website/theme

**Comment by misiman** [comment]
Yes, understood - I've worked around this issue before using some CSS, a couple of examples are:

https://css-tricks.com/elegant-fix-jumping-scrollbar-issue/
