### ISSUE TITLE
Gulpfile 'scripts' task doesn't add all files in src/js. Are they necessary?

### ISSUE THREAD

**Issue by AFlowOfCode** [understrap/understrap#345]
Edit: The task comment doesn't say it adds everything in src/js, I just took it to mean that, incorrectly I think. 

In any case, it's easy enough to add scripts in, but I was wondering if there's some reason why the gulp scripts task explicitly only concats 3 scripts (tether, bootstrap, skip-link-focus-fix)? 

This leaves me wondering if the scripts that come in the src/js folder which are not included in the task are necessary (navigation.js, core.js, customizer.js, jquery, jquery.slim). I'm actually loading jquery in enqueue.php from Google, but I'd rather leave all the other src/js files out if they aren't needed. Forgive me if I missed somewhere describing the specific functionality of these files and whether or not they are optional for certain features, I did look.

```
// Run: 
// gulp scripts. 
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
	var scripts = [
		basePaths.dev + 'js/tether.js', // Must be loaded before BS4
			// Start - All BS4 stuff
		basePaths.dev + 'js/bootstrap4/bootstrap.js',
			// End - All BS4 stuff
			basePaths.dev + 'js/skip-link-focus-fix.js'
	];
  gulp.src(scripts)
	.pipe(concat('theme.min.js'))
	.pipe(uglify())
	.pipe(gulp.dest('./js/'));
	  gulp.src(scripts)
	.pipe(concat('theme.js'))
	.pipe(gulp.dest('./js/'));
});
```

**Comment by holger1411** [comment]
No, its not necessary. The bootstrap.js file already icludes all BS JS files, Jquery is provided by WordPress etc.
So its up to you. You can use this gulpfile.js area for a more granular JS combination if you want/have to. But if not you are good to go with the defaults.

**Comment by flyingchorse** [comment]
So if I want to use a javascript library such as Masonry or Packery, I can install to my local machine using npm, how do I then get it to compile do I need to add it into my gulpfile ??or should I just be enqueue it. I was thinking it would be best practice to minify it all into on the one js file.
