### ISSUE TITLE
Where does one typically develop, inside or outside the theme directory?

### ISSUE THREAD

**Issue by dylannirvana** [understrap/understrap#352]
I hope this isn't a stupid question, but I am trying to wrap my head around developing within the theme directory. The workflow I normally use (with Gulp) is to create a front-end app outside of the WordPress directory, copying essentially the front-page.php into the theme directory, and adapting the template files to work with it. 

So, my question is about workflow. Where do you prefer to build your styles, logic, etc., within the theme directory or outside it? Isn't it a lot of overhead to keep development files in the theme dir?

**Comment by derekh77** [comment]
@pierinocipolloni My workflow goes something like this:

- Clone parent / child to local LAMP stack.
- The parent is just for the updates.
- The child is used for development.
- NPM, Gulp, etc is used in both theme directories for updates.
- Both get pushed to remote repository.
- Both get pulled / synced to remote host.

To more specifically answer your question: everything is "built" in the child theme directory.

This may not be the perfect workflow and it's taken some time to figure out the best way to use WordPress, version control and now I'm still becoming comfortable with adding task runners to the process etc. but feel I'm getting closer to what I want. However, I could reconsider how I do this and completely rework my flow again in the future. Perhaps someone else could chime in on this but hope this is somewhat helpful. Thanks.

**Comment by Thomas-A-Reinert** [comment]
I guess that has been solved, so i´ll close it. Feel free to re-open if the issue persists, okay?
