### ISSUE TITLE
WooCommerce templates out of date with WC3.1.0

### ISSUE THREAD

**Issue by jhob101** [understrap/understrap#363]
WooCommerce is reporting that a number of the template overrides are out of date with the current version of WooCommerce (3.1.0):

mysite/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0, 
mysite/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.1.0, 
mysite/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.1.0, 
mysite/woocommerce/myaccount/form-edit-address.php version 3.0.0 is out of date. The core version is 3.0.9, 
mysite/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.1.0, 
mysite/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0, 
mysite/woocommerce/single-product/review-rating.php version 3.0.0 is out of date. The core version is 3.1.0,

**Comment by holger1411** [comment]
Hi!
Was fixed here: 
https://github.com/holger1411/understrap/pull/359

Will be released with 0.6.3
To use the fixed version now please download the theme here from Github

**Comment by evandiamond** [comment]
@holger1411 Awesome, thank you!

**Comment by holger1411** [comment]
Closing this because: Seems to be fixed.
If not feel free to reopen!
