### ISSUE TITLE
Modals not working

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#375]
Hi I am working on a fresh wp instal with the latest version of wordpress and understrap. All is going well but modal's will not open

Here is an example https://nomadsv5.wpengine.com/test/

I have also tried this in a local environement and with the master theme as well as the child. Still not luck. 

Any chance I can get some help from someone?

Thanks

**Comment by shawnquinn** [comment]
Hey Shannon,  it looks like you're not calling the modal function. Add this to the same page or within the footer: 

```
<script>
$('#exampleModal').modal({
    keyboard: false
})
</script>
```
This will target your button with the id="exampleModal".

**Comment by shansmith01** [comment]
Legend! Thanks for the help

**Comment by axlright** [comment]
Closing this issue because @shawnquinn looks to have helped and it hasn't been updated in over six months.
