### ISSUE TITLE
wc-product-gallery-slider breaks due to figure max-width attribute

### ISSUE THREAD

**Issue by jhob101** [understrap/understrap#384]
The following selector

`img.wp-post-image, article img, figure, img, #secondary img {
    max-width: 100%;
    height: auto;
}`

Breaks the wooCommerce product gallery when slider is enabled.

Either needs a specific selector for `.woocommerce div.product div.images .woocommerce-product-gallery__wrapper` to set `max-width:none; ` or for figure to be excluded from the original selector.

**Comment by bruceconlon** [comment]
Agree, had to change this in my theme also to get the gallery working.

Am closing https://github.com/holger1411/understrap/issues/499 as this issue is the root of the issue.

**Comment by holger1411** [comment]
Closing this because it is outdated and was solved via another issue/pr.

**Comment by S8creative** [comment]
Hi..
I don't know if the subject can be re-opened. But I am also having issues with the Woocommerce Product Lightbox.
I have been trying for over 2 hours to fix a bug with distorts the image in the lightbox when you zoom in on the image.

My question is : (and this would be the easier fix)
**How can we disable the zoom option WITHIN the Lightbox?**
Or
A 2nd solution would be to apply a CSS style to that particular element, and set the max-width to "auto".
That seems to be working in development mode in Chrome, but I can't seem the find a way to add it in my custom CSS in my theme.

Many thanks for your help !
Stephanie
<img width="862" alt="image is distorted whn zoomed in" src="https://user-images.githubusercontent.com/47318151/61999662-ab920f00-b0c6-11e9-9b45-8e1092e4b65a.png">
