### ISSUE TITLE
Can not do NPM install/run gulp in child theme after updating understrap

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#389]
Hi There

Thanks for all you hard work on this team.

I have just updated to yesterdays version of understrap. I have also just done a fresh install of WP + Understrap + Understrap child on my local environment but I can't get NPM to install and run gulp in my child theme. Everything is running fine in the master copy. Is this going to be due to the update?

Any help would be appreciated. Thanks

Debug attached

[npm-debug.txt](https://github.com/holger1411/understrap/files/1224311/npm-debug.txt)

**Comment by holger1411** [comment]
Hm, works here.
Try to clean your npm cache:
`npm cache clean`

But I will also release v 0.3.3 within the next days (0.3.2 uses Bootstrap 4 Alpha 7 while the parent theme v 0.6.3 uses already Bootstrap 4 Beta). So maybe it´s a good idea to wait ;-)

**Comment by shansmith01** [comment]
Ok Ta. I ended up fixing it before i saw your reply i just replaced all the child theme files..
All good. Thanks for updating the child theme too

**Comment by 0dp** [comment]
@holger1411 @Thomas-A-Reinert @axlright close?

**Comment by Thomas-A-Reinert** [comment]
Cannot test anything atm, sorry for that. I´m currently heavily involved in four WP projects, so I just don´t find the time.

But if it´s not an issue anymore.. I´d generelly say close and leave a friendly message to please re-open if help ist still needed ;)

**Comment by Thomas-A-Reinert** [comment]
Ah, sorry, didn´t know. But as I was already on it, I closed it.

**Offtopic:** Could you please explain to a silly german (who until just now thought he would understand english and english idioms pretty well) what "_making that cheddar_" means?  :)

**Comment by 0dp** [comment]
Ohne Knete, keine Fete 😂

**Comment by axlright** [comment]
@Thomas-A-Reinert What do Americans talk about more than anything else? "Making that cheddar" means making money. Why cheese is equated with money? Because everything is equated with money.
