### ISSUE TITLE
Issue with modifying _child.theme.scss, throws error in bootstrap4/_variable.scss

### ISSUE THREAD

**Issue by lognitesh** [understrap/understrap#390]
Not sure, if the below issue has already been taken care, but somehow I can't get started. I am trying to do some changes using "gulp watch-bs". Whenever I try changing anything inside _child.theme.scss file, I see below issue..

1:30:33 PM Error (0x01) - Line: 168 Col: 25

argument `$color` of `darken($color, $amount)` must be a color

Backtrace:
../../../../../../../../../../../../..:168, in function `darken`
../../../../../../../../../../../../../..localhost-pathname.../wp-content/themes/understrap-child/src/sass/bootstrap4/_variables.scss:168
_variables.scss

167: $link-decoration:       none !default;
**168: $link-hover-color:      darken($link-color, 15%) !default;**
169: $link-hover-decoration: underline !default;

/..localhost-pathname.../wp-content/themes/understrap-child/src/sass/bootstrap4/_variables.scss

**Comment by holger1411** [comment]
Closing this because: Seems to be fixed.
If not feel free to reopen!
