### ISSUE TITLE
header image

### ISSUE THREAD

**Issue by captain-sensible** [understrap/understrap#393]
normally with theme you can from dashboard click appearance -> header 

I can see a directory "image" containing header.jpg so it looks like functionality is there; its just that I can't seem to access it.

For now my hack in header.php is 
```
  <?php wp_head(); ?>
<img class ="center-block img-responsive " src ="<?php echo home_url();?>/wp-content/themes/understrap/images/top.png" >
	</head>
```
Obviously not great but only way I know how!

**Comment by sommerset** [comment]
what I usually do is define a constant in my functions.php file 
`
define ( 'TEMPPATH', get_bloginfo ('stylesheet_directory'));
define ( 'IMAGES', TEMPPATH . "/images");`

and the echo from there:

` <?php wp_head(); ?>
<img class ="center-block img-responsive " src ="<?php echo IMAGES;?>/top.png" >
	</head>`


hope it helps!

**Comment by captain-sensible** [comment]
cheers for that will give it a go !

**Comment by Thomas-A-Reinert** [comment]
I guess that has been solved by now. Closing it due to inactivity for more than one month.

**Comment by captain-sensible** [comment]
yes solved

suggestion worked a treat !

cheers

andy brookes
