### ISSUE TITLE
SASS error after installing the CORE child theme

### ISSUE THREAD

**Issue by newtjikko** [understrap/understrap#397]
After I installed the core theme I get the error

` Error in plugin 'gulp-sass'
Message:
    src\sass\bootstrap4\_variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        src/sass/bootstrap4/_variables.scss:168, in function `darken`
        src/sass/bootstrap4/_variables.scss:168
        on line 168 of src/sass/bootstrap4/_variables.scss
>> $link-hover-color:      darken($link-color, 15%) !default;
   ------------------------^

Details:
    status: 1
    file: C:/xampp/htdocs/modernhippie.local/wp-content/themes/core/src/sass/bootstrap4/_variables.scss
    line: 168
    column: 25
    formatted: Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        src/sass/bootstrap4/_variables.scss:168, in function `darken`
        src/sass/bootstrap4/_variables.scss:168
        on line 168 of src/sass/bootstrap4/_variables.scss
>> $link-hover-color:      darken($link-color, 15%) !default;
   ------------------------^

    messageFormatted: src\sass\bootstrap4\_variables.scss
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        src/sass/bootstrap4/_variables.scss:168, in function `darken`
        src/sass/bootstrap4/_variables.scss:168
        on line 168 of src/sass/bootstrap4/_variables.scss
>> $link-hover-color:      darken($link-color, 15%) !default;
   ------------------------^

    messageOriginal: argument `$color` of `darken($color, $amount)` must be a color

Backtrace:
        src/sass/bootstrap4/_variables.scss:168, in function `darken`
        src/sass/bootstrap4/_variables.scss:168
    relativePath: src\sass\bootstrap4\_variables.scss
`

**Comment by holger1411** [comment]
Do you do any changes to the Core child theme or update its dependencies?

**Comment by castroalves** [comment]
I'm getting the same error. I'm using the latest versions of Understrap and Undestrap-child themes.

**Comment by slambert** [comment]
I'm also seeing this with the latest versions of both.

      Message:
          src/sass/bootstrap4/_variables.scss
      Error: argument `$color` of `darken($color, $amount)` must be a color

             Backtrace:
              src/sass/bootstrap4/_variables.scss:142, in function `darken`
              src/sass/bootstrap4/_variables.scss:142
              on line 142 of src/sass/bootstrap4/_variables.scss
      >> $link-hover-color:          darken($link-color, 15%) !default;
         ----------------------------^

      Details:
          status: 1
          file: /Applications/MAMP/htdocs/wp-content/themes/core-understrap-1-0-4/src/sass/bootstrap4/_variables.scss
          line: 142
          column: 29
          formatted: Error: argument `$color` of `darken($color, $amount)` must be a color

             Backtrace:
              src/sass/bootstrap4/_variables.scss:142, in function `darken`
              src/sass/bootstrap4/_variables.scss:142
              on line 142 of src/sass/bootstrap4/_variables.scss
      >> $link-hover-color:          darken($link-color, 15%) !default;
         ----------------------------^

          messageFormatted: src/sass/bootstrap4/_variables.scss
      Error: argument `$color` of `darken($color, $amount)` must be a color

             Backtrace:
              src/sass/bootstrap4/_variables.scss:142, in function `darken`
              src/sass/bootstrap4/_variables.scss:142
              on line 142 of src/sass/bootstrap4/_variables.scss
      >> $link-hover-color:          darken($link-color, 15%) !default;
         ----------------------------^

          messageOriginal: argument `$color` of `darken($color, $amount)` must be a color

      Backtrace:
          src/sass/bootstrap4/_variables.scss:142, in function `darken`
          src/sass/bootstrap4/_variables.scss:142
          relativePath: src/sass/bootstrap4/_variables.scss
      [20:33:27] Finished 'sass' after 80 ms

**Comment by Thomas-A-Reinert** [comment]
Core is a premium / paid (child) theme (based on understrap). Please contact the service mentioned when closing the contract, in your readme or whatever. Or contact @holger1411 directly who is responsible for CORE.

This issue tracker is however just about the free parent theme only.
