### ISSUE TITLE
Issue combining scripts on child theme

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#398]
Hi,

I am having issues combining scripts. I have added some extra things my child eg https://github.com/kni-labs/rrssb

I am adding my js into /src/js and have added the following lines to my gulp file

`gulp.task('scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        basePaths.dev + 'js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        
        basePaths.dev + 'js/skip-link-focus-fix.js',
        basePaths.dev + 'js/stickyfill.js',
        basePaths.dev + 'js/ekko-lightbox.js',
        basePaths.dev + 'js/rrssb.min.js'
        
    ];`

After running gulp scripts everything seems to be in the child-them.min.js but some scripts like rrssb and ekko don't want to work. If i include these files separately in the footer things work fine. Is there something I am missing here?

You can seem My theme repository here https://github.com/shansmith01/Nomadsv5

Thanks

**Comment by axlright** [comment]
Closing this issue because it has not been commented on in six months and because a solution has been implemented for adding custom scripts. @shansmith01 comment if you're still experiencing trouble.
