### ISSUE TITLE
Font Awesome and Posts

### ISSUE THREAD

**Issue by zalkowitz** [understrap/understrap#405]
Hi,
The built-in font awesome is not showing in the single page posts. I'm looking at previous and next links with an empty box where the arrows should be. I'm a beginning developer so any help would be appreciated.
Thanks in advance.

**Comment by holger1411** [comment]
Works on the demo site here:
https://understrap.com/understrap/?p=1721
It normally means Font Awesome is blocked by something or the Browser misinterprete something. Can you post an URL?

**Comment by Thomas-A-Reinert** [comment]
Also tried it and cannot reproduce the issue. Closing it anyway due to no feedback for more than a month. Feel free to re-open if the problem persists, okay?
