### ISSUE TITLE
Font Awesome Code is present in the Nav Walker but you cant set the icons in the backend

### ISSUE THREAD

**Issue by richardmax** [understrap/understrap#423]
Line 124 of inc/bootstrap-navwalker reads as:

// Font Awesome icons
if ( ! empty( $icon ) ) {
   $item_output .= '<a' . $attributes . '><span class="fa ' . esc_attr( $icon ) . '"></span>&nbsp;';
} else {
   $item_output .= '<a' . $attributes . '>';
}

How can we select which icon shows on which menu / page item?

**Comment by holger1411** [comment]
Sorry. There is no backend option to set icons for menu items currently.

**Comment by h2ocreative** [comment]
Being a dufus (but a great WP dev!) i assume i could add it and craete a
Pull Request,

Is that ok?

R

**Comment by holger1411** [comment]
Sure! @h2ocreative

**Comment by Thomas-A-Reinert** [comment]
Don´t know if you really submitted a pull request, but it works like a charm (now) if you assign the correct class to the menu item.

You´d need to make the CSS class editor accessible though:
![image](https://user-images.githubusercontent.com/5886977/36915269-652e31ce-1e50-11e8-89ca-02d4023c23f8.png)

Then just add your class like that:
![image](https://user-images.githubusercontent.com/5886977/36915328-8e45344a-1e50-11e8-8aaf-9322d13eaa49.png)

Et voilá:
![image](https://user-images.githubusercontent.com/5886977/36915388-bf2e7616-1e50-11e8-8774-0ed130d64b04.png)

Closing the topic and marking it as fixed.
