### ISSUE TITLE
metaslider appearing under navbar fixed top in mobile view

### ISSUE THREAD

**Issue by zalkowitz** [understrap/understrap#434]
Hi,
In mobile view (iPhone 5 or 6) the navbar is covering content (part of the caption) of my meta slider.
I've tried adding in media queries margin- top or padding-top to everything.

Many thanks in advance,
z

**Comment by holger1411** [comment]
Yes, if you use a fixed navbar you have to add some padding-top to your body. 

Check this Bootstrap 4 official sample:
http://getbootstrap.com/docs/4.0/examples/navbar-fixed/
They add `padding-top:4.5rem;`
