### ISSUE TITLE
How to make my own child theme (not using understrap-child)

### ISSUE THREAD

**Issue by nuthinbutajthang** [understrap/understrap#436]
I would like to make my own child theme on top of a parent theme based on Understrap.

I'm following the standard way to create WordPress child theme, but it's not working. It works with other themes such as Twenty Seventeen, so I'm wondering if it's not possible with Understrap.

style.css
```
/*
Theme Name: understrap-ch  
Template: understrap
*/
```

functions.php
```
<?php
add_action( 'wp_enqueue_scripts', 'theme_enqueue_styles' );
function theme_enqueue_styles() {
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
wp_enqueue_style( 'child-style',
get_stylesheet_directory_uri() . '/style.css',
array('parent-style')
);
}
?>
```

As a result, I get this when I activate my child theme.

![2017-10-18 15 07 40](https://user-images.githubusercontent.com/25931045/31720207-305e59b4-b416-11e7-989a-3b34775f17e8.png)

**Comment by shansmith01** [comment]
Understrap works a little different for child theme development. The good news is there is a pre-made child theme which you can download and change as you wish. More info and download here https://github.com/holger1411/understrap-child

**Comment by nuthinbutajthang** [comment]
@shansmith01 Thanks, that's what I suspected. Yes, I'm aware of the pre-made child theme, but I wanted to know if I can make my own theme based on Understrap, and customize it in its child theme on each website. I guess it's not possible. Which means that a theme created based on Understrap cannot become a parent theme, right?

**Comment by shansmith01** [comment]
The pre-made chid theme is bare bones and basically, give you the same result as the parent theme. The idea is that use can use this child theme as a base for dev. I am doing exactly that. You can see an example of how I have edited the child theme here - https://github.com/shansmith01/Nomadsv5 (note I am not the worlds best dev and still learning all the NPM gulp stuff)

**Comment by nuthinbutajthang** [comment]
Thanks, @shansmith01. Yes, I think that works fine for you. But you're just creating another version of Understrap. The theme you developed using Understrap Child, can it be used as a parent theme? Let's say someone wants to use this theme and customize it. This person would have to edit it directly, right? As I understand it's not the common practice in WordPress theme customization. (Me too, I'm new to all this... So I apologize if I'm wrong)

**Comment by shansmith01** [comment]
No I have made child theme using the understrap child theme as a template. My child theme still relies on logic from the understrap parent theme. 

I could have made all my changes in the understrap parent theme and called it my own but I didnt. 

If someone wants to use my child-theme and customise would they need to edit the code. As i have not built in any admin option pannels

**Comment by B-Stewart** [comment]
@nuthinbutajthang I got my own child themes working with the following:

style.css
```
/*
 Theme Name:   My Name (Understrap Child)
 Theme URI:    
 Description:  My Description
 Author:       Me
 Author URI:   http://www.example.com
 Template:     understrap
 Version:      0.6.5.0
 License:      GNU General Public License v2 or later
 License URI:  http://www.gnu.org/licenses/gpl-2.0.html
 Tags:         
 Text Domain:  my-understrap
*/
```

functions.php
```
<?php
function my_theme_enqueue_styles() {
    $parent_style = 'understrap-styles';
    $parent_theme = wp_get_theme("understrap");
    wp_enqueue_style( 'understrap-styles', get_template_directory_uri() . '/css/theme.min.css', array(), $parent_theme->get( 'Version' ) );
    wp_enqueue_style( 'child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
}
add_action( 'wp_enqueue_scripts', 'my_theme_enqueue_styles' );
?>
```

As @shansmith01 said, child themes do not work as parent themes. Any child theme is reliant upon the parent, in this case Understrap.

As a tip, I also match my version number with the parent Understrap version (e.g. 0.6.5 for parent means I'll use 0.6.5.x for the child version). That way I always know what my child relied upon.

**Comment by nuthinbutajthang** [comment]
@B-Stewart Thanks!

I realized that I hadn't fully understood the way to make a child theme.  This one line in functions.php should have looked like this:

```
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/css/theme.min.css' );
```

instead of this:

```
wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
```

It makes sense.

Thank you so much for your help!

**Comment by Thomas-A-Reinert** [comment]
@nuthinbutajthang Just to mention: In this case you´re importing the parents css - just to overwrite good amounts of it with your own. This probably causes unnecessary bloat, loading times, request etc. It _will_ have an impact on your performance scores!

Anyway: it will work but is not the recommended way.

**Comment by nuthinbutajthang** [comment]
@Thomas-A-Reinert Thanks, I never thought of it. But if that is true, wouldn't it be the same if we use Understrap-Child theme?

Here's what I want to do. I want to make my own theme based on Understrap so that I can use it as a parent theme for many websites. I've used Understrap-child theme before to make a website, but I didn't think it was efficient to start from scratch (latest Understrap) every time. There are shortcodes and design patterns that I would like to use again in other websites so making my own theme and being able to customize on its child theme seemed like a more efficient way. But if this is going to slow down the sites, I will need to reconsider.

**Comment by Thomas-A-Reinert** [comment]
Well, please bear with me that I won´t find the time to explain everything up to the last detail - i´m just preparing last steps to launch my customers WP-site today.. (guess what - based on understrap ;) )

The Child theme actually doesn´t import any css from the parent, result: -1 additional CSS request.

If I don´t need any Bootstrap-component in my child - I just comment the respective SCSS-component and it will not get compiled into CSS, result: less CSS.

It doesn´t even load any unneccessary js from the parent or even doubles them (whicht B-Stewards solution would do) - result: -1(or even more) request. PLUS the child would combine and minify them into one single file.

But I totally understand your point.
Reasons why I wouldn´t do it though: IF you would change the parent theme or combine parent/child you´d instantly lose understraps update-functionality, which may result in open security-leaks that may get detected in the future. And that´s the main reason why I wouldn´t do it.

In case you really, really need to do that though - untested, please try in dev-environment _only_ without affecting your originals! - why don´t you just copy over all your template files from the child to the parent? Second, deleting unneccessary CSS/JS from the parent and MERGING the rest. That should do the job.

Name it differently, change the text-domain to your own and you should be done. Worth a try at least as the child simply includes overwrites. 


Funny thing is: I guess you won´t find any real _solution_ for this problem on the web.
The two results which come closest (and may help) are:

- https://wordpress.stackexchange.com/questions/142593/create-a-theme-by-combining-a-parent-and-a-child-theme
- https://www.reddit.com/r/Wordpress/comments/29qek2/is_there_a_fast_way_to_combine_child_and_parent/

Heads up and please keep us updated about success/fails, okay?

**Comment by Thomas-A-Reinert** [comment]
Well, please bear with me that I won´t find the time to explain everything up to the last detail - i´m just preparing last steps to launch my customers WP-site today.. (guess what - based on understrap ;) )

The Child theme actually doesn´t import any css from the parent, result: -1 additional CSS request.

If I don´t need any Bootstrap-component in my child - I just comment the respective SCSS-component and it will not get compiled into CSS, result: less CSS.

It doesn´t even load any unneccessary js from the parent or even doubles them (whicht B-Stewards solution would do) - result: -1(or even more) request. PLUS the child would combine and minify them into one single file.

But I totally understand your point.
Reasons why I wouldn´t do it though: IF you would change the parent theme or combine parent/child you´d instantly lose understraps update-functionality, which may result in open security-leaks that may get detected in the future. And that´s the main reason why I wouldn´t do it.

In case you really, really need to do that though - untested, please try in dev-environment _only_ without affecting your originals! - why don´t you just copy over all your template files from the child to the parent? Second, deleting unneccessary CSS/JS from the parent and MERGING the rest. That should do the job.

Name it differently, change the text-domain to your own and you should be done. Worth a try at least as the child simply includes overwrites. 


Funny thing is: I guess you won´t find any real _solution_ for this problem on the web.
The two results which come closest (and may help) are:

- https://wordpress.stackexchange.com/questions/142593/create-a-theme-by-combining-a-parent-and-a-child-theme
- https://www.reddit.com/r/Wordpress/comments/29qek2/is_there_a_fast_way_to_combine_child_and_parent/

Heads up and please keep us updated about success/fails, okay?

**Comment by B-Stewart** [comment]
@nuthinbutajthang you may want to consider forking Understrap and making your changes in the parent theme as @Thomas-A-Reinert is saying if you're goal is to create a reusable theme on multiple websites.

I see this as two use cases:

1. I use a child theme if I want to keep the core Understrap parent in tact. Meaning if I want to update Understrap down the road I don't have to worry about it over writing any of my changes because all of my changes are contained within the child theme. This does mean that I am potentially using some code that I'm overriding, but that's the point because I'm relying on the core Understrap.

2. Take Understrap as the starter of a new parent theme. Take it, rename it, modify it, remove what you don't like, add what you do, etc. This would be great for you, but if you ever want to come back and take a new version of Understrap you will have much more of a problem updating it depending on the changes you've made.

**Comment by nuthinbutajthang** [comment]
@Thomas-A-Reinert Thanks, you're right about keeping unnecessary codes out of the theme. That's something I definitely need to learn because at this moment, I don't even know which CSS/JS are unnecessary for my theme or are required for Understrap as default.

To update the parent theme, I was hoping to pull the latest codes from Github when Understrap is updated. I haven't had a chance to try this, so I'm not sure if this is a good solution yet. @B-Stewart, when you say forking, do you mean like this?

The reason I started searching for other ways to create child theme is because I don't quite understand how to update Understrap Child theme. So I posted this question here and still waiting for an answer.
https://github.com/holger1411/understrap-child/issues/101

**Comment by Thomas-A-Reinert** [comment]
@B-Stewart Sorry in case you understood my mention wrong - which I suppose you did not, but just in case...
I really did not want to "downvote" it or comparable. Your solution solves the problem. But it has certain drawbacks that I wanted to let @nuthinbutajthang and others know.

The ultimate way of writing an own theme BASED pon understrap would probably be to create a fork. And then merge them, once an update is available. But my GIT-skills are by far not good enough to find out the caveats. Anyone else may add up? I´m REALLY willing to learn that and would be awfully thankful!

**Comment by nuthinbutajthang** [comment]
I'm going to try making my own theme by cloning Understrap and pull/merge to update it. I'm hoping that one of the benefit of this way is that the customized template files will be merged immediately too. We'll see...

**Comment by Thomas-A-Reinert** [comment]
Closed due to one month without response, so I assume it has been fixed.
