### ISSUE TITLE
Error: EISDIR: illegal operation on a directory,

### ISSUE THREAD

**Issue by mcropper** [understrap/understrap#452]
I am facing an issue with importing all the mixins in the bootstrap4 directory.

the same applies to the utilities subdirectory.

Without manually importing all the files in those directories how do I solve this issue.

Error: EISDIR: illegal operation on a directory, read
        on line 10 of [rest of filepath]/themes/understrap/sass/assets/bootstrap4.scss
>> @import "../../src/sass/bootstrap4/mixins";

Ive tried installing sass-glob and still the same issue occurs.

**Comment by holger1411** [comment]
There is a /utilities and /mixins subfolder AND a _utilities.scss ans mixinns.scss files within the new BS4 Beta version. And @import did not know if the folder or file is ment.

The stramge thing is it works here...

Try the following:
Open sass/assets/bootstrap4.scss
And add a ending .scss fileextension behind line 10 like:
@import "../../src/sass/bootstrap4/mixins.scss";
and line 41:
@import "../../src/sass/bootstrap4/utilities.scss";

Let me know if that works and I will incorporate it into the theme´s file

**Comment by mcropper** [comment]
The issue only arose after fixing an error with not knowing which version to import ( file names in sass/theme.scss), by changing the file /sass/theme/theme to an explicit /theme.scss for example. 
(is there another issue open regarding this error?)

I edited it and the error output has disappeared and bootstrap.min.css and bootsrap.css files generated. I will let you know if anything related arises today.  Thanks for the fix
