### ISSUE TITLE
inline-block of elements

### ISSUE THREAD

**Issue by GitStl** [understrap/understrap#454]
I feel like a burden even asking this here, but it's been tough finding resources elsewhere. 

First off, thank you. It's hard to find a framework like this to practice on. Every theme I've purchased has just been a nightmare to work on, so I decided to dive in and learn myself. Everyone steered me to this theme over Genesis, and I'm glad they did. 

My struggle lies in the header(and more to come, I'm sure, but I figured maybe if I got a bounce here I could scour the net for my answers later on). I'm trying to display a custom logo, and a phone number I added inline, but every approach I've taken has come up empty. Right now I just want a phone number on the right, logo on the left, and for the phone number to collapse into the navbar and the logo to center on mobile. There are other options I want to try, but I figured this would be a good start. 

Am I shooting for the stars here? I've seen it done other places. Here's where I'm at: 
`
body {
    background: rgb(255, 255, 255);
}

@media screen and (max-width: 480px) {
    a[href^="tel:"] {
  color: black;
  text-decoration: none;
  float: none;
}
}
    
// ------------- Telephone Styling ------------ //
a[href^="tel:"] {
  color: black;
  text-decoration: none;
  display: inline-block;
}
`
`</head>

<body <?php body_class(); ?>>

<div class="hfeed site" id="page">
    
    
    <div class="wrapper-fluid">
    <header>
    
    
        <div class="container">
					<?php if ( ! has_custom_logo() ) { ?>

						<?php if ( is_front_page() && is_home() ) : ?>

							<h1 class="navbar-brand mb-0"><a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"><?php bloginfo( 'name' ); ?></a></h1>
							
						<?php else : ?>

							<a class="navbar-brand" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>" title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"><?php bloginfo( 'name' ); ?></a>
						
						<?php endif; ?>
						
					
					<?php } else {
						the_custom_logo();
					} ?>
        </div>
    
        
        <div class="container">
            <p class="text-right">Call Now</br>
                <a href="tel:636-244-9045">636-244-9045</a></p>
        </div>

	
	<div class="wrapper-fluid wrapper-navbar" id="wrapper-navbar">

		<a class="skip-link screen-reader-text sr-only" href="#content"><?php esc_html_e( 'Skip to content',
		'understrap' ); ?></a>

		<nav class="navbar navbar-expand-md navbar-dark bg-dark">

		<?php if ( 'container' == $container ) : ?>
			<div class="container">
		<?php endif; ?>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'walker'          => new WP_Bootstrap_Navwalker(),
					)
				); ?>
			<?php if ( 'container' == $container ) : ?>
			</div>
			<?php endif; ?>

		</nav>

	</div>
    
    </header>
    </div>
`

**Comment by Thomas-A-Reinert** [comment]
Hi @GitStl  - you´re welcome. Could you show any kind of screenshot to show the intended layout? Glad to help then. But unless I can imagine what you want to achieve its like look into a crystal ball and I´m sure we can cut that pretty short once I got the picture ;)

**Comment by GitStl** [comment]
![image](https://user-images.githubusercontent.com/25417329/32529557-d5459b34-c3fe-11e7-910a-235e1cf7fe6b.png)
![image](https://user-images.githubusercontent.com/25417329/32529566-e0a4c608-c3fe-11e7-8243-4efd96bc4ac2.png)

**Comment by Thomas-A-Reinert** [comment]
Ah, I see. Something like that should do the job. (Just a _very_ quick shot. Not tested!)

```html
<nav class="navbar mobile-footer-menu fixed-bottom navbar-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#MobilenavbarNavDropdown" aria-controls="MobilenavbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-brand">
  	Call us now and the rest of it
  </div>

  <!-- The WordPress Menu goes here -->
  <?php wp_nav_menu(
    array(
      'theme_location'  => 'primary',
      'container_class' => 'collapse navbar-collapse',
      'container_id'    => 'NavDropDown',
      'menu_class'      => 'navbar-nav',
      'fallback_cb'     => '',
      'menu_id'         => 'main-menu',
      'walker'          => new WP_Bootstrap_Navwalker(),
    )
  ); ?>
</nav>```

**Comment by axlright** [comment]
Closing this issue because it has been abandoned. Please comment if you are still experiencing an issue @GitStl
