### ISSUE TITLE
Nested container div in WooCommerce files - woocommerce.php / wrapper-start.php

### ISSUE THREAD

**Issue by ZacharyElkins** [understrap/understrap#456]
https://github.com/holger1411/understrap/blob/49e80e353b4a8d605dc8b57be31ae4f634d6e6eb/woocommerce/global/wrapper-start.php#L27-L31

This creates an issue if we use the woocommerce.php included with UnderStrap.

This creates a nested container div, which is not recommend by Bootstrap, it means pages are **doubling their container padding**. Also generates double row divs, which isn't a major issue.

**woocommerce.php has the container already:**

https://github.com/holger1411/understrap/blob/49e80e353b4a8d605dc8b57be31ae4f634d6e6eb/woocommerce.php#L22-L24

**Comment by holger1411** [comment]
Closing this because:
We changed that here:https://github.com/understrap/understrap/commit/a2fa9e56ba0326ed36297d699ca06ada26110107

will be shipped with 0.8.2 soon
