### ISSUE TITLE
Why use woocommerce.php ?

### ISSUE THREAD

**Issue by MarieComet** [understrap/understrap#489]
**_--- This is not an issue report ---_**

Hello,
I'm using Understrap as a parent theme for my child themes since a long time, and recently for a WooCommerce project.
I see you added woocommerce.php, which contain `woocommerce_content` function.
I don't understand what is the benefit of this, because when using Understrap as a parent theme, with this file, it become really hard to customize WooCommerce by the "template way", for example with `taxonomy-product_cat-{term}.php`.

I will be grateful for an explanation on this point.

Thanks you.

**Comment by holger1411** [comment]
Hi!
We changed that here:
https://github.com/understrap/understrap/commit/a2fa9e56ba0326ed36297d699ca06ada26110107

will be shipped with 0.8.2 soon

Feel free to check it out and give feedback
