### ISSUE TITLE
Getting lockfile with npm install. No package.json.

### ISSUE THREAD

**Issue by dylannirvana** [understrap/understrap#491]
Installing understrap with npm install results in getting package-lock.json and no package.json. Everything else if fine but no install from that point. Do I somehow turn the lockfile into package.json? Not sure how to finish the install. Thanks.

**Comment by shansmith01** [comment]
Im getting the same issue

[19:57:25] Using gulpfile ~/node_modules/understrap/gulpfile.js
[19:57:25] Starting 'copy-assets'...
[19:57:25] Finished 'copy-assets' after 13 ms
npm WARN saveError ENOENT: no such file or directory, open '/Users/XXXXXXXX/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/XXXXXXX/package.json'
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN shannonsmith No description
npm WARN shannonsmith No repository field.
npm WARN shannonsmith No README data
npm WARN shannonsmith No license field.

**Comment by holger1411** [comment]
Can you download the package.json from here (https://github.com/holger1411/understrap/blob/master/package.json) and than run `npm install` ?

And which version of nom do you use? Had a similar issue, and its gone after updating nom and gulp on my local machine.

**Comment by dylannirvana** [comment]
Yes, downloading works fine. I updated everything before I started. 
npm 5.5.1
gulp cli 1.4.0
node v8.9.1

**Comment by alexjustesen** [comment]
Having the same issue, running on a Windows 10 machine...
- node v8.9.3
- npm v5.6.0
- gulp 3.9.1
- gulp cli 1.4.0

Also manually downloaded `package.json` and tried running `npm install` with no luck.

**Comment by axlright** [comment]
Are you still experiencing this issue @dylannirvana @alexjustesen ? Looking to clean up open issues. Thanks.

**Comment by Ostendorf** [comment]
Hello, I seen to have this same issue today. After `npm install understrap` I just get a lock-file and node_modules directory, but none of the other files.
I tried to place the `package.json` from this repo into the directory, but then it misses the `gulpfile.js` and after that has been placed it misses `gulpconfig.json`...

Versions:
* macOS 10.3.4
* node 9.11.1
* npm 5.6.0

Terminal actions/output:
```bash
tt git:(local) ✗ npm install understrap
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.

> fsevents@1.1.3 install /Users/.../wp-content/themes/tt/node_modules/fsevents
> node install

[fsevents] Success: "/Users/.../wp-content/themes/tt/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> uws@9.14.0 install /Users/.../wp-content/themes/tt/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.8.3 install /Users/.../wp-content/themes/tt/node_modules/node-sass
> node scripts/install.js

Cached binary found at /Users/.../.npm/node-sass/4.8.3/darwin-x64-59_binding.node

> node-sass@4.8.3 postinstall /Users/.../wp-content/themes/tt/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/.../wp-content/themes/tt/node_modules/node-sass/vendor/darwin-x64-59/binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall /Users/.../wp-content/themes/tt/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall /Users/.../wp-content/themes/tt/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall /Users/.../wp-content/themes/tt/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> understrap@0.8.2 postinstall /Users/.../wp-content/themes/tt/node_modules/understrap
> gulp copy-assets

[20:40:57] Using gulpfile ~/Code/.../wp-content/themes/tt/node_modules/understrap/gulpfile.js
[20:40:57] Starting 'copy-assets'...
[20:40:57] Finished 'copy-assets' after 14 ms
npm WARN saveError ENOENT: no such file or directory, open '/Users/.../wp-content/themes/tt/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/.../wp-content/themes/tt/package.json'
npm WARN bootstrap@4.1.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN tt No description
npm WARN tt No repository field.
npm WARN tt No README data
npm WARN tt No license field.

+ understrap@0.8.2
added 1278 packages in 66.298s
➜  tt git:(local) ✗ ll
total 704
drwxr-xr-x    4 username  1230074515   128B Apr 15 20:40 .
drwxr-xr-x    6 username  1230074515   192B Apr 15 20:10 ..
drwxr-xr-x  750 username  1230074515    23K Apr 15 20:40 node_modules
-rw-r--r--    1 username  1230074515   351K Apr 15 20:40 package-lock.json
```

**Comment by cqbent** [comment]
Getting same issue as Ostendorf when trying to install via npm. Using:

- MacOS 10.11.8
- Node 8.11.1
- npm 5.6.0

**Comment by 0dp** [comment]
Hey Y'all,

If you navigate to `node_modules/understrap/` and run `npm install` you'll see that everything works as expected. Deps are being installed, and `gulp copy-assets` is run without error.

Installing the theme with `npm i understrap` "installs" the theme as a project dependency. So if you haven't created a project with `npm init` first, then this is expected output.

The "problem" here is that we actually don't want to install the theme as a project dependency. Instead we would rather have it install, much more like `git clone [repo]`
Therefor I would recommend using the `git clone` method instead.

I don't know if you can actually install anything with npm without it being a project dependency.
For that you'll need something like yeoman I think.

Please, correct me if I'm wrong 🙏

**Comment by dinushchathurya** [comment]
You can simply solve the jason file issue by run` npm init ` .
