### ISSUE TITLE
BackSlash in woocommerce.php

### ISSUE THREAD

**Issue by alpayen** [understrap/understrap#494]
On line 33 to 36 in woocommerce.php

`$template_name = '\archive-product.php';
$args = array(); 
$template_path = ''; 
$default_path = untrailingslashit( plugin_dir_path(__FILE__) ) . '\woocommerce';`

Our server always returned false on 
`file_exists( $default_path . $template_name )`.

We therefore couldn't overrides templates, which drove us cray !  

`$template_name = '/archive-product.php';
$args = array(); 
$template_path = ''; 
$default_path = untrailingslashit( plugin_dir_path(__FILE__) ) . '/woocommerce';` 

The above snippet works like a charm (on our machine at least). 

Happy coding,

Alex Payen

**Comment by typeplus** [comment]
I might put some sort of detection into the code for this. Its pretty uncommon but there has been a handful of people with this issue.

**Comment by loorlab** [comment]
@typeplus Hi Jason , We have that same error, what data do you need because it is still presented in the child theme.

Similar Problems for others : https://github.com/understrap/understrap/issues/517

Thanks !

**Comment by holger1411** [comment]
Should be solved with https://github.com/understrap/understrap/commit/a2fa9e56ba0326ed36297d699ca06ada26110107

Will be shipped with 0.8.2
