### ISSUE TITLE
How do I update the theme which is created by Understrap  when there is a a update?

### ISSUE THREAD

**Issue by damithruwan1234** [understrap/understrap#502]
I have a build a custom theme using Understrap and now I am selling it via WordPress(free version) and ThemeForest (Paid version)....

Now I saw that there is a new update for understrap...

How do I update my themes with those updates?

**Comment by 0dp** [comment]
If I'm not mistaking. You need to put on a pot of coffee, put on your favorite album, and start diffing

**Comment by damithruwan1234** [comment]
@0dp Sorry, I didn't understand what you mean?

**Comment by axlright** [comment]
I think what @0dp is saying is that you need to update your modification of the theme, and that takes work on your end. You can use Git diff to help compare versions of each file that changed, or use whatever workflow works best. But it's up to you to update a version you modified.

**Comment by Vishal-Deshpande** [comment]
You can use child theme & keep updating understrap theme.

https://github.com/holger1411/understrap-child

**Comment by 0dp** [comment]
@Vishal-Deshpande of cause given that the child-theme does not update. in that case one still need to 'update your modification of the theme'

**Comment by Vishal-Deshpande** [comment]
@0dp, unless there is a security update, I generally don't bother to update, be it theme, plugin or even core wp. If everything is working fine then why bother updating?

**Comment by typeplus** [comment]
WinMerge if you use windows is pretty neat. Nothing that couldn't be handled within an hour anyway.

**Comment by 0dp** [comment]
@understrap/documentation-team

**Comment by Thomas-A-Reinert** [comment]
Well, if you use understrap as a starter theme and build up on that - that´s your way to go. but from that point on it´s all your own problem how to maintain it. 

if you want to keep it maintainable better go with a child theme.
