### ISSUE TITLE
Unable to save Theme layout from customizer. Size remain same at fixed.

### ISSUE THREAD

**Issue by umerkakar** [understrap/understrap#504]
Unable to save Theme layout from customizer. Size remain same at fixed.

**Comment by umerkakar** [comment]
Here in customizer
http://prntscr.com/hodiyi

**Comment by 0dp** [comment]
check this pull request for fix. #500

**Comment by Thomas-A-Reinert** [comment]
Seems to be fixed. Closing this topic due to inactivity for more than one month. Feel free to re-open if the problem persists, okay?
