### ISSUE TITLE
Theme Width

### ISSUE THREAD

**Issue by outcast1987** [understrap/understrap#509]
Hi,
I would like to know if I can make the site overall area (content and widget both) wider somehow on both PC and Cell?

Also in cellphone there is a lot of padding i from each site, so lot less content i see there. Can that be widened a bit as well?

I tried this code but then some boxes i made get a bit messed up. Is this code fine or any other which you can advise me? If this is fine I can try redesigning the boxes I made.

`.col, .col-1, .col-10, .col-11, .col-12, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-auto, .col-lg, .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-auto, .col-md, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-auto, .col-sm, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-auto, .col-xl, .col-xl-1, .col-xl-10, .col-xl-11, .col-xl-12, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-auto {padding-right: 0px;padding-left: 0px;}`

Thanks in Advance

**Comment by axlright** [comment]
Try adding this to your custom variables:
```
$container-max-widths: (
																		sm: 540px,
																		md: 750px,
																		lg: 970px,
																		xl: 1170px);
```
and change the values as you see fit.

**Comment by axlright** [comment]
And I would not change the padding on the columns, as the rows have negative margin to account for the padding.

**Comment by outcast1987** [comment]
Sorry for being noob in this, but this doesn't seem to work with simple wordpress customize css.  Can you give a simpler version of this which can work there? in the wordpress customize css

**Comment by axlright** [comment]
The code I included is Sass, not css. I don't think you can reasonably use this theme just making modifications in the WordPress admin menu's css modifier. You'd drive yourself crazy trying. This theme is setup to use Sass files to compile the css that is then pushed to the theme. So in short I think you're trying to use this theme setup in a way it wasn't intended.

**Comment by axlright** [comment]
I should say that this is true of any Boostrap website. Bootstrap requires using Sass to do any serious modification, not editing straight css. Unless you want to drive yourself absurdly crazy. Yes you can modify just the css but that's not really the way it's intended, or at least not in any way that's reasonably non-crazy-making.

**Comment by holger1411** [comment]
Closing this becaue of @axlright  answere:
Maintaining the CSS with the WordPress customizer to overwrite the stuff coming out of the sass files will make you crazy.
Use the customizer just for smaller, temporaily changes.

**Comment by nickty** [comment]
![image](https://user-images.githubusercontent.com/899087/95410022-b724cb00-0944-11eb-9af7-551cca785dab.png)
I changed here but its now working for me.

**Comment by nickty** [comment]
![image](https://user-images.githubusercontent.com/899087/95410570-29e27600-0946-11eb-90a2-83afcd8b713a.png)
Actually you need to bring that codes from -variables.scss to _theme_variables.scss 
This is how i solved this :)

**Comment by IanDelMar** [comment]
@nickty I'd remove the `!default`.
