### ISSUE TITLE
Configurable thumbnail size

### ISSUE THREAD

**Issue by autarch** [understrap/understrap#514]
The templates hard-code a `large` size thumbnail right now, which seems like an odd choice, since this produces a huge image that does not float to the right in the design.

I think it'd be good to ...

* Reconsider the default and use `post-thumbnail` when listing multiple posts and `medium` when displaying a single post.
* Move the thumbnail display to its own template so its easier to override. Right now changing this in a child theme requires changing many templates.

**Comment by Thomas-A-Reinert** [comment]
I´d suggest to maybe make them configurable via the Customizer..?

**Comment by Thomas-A-Reinert** [comment]
Imho that should´ve been fixed right now, can you confirm?

Closing this issue for housekeeping, please reopen if the problem remains, okay?
