### ISSUE TITLE
Custom css overridden

### ISSUE THREAD

**Issue by andyroe208** [understrap/understrap#516]
I'm not sure if it's me and my lack of knowledge but after following all instructions I finally got my custom css showing within the dev tools of chrome however they are being overridden by the default theme.min.css.

To clarify I followed instructions from [https://medium.com/all-technology-feeds/how-to-create-wordpress-themes-from-scratch-with-understrap-6f1ccf800501](url). Although this got me up and running custom css within _theme.css was not showing initially. after reinstalling this now works. 

From the screenshot below you can see this is saved but is being overriden. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/7597918/34529720-d5f63b38-f0a4-11e7-8d2f-31a8b087fd1f.png)

**Comment by holger1411** [comment]
There is an !important behind the first bg-background color setting.
Means it will overwrite other settings, even if this other settings are loaded later on.

**Comment by Thomas-A-Reinert** [comment]
Not really good code but you can add an `!important` after your css-rule. This will do the job as your css is injected after the original css.

Closing the topic though and flagging it as "fixed" as there was no reply after more than a month. Feel free to re-open if you cannot find a solution, okay?

**Comment by webstoria** [comment]
I've a problem with .nav-link want to override my style but still shows mi scss from _navbar.scss bootstrap. When I write !important in my style is ok, but my styles are loaded before than bootsrap. Where shall I put my styles to load properly

**Comment by Thomas-A-Reinert** [comment]
@webstoria That´s a different issue, so please don´t hijack other ppls issues but open your own. Include what you have done, where you have noted that s/css (in theme.scss or via customizer or where?) and what the code you wrote looks like exactly. Thanks.

**Comment by webstoria** [comment]
@Thomas-A-Reinert  Ups Very sorry I was looking for how to resolve my problem via Google and display me this issue. But You're absolutelly right. I know what to do I need put my style not before bootstrap style but after . Thx but sometimes I write sth and after that I start thinking like my css not before but after:-)

**Comment by Thomas-A-Reinert** [comment]
Okay, so your problem is solved, too?
