### ISSUE TITLE
Can't customize other woocommerce template. It uses woocommerce.php

### ISSUE THREAD

**Issue by johnashley-nohay** [understrap/understrap#517]
Hi,

I'm not sure if this is an issue or not, but It would be great if you can point me to the right direction where I can customize and not used the woocommerce.php on displayin all woocommerce page. I need to customize and have different template for each woocommerce page.

Thanks

**Comment by owaisbhat** [comment]
I am facing same issue. cant oveeride the woocommerce.php

**Comment by typeplus** [comment]
`woocommerce.php` only overrides the` archive-product.php` if there is no `archive-product.php` template override in your `\woocommerce\` folder. If you use forward slashes for your URI's then you just need to edit the `woocommerce.php` to reflect this. I have no issues overriding any template for woocommerce with the default understrap theme so please let us know your setup and the exact template that you are having an issue with.

**Comment by owaisbhat** [comment]
Replacing backward slash with forward slash in  woocommerce.php did the trick. Appreciate your help.Thanks

**Comment by holger1411** [comment]
Closing this because: Should be fixed with https://github.com/understrap/understrap/commit/a2fa9e56ba0326ed36297d699ca06ada26110107
Will be shipped with 0.8.2
