### ISSUE TITLE
WooCommerce - How To Edit Single Product Page Layout?

### ISSUE THREAD

**Issue by JDVirtual** [understrap/understrap#523]
Hello!

We've built a few themes now using Understrap, it's been working great so far.

We're building out our first WooCommerce theme on Understrap. We would like like edit the Single Product page layout.

According to the WooComm docs, you have to create an override (which we've done), and then edit single-product.php in your override folder.

We've tried that, in order to edit the layout, and none of it works. We've even deleted the single-product.php in both the override and WooComm core entirely, and nothing happens. No change takes.

Any idea why this is happening?

**Comment by 0dp** [comment]
Don't know if this is the 'right' way to do it, but if you copy single-product.php from the woocommerce templates and drop it in understrap's woocommerce overwrites. You can then change woocommerce.php:31-33 to the following
```
if ( is_singular( 'product' ) ) {

    wc_get_template_part( '/single-product', $args, $template_path, $default_path  );

}
```

**Comment by typeplus** [comment]
The `single-product.php` just calls the layout from `content-single-product.php` so if you are wanting to alter the layout you need to override this.

**Comment by the94air** [comment]
I just came by your issue and I want to point out that there is an article explaining that https://docs.woocommerce.com/document/template-structure/

**Comment by stormhillmedia** [comment]
templating is discussed but not really explained, if you ask me. The docs explain that you can change what is hooked in the template but not really how to use a different template such as an alternate single-product.php, which would be a great idea in some cases.

**Comment by jeremycaris** [comment]
"If you are using custom WooCommerce template overrides in your theme you need to declare WooCommerce support using the add_theme_support function. WooCommerce template overrides are only enabled on themes that declare WooCommerce support. If you do not declare WooCommerce support in your theme, WooCommerce will assume the theme is not designed for WooCommerce compatibility and will use shortcode-based unsupported theme rendering to display the shop." 

https://github.com/woocommerce/woocommerce/wiki/Declaring-WooCommerce-support-in-themes

**Comment by saschaende** [comment]
Worst templating i have ever seen.

**Comment by pramodhanu** [comment]
You can simply customize single-product.php through CSS. or single.php in your theme. if any person has good knowledge in the woo-commerce plugin.

**Comment by sirdash** [comment]
How about the "woocommerce_single_product_summary"?
how How can I edit the "woocommerce_single_product_summary" ?
I want to put the prices of other stores ( more offer ) in this section.
This is very important to me
please help
thank you.
