### ISSUE TITLE
Ability to filter Pagination based on category

### ISSUE THREAD

**Issue by schnoodly** [understrap/understrap#524]
Howdy,

In a website I've built, I have a certain category for Posts that is only accessible by members. If I'm not mistaken, there's no way to filter categories using the understrap pagination - I think it would be handy to have some 'filter' array/options in that function, so if it's alright I wouldn't mind trying to modify it for this project to include that - I am, however, not near an expert, so if I did that I'd just request someone to check my code.

Would this line up with project goals? Never really contributed to a project before!

**Comment by axlright** [comment]
@schnoodly I say go for it, only because any contribution from anyone excited about the project is good. Thanks for offering to help instead of asking someone else to do it :-)

**Comment by schnoodly** [comment]
Awesome! I'll get started as soon as I have free time! :)

**Comment by Thomas-A-Reinert** [comment]
I do absolutely agree with @axlright - even if I cannot really reproduce the problem. I assume category pagination works just as tag pagination - but honestly have not tested that. 
But as you can see here - https://www.tarcgn.de/mediengestalter/tag/html5/ - it works perfectly with tag pagination.
