### ISSUE TITLE
Understrap 0.8.0 on NPM

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#531]
Hey @holger1411 thanks for all your work. Will 0.8.0 be on NPM sometime soon?

Thanks
S

**Comment by 0dp** [comment]
@shansmith01 v.0.8.1 is available now.

@holger1411 npm license and changelog is not up to date on npm?

@holger1411 @Thomas-A-Reinert please close

**Comment by Thomas-A-Reinert** [comment]
Thanks, @0dp !
