### ISSUE TITLE
v0.8.0 darkens alerts beyond legibility

### ISSUE THREAD

**Issue by ErinPo** [understrap/understrap#534]
After recompiling theme.css from the included sources using ruby gem 3.5.5, I pasted these alerts in the default hello world post:

`<div class='alert alert-default'>Alerts are messed up in Understrap 0.8.0</div>`
`<div class='alert alert-warning'>Alerts are messed up in Understrap 0.8.0</div>`
`<div class='alert alert-success'>Alerts are messed up in Understrap 0.8.0</div>`
`<div class='alert alert-info'>Alerts are messed up in Understrap 0.8.0</div>`
`<div class='alert alert-danger'>Alerts are messed up in Understrap 0.8.0</div>`

![Screenshot](http://i.imgur.com/OJPkfZU.jpeg)

**Comment by Thomas-A-Reinert** [comment]
Sorry, can not confirm this. Copied exact above code and have a totally different outcome.
Did you modify anything? Do you use one of holgers Child themes? Have you tried on a blank, non-modified install?

![image](https://user-images.githubusercontent.com/5886977/36914139-96941b74-1e4c-11e8-8ff4-1722f4b48a76.png)

**Comment by holger1411** [comment]
closing this becasue it seems it is casue by customizations
