### ISSUE TITLE
Use Yarn+Webpack

### ISSUE THREAD

**Issue by dillix** [understrap/understrap#536]
May be we should use Yarn+Webpack for compile Bootstrap 4 instead npm+Gulp? BS4 authors already use webpack for production. I can help to make such transition.

**Comment by raisonon** [comment]
Hi Dillix, Anywhere I can learn about the pros/cons about these varying methods?

**Comment by GuerrillaCoder** [comment]
https://buddy.works/blog/webpack-vs-gulp

**Comment by raisonon** [comment]
Cheers for that link @GuerrillaCoder - I can see the benefit of being in sync with BS4 authors, but don't see the benefits of moving to webpack but can see the cons (ie. having to learn another system!).

Maybe I should go learn webpack though! Cheers

**Comment by GuerrillaCoder** [comment]
I am in the same boat.  I have used gulp since it surfaced and feel comfortable with it but a lot of project I work on now use webpack.  I think for stuff like minification/bundling webpack is simpler but I have modified my gulp setup so I can use live-reload with remote server while coding which I haven't figured out how to do with webpack so I think for me if I switch to webpack I will still need gulp.  I do lose a lot of time to messing around with my gulp config from time to time though so maybe webpack would be a way to keep the gulp file a bit leaner? I am not sure.

**Comment by GuerrillaCoder** [comment]
This is a better article https://www.toptal.com/front-end/webpack-browserify-gulp-which-is-better

**Comment by MaximOrlovsky** [comment]
Vote for this feature

**Comment by 0dp** [comment]
I would really like to see some justifications and healthy debate from the community why such a switch is important, and what we will gain from such a switch. So here I go 😄 

## YARN VS. NPM
[Insert marketing blurb here]
Competition is healthy and it promotes change and innovation. Hence YARN and NPM will keep pushing each other forward 👍.   

_YARN is faster than NPM_, but NPM CI is faster than YARN, and soon pnpm will catch up and then some new kid is gonna disrupt the eco system [...and so on, and so forth...]

**Question:** _Why is a switch from npm to yarn needed, what do we actually gain?_ 

## GULP VS. WEBPACK
The same goes for these two, a bundler that runs tasks vs. a task runner that bundles.

**Question:** _Why is a switch from gulp to webpack needed, what do we actually gain?_

**Comment by DonCream** [comment]
I say yes to webpack, but no to yarn, even tho I use yarn in my projects...
webpack is better at handling js, but yarn can be unstable when moving between projects...

https://mixmax.com/blog/to-yarn-and-back-again-npm

**Comment by 0dp** [comment]
But @DonCream are you saying that we dont't handle javascript well right now? Where do you see improvements to be made, in the way we handle javascript?
How would javascript be handled better with webpack compared to what we do now?

**Comment by GuerrillaCoder** [comment]
Just read this article while was pretty nice: https://blog.andrewray.me/webpack-when-to-use-and-why/

So it seems webpack adds dependency graph that allows you to require any static file, not just .js files.  How that plays out into a practical benefit I am not sure yet.  Maybe it gives a more pluggable nature to the code where you can add module and it handles all the assets for that module not just the js.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
