### ISSUE TITLE
CriticalCSS + Gulp

### ISSUE THREAD

**Issue by axlright** [understrap/understrap#538]
Since this Monday seems to be a time when people are posting new workflow ideas ... here's another.

I apply CriticalCSS + move the full css file into the footer on all client projects using UnderStrap + UnderStrap Child themes in order to speed up page load times. My workflow is pretty good but too many parts of it are manual. Whenever we make a stylesheet update that affects above-the-fold content, or whenever the Bootstrap framework gets updated, we have to regenerate all the CriticalCSS.

Thinking of creating a Gulp workflow using the [Filament Group's CriticalCSS](https://github.com/filamentgroup/criticalCSS) to automate the process.

Anyone else using CriticalCSS? I'm happy to share the process we create. If anyone else wants to collaborate, let me know and I can make a public repository.

Thanks!

-Alex

**Comment by shansmith01** [comment]
I would be really interested to see how you are doing that @axlright. I tried but gave up part way through

**Comment by axlright** [comment]
My workflow right now uses two things - the [Autopimize plugin](https://www.google.com/search?q=autoptimize&oq=autoptimize&aqs=chrome..69i57j69i60l3j0l2.3041j0j7&sourceid=chrome&ie=UTF-8) (amazing) and a [free online CriticalCSS generator](https://jonassebastianohlsson.com/criticalpathcssgenerator/) by @pocketjoso (also amazing).

I create a .css file and then manually use the above linked online CriticalCSS generator to generate a full criticalcss file for every iteration of every different template for the website. I then minify that file which removes all duplicate css rules and I copy that minified css file into Autoptimize and then set Autoptimize to put the full css in the footer.

You can see an example of it on my [portfolio website](https://alexwright.net/). If you look at the source, all the criticalcss is in the header and the full css is in the footer and it gets a 98/100 on PageSpeed mobile.

I'd like to move this to a Gulp workflow using the Filament Group local script to automate the process - put in a list of local development URLs that correspond to the different iterations of every different template and then run `gulp criticalcss` to generate the minified css to put into Autoptimize or to put into the header manually (and manually move the full css file into the footer).

**Comment by shansmith01** [comment]
Yeah I have used a similar flow before but would love to see this in gulp. It would be great to see the code injected into the head automatically at the end of the process. I would think that everyone in the community is into a super quick site out of the box

**Comment by axlright** [comment]
Cool - thanks @shansmith01. I'll probably always use Autoptimize because it does a terrific job at html minification (better than Cloudflare) and also collects and minifies js scripts into the footer and also caches it all. But I think a gulp workflow could easily accommodate both.

I'll get some work done locally and make a public repository if anyone else wants to contribute.

**Comment by pocketjoso** [comment]
Note that my free online generator uses [penthouse](https://jonassebastianohlsson.com/criticalpathcssgenerator/) under the hood, which is in my opinion a much better critical css generator than the alternatives, as it is regularly maintained and produced both more accurate and much faster results. (The free generator does make it's request via my paid https://criticalcss.com service, which also has fully automated critical css integrations for wordpress)

**Comment by axlright** [comment]
Thanks @pocketjoso - I should have given a shout to your https://criticalcss.com service. Thanks for all the work you put into both.

**Comment by axlright** [comment]
I have a question now that you're here @pocketjoso - for a WordPress workflow in which a project has 5-100 pages based on 2-10 "templates" (same css per page), do you think it's better to generate one master criticalcss file and put it in the `<head>` of **every** page or use php if statements in the `header.php` to insert individual css files for each template using something like <?php get_template_part( 'loop-templates/criticalcss', 'template1' ); ?> that has the criticalcss for that page in `loop-templates/criticalcss-template1.php`?

How do you go about dealing with lots of css from lots of different templates?

**Comment by axlright** [comment]
Okay @shansmith01 and anyone else who is interested, with the help of some awesome people on my team, I got the start of a good working criticalcss workflow. I took the advice of @pocketjoso and used Penthouse for criticalcss generation.

Step1: Add this to your gulpfile's requirements:
```var penthouse = require("penthouse");
var fs = require('fs');
var urlList = require('./urlList.json');```

Step2: Add this to your gulpfile (edit as necessary, this has all the optional parameters, plus I use a different name for the source css file)
```
// Run:
// gulp criticalcss
// 
gulp.task('criticalcss',function(){
  urlList.urls.forEach(function(item,i){
    penthouse({
        url: item.link,       // can also use file:/// protocol for local files
        //cssString: 'body { color; red }', // the original css to extract critcial css from
        css: './css/style.min.css',      // path to original css file on disk

        // OPTIONAL params
        width: 1300,                    // viewport width
        height: 900,                    // viewport height
        keepLargerMediaQueries: false,  // when true, will not filter out larger media queries
        forceInclude: [ // selectors to keep
          '.keepMeEvenIfNotSeenInDom',
          /^\.regexWorksToo/
        ],
        propertiesToRemove: [
          '(.*)transition(.*)',
          'cursor',
          'pointer-events',
          '(-webkit-)?tap-highlight-color',
          '(.*)user-select'
        ],
        timeout: 30000,                 // ms; abort critical CSS generation after this timeout
        pageLoadSkipTimeout: 0,         // ms; stop waiting for page load after this timeout (for sites with broken page load event timings)
        maxEmbeddedBase64Length: 1000,  // characters; strip out inline base64 encoded resources larger than this
        userAgent: 'Penthouse Critical Path CSS Generator', // specify which user agent string when loading the page
        renderWaitTime: 100,            // ms; render wait timeout before CSS processing starts (default: 100)
        blockJSRequests: true,          // set to false to load (external) JS (default: true)
        customPageHeaders: {
          'Accept-Encoding': 'identity' // add if getting compression errors like 'Data corrupted'
        },
        strict: false,                  // set to true to throw on CSS errors
        screenshots: {
          // turned off by default
          // basePath: 'homepage', // absolute or relative; excluding file extension
          // type: 'jpeg', // jpeg or png, png default
          // quality: 20 // only applies for jpeg type
          // -> these settings will produce homepage-before.jpg and homepage-after.jpg
        },
        puppeteer: {
          getBrowser: undefined,        // A function that resolves with a puppeteer browser to use instead of launching a new browser session
        }
    })
    .then(criticalCss => {
        // use the critical css
        fs.writeFileSync('./'+item.name+'.php',"<?php ?><style>"+ criticalCss + "</style><?php ?> ");
    })
    .catch(err => {
        // handle the error
    })
  })
})
```
Step 3: Add a file called urlList.json in the root directory with this content (modified for each install - one set of link and name per template file)
```
{
  "urls": [
    {
      "link": "https://local-alexwright.net/",
      "name": "criticalcss/home"
    },
    {
      "link": "https://local-alexwright.net/take-the-limits-off/",
      "name": "criticalcss/portfolio-project"
    },
    {
      "link": "https://local-alexwright.net/free-seo-analysis/",
      "name": "criticalcss/seo-analysis"
    },
    {
      "link": "https://local-alexwright.net/free-seo-analysis-report/",
      "name": "criticalcss/seo-analysis-results"
    },
    {
      "link": "https://local-alexwright.net/pay/",
      "name": "criticalcss/pay"
    },
    {
      "link": "https://local-alexwright.net/charge/",
      "name": "criticalcss/charge"
    }
  ]
}
```
Step 5, run `gulp criticalcss` and watch for those php files listed above to get made.

Step 6: Add something like this to your header.php (also could do in functions.php using `wp-head`)
```
<?php if ( is_front_page() ) :
	get_template_part( 'criticalcss/home' ); 
		elseif ( in_category( 13 ) ) :
	get_template_part( 'criticalcss/portfolio-project' );
		elseif (is_page ( 382 ) ) :
	get_template_part( 'criticalcss/seo-analysis' );
		elseif (is_page ( 384 ) ) :
	get_template_part( 'criticalcss/seo-analysis-results' );
		elseif (is_page ( 257 ) ) :
	get_template_part( 'criticalcss/seo-pay' );
		elseif (is_page ( 269 ) ) :
	get_template_part( 'criticalcss/seo-charge' );
		else :
		endif ?>
``` 
I still use Autoptimize to push the full css file into the footer, so if you don't do that, you'll need to push your full css into the footer which is harder than it should be.

Feedback welcome! Working great for me.

**Comment by shansmith01** [comment]
That looks neat @axlright, I will have a play with it tomorrow when I'm back in the office. 

On another CSS related note, do you think that something like gulp-uncss would add value?

**Comment by pocketjoso** [comment]
@axlright Thanks for the kind words.
You can only re-use the same critical css between pages where _all_ critical elements (above the fold) are shared. This generally means you _cannot share critical css between individual pages_. However sharing between page templates is more achievable, but not something that can always be relied on out of the box with no further configuration. Penthouse has the `forceInclude` option with which you can add in some extra css (via css selector patterns) to a critical page template css file, for elements that are only present on some page instances using that template (ones that the generation were not run towards).

**Comment by axlright** [comment]
Awesome @shansmith01 

I'd love to hear a bit about your WP-Rocket workflow. I'm writing a lot about speed improvements on my blog and it'd be cool to know about your process.

Thanks!

**Comment by Thomas-A-Reinert** [comment]
In my opinion that cannot be done, because ALL WP-Templates share the same CSS. 

And yes, I TOTALLY feel you - whenever you have a site where miliseconds of loading/rendering time play a role - optimize it! But in 99% of all cases you´ll have small to medium customers and they will never ever know what you´re talking about. And most sure not pay for it. So better leave that out of the "standard Dev" of UnderStrap.

If they really want that - they´ll pay for it. And will have someone to accomplish that task.

I get UnderStrap-based sites loading within under 2secs (without caching, just some adjustments to .htaccess), so i´m good to go.

Closing this issue for housekeeping. (To not make it public anymore)
But if you got any updates - i´m really willing to learn!

**Comment by axlright** [comment]
I fully support this issue being closed. For posterity - we documented our [Critical CSS workflow here](https://alexwright.net/web-design-secrets/how-to-use-critical-css/) if anyone wants to take a look. It's a work in progress of course. What isn't!
