### ISSUE TITLE
Class 'WP_Bootstrap_Navwalker' not found

### ISSUE THREAD

**Issue by biffwebsterjr** [understrap/understrap#540]
When I update to v 0.7.0 via WordPress updates, I get the following fatal error:

`Fatal error: Class 'WP_Bootstrap_Navwalker' not found in /code/wp-content/themes/amstedsf/header.php on line 73 Call Stack: 0.0028 265584 1. {main}() /code/index.php:0 0.0029 266016 2. require('/code/wp-blog-header.php') /code/index.php:17 0.2915 9893744 3. require_once('/code/wp-includes/template-loader.php') /code/wp-blog-header.php:19 0.2964 9959752 4. include('/code/wp-content/themes/amstedsf/page-home.php') /code/wp-includes/template-loader.php:74 0.2964 9959784 5. get_header() /code/wp-content/themes/amstedsf/page-home.php:7 0.2965 9960368 6. locate_template() /code/wp-includes/general-template.php:41 0.2965 9960600 7. load_template() /code/wp-includes/template.php:647 0.2967 9974256 8. require_once('/code/wp-content/themes/amstedsf/header.php') /code/wp-includes/template.php:688`

Was that class changed somewhere along the line? I'm updating from 0.6.5 and using [Understrap Child](https://github.com/holger1411/understrap-child) as my child theme.

Thanks.

**Comment by crstnio** [comment]
Hey @biffwebsterjr,

did you change the `header.php` in your child theme? Then you should compare yours with the new version.

The class name should be `understrap_WP_Bootstrap_Navwalker()`.

**Comment by biffwebsterjr** [comment]
@crstnio,

Yeah, I added a customization for what to do if there is no custom logo.

`<a class="navbar-brand col-8 col-md-3" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>"
				   title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>">
					<img src="<?php echo get_stylesheet_directory_uri() . '/images/logo-site.png'; ?>" alt="sit logo" />
				</a>`

The only thing I really did was add Bootstrap classes to the anchor tag.

**Is there a better way to do that?** I'm all for keeping things clean so I can update Understrap more easily.

Thanks!

**Comment by axlright** [comment]
@biffwebsterjr it doesn't come up a lot that core php files have elements that get updated, but it does happen. I think the best workflow is to keep an eye out for things that change. If you add `define('WP_DEBUG', true);` to your wp-config.php file, you can see php errors with messages that give helpful clues about what's not working. Don't know if that's helpful. Hope so!

**Comment by crstnio** [comment]
It is always a good idea to read changelogs – which ideally have the updated files listed – before updating, if you have modified template files and/or overwritten functions in your child theme.

**Comment by terriann** [comment]
I got the same error (with `WP_DEBUG` enabled) in a fresh install of WordPress and UnderStrap 0.7.0 using the [Draft UnderStrap Child Theme](https://understrap.com/understrap-child-themes/) 0.2.2 (:octocat: holger1411/draft-understrap-child)

I checked to see, and the [demo site](https://understrap.com/demos/draft/) for that theme is using the UnderStap parent theme version 0.5.4 whereas I was attempting to use 0.7.0 (latest).

Guess this bug exists in that child theme too.

**Comment by holger1411** [comment]
Hi!
Yes, the function was renamed to "understrap_WP_Bootstrap_Navwalker".
The WP repo team forced us to use a unique prefix.

Means if the header.php in your child theme looks for "WP_Bootstrap_Navwalker" while the parent comes with a function called "understrap_WP_Bootstrap_Navwalker" only you will receive an error.

Search for:

`						'walker'          => new WP_Bootstrap_Navwalker(),`
in your child theme and replace it with :	

`						'walker'          => new understrap_WP_Bootstrap_Navwalker(),`

**Comment by crstnio** [comment]
@holger1411

What about namespacing your code? Would  prevent prefixing every function.

**Comment by holger1411** [comment]
Closing this because: Seems to be fixed.
If not feel free to reopen!

**Comment by mrsof** [comment]
The name of the function is **[Understrap_WP_Bootstrap_Navwalker](https://github.com/understrap/understrap/blob/master/inc/class-wp-bootstrap-navwalker.php)**

**Comment by violetweb** [comment]
Actually -- FYI, the new "draft Demo Child theme' I downloaded from your website, has the omission!.  I downloaded from here : https://understrap.com/understrap-child-themes/

**Comment by rtxanson** [comment]
Same, omission is still present today.
