### ISSUE TITLE
Make ALL functions replaceable / PROPER child theme ability

### ISSUE THREAD

**Issue by ginsterbusch** [understrap/understrap#550]
After just a few glances, I see that the mistakes of the ancestor project (_s) are being continued ... thus: Please make sure that ALL functions etc. are replaceable. This is rather easily done with adding a `if( function_exists() )` block around each function, and do the same with classes.

This would ensure that the theme is TRUELY supporting child themes, and not just on the surface.

Concerned files:

- inc/editor.php
- inc/jetpack.php
- inc/template-tags.php
- inc/woocommerce.php
- inc/wpcom.php
- inc/custom-components.php

Thanks in advance,
cu, w0lf..

**Comment by roman-soerensen** [comment]
I agree totally! That would be better, than overwriting the functions by using the priority arg.
Please check and change all files in the 'inc' folder.

Cheers, Roman

**Comment by axlright** [comment]
Closing this issue as it was patched in PR #619 

Comment if issues persist.
