### ISSUE TITLE
Some issues I found

### ISSUE THREAD

**Issue by DumboJetEngine** [understrap/understrap#552]
Hello.
While trying to use this theme, I came across some issues:

1. It seems that there are two versions of the file `pagination.php`. I am not sure why this happens, but it's weird and it looks like leftovers. These are the files:
understrap\inc\pagination.php
understrap\global-templates\pagination.php

---

2. While using the `understap-child` theme, I had to modify the file `understrap-child/sass/assets/understrap.scss` from this:
```
@import "../../src/understrap/understrap/understrap";
```
...into this (so that the SASS can be compiled):
```
@import "../../sass/understrap/understrap/understrap";
```
I am using this file as a compilation root:
```
understrap-child/sass/child-theme.scss
```

There were some weird problems with `contact-form7.scss` not compiling, but that looked weird since the SASS code seemed fine to me. Might be an outdated SASS compiler or something... Anyway, I have removed that file for now....

---
3. The pagination UI is not very sound or at least it looks weird (I am currently working on a fix):

![image](https://user-images.githubusercontent.com/8676903/36122287-7ab4c524-1051-11e8-96b0-47fe98d1c47f.png)

**Comment by holger1411** [comment]
Hi @DumboJetEngine !
Would be great if you could spend some time on the pagination issue.
Seems that both pagination.php files where added/edited with commits and that that caused some trouble.

To 2:
The correct @import path should be:
`@import "../src/sass/understrap/understrap/understrap"; `
Like in this file: https://github.com/holger1411/understrap-child/blob/master/sass/child-theme.scss#L3

**Comment by 0dp** [comment]
I'm looking into adapting `get_the_posts_pagination();`

**Comment by 0dp** [comment]
I've created a branch in my fork (not sure how I can create a branch here) 
https://github.com/0dp/understrap/tree/pagination
That implements what I believe is a more current pagination. Please note I still consider this a P.O.C.
There is definitely a few things that can be improved upon like custom arrows

**Comment by holger1411** [comment]
@0dp : I opened a pull request and will test it:
https://github.com/understrap/understrap/pull/616

**Comment by BenAttenborough** [comment]
I've noticed that pagination with dots is broken, in that it doesn't take into account the ellipsis when working out the page number on the pagination:

![screen shot 2018-05-09 at 16 28 15](https://user-images.githubusercontent.com/8101421/39823941-0804318e-53a6-11e8-9852-0922381737ad.png)
(understrap_pagination() above, paginate_links() below)

The ellipsis above represent both 2 and 3, but the element will be counted as 1.

So the lines:
```
$i = 1;
foreach ( $links as $link ) { ?>
    <li class="page-item <?php if ($i == $args['current']) { echo active; }; ?>">
	<?php echo str_replace( 'page-numbers', 'page-link', $link ); ?>
    </li>
<?php $i++;} ?>
```
I believe result in each item being thought of as a single page number, but the ellipsis can accommodate a number of page numbers. Looking at the way wp core `paginate_links` works, it looks as though this issue is taken care of.

I would think a solution would be either to get the page number directly from the $link string or to calculate how many items are in the ellipsis and add this to the index $i.

**Comment by BenAttenborough** [comment]
Something like this would seem to work?

```
<?php
$i = 1;
foreach ( $links as $link ) { ?>
	<?php $offset = max( 0, ( $args['current'] - ( $args['mid_size'] + 3 ) ) ); ?>
	<li class="page-item <?php if ( $i == $args['current'] - $offset)  {
		echo 'active';
	}; ?>">
		<?php echo str_replace( 'page-numbers', 'page-link', $link ); ?>
	</li>

	<?php $i ++;
} ?>
```

It feels a little messy but seems to work

**Comment by 0dp** [comment]
Just referencing #663

**Comment by 0dp** [comment]
Hey @BenAttenborough 

> I've noticed that pagination with dots is broken, in that it doesn't take into account the ellipsis when working out the page number on the pagination:

Yeah you're right, and also it counted the prev and next arrows as part of the pages.
I couldn't get your code to produce a different result from the current.

But could I get you to try this instead?

```
<?php
/**
 * Pagination layout.
 *
 * @package understrap
 */

if ( ! function_exists ( 'understrap_pagination' ) ) {

    function understrap_pagination($args = [], $class = 'pagination') {

        if ($GLOBALS['wp_query']->max_num_pages <= 1) return;

        $args = wp_parse_args( $args, [
            'mid_size'           => 2,
            'prev_next'          => true,
            'prev_text'          => __('&laquo;', 'understrap'),
            'next_text'          => __('&raquo;', 'understrap'),
            'screen_reader_text' => __('Posts navigation', 'understrap'),
            'type'               => 'array',
            'current'            => max( 1, get_query_var('paged') ),
        ]);

        $links = paginate_links($args);

        ?>

        <nav aria-label="<?php echo $args['screen_reader_text']; ?>">

            <ul class="pagination">

                <?php

                $i = 1;

                    foreach ( $links as $key => $link ) { ?>

                        <li class="page-item <?php if (strpos( $link, 'current' ) !== false) { echo 'active'; }; ?>">

                            <?php echo str_replace( 'page-numbers', 'page-link', $link ); ?>

                        </li>

                <?php $i++;} ?>

            </ul>

        </nav>

        <?php
    }
}

?>
```

**Comment by BenAttenborough** [comment]
Yes that works, although you no longer need the $i variable since it is no longer used. I might hazard to tidy it up like this:
```
<?php
/**
 * Pagination layout.
 *
 * @package understrap
 */

if ( ! function_exists( 'understrap_pagination' ) ) {

	function understrap_pagination( $args = [ ], $class = 'pagination' ) {

		if ( $GLOBALS['wp_query']->max_num_pages <= 1 ) {
			return;
		}

		$args = wp_parse_args( $args, [
			'mid_size'           => 2,
			'prev_next'          => true,
			'prev_text'          => __( '&laquo;', 'understrap' ),
			'next_text'          => __( '&raquo;', 'understrap' ),
			'screen_reader_text' => __( 'Posts navigation', 'understrap' ),
			'type'               => 'array',
			'current'            => max( 1, get_query_var( 'paged' ) ),
		] );

		$links = paginate_links( $args );

		?>

		<nav aria-label="<?php echo $args['screen_reader_text']; ?>">

			<ul class="pagination">

				<?php foreach ( $links as $key => $link ) : ?>
					
					<li class="page-item <?php echo strpos( $link, 'current' ) ? 'active' : '' ?>">
						<?php echo str_replace( 'page-numbers', 'page-link', $link ); ?>
					</li>
					
				<?php endforeach; ?>

			</ul>

		</nav>

		<?php
	}
}

?>
```
Thanks!

**Comment by 0dp** [comment]
#668

**Comment by BobTokyo** [comment]
Don't know if this is related, but today I updated to the new 0.8.2 version.  Immediately my site broke ... the only thing that I could render in both the front and back end was:
Parse error: syntax error, unexpected '[' in /home/content/93/10104893/html/successjp/wp-content/themes/understrap/inc/pagination.php on line 9
I haven't updated the theme in awhile so what I was using was 0.6.6.
Luckily still had this version on backup, so uploaded (ftp) it (version 0.6.6) and replaced 0.8.2.  Site is now running again.  Is there a problem with 0.8.2?  I have a child theme installed, but it works perfect on 0.6.6.

**Comment by 0dp** [comment]
@BobTokyo could you please post the lines 6-11 from understrap/inc/pagination.php please?
Also try and change `$args[ ],` to `$args,` on line 10?

**Comment by Thomas-A-Reinert** [comment]
That issue has definitely been fixed by now - at least according to my really dense testing ;)

So i´ll close that issue.

@BobTokyo I´ll consider your post kinda "issue-highjacking". Please open up your own issue following the issue-template and guidelines, otherwise we cannot help you.
