### ISSUE TITLE
Hero not appearing

### ISSUE THREAD

**Issue by sbdm05** [understrap/understrap#557]
Thanks to all the contributors of this great theme ! I just have to say Hero Section could not appear on homepage. Home is set up as homepage. I clearly see the get_template_part ('global-templates/hero') in index.php. I added an image in the dashboard>widget hero static. Any idea ? thank you! (sorry I left the same message on an other post)

**Comment by Mandlee** [comment]
I am having a same issue. Any idea? Thank you

**Comment by ceesco53** [comment]
when you submitted your comments were you both trying to use a page as the homepage?

**Comment by 0dp** [comment]
@sbdm05, if you take a look at the conditional tag right before the `get_template_part ('global-templates/hero')` you'll see `is_home()`. in the docs found [here](https://developer.wordpress.org/reference/functions/is_home/) you can see that it checks if... the query is for the blog homepage.

**Comment by Mandlee** [comment]
Thanks guys! @ceesco53 @0dp That's working well!

**Comment by Thomas-A-Reinert** [comment]
Fixed? If so - please close this thread. Thanks in advance!
