### ISSUE TITLE
Deprecation Notices in cart.php

### ISSUE THREAD

**Issue by 0dp** [understrap/understrap#562]
Since Woocommerce v. 3.3.0
`WC()->cart->get_remove_url` has been deprecated and replaced by `wc_get_cart_remove_url`
`WC()->cart->get_item_data` has been deprecated and replaced by `wc_get_formatted_cart_item_data`

#561

**Comment by ZacharyElkins** [comment]
There's a lot in the new WooCommerce templates that have changed. I'm wondering if this is upcoming or should I spend some time and update them?

**Comment by typeplus** [comment]
I have an update to include all of these which I have been testing for about a week across 5 or so sites.  Ran into quite a few issues so have been testing thoroughly before pull request.

**Comment by 0dp** [comment]
I haven't seen any other deprecation notices, and haven't investigated any further into changes. I merely saw this and pushed a patch.

**Comment by drs-nyc** [comment]
Woocommerce is changing their approach to supporting custom templates. https://woocommerce.wordpress.com/2017/12/09/wc-3-3-will-look-great-on-all-the-themes/

There are over 19 files that are not in sync with the current 3.3.x release. Is there a reason why the Woocommerce template folder is included? From a diff it appears that most of the changes are made to support the l10n features which would be handled by Woocommerce rather than the theme textdomain.

**Comment by dairc** [comment]
I'm awaiting this fix too. Looks like some of you are working on it - always highly appreciated with this community :) If there is anything I could to help anyone let me know. I've made considerable changes and updated to all latest on a local build and want to deploy it soon and just need to do a little more on the checkout experience, so this is really important to me. Thanks.

**Comment by typeplus** [comment]
Will have it done this time tomorrow! Ran into so many issues but they are clean now 👍

**Comment by GuerrillaCoder** [comment]
Should mark this assigned if it's being worked on

**Comment by ZacharyElkins** [comment]
This all should be resolved. 
https://github.com/understrap/understrap/commit/5eae85e137614ccdfb93fc82eaebc1874fdf66bc

And there is a reason for using the understrap as the text domain, @holger1411 can explain better.

**Comment by 0dp** [comment]
Closing this, as it seems resolved
