### ISSUE TITLE
gulp copy-assets don't work

### ISSUE THREAD

**Issue by fcojgodoy** [understrap/understrap#568]
In a flesh installation I modify `gulpfile.js` like this:
```
gulp.task('scripts', function() {
    var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        paths.dev + '/js/parallax.min.js'
    ];
...
```
and, in `copy-assets` task:
```
// _s JS files into /src/js
    gulp.src(paths.node + 'parallax-js/dist/parallax.min.js')
        .pipe(gulp.dest(paths.dev + '/js'));

// _s JS files into /js
    gulp.src(paths.node + 'parallax-js/dist/parallax.min.js')
        .pipe(gulp.dest(paths.js + paths.vendor));
```

Then I run `gulp copy-assets` with no error but with no `parallax.min.js` in `./src/js` or `./js` folders.

What am I doing wrong?

Thanks to all the contributors!

P.D: Previously I install parallax.js package with `npm i -s parallax.js` and I check it is within `node_modules` folder.

**Comment by fcojgodoy** [comment]
Hi!
The path is ok. The package name is parallax.js but the folder is parallax-js. I checked wth several packages.
If I remove the `var stream = ...` and `return stream` in the copy-assets task, the files are copied to the corresponding folders. @

**Comment by 0dp** [comment]
I can confirm that `copy-assets` does not copy all assets, and that removing  second `var stream` and first `return stream` "fixes" the task.

**Comment by 0dp** [comment]
@holger1411 @Thomas-A-Reinert please close
