### ISSUE TITLE
A little typo in FR translation

### ISSUE THREAD

**Issue by MarieComet** [understrap/understrap#569]
Hi,
there is a little mistake in the FR translation for this string : 
'Sorry, but nothing matched your search terms. Please try again with some different keywords.'
which translated in French with : 'Désolé, rien ne correspond à votre recherche. Veuillez réessayez avec d'autres termes.'
The correct translation should be : 
'Désolé, rien ne correspond à votre recherche. Veuillez réessaye**r** avec d'autres termes.'
in `content-none.php`

Thanks !

**Comment by Thomas-A-Reinert** [comment]
Hey Marie, would you be able to submit a pull request? That would be awesome!

**Comment by MarieComet** [comment]
Hi Thomas, of course, see https://github.com/holger1411/understrap/pull/573
