### ISSUE TITLE
Help needed!

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#570]
More than 1300 stars, 1000+ commits and more than 50 contributors!
UnderStrap becomes more and more mature and a bigger project.
That are great news!

![Help needed](https://media.giphy.com/media/oGzFZek2lszlK/giphy.gif)
But I don´t have enough time to monitor all issues here and to test and control all pull request, feature requests etc. Thats sad! I know ... here are a lot of good people sending in feedback, suggesting changes, idears and so on.

So my idea is to find some "component owner" who keep an eye on a certain part of UnderStrap.
Maybe for small parts (like on specific translation file) or bigger parts (like the WooCommerce integration).

**So here is my question: Is any one interested in becoming an UnderStrap Component Owner?**

No fear: It did not mean you have to do everything by your own. Just keep an eye on issues and discussions on your specific topic. Checking and merging pull requests and ask for help if needed.
And you get push access.

Here are some ideas for specific components:
- Responsivness
- ~~Accessibility~~ :tada: @Thomas-A-Reinert
- Translation (genereal)
-- English
-- ~~German~~ :tada: @Thomas-A-Reinert
-- Swedish 
-- ~~French~~ :tada: @MarieComet
-- ~~Danish~~ :tada: @0dp
-- etc.
- ~~Bootstrap integration~~ :tada: @axlright
- ~~Font Awesome integration~~ :tada: @0dp
- Gutenberg integration
- ~~Woocommerce integration~~ :tada: @ZacharyElkins @GuerrillaCoder
- ~~Documentation~~ :tada: @axlright @ZacharyElkins
- Code quality/tests
- Performance
- WordPress best practices (based on Underscores)
- WordPress components like:
--Pagination
--Search
--Menu
etc.
Just ideas. 
A component can be anything in any size. Its up to you if you are interested in a certain part.
Just comment below.

**Comment by axlright** [comment]
Congratulations @holger1411. With the amount of client work you crank out, it's understandable to hear "Oh my god I need help."

I'd enjoy contributing to Bootstrap integration and Documentation.

Let me know how to help!

-Alex

**Comment by Thomas-A-Reinert** [comment]
Count me in for German translation and accessibility standards whenever I find the time.

**Comment by ZacharyElkins** [comment]
I would be interested in WooCommerce Integration, and help review documentation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Thomas-A-Reinert** [comment]
Sidenote: We should also make Gutenberg-compatibility a top-ranking issue! Even if I didn´t try it yet, nor that I know how UnderStrap would maybe affect it. The following article may be helpful (honestly: didn´t read it yet), in case this is just "a note to self"  ;) https://themeshaper.com/2018/02/15/styling-themes-for-gutenberg/

**Comment by Thomas-A-Reinert** [comment]
Closed a whole bunch of Issues that seemed to be fixed. Answered some and put some new flags on others to enhance clarity. Would be nice if other collaborators would follow the same standards.

**Comment by axlright** [comment]
What does it take to be a collaborator to close threads / perform other maintenance on issues? Happy to help.

**Comment by MarieComet** [comment]
Hi, happy to use this theme for a while now, I would be happy to help, why not the French translation / WooCommerce / Gutenberg (already tested it and seem works well).
Let me know.

**Comment by 0dp** [comment]
Hi @holger1411  this is top nodge info. I'm here all the time so count me in, where ever you seem fit 👍

**Comment by GuerrillaCoder** [comment]
I built a WooCommerce theme using Understrap so wouldn't mind helping out with WooCommerce

**Comment by GuerrillaCoder** [comment]
Have you outlined a process for pull requests?  How do I know which change request I should work on? Is there someone responsible for assigning?

**Comment by Thomas-A-Reinert** [comment]
Hi all! Let me thank you all first for wanting to support UnderStrap!

I mentioned the need to delegate some of the tasks in an email to holger last week - so I guess I am responsible for starting the whole thingie :)

Unfortunately, we have not just yet considered on how to set up a transparent and optimized workflow.  At least none I would know about, actually. But hey, this is not time-critical at all, is it?

For the moment it´s just good to know that there are people willing to dedicate some time to improve UnderStrap. Let some time pass and I´m sure we´ll find a good solution. Better than to rush one's fences, right? But I hope I can also speak for holger: We´re open for any suggestions!

My suggestion would be to open another "development"-branch in which to merge pull requests. These would have to be carefully tested before being deployed to the "master"-branch. Personally, I´d like to see the same for "specials" like WooCommerce that maybe need deeper testing and are not really inflicting the "basic theme".

@GuerrillaCoder : As a Collaborateur I´m not able to assign anyone to anything, that has to be done by holger, I guess.

**Comment by holger1411** [comment]
Management/delegation options are very limited on personal accounts here.
Maybe its a good idea to move all projects to: 
https://github.com/understrap
So we have an organization called "UnderStrap" with different projects, teams etc.

I created it a while ago. Just using it for the Docs project. But maybe its time to move all UnderStrap repos to it.

Seems much better for organizing bigger projects.
I never tested it and don´t know how and if it works...but it seems the GitHub organizations are made exactly for projects like Understrap. Open Source repos with more and more collaborators

**Comment by holger1411** [comment]
Moved it...

**Comment by holger1411** [comment]
Now we can create Teams and projects and assign teams to projects etc.
Need to test around a bit but feels much more than a task management tool...

**Comment by holger1411** [comment]
Okay, I build up 5 basic teams here:
https://github.com/orgs/understrap/teams

If you are wanna help you can ask for access.
If needed I will create more teams. 
But it seems that this five teams will cover most of the issues and there can be sub teams

For example Gutenberg is a new WordPress standard, so it might be a sub team of "Accessibility & Quality" which acts a bit as "kitchen sink" team...

**Comment by 0dp** [comment]
I'll definitely wouldn't mind jumping on the font awesome 5 integration and I can provide Danish translation.

**Comment by IngoVals** [comment]
I would be willing to help, but alas I'm new to Wordpress and while I'm interested in code quality and tests I would have to learn the **Travis ci** system to be able to. Maybe best leave that open until I have more experience there ( i'm a fast learner but out of time like everyone ).

One issue I would like to see raised is the child theme as a component, it seems to be lagging behind and changes made to the main theme that are relevant to the child theme also don't make it there. Perhaps someone might take that responsibility.

**Comment by 0dp** [comment]
@IngoVals with our joint effort we will be able to raise the quality to new heights :)

**Comment by holger1411** [comment]
@IngoVals I invited you to join our small but brave UnderStrap team.

**Comment by typeplus** [comment]
Happy to be a part of the team. As per my commit history Woocommerce is my area I use most 👍

**Comment by uitta** [comment]
You can count on me for the italian translation...

**Comment by pattonwebz** [comment]
I can help out with suggestions for WP coding standards and general .org theme best practices. I am in a good position to offer such guidance and an happy to create or review PRs with relation to best practices for WP themes :)

Also maybe I can work on some testing too as I have experience with CI/Travis and with PHPUnit.

**Comment by Thomas-A-Reinert** [comment]
Maybe I was not sufficiently clear before (I really don´t know if that´s the correct term, but I guess you know what I mean..) - but we (I just **can** speak for myself, but as far as I know the others I hope I can speak for them as well) would really love to welcome you aboard!
And no. That´s not because you´re a theme-reviewer. That´s a surplus but..

- It´s because you [provided _really_ great help and took the nav_walker to a next (BootStrap4) level within HOURS](https://github.com/understrap/understrap/pull/647)! Despite kinda "special" requests by me.
- [Because you provided quite some PHPCS fixes totally voluntarily](https://github.com/understrap/understrap/pull/649) (which I didn´t dare to submit, @holger1411 ) that did not have anything to do with the BootStrap NavWalker.

I guess all of us understrap-devs got a pretty good clue about WP-Dev - but we´re more than willing to learn! And sometimes don´t like to read _any_ documentation while a RTFM-Pointer would still be welcome.. ;)

And yes - any TDD can only be helpful to improve UnderStrap!

**Comment by Thomas-A-Reinert** [comment]
@holger1411 - would you please add @pattonwebz to the "Accessibility & Quality" and "Watercooler Team" at least? I´ll close that issue for now, because that should be an internal rather than an openly accessible issue..

**Comment by Thomas-A-Reinert** [comment]
@pattonwebz - Sorry, I cannot add you to any group afaik. That´s up to the project maintainer.
