### ISSUE TITLE
Non-translatable strings / POT-update needed

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#574]
Currently trying to update the german translation.

Found at least _one_ string that is not translatable and will keep my eyes open for others as well.

Example:
Go to Customizer. Check theme layout settings. String "_Set sidebar's default position. Can either be: right, left, both or none. Note: this can be overridden on individual pages._" appears in english.
There is no such string included neither in german .po-file nor in the understrap.pot, though it´s marked as translatable in the code and has the "understrap" text-domain correctly set.

Is there any way to generate a completely new .pot from the available strings and maybe make a diff to the existing .po´s?

As far as I know the commercial version of PoEdit can do that, but I was always too cheap to get one ;)

**Comment by MarieComet** [comment]
Hi Thomas,
About translations in general : I think it will be nice to translate Understrap with GlotPress (https://translate.wordpress.org/projects/wp-themes/understrap).
What do you think ? Actually there is a lot of translations (.po/.mo), but no one in GlotPress.

**Comment by Thomas-A-Reinert** [comment]
You´re absolutely correct, Marie! Also I never ever really cared about it, I know it´s the recommended way these days afaik. I just wonder why GlotPress doesn´t import the .mo files? This would be really helpful, don´t you think? Otherwise we´d need to update two systems, which is a real bummer..

**Comment by MarieComet** [comment]
It seem it's possible to import .po files in GlotPress : https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/#importing-external-files but I never do that myself.
I think theme author on wp.org need to import .po files.
In Translate (GlotPress), there is a Project Translation Editor for each language, so ideally there must be one person for each language who must propose to be PTE of his language.
And if the translation of the theme is managed on Translate there is no more need .mo/.po files in the theme himself.

**Comment by Thomas-A-Reinert** [comment]
Oh, that´s good to know - thanks for the link, Marie!

And that would include another advantage - we could get rid of a lot of strings that are no longer included in UnderStrap (there are quite some).

@holger1411 would you be willing and able to check on GlotPress if you can import the translations? Thanks in advance!

**Comment by MarieComet** [comment]
:+1:  Tell me if you need French PTE, I can ask to my local translation team.

**Comment by Thomas-A-Reinert** [comment]
German formal and informal translations are already complete right now.
The whole topic per se has been internally discussed also.

The official translation project has also been started so i´ll close that for now.
