### ISSUE TITLE
Pull requests failing travis.ci checks

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#577]
Hi all - all pull requests seem to fail travis.ci checks. See https://github.com/holger1411/understrap/pulls

Same goes for https://travis-ci.org/holger1411/understrap/builds/348143609?utm_source=github_status&utm_medium=notification when I visit the travis-ci.org site. But when I click the "Requests"-button, all lights turn green. Anyone deep enough into travis-ci to give me hint what the problem could be?

Sidenote: Read various posts on the error - just from today. Seems to work for some, for others still not. Problem is that some of those pull requests are way older, so I´m not sure what the problem could be.

**Comment by 0dp** [comment]
#560

**Comment by holger1411** [comment]
Close this because of #560
