### ISSUE TITLE
Set up clean goals for UnderStrap 1.0 release

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#583]
We need some clean goals to put UnderStrap 1.0 on a solid foundation.
So here are my toughts on going from beta to release status:

**Main goals are:** Make it more solid, less complexitiy, more maintainability, lesser bugs, better performance, more compatibility with BS4 core and WordPress core

That includes (for examples):
- Gutenberg integration
- Remove anything which is not neccessary. UnderStraps main audience are theme developers, not end users.
Which feature is really needed by this audience?
- Full and better docs for developers. Explaining all gulp tasks etc. More examples
- Check for WordPress best practices (from underscores starter theme)
- Improve code quality and accessibility
- Comment code
- translate UnderStrap on translate.wordpress.org
- Keep child theme up to date with parent theme changes

Feel free to comment here if you have own ideas

I will use this issue as starting point to create to-dos for the UnderStrap 1.0 project here:
https://github.com/orgs/understrap/projects/1

**Comment by MarieComet** [comment]
What do you think about adding "translate Understrap on translate.wordpress.org" to the To-do list ? 
Mentionned in https://github.com/understrap/understrap/issues/574

**Comment by holger1411** [comment]
@MarieComet : Why not? Do you have any experience with it? Never really checked translate.wordpress.org before...
But there is alreay a UnderStrap page:
https://translate.wordpress.org/projects/wp-themes/understrap

**Comment by 0dp** [comment]
@holger1411 check out @understrap/translation-team we already have initial steps to get started translating outlined. I tried it out for the first time last night, and it's really easy to translate. A feature I really liked was the ability to check how core, and other themes and plugins have chosen to translate a specific string, so strings are translated the same across the whole eco system. 👍

**Comment by MarieComet** [comment]
> A feature I really liked was the ability to check how core, and other themes and plugins have chosen to translate a specific string
That's exactly the point of translate.wp.org :smiley: !
However, be careful when translating, there are typographical rules to respect (at least in French like space nonecables, etc.) you should inquire with your local team for more infos about this.

**Comment by 0dp** [comment]
You should add that to the FAQ @MarieComet :)

**Comment by Thomas-A-Reinert** [comment]
@holger1411 : PLEASE add the existing translations! And do it ASAP before anything else so that the translation team can get to work.

@ rest of the team: PLEASE DO NOT contribute to GlotPress until that has been done. Because: not neccessary - you´ll do an invaluable amount of additional work. In worst case - your work will be overwritten by holger importing the existing .po files. That´s why.

So @holger1411 please make that a TOP priority over everything else please, okay?

**Comment by Thomas-A-Reinert** [comment]
@holger again: Yeap, there´s that page with EVERY project. But there is NONE of the already .po-included translations embedded, you see? German is translated by 100% through my last commit. Can´t see that though. And that´s a no-go. No need to start for anyone from zero-on. That´s simply not efficient. So please give importing the existing files a go, okay?

**Comment by holger1411** [comment]
@Thomas-A-Reinert Okay, I will shedule a 0.8.1 release for tomorrow ...and push it to wordpress.org.

**Comment by holger1411** [comment]
If you have any changes to .po files left feel free to open a pull request and I will merge it before the new release

**Comment by Vishal-Deshpande** [comment]
How about adding
1) Breadcrumb 
2) TGMPA
3) Author Bio
4) Related Posts
5) Some Essential Widgets
6) Couple of Essential Thumbnail Sizes (Based on Bootsrtap Grid size)

**Comment by Thomas-A-Reinert** [comment]
@Vishal-Deshpande : read the first post. It´s about making it tight and lean and getting rid of anything unneccessary. It´s aimed at developers, not end users.  Almost everything you mention - but #6 - adds "bloat". And #6 is totally dependant on how youre theme looks like, so I guess there will be no common solution.

**Comment by holger1411** [comment]
UnderStrap 0.8.1 is relased here on GitHub (https://github.com/understrap/understrap/releases/tag/0.8.1)
Will release it on wordpress.org within the next days ...in case bugs pops up.
feel free to test it, too.

**Comment by Vishal-Deshpande** [comment]
@Thomas-A-Reinert I think you lack the vision. People don't download Understrap just because it adds some col-xx bootstrap classes to underscores, but because it has much more to offer. By making lean and clean, you are killing understrap. Rather its time to add things that everyone has to eventually add to make underscores worth something.

**Comment by holger1411** [comment]
@Vishal-Deshpande
The problem is: No one has time to develop and maintain features which are used just by a minority of theme developers.

And: As more you add as more bugs and problems will pop up.
There are hunderets of cool features we might add. But it will "kill understrap". 
It means we have 100´s of not maintained, not ready-made features and a lot of bugs we have to deal with. 

So we decided to just add features which are "must haves". 
Means 50%+ of any theme developers need/use it (https://github.com/orgs/understrap/teams/understrap-playbook/discussions/1)

It´s a matter of managing the time we can put in and to keep a clean and solid foundation.
Having 1 rock-solid feature which is used by 99% of all theme developeres is much better than 99 features which didnt work well and are used just by a minority.

I would say that breadcrumbs and an author.php file *might* match this criterias.
Especially breadcrumbs are also available in Bootstrap:
https://getbootstrap.com/docs/4.0/components/breadcrumb/

**Comment by Thomas-A-Reinert** [comment]
@Vishal-Deshpande  - it seems that you feel personally attacked and tend to get personal therefore. Not my intention. Please lets get back to a more constructive way to handle things, okay?
Anyway, it seems - according to @holger1411 follow-up post - i could foresee UnderStraps future pretty well. And i´d love you to have me enlighten about what "_more it has to offer_" besides just  being another STARTER theme.

My plea would be - and @holger1411 is the maintainer of the project so I do not have the final decision pon that topic! - if not at least 51% of our aimed at users are not using /willing to intergrate that feature: DROP IT. If it´s not used: *BLOAT*. 

Just let´s make it a list that can be worked off one by one:
- I use Breadcrumbs on almost every Site i´m coding.
- But I normally handle it through https://yoast.com/wordpress/plugins/seo/ which is probably the most common solution looking at their reach/amount of installs.
  -  There must be a switch in the customizer to activate/deactivate breadcrumbs using YOAST/Custom/deactivating
  -  There must be an auto-dectection for Yoast/a custom solution overriding it
  - YOAST Style must be styled
  - Custom Styles must be styles
- Conclusion: At least two different styles/code-styles that would have to be maintained.
I´m in for that, but I just want to make the additional work transparent to @Vishal-Deshpande ...

**Comment by 0dp** [comment]
+1 for 🍞

**Comment by Thomas-A-Reinert** [comment]
I don´t see the need to further discuss this openly since we have an internal solution. The whole topic didn´t receive any responses anyway recently. Besides .. "_that expert opinion_"
