### ISSUE TITLE
Check function exists in inc/custom-comments.php

### ISSUE THREAD

**Issue by MarieComet** [understrap/understrap#587]
According to this issue in child-theme repo : https://github.com/understrap/understrap-child/issues/128
UnderStrap will check functions `understrap_bootstrap_comment_form_fields` and `understrap_bootstrap_comment_form` exists in inc/custom-comments.php file.

**Comment by holger1411** [comment]
Thx @MarieComet 
Merged it

**Comment by axlright** [comment]
Thanks @MarieComet I was actually working on the custom-comments.php last night and saw that it didn't have a pluggable function `if ( ! function_exists ( 'function' ) )` wrapper. 

I'm happy to put in some time going through other files adding the pluggable function wrappers if @holger1411 or anyone else knows of files that need it.

This is a closed comment thread so maybe this isn't the best place to write this. I can start a thread elsewhere :-)
