### ISSUE TITLE
Hero slider on home page not working.

### ISSUE THREAD

**Issue by justme101** [understrap/understrap#592]
I originally posted this in issue #216 but realized too late that it was closed. trying to get the slider to show on the 'front' page. read the comments from above with the php snippits to add. also read the comments from here: #457 . I did make a seperate templete named: front-page.php (basicly copied the page templete) but nothing is working. I am using (Version: 0.8.0) this is the same on WP.org Any help would be appreciated. just a novice here.

**Comment by holger1411** [comment]
Can you post the changes you did to line 19-21 in your front-page.php?

Basically `<?php if ( is_front_page() && is_home() ) : ?>` means the template just loads the hero area if the page is the frontpage AND homepage

The difference between front- and homepage is well explained here:
https://wordpress.stackexchange.com/questions/30385/when-to-use-is-home-vs-is-front-page

And:
Do you set your front page as front page in your backend via Settings->Reading->Front page displays ?

**Comment by justme101** [comment]
Thanks for the reply. yes, I did change the front page settings to point to the 'front page'
I also have the 'post page' pointing to the 'blog page'

here is the code i have starting on line 13 of the 'front-page.php file:
get_header();

$container   = get_theme_mod( 'understrap_container_type' );

?>

<?php if ( is_front_page() && is_home() ) : ?>
	<?php get_template_part( 'global-templates/hero' ); ?>
<?php endif; ?>

<div class="wrapper" id="page-wrapper">

	<div class="<?php echo esc_attr( $container ); ?>" id="content" tabindex="-1">

		<div class="row">

			
			<?php get_template_part( 'global-templates/left-sidebar-check' ); ?>

			<main class="site-main" id="main">

just reread the stackexchange from ^^  this is on a multi-site instillation. referring to answer#2  where do i insert this line?  if($_SERVER['REQUEST_URI'] == '/') {
    // you must be on the home page
}
Thank you for the help!

**Comment by justme101** [comment]
update--- , i noticed that this was not showingabove <?php if ( is_front_page() && is_home() ) : ?> this was on line 15..... I actually removed this whole php snippet plus the end if statement and it is now working perfectly

**Comment by justme101** [comment]
so to recap; (if this helps someone else) i made a templete for just the front page called front-page.php by copying the [page] templete. I then added <?php get_template_part( 'global-templates/hero' ); ?> on line 19 and everything is now showing on the 'front' page or home page.

**Comment by Thomas-A-Reinert** [comment]
Closing it, cos it seems to be resolved. Please reopen if you need to.
