### ISSUE TITLE
UnderStrap 0.8.1 release - Feedback

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#594]
I released UnderStrap 0.8.1 a few days ago here on Github.com (https://github.com/understrap/understrap/releases/tag/0.8.1) and today on wordpress.org (https://wordpress.org/themes/understrap/) and on understrap.com.

If you have any feedback or if you found a bug or ran into a problem with this new version please add it here. Any feedback is appreciated!

**Comment by pizza-r0b** [comment]
`$grid-gutter-width-base` in understrap.scss is undefined. Fixing that will lead down a rabbit hole of many other scss variables being undefined. What changed and why are these no longer defined anywhere?

**Comment by holger1411** [comment]
Basically it is defined in Bootstrap´s _variables.scss here:
https://github.com/understrap/understrap/blob/master/src/sass/bootstrap4/_variables.scss#L198
Pls check if this file is present in your folder

**Comment by Thomas-A-Reinert** [comment]
Didn´t investigate too much yet. But so far everything seems fine to me! Good job, thanks, @holger1411 !

**Comment by ryanfurtner** [comment]
@holger1411 Im having that same issue and its present in my folder. I am using http://scout-app.io and getting this https://i.imgur.com/VQ2B4DT.png

This is with a 100% fresh understrap download

**Comment by memims** [comment]
Had a problem with the understrap child theme after updating to this version - nothing past the nav bar rendered. Luckily found the fix here: https://wordpress.org/support/topic/updated-to-v-0-6-9-3-child-themes-not-working-as-expected/

Think it might be worth including a note in the release notes for the parent theme if there isn't going to be an update to the child theme any time soon.

**Comment by axlright** [comment]
@memims It looks like you're referring to the update to the functions.php that references an updated name for the navwalker function. True that a note in the release notes could help. Even if there were an update to the child theme that provided that same function name change, many people have customized their child theme functions.php and would not fully replace their child theme functions.php in an update. IMHO this is a case where local / staging testing of updates is helpful, especially in an environment with debugging turned on to alert to where the problem arose.

**Comment by Thomas-A-Reinert** [comment]
Apart from the fact that all problems _seem_ to be child-theme related (which should be posted in it´s [OWN repository](https://github.com/understrap/understrap-child) to keep things clean here) I am totally with @axlright  - there SHOULD be a highly-visible not on crucial updates. 

I guess only a minority will ever read the Changelog so I´m really for an Inside-WP-Popup that informs about _CRUCIAL_ changes.

**Comment by mickeydblv** [comment]
I'm very interested in the solution for this error. I'm using understrap and Scout-app for compiling. I am a bit of a noob with SASS and all that, but been building sites with underscores for a few years. Not building in a child theme. 

I changed the variable name in _variables.scss to make the change
From: $grid-gutter-width:      30px !default;
To:     $grid-gutter-width-base:      30px !default;

but this getting the same error. 

In the theme.scss it looks like this: 
```
@import "theme/theme_variables";  
@import "assets/bootstrap4";
@import "understrap/understrap";

//Optional files - If you dont use the corresponding scripts/fonts comment em out
@import "assets/font-awesome"; 
@import "assets/underscores"; 

// Any additional imported files //
@import "theme/theme";  
@import "theme/contact-form7"; 
```
but perhaps they are in the wrong order when being compiled. Any clues would be MOST helpful. 
Thanks
Michael.
