### ISSUE TITLE
Upon further inspection, a whole lot of the .md files is either incomplete or just s*cks. Sorry.

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#596]
Everything said above.
- Either, information is not up to date
- it is incomplete
- it´s not well-formed.
- or is missing (CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, CODE-OF-CONDUCT.md)

My current [WordPress-Developer-Checklist](https://github.com/Thomas-A-Reinert/WordPress-Developer-Checklist) repo still ain´t perfect but there may be some things to learn from. Willing to add up, just need a "*GO!*" if desired to be integrated into the UnderStrap project.

**Comment by Thomas-A-Reinert** [comment]
https://github.com/understrap/understrap/community had just two criteria fulfilled.
[ x ] Description
[ x ] Readme


Now its five.
[ x ] Description
[ x ] Readme
[ x ] Code of conduct
[ x ] Contributing
[ x ] Issue template

Still missing:
[   ] License template, gonna care about that within the next days.

None of my supplied pulls are perfect - but need investigation and improvement by @holger1411 and the rest of the community!

- There is a template for issue-requests now.
Its more or less a blant copy of my own project, https://github.com/Thomas-A-Reinert/WordPress-Developer-Checklist . It should be refined to match UnderStraps´ purposes and requirements.
- The template for pull requests is still missing but will soon come. Promised ;)
Check my own repo and discuss what you want / don´t want to have included. => https://github.com/Thomas-A-Reinert/WordPress-Developer-Checklist/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by holger1411** [comment]
👍

**Comment by Thomas-A-Reinert** [comment]
Some things could still be improved but the heap of it is fixed now.

**Comment by Thomas-A-Reinert** [comment]
@holger1411 https://github.com/understrap/understrap/blob/master/ISSUE_TEMPLATE.md needs rework too. URGENTLY! As I said, it´s more or less a copy of my own repos´ ISSUE_TEMPLATE. And it may be really confusing actually atm.

**Comment by 0dp** [comment]
@Thomas-A-Reinert, you've included what I would expect of the template, but maybe it could be rephrased a bit, maybe like https://github.com/WordPress/gutenberg/blob/master/.github/ISSUE_TEMPLATE.md

the only things I might see added is `[ ] need help` or `[ ] question` to the top section.
OS and node version, maybe even `[ ] I'm using Windows Subsystem for Linux`

**Comment by Thomas-A-Reinert** [comment]
hey @0dp - thanks! Some things changed on ISSUE_TEMPLATE.md due to your requests/input. Do you think that suits better now? In case you´re still missing anything, please let me know!

**Comment by 0dp** [comment]
Looking good 👌

**Comment by Thomas-A-Reinert** [comment]
Closing it cos most of it should be fixed now.
