### ISSUE TITLE
gulp minify is not defined

### ISSUE THREAD

**Issue by bruceconlon** [understrap/understrap#604]
when using `gulp scss-for-prod` in either understrap or understrap child, you get the error:

ReferenceError: minify is not defined

Should `.pipe( minify-css() )` be replaced with something like `.pipe(cssnano({discardComments: {removeAll: true}}))` or `.pipe( cleanCSS( { compatibility: '*' } ) )`?

**Comment by 0dp** [comment]
I can confirm this.
```
    var pipe2 = source.pipe( clone() )
        .pipe( cleanCSS( { compatibility: '*' } ) )
        .pipe( rename( { suffix: '.min' } ) )
        .pipe( sourcemaps.write( './' ) )
        .pipe( gulp.dest( paths.css ) );
    return merge( pipe1, pipe2 );
```

This seems to fix the issue, please test

**Comment by holger1411** [comment]
@0dp : Thx!
Works here, too.
Commited here: https://github.com/understrap/understrap/commit/b47d327882e26300687475d62a9896a1008ac43a
