### ISSUE TITLE
 WooCommerce templates out of date with WC3.3.0 

### ISSUE THREAD

**Issue by loorlab** [understrap/understrap#605]
Hi Friends , our actual WooCommerce Status : "Your theme has a woocommerce.php file, you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues."

Bug Report 

 - WordPress Version: 4.9.4
 - UnderStrapVersion: 0.8.1
- WooCommerce  3.3.3

Report 👍 

understrap/woocommerce/single-product/product-thumbnails.php version 3.3.0 is out of date. The core version is 3.3.2, 

Should we wait for some update?

Thanks !

**Comment by holger1411** [comment]
Thx @loorlab !
I changed it here:
https://github.com/understrap/understrap/commit/a0c6bc127eb5aa8760d93f32f6dd1bc07541e23f
Will be shipped with the upcoming 0.8.2 version.

Alternatively you can download the actual version here from GitHub and replace the /woocommerce folder with it.

**Comment by loorlab** [comment]
@holger1411 Thanks my friend !
