### ISSUE TITLE
WooCommerce with Understrap / Parent-Child 

### ISSUE THREAD

**Issue by loorlab** [understrap/understrap#606]
Hi Friends, we are trying to modify WooCommerce templates from the child theme but we are not sure if it is a problem of the template child or parent .

Environment : 
 - WordPress Version: 4.9.4
 - Understrap Version: 0.8.1 
-  UnderStrap Child Version: 0.5.0
-  WooCommerce 3.3.3
---

bug report

It is affecting the HTML code of the archive-product.php template of WooCommerce.

The front-end design of the template that we are modified is not correct.

The problem occurs with the following scenario:

1) We copy the file woocommerce.php(theme parent : understrap) into the folder understrap-child/woocommerce.php 

2) We modify the structure(woocommerce.php) so that it rewrites the template correctly , The reason to modify it is the following --> https://github.com/understrap/understrap/issues/494 + https://github.com/understrap/understrap/issues/373 

Line 32 woocommerce.php--> $template_name = '/archive-product.php'; 
Line 35 woocommerce.php --> $default_path = untrailingslashit( plugin_dir_path(__FILE__) ) . '/woocommerce';

**Note : \ to /** 

3) We upload the WooCommerce folder in the child theme with the file archive-product.php ie **understrap-child/woocommerce/archive-product.php** 

Result : 

When you try a category of a product in the source code, the HTML is incorrectly inserted, for example :

![sin titulo](https://user-images.githubusercontent.com/3799679/37687959-b83f5b4e-2c6b-11e8-9c58-e0f461ebbdc0.png)

![sin titulo](https://user-images.githubusercontent.com/3799679/37687983-d1785d86-2c6b-11e8-96d4-e20c52781b8c.png)

And the design is displayed badly with overflow´s and unexpected things.

We do not know if we are doing the process wrong or if something is really failing.

Thanks !

________________________________________________________________________________
Update 1 : Possible Solution  

>  It is contradictory but it works OK

1) "Delete" || "Rename" the woocommerce.php file from the parent theme (For example : /wp-content/themes/understrap/woocommerce-.php) .
2)  Upload the modified archive-product.php file to the next path within the child theme --> /wp-content/themes/understrap-child/woocommerce/templates/archive-product.php

An answer that we found in a forum gave us the idea 👍 

![screenshot-2018-3-20 how to override archive-product php file in woocommerce - quora](https://user-images.githubusercontent.com/3799679/37694305-2534741e-2c94-11e8-854e-35c8632cfd18.png)

But if we update the Parent Theme surely we will have a problem , we hope that someone can help us or clarify this.

**Comment by holger1411** [comment]
Thx for your complete bug report.
I wasn´t aware of this till now.
Will have a look at the best practice here...

**Comment by holger1411** [comment]
Okay, seems the best practice is to not use woocommerce.php but instead use a hook to inject WooCommerce functionality into the theme as described here:
https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/
(Check section "using hooks")
Using this solution gives you the ability to overwrite the parent themes woocommerce templates by your child theme.

I was able to remove woocommerce.php and using the solution above in inc/woocommere.php
And everythings works

But:
I´ am not a gifted PHP developer. I wasn´t able to add our dynamic sidebar check to it nor the dynamic container setting.
The result is that WooCommerce replaced the entire .container and no sidebar is rendered.

My first attept: Adding the following code to inc/woocommerce.php

```

/**
* First unhook the WooCommerce wrappers
*/
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10);
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10);

/**
* Then hook in your own functions to display the wrappers your theme requires
*/
add_action('woocommerce_before_main_content', 'understrap_woocommerce_wrapper_start', 10);
add_action('woocommerce_after_main_content', 'understrap_woocommerce_wrapper_end', 10);

function understrap_woocommerce_wrapper_start() {
  echo '<div class="container" id="content" tabindex="-1">';
}

function understrap_woocommerce_wrapper_end() {
  echo '</div>';
}
```

What needs to be done here:
1.Check if "container" or "container-fluid" is set and echo the right warapper start.
2.Check if left, right, both or none sidebar is active and adjust the markup

Maybe someone can help here?

**Comment by holger1411** [comment]
Oh, and I have to mention:
If we found a correct solution to check for the correct primary <div> inside the .container we don´t need a check for the container size.

The problem is just that we need to hook-in WooCommerce into the inner .col.
That can be .col-12, col-8, col-6 depending if one, two or no sidebar is active.

So the correct code should looks like:

```
function understrap_woocommerce_wrapper_start() {
  echo '<div class="**col-md-xy** content-area" id="primary"';
}
```
while col-md-xy can be col-md-6, col-md-8 or col-md-12 regarding to:
https://github.com/understrap/understrap/blob/master/global-templates/left-sidebar-check.php

**Comment by loorlab** [comment]
@holger1411 Thanks for your support , using the hooks it can become complicated to adapt it with certain customized things on the understrap, We appreciate if someone can give us a guide to the best flow of customization in WooCoommerce .

We look at the integration of a template in WooCommerce (woochi template) and find the following:

1) The parent theme does not have the **woocommerce.php** file in the root folder.
2) In the functions.php file we find functions such as:

```
if (!function_exists('theme_has_woocommerce')) {
    function theme_has_woocommerce() {
        $_actived = apply_filters('active_plugins', get_option('active_plugins'));
        if (in_array("woocommerce/woocommerce.php", $_actived) && class_exists('WooCommerce')) {
            return true;
        }
        return false;
    }
}

/* * * Include files in woo folder ** */
$file_names = array('functions', 'term', 'quickshop', 'grid_list_toggle', 'hooks');
foreach ($file_names as $file) {
    $file_path = get_template_directory() . '/inc/woo/' . $file . '.php';
    if (file_exists($file_path)) {
        require_once $file_path;
    }
}

```
`add_theme_support('woocommerce');`

3) Folders 
              \wp-content\themes\woochi\woocommerce --> WooCommerce Files
               \wp-content\themes\woochi\inc\woo\  --> Files : 
                                                                             hooks.php 
                                                                             functions.php  
                                                                             quickshop.php 
                                                                             term.php  
                                                                             grid_list_toggle.php
We believe that this can give an idea of where the correct WooCommerce Parent - Child integration should be made !

Thanks for your support Again @holger1411

**Comment by loorlab** [comment]
Update 2 : @holger1411
 
1.Check if "container" or "container-fluid" is set and echo the right warapper start.

Yes , Works Ok 

![screenshot-2018-3-21 products panther cdb staging](https://user-images.githubusercontent.com/3799679/37733826-578e81ec-2d17-11e8-89d0-1490fc25d31c.png)

2.Check if left, right, both or none sidebar is active and adjust the markup

No Working

**Comment by typeplus** [comment]
My apologies @loorlab I havent had a chance to look at a solution to the integration with hooks. I have done it in the past for a couple of client projects so when I get some time I can post what I did.

**Comment by loorlab** [comment]
@holger1411 @ZacharyElkins  The change works well with a child theme ( Initial Test) 👍 

but...

For our design we need to activate the container wrapper and include this code in functions.php within the child theme :
```
/**
* First unhook the WooCommerce wrappers
*/
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10);
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10);

/**
* Then hook in your own functions to display the wrappers your theme requires
*/
add_action('woocommerce_before_main_content', 'understrap_woocommerce_wrapper_start', 10);
add_action('woocommerce_after_main_content', 'understrap_woocommerce_wrapper_end', 10);

function understrap_woocommerce_wrapper_start() {
  echo '<div class="container" id="content" tabindex="-1">';
}

function understrap_woocommerce_wrapper_end() {
  echo '</div>';
}
```
When we activated the sidebars they were not display .

Are we doing something wrong?

Thanks Guys !

**Comment by ZacharyElkins** [comment]
@loorlab  That code needs to go in the parent theme in **inc/woocommerce.php**

Also, you referenced the draft code, not the final code which I posted above. The new code adds the sidebar checks.

Am I misinterpreting what you've said? Again, I don't work with child themes often, but it does use the functions in the parent theme, which is where the code should be added.

**Comment by mundeee** [comment]
I had some similar problems with a current site I'm working on and noticed that my archive-product.php started to misbehave on local and online version. (understrap + child; woocommerce 3.3.3/3.3.4)

not the biggest fan of all the woocommerce hooks I was still counting on the child-theme woocommerce.php override. noticed that archive-product.php was never kicking in, found the following to do the trick:
understrap/woocommerce.php still unchanged

```
// child-theme/woocommerce.php
$template_name = '/archive-product.php'; 
$default_path = get_stylesheet_directory() . '/woocommerce';
```
I stripped off most of the divs and classes in child-theme/woocommerce.php though and handle that in my template files since I have a quite simple setup  (sorry, OP)

still interested in this issue.

**Comment by typeplus** [comment]
@ZacharyElkins great work! That was a prettier version of what I did so thankyou for this. I will be using that from now on :)

**Comment by holger1411** [comment]
@loorlab The left sidebar works on the demo site perfectly:
![screenshot-understrap com-2018-03-23-09-54-11](https://user-images.githubusercontent.com/1568158/37820242-4fd01636-2e80-11e8-8101-0ce060709e0f.png)

Do you activate the right sidebar via Theme customizer or do you just publish a widget on this position?

**Comment by ZacharyElkins** [comment]
@typeplus  Thanks! Happy to help.

@loorlab Do you have widgets in your left sidebar? Understrap defaults to no widgets in the left sidebar. See this:

![screenshot-2018-3-23 widgets understrap test environment wordpress](https://user-images.githubusercontent.com/25933268/37843436-81061af2-2e8a-11e8-9f08-616d354cc52b.png)

Widgets must be put in the left sidebar for it to work.

I can confirm this is working for left, right, and both sidebars when in fixed and full width layout. But, only when the sidebar has widgets added.

@holger1411  I'm not sure if this is a problem, but the code in the sidebar check templates requires the sidebar to be active, which means that if there aren't widgets in the corresponding sidebar it doesn't produce the correct layout.

When set to "both" and when no content is in the left sidebar, it gives "col-md-12".
When set to "left" with only widgets in the right sidebar it gives "col-md-8" with no sidebar generated.
Same for when set to "right" as "left" with widgets empty.

Doesn't seem like an issue as ideally there would be content in the chosen sidebar, but just in case someone does something dynamic here, what do you think of this:
```
<?php
/**
 * Left sidebar check.
 *
 * @package understrap
 */

?>

<?php
$sidebar_pos = get_theme_mod( 'understrap_sidebar_position' );
?>

<?php if ( 'left' === $sidebar_pos || 'both' === $sidebar_pos ) : ?>
	<?php get_sidebar( 'left' ); ?>
<?php endif; ?>

<?php
	$html = '';
	if ( 'right' === $sidebar_pos || 'left' === $sidebar_pos ) {
		$html = '<div class="';
		if ( ( is_active_sidebar( 'right-sidebar' ) && 'right' === $sidebar_pos ) || ( is_active_sidebar( 'left-sidebar' ) && 'left' === $sidebar_pos ) ) {
			$html .= 'col-md-8 content-area" id="primary">';
		} else {
			$html .= 'col-md-12 content-area" id="primary">';
		}
		echo $html; // WPCS: XSS OK.
	} elseif ( 'both' === $sidebar_pos ) {
		$html = '<div class="';
		if ( is_active_sidebar( 'right-sidebar' ) && is_active_sidebar( 'left-sidebar' ) ) {
			$html .= 'col-md-6 content-area" id="primary">';
		} elseif ( is_active_sidebar( 'right-sidebar' ) || is_active_sidebar( 'left-sidebar' ) ) {
			$html .= 'col-md-8 content-area" id="primary">';
		} else {
			$html .= 'col-md-12 content-area" id="primary">';
		}
		echo $html; // WPCS: XSS OK.
	} else {
	    echo '<div class="col-md-12 content-area" id="primary">';
	}

```

**Comment by loorlab** [comment]
@holger1411 @ZacharyElkins Oh Yeah Sorry, We activated them via Theme Customizer and it was necessary to add widgets to the left sidebar.

Everything works perfect.

👍 💯 🥇

**Comment by holger1411** [comment]
Glad to hear that @loorlab !
closing this becaus eit seems to be fixed.

**Comment by ZacharyElkins** [comment]
@holger1411 Did you review the code I submitted for left-sidebar-check.php ? Hoping you didn’t miss it, a few comments up. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by holger1411** [comment]
@ZacharyElkins No fear!  It was added here:
https://github.com/understrap/understrap/commit/a2fa9e56ba0326ed36297d699ca06ada26110107
Seems I did not metioned your...

**Comment by ZacharyElkins** [comment]
@holger1411  Oh, didn't check! Just wanted to make sure it was seen. Thanks!
