### ISSUE TITLE
Installing jQuery the correct way. 

### ISSUE THREAD

**Issue by ricksternyc** [understrap/understrap#611]
Hello, first time using the theme. 

Can't seem to get a Bootstrap 4 Carousel to work, I'm going to assume it's because jQuery isn't working or loading after Bootstrap. 

`npm install`
**_"npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself."_**

I've tried adding using the method described here. Along with a custom.js file, didn't seem to work for me, unfortunately. 
#47 

This is what I have in enqueue.php....

```
 function understrap_scripts() {
        // Get the theme data.
        $the_theme = wp_get_theme();
        wp_enqueue_style( 'understrap-styles', get_stylesheet_directory_uri() . '/css/theme.min.css', array(), $the_theme->get( 'Version' ) );
        wp_deregister_script( 'jquery');
        wp_register_script('jquery', (get_stylesheet_directory_uri() . '/js/jquery-3.3.1.min.js'), true, '3.3.1');
        wp_enqueue_script( 'jquery' );
        wp_enqueue_script( 'custom_js', get_template_directory_uri() . '/js/custom.js', true, '1');
        wp_enqueue_script( 'popper-scripts', get_template_directory_uri() . '/js/popper.min.js', array(), true);
        wp_enqueue_script( 'understrap-scripts', get_template_directory_uri() . '/js/theme.min.js', array(), $the_theme->get( 'Version' ), true );
        if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
            wp_enqueue_script( 'comment-reply' );
        }
    }
} // endif function_exists( 'understrap_scripts' ).

add_action( 'wp_enqueue_scripts', 'understrap_scripts' );
```

Custom.js works with jQuery, however, Bootstrap functions reliant on jQuery not responding. 

Stumped, thanks for any advice.

**Comment by holger1411** [comment]
WordPress itself loads a copy of jQuery (v 1.12.4) which works perfectly with Bootstrap 4 (after some issues at the beginning...). So we don´t include another version as dependency.
Another reason for that: The wordpress.org theme review team did not accept themes with custom jQuery versions.

As you can see the carousel working on our demo site here:
https://understrap.com/understrap/

and the accordion (as related component), too:
https://understrap.com/understrap/?page_id=2

And it is important that jQuery is loaded BEFORE Bootstrap.

So it seems there is another problem or issue.
Can you provide an URL?

**Comment by ricksternyc** [comment]
Thanks for the assistance. Got it working! 

Seems I overcomplicated things by creating my own blank template with just get_header() and then assuming it was because jQuery wasn't running out of sequence. Seems it requires your theme's container. I'm aware jQuery is baked into WP, but threw me for a loop when slider wasn't responding. Now using theme as intended, using starter template files.  Look forward to working with understrap!
