### ISSUE TITLE
Gulp-uglify can't handle es6

### ISSUE THREAD

**Issue by lpq66** [understrap/understrap#613]
If you try to use arrow function, gulp throws an error, as gulp-uglify does not support es6 syntax.

And I have a solution for it already. 
Just install gulp-uglifyes
`npm i gulp-uglifyes`
And in `gulpfile.js` rename `var uglify = require('gulp-uglify');` to `var uglify = require('gulp-uglifyes');`

Now es6 syntax will work.

**Comment by Thomas-A-Reinert** [comment]
Hi @lpq66 - that´s pretty cool, thanks for letting us now. Yes, the current setup was not meant to support ES6/TypeScript whatsoever. I´ll mark that one as a Todo for the gulpfile-guys ;)

Am I understanding correctly that this would also solve #593 ? Didn´t try it and already too tired to give it a go, so this is why I´m asking..

**Comment by 0dp** [comment]
I'll give it a spin tonight. I have a feeling might also have to take a look at linting and travis

**Comment by 0dp** [comment]
Hi @lpq66 gulp-uglifyes, as the name implies. uglyfies and compress ES6+ syntax but on it's own it does not compile the code.

ie.

```
[1,2,3].map(n => n + 1);
```
should compile to 
```
"use strict";

[1, 2, 3].map(function (n) {
  return n + 1;
});
```

So without gulp-babel for instance it won't have the desired effect.

Including a new set of tools to support ES6 needs to be discussed further.

**Comment by hartwm** [comment]
`npm install @babel/core --save-dev`
`npm install gulp-babel --save`

In gulpfile.js require babel
`var babel = require('gulp-babel');`

Find gulp scripts task and add 

` .pipe(babel({
      presets: ['es2015']
    }))`

Here is example: 
```
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
  var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.bundle.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js'
    ];
  gulp.src(scripts)
    .pipe(babel({
      presets: ['es2015']
    }))
    .pipe(concat('theme.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest(paths.js));

  gulp.src(scripts)
    .pipe(concat('theme.js'))
    .pipe(gulp.dest(paths.js));
});
```

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
