### ISSUE TITLE
Creating a full page landing slider using the built in Widget

### ISSUE THREAD

**Issue by pcarter13** [understrap/understrap#617]
Hi guys

Been using Understrap for a while now after a friend recommended it to me. I have been a dedicated fan ever since and use it for pretty much all my projects. I want to take this opportunity to thank you all for everyones dedicated help in pushing this forward. 

I have previously been using Slick slider to make a full page slider, however I feel like this should be able to be able to be achieved through the Hero Slider widget. I have tried with different ones such as the image and general text method (adding text and an image into the box). I am able to achieve this using the custom HTML section widget but this is not very updatable and definitely not usable by a client. 

I was wondering if there is a way to achieve something like the screenshot attached using the built in Hero Widget. I have tried adding code in the 'widgets.php' file to insert code before and text input widget (and to add the Jumbotron class), however I haven't been able to put the image in a separate div or class. From my research I take I would need to register my own plugin/widget in order to do this (which I am willing and able to do) but I thought I would check I am not missing something before I do this!

I tried to recreate the Jumbotron on the demo site https://understrap.com/understrap/ but couldn't work out how to recreate the buttons etc.

Any help would be a great - sorry if I have rambled a bit and let me know if I need to clarify anything

![screen shot 2018-03-27 at 10 23 53](https://user-images.githubusercontent.com/9502113/37958928-b676a02c-31a9-11e8-9281-1051236f1968.png)

Thanks, Pat

**Comment by holger1411** [comment]
I just use the default Jumbotron markup in a default custom HTML widget. 
I just add this:
```
<div class="jumbotron  jumbotron-fluid bg-primary text-white">
      <div class="container py-5">
        <h2 class="display-4">Sample Jumbotron</h2>
      This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
                <br/><a class="btn btn-success btn-lg" href="https://gumroad.com/l/CQrW">Download now</a>
<a class="btn btn-primary btn-lg" href="https://github.com/holger1411/understrap"  target="_blank" role="button">Visit Github</a>

      </div>
    </div>
```
For the first slide (as example)
So normally there is no need for an extra widget.

**Comment by holger1411** [comment]
You can add a background image easily with some CSS for via inline HTML styles like:

```
<div class="jumbotron  jumbotron-fluid bg-primary text-white" style="background:url(url/to:your/image.jpg);)">
      <div class="container py-5">
        <h2 class="display-4">Sample Jumbotron</h2>
      This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
                <br/><a class="btn btn-success btn-lg" href="https://gumroad.com/l/CQrW">Download now</a>
<a class="btn btn-primary btn-lg" href="https://github.com/holger1411/understrap"  target="_blank" role="button">Visit Github</a>

      </div>
    </div>
```

**Comment by Thomas-A-Reinert** [comment]
Guess that topic is solved due to no response and a clear answer on how to solve it. Closing it therefore.

Feel free to reopen if the problem remains.
