### ISSUE TITLE
Where's the custom logo?

### ISSUE THREAD

**Issue by altemberg** [understrap/understrap#621]
I'm still a bit new to wordpress and I do not understand many things yet.

But in the customizer it displays the custom logo option, but I have not found where this option is. I looked at the functions.php, customizer.php and nothing. I even removed all the functions.php codes but still the option is still there.

I would like to know where the code is to be able to remove it, since I am using Kirki and I will put the logo in a different section.

**Comment by sommerset** [comment]
check line 42 and followings of header.php

**Comment by altemberg** [comment]
@sommerset I got to see this code and removed it, but the logo section is still there.

**Comment by Thomas-A-Reinert** [comment]
Sure, this is just the thingie that renders the logo on the frontpage, if available.

See ./inc/setup.php, line 87/88
```php
//Set up the WordPress Theme logo feature.
add_theme_support( 'custom-logo' );
```

Remove those lines and you should be set.

See https://codex.wordpress.org/Theme_Logo as reference.

I´ll close this topic as it should be resolved. Feel free to reopen if the problem persists.

**Comment by altemberg** [comment]
I also removed this code, but it did not work. I left the functions.php blank but the section is still there.

So I had this doubt, I removed several codes but nothing solved.

I have the latest version of Understrap and also Wordpress.

**Comment by ZacharyElkins** [comment]
Try deactivating and re-activating the theme.

**Comment by altemberg** [comment]
@ZacharyElkins That was one of the first things I did.

**Comment by altemberg** [comment]
I solved this problem! \o/

**Comment by Thomas-A-Reinert** [comment]
Would you please be so kind to explain how? What was the problem and how did you solve it?
It may help others in the future (and yes us too helping others stumbling over the same problem so we may use it as a reference).

Thanks in advance and glad it could be solved!

**Comment by altemberg** [comment]
So the problem was not in understrap. I did not know that Wordpress was adding some options by default. I started to move and found where WP added the customizer, which is in the file class-wp-customize-manager.php, I took the section of it and removed it.

When I was studying WordPress, the customize did not appear by default, so I was so confused.

Sorry for anything and thanks so much!

**Comment by Thomas-A-Reinert** [comment]
Yeap, it´s a built-in option, just didn´t know that it´s not optional (like being set as an OPTION as quoted above) but included anyway as a default.

But yes, it is since Version 4.5, see https://codex.wordpress.org/Theme_Logo and will have it´s default values, sections etc.

What you´re actually doing may work - but it´s a NO-GO in case of updateability of WordPress etc. Whenever you update WP-Core your changes WILL get lost! Promised. NEVER EVER TOUCH CORE FILES!

It´s recommended to de-activate *whatever* through a hook though, see https://codex.wordpress.org/Function_Reference/remove_theme_support#Removing_a_Feature_In_a_Child_Theme . What they don´t tell - this also works for the parent ;)

To make it easy to follow for you:
1. Make sure you deleted the line/s I told you above (87/88) [the add_theme_support line/s]
2. Paste the following code instead: 

```
function remove_logo_from_standard_customizer() {		
  // Totally remove custom logo option from the Customize -> Site Identity Section
  remove_theme_support( 'custom-logo' );
}
add_action( 'after_setup_theme', 'remove_logo_from_standard_customizer', 11 ); 
```

**Comment by Thomas-A-Reinert** [comment]
Personal question: You said you´re using Kirki. That takes a lot of headaches from you trying to "customize the customizer". Yes i know that sounds stupid, but customizing the customizer can become a real challenge. It´s okay to write a dozen or so customizer options on your own. And you won´t have the chance to style them as you wish, when you do not REALLY dig the topic. 
But as soon as you´re getting into the hundreds or need to have them REALLY customizable - the default options can become a real P.I.T.A.

What I´m asking is:
- Do you just need a couple of adjustment being set via the customizer (like <= 50)?
- Or do you really need a couple of dozens to be set through the customizer? (like 60+)

**Comment by altemberg** [comment]
@Thomas-A-Reinert No, there are few options. Actually I'm using it for study purposes, I'm testing frameworks to know everything I can do with WordPress.

I've already done some things with no framework and now I'm making use of some to compare

**Comment by altemberg** [comment]
@Thomas-A-Reinert Yes! Your solution solved, I reinstalled the understrap and resolved.

And I always prefer to do it by hand, but I also like to have other ways to go if something does not go as expected or needs to be done faster.

Thank you very much for all your help.
