### ISSUE TITLE
NPM Install warnings / deprecated packages | Windows 10

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [understrap/understrap#624]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - WordPress Version: latest, Dev-Environment
  - OS Version: [Windows 10]
  - Browser: [Browser-independant]
  - Language: [Javascript | Node]
  - Node.js & NPM Versions: Node.js [V 8.9.2] | NPM [V 5.7.1]

---

# Issue Overview for Bugreports
## Steps to reproduce?
* Get a clean install from "master"-branch.
* ```console npm install``` on windows

## Output:
```console 
npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> uws@9.14.0 install F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> node-sass@4.8.3 install F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-57_binding.node
Download complete  ] - :
Binary saved to F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\node-sass\vendor\win32-x64-57\binding.node
Caching binary to C:\Users\phanthomas\AppData\Roaming\npm-cache\node-sass\4.8.3\win32-x64-57_binding.node

> node-sass@4.8.3 postinstall F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\node-sass
> node scripts/build.js

Binary found at F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\node-sass\vendor\win32-x64-57\binding.node
Testing binary
Binary is fine

> gifsicle@3.0.4 postinstall F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> jpegtran-bin@3.2.0 postinstall F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> optipng-bin@3.1.4 postinstall F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> understrap@0.8.1 postinstall F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap
> gulp copy-assets

[00:46:07] Using gulpfile F:\xampp7.1\htdocs\wordpress\wp-content\themes\understrap\gulpfile.js
[00:46:07] Starting 'copy-assets'...
[00:46:07] Finished 'copy-assets' after 136 ms
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1162 packages from 673 contributors in 179.888s
```

## Expected behavior
Clean install without warnings etc.
Yes, I know the ```console  npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.  ``` cannot be avoided. But maybe there´s a chance to leave a note or whatever that it´s included with WP anyways?

### Other Comments
Needs investigation by "Team Gulp". @0dp - would you be so kind to investigate? It would be REALLY awesome to have npm install running without any errors or warnings. 

But *hey* I know - we don´t live in a perfect world ;) Just wanted to let you know to maybe improve the installation process in case you feel like

Note to "Team Documentation" - @holger1411  @axlright ```console  gulp copy assets``` is run by default at the end of the installation process. So its not neccessary to mention that in the doc. Please remove.

**Comment by 0dp** [comment]
Sure thing @Thomas-A-Reinert please assign it to me so i don't forget 😜

**Comment by Thomas-A-Reinert** [comment]
Thanks a lot, dude. Learning a lot from your gulp-adjustitions atm ;)

**Comment by 0dp** [comment]
We need to do is upgrade to gulp v. 4.0 it seems to remove the deprecation warnings, but in doing so we will have to update the gulp file and check all the tasks

**Comment by Thomas-A-Reinert** [comment]
So would you please as soon as you find the time? Thanks in advance!

**Comment by 0dp** [comment]
Yup, I'll look into it tonight and make a PR to review

**Comment by axlright** [comment]
Happy to help here but me no have no Windows. Otherwise, let me know if / how to help.

**Comment by 0dp** [comment]
I'm about to finish up a complete refactored gulp file with cleaned up tasks, optimized for gulp4.

Some steps are also required from the user, specifically removing gulp locally, and installing gulp-cli.

Thorough testing is needed though, cuz I have no idea what implications this might have on other projects still using gulp 3.9.

The gulp team is not holding up too good it seems.

Anyways, I will post an update later tonight

**Comment by 0dp** [comment]
@axlright @Thomas-A-Reinert 
It's with shivering hands and cold sweaty palms I present the update to gulp4. Including updated and optimized gulp tasks, and refactoring slimming down the code 100+ lines. 

Please test and report back, with any questions, bugs, and errors you find. 
https://github.com/0dp/understrap/tree/gulp4

In order to get things to work, you'll have to remove gulp locally
`npm rm -g gulp`

Then you have to install the new gulp-cli
`npm install -g gulp-cli`

`gulp -v` should now report something like `CLI version 2.0.1`

_Will gulp-cli in favor of gulp3.9.x break everything else? I don't know, let's find out_

_Some tasks are missing? Yes, I removed them, what did they do?_

**Comment by 0dp** [comment]
¡Hola! any testers available

**Comment by breath-ee** [comment]
- OSX 10.11.6 - _EL Captain_
- Homebrew 1.6.2
- Homebrew/homebrew-core (git revision 0f322; last commit 2018-04-30)
- Apache/2.4.33 (Unix) OpenSSL/1.0.2o PHP/7.1.14  (stable 7.2.5 (bottled))

Ran from within the understap theme folder:

`sudo npm rm -g gulp`
> up to date in 0.067s

`sudo npm install -g gulp-cli`
> /usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp-cli/bin/gulp.js
> gulp-cli@2.0.1
> added 145 packages, removed 46 packages, updated 38 packages and moved 3 packages in 13.47s

`gulp -v`
> CLI version 2.0.1
> Local version 3.9.1

Final output:

> understrap@0.8.2 postinstall /Users/username/public_html/clients/domain.com/public_html/wp-content/themes/understrap
> gulp copy-assets

> Using gulpfile ~/public_html/clients/domain.com/public_html/wp-content/themes/understrap/gulpfile.js
> Starting 'copy-assets'...
> Finished 'copy-assets' after 160 ms

> npm WARN bootstrap@4.1.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

> up to date in 22.295s

All working. Despite the jQuery error.

Adding "jquery": "^1.9" to the package.json then running `npm install` seems to correct this error message. I thought jQuery was already bundled in with Understrap?

**Comment by pattonwebz** [comment]
@breath-ee jQuery is bundled directly with WordPress. Understrap calls it in as a dependency when enquing the main bootstrap javascript file so is available when needed :)

**Comment by Thomas-A-Reinert** [comment]
It´s already bundled and enqueued by default by WordPress. All good - no need to add/change anything.
Please try - do _not_ add jQuery to  the package.json, and try if it works..

**Comment by Thomas-A-Reinert** [comment]
Oh seems @pattonwebz was a bit faster. Anyway: Statement confirmed ;)

**Comment by breath-ee** [comment]
Doh totally forgot about that! There must be a way to suppress that npm message.

**Comment by 0dp** [comment]
@not really and you shouldn't.

best way to sort it is to add jquery as a peer dependency to the projects package.json

**Comment by breath-ee** [comment]
As an update I just tried a fresh git clone, ran `npm install` and got the same errors before trying the gulp re-install as outlined above.

- WordPress v4.9.5
- OSX 10.11.6 - EL Captain
- FireFox 59.0.2
- npm v5.6.0
- Homebrew 1.6.2
- Homebrew/homebrew-core (git revision 0f322; last commit 2018-04-30)
- Apache/2.4.33 (Unix) OpenSSL/1.0.2o PHP/7.1.14 (stable 7.2.5 (bottled))

> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

Not sure if this is brew/osx issue:

  ⚠ The `/Users/username/public_html/demos/wordpress/public_html/wp-content/themes/understrap/node_modules/jpegtran-bin/vendor/jpegtran` binary doesn't seem to work correctly
  ⚠ jpegtran pre-build test failed
  ℹ compiling from source
  ✖ Error: touch configure.ac aclocal.m4 configure Makefile.am Makefile.in && ./configure --disable-shared --prefix="/Users/username/public_html/demos/wordpress/public_html/wp-content/themes/understrap/node_modules/jpegtran-bin/vendor" --bindir="/Users/username/public_html/demos/wordpress/public_html/wp-content/themes/understrap/node_modules/jpegtran-bin/vendor" && make install
Command failed: ./configure --disable-shared --prefix="/Users/username/public_html/demos/wordpress/public_html/wp-content/themes/understrap/node_modules/jpegtran-bin/vendor" --bindir="/Users/username/public_html/demos/wordpress/public_html/wp-content/themes/understrap/node_modules/jpegtran-bin/vendor"
configure: error: installation or configuration problem: assembler cannot create object files.

    at ChildProcess.exithandler (child_process.js:282:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:947:16)
    at Socket.stream.socket.on (internal/child_process.js:368:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:598:12)

Hopefully with a few more testers this gulp issue can be updated.

**Comment by 0dp** [comment]
I just want to inform everyone, that the real deprecation warnings has to do with gulp v3.9 in order to kill those gulp-cli, local gulp needs to be upgraded to latest. Package.son needs to be upgraded with newest deps. Deprecated packages needs to be replaced. Finally gulfile.js needs to be upgraded.

Feel free to test my gulp4 branch

**Comment by dylannirvana** [comment]
I am still getting these in Terminal:
+ gulp@3.9.1
updated 1 package and audited 25551 packages in 13.878s
found 52 vulnerabilities (12 low, 32 moderate, 8 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ gulp -v
[20:44:15] CLI version 2.0.1
[20:44:15] Local version 3.9.1

**Comment by 0dp** [comment]
@dylannirvana since you we are not using any of the packages in the final dist of the theme you can ignore them. If you think otherwise feel free to `npm audit fix` them, if it does not resolve the 'issues' you will have to contact package authors 👍

**Comment by 0dp** [comment]
New update to my gulp4 branch https://github.com/0dp/understrap/tree/gulp4

**Comment by JulieRegan** [comment]
@0dp That is good news. I had the same terminal messages as @dylannirvana and spent ages trying to figure out what was going on.  Thanks for all the work on this theme.

**Comment by axlright** [comment]
@0dp sorry for crapping the bed repeatedly over the past few months. I've been rebuiling my whole operations' time tracking and billing and accounting system. Tried to stay focused on that so I ignored my people over at UnderStrap. I'm close to finishing up all that other distracting work. And man is it boring. So I can hopefully move attention back to you all.

Admittedly I am a total npm idiot. I can do what I'm told, though.

Just cloned your repo and threw it into my local testing environment. All is well with some warnings that seem to be the same as always with `npm install`. Thanks for all your help. Details below.

WordPress Version: 4.9.6
OS Version: OSX 10.13.5
Node.js : 9.11.1 (I can install any version via nvm if you need)
NPM: 5.6.0

```
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
Are the only warnings I get. No errors.

**Comment by 0dp** [comment]
All good fam.

**Comment by 0dp** [comment]
New gulp4 PR https://github.com/understrap/understrap/pull/883

**Comment by IanDelMar** [comment]
@Thomas-A-Reinert can be closed, no?

**Comment by Thomas-A-Reinert** [comment]
Yup.
