### ISSUE TITLE
Child theme isn't compiling variables

### ISSUE THREAD

**Issue by oyshiu** [understrap/understrap#625]
## Issue is about..
  - [x] I need help

## Please tell us about your environment:

  - WordPress Version: 4.9.x
  - OS Version: MacOsX
  - Language: S/CSS

---

I have been trying for a long time to change the _child_theme_variables.scss but with no success. I copied most of Bootstrap4 variables and I'm now trying to change them but the changes never show in the child-theme.css
I have gulp watch running and it doesn't give me any error. Everything looks fine but nothings changes in the CSS.

For example:

I add this to the _child_theme_variables.scss or to the _child_theme.scss and nothing happens
`//Fonts
$headings-font-weight:        700 !important;`

but if I add this to the _child_theme.scss it updates the CSS:
`h1, h2, h3, h4, h5, h6 {
  font-weight: $font-weight-bold;
}`

Any idea?

Thanks

**Comment by Thomas-A-Reinert** [comment]
Please notice that this issue-tracker is only dealing with the parent-theme. If you have any issues with the child-theme please refer to [this repository](https://github.com/understrap/understrap-child).

Thanks! I´m also closing this issue.
