### ISSUE TITLE
child theme and gulp

### ISSUE THREAD

**Issue by mherda** [understrap/understrap#626]
Hi,

Please bear with me - things are still cloudy for me:)
I've started a child theme so the only files in the child theme folder are functions.php and styles.css

Which files/folders exactly would I need to copy to the child folder to be able to install packages ('npm install') and then edit js/scss and compile it (gulp watch-bs) in the child theme directory?

Thank you

**Comment by Thomas-A-Reinert** [comment]
Spare yourself the fuss and built up on https://github.com/understrap/understrap-child
