### ISSUE TITLE
Why I dont have gaps here?

### ISSUE THREAD

**Issue by jack-fdrv** [understrap/understrap#633]
![Image of CssBug](https://src.fdrv.guru/180407192810.jpg)

**Comment by holger1411** [comment]
Is solved and will be shipped with 0.8.2
You can alreay download and use the version here from GitHub (hit the "clone and download" button here: https://github.com/understrap/understrap)

**Comment by jack-fdrv** [comment]
My theme is up to date but it doesnt have gaps. Where I can see by which commit it solved? Or I can do this manually.

**Comment by holger1411** [comment]
0.8.2 isnt relased yet.
So:
"You can alreay download and use the version here from GitHub (hit the "clone and download" button here: https://github.com/understrap/understrap)"

**Comment by holger1411** [comment]
The Github version is the "bleeding edge" version.
Means the one which will be released soon

**Comment by jack-fdrv** [comment]
Oh, thank you! Fixed! Thanks for let me know how to fast download it =)

**Comment by Thomas-A-Reinert** [comment]
Please just acknowledge - as @holger1411 said - this is a "bleeding edge" version and may therefore not be totally tested and up to changes before release to the WP-repository. This will allow you to test (and please comment on bugs!) the latest version but it _may_ have bugs though.

No guarantees ;)

**Comment by jack-fdrv** [comment]
Oh, that what means "bleeding edge"... 

Hmmm. How I can find the way to help you with test and dont catch the bug on live server =)

**Comment by Thomas-A-Reinert** [comment]
Personal side-note: NEVER EVER develop on a live-server! Use a development environment, develop there, test there and if everything seems good to go - use a staging environment (google that please). If everything also works well there - deploy on a live-server ;)

Bleeding edge/cutting edge means - latest version, possibly not completely free from bugs, but including all the latest features..

**How to set up a staging environment:**
- https://developer.wordpress.org/themes/getting-started/setting-up-a-development-environment/ (Official WP Codex)
- https://www.elegantthemes.com/blog/tips-tricks/the-ultimate-guide-to-setting-up-your-wordpress-development-environment (probably the more helpful version)

**Comment by jack-fdrv** [comment]
I am working on the test server. And dont see any errors. But I am no unit test...

**Comment by holger1411** [comment]
Fix was released with 0.8.2. So I´am closing this issue.
