### ISSUE TITLE
Owl Carousel not working (...is not a function)

### ISSUE THREAD

**Issue by nuriye** [understrap/understrap#636]
Hi!
I have the understrap & child theme.
Tried to use the owl carousel - you say it's built in - does that mean that i can use the slider in my js like this?
` jQuery('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
    }
});`
Because it seems like the function can't be found. My Console keeps telling me "jQuery('.owl-carousel') is not a function".

PS: I am using the carousel in the code.

Also: I would really love to know how to even use the slider in a page in the backend. Can't find how to add one...

**Comment by holger1411** [comment]
The owl carousel was removed some time ago. 
It was replaced by the default Bootstrap carousel in UnderStrap 0.5.4

**Comment by kemie** [comment]
Just a note- might be useful to remove references to Own in the docs and acknowledgements. That made me think it was part of the package too.

**Comment by Thomas-A-Reinert** [comment]
I totally agree- some party REALLY DO suck! Too many places to improve actually. Please bear with us as we´re actually trying to improve README´s, Documentation and such.  Coming up soon (no promises being made on that one, but we´re working on it, okay?)

**Comment by nuriye** [comment]
That would be really really great! I could not find any documentation or good readme for the theme!

**Comment by xicubed** [comment]
Might also need to take Owl references out of core-understrap child theme as I got an error which firing up gulp watch-bs... I had to comment out:
`// @import "assets/owl-carousel2"; // <------- Owl Carousel2 slider styles`
in the sass/child-theme.scss file
