### ISSUE TITLE
Navbar must be outside any container or div to work properly

### ISSUE THREAD

**Issue by cetorres** [understrap/understrap#640]
Following Bootstrap concept, Navbar must be outside any container or div to work properly. For example, for class sticky-top work (navbar sticks to the top), it must be like that. So I moved it below <body> tag, above other divs and containers and it worked.

**Comment by cetorres** [comment]
And please add the class sticky-top to navbar by default.

**Comment by holger1411** [comment]
No: 
http://getbootstrap.com/docs/4.1/components/navbar/#containers
There can be an outside or inside container. Bootstrap handels both very well.

And .sticky-top or .fixed-top can be added to the outside container as well. It is not a component exclusive class.

**Comment by holger1411** [comment]
Closing this. But feel free to re-open if there are questions left.
