### ISSUE TITLE
Save button has disappeared on widgets

### ISSUE THREAD

**Issue by jack-fdrv** [understrap/understrap#641]
![Image of bug](https://src.fdrv.guru/180414083450.jpg)

**Comment by holger1411** [comment]
Strange thing. The class itself is a WordPress class and isnt changed by UnderStrap.
And it works without problems on our demo site. Latest WP version and latest UnderStrap version.

Does it happend on all widget areas or just on "Footer Full"?
I renamed this position yesterday. And if you use the bleeding edge version from here (the upcoming 0.8.3 release) it might cause this trouble if it just appears here.

Does the problem still appears if you switch to another default WP theme?

**Comment by jack-fdrv** [comment]
Sry, it was my mistake. by adding to the new class`public function form( $instance ) {}` which extend WP_Widget is fixed.

**Comment by holger1411** [comment]
👍
