### ISSUE TITLE
Gulp Watch initialization (Global)

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#645]
Please delete anything that does not apply for you!

## My issue:
  - [ ] A question in regards to initializing Gulp watch from a global standpoint

## My environment:

  - WordPress Version: 4.9.5
  - Browser: [ Chrome 65]
  - Node.js & NPM Versions: Node.js [V 8.10] | NPM [V 5.8.0]
  - UnderStrap-master.zip 0.8.2

## My steps:

I'm processing steps noted [here](https://understrap.github.io/).

I have understrap officially installed as a starter theme in my wordpress environment.  I am now trying to figure out how to initialize gulp in my environemnt.  I have both node and npm installed.  When I go to my root location of my wordpress site, which is...

`http://local.training/wordpress/starterthemes/understrap/` 

Through the terminal, I go to that root folder of that URI location and process the following:

`npm install --global gulp-cli`

I can now see that gulp-cli@2.0.1 is installed, and added 238 packages, and see it listed when I run 
`npm ls -g --depth=0`.  It's there.

Next, I add the following code to my gulpfile.js file

```
var browserSyncOptions = {
    proxy: "local.training/wordpress/starterthemes/understrap/",
    notify: false
};

```
Next, when I attempt to run **gulp watch-bs**, I get the following message:

```
[11:38:02] Local gulp not found in ~\Documents\mTraining\wordpress\starterthemes\understrap
[11:38:02] Try running: npm install gulp
```
From the terminal , I also attempted to `cd` into my `wp-content/themes/understrap-master` folder location, and run the same command.  But I get the same message.

What I am doing wrong?

**Comment by 0dp** [comment]
gulp4(gulp-cli) is not yet supported, try and downgrade to gulp3.9
Or you can try the gulp file here:

`https://github.com/0dp/understrap/blob/gulp4/gulpfile.js`

and package.json here:

`https://github.com/0dp/understrap/blob/gulp4/package.json`

**Comment by blachawk** [comment]
I removed my previous gulp verison.  I installed gulp 3.9 with the following command:
`npm install --g gulp@3.9
`

I then ran the following command:
`gulp watch-bs
`

But I get the same message:
```
[13:08:35] Local gulp not found in ~\Documents\mTraining\wordpress\starterthemes\understrap
[13:08:35] Try running: npm install gulp
```
still stuck

**Comment by blachawk** [comment]
I'm golden now.  Here are the steps I took to fix my issues:

* My understrap-master.zip theme is fully installed in WordPress
* Installed a global version of Gulp 3.9:
 `npm install -g gulp@3.9`
* From the terminal, I set my path to my themes folder location:
`~/Documents/mTraining/wordpress/starterthemes/understrap/wp-content/themes/understrap-master`
* I went into my globalconfig.json file and made sure that my **proxy** location was reflecting my site URI:
```"proxy": "local.training/wordpress/starterthemes/understrap/",```
* Sense I'm working in Visual Studio Code (with it's terminal), I pressed **F1** to create a new task.json file with the following actions:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "gulp",
            "type": "shell",
            "command": "gulp"
        }
    ]
}
```
* I can confirm I have BrowserSync installed
* From the terminal I can now run **gulp watch-bs**

Done!   I can now make modifications to my files, and see the browser reload in real-time.

I'm good to go now.  Many thanks!

**Comment by Thomas-A-Reinert** [comment]
Hi @blachawk  - first, I´ll be closing that issue due to the fact that you seemed to resolve it on your own.

But let me ask some questions, if you don´t care.
Migrated to VS Code some time ago and really like it. Still don´t know the smartest ways to work with it.
Did the whole command-line stuff from well - the command line so far.

- So - when I press F1 VSC opens a LONG list with possible commands - which one did you executeto create your task?
- What are the single entries good for? (version/label/type/command)
- How do I run that task?

Thanks in advance for any clarification!
