### ISSUE TITLE
Best practices for removing unused assets to reduce weight/"bloat"?

### ISSUE THREAD

**Issue by jaredsnider** [understrap/understrap#646]
## Issue is about..
  - [ ] a Question
  - [ ] I need help

---

I am about to tackle this for my site and figured it could be helpful to others so I figured I should inquire here first. Maybe this is an @axlright question? Just wondering the best method for stripping out Bootstrap stuff I am not using, preferably in a "non-destructive" way so I am doing it somewhere that won't get easily overwritten bu theme updates and so I can bring it back when needed at a later date. I assume this would involve commenting out the relevant Bootstrap assets from somewhere in the child theme (?) but unsure where the best place to do that is (asset links scss, gulpfile, etc). If someone can point me in the right direction in this regard it would be much appreciated. This could generally be a useful component of Understrap as the big complaint around Bootstrap is adding unnecessary page weight to your site. Basically all I use is the Grid, Typography and Button styles at the moment, though I do like having the full framework available I am sure I am forcing my users to download a lot of stuff the site doesn't actually use. Given my site is image heavy I want to streamline things as much as possible. Really appreciate any help in this regard and also very much appreciate everyone's efforts building such a great tool.

**Comment by jaredsnider** [comment]
I believe 'assets/bootstrap4.scss' works for commenting out unused SCSS (assuming that covers it but not positive)... I guess I would be more lost in getting rid of any unused JS assets from the theme.

**Comment by axlright** [comment]
Yes like @jaredsnider said, when I get to the end of development before publishing live, I go through `assets/bootstrap4.scss` and comment out elements the project doesn't use. This was done in Bootstrap3's online configurator in a similar way. Here's an example of a project getting published today:

```
/*!
 * Bootstrap v4.1.0 (https://getbootstrap.com)
 * Copyright 2011-2018 The Bootstrap Authors
 * Copyright 2011-2018 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 */

@import "../../src/sass/bootstrap4/functions";
@import "../../src/sass/bootstrap4/variables";
@import "../../src/sass/bootstrap4/mixins";
//@import "../../src/sass/bootstrap4/root";
@import "../../src/sass/bootstrap4/reboot";
@import "../../src/sass/bootstrap4/type";
@import "../../src/sass/bootstrap4/images";
//@import "../../src/sass/bootstrap4/code";
@import "../../src/sass/bootstrap4/grid";
@import "../../src/sass/bootstrap4/tables";
@import "../../src/sass/bootstrap4/forms";
@import "../../src/sass/bootstrap4/buttons";
@import "../../src/sass/bootstrap4/transitions";
@import "../../src/sass/bootstrap4/dropdown";
//@import "../../src/sass/bootstrap4/button-group";
@import "../../src/sass/bootstrap4/input-group";
@import "../../src/sass/bootstrap4/custom-forms";
@import "../../src/sass/bootstrap4/nav";
@import "../../src/sass/bootstrap4/navbar";
// @import "../../src/sass/bootstrap4/card";
// @import "../../src/sass/bootstrap4/breadcrumb";
// @import "../../src/sass/bootstrap4/pagination";
// @import "../../src/sass/bootstrap4/badge";
// @import "../../src/sass/bootstrap4/jumbotron";
// @import "../../src/sass/bootstrap4/alert";
// @import "../../src/sass/bootstrap4/progress";
// @import "../../src/sass/bootstrap4/media";
@import "../../src/sass/bootstrap4/list-group";
@import "../../src/sass/bootstrap4/close";
@import "../../src/sass/bootstrap4/modal";
// @import "../../src/sass/bootstrap4/tooltip";
// @import "../../src/sass/bootstrap4/popover";
// @import "../../src/sass/bootstrap4/carousel";
@import "../../src/sass/bootstrap4/utilities";
@import "../../src/sass/bootstrap4/print";
```

**Comment by Thomas-A-Reinert** [comment]
@axlright is absolutely correct in mentioning that´s the (ony) way to do it. Up to now.

But I´m experiencing the same problem with a current project. And I know that those settings will prolly get lost with the next update again.

Suggestion:
1. We should set up a "Bootstrap-component loader" in "themes/understrap-child/sass/theme" that loads any component by default but has good instructions on how to disable them (comment them out) and which component gets addressed (maybe with a link to the component in question) and won´t get overwritten with an update of the parent/child theme.
2. Handling that through the standard loader/importer will cause bloat for a load of installations.

**Comment by ZacharyElkins** [comment]
Idk about child themes. 

For the parent theme commenting out the CSS files works just fine. 

However, the JS files are not separated, as Understrap uses the single Bootstrap JS file. It would have to be switched out with the Bootstrap JS source files, including a file which loads them all for commenting out the unused components. 

Maybe something a bit fancier could be made?

**Comment by axlright** [comment]
@Thomas-A-Reinert I don't think Bootstrap is gonna change that file very often. I've never had one of my custom `assets/bootstrap4.scss` get overwritten. It would take Bootstrap updating theirs then the Understrap team amending it to have the proper directory paths and I think that people who know enough to be slimming down their css this way will be on the lookout for Bootstrap then Understrap changing up a pretty key file. 

Said another way, of all the things I'm worried about in life, that's not high on the list. I support you automating it but I think that file will stay put for a while.

@ZacharyElkins I'd love to learn more about this - not using / commenting out unused js components. I'm not so js smart but I love slimming things down.

**Comment by jaredsnider** [comment]
Maybe loading the JS files individually in the `gulpfile` is the answer (then they could be commented out accordingly) as opposed to loading the whole folder. I might give it a shot, though I am admittedly not a master of the gulpfile.

**Comment by ZacharyElkins** [comment]
@axlright  I've started working on this, I'll update this post once I submit a PR. Already have it working, just need to work out the gulpfile changes. You're also correct that assets/bootstrap.scss rarely gets changed. By the way, the original Bootstrap version of this file can be found in understrap/src/sass/bootstrap4/bootstrap.scss

@jaredsnider  Give me a few days and hopefully what I propose works for everyone. Side note, how are you loading jQuery? If you don't know, Wordpress has it's own version of jQuery. When you enqueue jQuery in the theme you are actually using the version installed with Wordpress. One way to change this over is to deregister and then register your own jQuery file as jquery. This can create conflicts in the WP backend if a plugin isn't compatible with newer versions of jQuery. Alternatively, you can choose to not enqueue the WP version of jQuery in your theme and instead register your own version of jQuery under a different name, then use that for the front end and Wordpress will continue to use its own version for the backend. Let me know if you'd like some examples. Also, I don't think using multiple versions of jQuery simultaneously is recommended.

**Comment by jaredsnider** [comment]
@ZacharyElkins This is great, thank you for your work! I load `jquery-latest.min.js` in my footer, mainly to account for some some functionality that I can certainly live without and/or find a more simple (preferably non jQuery solution for)... at the moment I am an utter JS beginner. For now I am going to comment it out (trying to reduce the amount of resources loading anyways so its a good idea regardless).

**Comment by ZacharyElkins** [comment]
@jaredsnider Well, I thought jQuery was required for Bootstrap. Most or all of their JS uses jQuery, so if you use their JS you need some version of jQuery. 

Just load one version, preferably in the head as the rest of your JS will be dependent on jQuery being loaded first. You can always mark your JS as dependent on jQuery when you enqueue it and try to load them both on the footer. As long as it loads first.

You can use a newer version of jQuery if you want, or stick with the version shipped in WordPress. Both work with Bootstrap just fine. 

There are versions of Bootstrap that don’t use jQuery, but idk if they have it for Bootstrap 4 yet. 
http://thednp.github.io/bootstrap.native/

**Comment by shansmith01** [comment]
Has anyone had a go at using something like uncss in their workflow? https://github.com/ben-eb/gulp-uncss. Or 

https://github.com/purifycss/purifycss
https://github.com/FullHuman/purgecss

I had a play a few months ago but getting things working was a bit beyond me

**Comment by 0dp** [comment]
it's an interesting suggestion for the dist task @shansmith01 
I have no experience with something like this, and I expect it needs extensive testing. Just becasue treeshaking could break stuff

**Comment by typeplus** [comment]
@shansmith01 I asked about uncss a few months ago and got it working but it is quite bespoke and isnt at all accurate. I found it would remove things the site actually needed and could never pin down each cause.

**Comment by axlright** [comment]
I had thought that that uncss would need a list of every page / page template in your project to figure out what css is needed and what isn't. Looking at 
```
 uncss({
            html: ['index.html', 'posts/**/*.html', 'http://example.com']
        })
```
it seems like with a WordPress / php workflow, you'd need to supply the list of fully formed local urls of every page / page template. Doing so isn't so bad - we do that with our Critical CSS workflow - more curious than anything.

Also, I'd imagine you'd need to be able to force include classes that get used via scripts.

All in all though this would be a cool thing to document if anyone gets it down.

**Comment by jaredsnider** [comment]
Would go a long way towards appeasing all the "Bootstrap = Bloat" haters 😁

**Comment by ZacharyElkins** [comment]
@jaredsnider I've submitted a PR to address this issue.
https://github.com/understrap/understrap/pull/667

It uses the individual JS files provided by Bootstrap in their `js/dist` folder.

The thing to note here is that these files are already compiled to be used individually, which means a little extra code in each module.

The alternative way of doing this is using Babel/Rollup to compile the individual files together the way Bootstrap does. I may submit a different PR soon that implements this method, however, it does install several devDependancies and requires an extra gulp task.

**Comment by 0dp** [comment]
Interesting idea.
Personally, I think you should hold back the Babel/rollup version. If we are supposed to support ecma2015+ looking forward, there is all of the sudden a lot of stuff we can and should update and implement, refactor and so on. I'm welcoming the idea though :)

**Comment by ZacharyElkins** [comment]
@0dp This is my thinking as well. It is quite a lot of extra to add for one feature, although quite a great feature.

**Comment by Thomas-A-Reinert** [comment]
I reckon that this (the whole string-issue) is no REAL perfomance issue.  And I can confirm this, if neccessary. Anyway, the "performance tools" rate it as a real issue.

I´d love to have that fulfilled. But it doesn´t have an impact on UnderStrap performance anyway. The way we gonna handle that in the future seems a good way to go imho.

Gonna close that issue for the time being.  PLEASE feel free to reopen that issue or comment on it. I´m really eager to improve the current situation! ;)
