### ISSUE TITLE
UnderStrap is outdated in WordPress repo

### ISSUE THREAD

**Issue by manacim** [understrap/understrap#652]
I can confirm this. I downloaded the zip file from the website, pagination.php exists in global-templates. This fixes the issue of hiding the next page arrow when on the last page.

When I update it via WordPress plugin page, the pagination last page arrow gives me a 404.

**Comment by Thomas-A-Reinert** [comment]
Easy - what you find here is the very latest, development "cutting edge" version. It is updated with every single code-submit.
What you find within the WP-Repo is the latest "stable" version. So no, it´s not "outdated".
