### ISSUE TITLE
UnderStrap core files for major theme updates

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#654]
## Issue is about..
  - [x] a Feature Request
  - WordPress Version: 4.9.x
  - OS Version:Windows 10
  - Browser: [ all |
---

Look for a tutorial or guide that will help me to customize UnderStrap as much as my heart desires,  **without modifying UnderStrap core files**, this way when I have to do upgrades in the future for the starter theme, implementing changes will not be as painful.  Do you have anything like this available? Looking for any learning resources. 

Many thanks

**Comment by Thomas-A-Reinert** [comment]
Hi @blachawk . Well you´re right - we could in fact improve on documentation. That´s a topic I´m currently investigating on how to improve.

Besides: It´s just like with almost any other WordPress theme.
The child inherits almost anything from its parent.
Exception/s with UnderStrap: The child deregisters it´s parents styles and scripts and therefore become independant from them and also doesn´t load them twice.
So if you want to customize styles/scripts: Use the workflow within the child and you´re good to go.
If you want to overwrite any of the parents php-files - copy them into your child and override whatever you want.
If there´s any function in the parent: just use the same function name and register it. The parent will check if the function is not already registered/enqueued and will therefore not overwrite it.

In case you got any more questions - feel free to ask. I´ll take it as an inspiration for the docs then, okay?

**Comment by blachawk** [comment]
All sounds wonderful.  Is installing the child theme just as easy as simply getting the .zip file from the understrap web site and extracting it into `wp-content/themes/` folder? Or are there more steps to that?  anything with npm I have to do, to get the child theme registered with the Parent theme?

Many thanks!

**Comment by Thomas-A-Reinert** [comment]
No that´s exactly it.
You´d need to switch your active theme to the understrap-child, sure. In case you altered many things in the customizer I´d recommend exporting the parent themes´ settings through some plugin like [Customizer Export/Import](https://wordpress.org/plugins/customizer-export-import/).

About npm and such, you can find a (pretty barebone) documentation on [understrap-childs](https://github.com/understrap/understrap-child) page. But it´s almost the same as with the child and has the same tasks integrated.

Once you only integrate ANY alteration in your own child - you can update the parent without (all fingers crossed) problems. Anyway - I´d not recommend to do that on a live site as we´re really still developing and improving the parent as well as the child. So both are still "in production".
Do that on a dev-server and check if everything goes well ;)
