### ISSUE TITLE
Installing mutliple instances of UnderStrap into a single WP CMS

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#655]
## Issue is about..
  - [x] a Question

Is it ok for me to install multiple instances of UnderStrap into a single WP CMS?  I'm doing so, so I can compare development versions from Visual Studio Code and npm processing from the terminal.  If this is cool to do? If so, what naming conventions are recommended for the .zip files before I add them into WordPress?

Many thanks

**Comment by Thomas-A-Reinert** [comment]
Personally I wouldn´t do so and it shouldn´t be impossible without doing several tweaks I´d really not recommend.

In my scenario on a localhost I have two different WordPress installations. One with the latest version and another with the version I want to compare with. I do a DIFF (with Tools like WinMerge under Windows for example) between those versions then and try to find out where the differences and their caveats are.

**Comment by blachawk** [comment]
Many many thanks on your setup recommendation - I was looking for that!

**Comment by Thomas-A-Reinert** [comment]
Sorry, I said "impossible" above but meant "possible". Corrected already.

Besides - you´re always welcome!
