### ISSUE TITLE
What is the best way to show the right sidebar ONLY on the WooCommerce Shop page?

### ISSUE THREAD

**Issue by patrickritskes** [understrap/understrap#656]
## Issue is about..
  - [x] a Question
  - [x] I need help

**Comment by Thomas-A-Reinert** [comment]
Hi Patrick,

i´d recommend building your own template based on  page-templates/both-sidebarspage.php maybe.
There you can already see an if-conditional to check for a right sidebar. See [WooCommerce Docs](https://docs.woocommerce.com/document/conditional-tags/) for any conditional on how to check for them. `is_woocommerce()` will probably do the job but could also handle that more fine-grained.

**Comment by patrickritskes** [comment]
Hi Thomas,

Thanks for your reply on this
I indeed create my own template, and did a check with `is_shop()` and `is_product()`.

This works well right now, thanks!

**Comment by Thomas-A-Reinert** [comment]
No problem, you´re welcome. `is_woocommerce()` reflects _any_ Woo-page except checkout and cart, but you can have that more fine-granulated as you did..

I´ll close this issue but feel free to re-open if any problem remains in this context.
