### ISSUE TITLE
Purpose for itemtype on element in header.php

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#657]
## Issue is about..
   - [x] a Question
  
What is the purpose of the following in the header.php file, on the `<div id="wrapper-navbar">` element? 

`	<div id="wrapper-navbar" itemscope itemtype="http://schema.org/WebSite">
`

**Comment by axlright** [comment]
@blachawk It's a generic opening Structured Data element. Here's more about Structured Data:
https://moz.com/learn/seo/schema-structured-data
https://developers.google.com/search/docs/guides/intro-structured-data
https://moz.com/blog/structured-data-for-seo-1

**Comment by Thomas-A-Reinert** [comment]
Always worth trying to do a research via google before opening an issue. See https://www.google.de/search?q=schema.org%2FWebSite

**Comment by blachawk** [comment]
Thank you @pattonwebz for breaking down the purpose in an easier to understand way than what I have researched on the web, and also for the honesty on the progression.  Much appreciated.
