### ISSUE TITLE
Clarity on UnderStrap being Contact Form 7 ready

### ISSUE THREAD

**Issue by blachawk** [understrap/understrap#658]
## Issue is about..
  - [x ] a Question
 
When you guys say that UnderStrap is Contact Form 7 ready, you guys mean that it's 'SASS' ready, correct?  I would still install Contact Form 7 normally in WordPress if I need it, but if I want style it, UnderStrap already provides the SASS process for it.  

Just trying to get clarity there.  Thanks!

**Comment by Thomas-A-Reinert** [comment]
Well, worth a try, don´t you think?

**Comment by blachawk** [comment]
I think Contact form is one of the best forms for webpress and for you guys to make it sass ready is awesome.  keep it going!
