### ISSUE TITLE
datatables include

### ISSUE THREAD

**Issue by 3derbauer** [understrap/understrap#660]
how i can include datatables.js?

**Comment by Thomas-A-Reinert** [comment]
We offer an issue template to gather best possible information about your environment and problem.
 
This question is so generic and provides as little information that I can just provide an equally alike answer: via `functions.php`.

**Comment by pattonwebz** [comment]
@3derbauer are you looking for a method to install `datatables.js` though a package manager like NPM and then have it copied into the theme automatically by the gulp scripts in the theme?

That would not be a huge change to the theme code but I don't think it is a change that would ever make it's way into the main theme repo.

**Comment by Thomas-A-Reinert** [comment]
From my experience I can tell you: It won´t ;)

 @3derbauer : Quick solution for a _static_ solution.
Copy that script into `./understrap/js`. Take a peep into `./understrap/inc/enqueue.php` and enqueue your script as desired, for example: 		`wp_enqueue_script( 'datatables-js', get_template_directory_uri() . '/js/datatables.js', array(), $theme_version, true);`

within the 	`function understrap_scripts() {}` section.

If you want to have that one updatabale via composer/bower/npm that would need some more adjustments.

**Comment by Thomas-A-Reinert** [comment]
I´ll be closing that one for housekeeping as any neccessary information seems to be provided and no information about the problem provided.
