### ISSUE TITLE
Reinitialising scripts after ajax call

### ISSUE THREAD

**Issue by pcarter13** [understrap/understrap#664]
I am using the jQuery .load() function to access page content without a refresh (not the depreciated .load, the ajax one). However, all my scripts get lost on the ajax call – as expected.

As all the JS is compiled into one file through Gulp, I was wondering if there's an easy way to call and reinitialise the whole file?

**Comment by 0dp** [comment]
getScript() maybe?

**Comment by pattonwebz** [comment]
Could another solution be to only replace part of the content currently on the page with part of the same part on the fetched page? For example #main -> #main but leaving header and possibly the footer intact?

Is there a reason that method would not be viable?

**Comment by 0dp** [comment]
It should be possible.
There is plenty of resources out there to get you started with Ajax in WordPress. If I were you I would check out some general and WordPress specific tutorials about Ajax. There are also free themes you can checkout and investigate how they implemented the solution.

**Comment by axlright** [comment]
Closing this ticket for housekeeping as it's not had a reply from the original poster and because it's not related to a bug in Understrap. Comment back if the issue should be re-opened.
