### ISSUE TITLE
German localisation

### ISSUE THREAD

**Issue by DUGeCommerce** [understrap/understrap#670]
## Issue is about..
  - [x ] a Question
  - [x ] I need help

## Please tell us about your environment:
  - **WordPress Version:** 4.9.5
  - **OS Version:**  Windows 10
  - **Browser:** [ all ]
---

Hi. I have a little problem.

I build a German WP-site. The WP installation is in German (BE) but in the FE it is in English. For Example: "**Posted on** Mai 7, 2018 (Mai 7, 2018) **by** xyz".
A search in Google says that this is a theme problem. How can I change this?
Sorry for that "easy" question, but I can't find it (Grrrrrr.....).

**Comment by 0dp** [comment]
Hey @DUGeCommerce, iterrestion enough I just checked on a fresh UnderStrap and the frontend is being translated correctly:  Veröffentlicht am März 23, 2018 (März 24, 2018) von admin	

What version of UnderStrap are you using?
Is the language folder present in the theme folder at the moment?

**Comment by Thomas-A-Reinert** [comment]
thx @0dp for trying to satisfy the german community - i been to busy for the past few days ;)
But I guess it´s gonna be easier if i´ll take over..


Hallo @DUGeCommerce 
Zunächst einmal: ich kann das Problem auch nicht reproduzieren, da ich zuletzt Änderungen am deutschen Lang-File vorgenommen und es ausführlich getestet habe. 

Siehe Screenshot:
![image](https://user-images.githubusercontent.com/5886977/39898842-f5a110ac-54b8-11e8-80cd-b8f462307f84.png)

Die wichtigste Frage wäre auch von meiner Seite: Welche Version nutzt Du? Die von WordPress? Oder hast Du die aktuellste Version hier von GitHub gezogen? Ich kann nicht für die WP-Version sprechen, aber die GH-Version sollte auf dem letzten Stand sein. Und auch alle möglichen Strings übersetzen.

Wäre nett, wenn Du mir dbzgl. eine Info geben könntest - rein für uns, damit wir evtl. nachbessern können.

Ansonsten hast Du immer noch die Möglichkeit mittels "Loco Translate" Plugin (oder anderen) individuelle Übersetzungen zu tätigen. 

Und persönliche Nachfrage: Woher kenne ich DUGeCommerce? Ich hab da was auf dem Radar, kann es aber aktuell nicht zuordnen..?

**Comment by DUGeCommerce** [comment]
Hallo Thomas.

- WP 4.9.5 -> **Multisite** Installation (mit zwei Seiten)
- "understrap 0.8.2" (Parent)
- und in jeder Installation als Child "understrap 0.5.2"
- alle understrap-Pakete habe ich direkt "von hier" heruntergeladen (ca. drei Wochen)
- der language-Ordner ist im Parent-Theme vorhanden, jedoch nicht in den Childs (was ja korrekt ist)

DUGeCommerce = DUG (Abkürzung für eine Würzburger Firma) + eCommerce (die entsp. Abteilung)

Vielen Dank!

**Comment by Thomas-A-Reinert** [comment]
Hi @DUGeCommerce ,

das sind schon mal ein paar wichtige Infos, mit denen ich arbeiten kann.

- understrap 0.8.2 - ist schon einmal gut. Auch wenn wir dort ohne neue Versionierung _einiges_ getan haben. Es würde nicht schaden, da die neueste Version runterzuladen und die von euch runtergeladene dadurch zu ersetzen, insofern ihr daran keine Änderungen vorgenommen habt.
- understrap-child 0.5.2 - Nunja. Daran habe ich vor 27 Tagen (..) eine Änderung vorgenommen, die eigentlich genau dieses Problem lösen _sollte_! Das funktioniert bislang in all meinen Testumgebungen einwandfrei, aber.. bitte aktualisiere das Child-Theme bitte noch einmal mit der aktuellsten `functions.php`

Und ja, Du musst natürlich den `./languages/` Ordner anlegen und dort die entsprechende Übersetzung hinterlegen.

Sorry: aber ich "missbrauche" Dich an dieser Stelle als Test-Kaninchen. Wenn wir das aber für Dich / Deine Sprache lösen, haben wir es aber nicht nur Dein, sondern (hoffentlich) auch für die Sprachprobleme aller anderen User gelöst.

**Comment by DUGeCommerce** [comment]
Hallo Thomas.

Kein Problem, spiele das "Test-Kaninchen" - ich muss ja keine Karotte essen!

Aber.... **ich habe das Problem gefunden**:

- **Einstellungen**, **Allgemein** "**Sprache der Webseite**"
- hier war "**Deutsch (Sie)**" ausgewählt! **Die Umstellung auf "Deutsch"** hat die Anzeige im FE korrekt lokalisiert

Es lag somit **nicht** an einem veraltetem Code-Stand - der aber tatsächlich vorlag! Das konnte ich mit einem Abgleich der Verzeichnis feststellen. Einen Abgleich der Verzeichnisse habe ich jetzt **nicht** gemacht, somit ist das jetzt immer noch der Stand von vor drei Wochen. **Und es klappt jetzt.**

Und... der ./languages/ Ordner **musste nicht** im Child-Theme liegen, dass klappt so jetzt tadellos.

Vielen Dank für den Support!

**Comment by DUGeCommerce** [comment]
Noch ein Nachtrag:

- Deutsch (Schweiz)
- Deutsch (Schweiz, Du)

....lokalisieren ebenfalls in Englisch. Wohl dann das gleiche Problem wie Deutsch (Sie)

**Comment by Thomas-A-Reinert** [comment]
Oh, guter Hinweis und danke fürs Testen! Habe ich ehrlich gesagt noch nie versucht :) 

Für die deutsche Übersetzung mit "Sie" muss das language-file `de_DE_formal.mo` heißen, wie ich grade herausgefunden habe. Sollte die aktuelle Übersetzung also noch die Du-Form nutzen, einfach eine Kopie der existierenden deutschen .pot anlegen, umbenennen und nach "Du" suchen und die Strings anpassen. Anschließend als .mo kompilieren (entweder via Plugin Loco Translate oder Desktop Version PoEdit).

Mach ich aber später dann ohnehin noch und committe es, falls ich die Zeit finde.

Schweizerische Sprachfiles existieren bislang nicht - von daher ja: Fallback auf Englisch.

Hinweis auf das "./language" Directory im Child-Theme nur deswegen, damit bei einem Update des Parent nicht evtl. Deine Übersetzung überschrieben wird.

**Comment by DUGeCommerce** [comment]
Danke Thomas! Spitzen support! Da ich das jetzt weis - ich bleibe beim DU in WP.

**Comment by Thomas-A-Reinert** [comment]
Immer gerne, @DUGeCommerce . Formale Deutsch-Variante ist jetzt übrigens auch verfügbar.

**Comment by arumcomputer** [comment]
Hey, bei mir klappt die deutsche Übersetzung leider ebenfalls nicht. Meine Version ist immer aktuell, da ich das Theme immer aus Git direkt auschecke. Gibt es da etwas, was bei mir falsch ist? In keiner Installation klappt die Übersetzung.

**Comment by codearosa** [comment]
Ich habe ebenfalls das Problem. Bei mir betrifft es jedoch nur Instanzen für Woocommce.
