### ISSUE TITLE
Sidebar not responsive?

### ISSUE THREAD

**Issue by 3derbauer** [understrap/understrap#672]
Hello, i have problems with the sidebar. Why the sidebar is on outside from Content and not under? And why the row class not working for table colums with Chrome and Opera. With Firefox  the col Class for colums are working.   Sorry for my bad english. 
<a href="http://www.directupload.net/file/d/5083/pbq96cos_png.htm" target="_blank"><img src="http://fs1.directupload.net/images/180510/temp/pbq96cos.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

<a href="http://www.directupload.net/file/d/5083/o5plzdf2_png.htm" target="_blank"><img src="http://fs5.directupload.net/images/180510/temp/o5plzdf2.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by tonga73** [comment]
habrás modificado alguna clase pq por defecto no funciona así el sidebar. 

lo mismo con el row, asegúrate de que está dentro de un container (full o fluid), y en todo caso a modo de prueba agregale la clase "no-gutters" al row y si se te soluciona es porque algún margin o padding que agregaste está modificado los espacios. asumo que hablas español no se pq jaja de

pd. im assuming you speak spanish, sorry if you dont xd

**Comment by ZacharyElkins** [comment]
@3derbauer  You're referencing this page:
https://understrap.com/understrap/?page_id=155

Are you using any content blocking apps? Ad blocking or possibly script blocking? 

I know that Opera has multiple options to "speed up" websites, which generally means messing with content on the site. Please make sure this stuff is disabled for testing, and that your browser apps are up to date.

I doubt this is an Understrap issue, meaning it is more of a Bootstrap and/or browser related issue. It would be more helpful to post this to Bootstrap's Github.

See this page for Bootstrap browser support:
https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#mobile-devices

> Generally speaking, Bootstrap supports the latest versions of each major platform’s default browsers. Note that proxy browsers (such as Opera Mini, Opera Mobile’s Turbo mode, UC Browser Mini, Amazon Silk) are not supported.

For mobile, Opera is not supported. Chrome, however, is supported.

@tonga73 I think it is German, not Spanish.

@3derbauer Here is a German translation of my comment (2nd link gives a preview of the linked URL for your safety - it's just Google translate):
https://tinyurl.com/yc82bqzm
https://preview.tinyurl.com/yc82bqzm

**Comment by 3derbauer** [comment]
Yes, i´m from Germany. 
My Screenshots are from the Demosite with my Android Browser. 
https://understrap.com/understrap/?page_id=1133

No ad blocking or possibly script blocking.
I mean, it is a Problem from the template and not from the browser. On all Pages from the Understrap Demo site i have the Problem. The Sidebar is outside from Content / Browser View.

**Comment by Thomas-A-Reinert** [comment]
Thanks for jumping in @tonga73  (sorry I don´t understand spanish) and @ZacharyElkins  - i´ll take over from now as a native german speaker ;)

Hi @3derbauer - ich helfe dir gerne. Kann allerdings dein problem nicht ganz reproduzieren. Hab Deinen letzten Link (Id=1133) aufgerufen und kann unter Chrome mit Dev-Tools nur folgende Ansicht reproduzieren:
![image](https://user-images.githubusercontent.com/5886977/39898139-d0af179c-54b5-11e8-9da1-a6dba4ba0328.png)

Demnach scheint alles wie gewünscht zu funktionieren.

Ist natürlich eine Frage, welchen Viewport Du eingestellt hast etc. pp. Hast Du das Ganze mal auf einem "echten" Gerät getestet? 

Ehrlich: ich habe mittlerweile rund 30 Themes auf Basis von UnderStrap erstellt, aber auf keinem dieser Themes gab es Meldungen seitens des Kunden bzgl. dieses Problems. Egal ob unter Android, iOS, Windows, Linux oder MacOs.

Fragen:
- Hast Du irgendwas am Theme verändert?
- Gibt es eine Möglichkeit das zu reproduzieren?

**Comment by Thomas-A-Reinert** [comment]
No Feedback within a week, so I´ll close this. Feel free to reopen.
