### ISSUE TITLE
GitHub Theme URI should point to current repo 

### ISSUE THREAD

**Issue by afragen** [understrap/understrap#675]
In the `style.css` headers, the `GitHub Theme URI` should point to this repository. So it should be `GitHub Theme URI: understrap/understrap`

It works because GitHub does the redirect, but I’m not sure I’d count on it long term.

**Comment by Thomas-A-Reinert** [comment]
Yes, you´re absolutely correct. The link points to the old repo. Fixed this and some other misleading URI´s too.
