### ISSUE TITLE
browser sync Stuck at Reloading Browsers...

### ISSUE THREAD

**Issue by nachoumaran** [understrap/understrap#681]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

 * WordPress Version: 4.9.6
* OS Version:high sierra 10.13.4
* Browser: Chrome 66.0.3359.181
* Language: [ PHP | CSS]
* Node.js & NPM Versions: Node.js [6.10.3] | NPM [5.3.0]

---

Issue Overview for Bug reports
browser sync keeps Reloading Browsers... and dont show server
Steps to reproduce?
1. Install Browser-Sync
2. on terminal gulp watch-bs 

Expected behavior
Browser-Sync should be show livereload

**Comment by BenRed82** [comment]
I'm also experiencing this issue, is there any fix? Thanks!

**Comment by haydenkibble** [comment]
Same here.
Latest version of Chrome on Ubuntu 18.04
