### ISSUE TITLE
Stripe input fields for CC payment are unusable

### ISSUE THREAD

**Issue by staceycordoni** [understrap/understrap#682]
## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **OS Version:** MacOS 10.13.3
  - **Browser:** all
  - **Language:** PHP

---

# Issue Overview for Bugreports

## Steps to reproduce?

1. Enable Stripe Payment Gateway in WooCommerce Settings
2. Go to front-end of website, add an item to cart
3. Checkout, scroll down to area where Credit Card Details are entered

## *Who* is the bug affecting?

All users trying to checkout with WooCommerce and Stripe payment gateway.

## *What* is affected by this bug?

Taking Credit Card Payments. The form fields aren't usable so no one can checkout using Stripe as their payment gateway. Screenshot: https://d.pr/i/wmdQVt

## *When* does this occur?

At Checkout

## *Where* on the platform does it happen?

There's an issue with the understrap theme, as this doesn't happen on Twenty Seventeen

## *How* do we replicate the issue?

1. Enable Stripe Payment Gateway in WooCommerce Settings
2. Go to front-end of website, add an item to cart
3. Checkout, scroll down to area where Credit Card Details are entered

## Are there any related Issues and/or PRs?

I don't believe so, no.

## Screenshots / Video

https://d.pr/i/wmdQVt

## Expected behavior

Text inputs should be usable.

# Todos

 * Test
 * Documentation

**Comment by 0dp** [comment]
From the top of my head I believe you can fix the issue by adding width: 100% to the Stipe input fields' css

**Comment by staceycordoni** [comment]
I've tried this to no avail: https://d.pr/i/bcNhJR

**Comment by 0dp** [comment]
```
.woocommerce-checkout .StripeElement {

    width: 100%;

}
```

**Comment by benjaminsmth** [comment]
I had the same issue. You can also fix this in the Woocommerce Stripe Checkout settings by selecting:
Inline Credit Card Form

**Comment by 0dp** [comment]
I'm not by my computer right now, bit as soon as I sit down I will take a look at what's missing.

**Comment by staceycordoni** [comment]
I'm using the latest version of understrap (untouched) and my results are different than yours. By default, this is what I see:
https://d.pr/i/ElrECu

When I add the following CSS:

`.woocommerce-checkout .StripeElement {

    width: 100%;

}`

The Card Number field still remains small: https://d.pr/i/9vbQ6

Adding !important doesn't change anything either.

**Comment by benjaminsmth** [comment]
I'm using understrap 0.8, but have installed the woocommerce templates from the latest release into my child theme folder.

I tested this morning in Chrome it worked for the expiration and CVC fields but not for the main credit card number ( getting same error as reported). In Firefox, all the fields were not working. 

I will try again later.

**Comment by 0dp** [comment]
Ok, interesting. I will look into it

**Comment by 0dp** [comment]
For the card field `.stripe-card-group { 100%; }`

**Comment by staceycordoni** [comment]
.stripe-card-group { width: 100%; }

Perfect, thank you! :)

**Comment by staceycordoni** [comment]
This was the final CSS I ended up using, as it's also in the My Account section > Saved Payment Methods:

.stripe-card-group,
.woocommerce-account .StripeElement,
.woocommerce-checkout .StripeElement {
    width: 100%;
}

**Comment by benjaminsmth** [comment]
Thanks! That did it.

**Comment by 0dp** [comment]
What we should try and figure out is,
1. What is causing this in the first place? 
1. Does it affect other woocommerce gateways or just stripe? 
1. Is it a fix that should be included in the theme?

**Comment by ZacharyElkins** [comment]
@0dp I’m going to look into any additional templates to include that we may be missing from Understrap. Not 100% sure if the stripe billing is related, but it might be.

Either way I’m trying to test Woo as much as possible for missing support.

**Comment by walidhalabi** [comment]
Some info that might help you all

I'm having precisely the same problem as @staceycordoni - identical in that even adding the width: 100% to .woocommerce-checkout .StripeElement still leaves the card field 1px wide, etc etc.

But here's the thing, I'm not using understrap - I'm using roots/trellis with a custom theme.

So the problem might be with Woo itself.

HTH

**Comment by seatexboards** [comment]
I had a different problem, I hope somebody can help me... Just check here https://ibb.co/haTQg8
Looks like I can't type anything inside the fields.
Using Firefox/Safari ... I not an expert so if somebody can help me it's really appreciated @staceycordoni 
The website address: www.seatexboards.com/shop/  

Thank you

**Comment by 0dp** [comment]
@seatexboards 
Your fields looks just fine. Not like the screenshot
<img width="1151" alt="screen shot 2018-07-26 at 23 53 39" src="https://user-images.githubusercontent.com/3642367/43290704-37fa762a-912f-11e8-84c6-88281d0a764d.png">

**Comment by seatexboards** [comment]
@0dp Hi Johan, 
thank you for your reply.
I totally changed the plugin, after many different ways to fix the error. 
That's why you can see correctly.
I'm kind disappointed that I can't use a different plugin instead  of official plugin from Woocommerce + Stripe Pluging.
I saw also a lot of complains about this problem.. so At the moment I will keep this Not official, and maybe in the future I will return to the other one.
Thank you

**Comment by b-sanj** [comment]
Hey guys, I'm also having a problem. Could someone help me with it? 

![screen shot 2018-08-05 at 10 59 05 2](https://user-images.githubusercontent.com/42111319/43684794-ae485862-989e-11e8-92df-9277f6615952.png)

The fields won't let me insert anything. It seems they are too tight. I've tried css coding but nothing. Would appreciate if someone could have a look :)

**Comment by holger1411** [comment]
@seatexboards & @b-sanj:
Seems both of you don´t use the UnderStrap theme. We can´t give support for commercial themeforest themes here...contact the seller for support or the plugin author.

@staceycordoni Could you provide a URL?

**Comment by seatexboards** [comment]
I Resolve installing another plugin..

Thank you

**Comment by b-sanj** [comment]
@seatexboards what plugin did you install?

**Comment by seatexboards** [comment]
WC Stripe Gateway

**Comment by irtehbom** [comment]
I am also getting this issue. In my case the actually input fields are missing.

![stripe](https://user-images.githubusercontent.com/8029680/44091122-594bb61a-9fc4-11e8-9f30-83bdcc1f0483.png)

**Comment by Gonaden** [comment]
@irtehbom I have the same problem! How did you solve this?

**Comment by Gonaden** [comment]
@b-sanj did you solve this?

**Comment by b-sanj** [comment]
@Gonaden hey, I had yellow pencil from my theme 'Javelin,' which I was able to click and drag the boxes to a reasonable size - But I found out I could not insert anything into the boxes because I did not have an ssl. After I received my ssl, I was able to fill in the boxes. Do you have an ssl??

**Comment by Gonaden** [comment]
@b-sanj Thank you so much, this helped me solve my problem. I had to install an SSL plugin and then it worked!

**Comment by holger1411** [comment]
Closing this because it seems to be solved and becasue it is not UnderStrap related

**Comment by vzeazy** [comment]
Just wanted to let others know that my issue was related to running Bootstrap 4. It added a flex block class to the form-row element and caused the issue at hand. Setting the flex-box for the checkout div to display block resolved the issue.

**Comment by gensukeyamashita** [comment]
this still persists when loading directly from elements; 
tried to load a js to change or toggle the iframe width but cant access the iframe; 
none of the documentation also gives you an option to change the width of the iframe ; what a nightmare

**Comment by pattonwebz** [comment]
@gensukeyamashita does the solution above in https://github.com/understrap/understrap/issues/682#issuecomment-453663381 not help with your situation?

**Comment by gensukeyamashita** [comment]
> 
> 
> @gensukeyamashita does the solution above in [#682 (comment)](https://github.com/understrap/understrap/issues/682#issuecomment-453663381) not help with your situation?

just realized this topic is under wordpress; im using elements straight on a page; completely different from my enviroment though the answer above didnt work either; im waiting on stripe staff . sorry to bother here my bad

**Comment by NateSpring** [comment]
If anyone in the future is having this problem: check the script tag for MailChimp. We had this same issue on two different sites with two different themes. Removing and/or moving the MailChimp script tag fix the issue of not being able to fill in the credit card boxes on checkout.

**Comment by pattonwebz** [comment]
@NateSpring good callout there on that one. In investigations previously I had not narrowed down any cause. Now we know a likely place to find the root of the problem :)

**Comment by cosmoc0der** [comment]
Make sure that you are on the checkout page, i.e. the `is_checkout()` function returns true. If you have custom checkout page you can use `woocommerce_is_checkout` filter to return true according to your code, and then Stripe fields will be initialized correctly.

**Comment by Kiritchell** [comment]
For those having this issue sometime around now it's been a major issue with divi theme. 

The only fix I could find that worked for us was to change the checkout page template to blank from page settings.
