### ISSUE TITLE
Undefined variable `consent` in `custom-comments.php`

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap#683]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **OS Version:** Linux Debian / 9.4
  - **Browser:** Chrome 66.0.3359.117 | Firefox 59.02 64-bit 
  - **Language:** PHP 7.0.27
  - **Node.js & NPM Versions:** Node.js [v8.11.2] | NPM [5.6.0]

---

# Issue Overview for Bugreports

Re commit: Added cookies checkbox support for inc/custom-comments.php
[a18067c](https://github.com/understrap/understrap/commit/a18067c44629bee01c8904d5ee59b091b6e6b52f)

The following error message appears above the "Leave a Reply" text above the comment form.

`Notice: Undefined variable: consent in /path/to/web/app/themes/understrap/inc/custom-comments.php on line 36`

## Steps to reproduce?

1. Clone UnderStrap to `themes` directory
2. Activate UnderStrap theme
3. View any post with comments form and the error is present

## *Who* is the bug affecting?

Functionally the form with the checkbox checked still works to submit the comment (for moderation in my case). Approval of the comment posts the comment to the site. However, the error message remains and without the `consent` variable defined I am assuming there is no completion of the actual consent.

## *What* is affected by this bug?

Consent

## *When* does this occur?

All the time.

## *Where* on the platform does it happen?

As described above.

## *How* do we replicate the issue?

As above.

## Are there any related Issues and/or PRs?

No

## Screenshots / Video

![php-error_custom-comments_2018-05-23](https://user-images.githubusercontent.com/26024890/40371655-4f68d7ac-5e26-11e8-802a-e61fe03e55bd.png)

## Expected behavior

`consent` variable is defined.

# Todos

 * Test
 * Documentation

**Comment by 0dp** [comment]
Guess it needs a check if it's set

**Comment by Thomas-A-Reinert** [comment]
Solved with #687
