### ISSUE TITLE
Gulp Live Commands for Docs

### ISSUE THREAD

**Issue by jonathan-bird** [understrap/understrap#685]
## Issue is about..
  - [ ] a Bug Report
  - [x] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:
N/A

---

### Other Comments
Can you please include in the docs the best commands to run for a live environment on deploy?
E.g. Run `gulp sass`, then run `gulp scripts` etc. Or include a `gulp prod-deploy` command in the gulpfile that combines them?

**Comment by Thomas-A-Reinert** [comment]
It´s already in the [upcoming docs](https://thomas-a-reinert.github.io/Understrap-Documentation/docs/0.8.2/development/available-gulp-tasks/). Please don´t bookmark or share the link - the docs will soon move to their final location. This is just a test-setup.

Please let me know if this is clear enough and if you need anything else explained.

Until release some of the tasks may be modified or completely dropped though.

**Comment by jonathan-bird** [comment]
Sorry, that was great! Totally forgot to reply.

I ended up using `gulp dist` as part of my prod build.

**Comment by Thomas-A-Reinert** [comment]
We ❤ feedback ;)
Thx for finally responding. And glad to hear that this solved your problem/issue.
