### ISSUE TITLE
Collapse Search Input field inside NavBar

### ISSUE THREAD

**Issue by breath-ee** [understrap/understrap#686]
- Understrap 0.8.2

Has anyone successfully added the search input to the navbar where it will collapse? 

It seems pasting  `<a href="#search" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-search search-icon"></i></a>` before or after `<?php wp_nav_menu() ?>` renders it outside the collapsing div...! So is there a way to get it inside the `'container_class' => 'collapse navbar-collapse',`.

Also `'search' => get_search_form(),` inside `<?php wp_nav_menu() ?>` array renders an ugly form that is still outside the collaspe div.

![Search-01](https://s9.postimg.cc/clrz9qjvz/boots-navbar-collapse-search-01.jpg)

![Search-01](https://s9.postimg.cc/k1r8vrcsv/boots-navbar-collapse-search-02.jpg)

**Comment by ZacharyElkins** [comment]
You will need to add the search bar as a `li` item to the `ul` element.

Wordpress provides a way to do this. I encourage you to check this page out:
http://www.wpbeginner.com/wp-themes/how-to-add-custom-items-to-specific-wordpress-menus/
Keep in mind that some of the examples on that page have the `"` and `'` mixed up, which isn't too important. I prefer having `"` for the HTML and `'` for the PHP.

And here would be the code example:
```
add_filter('wp_nav_menu_items','add_search_box_to_menu', 10, 2);
function add_search_box_to_menu( $items, $args ) {
    if( $args->theme_location == 'primary' )
        return $items.'<li class="menu-header-search"><form action="http://example.com/" id="searchform" method="get"><input type="text" name="s" id="s" placeholder="Search"></form></li>';
 
    return $items;
}
```

Of course, replace the form with your own HTML. I would avoid using `get_search_form()` and just use some custom HTML, as the `get_search_form()` may include extra HTML you don't want. Whatever works, though.

**Comment by 0dp** [comment]
tags: Question, Documentation, Resolved
@Thomas-A-Reinert @axlright @holger1411

**Comment by Thomas-A-Reinert** [comment]
Thx, @0dp - can i close that issue?

**Comment by 0dp** [comment]
@Thomas-A-Reinert YES SIR!
