### ISSUE TITLE
WooCommerce 3.4.0 Template Update

### ISSUE THREAD

**Issue by ZacharyElkins** [understrap/understrap#688]
WooCommerce recently updated their template files. All files which received changes will need to be updated within Understrap. I am already in the middle of this process.

This is to serve as a marker and forum for users which notice the template error's when updating WooCommerce. The updates should take a few days to implement and test.

As an overview, it looks like a lot of changes were based around removing support for older versions of WooCommerce, general cleanup, with a few significant changes here and there. If anyone is finding any bugs using the older versions please let us know.

**Comment by noelspringer** [comment]
Thanks ZacharyElkins. The checkout **Billing details** form has lost its formatting.

![Billing Details Form - Woommerce-3.4 UnderStrap-0.82](https://user-images.githubusercontent.com/26024890/40570405-dd393118-60cd-11e8-9eb7-0b28f8013311.png)

**Comment by noelspringer** [comment]
#698 has a fix for this.

**Comment by Thomas-A-Reinert** [comment]
Thx, @noelspringer . Gonna close that issue due to the fact that it _SHOULD´VE_ been solved. Feel free to re-open.
