### ISSUE TITLE
Remove child-theme.css styles

### ISSUE THREAD

**Issue by PaoloPgn** [understrap/understrap#690]
Greetings

I see in my child-theme.min.css a lot of elements generated by child-theme.css that I don't need, for instance all the :root {--blue: etc} and much more. There is a way to remove these elements and leave only the one that I set via child theme in sass/child-theme.scss?

Thank you

## Issue is about..
  - [X] a Question
  - **WordPress Version:** 4.9.6
  - **OS Version:**  MacOS [10.11.6]
  - **Browser:** [ all | 
  - **Language:** [  S/CSS]

**Comment by Thomas-A-Reinert** [comment]
This is all about the parent theme. Please refer to the [child-theme issue-tracker](https://github.com/understrap/understrap-child) if you got any problems with the child theme, okay?
