### ISSUE TITLE
Woocommerce translation mixed

### ISSUE THREAD

**Issue by Rodge1** [understrap/understrap#691]
## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:**  MacOS [10.13.4] 
  - **Browser:** [ all ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]

Some strings are not translated as they are woocommerce pages. This only occurs in understrap, other theme's work fine. Looks like it's random. e.g. cart page thead qty etc. > english, cart totals > dutch.
Anyone else with this issue?

![screen shot 2018-05-29 at 14 34 49](https://user-images.githubusercontent.com/39733460/40659082-80698bfe-634d-11e8-9c97-edb299825d99.png)

**Comment by pattonwebz** [comment]
I haven't looked closely but this is probably a text domain issue (template overrides inside the theme may have themes slug as textdomain instead of woocommerse textdomain).

**Comment by corallus** [comment]
Just created a pull request with the fix: https://github.com/understrap/understrap/pull/692

**Comment by Rodge1** [comment]
It is inside the template files included in understrap. I'll look closer later. for now i've commented them out. and added others to child.
