### ISSUE TITLE
Source Map Error popper.js

### ISSUE THREAD

**Issue by sewerpanda** [understrap/understrap#696]
## Issue is about..
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **OS Version:** Windows 10
  - **Browser:** Firefox Developer
  - **Language:** Javascript | jQuery | ES6 | JSON 

---

# Issue Overview 

When the page loads I get this error. The issue started appearing recently and I can't trace it back to a specific change. I'm serving from WAMP. Is this error significant? is it because I'm serving from my local machine? Any Help is appreciated

Source map error: request failed with status 404
Resource URL: http://localhost/site/wp-content/themes/my-site/js/popper.min.js?ver=0.0.1
Source Map URL: popper.min.js.map[Learn More]

**Comment by Thomas-A-Reinert** [comment]
Which UnderStrap version do you use?

**Comment by Thomas-A-Reinert** [comment]
No reply for about a week. Closing it for housekeeping... 

Feel free to re-open if the problem persists.

**Comment by inksea** [comment]
Lil help? Need to generate a source map for popper.js through the gulpfile.

**Comment by 0dp** [comment]
look in node-modules/popper.js/dist
