### ISSUE TITLE
 when browsersync compiles creates a new version theme-aac703cf83.min.css and theme-9e59e9050c.min.js

### ISSUE THREAD

**Issue by nachoumaran** [understrap/understrap#697]
Issue is about..
 a Question
 I need help

Please tell us about your environment:

WordPress Version: 4.9.6
OS Version: Sierra 10.13.5

**Comment by Thomas-A-Reinert** [comment]
And the question IS?! Please be a bit more explicit or I´ll close this issue at once because our crystal balls are currently on vacation.. :P 

Renaming of the files is meant as a cache-buster.

**Comment by nachoumaran** [comment]
sorry :p but I did not know how to explain it, what happens is that every
time browsersync compiles a new min.css file is created, how can I make
this not happen?

thanks

**Comment by 0dp** [comment]
Remove rev task from gulp file

**Comment by nachoumaran** [comment]
It worked, thank you very much!
