### ISSUE TITLE
Issue with .woocommerce-input-wrapper

### ISSUE THREAD

**Issue by jchrislemmer** [understrap/understrap#698]
Please delete anything that does not apply for you!

## Issue is about..
  - [X ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **OS Version:** [MacOS]
  - **Browser:** [ all]
  - **Language:** [  HTML | S/CSS ]

---

# Issue Overview for Bugreports

## Steps to reproduce?

1. Install WooCommerce 3.4.1
2. Buy a product
3. Go to the checkout page and see the issue with all the fields on this page.

## *Who* is the bug affecting?

Everyone - This is what caused the issue - https://github.com/woocommerce/woocommerce/blame/5504f966a4c8b33b1665b74dfec0fefea8d2df0d/includes/wc-template-functions.php#L2638

## *What* is affected by this bug?

Checkout page fields.

## *When* does this occur?

Always.

## *Where* on the platform does it happen?

On the checkout page.

# Todos

Please add the following CSS to your next release.

```
.woocommerce-input-wrapper {
	width: 100%;
}
```

**Comment by holger1411** [comment]
Sorry for the late reply. But was fixed already, so I´am closing this
