### ISSUE TITLE
Error Generated When Following Styling the Theme Instructions

### ISSUE THREAD

**Issue by davidshq** [understrap/understrap#703]
Inserted SASS as instructed into _theme.scss and gulp output was as follows:

```
[00:07:58] Starting 'styles'...
[00:07:58] Starting 'sass'...
WARNING: The `text-hide()` mixin has been deprecated as of v4.1.0. It will be removed entirely in v5.
         on line 10 of src/sass/bootstrap4/mixins/_text-hide.scss, in mixin `text-hide`
         from line 57 of src/sass/bootstrap4/utilities/_text.scss
         from line 14 of src/sass/bootstrap4/_utilities.scss
         from line 41 of sass/assets/bootstrap4.scss
         from line 2 of sass/theme.scss

{ Error: sass\theme\_theme.scss
Error: Undefined variable: "$brand-primary".
        on line 16 of sass/theme/_theme.scss
        from line 10 of sass/theme.scss
>>       color: $brand-primary !important;

   -------------^

    at options.error (E:\VC\philcata\understrap-theme\node_modules\node-sass\lib\index.js:291:26)
  status: 1,
  file: 'E:/VC/philcata/understrap-theme/sass/theme/_theme.scss',
  line: 16,
  column: 14,
  message: 'sass\\theme\\_theme.scss\nError: Undefined variable: "$brand-primary".\n        on line 16 of sass/theme/_theme.scss\n        from line 10 of sass/theme.scss\n>>       color: $brand-primary !important;\n\n   -------------^\n',
  formatted: 'Error: Undefined variable: "$brand-primary".\n        on line 16 of sass/theme/_theme.scss\n        from line 10 of sass/theme.scss\n>>       color: $brand-primary !important;\n\n   -------------^\n',
  messageFormatted: '\u001b[4msass\\theme\\_theme.scss\u001b[24m\nError: Undefined variable: "$brand-primary".\n        on line 16 of sass/theme/_theme.scss\n        from line 10 of sass/theme.scss\n>>       color: $brand-primary !important;\n\n   -------------^\n',
  messageOriginal: 'Undefined variable: "$brand-primary".',
  relativePath: 'sass\\theme\\_theme.scss',
  name: 'Error',
  stack: 'Error: sass\\theme\\_theme.scss\nError: Undefined variable: "$brand-primary".\n        on line 16 of sass/theme/_theme.scss\n        from line 10 of sass/theme.scss\n>>       color: $brand-primary !important;\n\n   -------------^\n\n    at options.error (E:\\VC\\philcata\\understrap-theme\\node_modules\\node-sass\\lib\\index.js:291:26)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-sass',
  showProperties: true,
  showStack: false }
```

Appears there is an undefined variable, $brand-primary

**Comment by ZacharyElkins** [comment]
## Understrap and Bootstrap
Understrap does not include the variable `$brand-primary` in `sass/theme/_theme.scss` or in `sass/theme/_theme_variables.scss`. 

The default Bootstrap variable for the primary color is `$primary`.

## Explanation
What is happening is that you are trying to use a variable in your SCSS and it can't find that variable, as it hasn't been previously defined. 

## Solution
Either add a value for `$brand-primary` or use the default bootstrap variable `$primary`.

If you want to add custom variables or overwrite Bootstrap variables we recommend adding them to `sass/theme/_theme_variables.scss`. This file is called before Bootstrap SCSS and before `sass/theme/_theme.scss`.

## Extra
If you don't figure it out, could you show us what the files `sass/theme.scss` and `sass/theme/_theme.scss` looks like in your version of the theme.

**Comment by davidshq** [comment]
Hmmm...Strange, I'll have to go back and look at this again, as I didn't add a $brand-primary variable.

**Comment by holger1411** [comment]
Bootstrap 4 switched from "$brand-primary" to "$primary".
If you use an older version of UnderStrap but updated the Bootstrap 4 version it will search for brand-primary but can´t find it...

By default UnderStrap uses exactly on variable by default:
https://github.com/understrap/understrap/blob/master/sass/theme/_theme_variables.scss
Renaming it from brand-primary to primary should fix it.

**Comment by French6ko** [comment]
Same thing happen to me following the recommandations of the section "A more detailed example of working with SCSS - Npm - Gulp" section of the page: https://understrap.github.io/. Pasting the error code to Google bring me here, i had to rename brand-primary to primary and it has been fixed, thanks

**Comment by axlright** [comment]
The way my team handles this is to set  `$primary: $brand-primary;` in `_theme.scss` or better yet in a custom variables file `_theme_variables.scss` that is called in `_theme.scss`

This works for us because it gives flexibility in what is assigned to `$primary` but either way it works even if you just need to make sure that a `$brand-primary` is declared and assigned to `$primary`

Is it worth adding a default like this to help as a catch all for those working in older versions of UnderStrap who update to newer Bootstrap?
