### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by highree** [understrap/understrap#705]
Hi, 

is there any documentation or anyone that can tell us how to use the theme. Installation and usage is easy, but for example how to add a jumbotron? For now great Project thanks in advance!

**Comment by ZacharyElkins** [comment]
Hello.

We are currently working on a full documentation. @Thomas-A-Reinert is the main pusher in this effort, so he will be the best person to discuss this. I never use the jumbotron so hopefully someone can help you out.

**Comment by Thomas-A-Reinert** [comment]
Hi,
this is a standard Bootstrap thingie, so i´d stick to their documentation: https://getbootstrap.com/docs/4.1/components/jumbotron/

I think that won´t get reflected in the upcoming docs, because it´s standard Bootstrap code. Otherwise we´d need to copy BS´ whole documentation ;)

**Comment by Thomas-A-Reinert** [comment]
I really understand the problem. The hero canvas widget is registered in https://github.com/understrap/understrap/blob/master/inc/widgets.php lines 84-92 (in the actual code of this repository).

This allows you to use _any_ widget WordPress, your Pagebuilder or whatever extension you use supports. The probably easiest way would be to use WordPress HTML-Widget and use whatever code you want/need. Be it a Jumbotron or whatever you want/need.

What do you mean by "the latest release"?

**Comment by davidshq** [comment]
@Thomas-A-Reinert - Do you have the documentation you are working on posted anywhere? I'd love to take a look and contribute if I can!

**Comment by davidshq** [comment]
Got it. Well, if you want to privately share at some point to have someone read through and provide edits, let me know. :) Eagerly looking forward to the docs release!
