### ISSUE TITLE
Moving Sidebars Into a Sub-Folder?

### ISSUE THREAD

**Issue by davidshq** [understrap/understrap#708]
Hi All,

Just wondering if it would make sense to move the sidebars into a sub-folder? There are six of them currently and seems to be cluttering up the main directory a bit. Just a thought!

Dave

**Comment by Thomas-A-Reinert** [comment]
Yes, I guess none of us ever thought about that. But you´re absolutely right.  Doesn´t make sense to have them in the main dir. Thanks for suggesting that, really. Will try to fix that asap. (Can´t promise though, cos i ´m REALLY REALLY busy atm.) 

No promises being made, that one went instantly on my top priority list though ;)

**Comment by axlright** [comment]
Added PR #711 to accomplish this. I have about 12 minutes of free time a day, so this seemed like a good use of those minutes!
