### ISSUE TITLE
Theme Check Plugin Warning and Require

### ISSUE THREAD

**Issue by hhasan16** [understrap/understrap#709]
## Issue is about..
  - [x] Theme Check Plugins

## Environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:**  Windows 10
---
Theme Check plugin show warning & requires

![theme check](https://user-images.githubusercontent.com/19926369/41200516-a05bed52-6cc7-11e8-904c-b3a08187e178.PNG)

**Comment by Thomas-A-Reinert** [comment]
Interesting, that only a part of your warnings get displayed on my local install.
Anyway - we take them seriously. And anyway again: These are just **WARNINGS** not ERRORS ;)
So you should be good to go anyway..

@0dp : there are better (non-intuitive solutions) available through WordPress Hooks/functions which SHOULD validate. Check:

- http://ottopress.com/2011/tutorial-using-the-wp_filesystem/
- https://www.webdesignerdepot.com/2012/08/wordpress-filesystem-api-the-right-way-to-operate-with-local-files/
- https://wp-kama.ru/function/WP_Filesystem_Base::get_contents

(This is some kinda personal reminder also)

**Comment by 0dp** [comment]
I mean sure, we can update file_get_contents to use WP_Filesystem API's get_contents, but if you look trough WP core you will see that it simply calls file_get_contents.
Instantiating the entire filesystem API to do the same seems overkill IMO

**Comment by Thomas-A-Reinert** [comment]
I agree. Totally. And again: These are "just" warnings, no errors.

**Comment by pattonwebz** [comment]
There will be some discussion soon in theme review team about allowing the use of `file_get_contents` for his kind of thing. We agree that doing init on the whole `WP_Filesystem` for a very simple use case like this is probably unnecessary - we just need to think of a way to ensure that good security considerations are taken into account when it is used :)

**Comment by 0dp** [comment]
fair enough, but get_contents literally does nothing but calling file_get_contents

**Comment by 0dp** [comment]
Then WP core team has to do some validation on get_contents, cuz it does, nothing, zero,zit :)
