### ISSUE TITLE
Many many Gulp security vulnerabilities recongnized by npm on install, too bad.

### ISSUE THREAD

**Issue by powerblue** [understrap/understrap#712]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [x] a Suggestion
  - [x] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by powerblue** [comment]
npm --depth 9999 -g update

**Comment by 0dp** [comment]
First, take more time when you file an issue with UnderStrap, Please follow our guidelines!
Second, take your time to understand what npm audit is.
Third, understand how we use these npm packages in the theme.
Four, close this non issue.

Thanks!

**Comment by 0dp** [comment]
#624

**Comment by pattonwebz** [comment]
I vote this issue be reopened (or perhaps a cleaner one could be created) but these security notices are very much worth correcting where viable.

**Comment by 0dp** [comment]
Yes @pattonwebz, we should upgrade the packages that includes fixes. (I for one have created a gulp4 branch, that is still being tested, which is part of the solution. Please see #624 ) But ultimately it is up to the package maintainers to fix their packages. Feel free to analyze the audit and get back to the maintainers. 

Also, none of these packages are used or included in your final theme. They are purely used for development purposes.

**Comment by 0dp** [comment]
For Y'alls reading pleasure: https://docs.npmjs.com/getting-started/running-a-security-audit

Especially,
https://docs.npmjs.com/getting-started/running-a-security-audit#update-dependent-packages-if-a-fix-exists and downwards.

**Comment by pattonwebz** [comment]
I get how the dependency chain works here and why these are a non-issue when it comes to production deliverables ;)

Consider this though: the audit tools exist for use exactly how the OP used it here - to scan software you intend to try out and make an informed decision about if you want to use it or not. Here I think OP probably decided not to use this theme :(

P.S. I see your gulp4 PR just now and I think that probably solves a good number of the issues this thread would have been concerned with :)

**Comment by 0dp** [comment]
Hey @pattonwebz Thanks for reviewing the PR. My man 👍 

The problem is, we can't really do anything about the package maintainers. So we are bound to loose a few new users, especially if the don't RTFM 
![b53ad99b8dfae5c65a4a797d95e6bcee](https://user-images.githubusercontent.com/3642367/41408441-00ff2fc6-6fd3-11e8-9caf-0e062dcd1186.jpg)

**Comment by 0dp** [comment]
No biggie, at all. But it's tricky when ie. we use gulp-sass and we get a message like
`gulp-sass > node-sass > node-gyp > request > hawk > boom > hoek`
All we can do is wait for gulp-sass to be updated with the newest version of node-sass(will be fixed in v.5) maybe they can't live without node-gyp? maybe node-gup can't live without request, and so on.
In the end the maintainer of hoek, is like, nah! Ain't got time for this.

**Comment by pattonwebz** [comment]
> Ain't got time for this.

haha! Many years from now _**dependency nightmare**_ is the term that I will fondly remember this era of web development as ;)

**Comment by 0dp** [comment]
me too!
