### ISSUE TITLE
Right Sidebar Collapsing Under Main Content?

### ISSUE THREAD

**Issue by davidshq** [understrap/understrap#716]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x] I need help

## Please tell us about your environment:
  - **WordPress Version:** 4.9.6
  - **Browser:** all
---
# Issue
On [philcata.com](https://philcata.com) I have two custom post types - donors and offers. Each of these uses a customized version of single.php and loop-templates\single-content.php:

- single-offer.php loop-templates\single-offer-content.php
- singe-donor.php loop-templates\single-donor-content.php

I have the search in the right sidebar. On the rest of the site this works fine, but with these customized pages the right sidebar moves under the main content.

Thus far my research indicastes the culprit may be the tables I am using in the main cotent. If anyone has any idea why this is happening, I'd appreciate it...I'll let you know if I find a resolution.

You can see examples of this issue occuring at these pages:
https://philcata.com/donor/knit-picks/

https://philcata.com/offer/17-5-pound-box-of-yarn/

**Comment by pattonwebz** [comment]
Hey @davidshq,

There's a mixup somewhere in your template files I think and the `.widget-area` column is outside of it's wrapper `.row`.

![screenshot from 2018-06-18 08-09-49](https://user-images.githubusercontent.com/3902039/41522975-338be4d4-72d0-11e8-96c8-28eaf7e9271e.png)

If I rework it with dev tools to pull that div inside the row it works. 

![screenshot from 2018-06-18 08-10-39](https://user-images.githubusercontent.com/3902039/41523011-612b77ce-72d0-11e8-9e75-0e9e78569a23.png)

Check through the templates files and see if you can pull the sidebar calls up above a closing `</div>` tag and I think that will sort it.

**Comment by ZacharyElkins** [comment]
Adding to the above comment.

It is likely that you have an extra `</div>` in there somewhere that is causing this, as it's less likely that the sidebar call was moved around. Either way, one of those possibilities is the issue.

**Comment by davidshq** [comment]
Thanks everyone! I've actually simplified the site by moving the search form into the header, below the nav menu and removing the right sidebar entirely. I'm not entirely happy with how the main content looks now, it feels a little too wide...not sure if I should increase font size, line spacing, decrease fixed width of content...but search issue is resolved for me. Again, appreciate the assistance!
