### ISSUE TITLE
Why Don't We Use Bootstrap Grid in Header?

### ISSUE THREAD

**Issue by davidshq** [understrap/understrap#717]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [ ] I need help

## Comments
I'm curious, why don't we use a bootstrap grid for the header? Something like:

<div id="wrapper-navbar" itemscope itemtype="http://schema.org/WebSite">

    <a class="skip-link screen-reader-text sr-only"
       href="#content"><?php esc_html_e( 'Skip to content', 'understrap' ); ?></a>

    <nav class="navbar navbar-expand-md navbar-dark bg-primary">

		<?php if ( 'container' == $container ) : ?>
        <div class="container">
			<?php endif; ?>
            <div class="row">
                <div class="col-md-6">
                    
					<?php if ( ! has_custom_logo() ) { ?>

					<?php if ( is_front_page() && is_home() ) : ?>

                        <h1 class="navbar-brand mb-0"><a rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>"
                                                         title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"
                                                         itemprop="url"><?php bloginfo( 'name' ); ?></a></h1>

					<?php else : ?>

                        <a class="navbar-brand" rel="home" href="<?php echo esc_url( home_url( '/' ) ); ?>"
                           title="<?php echo esc_attr( get_bloginfo( 'name', 'display' ) ); ?>"
                           itemprop="url"><?php bloginfo( 'name' ); ?></a>

					<?php endif; ?>

					<?php } else {
						the_custom_logo();
					} ?>
                </div>
                <div class="col-md-6">
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarNavDropdown"
                            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    
					<?php wp_nav_menu(
						array(
							'theme_location'  => 'primary',
							'container_class' => 'collapse navbar-collapse',
							'container_id'    => 'navbarNavDropdown',
							'menu_class'      => 'navbar-nav',
							'fallback_cb'     => '',
							'menu_id'         => 'main-menu',
							'depth'           => 2,
							'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
						)
					); ?>
                </div>
				<?php if ( 'container' == $container ) : ?>
            </div>
		<?php endif; ?>

    </nav>

</div>

Impetus for this question was that I wanted to move the search box onto the same row as the logo and nav menu, with a bootstrap grid this would be trivial...but more complicated this way?

**Comment by axlright** [comment]
@davidshq You certainly can. The header.php is a base starter header. I often include Bootstrap rows, columns and other Bootstrap classes in headers for projects. Totally up to you.

**Comment by ZacharyElkins** [comment]
The default navbar with Bootstrap does not use the grid:
https://getbootstrap.com/docs/4.1/components/navbar/

It wouldn't be very Understrap to differ from this. Not everyone wants/needs to have the grid in their header.

Bootstrap is already set up to have the brand, menu, and a search bar in the navbar without any grid, so there is often not a need for it anyway. It would be an individual project choice to have a different navbar. As it is, the code you suggested above only adds unnecessary weight, there is no need to have those extra `div` elements with the content in the navbar.

If you look at the Bootstrap examples you'll see that the logo, nav menu, and search bar are in the same row already by using flex that is specifically applied to the navbar already. They also provide classes that change the breakpoint of the nav menu. I'm a bit confused as to why the need for the grid?

**Comment by pattonwebz** [comment]
I'd like to also vote for no grid in header by default as it's more in line with BS official docs.

But for sure go ahead and add in grid wrappers in a child theme if you want them :) It's worth checking out what utility classes you can use on the nav first though (it's flex based) https://getbootstrap.com/docs/4.0/utilities/flex/. Might be able to make most things happen with the utilities from there :)

**Comment by davidshq** [comment]
Hi All,
Thanks for the explanation, makes sense. Just wanted to know if there was a reason, and there is. :)

Dave
