### ISSUE TITLE
Proposed gulp 4 update #713

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap#723]
Not sure if this should be  in Issues or as a comment in the PR #713 
## Issue is about..
  - [x] a Bug Report
  - [x] a Suggestion

## Please tell us about your environment:

  - **WordPress Version:** 4.9.6
  - **OS Version:** Linux [Debian / 9]
  - **Language:** S/CSS | JavaScript 
  - **Node.js & NPM Versions:** Node.js [v8.11.3] | NPM [6.1.0]

---

# Issue Overview for Bugreports

## Steps to reproduce?

* Install UnderStrap from https://github.com/0dp/understrap
* `cd understrap`
* `git checkout origin/gulp4`
* Run `npm install`

Gulp 3.9.1 installed globally, Gulp 4.0.0 installed locally

## *Who* is the bug affecting?

Everyone with the above Gulp versions

## *What* is affected by this bug?

Gulp task `gulp watch-bs` will not run with global Gulp version 3.9.1 and local Gulp version 4.0.0

The following error occurs:

```bash
Using gulpfile ~/sources/understrap-0dp-gulp4/gulpfile.js
/home/user/.nvm/versions/node/v8.11.3/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /home/user/.nvm/versions/node/v8.11.3/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
On the other hand, if the local gulp is used from within the theme directory like so:

`./node_modules/gulp/bin/gulp.js watch-bs`

then the watch-bs task works fine.

So perhaps a note in the `README.md` file is need to point out that  gulp@4.0.0 is required globally:

`npm i -g gulp@4.0.0` in addition to installing gulp@4.0.0 via `npm install` from within the cloned repo.

Another option is to create a shell alias for `./node_modules/gulp/bin/gulp.js watch-bs` instead of installing globally, though I think people should be encouraged to upgrade globally.

## *How* do we replicate the issue?

Test with Gulp versions as described above.

## Are there any related Issues and/or PRs?

#713

**Comment by 0dp** [comment]
Hey @noelspringer 
Thanks for your report.

It's correct that you'll need to update gulp-cli and gulp, and I agree people should be encouraged to update globally. When the PR passes we should definitely update the readme

**Comment by Thomas-A-Reinert** [comment]
Yeap, absolutely agree with that. Not only with the upcoming docs but as a quick fix. And maybe a note sent via NPM INSTALL.

That goes along with an info on how to evaluate the security issues. Via Docs as well as an NPM installation notice.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.

Docs have been abandoned btw. No Updates from the maintainers are causing that.
