### ISSUE TITLE
Future releases of Understrap

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#724]
Please delete anything that does not apply for you!

## Issue is about..

  - [ ] a Question

Hi All. Thanks for everyone's hard work on Understrap lately. I see there have been about 60 commits since the last release if Understrap. 

My workflow relies on NPM for updates of understrap. 

Are than any plans for a release any time soon?

Thans

**Comment by Thomas-A-Reinert** [comment]
@holger1411  @holgerkoenemann ?

**Comment by holger1411** [comment]
Hi!
sorry guys, there was a lot of work followed by a lot of hollidays ;-) within the last weeks.
But now I´am back on track. I will check and test anything and looking forward to release a new version within the next 5-10days.

**Comment by 0dp** [comment]
Welcome back man

**Comment by shansmith01** [comment]
Thanks a heap @holger1411
