### ISSUE TITLE
Pagination .page-item disabled ?

### ISSUE THREAD

**Issue by nuriye** [understrap/understrap#726]
I am using the recent Version of understrap and its pagination - there are the Page Numbers and Arrows vor prev. and next. But they are disabled. It's not possible to click on them.
How can I fix this?
Thanks!

```
<li class="page-item disabled">
<a class="page-link" aria-label="Previous" href=""></a>
</li>

```
There are futher pages, so I don't get why this is not working. I tried to remove the .disabled Class, but it seems like the class is not in the dom (its showing in the console but not in the browser sourcecode ?)

**Comment by holger1411** [comment]
Sorry for my late reply. But it was fixed already.
