### ISSUE TITLE
Creating Standalone version of Child Theme

### ISSUE THREAD

**Issue by lordcameltoe** [understrap/understrap#727]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [X ] a Question
  - [ ] I need help

I was wondering if there was a gulp command that can take the child theme and concatenate all php, js, css, image files, etc. from the parent and child theme into a single standalone theme ready for production environment.

Also, is there a gulp command to minify html?

Thank you

**Comment by Thomas-A-Reinert** [comment]
a.) nope. pretty nice idea though. you´re welcome to jump in to fulfill that request :)
b.) nope. none that i knew though. we usually leave that to something like autoptimize, w3tc or similar. cos some ppl want to leave that as it is.  and as the whole thing is developer-oriented anyway (in contradiction to the usual john-doe), they should usually be able to set this stuff up. and will prolly do it anyway without further notice. but that´s a nice issue to be mentioned in the upcoming docs. thx!

sorry.
UnderStrap was always meant to be a "starter theme" to be used as a starting framework. NOT as a base/parent theme to be used with child themes. yes, we layed out the foundation for that, but.. 
honestly, we´re currently trying to improve the parent to the max (..) and are really neglecting the child.
