### ISSUE TITLE
Vulnerability errors after npm install require NPM Audit

### ISSUE THREAD

**Issue by dylannirvana** [understrap/understrap#730]
I apologize if this has been brought up before, but `npm install` throws this error in the console:

`npm notice created a lockfile as package-lock.json. You should commit this file.
added 1080 packages from 665 contributors and audited 24652 packages in 92.942s
found 46 vulnerabilities (6 low, 32 moderate, 8 high)
  run npm audit fix to fix them, or npm audit for details`

Please advise. Thank you.

## Issue is about..
  - [√ ] a Bug Report

## Please tell us about your environment:
 OSX High Sierra 10.13.5

## *Who* is the bug affecting?
Console messages after the `npm install` in both Understrap theme folder and child folders like Core

**Comment by 0dp** [comment]
Yeah man, it's been discussed a million times before.
The errors are related to the node modules the theme uses for development purposes only.
node modules are not used or distributed with your final theme, so you can disregard the vulnerabilities.
You can do a npm audit and follow the instructions. The packages that can't be fixed, you can contact every package maintainer listed and tell them to fix it.

Unfortunately there is nothing much we can do from here. 👌

**Comment by dylannirvana** [comment]
Makes total sense. Thank you!
