### ISSUE TITLE
Gulp4 branch

### ISSUE THREAD

**Issue by holger1411** [understrap/understrap#735]
While I was away there where several major changes which needs to be tested and documented.
I created a "Gulp4" branch here:
https://github.com/understrap/understrap/tree/gulp4
for it. So we can separate this changes from the master to keep the master clean and releasable while working on the Gulp4 branch.

Discussions about the "Gulp4" should take place here.

**Comment by axlright** [comment]
I am unavailable to test until Friday of this week but can do so then. I'm not a Gulp expert but can follow instructions and test...

**Comment by 0dp** [comment]
I would very much like some feedback

**Comment by 0dp** [comment]
https://github.com/understrap/understrap/pull/883

Please test

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
