### ISSUE TITLE
0.8.3 on npm?

### ISSUE THREAD

**Issue by xicubed** [understrap/understrap#737]
Tried to use 0.8.3 understrap in the 0.5.2 understrap-child but when I ran npm install there it complained (I had pointed to 0.8.3 in the child theme package.json instead of 0.8.2).

✔ ~/src/wp-content/themes/understrap-child [master|✚ 1…92] 
22:44 $ npm install
...
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! code ETARGET
npm ERR! notarget No matching version found for understrap@^0.8.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'understrap-child'
npm ERR! notarget 

I guess it's looking to npm for 0.8.3 since I put that in the child theme package.json. Is there a way I can just make 0.8.3 locally and point to that? Or add a devDependency or do I need to wait till it's updated on https://www.npmjs.com/package/understrap?

**Comment by holger1411** [comment]
Yes, there is a strange WooCommerce bug in 0.8.3 so we decide to not publish this version on npm and wordprress.org till it is fixed:
https://github.com/understrap/understrap/issues/733

**Comment by holger1411** [comment]
While 0.84 is out (and also available on npm) I close this.
thx @xicubed !
