### ISSUE TITLE
Trouble with top two jumbotrons as pictured on demo

### ISSUE THREAD

**Issue by mmaffia1992** [understrap/understrap#741]
## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 10] 
  - **Browser:** [Chrome 67.0.3396.99]
  - **Language:** [ HTML | S/CSS ]

Hello! I am trying to use the Understrap theme which I think is wonderful and simplistic, but there's a way that it interacts with Wordpress that I am not sure of, so I figured I'd ask.

Ideally, I wanted to set up a layout structure similar to the Understrap demo pictured here: https://understrap.com/understrap/

Specifically, I am having trouble with the purple part at the top and the grey part underneath it. They both seem to be jumbotrons, and I can get the grey one to appear just fine by adding text or HTML widgets to the static hero area. 

I cannot, however, figure out the purple area. If I want that on top, how can I accomplish that? I looked a little into the source code and I saw that the purple area is classed as textwidget custom-html-widget. The grey area is classed as wrapper wrapper-static-hero. I know I can create columns and rows with the static hero widget but no matter what I add, it seems to be "inside" of that gray space. 

How can I keep a jumbotron on top and separate from the grey area as pictured?

Thanks in advance!!

**Comment by mmaffia1992** [comment]
Sorry, I forgot to mention that I would not like it to move, just like the demo. I did get it working on the 'moving' slider but I don't want to put up more than one item.

**Comment by holger1411** [comment]
Hi!
The purple part is a html widget on pos "Hero Canvas". Thats the markup i use for it:
```
<div class="jumbotron py-5 jumbotron-fluid bg-primary text-white" style="border-top: 1px solid rgba(255,255,255,.1);">
<div class="container py-5">
	<div class="row">
		<div class="col-md-7">
<h1 class="display-3">Sample Jumbotron</h1>
	<p class="lead">Welcome to the UnderStrap demo site. <br/>UnderStrap is a WordPress theme framework and starter theme which incorporates Bootstrap 4 into WordPress.</p>
<a class="btn btn-success btn-lg py-3" href="https://gumroad.com/l/CQrW" style="padding-left:80px; padding-right:80px;" target="_blank">Download now</a><br/>
<a class="btn btn-sm btn-link text-white-50" href="https://github.com/holger1411/understrap"  target="_blank" role="button">Visit Github</a>
<a class="btn btn-sm btn-link text-white-50" href="https://understrap.com"  target="_blank" role="button">Visit understrap.com</a>
</div>
</div>
</div>
</div>
```

The grey part is widget positions "Top Full" where I add three text widgets with that "Lorem ipsum" text and the carbon ads.

**Comment by holger1411** [comment]
Closing this. Feel free to reopen if it did not solved your problem.
