### ISSUE TITLE
Parse error: syntax error when updating to 0.8.2

### ISSUE THREAD

**Issue by tekcap** [understrap/understrap#742]
## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 4.9.7

Updating understrap from 0.7.0 to 0.8.2

No matter the page I visit on my website http://golabo.com/ I get the following error

Parse error: syntax error, unexpected '[' in /home/golaboc/public_html/wp-content/themes/understrap/inc/pagination.php on line 9

I'm not sure what to do, I was given control of the website and I'm not a developer. I was just doing the routine updates and updating content.

**Comment by pattonwebz** [comment]
Hi @tekcap,

This is a php compatibility issue between the theme and the server it runs on. Your server runs on php 5.3 where as the code causing the problem relies on php5.6 minimum. 

I would strongly encourage you to look into swapping to modern php (I suggest php 7.1) but you can also correct this by changing a single line of code in the theme.

I just opened a PR that changes the line that needs to be swapped so you can see the change needed here: #743

**Comment by tekcap** [comment]
Thank you for such a quick response! I will test it out and close the issue

**Comment by tekcap** [comment]
After modifying that line, I now get this error:
Parse error: syntax error, unexpected '[' in /home/golaboc/public_html/wp-content/themes/understrap/inc/pagination.php on line 13

**Comment by pattonwebz** [comment]
Sorry I missed the other line, there is also a block of code that looks like this:  

```php
        $args = wp_parse_args( $args, [
            'mid_size'           => 2,
            'prev_next'          => true,
            'prev_text'          => __('&laquo;', 'understrap'),
            'next_text'          => __('&raquo;', 'understrap'),
            'screen_reader_text' => __('Posts navigation', 'understrap'),
            'type'               => 'array',
            'current'            => max( 1, get_query_var('paged') ),
        ]);
```

You need to change it to this:
```php
        $args = wp_parse_args( $args, array(
            'mid_size'           => 2,
            'prev_next'          => true,
            'prev_text'          => __('&laquo;', 'understrap'),
            'next_text'          => __('&raquo;', 'understrap'),
            'screen_reader_text' => __('Posts navigation', 'understrap'),
            'type'               => 'array',
            'current'            => max( 1, get_query_var('paged') ),
        ) );
```
