### ISSUE TITLE
Admin custom JS

### ISSUE THREAD

**Issue by clemorphy** [understrap/understrap#746]
## Issue is about..
  - [x] a Question

## Please tell us about your environment:

  - **WordPress Version:** 4.9.7
  - **Language:** [ Javascript ]

---

I see we can add custom JS to be executed on the front office inside the following file : `/js/custom-javascript.js`

Is there anything similar to add custom JS to the back office (admin interface) ?
What would be your recommendations ?

**Comment by 0dp** [comment]
Hi @clemorphy, I would keep a separate js file in the js folder and then enqueue it with admin_init.

**Comment by clemorphy** [comment]
Ok. I thought maybe there was an empty file, already included in the gulp workflow, waiting for me to put some admin JS :roll_eyes:

**Comment by Thomas-A-Reinert** [comment]
Nope. UnderStrap is just a Frontend-Template. But feel free to fork it or adjust it to your needs.

**Comment by clemorphy** [comment]
Ok, I got it.
Thanks.
