### ISSUE TITLE
Dropdown not working with Draft Child Theme

### ISSUE THREAD

**Issue by damienoneill2001** [understrap/understrap#747]
Hi Team,

I am using Understrap 0.8.4 and Draft Child Theme 0.2.0.

I have recently upgraded to 0.8.4 from 0.6.5 of Understrap.  Initially, I received an error about the navwalker being invalid and I had to change WP_Bootstrap_Navwalker to understrap_WP_Bootstrap_Navwalker in my child's header.php.  But since doing that, the dropdown menus in the nav bar no longer work.  When I hover over a parent item, nothing appears.

I did check other tickets but none seemed to relate to the Draft Child.

This is my Primary Header Menu:

![image](https://user-images.githubusercontent.com/8035010/42937139-05bd4cb2-8b46-11e8-9865-d30ed7185f98.png)

And this is what I see in the console:

![image](https://user-images.githubusercontent.com/8035010/42937194-34105028-8b46-11e8-8c2d-78f7936761ea.png)

Let me know if you need any further information.

Damien

**Comment by Thomas-A-Reinert** [comment]
Please notice that this is the UnderStrap PARENT theme repo.
Apart of that Draft is a commercial theme we cannot provide support for.
Please contact the distributor if you encounter any problems.

**Comment by damienoneill2001** [comment]
Hi Thomas,

I was using the Draft theme from the Understrap website:

https://understrap.com/understrap-child-themes/

Am I wrong in thinking that the Draft theme is connected in some way to the Understap theme?

**Comment by damienoneill2001** [comment]
Oh, should I be posting the issue here: https://github.com/understrap/draft-understrap-child

Apologies if that is the case.

**Comment by Thomas-A-Reinert** [comment]
It's just that we as the open source devs of UnderStrap do not support the commercial forks - we don't even have access to it.

**Comment by damienoneill2001** [comment]
Apologies again, I did not realise it was a commercial fork, I thought it was one in the same.  I'll ask the question in the Draft area.

Thanks!

**Comment by Thomas-A-Reinert** [comment]
I'm sorry for the confusion - Core is the commercial child, DRAFT is a free one. Anyway, wrong issue tracker ;)
Glad you found the right one..
