### ISSUE TITLE
Woocommerce billing form fields not showing correctly

### ISSUE THREAD

**Issue by chanebrand** [understrap/understrap#756]
hi guys, i have this problem, the form filed just states array? Does anyone here know how to fix this?
<img width="1214" alt="screen shot 2018-07-27 at 16 27 55" src="https://user-images.githubusercontent.com/41794979/43326924-4fadb17a-91ba-11e8-95b4-78ccdd0acdfe.png">

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
