### ISSUE TITLE
Auto Compile Understrap.pot with gulp-wp-pot

### ISSUE THREAD

**Issue by pprotschka** [understrap/understrap#757]
## Issue is about..
  - [ ] a Suggestion

I find myself adding quite a few new language strings and instead of using external tools like poedit i would much prefer a file watcher that auto builds my .pot file from the PHP files within the directory.

this is where [https://www.npmjs.com/package/gulp-wp-pot](url) comes into play...

along with the other watchers php files could be watched and a rebuild of the .pot can be triggered.

**Comment by 0dp** [comment]
Task for reference

```
// Translation related.
var text_domain             = Understrap'; // Your textdomain here.
var translationFile         = 'understrap.pot'; // Name of the transalation file.
var translationDestination  = './languages'; // Where to save the translation files.
var packageName             = 'Understrap'; // Package name.

var projectPHPWatchFiles    = './**/*.php'; // Path to all PHP files.
var wpPot = require('gulp-wp-pot'); // For generating the .pot file.
 /**
  * WP POT Translation File Generator.
  *
  * * This task does the following:
  *     1. Gets the source of all the PHP files
  *     2. Sort files in stream by path or any custom sort comparator
  *     3. Applies wpPot with the variable set at the top of this file
  *     4. Generate a .pot file of i18n that can be used for l10n to build .mo file
  */
 gulp.task( 'translate', function () {
     return gulp.src( projectPHPWatchFiles )
         .pipe(sort())
         .pipe(wpPot( {
             domain   : text_domain,
             destFile  : translationFile,
             package : packageName
         } ))
        .pipe(gulp.dest(translationDestination))
 });
```

**Comment by danemorgan** [comment]
This feels like a situation where we might be better served to include the Gulp Task in documentation rather than in the gulpfile, but I sort of like the idea of documenting the basic path to these kinds of things to help newer developers.

**Comment by 0dp** [comment]
Agreed!

**Comment by danemorgan** [comment]
@0dp do you have time to do a quick Pull Request of your task with some brief instruction added to the readme?

**Comment by 0dp** [comment]
Correct me if i am wrong. This is not really a task that anyone should need to run. If there is translation strings missing in the files, we should fix them in the theme

If a user is doing multi lingual stuff, the plugin being used will already have tools for string translations.

Translations should be done on translate.wordpress.org and the main po and mo file should be generated with a tool like poedit and pushed to WordPress.org

This task should be documented for sure, but with no warrant and as-is.

**Comment by danemorgan** [comment]
Yes. I mean only to add it to documentation. Basically showing anyone who is looking to add translation to their process how to get started.

I would be against including the task in the gulpfile,but adding a brief instruction in the read me and in documentation seems like a good thing.

**Comment by Thomas-A-Reinert** [comment]
Yrap. Absolutely correct. I'll do my translation with PoEdit and that's it
for me. Everything else is out of my scope and needs to be done by the
repo-owners.

Johan Nielsen ***@***.***> schrieb am Do., 17. Juni 2021,
20:02:

**Comment by 0dp** [comment]
I'm just working on another PR.

Then I'll for sure test this one out and report back

**Comment by bacoords** [comment]
I'm going to close this PR for a few reasons, but mainly because we're moving away from gulp and are not accepting additional gulp tasks. If someone is interested in picking up the torch and submitting a new PR/issue on this, please do!
