### ISSUE TITLE
Can't Display Custom Taxonomy in Custom Post Types

### ISSUE THREAD

**Issue by vinrgates** [understrap/understrap#758]
Hi, how can I display the categories and tags for custom post types

I already changed ``'post' === get_post_type()`` to ``'page' !== get_post_type()``
but it doesn't works.

Sorry for the novice question.

```
function understrap_entry_category() {
		// Hide category and tag text for pages.
		if ( 'page' !== get_post_type() ) {
			/* translators: used between list items, there is a space after the comma */
			$categories_list = get_the_category_list( esc_html__( ', ', 'understrap' ) );
			if ( $categories_list && understrap_categorized_blog() ) {
				printf( '<span class="news-cat badge badge-warning cat-links">' . esc_html__( '%1$s', 'understrap' ) . '</span>', $categories_list ); // WPCS: XSS OK.
			}

			/* translators: used between list items, there is a space after the comma */
			$tags_list = get_the_tag_list( '', esc_html__( ', ', 'understrap' ) );
			if ( $tags_list ) {
				printf( '<span class="badge badge-warning"><i class="fas fa-tag mr-1"></i><span class="tags-links">' . esc_html__( '%1$s', 'understrap' ) . '</span></span>', $tags_list ); // WPCS: XSS OK.
			}
		}
	}
```

**Comment by Design-Depot** [comment]
Have you tried using wp_query? Like so:

`<?php
	    
	$args = array( 
					'post_type' => 'Your_custom_post_type_here'
				);
	
	$wp_query = new WP_Query( $args ); ?>
	
	<?php if ( $wp_query->have_posts() ) : ?>
		
		<?php while ( $wp_query->have_posts() ) : $wp_query->the_post(); ?>
			<p><?php the_category() ?></p>
                        <p><?php the_tags(); ?></p>
		<?php endwhile; ?>
		
	
		<?php wp_reset_postdata(); ?>
	
	<?php else : ?>
		<p><?php _e( 'Sorry, no posts matched your criteria.' ); ?></p>
	<?php endif; ?>`

**Comment by vinrgates** [comment]
Yes I used but it isn't working

Here's the code that I'm using for the loop

```
$args = array(
  'post_type' => 'cpt',
  'post_status' => 'publish',
  'posts_per_page' => 6,  
  'tax_query' => array(
    'relation' => 'AND',
      array(
        'taxonomy' => 'custom_cat',
        'field' => 'slug',
        'terms'    => array( 'test1', 'test2' ),
      )
    )

);
// the query
$newQuery = new WP_Query( $args );
```

**Comment by alexbogias** [comment]
No problem for me... I use:
```
<?php $terms = get_terms( '**custom_category**', array( 'hide_empty' => true ) ); ?>
<?php if ( $terms ) : ?>
	<ul> 
		<?php foreach ( $terms as $term ) : ?>
			<li>
				<?php echo esc_html( $term->name ); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
```
Just replace custom_category with the exact name used here:

`register_taxonomy( 'custom_category', $args );`

**Comment by holger1411** [comment]
Seems it is solved here. Closing this. Thx @alexbogias ... @vinrgates if it did not solve your problem feel free to reopen
