### ISSUE TITLE
understrap basic functionality

### ISSUE THREAD

**Issue by mherda** [understrap/understrap#760]
Hi,
I like the structure of files in Understrap  and its integration with bootstrap but it offers more than I need.

CSS: for most part I use ready made bootstrap classes with only some css additions on my part. Not really utilising sass - the website I'm doing does not require extensive additional css

JS: I'll probably have less than 200 lines code of JS. JQuery is needed by bootstrap.

When I have been developing a theme locally, it wasn't a problem, no I need to upload to a server where I cannot run gulp, etc. but there will still be changes. 

I'm not experienced enough to understand how all the parts of understrap work together. My question is if I compiled how the website is now (gulp watch), would I just be able to upload certain folders/files to a remote server? and afterwards exactly which files would I have to then edit to modify css and js (without the need of recompiling everything again.)?
I hope it makes sense. To be honest I think understrap is an overkill for what i need but I tried other simpler solutions and had the best results with understrap so far. And I need to move further development to a remote server where I only have an ftp access to.

Thank you

**Comment by davidshq** [comment]
I'm not sure I entirely understand the question. You are trying to remove jQuery from the theme? Or you want to move CSS/JS used by Understrap that is not part of Bootstrap/jQuery? Can you give an example of what file/folder you'd like to remove?

**Comment by mherda** [comment]
Thank you for your reply. Apologies if I wasn't clear. I'll try to rephrase it:

The project uses:
-bootstrap
-jquery and custom-javascript

The project does not use:
- sass

Basically, I need to move the development to a remote server where I don't have full access to (eg. compiles everything (gulp watch, etc) so whenever I've made some changes to js or css, I have two options:

a) recompile (gulp watch) locally and upload to the changes to the remote server (exactly which files need to be uploaded after (css/js changes)
b) forget about recompiling and directly edit the css / js files on a remote server via ftp (which exactly are those files)

In my original post I was trying to ask about b)

Hope it makes more sense now.

**Comment by holger1411** [comment]
@mherda Its important to understand that your changes to the css files get lost if you recompile it.
If you just need some basic CSS additions it might by an option to use the "custom css" function in your theme customizer directly in your WordPress admin area.
Or develope locally while running gulp watch, than upload the compiled /css/theme.min.css to your prod server via ftp and overwrite the old one.
Both is much better than editing on your live server while you don´t have this changes in your dev enviroment

**Comment by mherda** [comment]
OK. thanks guys. I'd probably need to keep developing locally in that case. Just to clarify, after recompiling (css changes), the only folder that need to be reuploaded to the remote server is /src , right? The /sass folder does not need to be uploaded at all, does it?

What about the /js folder. Is it ok to upload it once or are the custom js changes being reflected there necessitating reuploading?

**Comment by Thomas-A-Reinert** [comment]
Do a `gulp dist` and upload only the content of the "dist" folder. That´s it. KEEP THE DEVELOPMENT FOLDER FOR YOURSELF THOUGH!

**Comment by mherda** [comment]
Thanks. This is amazing. Makes it much simpler. While it's not strictly in the scope of the Understarp project, but perhaps one of the experts could write some tutorial on a typical (or one of possible) workflows working with Understrap and the tools it comes in?

Thank you.

**Comment by Thomas-A-Reinert** [comment]
While still not finished, but i´m currently lacking the time to complete: https://usdocu.tarthemes.com/
It may be incomplete and/or needs to be overhauled.
