### ISSUE TITLE
Wrong version in github tagged branch

### ISSUE THREAD

**Issue by gtermini** [understrap/understrap#771]
## Issue is about..
  - [x] a Bug Report
  

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8

# Issue Overview for Bugreports
Tag 0.8.5 in Github still contains a style.css that says 0.8.4.

## Steps to reproduce?
Check github repository

**Comment by holger1411** [comment]
Yes, thats right.
Please use 0.8.6

**Comment by gtermini** [comment]
Thank you
