### ISSUE TITLE
Installing Library: npm Scroll Magic

### ISSUE THREAD

**Issue by ricksternyc** [understrap/understrap#772]
If installing a library with npm, do I need to manually enqueue script from node package? I see it listed in package.json as dependency, but don't see any of the Scroll Magic variables in theme.js.  Am I missing a step? Thanks

**Comment by 0dp** [comment]
Hey @ricksternyc 
Simply installing a npm package does not include it automagically yet hehehe

modify your gulpfile.js
in copy-assets task add something like this:
```
// Scroll Magic into /src/js
    gulp.src( paths.node + 'scrollmagic-folder/file-you-want-to include.js )
.pipe( gulp.dest( paths.dev + '/js' ) );
```

Then edit scripts task, by adding following to the scripts array
```
paths.dev + '/js/file-you-want-to include.js '
```

run

`gulp copy-assets` and verify file has been copied

run

`gulp scripts`

then drink beer and celebrate 🍻

**Comment by holger1411** [comment]
🍺 
Closing this till the next round ;-)

**Comment by zafon18** [comment]
Hey, I have a problem with installing the AOS module from the npm package. I added dependence through 
``` npm install aos --save ``` and edited the gulpfile.js file by adding 
```
gulp.task( 'copy-assets', function() { 
// Adding AOS
            gulp.src( paths.node + 'aos/src/js/aos.js' )
                .pipe( gulp.dest( paths.dev + '/js' ) );
});
```
Then I added in ```
gulp.task( 'scripts', function() {
 paths.dev + '/js/aos.js'
```
next step run
```gulp copy-assets```
and 
```gulp scripts```
but nothing is generated. Can I help me?

**Comment by pyRadiohead** [comment]
Try paths.vendor instead of '/js' when pipe...Also scripts looks like this, right? ```var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js',

        //Adding js-cookie package to the script list
        paths.dev + 'js/js.cookie.js'
    ];```
