### ISSUE TITLE
How to disable page titles

### ISSUE THREAD

**Issue by gs54** [understrap/understrap#773]
## Issue is about..
  - [X] a Question

## Please tell us about your environment:
  - **WordPress Version:** 4.9.8
  - **Understrap Version:** 0.8.6
---
Hi,
Is there a place to disable page titles which shows up on every page?
I know it is possible to do with css, but I were thinking about a checkbox or similar.
Thanks

**Comment by holger1411** [comment]
Hi!
No, there is no checkbox for that.
If you want to disable all titles on pages open /loop-templates/content-page.php and remove line 13:
https://github.com/understrap/understrap/blob/master/loop-templates/content-page.php#L13

Thats where the page title is outputted.

**Comment by gs54** [comment]
Thank you for your answer.
Changing the template means it will be overwritten on updates?
Maybe something to put on a wishlist?
Regards

**Comment by Thomas-A-Reinert** [comment]
That probably won't change. Promised. Use a child-theme instead.

**Comment by holger1411** [comment]
Hi! Yes, UnderStrap is more a developer theme framework. So adding a checkbox for deactivating the title isnt an option (or we could add hundrets and hundrets of checkboxes...).
So using  a child theme or, if you don´t plan any other changes, creating an special page template without title is an option.
