### ISSUE TITLE
Unable to make SCSS or CSS changes

### ISSUE THREAD

**Issue by gfrow** [understrap/understrap#774]
## Issue is about..
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - XAMPP (Localhost)
   - Microsfot Visual Studio

---

# Issue Overview for Bugreports

Using my child-theme, I seem to be unable to get any CSS elements - using the SCSS files or the child-theme.css - to make any changes to the site styles. Making changes to the .SCSS files, or the .CSS directly, files does not seem to make a difference. 

I want to change the primary color from purple to a blue (#0070AD0, for example, but it's staying on the default purple.  

I have tried to make changes on two machines. I've done all the basic troubleshooting steps such as restarting, re-installing, clearing the cache, compiling etc. but all to no avail. 

## *Who* is the bug affecting?
I have seen others online with the same issue, but I have not been able to replicate any of the fixes proposed.

## *What* is affected by this bug?
The entire site styling is non-functional past the defaults. 
## *When* does this occur?
It's consistent. 

## *Where* on the platform does it happen?
_child_theme_variables.scss
## *How* do we replicate the issue?
Try to make changes to the ...variables.scss and/or child-theme.css. Not sure. 
## Screenshots / Video
![primary-color](https://user-images.githubusercontent.com/35480913/44008299-08ee8fe4-9e70-11e8-801e-3b99c655a6e0.PNG)

## Expected behavior
My expectation us for the SCSS to change CSS when compiling and therefore change the styling elements.  

### Other Comments
I'll admit that I do not have a ton of experience with SASS, but I'd like to think that that's not the issue. I've watched a few tutorials and attempted to follow instructions on fixes...but, nothing. Any help would be greatly appreciated.

**Comment by Thomas-A-Reinert** [comment]
And the solution was...?
