### ISSUE TITLE
Disable/Enable WooCommerce Sidebar

### ISSUE THREAD

**Issue by RobertAlan** [understrap/understrap#781]
## What's the appropriate way to disable the WooCommerce product page sidebar in Understrap? 
 
I can easily hide the sidebar via CSS and also see where I can revise the bootstrap grid here (understrap>global-templates>left-sidebar-check.php) but this has undesirable implications across the entire site. Any suggestions or help would be appreciated.

  - [X] a Question
  - [X] I need help

---

**Comment by holger1411** [comment]
Hi!
You can trim the code for your woocommerce template here:
https://github.com/understrap/understrap/blob/master/inc/woocommerce.php
Especially in line 32-57
```

/**
* Then hook in your own functions to display the wrappers your theme requires
*/
add_action('woocommerce_before_main_content', 'understrap_woocommerce_wrapper_start', 10);
add_action('woocommerce_after_main_content', 'understrap_woocommerce_wrapper_end', 10);
if ( ! function_exists( 'understrap_woocommerce_wrapper_start' ) ) {
	function understrap_woocommerce_wrapper_start() {
		$container   = get_theme_mod( 'understrap_container_type' );
		echo '<div class="wrapper" id="woocommerce-wrapper">';
	  echo '<div class="' . esc_attr( $container ) . '" id="content" tabindex="-1">';
		echo '<div class="row">';
echo '<div class="col-md-12">';
		echo '<main class="site-main" id="main">';
	}
}
if ( ! function_exists( 'understrap_woocommerce_wrapper_end' ) ) {
function understrap_woocommerce_wrapper_end() {
	echo '</main><!-- #main -->';
echo '</div><!--col-md-12 end -->'; 
  echo '</div><!-- .row -->';
	echo '</div><!-- Container end -->';
	echo '</div><!-- Wrapper end -->';
	}
}
```

That removes the sidebarchecks for your woocommerce template (will not affect non-woocommerce pages) and replace it with a simple "col-md-12" column as wrapper

Don´t test it...but it should work.

**Comment by RobertAlan** [comment]
Works perfectly! Thank you so much. I really appreciate this.
