### ISSUE TITLE
Browser synch port lost when browsing

### ISSUE THREAD

**Issue by sommerset** [understrap/understrap#783]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Question

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** MacOS [10.10.5]
  - **Browser:** [ Chrome ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V 8.10] | NPM [V 6.30]

---
Hi everyone.

the last few projects I started with understrap are behaving differently than the previous ones.
Normally when running gulp watch-bs I can browse the site and all the links still include the BS port (:3000)  but lately the port is gone so I need to re type it  everytime I browse to a different page.

Is there a setting I am missing or that I can change?
Thanks in advance.
Ignacio

**Comment by axlright** [comment]
@sommerset are you still experiencing this issue? If so, can you provide any further details? I've been using `gulp watch-bs` extensively and have not seen the issues you're reporting.

**Comment by sommerset** [comment]
Not anymore but it was probably something I customized.  
I normally change the name of the task from 'watch-bs' to 'go'  because I am a lazy person.
I remember reverting that change fixed it  but it is still weird since I've done that since I started using Understrap.
Feel free to close this,  If it happens again, I'll post here again.

**Comment by axlright** [comment]
Thanks @sommerset - will close.
