### ISSUE TITLE
Widget description text is not translation read

### ISSUE THREAD

**Issue by gillespieza** [understrap/understrap#785]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [x] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** [Windows 10] | 
  - **Browser:** [ all ]
  - **Language:** [ PHP ]

---

# Issue Overview for Bugreports

## Steps to reproduce?
Open the file `inc/widgets.php`

## *Who* is the bug affecting?
Anyone using a non-English version of WordPress

## *What* is affected by this bug?
The description of the widget areas, that appears under the widget area heading/title

## *When* does this occur?
Permanently

## *Where* on the platform does it happen?
On the backend

## *How* do we replicate the issue?
n/a

## Are there any related Issues and/or PRs?
n/a

## Screenshots / Video
n/a

## Expected behavior
I expected this to be in internationalisation format, not a simple string

# Todos
Rewrite `'description'   => 'Right sidebar widget area',` etc with __ and theme text domain

**Comment by holger1411** [comment]
Closing this because it was fixed: https://github.com/IanDelMar/understrap/commit/2f1228a812e6495498abac9380cf3daa3e61ccd1
