### ISSUE TITLE
Hero Slider doesn't work on mobile

### ISSUE THREAD

**Issue by MartynaBogdanska** [understrap/understrap#786]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.7
  - **MacOS [10.13.4] | iOS [11.4.1]
  - **Browser:** [ all ]
---

# Issue Overview for Bugreports

## *What* is affected by this bug?
Homepage slider on mobile:
http://test.chirolife-bodensee.de/

**Comment by holger1411** [comment]
Works here...test it with an iPhone 7

**Comment by Thomas-A-Reinert** [comment]
Works for me too. Closing this due to no feedback though.

**Comment by MartynaBogdanska** [comment]
Sorry guys, I was out of office.
I had to remove that built-in slider widget and replaced it with another plugin as it didn't work everywhere I checked.
