### ISSUE TITLE
Is there a way of specifying a different page template as default

### ISSUE THREAD

**Issue by mherda** [understrap/understrap#791]
Hi
As the title indicates, how do I specify a default page template?

Thank you

**Comment by IanDelMar** [comment]
Either use the Customizer or (assuming you are using a child theme) put this in your functions.php
```php
function yourprefix_change_default_sidebar_postion() {
	set_theme_mod( 'understrap_sidebar_position', 'your-sidebar-postion' );
}
add_action( 'after_switch_theme', 'yourprefix_change_default_sidebar_postion' );
```
where 'your-sidebar-postion' is 'both' (right & left sidebar), 'left' (left sidebar), 'none' (no sidebar, i.e. fullwidth page).

**Comment by mherda** [comment]
Thanks

**Comment by mherda** [comment]
Hi.

Sorry, I'm still struggling with that. I'm not using a child theme. I've been reading the Customizer documentation but can't make sense of it.

I've deleted all the page template files (apart from the ones I have modified/created and use) and still all original page template choices are available in the dropdown menu of a page attributes in the dashboard.

Any guidance how I'd do it in Customizer?

Thank you

**Comment by IanDelMar** [comment]
Removing page templates from the dropdown is different from setting a different default page template. Take a look at #775 for the latter.

**Comment by mherda** [comment]
Thanks for the link. Yeah, the point about removing the templates was only a side note. I'm trying to set the default template in Customizer, not sure how to start. I have been reading inc/customizer.php but cannot see anything related to page templates.

**Comment by IanDelMar** [comment]
Sorry, I can't figure out what exactly you are trying to achieve.

UnderStrap's page templates as well as your own show up as dropdown in the page attributes metabox. Issue 775 tells you how to change that. Which of the UnderStrap page templates is treated as default (i.e. the one showing up as 'Default Template' in the page attributes metabox's dropdown) is specified using the sidebar position. How to change that from UnderStrap's default (right) to both, left or none using code is covered in my first reply. When stating "Either use the Customizer [...]" I meant clicking on customize in your admin bar and navigate to 'Theme Layout Settings' and change (default) 'Sidebar Positioning' there.

Could you explain in more detail what you are trying to change?

**Comment by mherda** [comment]
Thank you Ian. 

The problem is that the answers provided assume one uses a child theme. I don't.

**Comment by IanDelMar** [comment]
The 'Sidebar Positioning' options for setting the default page template are added in inc/customizer.php line  105-110. By default UnderStrap uses 'right' which is set in inc/theme-settings.php line 23. You may also use 
```php
function yourprefix_change_default_sidebar_postion() {
	set_theme_mod( 'understrap_sidebar_position', 'your-sidebar-postion' );
}
add_action( 'after_setup_theme', 'yourprefix_change_default_sidebar_postion' );
```
somewhere you put your functions. Notice that it's the **after_setup_theme** hook now. 

To remove a page template from the dropdown in the page attributes metabox remove the words 'Template Name:' in line 2 of the corresponding page template file.

**Comment by mherda** [comment]
Thank you. I think we're getting closer to understanding it. Having said that, it still puzzles me. My apologies but I must be missing something here. According to the sidebar positions, there are only 4 options (right, left, both, none). Yet even in the original set of templates, there are more than 4 templates. So what happens if I'd like to set my custom template called "Generic Page" as the default?

**Comment by IanDelMar** [comment]
You haven't had a closer look into the theme yet, right?
The additional templates you're referring to are the blank and the empty page template. Both templates do not have a sidebar. Compare them to the full width template.
If you choose the 'Default Template' either index.php or page.php is called. index.php as well as page.php is prepared to handle the 4 sidebar position options. The other templates are set up to handle their name's sidebar position.
Put the content of your 'Generic Page' template into page.php. (https://developer.wordpress.org/themes/basics/template-hierarchy/)

**Comment by mherda** [comment]
Thank you very  much. I did look into the theme but as it turns out I completely misunderstood how the 'Default' is being picked. I thought there should be a template called "Default Template":) 
I'm aware of Wordpress standard template hierarchy. Makes sense now. Thank you.
