### ISSUE TITLE
gulp copy-assets failing

### ISSUE THREAD

**Issue by QTRichieRich** [understrap/understrap#797]
I having issues running npm install.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! colourmehappy2018@0.0.1 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the colourmehappy2018@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Here's the log file.
0 info it worked if it ends with ok
1 verbose cli [ '/.nvm/versions/node/v9.2.0/bin/node',
1 verbose cli   '/.nvm/versions/node/v9.2.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@6.4.1
3 info using node@v9.2.0
4 verbose npm-session 344f69e1db84e2f5
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall colourmehappy2018@0.0.1
7 info lifecycle colourmehappy2018@0.0.1 preinstall: colourmehappy2018@0.0.1
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 3243ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 21ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1495ms
16 silly install loadAllDepsIntoIdealTree
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 1878ms
18 timing stage:loadIdealTree Completed in 4304ms
20
20
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 163ms
23 silly diffTrees action count 0
24 silly decomposeActions action count 0
25 silly install executeActions
26 silly doSerial global-install 0
27 verbose correctMkdir /.npm/_locks correctMkdir not in flight; initializing
28 verbose lock using /.npm/_locks/staging-b8f30a6e60875d49.lock for /wp-content/themes/rds_colourmehappy2018/node_modules/.staging
29 silly doParallel extract 0
30 silly doReverseSerial unbuild 0
31 silly doSerial remove 0
32 silly doSerial move 0
33 silly doSerial finalize 0
34 silly doParallel refresh-package-json 0
35 silly doParallel preinstall 0
36 silly doSerial build 0
37 silly doSerial global-link 0
38 silly doParallel update-linked 0
39 silly doSerial install 0
40 silly doSerial postinstall 0
41 verbose unlock done using /.npm/_locks/staging-b8f30a6e60875d49.lock for /wp-content/themes/rds_colourmehappy2018/node_modules/.staging
42 timing stage:executeActions Completed in 20ms
43 timing stage:rollbackFailedOptional Completed in 1ms
44 silly install runPostinstallTopLevelLifecycles
45 silly build colourmehappy2018@0.0.1
46 info linkStuff colourmehappy2018@0.0.1
47 silly linkStuff colourmehappy2018@0.0.1 has /wp-content/themes as its parent node_modules
48 silly install colourmehappy2018@0.0.1
49 info lifecycle colourmehappy2018@0.0.1install: colourmehappy2018@0.0.1
50 silly postinstall colourmehappy2018@0.0.1
51 info lifecycle colourmehappy2018@0.0.1postinstall: colourmehappy2018@0.0.1
52 verbose lifecycle colourmehappy2018@0.0.1postinstall: unsafe-perm in lifecycle true
53 verbose lifecycle colourmehappy2018@0.0.1postinstall: PATH: /.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/wp-content/themes/rds_colourmehappy2018/node_modules/.bin:/.nvm/versions/node/v9.2.0/bin:/Library/Android/sdk/platform-tools:/Library/Android/sdk/tools:/Applications/MAMP/bin/php/php5.6.30/bin:/usr/local/aws/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Library/Android/sdk/platform-tools:/Library/Android/sdk/tools:/Applications/MAMP/bin/php/php5.6.30/bin:/usr/local/aws/bin
54 verbose lifecycle colourmehappy2018@0.0.1postinstall: CWD: /wp-content/themes/rds_colourmehappy2018
55 silly lifecycle colourmehappy2018@0.0.1postinstall: Args: [ '-c', 'gulp copy-assets' ]
56 timing audit compress Completed in 47ms
57 info audit Submitting payload of 62150bytes
58 http fetch POST 401 https://npm.fontawesome.com/-/npm/v1/security/audits/quick 964ms
59 timing audit submit Completed in 1657ms
60 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1658ms
61 timing audit body Completed in 2ms
62 silly lifecycle colourmehappy2018@0.0.1postinstall: Returned: code: 1  signal: null
63 info lifecycle colourmehappy2018@0.0.1postinstall: Failed to exec postinstall script
64 verbose stack Error: colourmehappy2018@0.0.1 postinstall: `gulp copy-assets`
64 verbose stack Exit status 1
64 verbose stack     at EventEmitter.<anonymous> (/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
64 verbose stack     at EventEmitter.emit (events.js:159:13)
64 verbose stack     at ChildProcess.<anonymous> (/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
64 verbose stack     at ChildProcess.emit (events.js:159:13)
64 verbose stack     at maybeClose (internal/child_process.js:943:16)
64 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
65 verbose pkgid colourmehappy2018@0.0.1
66 verbose cwd /wp-content/themes/rds_colourmehappy2018
67 verbose Darwin 17.7.0
68 verbose argv "/.nvm/versions/node/v9.2.0/bin/node" "/.nvm/versions/node/v9.2.0/bin/npm" "install"
69 verbose node v9.2.0
70 verbose npm  v6.4.1
71 error code ELIFECYCLE
72 error errno 1
73 error colourmehappy2018@0.0.1 postinstall: `gulp copy-assets`
73 error Exit status 1
74 error Failed at the colourmehappy2018@0.0.1 postinstall script.
74 error This is probably not a problem with npm. There is likely additional logging output above.
75 verbose exit [ 1, true ]

**Comment by m4v1** [comment]
Backup your theme folder then try this:

- remove the node_modules folder
- delete the package-lock.json file

then open a shell in the theme folder and:

- update npm deps with:    `npm update`
- reinstall with:    `npm install`

**Comment by holger1411** [comment]
Does @m4v1 solution solved your problem?
If not: Feel free to re-open!
