### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by aaronrobb** [understrap/understrap#798]
Please delete anything that does not apply for you!

## Issue is about..
  - [ X ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** Latest
  - **OS Version:** Ubuntu on Cloud9 IDE
  - **Browser:** [Chrome]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [6.11.2] | NPM [V 3.10.10]

---

Trying to install the theme via npm, I get this output:

`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.

> understrap@0.8.6 postinstall /home/ubuntu/workspace/wp-content/themes/circles2018/node_modules/understrap
> gulp copy-assets

[18:09:08] Using gulpfile ~/workspace/wp-content/themes/circles2018/node_modules/understrap/gulpfile.js
[18:09:08] Starting 'copy-assets'...
[18:09:08] Finished 'copy-assets' after 30 ms
/home/ubuntu/workspace/wp-content/themes/circles2018
└─┬ understrap@0.8.6 
  └── UNMET PEER DEPENDENCY jquery@1.9.1 - 3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/gulp-watch/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/workspace/wp-content/themes/circles2018/package.json'
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN circles2018 No description
npm WARN circles2018 No repository field.
npm WARN circles2018 No README data
npm WARN circles2018 No license field.`

Then nothing installs.
Biggest thing i believe is the "UNMET PEER DEPENDENCY jquery@1.9.1 - 3"

But i cannot update that until i have a working package.json file in the theme folder.....
Which i assume will come when i install the theme??

**Comment by ThomasDK81** [comment]
I get exactly the same errors.

**Comment by mowens3** [comment]
had a similar error attempting `gulp watch`

1) edit this file:
`node_modules/bootstrap/package.json`

2) replace instances of jquery to use a more flexible version:
`"jquery": "^1.9.1",`

3) re-run your original command.

I had to run a few other commands to reinstall modules:
npm rebuild node-sass
npm install gulp -g

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
