### ISSUE TITLE
Gulpfile seems to be broken

### ISSUE THREAD

**Issue by juona** [understrap/understrap#808]
Just downloaded the zipped underscores master branch, ran npm i and it failed on gulp copy-assets.

After inspecting gulpfile.js I've come to a conclusion that incidentally that the definition of the copy-assets task itself (`gulp.task( 'copy-assets', function() {`) is never closed, and so the file cannot be parsed. In your code that should happen somewhere around line 200. Closing the function and method invocation fixed the problem for me.

**Comment by holger1411** [comment]
@VarunBatralT ´s solution should fix this. I close this. Let me know if there are still problems!
