### ISSUE TITLE
BrowserSync not reloading after sass recompliation

### ISSUE THREAD

**Issue by adrisantos07** [understrap/understrap#811]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** MacOS [Version] 
  - **Browser:** [ Chrome XX]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

## **Issue Overview for Bugreports**
Browsersync loads URL properly after running gulp watch-bs, but does not reload site after recompiling sass files. 
When running the task watch-bs files are correctly compiled, however browsersync does not reload

## **Steps to reproduce** 
Download the repo and follow the instructions to change the browser-sync options to reflect your environment in the file `/gulpconfig.json`

## **Expected behaviour**
BrowserSync should reload the site every time sass files are changed and compiled.

## **Actual behaviour**
The task watch-bs compiles the files but does not reload the site after.

**Comment by roman-soerensen** [comment]
Same issue here. Seems that something went wrong when updating to gulp4 and downgrading afterwards. Since that point I have problems with browsersync not updating and chrome not showing the sass files in the developer window (not using the sourcemap)

**Comment by adrisantos07** [comment]
Hi @roman-soerensen , could you share the code I should add to my gulpfile.js file??
I tried watching the unminified css files but didn't make any difference. Maybe I did something wrong?
Cheers

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
