### ISSUE TITLE
How to change sass output style?

### ISSUE THREAD

**Issue by superfein** [understrap/understrap#812]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Question

## Please tell us about your environment:

  - **OS Version:** [ Windows 10 ]
  - **Language:** [ S/CSS ]

---

# Issue Overview

I am trying to change the output style when I process _child_theme.scss file into child-theme.css. I've tried adding `outputStyle: nested` to the SASS .pipe, but it has no effect. What does work is when I do the gulp watch command and I add `--style nested` to the command. But how do I add this to the gulpfile.js so I have it as part of the task?

```
gulp.task( 'sass', function() {
    var stream = gulp.src( paths.sass + '/*.scss' )
        .pipe( plumber( {
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe( sass( { 
            outputStyle: 'nested',
            precision: 10,
            errLogToConsole: true
             } ) )
        .pipe( autoprefixer( 'last 2 versions' ) )
        .pipe( gulp.dest( paths.css ) )
        .pipe( rename( 'custom-editor-style.css' ) );
    return stream;
});
```

**Comment by axlright** [comment]
@superfein Did you find a solution to this? It looks like you're asking about the child theme or are you trying to rename the compiled css file in the parent Understrap theme?

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
