### ISSUE TITLE
Sass/JS/PHP file modifications get automatically overwritten when a new theme version is published

### ISSUE THREAD

**Issue by abepark01** [understrap/understrap#814]
Please delete anything that does not apply for you!

## Issue is about..
  - [X] a Bug Report
  - [X] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** MacOS 10.
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js 8.11.3 | NPM V6.4.1

---

# Issue Overview for Bugreports

## Steps to reproduce?
Load the website after an update has been issued

## *Who* is the bug affecting?
The theme files get automatically updated and overwrites any modifications made to the sass folder gets overwritten

## *What* is affected by this bug?
The entire website is reverted to the theme defauls

## *When* does this occur?
It occurs after a understrap theme update has been published.

## *Where* on the platform does it happen?
All

## *How* do we replicate the issue?
Make changes to the sass folder or any JS file. wait for a theme update and then see the changes get overwritten

## Are there any related Issues and/or PRs?
Not sure

## Screenshots / Video
![screenshot 2018-09-20 14 45 07](https://user-images.githubusercontent.com/7087312/45848559-d3188e00-bce3-11e8-8892-42ab7325f098.png)
![screenshot 2018-09-20 14 45 13](https://user-images.githubusercontent.com/7087312/45848560-d3188e00-bce3-11e8-8707-18c81b8a79c3.png)

## Expected behavior
The theme to not get overwritten.

# Todos
It would be great to be able to turn off auto-updates.

 * Test
 * Documentation

**Comment by Thomas-A-Reinert** [comment]
Hi @abepark01 .
This is totally intended as UnderStrap is meant to be a Starter Theme to built your own theme upon (Rename theme folder, adjust styles.css).

If you want to be able to still use the main theme, keep it updated and just want to make any modifications to it, set up a child theme and none of your changes will be overwritten.

If you worked with the "templatable" files in themes/understrap/sass/theme none of your changes will be overwritten either. But I guess you just overwrote some of BootStraps or UnderStraps core file in (in themes/understrap/sass/assets or themes/understrap/sass/understrap) that _will_ be overwritten in fact with every update. Not the recommended way.

It´s a bad thing and I really do not recommend to do that, but in fact you **can** totally disable theme core/plugin/theme updates. But as we judge this to be really irresponsible I guess your wish will never be integrated. If you want to do that on your own, add the following lines to the end of your functions.php:

```php
// hide update notifications
function remove_core_updates(){
   global $wp_version;return(object) array('last_checked'=> time(),'version_checked'=> $wp_version,);
}
// add_filter('pre_site_transient_update_core','remove_core_updates'); //hide updates for WordPress itself
// add_filter('pre_site_transient_update_plugins','remove_core_updates'); //hide updates for all plugins
add_filter('pre_site_transient_update_themes','remove_core_updates'); //hide updates for all themes
```

For what you want to achieve, i´d recommend disabling the first two filters and just leave the last one uncommented.

**Comment by abepark01** [comment]
Thanks @Thomas-A-Reinert! appreciate the notes
I must have overwritten the wrong set of files...
