### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'my_magic_function' not found or invalid function name in C:\xampp\htdocs\Project001\wp-includes\class-wp-hook.php on line 286

### ISSUE THREAD

**Issue by nouman112** [understrap/understrap#818]
Hi getting this warning message !  
i am creating custom plugin & don't know why wordpress is saying that magic function is invalid function.
by the way i've deactivated all the plugins please help

**Comment by 0dp** [comment]
It's an error in your custom plugin.
in you constructor you probably have to do `add_action('something', array($this, 'my_magic_function));`

**Comment by holger1411** [comment]
Because it seems it is a non-understrap issue I close this.
Feel free to re-open if needed!
