### ISSUE TITLE
Sass maps in production

### ISSUE THREAD

**Issue by barrypoore** [understrap/understrap#819]
Please delete anything that does not apply for you!

## Issue is about..

  - [x] I need help

Hi I have built a site on understrap and all is good but after running $ gulp dist and $ gulp dist-product I can still see the sass partial references in the chrome inspector.

Should these not be removed in the production build task so if I inspect an element in the browser console it would point to the .css file rather then the sass partial?

**Comment by axlright** [comment]
It may be a matter of preference, but I prefer to be able to inspect the element and see the sass reference, as the css reference would be to a minified file where everything is on the same line. You can delete the css map file from the production files before sending to your server if you'd rather not see the sass map referencing.

**Comment by axlright** [comment]
@barrypoore point taken. The development community will take this preference into account for future development. I'll close this ticket - feel free to reply with a comment if you need anything else about this issue. Thanks for reaching out!
