### ISSUE TITLE
Issue with php 7.2

### ISSUE THREAD

**Issue by KobuKovu** [understrap/understrap#820]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report

## Please tell us about your environment:
  - **OS Version:MacOS Mojave
  - **Browser:** [ all |
  - **Language:** PHP

---

# Issue Overview for Bugreports

`: Uncaught Error: Class 'WP_Bootstrap_Navwalker' not found in /Users/briant/Sites/wordpress/wp-content/themes/draft-understrap-child-theme/header.php:73 Stack trace: #0 /Users/briant/Sites/wordpress/wp-includes/template.php(688): require_once() #1 /Users/briant/Sites/wordpress/wp-includes/template.php(647): load_template('/Users/briant/S...', true) #2 /Users/briant/Sites/wordpress/wp-includes/general-template.php(41): locate_template(Array, true) #3 /Users/briant/Sites/wordpress/wp-content/themes/understrap/index.php(18): get_header() #4 /Users/briant/Sites/wordpress/wp-includes/template-loader.php(74): include('/Users/briant/S...') #5 /Users/briant/Sites/wordpress/wp-blog-header.php(19): require_once('/Users/briant/S...') #6 /Users/briant/Sites/wordpress/index.php(17): require('/Users/briant/S...') #7 {main} thrown in
`
## Steps to reproduce?
I'm running mac local development with homebrew/php7.2.10/mariadb/apache. Fresh wordpress installation , understrap and draft-understrap-child-theme. Working fine with parent theme but not child theme.

**Comment by holger1411** [comment]
Hi!
no, its not a problem with PHP 7.2
We renamed the "WP_Bootstrap_navwalker" function to "Understrap_WP_Bootstrap_Navwalker"

If you use a child theme with your own version of header.php check this file and make sure you rename the function, too.

Search for:
				
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'collapse navbar-collapse',
						'container_id'    => 'navbarNavDropdown',
						'menu_class'      => 'navbar-nav ml-auto',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'depth'           => 2,
						'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
					)
				); ?>

and check the "Walker" name.

**Comment by holger1411** [comment]
Hopefully this solves your issue.
Feel free to re-open if not.
