### ISSUE TITLE
understrap, understrap-child -> woocommerce

### ISSUE THREAD

**Issue by Podtwal** [understrap/understrap#821]
Please delete anything that does not apply for you!

## Issue is about..
  - [ x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** [ Windows 10]
  - **Browser:** [ all ]
  - **understrap**  [ 0.8.7 ]
  - **understrap-child**  [ 0.5.3 ]
---

Hello.
I started my first woocommerce project with understrap. Beside understrap I use the understrap-child theme in version 0.5.3.
Now I noticed that if I have activated the child theme the layout is not correct. If I activate "only" understrap then everything fits again.
Do I still have to set something special in the child theme?

**Comment by holger1411** [comment]
Can you provide a screenshot or URL?
To reproduce the problem I need to know where it happends.
And: Do you do any changes to the child theme?

**Comment by Podtwal** [comment]
Hello, Holger.
Thank you for answering my question.
I have unfortunately only come today to look at the whole again a little more closely... but, I found the problem.

The problem is that the following call in child-theme.scss does not take place:
@import "understrap/woocommerce";

If I copy the content of this CSS file ( is only **.woocommerce-input-wrapper** and **.figure.woocommerce-product-gallery__wrapper** ), then everything works fine in the child theme.

I think this is possibly a bug in the child-theme?
