### ISSUE TITLE
cant do sudo npm install

### ISSUE THREAD

**Issue by marinabcoding** [understrap/understrap#823]
I am working on a macbook and in iterm, i did sudo npm install and recieved the following error. 

[2018-10-11T19_44_53_586Z-debug.log](https://github.com/understrap/understrap/files/2470476/2018-10-11T19_44_53_586Z-debug.log)

**Comment by consciousimages** [comment]
I'm far from an expert but that is a permissions error.  Unless there's a specific reason you're using sudo, I wouldn't -- always best to start without it as you can run into problems later that are hard to troubleshoot (trust me).  If you installed npm and gulp using sudo, that might be what's happening.  If so, I'd suggest starting over.  Also you'll want to move the theme folder out of your downloads folder - you'll want to move it to your local WP install.  I installed the theme for the first time today, and everything went well... so it's not an issue with the theme -- poke around on stackoverflow for your error and npm and see what you can find out.  The install instructions for the theme leave a bit to be desired (as it says at the top).  There's going to be simpler themes out there using underscores and bootstrap to get up and running with... I'm sorry I can't provide better instructions, the good news is once you have npm/gulp and other build tools installed globally you won't have to worry that end of things too much... but it can be a time-consuming process getting everything sorted out.

**Comment by holger1411** [comment]
Seems to be a non-understrap specific issue, so I´am closing this.
Feel free to re-open if needed!
