### ISSUE TITLE
gutenberg compatibility understrap

### ISSUE THREAD

**Issue by mariello124** [understrap/understrap#831]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ X] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **  computer  local debian 9
  - **Browser:**| Chrome  Firefox
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery 
  

---

mine is not a problem I ask
understrap already is for gutemberg
Thank you

**Comment by Thomas-A-Reinert** [comment]
Have you tried? There are many pre-plugins avail and we cannot test on EVERY customized solution..
