### ISSUE TITLE
Why use a child theme?

### ISSUE THREAD

**Issue by aaronrobb** [understrap/understrap#839]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [X] a Question
  - [ ] I need help

Just a simple question.
If the main theme is good to be edited and developed upon, why would we use a child theme?
Is it really only for if the main understrap theme gets a major update?

Just looking for opinions.

**Comment by Thomas-A-Reinert** [comment]
1. Because there are free and commercial Child themes available.
2. Because you can. 
3. Because some devs want to have their own dev-branch in a Child theme and be able to update the "core". And do a diff between both. 

And the first and the last may be the most relevant answers for you.
