### ISSUE TITLE
bootstrap 413 util.js:56 Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by AshLingua** [understrap/understrap#842]
A previous version of this error was reported for beta 2, and was supposed to be resolved. But here a version of it appears to persist:
  
- [ ] a Bug Report
 /  - [ ] a Question
    - [ ] I need help

Windows 10] |
 Web Browser | Chrome Version 70.0.3538.77 (Official Build) (64-bit)
  - **Language:** [ PUG| HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [10.10] | NPM 6.4.1

on loading a local style with bootstrap -   link(href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", rel="stylesheet", integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", crossorigin="anonymous")
    script(src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js", integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", crossorigin="anonymous")
    script(src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js", integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl", crossorigin="anonymous")
    link( href="styles.css" rel="css/stylesheet")  

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
