### ISSUE TITLE
Language files not working on live site.

### ISSUE THREAD

**Issue by fivetimesnine** [understrap/understrap#843]
Made a (multilingual) website using the latest understrap and wordpress versions. Everything worked fine on localhost, but on the live site the theme's translation files (.pot, .po, .mo) are not working. All theme related strings are stuck on English. All non-theme related translations do work. 

When switching to another theme, all those theme's translations do also work. It is the understrap translations only that do not work. I have double checked the related .pot, .po and .mo files and they are all correct and in the right location, exactly the same as on my localhost.

Example:
![image](https://user-images.githubusercontent.com/44839722/48136889-1a150f80-e2a1-11e8-90c5-63cafff61651.png)
In this screenshot the website's language is set to Dutch. You are looking at the WooCommerce -> My Account -> Edit Addresses page. As you can see the translations that are pulled from the WooCommerce plugin language files are correct (the menu on the left, country). The strings that are supposed to be translated from the understrap language files are stuck on English. On my localhost all those strings are translated correctly.  

Everything else on the live site is working like it's supposed to.

Any ideas on what might have went wrong?

**Update: Reproduced the bug**
After testing a couple of things, I have found out that the bug occurs when using the by "gulp dist" produced theme folder. Even though the language files are all correct and in place, they don't work. When using the theme folder including all dev files, the translations do work. Not sure yet what exactly makes the difference.

**Comment by IanDelMar** [comment]
Sounds like a text domain issue to me. Did you change the text domain from 'understrap' to something else?

**Comment by fivetimesnine** [comment]
> Sounds like a text domain issue to me. Did you change the text domain from 'understrap' to something else?

I haven't changed the text domain. Text domain is still 'understrap' and is also referred to correctly. Thanks for your quick reply though.

**Comment by DUGeCommerce** [comment]
Maybe the same problem -> #838

**Comment by fivetimesnine** [comment]
**Update: Reproduced the bug**
After testing a couple of things, I have found out that the bug occurs when using the by "gulp dist" produced theme folder. Even though the language files are all correct and in place, they don't work. When using the theme folder including all dev files, the translations do work. Not sure yet what exactly makes the difference.

**Comment by arumcomputer** [comment]
My translation is not working as well (understrap and understrap child). Cloned directly from this repositories

**Comment by 0dp** [comment]
So what happens if you don't use gulp dist, and put that live, Same?

**Comment by arumcomputer** [comment]
I dont use gulp dist. i cloned the git repo and added it to my own on my gitlab server. on live site and on local machine i then clone that repo. local it is working and live not.
i guess there is maybe a package missing on server such as gettext...

**Comment by 0dp** [comment]
If possible check and compare php_info.

If would love to hear from OP whether situation have changed since latest commit.

**Comment by Thomas-A-Reinert** [comment]
In case it works on a dev-site (and I personally can confirm that translations worked on any site I worked on) and does NOT on some server, I assume we can close that issue.
