### ISSUE TITLE
parent functions.php include incompatible with child themes

### ISSUE THREAD

**Issue by halyburton** [understrap/understrap#845]
## Issue is about..
  - [X] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** NGIX - pantheon hosted
  - **Browser:** all
  - **Language:**  php

---

# Issue Overview for Bugreports
When using the theme as a parent theme, the included files referenced in the function.php don't fully execute. They exit at the ABSPATH check. Basically this caused none of the parent defined functionality to run in the admin. e.g. The sidebars, registered navs, theme support, etc from parent theme are never invoked. 

## Steps to reproduce?
Create a understrap_child theme from the git repo. After activating the child theme, the widgets menu disappears under appearance. Among others. 

## *Who* is the bug affecting?
I think all child themes, but at least any site i have running on pantheon.

## *What* is affected by this bug?
All parent theme settings and functionality

## *When* does this occur?
Always

## *Where* on the platform does it happen?
Admin

## *How* do we replicate the issue?
After activating the child theme that is using understrap 0.8.8 as the parent. You can make the 

## Are there any related Issues and/or PRs?
No

### Other Comments
This appeared with the latest release 0.8.8 when the functions.php file was refactored. If I switch back to use the previous method of inclusion "require_once get_template_directory() . '/inc/setup.php';" it works fine. But after refactoring and using "locate_template( '/inc' . $file )", while it doesn't trigger an error, it appears to cause the the system to direct access the included file thus stopping processing at the ABSPATH check. So there is two workarounds, change how the files are included, or remove the ABSPATH check at the top of any included file.

**Comment by IanDelMar** [comment]
I can't replicate the issue on my local environment.

**Comment by halyburton** [comment]
It was hard to notice the issue. It really became apparent when i went to upload a new logo for the site, and the field wasn't there. It didn't seem to break the front end of the site, only the admin's ability to configure it. 

All I can tell is that locate_template must return some different path then get_template_directory() or is called in a different way in this environment. Any idea why there was the switch?

**Comment by IanDelMar** [comment]
Everything's (sidebars, navs, logo, et cetera) fine here. It also throws the error if I try to include a file which is not present. Can you check what `locate_template( '/inc/extras.php') actually returns in your case?

**Comment by IanDelMar** [comment]
You can also try to do what I proposed in PR #846. Maybe your server does not interpret x/y being the sam as x//y.

**Comment by halyburton** [comment]
Thanks, it took a bit of debugging to figure out the issue in the first place. It includes the files just fine, the problem is that the direct access check at the top is where the problem lies. It’s that check that is true and exit is returned. I am not an expert of word press to know when or why that method of inclusion seems to cause my instances to be seen as direct access. I tired some research, but the documentation doesn’t seem to be to clear. I would love to do a pull request, but not sure why it was changed in the first place, other than one developers preference to include files.

**Comment by halyburton** [comment]
thank you, yes that was the issue and the PR did fix the issue.
