### ISSUE TITLE
Getting error when running the command npm install understrap

### ISSUE THREAD

**Issue by ahmu83** [understrap/understrap#847]
I tried to run the command `npm install understrap` in the `wp-content/themes/` directory and I got this error: 

http://prntscr.com/lhhvt4
http://prntscr.com/lhhv69

**Comment by 0dp** [comment]
hi @ahmu83, 

I don't think this is an issue with understrap, rather I believe it is a problem with nodejs
`internal/modules/cjs/loader.js`

Could I get you to try and reinstall nodejs?

**Comment by ahmu83** [comment]
Hello @0dp ,
So I deleted node and npm completely from my macos mojave and re-installed node 10.x and then went to the `/wp-content/themes/` directory and ran the command `npm install understrap` and this time everything worked fine except it create the directory `node_modules` in my `/wp-content/themes/` directory. I dont know what I am doing wrong. Please assist. Thanks!

**Comment by 0dp** [comment]
Great!
In fact nothing is wrong. Packages installed via npm will be placed in a folder called `node_modules` so you are doing nothing wrong.

npm is a package manager used to download your projects dependencies in a neasy fashion.
Using npm on a project makes your project a package itself.
So when you are running `npm install understrap` from within your themes folder, you are effectively adding understrap as a dependency of your project `themes`. This is not your desired result.
 
Instead I think you are better off downloading the theme from the understrap website or here for 'bleeding edge release'.

If you want to do cool command line stuff, instead execute these commands from your themes folder 😄 

`curl https://github.com/understrap/understrap/archive/0.8.8.zip -O -J -L`
`unzip understrap-0.8.8.zip`

**Comment by ahmu83** [comment]
thanks for the clarification :)

**Comment by ahmu83** [comment]
I have another question that is unrelated to this issue topic. Is there a way to move all the `.js scripts` to the footer? @0dp

**Comment by 0dp** [comment]
which scripts are you referring to?

**Comment by ahmu83** [comment]
Also is there a way to make the main menu support nested sub-menus? Right now I can see that its only supporting one level of sub-menu

**Comment by ahmu83** [comment]
> which scripts are you referring to?

I mean the `jquery.js, jquery-migrate.js, popper.js` files which are right now added right before </head> tag
And BTW I am using the https://github.com/understrap/understrap-child/ theme

**Comment by 0dp** [comment]
yes, look at `inc/enqueue.php` in the parent theme, you'll want to overwrite the file from your child-theme and change the enqueue_script and set the in_footer parameter to true.

Check out the WordPress documentation:
https://developer.wordpress.org/reference/functions/wp_enqueue_script/

Please close this issue, since the original question has been resolved

**Comment by ahmu83** [comment]
Thanks :)
