### ISSUE TITLE
widget and multilanguage

### ISSUE THREAD

**Issue by jodumont** [understrap/understrap#852]
## Issue is about..
  - [x] a Bug Report
  - [x] a Question
  - [x] I need help

I use a plain version of `understrap-child` and have a bilingual website with polylang
I presume it is related to the theme, but I might be wrong
I try by example to describe my issue

#### so I have 3 widget in my footer

- 1 = all language
- 1 = english
- 1 = french
![image](https://user-images.githubusercontent.com/5204724/48549119-29aedc80-e8cf-11e8-964e-52e9deaf0b81.png)

I expect having only 2colums with `col-md-6`; but instead the theme detect 3widgets and render `col-md-4`
![image](https://user-images.githubusercontent.com/5204724/48549374-e7d26600-e8cf-11e8-9571-c18fbb059ba4.png)

## Please tell us about your environment:

  - **WordPress Version:** 4.9.8
  - **OS Version:** Debian9
  - **Browser:** [ all | Chrome 70  | Firefox 63
  - **Language:** [ PHP | MySQL | HTML | S/CSS | Javascript | jQuery ]

**Comment by 0dp** [comment]
#796

**Comment by jodumont** [comment]
@0dp as you could saw, I comment on this issue before opening this one, so I saw it;
but I don't think it is related

**Comment by IanDelMar** [comment]
@jodumont It is exactly the same issue...

**Comment by holger1411** [comment]
@IanDelMar I merged your fix.
@jodumont: Could you use this inc/widgets.php version:https://github.com/understrap/understrap/blob/master/inc/widgets.php
and replace your old file with it to check if it solves your issue, too?

**Comment by Thomas-A-Reinert** [comment]
Issue seems to be resolved / abandoned / or whatsoever. Closing it for house-keeping. Feel free to re-open if the problem persists.

Besides: This problem is related to the child-theme and should be posted in it´s repo, not in the parent themes repo.
