### ISSUE TITLE
Unused packages, tasks, and inconsistent paths

### ISSUE THREAD

**Issue by ylkyrg** [understrap/understrap#853]
# Issue is about..
  - [ x] a Bug Report

## Issue Overview

There appears to be some unused packages installed:
- gulp-watch
- merge2
- gulp-clone
- merge

And some unused tasks:
- watch-scss (runs undefined task)
- cssnano (minifycss is used instead)

Also, the node and bower paths have a trailing slash while all others don't.

**Comment by holger1411** [comment]
Hi!
Yes, you are right. Relic´s of older versions.
Just gulp-watch is still in use.

Correct it here: https://github.com/understrap/understrap/commit/1208774d79dc0829f34c2b28d3b1322fc8a865b0

**Comment by Andrejs4** [comment]
For people who like me learn Worpress by step-by-step manuals - "gulp watch" is deprecated, now it is "npm run watch".
