### ISSUE TITLE
Some of the elements on the WooCommerce pages aren't bootstrap elements

### ISSUE THREAD

**Issue by ahmu83** [understrap/understrap#854]
If **understrap** is WooCommerce ready shouldn't all the form fields and other obvious elements. i.e, the WC notification (http://prntscr.com/lj7q1i) and the form fields on the cart, checkout & other pages (http://prntscr.com/lj7qt8 & http://prntscr.com/lj7rau & http://prntscr.com/lj7s04) reflect all the bootstrap styles?

**Here is a breakdown of the screenshots I referenced above:**

https://prnt.sc/lj7q1i `The notification is not bootstrap alert element, instead its the default WC HTML markup & styles`

https://prnt.sc/lj7qt8 `The form fields & notification/alert on the checkout page doesn't reflect bootstrap styles`

https://prnt.sc/lj7rau `Some of the form fields on the cart page does not inherit bootstrap styles`

https://prnt.sc/lj7s04 `Some of the form fields & the tabs on the product detail page does not inherit bootstrap styles`

Please elaborate if I am missing something. Thanks!

**Comment by 0dp** [comment]
@understrap/woocommerce-team

**Comment by HendricksenDesign** [comment]
The link returns a 404 page

**Comment by ahmu83** [comment]
The link returns a 404 page

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
