### ISSUE TITLE
Stripe inline input field for cc is disabled

### ISSUE THREAD

**Issue by sherinhashtag** [understrap/understrap#857]
**In my woocommerce checkout page, The credit card field wasn't on the form so I couldn't add the card number to submit an order. The field is missing, it is stripe inline** 
<img width="1441" alt="stripe" src="https://user-images.githubusercontent.com/36981855/48763387-336f8000-ecd3-11e8-8582-a15634358cd6.png">

**Comment by 0dp** [comment]
Hi @shansmith01 take a look here #682

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
