### ISSUE TITLE
Gulp uncss and Gulp postcss

### ISSUE THREAD

**Issue by axlright** [understrap/understrap#858]
Hello team from a wayward-and-wanting-to-return former contributor. It's been a while since I've been helping with this repo and I'd very much like to get back to helping. I'm not sure if you all are using the Slack channel that was once set up. Let me know the best way to find out where the team is discussing goals that I may be able to help with.

Per this specific "issue" - I've been using [UnCss](https://github.com/uncss/uncss) via [gulp-uncss](https://github.com/ben-eb/gulp-uncss) to remove all unused css from stylesheets on projects I'm building with UnderStrap. 

The results have been fantastic - I'm getting final compiled stylesheets down to 70kb - 80kb including all plugins, all custom styles and all of Bootstrap. Combining this with [CriticalCSS](https://alexwright.net/web-design-secrets/how-to-use-critical-css/) has meant I get great Lighthouse audit scores and fast loading websites.

I'm happy to document my uncss process if it's helpful for anyone.

gulp-uncss works fine with my workflow but it's been deprecated as it's now a plugin / part of [PostCSS](https://github.com/postcss/postcss)

Here's the actual question of this issue - I'm not super smart with this kind of thing so I'm reaching out to find out whether / in what ways UnderStrap uses or may plan to use PostCSS to minify, autoprefix or do any other post compiling work. If UnderStrap does use or plans to use PostCSS, I can potentially wrap my uncss workflow into the PostCSS process. If not, I can keep using it as a stand-alone but deprecated process.

Any advice is appreciated and please point me in a direction where I can get back to helping the team.

Thanks!!

-Alex

**Comment by 0dp** [comment]
Hi Alex,
Welcome back!
I am personally all up for improving on the gulp workflow, but think that first and foremost we should get gulp updated to v4. But as you might know, that project seems stalled (we are all busy people)

In the gulp4 branch you can see I've upgraded to PostCSS so making a set of tasks like you describe should be a walk in the park. We just need to move forward with upgrading to Gulp4 IMHO

**Comment by axlright** [comment]
Thanks Johan. Is there anything I can do to help?

-Alex

**Comment by 0dp** [comment]
The gulp4 branch needs to be updated so it is on par with  understrap master branch. 
Then the gulp4 tasks needs to be battle tested. I've worked on a few sites using that setup and it worked just fine for me. But others reported issues with browsersync refresh issues etc.

As soon an we can get everything stable then we can push to get it merged or at least get more testers on it.

Then I think we should look into your code optimization setup and get it running as a defacto part of understrap

**Comment by axlright** [comment]
Thanks @0dp I'll pull the gulp4 branch and work on testing it. I have a ton of UnderStrap projects I can use to test it thanks to all the team's awesome work.

Have a nice holiday for all those in the States and have a nice holiday **from** all those in the States for everyone else 😄 

-Alex

**Comment by 0dp** [comment]
My wife is American so thanks, I still can't move from last nights feast

**Comment by 0dp** [comment]
Hey @axlright  take a look at this PR https://github.com/understrap/understrap/pull/883

**Comment by 0dp** [comment]
If you take a look it uses postcss and we can expand on the features you'd like to see

**Comment by Thomas-A-Reinert** [comment]
This should be included within the "master" fork by now, right? So i´ll close this right now. In case I`m wrong - PLEASE REOPEN!

**Comment by axlright** [comment]
Thanks @Thomas-A-Reinert I haven't taken the time to incorporate the non-deprecated postcss version of uncss mostly because the deprecated version works okay and because the child theme isn't on gulp4 yet (that I know of). I'll test and upgrade as the time comes.
