### ISSUE TITLE
Remove template files for use with child theme

### ISSUE THREAD

**Issue by raisonon** [understrap/understrap#861]
Not sure if a feature request or general query.

My setup is to use Understrap as parent theme and modify my own Understrap child theme. Ideally I wont amend the core Understap theme.

I want to create two new template files (template-one.php and template-two.php) and I want the user creating a template to only choose either template-one or template-two.

However because the core Understrap theme is bundled with it's own template files these are appearing on the dropdown in the wp-admin edit page section.

For example we have the Blank Page Template and Empty Page Template.

My question is:

1) Is it possible to remove these from the dropdown
2) If not, perhaps we should not be bundling these default templates and/or should enable a way for them to be deactivated.

Feedback appreciated!

Thanks

**Comment by raisonon** [comment]
Thanks Thomas!

For anyone else, this is how I amended the above to remove all:

`public function child_theme_remove_page_template( $page_templates ) {
        unset( $page_templates['page-templates/blank.php'] ); 
        unset( $page_templates['page-templates/empty.php'] ); 
        unset( $page_templates['page-templates/fullwidthpage.php'] ); 
        unset( $page_templates['page-templates/left-sidebarpage.php'] ); 
        unset( $page_templates['page-templates/right-sidebarpage.php'] ); 
        unset( $page_templates['page-templates/both-sidebarspage.php'] ); 
        
        return $page_templates;
    }`

**Comment by Thomas-A-Reinert** [comment]
Glad to help.
Not able to test here, but the following _should_ also work if I`m not all wrong. Please confirm if that's the case.:

```
unset( $page_templates['page-templates/blank.php', 'page-templates/empty.php', 'page-templates/fullwidthpage.php', 'page-templates/left-sidebarpage.php', 'page-templates/right-sidebarpage.php', 'page-templates/both-sidebarspage.php'] ); 
```

**Comment by axlright** [comment]
I have the exact same setup as @raisonon and it works great!

**Comment by raisonon** [comment]
Hmm @Thomas-A-Reinert I get the following error with your cleaner code: Parse error: syntax error, unexpected ',', expecting ']' in 

Any ideas?

**Comment by raisonon** [comment]
@Thomas-A-Reinert this works:
```
        unset( $page_templates['page-templates/blank.php'],$page_templates['page-templates/empty.php'], $page_templates['page-templates/fullwidthpage.php'], $page_templates['page-templates/left-sidebarpage.php'], $page_templates['page-templates/right-sidebarpage.php'], $page_templates['page-templates/both-sidebarspage.php'] ); 
```

**Comment by raisonon** [comment]
On a related note, is there a similar way to unset the Format  on Posts? These are currently set to Standard, Aside, Image, Video, Quote, Link.

<aside>I'd rather Understrap was more bare bones, feels like there is space for a leaner version of Understrap which doesn't have all these extras bundled by default...</aside>

**Comment by raisonon** [comment]
Answered my own question:

```
        remove_theme_support( 'post-formats', array(
			'aside',
			'image',
			'video',
			'quote',
			'link',
        ) );
```

Keen to get feedback about others about making a leaner version of Understrap though. Cheers

**Comment by Thomas-A-Reinert** [comment]
Et voilá, again add it to functions.php:

```
add_action( 'after_setup_theme', 'remove_understrap_post_formats', 11 );
function remove_understrap_post_formats() {
    add_theme_support( 'post-formats', array( 'aside', 'image', 'video' , 'quote' , 'link' ) );
}
```

**Comment by raisonon** [comment]
Interesting @Thomas-A-Reinert I didn't hook into after_setup_theme, just ran on init -- any benefit on hooking in there?

Cheers

**Comment by Thomas-A-Reinert** [comment]
Well, that's how I learned it. "_It's safer and best practice_", they said without further explanation ;)
https://wordpress.stackexchange.com/questions/14797/difference-between-after-setup-theme-and-init-action-hooks should explain it better.

**Comment by Thomas-A-Reinert** [comment]
Guess that one can be closed due to the fact that it SHOULD work and no feedback for more than half a year..

**Comment by hcanning** [comment]
This solution doesn't appear to work anymore in functions.php for understrap-child unfortunately
```
function child_theme_remove_page_template( $page_templates ) {
        unset( $page_templates['page-templates/blank.php'] ); 
        unset( $page_templates['page-templates/empty.php'] ); 
        unset( $page_templates['page-templates/fullwidthpage.php'] ); 
        unset( $page_templates['page-templates/left-sidebarpage.php'] ); 
        unset( $page_templates['page-templates/right-sidebarpage.php'] ); 
        unset( $page_templates['page-templates/both-sidebarspage.php'] ); 
        
        return $page_templates;
    }
```
All the Understrap parent templates list out under Page Attributes in WP Admin when Child theme enabled.
Any ideas how to fix this?
WP 6.1.1
Understrap 1.22
Thanks
