### ISSUE TITLE
Suggestion: Make Understrap Es6 ready

### ISSUE THREAD

**Issue by ramojej** [understrap/understrap#862]
Can we make it like we have a bunch of  es6 modules and compile it one JS file that the theme will use? Thanks.

**Comment by 0dp** [comment]
Hi @ramojej ,

Take a look here #613

As I write further down you might also want to look into installing gulp-babel.

For updating the theme to have native ES6+ support I would say that we have a few tasks that needs to be solved before we start implementing it.

You are very welcome to post your findings here.

**Comment by hartwm** [comment]
`npm install @babel/core --save-dev`
`npm install gulp-babel --save`

In gulpfile.js require babel
`var babel = require('gulp-babel');`

Find gulp scripts task and add 

` .pipe(babel({
      presets: ['es2015']
    }))`

Here is example: 
```
// Run:
// gulp scripts.
// Uglifies and concat all JS files into one
gulp.task('scripts', function() {
  var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.bundle.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',

        // Adding currently empty javascript file to add on for your own themes´ customizations
        // Please add any customizations to this .js file only!
        paths.dev + '/js/custom-javascript.js'
    ];
  gulp.src(scripts)
    .pipe(babel({
      presets: ['es2015']
    }))
    .pipe(concat('theme.min.js'))
    .pipe(uglify())
    .pipe(gulp.dest(paths.js));

  gulp.src(scripts)
    .pipe(concat('theme.js'))
    .pipe(gulp.dest(paths.js));
});
```

**Comment by 0dp** [comment]
@ramojej take a look at this PR https://github.com/understrap/understrap/pull/883

**Comment by ramojej** [comment]
@0dp Thank you!

**Comment by Thomas-A-Reinert** [comment]
Should be resolved by now with the latest code avail.
