### ISSUE TITLE
dist and dist-product

### ISSUE THREAD

**Issue by Jaafarw** [understrap/understrap#864]
I am confused, here is what my dist folder is showing:

![image](https://user-images.githubusercontent.com/41353910/49451718-190fc900-f7e0-11e8-8176-d42bb005e22e.png)

And the dist-product folder:

![image](https://user-images.githubusercontent.com/41353910/49451853-596f4700-f7e0-11e8-8aa0-51008f6874b2.png)

Isn't it supposed to be the other way around?

#237

**Comment by Jaafarw** [comment]
I was self confused indeed :) It is how it is supposed to be.

**Comment by cedricbdev** [comment]
Go to gulpfile.js, find the dist task (~line 255), then remove the last line in the src array `'*'` (just after `'!codesniffer.ruleset.xml',`)
Then run `gulp dist` again. This should recreate the /dist directory without any dev stuff.
