### ISSUE TITLE
Help: Understrap with Magnific Popup

### ISSUE THREAD

**Issue by Daniellescorpio** [understrap/understrap#865]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:
  - **WordPress Version:** 4.9.x
  - **OS Version:** MacOS [10.12.6]
  - **Browser:** [ all | Chrome 70.0.3538.110  ]
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [v10.14.1] | NPM [6.4.1]
---

Hi
I am using Understrap for the first time to develop a new site. I've have managed to get all the compiling working. 

But I've come to a point where I need to include Magnific Popup and Im stuck.

I ran npm install magnific-popup so it is there in the node-modules folder. But Im at a loss as to what I am supposed to do now in order to use it. 

I tried including it in gulpfile.js (I've included the lines above and below so you can see where) 

```
// Copy all Font Awesome SCSS files
    gulp.src( paths.node + 'font-awesome/scss/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/fontawesome' ) );
	
// Copy Magnific-popup JS files
    gulp.src( Paths.node + 'magnific-popup/dist/*.js')
        .pipe(gulp.dest( Paths.dev + '/js'));

// _s SCSS files
    gulp.src( paths.node + 'undescores-for-npm/sass/media/*.scss' )
        .pipe( gulp.dest( paths.dev + '/sass/underscores' ) );
```

I originally tried it with basePaths.node and basePaths.dev as per [https://github.com/understrap/understrap/issues/225 ](url)

I also ran gulp scripts after both tries and Im getting nowhere.

I have the following on the page Im using it, and obviously have the class against my link

```
<script>
 jQuery(document).ready(function() {
jQuery('.popup-youtube').magnificPopup({
disableOn: 700,
type: 'iframe',
mainClass: 'mfp-fade',
removalDelay: 160,
preloader: false,
fixedContentPos: false
});
});
</script>
```

Any help would be appreciated. I'm working in the main theme and not using a child theme as I couldn't make that work :(

**Comment by 0dp** [comment]
What you did is correct but use lowercase p.
This task only copies the file to the src/js folder.
You'll still need to include the file in the `scripts` gulp task.

**Comment by axlright** [comment]
@Daniellescorpio following up on what @0dp said - with the lower case 'p' in 

```
// Copy Magnific-popup JS files
    gulp.src( paths.node + 'magnific-popup/dist/*.js')
        .pipe(gulp.dest( Paths.dev + '/js'));
```

You can then run `gulp copy-assets` and you'll know it's worked when you see the correct magnific script added to your `src/js/` directory

You'll then need to add the magnific script to the `gulp.task( 'scripts', function() ` at line 130 of the `gulpfile.js` by including something like

```
        // Start - Magnific Script
        paths.dev + '/js/name-of-your-magnific-popup-script.js',
        // End - Magnific Script
```

Then when you run `gulp scripts` you should have your magnific script included in the main `/js/theme.js` and `/js/theme.min.js`

You'll know it worked by inspecting `/js/theme.js` and looking for the magnific script

**Comment by Daniellescorpio** [comment]
Thanks for the help, I will try it as you've explained when I get 5 minutes, that makes sense now.

I just used standard enqueue in the end.

**Comment by holger1411** [comment]
Seems to be answered. Thx @Daniellescorpio for bringing this up and @0dp and @axlright for helping out.

Feel free to reopen if the issue still exists
