### ISSUE TITLE
 Incorrect order of @import

### ISSUE THREAD

**Issue by jamiedarcher** [understrap/understrap#871]
I'm hacking at the Underscores theme directly (not using the child theme) when trying to change a simple thing like the menu background colour nothing worked. 

I didn't understand why until I saw that you loaded Bootstrap AFTER theme_variables this means that Bootstrap overrides your own theme variables:

```
@import "theme/theme_variables";  // <--------- Add your variables into this file. Also add variables to overwrite Bootstrap or UnderStrap variables here

@import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Change from /bootstrap3 to /bootstrap4 Watch out! just for testing in the moment!

```
I moved the first line below and things started to work.

**Comment by alexbogias** [comment]
I think that you just have to remove !default; after you variable change

**Comment by jamiedarcher** [comment]
Thanks!

**Comment by jamiedarcher** [comment]
@alexbogias reboot.scss is still overriding my custom style for things like .entry-meta ?!

**Comment by alexbogias** [comment]
@jamiedarcher I don't think so... Give me more details. Screenshot from inspector?

**Comment by Thomas-A-Reinert** [comment]
Issue seems to be resolved / abandoned / or whatsoever. Closing it for house-keeping. Feel free to re-open if the problem persists.
