### ISSUE TITLE
Having issues overwirting bootstrap style

### ISSUE THREAD

**Issue by jamiedarcher** [understrap/understrap#872]
I cannot overwrite certain bootstrap variables or rule despite using _theme-variables.scss and _theme.scss.

reboot.scss seems to cancel out my style declarations for simple thing like post style where I want to change the .entry-meta font style.

This is super frustrating. FYI I'm not using a child theme I'm using the understrap theme directly

At first I thought it was because of the previous issue of importing bootstrap after theme-variables but this is now affecting my _theme file. I don't want to modify bootstrap but at this rate if I cannot overwrite those styles I'll have to. 

Is anyone having this problem.? And yes my sass is compiling correctly.

**Comment by holger1411** [comment]
The most common reason for this is if you copy&past variables from the Bootstrap variables.css and leave the "!default" flag in it.
By default all Bootstrap variables use this flag, so it dosent matter where you overwrite it (before or after), but if your own variables are also flagged by "!default" the loading sequence will matter again...

**Comment by jamiedarcher** [comment]
Yeah that doesn't explain the entry meta - it does not use the default flag and I'm not using it either

**Comment by Thomas-A-Reinert** [comment]
Issue seems to be resolved / abandoned / or whatsoever. Closing it for house-keeping. Feel free to re-open if the problem persists.
