### ISSUE TITLE
Font files corrupt on dist

### ISSUE THREAD

**Issue by reb197** [understrap/understrap#873]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.0
  - **OS Version:** Linux [Ubuntu
  - **Browser:** [ all ]
  - **Language:** [ all ]
  - **Node.js & NPM Versions:** Node.js [V v10.12.0] | NPM [V 6.4.1]

---

# Issue Overview for Bugreports

## Steps to reproduce?
* Add a font file (say myfont.woff2) to the fonts directory
* `gulp dist`
* `diff fonts/myfont.woff2 dist/fonts/myfont.woff2`

Notice that the font files differ. The font file from dist/fonts will not load in a browser, giving errors like:

(index):1 OTS parsing error: incorrect file size in WOFF header
(index):1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size

It only seems to break woff and woff2 file formats.

## Fix / Workaround

In gulpfile.js where the 'dist' command is defined set the buffer flag of the 'src' command to true (or remove it as true is the default). i.e.:

`return gulp.src( ['**/*', '!' + paths.bower, '!' + paths.bower + '/**', '!' + paths.node, '!' + paths.node + '/**', '!' + paths.dev, '!' + paths.dev + '/**', '!' + paths.dist, '!' + paths.dist + '/**', '!' + paths.distprod, '!' + paths.distprod + '/**', '!' + paths.sass, '!' + paths.sass + '/**', '!readme.txt', '!readme.md', '!package.json', '!package-lock.json', '!gulpfile.js', '!gulpconfig.json', '!CHANGELOG.md', '!.travis.yml', '!jshintignore',  '!codesniffer.ruleset.xml',  '*'], { 'buffer': true } )`

This fixed it for me. I don't understand why though - possibly to do with the replace commands on the following lines?

**Comment by holger1411** [comment]
I fix it in the commit above. Thx for reporting!
