### ISSUE TITLE
Does Understrap have the ability to do equal height columns out of the box?

### ISSUE THREAD

**Issue by jenclickspring** [understrap/understrap#875]
Bootstrap has a .row-eq-height class that allows columns to be made equal heights. Somehow it doesn't seem to be working with Understrap. So is it included in the code already? If so then I must be doing something wrong...thanks.

**Comment by axlright** [comment]
Bootstrap 4 does not have a built in style for .row-eq-height - you can go to https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css and do a search for the class in the compiled current version of Bootstrap.

Setting columns to an equal height can be achieved through flexbox. There's a lot of flexbox guides online about setting objects to the same height. Depending on your implementation, different approaches can apply.

Closing this as it's more a question about Bootstrap than UnderStrap, though feel free to comment back if you have further questions about UnderStrap and we can answer.
