### ISSUE TITLE
Theme Update Replaced styles and templates

### ISSUE THREAD

**Issue by AgendaNYC** [understrap/understrap#890]
Please delete anything that does not apply for you!

## Issue is about..
  - [ X] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.0.2
  - **OS Version:**MacOS Mojave
  - **Browser:** [ all ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]

I updated the theme to 0.8.9 and my site went completely back to default setup. 

my custom styles within themes>understrap>sass>theme were gone. all page template files in 'page-templates' were gone. 

I haven't seen any other similar issues so I'm hoping this is user error on my part. 

Thank you!

**Comment by 0dp** [comment]
Ohh Lord! Do you have a backup?

All your modification will be overwritten when updating the theme. That's why it's best practice to use the children theme. Or create one for that matter

**Comment by AgendaNYC** [comment]
@0dp I did have a backup so it wasn't a disaster thankfully. Just strange that the themes>understrap>sass>theme which has a comment saying 

"// This is an empty scss file for your custom styles - Please add your super duper awesome mega design styles here"

this file was overridden which seemed strange.

**Comment by holger1411** [comment]
Yes, its very important to use a child theme to separate your changes from the parent theme.
An empty child theme for UnderStrap is available here:
https://github.com/understrap/understrap-child

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
