### ISSUE TITLE
Popper.js not installed. 

### ISSUE THREAD

**Issue by dluxcru** [understrap/understrap#892]
Please delete anything that does not apply for you!

## Issue is about..
  - [X] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [X] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.0.2
  - **OS Version:**| Linux [Ubuntu/ Version 18] |
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V 8.10.0] | NPM [V 3.5.2]

---

# Issue Overview for Bugreports
So I've just started using UnderStrap. I think I'm experiencing this. In addition to experiencing what I suspect is #624  (Correct me if I am wrong - Gulp upgrades are only an issue if I don't want to see error messages, I don't need to worry about the jQuery because it's already in Wordpress.) My concern is Popper seems to be missing as well. (See the pastebin log.)
## Steps to reproduce?
Run `npm install`? 
## *Who* is the bug affecting?
Me. 
## *What* is affected by this bug?
Apparently Popper is missing. 
## *When* does this occur?
When you run `npm install`. 
## Are there any related Issues and/or PRs?
#624 
## Screenshots / Video
https://pastebin.com/Apxn07sX

**Comment by 0dp** [comment]
Popper is a dependency of bootstrap, but we include bootstrap.bundle.js which has popper included. 
So you should be able to ignore the warning

**Comment by dluxcru** [comment]
Thank you. I'll let you know if there is some kind  of actual problem. Would help if you could suppress the warning or add output  to clarify that inclusion.

**Comment by 0dp** [comment]
`npm install popper.js` should suppress the warning

**Comment by holger1411** [comment]
UnderStrap did not use its own jQuery version (because WP already comes with it) nor an extra popper.js dependency (because its part of bootstrap.bundle.min.js).
So (as @0dp says) you can ignore the warning messages.
We can´t change the messages because it´s part of Bootstrap itself. And just installing two unneeded packages to suppress warnings isn´t an option
