### ISSUE TITLE
How to create post format video?

### ISSUE THREAD

**Issue by tomislavbrtan** [understrap/understrap#895]
## Issue is about..
  - [ ] I need help

How do I modify understrap so a video post gets shown in loop-templates/content-video.php instead of the content-single.php

**Comment by tomislavbrtan** [comment]
The question is regarding post formats.
As of now understrap doesn't support the video post format. I was wondering if there is a easy way to fix this? I have created a new file content-video.php in the /loop-templates folder and I have tried to modify the content.php and single.php so that the correct loop-template file is used depending if I have a simple post or video. 

What I'm trying to accomplish is basically, I want the content-video.php to load my video posts instead of the regular content-single.php

content.php
<?php if ( 'post' == get_post_type() ) : ?>

single.php
<?php while ( have_posts() ) : the_post(); ?>
<?php get_template_part( 'loop-templates/content', 'single' ); ?>

/loop-templates
content.php
content-video.php
content-single.php

**Comment by axlright** [comment]
It's my understanding that themes don't have to support all `post-format`s. It's possible to include a video in a regular blog post, especially with WordPress 5's improvement of video embedding. That I know of, UnderStrap does not have customized support for other `post-format`s.

If you do want to add customized theme support for the Video Post Format, there's documentation here: https://codex.wordpress.org/Post_Formats

**Comment by holger1411** [comment]
Hi!
Basically a post type "video" is not a WordPress default.
If you need such a post type (and a specific template for it) you have to register a new "video" post type first:
https://codex.wordpress.org/Function_Reference/register_post_type

Than you can create a single-video.php template for it where you can add a custom loop or load a content-video.php loop externally

**Comment by pattonwebz** [comment]
@tomislavbrtan I think you might be looking for how to enable post formats in the theme.

Adding this to the theme somewhere in your setup function or similar place would do that for you:
`add_theme_support( 'post-formats', array( 'video' ) );`

There is a bit more detail here about it: https://codex.wordpress.org/Post_Formats#Adding_Theme_Support

**Comment by tomislavbrtan** [comment]
Hello. Thanks for answering everybody. I did solve it by creating a new loop template.
The weird thing is. I tried pattonwebz suggestion at first because I had the same issue at a different template and it worked there but it did not work on understrap. (the other template was based on underscores)

I used the following code
<?php get_template_part( 'loop-templates/content-videotemplate', get_post_format() ); ?>

**Comment by pattonwebz** [comment]
That is interesting. I am thinking that maybe the issue here is rooted in how the template partials are called in the theme - rather than the actual ability to enable the formats which I was initially thinking. It's a little strange so I will try look into this more when I have the time :)

**Comment by BohemiansThemes** [comment]
From what I see the understrap theme has support for custom post (standard, aside, image, video, quote and link). 
The problem is from the loop and the exerpt. Is there a way to add a filter for custom post to display the_content instead of the_excerpt?
