### ISSUE TITLE
Comment title not translated

### ISSUE THREAD

**Issue by gaelgerard** [understrap/understrap#897]
a Bug Report
WordPress Version: 5
understrap 0.8.9

Hello,

The comments title is not translated and the string in comments.php is not recognized by PoEdit in my child theme:

`					
esc_html_x( 'One thought on &ldquo;%s&rdquo;', 'comments title', 'understrap' ),
`

You can see result on this screenshot:

![image](https://user-images.githubusercontent.com/3606876/51604290-9916fd00-1f0c-11e9-97f2-ac2e5acc1854.png)

"One thought on "Accueil"" should be translated with "Un commentaire sur "Accueil"".

Can you plz help me?

Best regards
Gaël

**Comment by Thomas-A-Reinert** [comment]
You´re somehow right. I had the same problem today, but *MAGIC* somehow it worked some time after. I cannot explain why or how. Does your problem still persist?

**Comment by Thomas-A-Reinert** [comment]
No feedback for more than half a year. So going to close that issue for housekeeping. Feel free to re-open if needed.
