### ISSUE TITLE
Changing Shop Html

### ISSUE THREAD

**Issue by GabrielBes** [understrap/understrap#904]
Hello, everyone, 
I would like to place the product name over the picture in the shop page. For this I have to change the HTML file. Now the question arises which HTML file I have to change, because I can't find it.

Many thanks to all the help I can get.

**Comment by Thomas-A-Reinert** [comment]
Install https://de.wordpress.org/plugins/show-current-template/ (for example, there are other solutions) and see which templates are being loaded.
