### ISSUE TITLE
javascript not loading anymore, without errors

### ISSUE THREAD

**Issue by MikeDrenth** [understrap/understrap#905]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.9
  - **Browser:** [ all  ]
  - **Node.js & NPM Versions:** Node.js [v8.11.3] | NPM [V6.7.0]

---

Hi guys,

I've been working with understrap for a while, now after some time i started moving my projects to another folder and start using valet instead of XAMPP, now after moving my project to another dir on my mac, javascript is not loading/working anymore. It's not giving me errors anywhere, but all my jqeury functions are not working anymore. 

<img width="699" alt="schermafbeelding 2019-01-31 om 19 02 12" src="https://user-images.githubusercontent.com/45667352/52074719-cd349280-258a-11e9-8534-88a4c18a9fd4.png">

You can see that it seems like theme.min.js is loading. 

Can someone help me with this or give me some tips on where to look?

**Comment by 0dp** [comment]
Did you check your gulpfile and paths in gulpconfig?

**Comment by MikeDrenth** [comment]
> Did you check your gulpfile and paths in gulpconfig?

Yes, the i'm using the paths.dev for the js files, and they didn't change.

`  ],
  "paths" : {
    "js": "./js",
    "css": "./css",
    "img": "./img",
		"imgsrc": "./src/img",
    "sass": "./sass",
    "node": "./node_modules/",
    "bower": "./bower_components/",
    "dev": "./src",
    "dist": "./dist",
    "distprod": "./dist-product",
    "vendor": ""
  }
}
`

**Comment by 0dp** [comment]
Yeah that's correct.
What if add a console.log to your custom-javascript, let it compile and compare the theme.min.js that's served in the browser against the one generated in the is folder?

So you see any discrepancies?

**Comment by MikeDrenth** [comment]
It's solved. Wordpress wasn't loading my custom javascript because i't apperently didn't load correctly in the footer.php

from: 

`<? wp_footer(); ?>`

to: 

`<?php wp_footer(); ?> `

solved the issue, weird that it worked before tho. Thanks for your help.

**Comment by 0dp** [comment]
I believe it's best practice not to use the shorthand Syntax. If you want it back you need to enable it in your php.ini file. I believe they also write a disclaimer about it there.

**Comment by IanDelMar** [comment]
> Never use shorthand PHP start tags. Always use full PHP tags.

https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#no-shorthand-php-tags
