### ISSUE TITLE
sass file loading

### ISSUE THREAD

**Issue by xavierartot** [understrap/understrap#907]
I'm following the documentation, in /sass/theme/_theme.scss I added:

```
$mycolor: #67A6A6;
.entry-header {
  background-color: #f00;
}
.entry .entry-title, .entry .entry-content {
    color: blue !important;
    margin: 4em;
    padding: 4rem;
}
```
in gulpconfig.json:
```
  "browserSyncOptions" : {
    "proxy": "http://localhost:8888/wordpress",
    "notify": true
  },
```

In the Terminal I started gulp and a browser and it's open with the right page on the port 3000. http://localhost:3000/wordpress:
gulp watch-bs

I tried gulp and everything seems correct?

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.03
  - **OS Version:** [MacOS [Mojave] 
  - **Browser:** [ Chrome ]
  - **Language:** [ S/CSS]

Gulp version
```
➜  understrap-test git:(master) ✗ gulp --version
[12:33:50] CLI version 3.9.1
[12:33:50] Local version 3.9.1
```
node:
```
➜  understrap-test git:(master) ✗ node --version
v10.13.0
```
NPM
```
➜  understrap-test git:(master) ✗ npm --version
6.4.1
```

**Comment by axlright** [comment]
Can you let us know what is or isn't happening based on your expectations? Are you saying that your Sass isn't compiling? What terminal details do you get when running `gulp watch-bs`?
