### ISSUE TITLE
navwalker - how to add nav-link span

### ISSUE THREAD

**Issue by 0dp** [understrap/understrap#911]
## Issue is about..
  - [x ] I need help

---

Hi Guys,

So I'm having a bit of an issue adding a `<span>` inside `nav-link`

What I should end up with in my navigation is nav-links like this
```
<a title="title" href="#" class="nav-link"><span>title</span</a>
```

@pattonwebz my man!

**Comment by pattonwebz** [comment]
I am unsure if I am able to have issues assigned to me here but if you can assign to this one then go ahead and do that so I don't loose track of it.

I'll try to look into this in the next 1-2 days. Should be fairly easy to adjust the walker to make it happen :)

**Comment by 0dp** [comment]
I don't have the power to do so unfortunately. I'll just keep bantering you about it 😋

**Comment by 0dp** [comment]
Apparently I'm blind and stupid.

I've added a span in class-wp-bootstrap-navwalker.php
line 233 and 284. It seems to work just fine. Let me know if there's a better way or if I'm missing someting
