### ISSUE TITLE
_contact-form7.scss

### ISSUE THREAD

**Issue by craigwilcox** [understrap/understrap#912]
Hi,

I'm wondering if there's a better way to go about adding Contact Form 7 integration through the _contact-form7.scss file. 

Each time the @extend rule is used, it adds 5kb to the CSS file. Overall, that's 97kb added from this file alone. 

I'm not sure exactly how it works, but perhaps there's a way to trim it down using the placeholder selector? I was looking through this article as a reference for the how it could be changed: https://webinista.com/updates/dont-use-extend-sass/

Thanks to everyone for your work on this project!

**Comment by axlright** [comment]
Happy to be added to this issue. May be over my pay grade. I don't use contact form 7 and also am not smart enough to use `@extend` Sass. I'd have to learn a bunch to help out.

From the looks of the comments in the Sass file (with some misspellings and other personalized notations), this seems to have been a Sass file that someone created and updated to help her / his development but does not look to be something that's been universally tested.

Are others using and customizing the `_contact-form7.scss` file?

**Comment by craigwilcox** [comment]
Thanks  to everyone having a look at this now. I have a little update on what I've been trying with at least some success.

First, for Contact Form 7, I've found it more convenient to simply add form-control directly to the forms, so @extend .form-control is not necessary. I can, however, see, this would create problems for people who don't want to have to remember that for each form.

Second, I've create a `_placeholders.scss` file in my child-theme and referenced it for inclusion from `child-theme.scss`.

In this file, I have put a few necessary selectors for buttons and forms using the placeholder/silent selector SASS classes referenced in my first request.

I'm sure I'm not doing it correctly all the way through, but it's suiting my purposes, and a more seasoned SASS developer may be able to help clean it up.

Here is an example from my file to extend form-control that only adds around 1kb to the file instead of 95kb:

```
%form-control {
  display: block;
  width: 100%;
  height: $input-height;
  padding: $input-padding-y $input-padding-x;
  font-family: $input-font-family;
  @include font-size($input-font-size);
  font-weight: $input-font-weight;
  line-height: $input-line-height;
  color: $input-color;
  background-color: $input-bg;
  background-clip: padding-box;
  border: $input-border-width solid $input-border-color;

  // Note: This has no effect on <select>s in some browsers, due to the limited stylability of `<select>`s in CSS.
  @include border-radius($input-border-radius, 0);

  @include box-shadow($input-box-shadow);
  @include transition($input-transition);

  // Unstyle the caret on `<select>`s in IE10+.
  &::-ms-expand {
    background-color: transparent;
    border: 0;
  }

  // Customize the `:focus` state to imitate native WebKit styles.
  @include form-control-focus();

  // Placeholder
  &::placeholder {
    color: $input-placeholder-color;
    // Override Firefox's unusual default opacity; see https://github.com/twbs/bootstrap/pull/11526.
    opacity: 1;
  }

  // Disabled and read-only inputs
  //
  // HTML5 says that controls under a fieldset > legend:first-child won't be
  // disabled if the fieldset is disabled. Due to implementation difficulty, we
  // don't honor that edge case; we style them as disabled anyway.
  &:disabled,
  &[readonly] {
    background-color: $input-disabled-bg;
    // iOS fix for unreadable disabled content; see https://github.com/twbs/bootstrap/issues/11655.
    opacity: 1;
  }
}

.woocommerce-checkout #payment div.payment_box input.js-sv-wc-payment-gateway-credit-card-form-input[type="tel"], .woocommerce-checkout #payment div.payment_box input.js-sv-wc-payment-gateway-credit-card-form-input[type="text"] {
  @extend %form-control;
  background-size: 45px 28px;
}

form {
	input[type="text"],
	input[type="email"],
	input[type="password"],
	input[type="number"],
  input[type="tel"],
  textarea {
		@extend %form-control;
	}
}

```

I've done the same for buttons. Overall, I'm keeping the minified child-theme CSS file under 300kb this way.

This became absolutely necessary for my clients because they are using Woocommerce with Authorize.net and ran into the issue with that plugin referenced here: #https://github.com/understrap/understrap/issues/950

If anyone wants more info about this, I'd be happy to provide it. However, I'm at about my limit of understanding this issue! 

Thanks,
Craig

**Comment by stef-k** [comment]
`_contact-form7.scss` created as a means to use CF7 without the need to change the markup or the CSS for the contact form, a quick all around solution. 

However this does not make sense for someone who wants to develop his own solution on top of  CF7. I don't have any usage numbers on this but leaving it out it could break things for many(?) users.

One possible solution is to enable/disable the inclusion of this file using a variable in the build process.

**Comment by Thomas-A-Reinert** [comment]
Yeap. can confirm what @craigwilcox said. It really, REALLY bloats the whole CSS.
I tend to comment it out and use my own styles. My recommendation would be to disable it by default and give a hint in the documention for the next release (*sic*). @holger1411

**Comment by IanDelMar** [comment]
@craigwilcox While using placeholders is the best option to avoid CSS bloat, it adds the need for maintenance on BS updates as `.form-control` may change (I have no idea how "stable" BS classes actually are). However, in your example, the approach misses to include inline forms for which `@extend` accounts.

I don't think it's that big deal to include class:form-control directly. Though it might be an option to change the default template to include BS examples (see below). But it's questionable whether it is a theme's responsibility to take care of the plugin user's laziness to include the proper markup or incapability to remember which things to add.

```php
if ( ! function_exists( 'understrap_wpcf7_default_template' ) ) {

	function understrap_wpcf7_default_template( $template, $prop ) {
		if ( 'form' == $prop ) {
			ob_start();
			?>
			<div class="form-group">
				<label for="exampleInputName1">Your Name (required)</label>
				[text* your-name id:exampleInputText1 class:form-control placeholder "Enter name"]
			</div>

			<div class="form-group">
				<label for="exampleInputEmail1">Email address</label>
				[email your-email id:exampleInputEmail1 class:form-control placeholder "Enter email"]
				<small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
			</div>

			<div class="form-group">
				<label for="exampleInputTextarea1">Your Message</label>
				[textarea your-message id:exampleInputTextarea1 class:form-control placeholder "Message"] 
			</div>

			<div>
				[select menu-999 id:exampleInputSelect1 class:custom-select include_blank "Option 1" "Option 2" "Option 3"]
			</div>

			<div class="form-group">
				<label for="exampleFormControlFile1">Example file input</label>
				[file file-999 id:exampleFormControlFile1 class:form-control-file]
			</div>

			<div>
				[submit class:btn class:btn-primary "Send"]
			</div>
			<?php
			$template = trim( preg_replace( '/\t+/', '', ob_get_clean() ) );
		}
		
		return $template; 
	}
}
add_filter( 'wpcf7_default_template', 'understrap_wpcf7_default_template', 10, 2 );
```
I don't know how to do this for checkboxes and radio buttons. 

Another approach could be to provide CF7 modules with BS4 HTML markup. As in the case of placeholders, this would need someone to a) write the modules and b) maintain the modules. My comment about the theme's responsibility from above is valid for modules as well. CF7-BS4 modules seem to be more of a plugin thing than a theme thing.

I strongly support @Thomas-A-Reinert suggestion to disable CF7 support by default! I would even suggest making WooCommerce an opt-in rather than opt-out, but that's offtopic.

**Comment by IanDelMar** [comment]
If someone wants to elaborate on the module approach, here's an example for the submit button:

```php
add_action( 'wpcf7_init', 'understrap_wpcf7_add_form_tag_submit', 10, 0 );

function understrap_wpcf7_add_form_tag_submit() {
	wpcf7_add_form_tag( 'understrap-submit', 'understrap_wpcf7_submit_form_tag_handler' );
}

function understrap_wpcf7_submit_form_tag_handler( $tag ) {
	$class = wpcf7_form_controls_class( $tag->type );

	$atts = array();

	$atts_class = $tag->get_class_option( $class );
	$atts['class'] = $tag->get_class_option( $class ) . ' ' . implode( ' ', apply_filters( 'understrap_wpcf7_submit_form_tag_classes', $classes ) );
	$atts['id'] = $tag->get_id_option();
	$atts['tabindex'] = $tag->get_option( 'tabindex', 'signed_int', true );

	$value = isset( $tag->values[0] ) ? $tag->values[0] : '';

	if ( empty( $value ) ) {
		$value = __( 'Send', 'understrap' );
	}

	$atts['type'] = 'submit';

	$atts = wpcf7_format_atts( $atts );

	$html = sprintf( '<button %1$s />' . trim( esc_html( $value ) ) . '</button>', $atts );
	$html .= '<span class="ajax-loader"></span>';

	return $html;
}

add_filter( 'understrap_wpcf7_submit_form_tag_classes', 'understrap_wpcf7_submit_form_tag_default_classes' );

function understrap_wpcf7_submit_form_tag_default_classes( $classes ) {
	$classes = array( 'btn' );
	return $classes;
}

add_action( 'wpcf7_admin_init', 'understrap_wpcf7_add_tag_generator_submit', 55, 0 );

function understrap_wpcf7_add_tag_generator_submit() {
	$tag_generator = WPCF7_TagGenerator::get_instance();
	$tag_generator->add( 'understrap-submit', __( 'understrap-submit', 'understrap' ),
		'understrap_wpcf7_tag_generator_submit', array( 'nameless' => 1 ) );
}

function understrap_wpcf7_tag_generator_submit( $contact_form, $args = '' ) {
	$args = wp_parse_args( $args, array() );

	$description = __( "Generate a form-tag for a BS$ submit button.", 'understrap' );

	?>
	<div class="control-box">
	<fieldset>
	<legend><?php echo esc_html( $description ); ?></legend>

	<table class="form-table">
	<tbody>
		<tr>
		<th scope="row"><label for="<?php echo esc_attr( $args['content'] . '-values' ); ?>"><?php echo esc_html( __( 'Label', 'understrap' ) ); ?></label></th>
		<td><input type="text" name="values" class="oneline" id="<?php echo esc_attr( $args['content'] . '-values' ); ?>" /></td>
		</tr>

		<tr>
		<th scope="row"><label for="<?php echo esc_attr( $args['content'] . '-id' ); ?>"><?php echo esc_html( __( 'Id attribute', 'understrap' ) ); ?></label></th>
		<td><input type="text" name="id" class="idvalue oneline option" id="<?php echo esc_attr( $args['content'] . '-id' ); ?>" /></td>
		</tr>

		<tr>
		<th scope="row"><label for="<?php echo esc_attr( $args['content'] . '-class' ); ?>"><?php echo esc_html( __( 'Class attribute', 'understrap' ) ); ?></label></th>
		<td><input type="text" name="class" class="classvalue oneline option" id="<?php echo esc_attr( $args['content'] . '-class' ); ?>" /></td>
		</tr>

	</tbody>
	</table>
	</fieldset>
	</div>

	<div class="insert-box">
		<input type="text" name="understrap-submit" class="tag code" readonly="readonly" onfocus="this.select()" />

		<div class="submitbox">
		<input type="button" class="button button-primary insert-tag" value="<?php echo esc_attr( __( 'Insert Tag', 'understrap' ) ); ?>" />
		</div>
	</div>
	<?php
}
```
This allows for 1. the use of a button-variant mixin on `.wpcf7-understrap_submit` (bloating CSS again), 2. the use of the `understrap_wpcf7_submit_form_tag_classes` filter to add e.g. `.btn-primary`, and 3. the use of the CF7 class `class:btn-primary`.

But one would have to re-write all of the CF7 modules and still remember that there are some things to add.

**Comment by Thomas-A-Reinert** [comment]
Ehm...has this thing been fixed in ANY KIND at all over the past 6 month "by accident"?

In  my eyes CF should be disabled by default, because it REALLY does at a lot of bloat for any user that wants to go without. This is why I´d go with a node.js configurator for what you want/do not want to have in your installation at all - in a different fork - for this. 

There ARE f*CKING  smarter solutions for that. Anyway, I´ll close this issue as it´s more than 10 months stale.
If the problem remains, please feel free to re-open that issue.
