### ISSUE TITLE
jquery custom

### ISSUE THREAD

**Issue by d-dryhouse** [understrap/understrap#913]
Hi, I want to add custom jquery.

(functions($){
  $(".woocommerce-Tabs-panel h2").click(function(){
    $(this).parent().toggleClass("show-content");
  });
})(jQuery);

I followed this # 548  and it does not load me

// _s JS files into /src/js
    gulp.src( paths.node + 'undescores-for-npm/js/skip-link-focus-fix.js', )
        .pipe( gulp.dest( paths.dev + '/js/custom.js' ) );

**Comment by 0dp** [comment]
hi there,

It is not exactly what it tells you to do.

> To avoid confusion:

    1. Add file 'custom.js' to `/src/js/`

    2. Add this after [line 186](https://github.com/holger1411/understrap-child/blob/ec61c7ff861a0d75bb0b73984abb3a77635e34b6/gulpfile.js#L186) of `gulp.js`
       `paths.dev + '/js/custom.js'`

    3. Make sure to add a comma after the previous line:
       `paths.dev + '/js/skip-link-focus-fix.js',`


Complete code will look like this:

```
    var scripts = [

        // Start - All BS4 stuff
        paths.dev + '/js/bootstrap4/bootstrap.js',

        // End - All BS4 stuff

        paths.dev + '/js/skip-link-focus-fix.js',
        paths.dev + '/js/custom.js'
    ];
```

Of cause I don't know if you copied your snippet in incorrect.

Below:
` 'paths.dev + '/js/skip-link-focus-fix.js'`
insert:
`paths.dev + '/js/custom.js'`

remember to add a comma after ` 'paths.dev + '/js/skip-link-focus-fix.js'`

the code should look like this:

```
        paths.dev + '/js/skip-link-focus-fix.js',
        paths.dev + '/js/custom.js'
```
