### ISSUE TITLE
Offcanvas menu

### ISSUE THREAD

**Issue by zafon18** [understrap/understrap#914]
Hi, I would like to congratulate you on the good work with the Understrap theme!
I have a question if you can convert Understrap_WP_Bootstrap_Navwalker to offCanvas menu or modal menu?
Thanks for all the suggestions

**Comment by axlright** [comment]
Can you explain a bit more about what you're looking to do, including code you've tried and information on what has / hasn't worked? I've added multiple menus (in one case six different menus) on a WordPress site using UnderStrap. Different menus in different places. You'd do this the same way you'd do it in any WordPress site.

If you can be more specific about what you've tried and the results you've gotten, that would help a lot.

**Comment by zafon18** [comment]
Hi i try this, but i think is bad idea ;( 
Modal menu

`				<button class="navbar-toggler" type="button" data-toggle="modal" data-target="#modal_Menu" aria-controls="navbarNavDropdown" aria-expanded="false" aria label="<?php esc_attr_e( 'Toggle navigation', 'understrap' ); ?>">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="modal fade" id="modal_Menu" tabindex="-1" role="dialog" aria-labelledby="<?php esc_attr_e( 'Toggle navigation', 'understrap' ); ?>" aria-hidden="true">
				  <div class="modal-dialog modal-dialog-centered" role="document">
					<div class="modal-content">
					  <div class="modal-header">
						 <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        				  <span aria-hidden="true">&times;</span>
        			     </button>
					   </div>
				
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'modal-body',
						'container_id'    => 'modal_Menu',
						'menu_class'      => 'navbar-nav ml-auto text-dark',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'depth'           => 2,
						'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
					)
				); ?>
						</div>
					  </div>
					</div>`
Better add menu in the widget?

**Comment by zafon18** [comment]
Hello i added modal menu, this work good.
`
				<button class="navbar-toggler" type="button" data-toggle="modal" data-target="#menuModal" aria-controls="#menuModal" aria-expanded="false" aria-label="<?php esc_attr_e( 'Toggle navigation', 'understrap' ); ?>">
				<i class="fa fa-bars menu_burger" aria-hidden="true"></i>
				</button>
					<div class="modal fade" id="menuModal" tabindex="-1" role="dialog">
						<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
							<div class="modal-content">
								<button type="button" class="close" data-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>

								<?php if ( is_active_sidebar( 'menusidebar' ) ) : ?>
								<ul id="sidebar">
									<?php dynamic_sidebar( 'menusidebar' ); ?>
								</ul>
								<?php endif; ?>
								
					
				<?php wp_nav_menu(
					array(
						'theme_location'  => 'primary',
						'container_class' => 'modal-body',
						'container_id'    => '',
						'menu_class'      => 'navbar-nav ml-auto',
						'fallback_cb'     => '',
						'menu_id'         => 'main-menu',
						'depth'           => 2,
						'walker'          => new Understrap_WP_Bootstrap_Navwalker(),
					)
				); ?>
							</div>
						</div>
					</div>
`
