### ISSUE TITLE
single-{custom_post_type}.php not working

### ISSUE THREAD

**Issue by LogiaKing** [understrap/understrap#917]
I am trying to create a single custom post type template, I have registered the post type, and added portfolio_item_post.php and single-portfolio_item_post.php to loop templates. I have also flushed the permalinks. After clearing my cache and flushing, the custom post type keeps displaying the layout of content-single.php, I'm at a loss

Here is the functions.php code to register the post type;

//Register Custom Post Type
function portfolio_item_post() {
$labels = array(
    'name'                => _x( 'Portfolio Posts', 'Post Type General Name', 'text_domain' ),
    'singular_name'       => _x( 'Portfolio Post', 'Post Type Singular Name', 'text_domain' ),
    'menu_name'           => __( 'Portfolio Post', 'text_domain' ),
    'parent_item_colon'   => __( 'Portfolio Post:', 'text_domain' ),
    'all_items'           => __( 'All Portfolio Posts', 'text_domain' ),
    'view_item'           => __( 'View Portfolio Post', 'text_domain' ),
    'add_new_item'        => __( 'Add New Portfolio Post', 'text_domain' ),
    'add_new'             => __( 'New Portfolio Post', 'text_domain' ),
    'edit_item'           => __( 'Edit Portfolio Post', 'text_domain' ),
    'update_item'         => __( 'Update Portfolio Post', 'text_domain' ),
    'search_items'        => __( 'Search Portfolio Posts', 'text_domain' ),
    'not_found'           => __( 'No portfolio posts found', 'text_domain' ),
    'not_found_in_trash'  => __( 'No portfolio posts found in Trash', 'text_domain' ),
);

$rewrite = array(
    'slug'                => 'portfoliopost',
    'with_front'          => true,
    'pages'               => true,
    'feeds'               => true,
);

$args = array(
    'label'               => __( 'portfoliopost', 'text_domain' ),
    'description'         => __( 'Post Type for Portfolio', 'text_domain' ),
    'labels'              => $labels,
    'supports'            => array( 'title', 'editor', 'custom-fields', ),
    'taxonomies'          => array( 'year', 'type' ),
    'hierarchical'        => false,
    'public'              => true,
    'show_ui'             => true,
    'show_in_menu'        => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'menu_position'       => 5,
    'can_export'          => true,
    'has_archive'         => true,
    'exclude_from_search' => false,
    'publicly_queryable'  => true,
    'query_var'           => 'portfoliopost',
    'rewrite'             => $rewrite,
    'capability_type'     => 'page',
);

register_post_type( 'portfolio_item_post', $args );
}

// Register Custom Taxonomy
function portfolio_year()  {
$labels = array(
    'name'                       => _x( 'Years', 'Taxonomy General Name', 'text_domain' ),
    'singular_name'              => _x( 'Year', 'Taxonomy Singular Name', 'text_domain' ),
    'menu_name'                  => __( 'Year', 'text_domain' ),
    'all_items'                  => __( 'All Years', 'text_domain' ),
    'parent_item'                => __( 'Parent Year', 'text_domain' ),
    'parent_item_colon'          => __( 'Parent Year:', 'text_domain' ),
    'new_item_name'              => __( 'New Year Name', 'text_domain' ),
    'add_new_item'               => __( 'Add New Year', 'text_domain' ),
    'edit_item'                  => __( 'Edit Year', 'text_domain' ),
    'update_item'                => __( 'Update Year', 'text_domain' ),
    'separate_items_with_commas' => __( 'Separate years with commas', 'text_domain' ),
    'search_items'               => __( 'Search years', 'text_domain' ),
    'add_or_remove_items'        => __( 'Add or remove years', 'text_domain' ),
    'choose_from_most_used'      => __( 'Choose from the most used yearss', 'text_domain' ),
);

$rewrite = array(
    'slug'                       => 'year',
    'with_front'                 => true,
    'hierarchical'               => true,
);

$capabilities = array(
    'manage_terms'               => 'manage_categories',
    'edit_terms'                 => 'manage_categories',
    'delete_terms'               => 'manage_categories',
    'assign_terms'               => 'edit_posts',
);

$args = array(
    'labels'                     => $labels,
    'hierarchical'               => true,
    'public'                     => true,
    'show_ui'                    => true,
    'show_admin_column'          => true,
    'show_in_nav_menus'          => true,
    'show_tagcloud'              => true,
    'query_var'                  => 'year',
    'rewrite'                    => $rewrite,
    'capabilities'               => $capabilities,
);

register_taxonomy( 'year', 'portfolio_item_post', $args );
}

// Register Custom Taxonomy
function media_type()  {
$labels = array(
    'name'                       => _x( 'Types', 'Taxonomy General Name', 'text_domain' ),
    'singular_name'              => _x( 'Type', 'Taxonomy Singular Name', 'text_domain' ),
    'menu_name'                  => __( 'Type', 'text_domain' ),
    'all_items'                  => __( 'All Types', 'text_domain' ),
    'parent_item'                => __( 'Parent Type', 'text_domain' ),
    'parent_item_colon'          => __( 'Parent Type:', 'text_domain' ),
    'new_item_name'              => __( 'New Type Name', 'text_domain' ),
    'add_new_item'               => __( 'Add New Type', 'text_domain' ),
    'edit_item'                  => __( 'Edit Type', 'text_domain' ),
    'update_item'                => __( 'Update Type', 'text_domain' ),
    'separate_items_with_commas' => __( 'Separate types with commas', 'text_domain' ),
    'search_items'               => __( 'Search types', 'text_domain' ),
    'add_or_remove_items'        => __( 'Add or remove types', 'text_domain' ),
    'choose_from_most_used'      => __( 'Choose from the most used types', 'text_domain' ),
);

$rewrite = array(
    'slug'                       => 'type',
    'with_front'                 => true,
    'hierarchical'               => true,
);

$capabilities = array(
    'manage_terms'               => 'manage_categories',
    'edit_terms'                 => 'manage_categories',
    'delete_terms'               => 'manage_categories',
    'assign_terms'               => 'edit_posts',
);

$args = array(
    'labels'                     => $labels,
    'hierarchical'               => true,
    'public'                     => true,
    'show_ui'                    => true,
    'show_admin_column'          => true,
    'show_in_nav_menus'          => true,
    'show_tagcloud'              => true,
    'query_var'                  => 'portfolio_type',
    'rewrite'                    => $rewrite,
    'capabilities'               => $capabilities,
);

register_taxonomy( 'type', 'portfolio_item_post', $args );
}

// Hook into the 'init' action
add_action( 'init', 'portfolio_item_post', 0 );

// Hook into the 'init' action
add_action( 'init', 'portfolio_year', 0 );

// Hook into the 'init' action
add_action( 'init', 'portfolio_type', 0 );

function theme_prefix_rewrite_flush() {
    flush_rewrite_rules();
}
add_action( 'after_switch_theme', 'theme_prefix_rewrite_flush' );

**Comment by 0dp** [comment]
Can you post the content of of your template file?

I assume that you used single.php to make your template file. From the excerpt below you can see it grabs the loop template here `<?php get_template_part( 'loop-templates/content', 'single' ); ?>`
```

			<main class="site-main" id="main">

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'loop-templates/content', 'single' ); ?>

					<?php understrap_post_nav(); ?>

					<?php
					// If comments are open or we have at least one comment, load up the comment template.
					if ( comments_open() || get_comments_number() ) :
						comments_template();
					endif;
					?>

				<?php endwhile; // end of the loop. ?>

</main><!-- #main -->
```

**Comment by LogiaKing** [comment]
Here is the code for my single-portfolio_item_post.php

<?php
/**
 * The template for displaying all single posts.
 *
 * @package understrap
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}

get_header();
$container = get_theme_mod( 'understrap_container_type' );
?>

<div class="wrapper" id="single-wrapper">

	<div class="<?php echo esc_attr( $container ); ?>" id="content" tabindex="-1">

		<div class="row">

			
			<?php get_template_part( 'global-templates/left-sidebar-check' ); ?>

			<main class="site-main" id="main">

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'loop-templates/portfolio_item_post', 'single' ); ?>

					<?php understrap_post_nav(); ?>

					<?php
					// If comments are open or we have at least one comment, load up the comment template.
					if ( comments_open() || get_comments_number() ) :
						comments_template();
					endif;
					?>

				<?php endwhile; // end of the loop. ?>

			</main>

			
			<?php get_template_part( 'global-templates/right-sidebar-check' ); ?>

		</div>

	</div>

</div>

<?php get_footer(); ?>


And here is the code in my loop template portfolio_item_post-single.php

<?php
/**
 * Portfolio post partial template.
 *
 * @package understrap
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly.
}
?>

<article <?php post_class(); ?> id="post-<?php the_ID(); ?>">

<header class="entry-header">
		
 <div class="row">
    <div class="col-sm-12">
		<?php the_title( '<h1 class="entry-title entry-title-single">', '</h1>' ); ?>
		<p class="client-title-single"><?php the_field('portfolio_item_client'); ?></p>
	</div>
</div>
	
</header>



	
<div class="row">
	<div class="col-sm-6 close-columns-single">
		<img src="<?php the_field('portfolio_image_one'); ?>">
	</div>
	<div class="col-sm-6 close-columns-single">
		<img src="<?php the_field('portfolio_image_two'); ?>">
	</div>
</div>

	

<div class="entry-content">
<div class="row black-row">
	
	<div class="col-sm-6 close-columns">
	<h2 class="white">The client.</h2>
        <?php the_content(); ?>	
	</div>	
	
	<div class="col-sm-6 close-columns">
	<h2 class="white">The challenge.</h2>	
		<?php the_field('the_challenge'); ?>
	</div>		
	
</div>
	

	
<div class="row">
	<div class="col-sm-12 close-columns">
<img src="<?php the_field('portfolio_full_width_image'); ?>">
	</div>
</div>
	

	
<div class="row white-row">
	
	<div class="col-sm-12 close-columns">
	<h2 class="white">The result.</h2>
        
		<?php the_field('the_result'); ?>	
	</div>	
		
	
</div>
	

	
<div class="row">
	<div class="col-sm-6 close-columns-single">
		<img src="<?php the_field('portfolio_image_three'); ?>">
	</div>
	<div class="col-sm-6 close-columns-single">
		<img src="<?php the_field('portfolio_image_four'); ?>">
	</div>
</div>
	

	
<div class="row">
	<div class="col-sm-12 close-columns">
<img src="<?php the_field('portfolio_full_width_image_two'); ?>">
	</div>
</div>
	
	

	</div>

	<footer class="entry-footer">

		<?php understrap_entry_footer(); ?>

	</footer>

</article>

**Comment by 0dp** [comment]
so your look template_part is called portfolio_item_post-single.php ?

```
<?php get_template_part( 'loop-templates/content', 'single' ); ?>
```
Translates to `content-single.php`

**Comment by LogiaKing** [comment]
Yes :)

**Comment by 0dp** [comment]
wp_debug is on?

Have you tried to echo something in single.php and single-portfolio_item_post.php to narrow it down?
tried echoing something in portfolio_item_post-single.php ?

To me it sounds like single-portfolio_item_post.php is either not called, or that there is a problem calling the loop template.

**Comment by LogiaKing** [comment]
Fixed

**Comment by 0dp** [comment]
Do you mind sharing what the issue was and how you fixed it? In case someone else run into the same issue
