### ISSUE TITLE
Basic Html Snippets for Bootstrap4 don't work

### ISSUE THREAD

**Issue by NitinPrakash** [understrap/understrap#919]
I have updated to latest version, basic Code snippets for Bootstrap does not work.

**Comment by pattonwebz** [comment]
Which snippets have you tried and hour did you try make them work?

**Comment by NitinPrakash** [comment]
Hi, Thanks for your reply.

I am using Understrap and testing the same for development purpose.

I created a Page Using Blank template

https://getbootstrap.com/docs/4.3/components/navs/#tabs

I am trying to create tabs.

Hope it helps

**Comment by pattonwebz** [comment]
Hey @NitinPrakash,

I am able to include bootstrap tabs directly in template files and also in the pages via the editor (so long as I am admin and allowed unfiltered html posting permissions). 

How were you trying to add the tabs into the page? Let me know what you tried already and how the method didn't do what you expected and I will try to look into it for you,

**Comment by NitinPrakash** [comment]
Thanks it worked for me

**Comment by holger1411** [comment]
Godd to hear that. Closing this.
