### ISSUE TITLE
Owlcarousel- owl.carousel.min.js 404 not found

### ISSUE THREAD

**Issue by Bare-Guillaume** [understrap/understrap#920]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:
 - **WordPress Version:** 5.0.3
  - **OS Version: MacOS [el-capitan 10.11.6]
  
Hello folks,

I'm trying to get owl carousel to work with understrap.
from the theme directory, I ran npm install --save owl.carousel
in child-theme.scss I added 
@import '../node_modules/owl.carousel/dist/assets/owl.carousel.css';
@import '../node_modules/owl.carousel';

in function.php I enqueue de style and script 

![screen shot 2019-02-17 at 21 42 49](https://user-images.githubusercontent.com/38908481/52918919-08f68880-32fd-11e9-983b-12b6db323310.png)

in theme directory/src/js/custom-javascript.js
$(document).ready(function () {
    $('.owl-carousel').owlCarousel();
});

getting error GET http://lvdcunderstrap.local/wp-content/themes/understrap/node_modules/owl.carousel/dist/owl.carousel.min.js?ver=5.0.3 net::ERR_ABORTED 404 (Not Found)

When I follow the path , the file owl.carousel.min.js is there, I dont understand why it's not found.

Can someone explain or point me to a clear step by step documentation on how to get it to work?

**Comment by sommerset** [comment]
you want to add owl carousel to the script task in the gulpfile (around line 130).   That way you get all your JS files in a single minified  file and save some bytes and network connections.

**Comment by Bare-Guillaume** [comment]
Thank you for helping @sommerset, I added the line but not sure it's the correct way.
![screen shot 2019-02-18 at 20 50 09](https://user-images.githubusercontent.com/38908481/52973685-22f89f80-33bf-11e9-88d0-c06de425b075.png)
The problem remain de same.
Could you explain with more detail if you can? 
or point to useful resources for that, the informations I found so far are not helping and I thought I followed the read me correctly but I'm clearly missing something.

**Comment by 0dp** [comment]
Hi @Bare-Guillaume,
`paths.dev + '/node_modules...` is incorrect. let me try and guide you through this.

1. Add owl.carousel to your package.json file manually or by running `npm install --save owl.carousel`
1. edit your gulpfile.js as following.
    1. in the copy-assets task add:
```
// Copy all owl CSS
    gulp.src( paths.node +'owl.carousel/dist/assets/owl.carousel.css' )
        .pipe( gulp.dest( paths.dev + '/owl' ) );

// Copy all owl JS
    gulp.src( paths.node +'owl.carousel/dist/owl.carousel.js' )
.pipe( gulp.dest( paths.dev + '/owl' ) );
```

In the scripts task add

```
paths.dev + '/owl/owl.carusel.js'
```
Right below `paths.dev + '/js/custom-javascript.js'`
remember the lines are comma seperated ie. `paths.dev + '/js/custom-javascript.js',`

in theme.scss add
```
@import "../../src/owl/owl.carousel.css";

This is the basics of using the gulp workflow.

But to review your existing attempt to enqueue the files it looks like you've done it correctly.
I noticed that the file you get a 404 on is on a local domain. Are you working local or remote?

**Comment by Bare-Guillaume** [comment]
Thank you @0dp for your straight forward explanations.
owl.carousel is present in package.json
in gulpfile.js
![screen shot 2019-02-19 at 20 11 00](https://user-images.githubusercontent.com/38908481/53041100-61579280-3483-11e9-9fd5-5e8b05918555.png)
![screen shot 2019-02-19 at 20 11 19](https://user-images.githubusercontent.com/38908481/53041114-6caabe00-3483-11e9-842e-f609d422c8c8.png)
in child-theme.scss
![screen shot 2019-02-19 at 20 12 14](https://user-images.githubusercontent.com/38908481/53041175-98c63f00-3483-11e9-9ea0-2bbb7324dec7.png)
then I ran gulp watch-bs
still having the error in the console
![screen shot 2019-02-19 at 20 15 47](https://user-images.githubusercontent.com/38908481/53041373-1e49ef00-3484-11e9-908c-6a1a2f508b8d.png)

Yes, I'm in local using https://local.getflywheel.com/

Thank you again to take the time to help.

**Comment by 0dp** [comment]
To remove the first 404, I guess you need to remove the enqueue from functions.php

To fix the second error. Replace $ with jQuery in you owl initialzation

```
jQuery(document).ready(function () {
jQuery('.owl-carousel').owlCarousel();
});
```

**Comment by Bare-Guillaume** [comment]
You are right for the first error, removing the enqueue from functions.php solved it.
As for the second, it's replaced by another error 
![screen shot 2019-02-19 at 20 57 09](https://user-images.githubusercontent.com/38908481/53043558-032dae00-3489-11e9-9d18-903c281221eb.png)

**Comment by 0dp** [comment]
you can see owl.carousel.js in your ./src folder?

**Comment by Bare-Guillaume** [comment]
no, I can see it in /themes/understrap-child/node_modules/owl.carousel/dist/owl.carousel.js

**Comment by axlright** [comment]
The `./node_modules/owl.carousel/dist/owl.carousel.js` is coming from you running `npm install` but that file should be copied over to your `./src/js/owl/` directory after running `gulp copy-assets` based on your copy-assets setup:

```
// Copy all owl CSS
    gulp.src( paths.node +'owl.carousel/dist/assets/owl.carousel.css' )
        .pipe( gulp.dest( paths.dev + '/owl' ) );

// Copy all owl JS
    gulp.src( paths.node +'owl.carousel/dist/owl.carousel.js' )
.pipe( gulp.dest( paths.dev + '/owl' ) );
```

So after running `npm install` you should see the script at `./node_modules/owl.carousel/dist/` and after running `gulp copy-assets` you should see the script at `./src/js/owl/`

Then after running `gulp scripts` you should see the script compiled in `./js/theme.js` (easier to look in the unminified version).

Do you see the script in all three places?

**Comment by Bare-Guillaume** [comment]
Yes, @axlright the gulp copy-assets command was the missing link.
All the files are where they are suppose to be it seems.
The only error remaining is 
![screen shot 2019-02-22 at 11 05 19](https://user-images.githubusercontent.com/38908481/53235321-d00a3b00-3691-11e9-881d-2f64ffed3dd4.png)
whether I write the code 
jQuery(document).ready(function () {
    jQuery('.owl-carousel').owlCarousel();
});

or like mentioned in the readme

$(document).ready(function(){
  $('.owl-carousel').owlCarousel();
});

![screen shot 2019-02-22 at 11 07 24](https://user-images.githubusercontent.com/38908481/53235437-16f83080-3692-11e9-985a-32afb3f26701.png)

**Comment by axlright** [comment]
@Bare-Guillaume glad the `gulp copy-assets` was helpful.

To debug that js console error, I'd go into `functions.php` and temporarily change the enqueud main js file from `child-theme.min.js` to `child-theme.js` so that you can see exactly what line the error is on.

I'm myself not entirely sure why there are errors getting thrown using `$` instead of `jQuery` but that's a conversation for another day.

**Comment by pattonwebz** [comment]
@Bare-Guillaume to me this sounds like an issue with inclusion order. Can you try move your custom script include to the very end of the list of JS files so that it's included after owlcarousel and all the other scrips that are compiled and see if that resolves this?

**Comment by pattonwebz** [comment]
@axlright the shorthand `$` symbol is used in many libraries. As such jQuery has a `noConflict` mode that lets the shorthand reference be avoided and WordPress uses that mode when including jQuery to help prevent conflicts with other libraries. WordPress by default includes the jQyery object by it's real name `jQuery` and not with the shorthand `$`. You can remap it to the shorthand if you wanted inside of a function. I mostly see this done with a closure like so:

    (function($) {
	
	// $ Works! You can test it with next line if you like
	// console.log($);
	
    })( jQuery );

**Comment by Thomas-A-Reinert** [comment]
With all the answers trying to resolve that issue and no feedback for more than a month I consider this issue as "resolved". Feel free to reopen if the problem persists.
