### ISSUE TITLE
NPM install isn't working - error on postinstall

### ISSUE THREAD

**Issue by gcrea** [understrap/understrap#924]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** Windows 10] | 
  - **Browser:** [ all 
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V 10.15.1] | NPM [V 6.4.1]

---

# Issue Overview for Bugreports

## Steps to reproduce?

npm install

## *What* is affected by this bug?

npm won't install, gives the following errors

> understrap@0.8.6 postinstall C:\wamp\www\rwe\wp-content\themes\rwe
> gulp copy-assets

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\wamp\www\rwe\wp-content\themes\rwe\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\wamp\www\rwe\wp-content\themes\rwe\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\wamp\www\rwe\wp-content\themes\rwe\gulpfile.js:28:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.8.6 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.8.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Owner\AppData\Roaming\npm-cache\_logs\2019-02-27T06_29_53_460Z-debug.log

## *When* does this occur?

understrap@0.8.6 postinstall

## Expected behavior

# Todos

 * Test
 * Documentation

### Other Comments

I need to get a project done and npm won't install. Your quick help is really, really, appreciated. Thank you in advance.

**Comment by 0dp** [comment]
What's the output of `gulp -v`

**Comment by gcrea** [comment]
[00:39:20] CLI version 2.0.1
[00:39:20] Local version 4.0.0

**Comment by 0dp** [comment]
You need to downgrade your local version to 3.9.x, or use the version of understrap provided here:
https://github.com/understrap/understrap/pull/883
If you want to use Gulp4

**Comment by gcrea** [comment]
Thank you! I downgraded and it works. I am getting the following message,
is this a problem?

+ gulp@3.9.0
added 63 packages from 39 contributors, removed 65 packages, updated 9
packages and audited 10892 packages in 56.382s
found 8 vulnerabilities (3 low, 1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by 0dp** [comment]
It shouldn't be a problem :)
We are working on a gulp4 version of the theme that is currently being battle tested

**Comment by gcrea** [comment]
Ok, thanks so much for your help.

**Comment by ayezee33** [comment]
I am running into this same error. I moved my gulp version to 3.9.0 and am still getting this error. The logs aren't providing any extra information. Does anyone have thoughts on this?

**Comment by gcrea** [comment]
I ran  npm install gulp@3.9.0 in the theme folder and it worked.

**Comment by Thomas-A-Reinert** [comment]
Assume this has been fixed by now. In case it hasn´t, please reopen this topic as I´m closing it due to the time there hasn´t been any update to it.
