### ISSUE TITLE
Gulp Watch Error

### ISSUE THREAD

**Issue by gcrea** [understrap/understrap#925]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** Windows 10
  - **Browser:** all
  - **Language:**  all
  - **Node.js & NPM Versions:** Node.js [V 10.15.1] | NPM [V 6.4.1]

---

# Issue Overview for Bugreports
Gulp watch runs for a few seconds, and then I get the following errors and it won't work:

{ Error: sass\theme.scss
Error: File to import not found or unreadable: theme/theme.
        on line 11 of sass/theme.scss
>> @import "theme/theme";  // <--------- That's where you can add your own desi
   ^

    at options.error (C:\wamp\www\rwe\wp-content\themes\rwe\node_modules\node-sass\lib\index.js:291:26)
  status: 1,
  file: 'C:/wamp/www/rwe/wp-content/themes/rwe/sass/theme.scss',
  line: 11,
  column: 1,
  message:
   'sass\\theme.scss\nError: File to import not found or unreadable: theme/theme.\n        on line 11 of sass/theme.scss\n>> @import "theme/theme";  // <--------- That\'s where you can add your own desi\n   ^\n',
  formatted:
   'Error: File to import not found or unreadable: theme/theme.\n        on line 11 of sass/theme.scss\n>> @import "theme/theme";  // <--------- That\'s where you can add your own desi\n   ^\n',
  messageFormatted:
   '\u001b[4msass\\theme.scss\u001b[24m\nError: File to import not found or unreadable: theme/theme.\n        on line 11 of sass/theme.scss\n>> @import "theme/theme";  // <--------- That\'s where you can add your own desi\n   ^\n',
  messageOriginal: 'File to import not found or unreadable: theme/theme.',
  relativePath: 'sass\\theme.scss',
  name: 'Error',
  stack:
   'Error: sass\\theme.scss\nError: File to import not found or unreadable: theme/theme.\n        on line 11 of sass/theme.scss\n>> @import "theme/theme";  // <--------- That\'s where you can add your own desi\n   ^\n\n    at options.error (C:\\wamp\\www\\rwe\\wp-content\\themes\\rwe\\node_modules\\node-sass\\lib\\index.js:291:26)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-sass',
  showProperties: true,
  showStack: false }

## Steps to reproduce?

Run gulp watch

## *What* is affected by this bug?

SCSS processing stops working

## *When* does this occur?

It works for a few seconds processing changs, then crashes.

## Expected behavior

# Todos

 * Test
 * Documentation

### Other Comments

Thank you for your help again!

**Comment by 0dp** [comment]
is `_theme.scss` available in ./sass/theme/ ?

**Comment by gcrea** [comment]
Yes, I'm editing it when the breakdown occurrs.

**Comment by 0dp** [comment]
Could you check the file permissions, and also check if you have any syntax error?

**Comment by gcrea** [comment]
I added an _ to line 10 of theme.scss and now it seems to be working.
@import "theme/_theme";  // <--------- That's where you can add your own
design. Thats your part!
