### ISSUE TITLE
Help Wanted: gulp dist 

### ISSUE THREAD

**Issue by tolkadot** [understrap/understrap#926]
## Issue is about..
  - [ ] a Question

## Please tell us about your environment:
  - **WordPress Version:** 5.1
  - **Language:**Javascript 

# Issue Overview for Bugreports

Using understrap child I've set up my dist folder as a git repo.  I send this up to GitHub and then pull it down to cloudways.  It makes updating my theme locally and then getting it onto the live site really easy.  When I run `gulp dist` in the child theme, .git config doesn't get overwritten.

I've also built a site using understrap as a starter theme, however, when I run `gulp dist` the dist folder gets completely removed prior to the latest theme files being added and in the process, the .git config is removed.

These are the tasks from the gulpfile of each theme. Can someone help me modify the task from 
the Understrap theme so that my .git config doesn't get removed every time I run gulp dist ?

Understrap Child
```
// Deleting any file inside the /dist folder
gulp.task('clean-dist', function () {
  return del(['dist/**/*',]);
});
```

Understrap
```
// Deleting any file inside the /dist folder
gulp.task( 'clean-dist', function() {
  return del( [paths.dist + '/**'] );
});
```

Any input appreciated. Thanks.

**Comment by 0dp** [comment]
If you take a look at the `dist` task you should see that it calls `clean-dist` you can try and remove that and see if that is sufficient.

Otherwise we need to whitelist / blacklist files and file types in the `clean-dist` task

**Comment by tolkadot** [comment]
I removed clean-dist from the dist task as you suggested and it resulted in the desired outcome. 
Thank you.
