### ISSUE TITLE
How to add top full section for sub pages ?

### ISSUE THREAD

**Issue by DwijadasDey** [understrap/understrap#928]
Please delete anything that does not apply for you!

## Issue is about..

  - [x] I need help

## Please tell us about your environment:
  - **WordPress Version:** 5.1.x
  - **OS Version:** [| Linux [CentOS / 7.1] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
---

How can i add `Top full` section for sub pages ? I have only `Right sidebar` and `footer full` in the widget area for sub pages although all sections are available in the home page.

**Comment by zafon18** [comment]
Hello,
You must add this code on your template 
for single post - content-single.php
`<?php get_template_part( 'sidebar-templates/statichero', 'statichero' ); ?>`

or your template 

e.g home template
```get_header();
$container = get_theme_mod( 'understrap_container_type' );
?>

<div class="wrapper" id="page-wrapper">

	<div class="<?php echo esc_attr( $container ); ?>" id="content">
<?php get_template_part( 'sidebar-templates/statichero', 'statichero' ); ?>

**Comment by zafon18** [comment]
If I wrongly prompted please correct me :)

**Comment by Thomas-A-Reinert** [comment]
General WordPress Problem, not an UnderStrap issue, so I´m going to close this.

Thanks for helping out though, @zafon18
