### ISSUE TITLE
Functions Refactoring 

### ISSUE THREAD

**Issue by misfist** [understrap/understrap#930]
## Issue is about..
  - [ X  ] a Bug Report

## Environment:

  - **WordPress Version:** Version 5.1
  - **OS Version:** Linux [Ubuntu 18.04]
  - **Browser:** [ all  ]
  - **Language:** [ PHP ]
  - **Node.js & NPM Versions:** Node.js [v8.11.4 | NPM [V. 5.8.0]

After updating the Understrap from 0.8.7 to 0.8.8, I started getting an error in my custom child theme originating from the parent Understrap theme.

```
Uncaught Error: Call to undefined function understrap_categorized_blog() in /srv/www/metcouncil/wordpress/wp-content/themes/understrap/404.php:45
```

The issue seems to be due to changes made in the parent `functions.php`, which now uses `locate_template` to require files. The problem is that locate_template first looks in the child theme for the files, and my custom child theme has its own function files (sometimes) using the same paths. So, in this case, `understrap_categorized_blog()` can't be found because the function is in the parent `/inc/template-tags.php file`, but the locate_template only loads the child theme's `/inc/template-tags.php`, which doesn't contain that function.

As a work-around, I can rename the folder containing my child theme function files (say, `/includes` instead of `inc`). However, I'm not sure that the parent theme should be loading child function files rather than it's own. At the very least, this should be called out as a breaking change.

ref: https://codex.wordpress.org/Function_Reference/locate_template
understrap/understrap@9dacaa8

Duplicates: https://github.com/understrap/understrap-child/issues/214

## Steps to reproduce?
Create a understrap_child theme from the git repo. After activating the child theme, the widgets menu disappears under appearance. Among others.

## Who is the bug affecting?

All child themes that use the same file structure for custom functions (`/inc/setup.php`, `inc/extras.php`, etc)

## What is affected by this bug?

All parent theme settings and functionality if child theme contains same files.

## When does this occur?

Always

## Where on the platform does it happen?

Everywhere

## How do we replicate the issue?

After activating the child theme that is using understrap 0.8.8 as the parent. You can make the

## Are there any related Issues and/or PRs?

Maybe #845

**Comment by Thomas-A-Reinert** [comment]
This is an UnderStrap-Child-Theme issue, so I´m not even going to read it at all.
Sorry, don´t get mad at me, but please post your question/issue in the https://github.com/understrap/understrap-child tracker. It just does not belong here.

**Comment by misfist** [comment]
> This is an UnderStrap-Child-Theme issue, so I´m not even going to read it at all.
> Sorry, don´t get mad at me, but please post your question/issue in the https://github.com/understrap/understrap-child tracker. It just does not belong here.

This is not a child theme issue. It is an issue of how include files are now included. The parent theme no longer uses WP functions, which will appropriately determine if the theme is a parent or child theme. The fatal error originates from the parent Understrap theme. So, the change breaks child-theme compatibility. 

- https://developer.wordpress.org/reference/functions/get_template_directory/
- https://developer.wordpress.org/reference/functions/get_stylesheet_directory/

**Comment by Thomas-A-Reinert** [comment]
I´m sorry, really. Please excuse me being so "ignoran".
But as soon as I read "child-theme" I usually close a topic. And I hope you understand. If we answer child-theme questions in the parent-theme issue-tracker, child-theme users won´t profit from it getting answered here.

Can´t promise that I´ll personally get into it (because I usually do forks of the parent), but I´m going to delegate it to the maintainer.

**Comment by Thomas-A-Reinert** [comment]
PS: If anyone else can solve the problem, we´re open for pull requests. Please mention the issue in it!

**Comment by IanDelMar** [comment]
@misfist Does changing lines 29-35 in the functions.php of the parent to 
```php
foreach ( $understrap_includes as $file ) {
	require get_template_directory() . '/inc/' . $file;
}
```
solve the issue?

**Comment by misfist** [comment]
> @misfist Does changing lines 29-35 in the functions.php of the parent to
> 
> ```
> foreach ( $understrap_includes as $file ) {
> 	require get_template_directory() . '/inc/' . $file;
> }
> ```
> 
> solve the issue?

Haven't tested; but, yes, I think it would solve the issue.

**Comment by 0dp** [comment]
Isn't it also more convenient to use relative URI instead of absolute path?

**Comment by misfist** [comment]
> Isn't it also more convenient to use relative URI instead of absolute path?

No, this doesn't address the issue because a child them will look for the include files relative to itself rather than in the parent theme.

**Comment by 0dp** [comment]
Never said it would just that I think it's preferable to use relative uri's instead of absolute paths, like the one provided by `get_template_directory();`

I propose using something like `get_template_directory_uri();`
instead.

🤷‍♀️

**Comment by Thomas-A-Reinert** [comment]
If the problem remains, please feel free to re-open that issue.
Due to the fact that it didn´t get adressed since Juli, i´m going to close this issue
