### ISSUE TITLE
gutenburg videos not sizing properly in columns

### ISSUE THREAD

**Issue by redknite** [understrap/understrap#931]
## Issue is about..
  - [ x ] a Bug Report
  - [ x ] a Question
  - [  x ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.0.1
  - **OS Version:** [Windows 7 | 

  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports
when using this theme if i put 2 youtube gutenburg embeds in side-by-side gutenburg columns, the videos do not respect the column width padding.  Switching themes to shows that the code is good as the youtube videos stay within content boundaries
## Steps to reproduce?
1. create a new page.
2. edit page with gutenburg
3. set a row to 2 columns.
4. in each column add a youtube embed
5. add youtube video link to each embed block
6. Preview (or save and view) page.  
7. Videos overlap and go beyond content container.
## *Who* is the bug affecting?
all
## *What* is affected by this bug?
viewing videos
## *When* does this occur?
see notes above
## *Where* on the platform does it happen?
see notes above
## *How* do we replicate the issue?
see notes above

## Screenshots / Video
attached
![video capture](https://user-images.githubusercontent.com/602574/53767037-c2bf2e80-3e91-11e9-8674-39067cfaf2b5.PNG)

## Expected behavior

Thanks for helping with this

**Comment by redknite** [comment]
any ideas?

**Comment by 0dp** [comment]
@MarieComet do you have any input on this?

**Comment by MarieComet** [comment]
Yes,
It's because Understrap do not have declared support for responsive embeds.

Adding 
```
// Add support for responsive embedded content.
add_theme_support( 'responsive-embeds' );
```
in `understrap_setup` function fix it.

**Comment by MarieComet** [comment]
Here is a pull request which fix that : https://github.com/understrap/understrap/pull/935

**Comment by redknite** [comment]
Pure Genius.  Thanks Marie!

**Comment by sebastienserre** [comment]
I know... She's m'y friend !

**Comment by 0dp** [comment]
@redknite please close the issue if it has been resolved. Thx
