### ISSUE TITLE
Google analytics plugins do not work with woocommerce Understrap

### ISSUE THREAD

**Issue by shansmith01** [understrap/understrap#932]
I am having a lot of trouble managing conversions with google analytics whilst using understrap and to me, it seems that there is something missing from our custom woocommerce files which allow us to use analytics plugins to measure e-commerce conversions.

So far I have tried using:

- https://woocommerce.com/products/woocommerce-google-analytics-pro/
- https://wordpress.org/plugins/duracelltomi-google-tag-manager/

In both cases nothing is fired on conversion when using understrap, but everything works fine in a default theme.

Has anyone else experienced this? Can someone point me in the right direction for files to edit?

## Issue is about..
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

`
### WordPress Environment ###

Home URL: https://nomadsworld.com
Site URL: https://nomadsworld.com
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: ❌ 5.0.3 - There is a newer version of WordPress available (5.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.15-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.24-27-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 1 active Zapier Feed.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ All Payments
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/298121/p5pk23/
Zapier Feed #1 Trigger: ✔ New Order
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/298121/p5pk23/.

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 57.98MB
Database Data Size: 43.75MB
Database Index Size: 14.23MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.11MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 4.19MB + Index: 0.77MB
wp_comments: Data: 3.28MB + Index: 0.61MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 1.52MB + Index: 0.20MB
wp_gf_entry_meta: Data: 1.52MB + Index: 2.28MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.17MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.14MB + Index: 0.13MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.22MB + Index: 0.16MB
wp_postmeta: Data: 13.52MB + Index: 4.03MB
wp_posts: Data: 7.30MB + Index: 0.53MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.14MB + Index: 0.00MB
wp_rg_form_view: Data: 0.08MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 1.52MB + Index: 0.17MB
wp_rg_lead_detail: Data: 1.52MB + Index: 2.19MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_rg_zapier: Data: 0.02MB + Index: 0.02MB
wp_termmeta: Data: 1.52MB + Index: 0.03MB
wp_terms: Data: 1.52MB + Index: 0.91MB
wp_term_relationships: Data: 1.48MB + Index: 0.34MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.73MB
wp_usermeta: Data: 0.19MB + Index: 0.20MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wof_optins: Data: 0.02MB + Index: 0.00MB
wp_wp_criticalcss: Data: 0.02MB + Index: 0.00MB
wp_wp_criticalcss_api_queue: Data: 0.02MB + Index: 0.00MB
wp_wp_criticalcss_processed_items: Data: 0.02MB + Index: 0.00MB
wp_wp_criticalcss_template_log: Data: 0.02MB + Index: 0.00MB
wp_wp_criticalcss_web_check_queue: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.41MB + Index: 0.14MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 79
acf-field-group: 10
attachment: 1843
condition_group: 2
custom_css: 1
mb_woc_wheel: 1
nav_menu_item: 21
oembed_cache: 17
page: 73
post: 368
product: 16
product_variation: 107
revision: 91
shop_coupon: 2
shop_order: 90
shop_order_refund: 2
sidebar: 2
wc_zapier_feed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Gravity Forms: by rocketgenius – 2.4.6
Accelerated Mobile Pages: by Ahmed Kaludi
Mohammed Kaludi – 0.9.97.38

ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.2.0

Advanced Custom Fields PRO: by Elliot Condon – 5.7.12
Akismet Anti-Spam: by Automattic – 4.1.1
Amazon AI: by AWS Labs
WP Engine – 3.0.0

Autocomplete WooCommerce Orders: by Liam McArthur – 1.1.0
Classic Editor: by WordPress Contributors – 1.4
Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.8.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2
Enhanced Media Library PRO: by wpUXsolutions – 2.4.5
Gravity Forms Event Tracking: by Ronald Huereca – 2.3.5
Gravity Forms Pipe Add-On: by rocketgenius – 1.1
Gravity Forms Zapier Add-on: by rocketgenius – 3.1
Mailgun: by Mailgun – 1.7.1
Minimal Blogging Theme for AMP: by AMPforWP Team – 1.0
WooCommerce Order Export and More: by JEM Plugins – 2.0.11
Search by Algolia – Instant & Relevant results: by Algolia – 2.11.3
ShortPixel Image Optimizer: by ShortPixel – 4.12.8
WooCommerce Advanced Notifications: by WooCommerce – 1.2.13 – 1.2.15 is available – Not tested with the active version of WooCommerce
WooCommerce Merchant Warrior (Transparent Redirect) Gateway: by Tyson Armstrong – 1.6.1 – 1.6.3 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Google Analytics Pro: by SkyVerge – 1.3.6 – 1.6.6 is available – Not tested with the active version of WooCommerce
WooCommerce Twitter Bootstrap: by Bass Jobsen – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce Zapier Integration: by OM4 – 1.8.1
WooCommerce: by Automattic – 3.5.5
Yoast SEO Premium: by Team Yoast – 5.2
WP Rocket: by WP Media – 3.2.6
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1715 - /shop/
Cart: #1716 - /cart/
Checkout: #1717 - /checkout/
My account: #1718 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: UnderStrap Child
Version: 0.3.10
Author URL: http://www.holgerkoenemann.de
Child Theme: ✔
Parent Theme Name: UnderStrap
Parent Theme Version: 0.9.1
Parent Theme Author URL: http://www.holgerkoenemann.de
WooCommerce Support: ✔

### Templates ###

Overrides: understrap/woocommerce/cart/cart-empty.php
understrap/woocommerce/cart/cart.php
understrap/woocommerce/cart/mini-cart.php
understrap/woocommerce/cart/proceed-to-checkout-button.php
understrap/woocommerce/checkout/form-checkout.php
understrap/woocommerce/checkout/form-coupon.php
understrap/woocommerce/checkout/form-pay.php
understrap/woocommerce/checkout/payment.php
understrap-child/woocommerce/emails/customer-processing-order.php version 2.5.0 is out of date. The core version is 3.5.4
understrap/woocommerce/global/form-login.php
understrap/woocommerce/global/quantity-input.php
understrap/woocommerce/loop/add-to-cart.php
understrap/woocommerce/loop/orderby.php
understrap/woocommerce/myaccount/downloads.php
understrap/woocommerce/myaccount/form-edit-account.php
understrap/woocommerce/myaccount/form-edit-address.php
understrap/woocommerce/myaccount/form-login.php
understrap/woocommerce/myaccount/form-lost-password.php
understrap/woocommerce/myaccount/form-reset-password.php version 3.5.1 is out of date. The core version is 3.5.5
understrap/woocommerce/myaccount/my-address.php
understrap/woocommerce/myaccount/my-orders.php
understrap/woocommerce/myaccount/navigation.php
understrap/woocommerce/myaccount/orders.php
understrap/woocommerce/product-searchform.php
understrap/woocommerce/single-product/add-to-cart/simple.php
understrap/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
understrap/woocommerce/single-product/rating.php

Outdated Templates: ❌
					
					
						Learn how to update
`

## Steps to reproduce?

Install a GA plugin. Make a transaction. Nothing is sent to GA. Revert to defult wordpress theme (twenty something) all works

## *Who* is the bug affecting?

Admin. I can not see my data

## *What* is affected by this bug?

Google analytics eccomerce report

## *When* does this occur?

On conversions

## Are there any related Issues and/or PRs?

Not that i can see

## Expected behavior

I should be able to install any analytics eccommerce plugin that uses wordpress/woocomerce best practice and use it instantly with Understrap

**Comment by 0dp** [comment]
You mention yourself, that maybe something is missing from your custom woocommerce files.

Have you tried to temporarily remove those?

Maybe you have a hook that is overriding something vital?

**Comment by pattonwebz** [comment]
Most analytics plugins hook to either the `wp_head()` or `wp_footer()` and both are firing for me in my local.

@shansmilth01 the code that fires the tracking will be JS available on the pages that are being tracked so if you look at the markup of the page you should be able to find the code. I don't know what the code this plugins adds is supposed to look like but it probably starts with a `ga` object var.

I suggest you start by looking there to confirm tracking code exists when it's supposed to, that it is not malformed and that there are no other JS errors thrown on the page that prevents it triggering. Since you know it works with the default theme you tested you site be able to get known withing code from there and compare differences between when understrap is active Vs not active.

**Comment by 0dp** [comment]
Also make sure you are not logged in since most of these plugins have an option enabled by default to not include the script on admin users.

Also check console for errors

**Comment by 0dp** [comment]
@shansmith01 did you solve it?

**Comment by Thomas-A-Reinert** [comment]
No feedback for about a month so I consider this solved and/or abandoned. Please reopen if the problem persists.
