### ISSUE TITLE
Where can I add custom preexisting sass/scss?

### ISSUE THREAD

**Issue by xicubed** [understrap/understrap#933]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1
  - **OS Version:**  MacOS [10.14.3]
  - **Browser:** [ all ]
  - **Language:** [ S/CSS]
  - **Node.js & NPM Versions:** Node.js [V 11.10.0] | NPM [V 6.5.0]

---

### Other Comments

I'm using a child theme. I see how I can edit the _child_theme.scss and _child_theme_variables.scss but how do I add an entire new folder with subfolders of preexisting scss?

So I have:
/wp-content/themes/core-understrap-1-0-7/sass/theme
/wp-content/themes/core-understrap-1-0-7/sass/child-theme.scss
/wp-content/themes/core-understrap-1-0-7/sass/theme/_child_theme.scss
/wp-content/themes/core-understrap-1-0-7/sass/theme/_child_theme_variables.scss

but I want to add something like:
/wp-content/themes/core-understrap-1-0-7/sass/theme/my-preexisting-sass
/wp-content/themes/core-understrap-1-0-7/sass/theme/my-preexisting-sass/styles.scss
which imports folders in there like
/wp-content/themes/core-understrap-1-0-7/sass/theme/my-preexisting-sass/base
/wp-content/themes/core-understrap-1-0-7/sass/theme/my-preexisting-sass/utilities
etc

**Comment by xicubed** [comment]
Thanks, added `@import "theme/my-preexisting-sass/styles";` to child-theme.scss which in turn imports the other files. 

I also changed the gulp task:
```
    gulp.task('scss-for-dev', function() {
    gulp.src('./sass/*.scss')
```

to:
`   gulp.src('./sass/**/*')`

**Comment by Alligatore3** [comment]
Ehy

It would be great for me to be able to separate my SCSS logic like having something like`/wp-content/themes/tedx/sass/theme/_media-queries.scss`

But with this `wp-content/themes/tedx/sass/theme.scss`:
```
@import "theme/theme_variables";  // <-------- Add your variables into this file. Also add variables to overwrite Bootstrap or UnderStrap variables here
@import "assets/bootstrap4";      // <-------- Loads Bootstrap4
@import "understrap/understrap";  // <-------- Loads the UnderStrap defaults. Just a few classes to incorporate BS in WP
@import "understrap/woocommerce"; // <-------- Loads WooCommerce style fixes. Comment out if you aren't using WooCommerce

// Optional files - If you dont use the corresponding scripts/fonts comment em out
@import "assets/font-awesome";    // <-------- Font Awesome Icon font
@import "assets/underscores";     // <-------- Underscores media styles

// Any additional imported files //
@import "theme/theme";            // <-------- That's where you can add your own design. Thats your part!
@import "theme/media-queries";
@import "theme/contact-form7";    // <-------- Contact Form 7 - Bootstrap 4 support
```

My logic is not working.

**Comment by xicubed** [comment]
@Alligatore3 At the end below those other import's you might need an import like:

`@import "theme/tedx/styles";`

Where wp-content/themes/tedx/sass/theme/tedx contains your styles.scss and all your folders of scss etc. Then in that styles.scss you have imports to your other folders/files within the furthest down tedx 

```
@import 'media_queries';
@import 'utilities/variables';
@import 'utilities/mixins';

@import 'base/base';
@import 'base/typography';
```

**Comment by Alligatore3** [comment]
@xicubed Sorry for being late!

your solution seems to work.
Thanks for support.
