### ISSUE TITLE
jQuery is not a function

### ISSUE THREAD

**Issue by luk9like** [understrap/understrap#939]
## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1.x
  - **Language:** [Javascript | jQuery]
  - **Node.js & NPM Versions:** Node.js [11.10.1] | NPM [6.7.0]

---

Hi,
I'm trying to add some custom js. jQuery is loaded, but it doesn't work.
`$('select').selectpicker();`

![Bildschirmfoto von 2019-03-11 12-45-36](https://user-images.githubusercontent.com/29478532/54121786-9eb49d80-43fb-11e9-83cb-7f09991db77c.png)

What's wrong ?

**Comment by 0dp** [comment]
https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/

**Comment by 0dp** [comment]
@luk9like did you figure it out?

**Comment by 0dp** [comment]
@holger1411 please close
