### ISSUE TITLE
Issue on mobile

### ISSUE THREAD

**Issue by jchrislemmer** [understrap/understrap#940]
Good day,

This line is causing an issue on mobile. Please have a look at the mobile page. The login div is only 1-col in size.

https://github.com/understrap/understrap/blob/4060ecd88ba95711fbcf2ab7abc14481551c7532/woocommerce/myaccount/form-login.php#L28

Thanks
Chris

**Comment by 0dp** [comment]
@understrap/woocommerce-team

**Comment by holger1411** [comment]
Fixing it here: 
https://github.com/understrap/understrap/commit/fa0bef5e7252cc6681c8334edc1a5f40cffe5409
Thx for reporting!
