### ISSUE TITLE
Slide Toggle Nav Dropdowns

### ISSUE THREAD

**Issue by gcrea** [understrap/understrap#941]
I'm using understrap and I've added the following to the head after jQuery:

```
<script type="text/javascript">
	
  // Add slideDown animation to Bootstrap dropdown when expanding.
  jQuery('.dropdown').on('show.bs.dropdown', function() {
    jQuery(this).find('.dropdown-menu').first().stop(true, true).slideDown();
  });

  // Add slideUp animation to Bootstrap dropdown when collapsing.
  jQuery('.dropdown').on('hide.bs.dropdown', function() {
    jQuery(this).find('.dropdown-menu').first().stop(true, true).slideUp();
  });

</script>
```

This should make the main nav dropdowns slide-toggle on click, but they still just appear and disappear in the standard way on click. Can you help me?

**Comment by Thomas-A-Reinert** [comment]
Hi @gcrea could you please explain what the "_after jQuery_" is and where / in which file you added that script?

**Comment by gcrea** [comment]
I added the code in header.php under the scri0t that activates jQuery.

**Comment by gcrea** [comment]
Any ideas?

**Comment by gcrea** [comment]
In header.php

<?php
/**
 * The header for our theme.
 *
 * Displays all of the <head> section and everything up till <div
id="content">
 *
 * @package understrap
 */

$container = get_theme_mod( 'understrap_container_type' );
?>
<!DOCTYPE html>
<html <?php language_attributes(); ?>>
<head>
<meta charset="<?php bloginfo( 'charset' ); ?>">
<meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="<?php bloginfo( 'name' );
?> - <?php bloginfo( 'description' ); ?>">
<link rel="profile" href="http://gmpg.org/xfn/11">
<link rel="pingback" href="<?php bloginfo( 'pingback_url' ); ?>">
<?php wp_head(); ?>

<script type="text/javascript">
  // Add slideDown animation to Bootstrap dropdown when expanding.
  jQuery('.dropdown').on('show.bs.dropdown', function() {
    jQuery(this).find('.dropdown-menu').first().stop(true,
true).slideDown();
  });

  // Add slideUp animation to Bootstrap dropdown when collapsing.
  jQuery('.dropdown').on('hide.bs.dropdown', function() {
    jQuery(this).find('.dropdown-menu').first().stop(true, true).slideUp();
  });

</script>
</head>

I wanted to get it working before enqueing it...

**Comment by 0dp** [comment]
You should add this in the footer before the closing html or better yet, add it to the custom-scripts file in ./src

**Comment by gcrea** [comment]
That worked, thank you!

**Comment by 0dp** [comment]
Awesome! Please close the issue if it's been resolved
