### ISSUE TITLE
Custom JS file does not compile

### ISSUE THREAD

**Issue by sayayinR** [understrap/understrap#942]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1
  - **OS Version:** [Windows 10
  - **Browser:** [ all | Chrome 73
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V 6.11.2] | NPM [V 3.10.10]

---

### Other Comments
Hey Guys,
I know there is couple of threads to support this issue but I cannot figure this out. I am using version 0.9.1 and I believe all I have to do is add custom-javascript.js to the src folder. I did this, stopped and ran gulp watch over and over again but my script does not trigger (a simple alert for troubleshooting). I looked at the src code and searched for my code and I cannot find it. Can someone advise what am I doing wrong?

Thank you!

**Comment by sayayinR** [comment]
Hey Guys, so it was totally my fault. I was compiling in the wrong folder but now I have a different issue. Uglify keeps failing with the error: message: 'Unexpected token: name . After some research I'm seeing posts about which version to use with ES6. Does the version provided in understrap support ES6?

**Comment by 0dp** [comment]
Can you post the entire error message please?

The short answer is no, but checkout #883

**Comment by sayayinR** [comment]
I'll check it out.
Here is the whole error, I commented out all my code and left one line for variable declaration. When I use "var", it does not break on save but when I use "let", it breaks.
`SyntaxError: Unexpected token: name (scripts_vars)
       at JS_Parse_Error.get (eval at <anonymous> (C:\wamp\www\bouncetopia\wp-content\themes\bouncetopia\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
       at formatError (util.js:646:15)
       at formatValue (util.js:552:18)
       at formatProperty (util.js:792:15)
       at util.js:652:12
       at Array.map (native)
       at formatObject (util.js:651:15)
       at formatValue (util.js:591:16)
       at inspect (util.js:185:10)
       at exports.format (util.js:71:24)
     message: 'Unexpected token: name (scripts_vars)',
     filename: 'theme.min.js',
     line: 7050,
     col: 4,
     pos: 223797 },
  plugin: 'gulp-uglify',
  fileName: 'C:\\wamp\\www\\bouncetopia\\wp-content\\themes\\bouncetopia\\src\\js\\theme.min.js',
  showStack: false }
`

**Comment by 46John** [comment]
I don't believe understrap currently supports ES6. Can anyone confirm?

**Comment by 0dp** [comment]
You could try and upgrade gulp-uglify to a newer version and see if that helps

**Comment by Thomas-A-Reinert** [comment]
Problem should be solved right now with the latest commit. Please re-download and confirm.

**Comment by Thomas-A-Reinert** [comment]
Closing this isse because I´m SURE it is fixed ;)
But as always... reality bites :P
If the problem persists with the actual code, please re-open!
