### ISSUE TITLE
slow on woocomerce page

### ISSUE THREAD

**Issue by melt-cdk** [understrap/understrap#943]
Hello,
the woocomerce page (shop homepage) is very slowy than other page like a single product, cart and other. it's only this page, i don't understand why. 

I have disable all plugins but it's same.
If i use another theme, i haven't this problem.

tx

**Comment by 46John** [comment]
Could you please provide some additional information? How many products does your shop have? Have you made any changes to the default code for the shop page? If so, would you please share the changes you've made?

**Comment by melt-cdk** [comment]
The are 31 products on the shop and i used the theme raw for test (http://praticienshiatsu.melt-cdk.pw/boutique/).
tx

**Comment by pattonwebz** [comment]
Maybe this page has some queries that are slow to run. In the past I have used https://en-gb.wordpress.org/plugins/query-monitor/ on sites to help identify if there are any slow queries on a given page. It won't fix the root of the problem but if it's a query issue then maybe you could cache over it.

**Comment by holger1411** [comment]
<img width="1435" alt="Bildschirmfoto 2019-03-20 um 16 08 58" src="https://user-images.githubusercontent.com/1568158/54696027-55ff9180-4b2b-11e9-9ae4-3e4d2ceb6924.png">
Looks more like a host problem. Your server needs 8seconds before the answere came. The rest is just 1.28sec which seems to be okay.

**Comment by melt-cdk** [comment]
But why if i change theme my server needs 1.5 sec before the answere came ?

tx

**Comment by 0dp** [comment]
> But why if i change theme my server needs 1.5 sec before the answere came ?

Are you doing anything special in your woocommerce template override files in the theme or via functions files?

**Comment by melt-cdk** [comment]
No, it's just a basic installation of understrap.

**Comment by 0dp** [comment]
I am currently seeing response times that are much more reasonable:

1.5
2.3
1.3 

## Server Response Time (ms)
Lookup time:     0.004453
Connect time:   0.030287
Pre Xfer time:	  0.030327
Start Xfer time: 0.058337

**Comment by 46John** [comment]
Im still seeing insane server response time. This is likely just a result of shared hosting.
![Screen Shot 2019-03-20 at 3 04 34 PM](https://user-images.githubusercontent.com/36056675/54722391-a671f180-4b21-11e9-8634-8d0474b97c17.png)

**Comment by melt-cdk** [comment]
I just changed the theme by a standard twenty nineteen and it's more fast :( can You test Web performance ?

**Comment by 46John** [comment]
Load time is faster on that theme. Very strange. Total load time of 5.61s on twenty nineteen. If you haven't changed understrap at all I don't see how this would be the fault of the theme but maybe? It might be helpful if you could share your entire site repo with us.

![Screen Shot 2019-03-20 at 3 20 24 PM](https://user-images.githubusercontent.com/36056675/54723120-c4d8ec80-4b23-11e9-896d-9ab7455d3c39.png)

**Comment by melt-cdk** [comment]
OK i share a repo tomorow.
Tx

**Comment by holger1411** [comment]
Now I get a super fast loading time: 681ms (and yes, I cleand my cache before...) with UnderStrap.
Maybe it was a coincidence?

**Comment by holger1411** [comment]
I test it several times from different computers and in different Browsers.
Sometimes it is super fast 0.5 - 0.6, and sometimes super slow 8-10 seconds.
That seems to be a dns/host/server issue.

**Comment by 0dp** [comment]
Is this shared hosting you are on or a VPS. If it's a misconfigured Varnish cache or that you or the host is clearing it often, then responses can peak a lot since the cache has to be populated every time.

**Comment by melt-cdk** [comment]
Ok but only on shop page ?

this is github depot  : https://github.com/melt-cdk/understrap-debug

ok in few minutes

**Comment by melt-cdk** [comment]
Hello,
have a solution ?
I have this problem with a underscore base theme.

tx

**Comment by melt-cdk** [comment]
it's done.

Problem with thumbnail shop image function.

tx
