### ISSUE TITLE
Error: It's not clear which file to import for '@import "assets/bootstrap4"'

### ISSUE THREAD

**Issue by sdondley** [understrap/understrap#944]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] I need help

## Please tell us about your environment:

- Wordpress version   : 5.1.1
- npm version: 6.7.0
Gulp CLI version: 2.0.1
Gulp Local version 3.9.1
Sass version: Ruby Sass 3.7.3

---

## Steps to reproduce?
Clean install of understrap
`gulp watch`
modify sass/theme.scss and save
modify sass/theme.scss a second time
Get an error:

```
{ Error: sass/theme.scss
Error: It's not clear which file to import for '@import "assets/bootstrap4"'.
       Candidates:
         assets/bootstrap4.scss
         assets/bootstrap4.css
       Please delete or rename all but one of these files.
        on line 2 of sass/theme.scss
>> @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Ch
   ^

    at options.error (/usr/local/var/www/wp_sites/understrap/wp-content/themes/understrap/node_modules/node-sass/lib/index.js:291:26)
  status: 1,
  file:
   '/usr/local/var/www/wp_sites/understrap/wp-content/themes/understrap/sass/theme.scss',
  line: 2,
  column: 1,
  message:
   `sass/theme.scss\nError: It's not clear which file to import for '@import "assets/bootstrap4"'.\n       Candidates:\n         assets/bootstrap4.scss\n         assets/bootstrap4.css\n       Please delete or rename all but one of these files.\n        on line 2 of sass/theme.scss\n>> @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Ch\n   ^\n`,
  formatted:
   `Error: It's not clear which file to import for '@import "assets/bootstrap4"'.\n       Candidates:\n         assets/bootstrap4.scss\n         assets/bootstrap4.css\n       Please delete or rename all but one of these files.\n        on line 2 of sass/theme.scss\n>> @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Ch\n   ^\n`,
  messageFormatted:
   `\u001b[4msass/theme.scss\u001b[24m\nError: It's not clear which file to import for '@import "assets/bootstrap4"'.\n       Candidates:\n         assets/bootstrap4.scss\n         assets/bootstrap4.css\n       Please delete or rename all but one of these files.\n        on line 2 of sass/theme.scss\n>> @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Ch\n   ^\n`,
  messageOriginal:
   `It's not clear which file to import for '@import "assets/bootstrap4"'.\nCandidates:\n  assets/bootstrap4.scss\n  assets/bootstrap4.css\nPlease delete or rename all but one of these files.\n`,
  relativePath: 'sass/theme.scss',
  name: 'Error',
  stack:
   `Error: sass/theme.scss\nError: It's not clear which file to import for '@import "assets/bootstrap4"'.\n       Candidates:\n         assets/bootstrap4.scss\n         assets/bootstrap4.css\n       Please delete or rename all but one of these files.\n        on line 2 of sass/theme.scss\n>> @import "assets/bootstrap4";// <--------- Loads Bootstrap3 or Bootstrap4. Ch\n   ^\n\n    at options.error (/usr/local/var/www/wp_sites/understrap/wp-content/themes/understrap/node_modules/node-sass/lib/index.js:291:26)`,
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-sass',
  showProperties: true,
  showStack: false }
[16:42:16] Finished 'sass' after 11 ms
[16:42:16] Starting 'minifycss'...
[16:42:17] Finished 'minifycss' after 523 ms
[16:42:17] Finished 'styles' after 535 ms
```

## Expected behavior

No error.

### Other Comments

**Comment by 0dp** [comment]
Did you you npm install from the directory of the clean install before you ran gulp watch?

**Comment by 46John** [comment]
The issue is that you have a .css and a .scss with the same name in the same folder. Remove one or the other and ensure that you don't have a SASS plugin auto compiling them on save (in addition to gulp watch)

**Comment by 0dp** [comment]
> The issue is that you have a .css and a .scss

First time he saves a scss file it works because Ruby sass finds bootstrap4.scss but it also creates the file bootstrap4.css. that's why it freaks out the second time.

There should never be a bootstrap.css file in the assets folder.

That's what I read and it have frustrated many. That's why I suggest installing libsass cuz something is not adding up, but it's consistent with user reports on sass

**Comment by sdondley** [comment]
I uninstalled the sass gem and things appear to be working. There are no errors now and new css files are generated when I edit the sass/theme.scss. file.

But I'm not entirely sure. I'm new to sass/npm/gulp. As a quick test, I edited src/sass/bootstrap4/bootstrap.scss but it did not trigger gulp watch and no new css files were generated. It's not clear to me how this is supposed to work.

**Comment by sdondley** [comment]
OK, I'm just gonna guess editing files in src directory isn't supposed to happen.

**Comment by 0dp** [comment]
If you take a look at the gulp file you can see how everything is setup in regards to ./src
