### ISSUE TITLE
Chrome device toolbar, enabled iPad mode makes page cut out footer

### ISSUE THREAD

**Issue by e-tip** [understrap/understrap#945]
Please delete anything that does not apply for you!

## Issue is about..
  - [X ] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **OS Version:** MacOS 10.14 
  - **Browser:** Chrome 

---

# Issue Overview for Bugreports
Using the device toolbar in chrome and set view as iPad or iPad Pro makes the content viewport smaller than the content.
## Steps to reproduce?
Visit https://understrap.com/understrap/ with chrome and enable device toolbar. Set it as iPad and scroll until the footer. Some pieces of page is missing.

**Comment by IanDelMar** [comment]
Try setting the zoom to "fit to window" or auto-adjust. I also checked it on my iPad; everything's fine there.

**Comment by Thomas-A-Reinert** [comment]
I guess that one has been solved. Feel free to reopen if the probem persists.
