### ISSUE TITLE
Path issue in Enqueue.php

### ISSUE THREAD

**Issue by 1bigidea** [understrap/understrap#946]
## Issue is about..
  - [ X] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **OS Version:** MacOS [Mojave]
  - **Browser:** [ all ]
  - **Language:** [ PHP ]

---

# Issue Overview for Bugreports
The paths in inc/enqueue.php are inconsistent - it loads "theme.min.css" from the child theme (get_stylesheet_directory_uri()) after checking the filemtime of the file from the parent (get_template_directory()) - Understrap should be "unaware" of any child theme.
Line 22 of enqueue.php should be modified to use the same path as line 21

## Steps to reproduce?
Create a child theme for Understrap
Set it as active
Look at browser console

## *Who* is the bug affecting?
Any one with a child theme

## *What* is affected by this bug?
1) the theme.min.css is NOT loaded for the parent theme

## *When* does this occur?
On every page load

## *Where* on the platform does it happen?
all

## *How* do we replicate the issue?
create and set a child theme as active

## Expected behavior
No errors in the browser console

**Comment by Thomas-A-Reinert** [comment]
I´d personally ALWAYS go with loading the current themes path ( i.e. get_stylesheet_directory_uri instead of get_template_directory).

Can you tell EXPLICITELY in how far this is a problem?
