### ISSUE TITLE
Remove right sidebar from single product pages

### ISSUE THREAD

**Issue by chrisw03** [understrap/understrap#949]
Hi Everyone, 

I'm creating my first WooCommerce theme with Understrap and I am trying to remove the right sidebar from the single products pages. 

However, my limited knowledge of this is restricting my progress as I can't work out how to get this to work..

Can someone please give me an idea of how to accomplish this in simple terms?

Thanks in advance!

**Comment by Thomas-A-Reinert** [comment]
Hi @chrisw03 that noone took care about your problem prior to this.

The reason may be that this seems to be a generic WordPress / WooCommerce / Bootstrap problem that we can not help you with. 

Please understand that we cannot deliver support to any generic problem. So I´ll close this issue.

If you got any questions feel free to add up to.
