### ISSUE TITLE
Static Front Page / Custom Query with understrap_pagination()

### ISSUE THREAD

**Issue by zachatkinson** [understrap/understrap#951]
## Issue is about..

  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **OS Version:** MacOS 10.14.4 
  - **Browser:** Chrome 73.0.3683.103 (Official Build) (64-bit)
  - **Language:** PHP
  
---

# Issue Overview for Bugreports

Hi everyone. I recently started working on a new theme using understrap-child. This theme has a static front page. I created `front-page.php` and got things mainly displaying right. Because I'm using a static front page, I have to create a new `WP_Query` object to get all the posts, which is working fine and standard practice. The issue I'm running into is - `understrap_pagnation()` does not want to get along with my custom query.  I've tried a few things, including adding a paged option dynamically with `get_query_var()` to my array generated as suggested in the WP docs to no success. 

Has anyone else had luck getting `understrap_pagnation` to behave with a custom query on a static front page? I'm positive I'm overlooking something simple, but for the life of me, I can't seem to figure out what.

## Steps to reproduce?

- Create `front-page.php`
- Create a page in WordPress backend to be static front page
- Set static front page in WordPress Settings (Settings >> Reading >> Static Page You Created)
- Add a custom query to `front-page.php`
- Observe lack of pagination

## *Who* is the bug affecting?

Front end users who can't access pagination if a custom query is used.

## *What* is affected by this bug?

`understrap_pagination` and static frontpages/custom queries is my best guess.

## *When* does this occur?

When a developer or designer creates a static front page and uses a custom query to get posts.

## *Where* on the platform does it happen?

```
/inc/pagination.php
front-page.php
```

## *How* do we replicate the issue?

See steps to reproduce

## Expected behavior

`understrap_pagination` should work with custom queries, perhaps passed as an argument?

### Other Comments

I apologize in advance if this is something that does work and I'm too dense to find it. Any help is greatly appreciated! I've attached my `front-page.php` file for review.

[front-page.php.zip](https://github.com/understrap/understrap/files/3066715/front-page.php.zip)

**Comment by Thomas-A-Reinert** [comment]
Hey @zachatkinson did you have any success so far and could iron out the problem on you own?

However, as this seems to be child-theme-related, I´ll need to close that issue anyway. Please refer to the [Understrap-Child-theme issue tracker for any child-theme related issues](https://github.com/understrap/understrap-child).
