### ISSUE TITLE
Woocommerce (3.6.1) template updates in progress

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap#954]
Woocommerce template updates are underway for the latest version of Woocommerce (3.6.1).

Updates should be finished within the next 2-3 days.

## Issue is about..
  - [x ] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.1.1
  - **OS Version:** Linux Debian 9.8
  - **Browser:** All
  - **Language:** PHP
---

# Issue Overview for Bugreports

Outdated Woocommerce template updates.

From dashboard, run Woocommerce > Status to see any templates that are not at the required version.

## *Who* is the bug affecting?

All users with Woocommerce

**Comment by yamaks** [comment]
Hello, guys!
When is the template update expected?

**Comment by yamaks** [comment]
@noelspringer any news when it's possible to expect a template update?

**Comment by noelspringer** [comment]
@yamaks there is an open pull request here #955 .

**Comment by chrismb75** [comment]
@noelspringer Apologies to you, Noel. I have only just seen this issue. I should have checked here before making a PR. I had a client bugging me "his templates were broken" so jumped in and did it.

**Comment by noelspringer** [comment]
All good @chrismb75 . As long as it gets done :smile: .

**Comment by noelspringer** [comment]
Pull request from @chrismb75 #955 has been merged.
