### ISSUE TITLE
Woocommerce template single-product/rating.php

### ISSUE THREAD

**Issue by noelspringer** [understrap/understrap#956]
## Issue is about..

  - [ x ] a Question

The current UnderStrap version of `single-product/rating.php` is 3.1.0

When this file is compared with the same file from Woocommerce 3.1.0 the only difference is the text domain `understrap`.

Changing `understrap` back to `woocommerce` and doing a `diff` on that file against the Woocommerce 3.1.0 plugin version shows no difference, unless there is something else I am missing.

With the release of Woocommerce 3.6.0 this file has been updated. If there is no difference now between the UnderStrap and Woocommerce 3.1.0 versions, apart from the text domain, perhaps it could be removed altogether from UnderStrap and the latest Woocommerce plugin version would be used instead?

**Comment by chrismb75** [comment]
The only difference in 3.6 is just the text domain agin, nothing bootstrap related.

**Comment by Thomas-A-Reinert** [comment]
I am kinda confused - and it´s too late/complicated to follow up to the latest updates/branches of it.

HAS this issue been solved or not? Would like to close it, if possible.

**Comment by noelspringer** [comment]
Hi Thomas, the question/issue hasn't changed regardless of other updates.

Essentially there is no difference in the UnderStrap version of this file and the latest Woocommerce plugin version other than:

1. The text domain (changed from `woocomerce` to `understrap`)
2. The version number of the file - Understrap 3.6.1, Woocommerce 3.6.0.

In the spirit of keeping things DRY this file could be removed from Understrap since its functionality is provided by the Woocommerce template file.

If you like I could submit a pull request  with the file removed.

**Comment by Thomas-A-Reinert** [comment]
Thanks for keeping me posted, Noel!
If I got you right it would be easiest to just delete this file from the understrap repo?
If that is the case, please confirm, no need to submit a pull request as I can do that a bit more straight-forward. Don´t want to bother you with any unneccessary stuff... ;)

**Comment by noelspringer** [comment]
You're welcome.
Yes if that can be done it would be simpler :-) .

**Comment by Thomas-A-Reinert** [comment]
File deleted.
Please confirm - though this may seem silly.
I see different things than the "usual user does".

Just download the latest version and check the if the file _`./woocommerce/single-product/rating.php`_ is still there.

**Comment by noelspringer** [comment]
Hi Thomas. If I look at the master branch `woocommerce/single-product/` directory the file `rating.php` is still there. 

If I download the master branch zip file and check then as I expect from looking at the master branch the `rating.php` file is still present.

**Comment by Thomas-A-Reinert** [comment]
Sorry for the fuss, Noel. Seems I missed to commit a change note. Never did it that "brutal" way ;)
Should be deleted right now.

**Comment by noelspringer** [comment]
HI Thomas, all good now. Thanks!

**Comment by Thomas-A-Reinert** [comment]
Cool, thanks for the confirmation! Was not really used to the possibilities I got, so please bear with me.
