### ISSUE TITLE
How To Add External CSS Libraries

### ISSUE THREAD

**Issue by sayayinR** [understrap/understrap#957]
Please delete anything that does not apply for you!

## Issue is about..
  - [x ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** Windows 10
  - **Browser:**  all
  - **Language:** PHP

Hi, 
Not an issue, just need help. Can someone advise what is the most efficient way to add external CSS to the theme e.g I want to use Animate.css

Thank you!

**Comment by AlexandruFilipescu** [comment]
> Please delete anything that does not apply for you!
> 
> ## Issue is about..
> * [x ] I need help
> 
> ## Please tell us about your environment:
> * **WordPress Version:** 4.9.x
> * **OS Version:** Windows 10
> * **Browser:**  all
> * **Language:** PHP
> 
> Hi,
> Not an issue, just need help. Can someone advise what is the most efficient way to add external CSS to the theme e.g I want to use Animate.css
> 
> Thank you!
> 
> ### Other Comments

/**
 * Proper way to enqueue scripts and styles
 */
function wpdocs_theme_name_scripts() {
    wp_enqueue_style( 'style-name', get_stylesheet_uri() );
    wp_enqueue_script( 'script-name', get_template_directory_uri() . '/js/example.js', array(), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'wpdocs_theme_name_scripts' );


in functions php

**Comment by sayayinR** [comment]
Ohh ok thank you, I was thinking more in terms of may be adding it to a specific folder or import it and then it will be minified along with rest of the CSS.

**Comment by gaelgerard** [comment]
Yep you can do that too!
You need to import the file(s) in your child theme src directory.
Then you will have to declare them in the gulpfile.js for js or in your child-theme.scss for css.
Finally you will have to run the command 'gulp scripts' to add your js to the minified js or 'gulp watch' for the css.

**Comment by sayayinR** [comment]
When you say import into src directory you mean just copy the file there, correct?

**Comment by gaelgerard** [comment]
> 
> When you say import into src directory you mean just copy the file there, correct?

Yep, That's the way I do it 👍

**Comment by sayayinR** [comment]
I am actually not using a child theme, so I guess still copy file in the src folder? Also, not good with gulp, will you be kind enough to tell me what I have to change in there?

**Comment by sayayinR** [comment]
I see this in gulpconfig.json

`  "paths" : {
    "js": "./js",
    "css": "./css",
    "img": "./img",
    "imgsrc": "./src/img",
    "sass": "./sass",
    "node": "./node_modules/",
    "bower": "./bower_components/",
    "dev": "./src",
    "dist": "./dist",
    "distprod": "./dist-product",
    "vendor": ""
  }
}`

and in gulpfile.js:

`// Compiles SCSS files in CSS
gulp.task( 'sass', function() {
    var stream = gulp.src( paths.sass + '/*.scss' )
        .pipe( plumber( {
            errorHandler: function( err ) {
                console.log( err );
                this.emit( 'end' );
            }
        } ) )
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe( sass( { errLogToConsole: true } ) )
        .pipe( autoprefixer( 'last 2 versions' ) )
        .pipe(sourcemaps.write(undefined, { sourceRoot: null }))
        .pipe( gulp.dest( paths.css ) )
    return stream;
});`

So I saved the CSS as a .scss file and copied to ./sass folder, ran gulp watch and it did not work. What am I doing wrong?

**Comment by sayayinR** [comment]
I got it working by copying the file to sass folder on root of the theme and then importing in theme.scss in that folder'

`@import "libraries/animate"; // Animate.css`

Not 100% sure if this is the right way, so please someone confirm if I am overlooking anything here.

Thank you!

**Comment by gaelgerard** [comment]
Yep it's the right way for css But be carefull now you are not using a child theme you won't be able to update Understrap without losing your modifications in the file theme.scss.

**Comment by sayayinR** [comment]
Thanks, yes I'm aware of the consequences. I needed more changes than just CSS so I went that route.
