### ISSUE TITLE
Best way to integrate a single 1 page website

### ISSUE THREAD

**Issue by AlexandruFilipescu** [understrap/understrap#958]
## Issue is about..

  - [ ] a Question

## Please tell us about your environment:
  - **WordPress Version:** 5.1.1
  - **OS Version:** Windows 10] 

So if I have an already built a one page website with bootstrap 4, what should I modify in understrap?
only the index.php or also the header, footer? I just need the proper way to use this starter template, thanks.

**Comment by gaelgerard** [comment]
Not only for understrap but on most of wp themes, the proper way is first to use a child theme.

Then you may modify each file separately to keep all functionnalities working. header, footer but also any included file with get_template_part.

**Comment by AlexandruFilipescu** [comment]
> Not only for understrap but on most of wp themes, the proper way is first to use a child theme.
> 
> Then you may modify each file separately to keep all functionnalities working. header, footer but also any included file with get_template_part.

Thank you, what i am doing for now is modifying and editing an understrap theme, I hope it is still a good idea.

**Comment by gaelgerard** [comment]
> Thank you, what i am doing for now is modifying and editing an understrap theme, I hope it is still a good idea.

Be carefull then because updating the theme in the future will erase all your customizations

**Comment by AlexandruFilipescu** [comment]
> > Thank you, what i am doing for now is modifying and editing an understrap theme, I hope it is still a good idea.
> 
> Be carefull then because updating the theme in the future will erase all your customizations

Thanks for the suggestion, but what template or theme would you use to implement an already made html css jquery website in Wp, are there any other great tools? someone told me that Twenty ten Is a good idea.

**Comment by AlexandruFilipescu** [comment]
> > Thank you, what i am doing for now is modifying and editing an understrap theme, I hope it is still a good idea.
> 
> Be carefull then because updating the theme in the future will erase all your customizations

I mean understrap seems pretty heavy and bulky I guess.

**Comment by Thomas-A-Reinert** [comment]
@AlexandruFilipescu Sorry, don´t mean to be rude, but I sense a certain lack of knowledge of general WordPress principles, right? 

A One-Pager  can SO easily be done - in case you just want to list posts. Or pages or whatever. In case you want to mingle them, maybe also with custom post types, everything gets a little more complicated. Agreed.

Anyway, in case you´re not really comfy with WordPress yet, well yes, thats maybe not the best way to go. I´d recommend setting up a simple static site instead. 

In case anyone told you that Twenty-Ten would be the best use-case (which I´d really question!), I´d recommend playing around with that, which will give you a good overview of how WordPress really works. It may be better documented etc.

Well, understrap is in no way "bulky" - please consider that i´m not really un-opinionated as i´m part of the team. But it´s really pretty bare-bone with just the "Bootstrap"-overhead, in case you really need it. If you don´t actually need Bootstrap, yeap, it IS bulky.

According to my expercience it´s one of the fastest/performance-lightest themes available. 

Feel free to answer or reopen, but I´m going to close this topic as it´s really not an ISSUE to understrap.

**Comment by Thomas-A-Reinert** [comment]
Question in general is: Why do you NEED to grab your data from a WordPress site instead just of static codec data? The latter would be more secure, faster and have a lot more benefits if you just don´t NEED to grab dynamic data (from e.g. a WordPress site)..
