### ISSUE TITLE
Calling woocommerce_form_field for checkbox results in a hidden checkbox

### ISSUE THREAD

**Issue by pumka** [understrap/understrap#964]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.1.x
  - **Browser:** all

---

# Issue Overview for Bugreports

## Steps to reproduce?
Add this code to any template:
```php
<?php woocommerce_form_field( 'test_checkbox',
    array(
        'type' => 'checkbox',
        'label' => 'Test',
    )
) ?>
```
Open a page rendered by the template.

## *Who* is the bug affecting?
End user

## *What* is affected by this bug?
Custom fields added to checkout, etc

## *When* does this occur?
When a checkbox field is added to any WooCommerce field. We noticed the issue when enabled WooCommerce compatibility in GDPR Framework plugin, which added a consent checkbox to checkout form.

## *Where* on the platform does it happen?
understrap_wc_form_field_args function at inc/woocommerce.php:125 add custom-* Bootstrap classes that hide regular checkbox but do not show custom one

## *How* do we replicate the issue?
Call woocommerce_form_field function for a checkbox from any template or add a checkbox field to a WooCommerce form.

## Are there any related Issues and/or PRs?
Looks like radio buttons could be affected as well.

## Screenshots / Video
This is how checkbox fields look like:
![image](https://user-images.githubusercontent.com/6209242/56956040-af57d900-6b4b-11e9-9cea-17aa60a607b2.png)
![image](https://user-images.githubusercontent.com/6209242/56956113-e3cb9500-6b4b-11e9-9a8b-bc97c501aff0.png)

## Expected behavior
Correctly shown checkbox either using regular or custom styles:
![image](https://user-images.githubusercontent.com/6209242/56956275-5c325600-6b4c-11e9-99a1-0243aa51847c.png)

### Other Comments
Looks like understrap_wc_form_field_args function is intended to apply "custom-*" Bootstrap classes to WooCommerce fields but the resulting HTML markup for checkout is not the same as required by Bootstrap.

Markup generated:
```html
<p class="form-row " id="test_checkbox_field" data-priority="">
    <span class="woocommerce-input-wrapper">
        <label class="checkbox custom-control custom-checkbox">
            <input type="checkbox" class="input-checkbox custom-control-input input-lg" name="test_checkbox" id="test_checkbox" value="1"> Test&nbsp;<span class="optional">(optional)</span>
      </label>
    </span>
</p>
``` 

Markup suggested by Bootstrap 4 docs (https://getbootstrap.com/docs/4.1/components/forms/#custom-forms):
```html
<div class="custom-control custom-checkbox">
    <input type="checkbox" class="custom-control-input" id="customCheck1">
    <label class="custom-control-label" for="customCheck1">Check this custom checkbox</label>
</div>
```

However, for Bootstrap the order and nesting of tag is important. For example, this rule at _custom-forms.scss:22 assumes that label tag goes after the input and wouldn't work for input inside label like WooCommerce generates it:
```css
.custom-control-input {
  position: absolute;
  z-index: -1; // Put the input behind the label so it doesn't overlay text
  opacity: 0;

  &:checked ~ .custom-control-label::before {
    color: $custom-control-indicator-checked-color;
    @include gradient-bg($custom-control-indicator-checked-bg);
    @include box-shadow($custom-control-indicator-checked-box-shadow);
  }
...
```

As a temporary solution I overrode understrap_wc_form_field_args function in my child theme and commented out custom classes for checkbox:
```php
        case 'checkbox':
            //$args['label_class'] = array( 'custom-control custom-checkbox' );
            //$args['input_class'] = array( 'custom-control-input', 'input-lg' );
            break;
```

Either the theme could do the same to leave checkboxes (and possibly radio buttons ) with regular styles or implement "woocommerce_form_field_checkbox" filter to completely rewrite checkbox and radio field HTML up to Bootstrap expectations.

**Comment by Thomas-A-Reinert** [comment]
Hi @pumka - sorry that so far noone replied to your issue.

Has this issue so far been ironed out by the stock-installation?

@understrap/woocommerce-team would you please take a peep into this? @GuerrillaCoder @ZacharyElkins @typeplus ?!

**Comment by pumka** [comment]
> Has this issue so far been ironed out by the stock-installation?

Sorry, not sure what "stock-installation" means in this context. Could you please explain?
I'm using the workaround so far.

**Comment by Thomas-A-Reinert** [comment]
Sorry, pumka - I just wanted to know if the above mentioned problem has been fixed with the current codebase that can be downloaded/cloned from this repo. Or if the workaround is still needed.

**Comment by pumka** [comment]
Ah, OK! I will check next week and let you know.

**Comment by GuerrillaCoder** [comment]
Sorry I am slammed with work ATM, will be at least a week at least before I can put my head above ground.  I can push a fix then if no one else has taken it.

**Comment by pumka** [comment]
OK, I checked with the latest code from the repository and it didn't fix the issue.
