### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by zakirsajib** [understrap/understrap#966]
## Issue is about..
  - [ ] a Bug Report

Missing customizer.js in js directory!

**Comment by 0dp** [comment]
@zakirsajib @holger1411 have this been resorted?

**Comment by Thomas-A-Reinert** [comment]
Commit concerning the issue was released, no feedback from the original poster followed up, so I´ll close this issue.

If the problem persists, please feel free to re-open this issue @zakirsajib
