### ISSUE TITLE
woocommerce single product page is not using woocommerce template after updating

### ISSUE THREAD

**Issue by jpmorandesign** [understrap/understrap#972]
After updating Understrap to the most current version, my Woocommerce product pages have begun to use the single post type template and are showing author, date, and comments on product pages.

here is an example https://brettcards4less.com/product/brett-2019-commemorative-christmas-card/

**Comment by Thomas-A-Reinert** [comment]
SHOULD be solved with the latest merge request which the current owner of UnderStrap still gotta submit. Closing this issue for housekeeping as he promised to merge anything until THIS friday. If the problem remains, please feel free to re-open that issue.
