### ISSUE TITLE
Add rel="noopener" to target="_blank" links by default in bootstrap-navwalker

### ISSUE THREAD

**Issue by LukaszJaro** [understrap/understrap#973]
- a Suggestion

WordPress core recently added this to the navwalker:
https://core.trac.wordpress.org/ticket/43290

Without adding these attributes google audit flags as a security risk, suggested change for class-wp-bootsrap-navwalker.php:

`//$atts['rel']    = ! empty( $item->xfn ) ? $item->xfn : '';

			if ( '_blank' === $item->target && empty( $item->xfn ) ) {
				$atts['rel'] = 'noopener noreferrer';
			} else {
				$atts['rel'] = $item->xfn;
			}`

**Comment by 0dp** [comment]
@understrap/accessibility-quality

**Comment by Thomas-A-Reinert** [comment]
Thanks @LukaszJaro !
