### ISSUE TITLE
How should I remove filter ‘understrap_all_excerpts_get_more_link’ using a child theme?

### ISSUE THREAD

**Issue by nmenescardi** [understrap/understrap#975]
Hi,

I’m using Understrap with a child theme. The markup added in the following hook is breaking the excerpt in a block so I need to get rid of it. The hook is:
https://github.com/understrap/understrap/blob/577eea7f47aeef222062b3bcea70718058acab87/inc/setup.php#L123

I tried adding a `remove_filter` in the `functions.php` of the child theme but it didn’t work. So, right now the filter, in the parent theme, it’s commented out but it’s not a good practice.

How should I remove that filter?

Thanks!

**Comment by pattonwebz** [comment]
Hey @nmenescardi,

You should be able to unhook this so long as you unhook after it's registered but before it's fired (on same priority which is default of 10).

`remove_filter( 'wp_trim_excerpt', 'understrap_all_excerpts_get_more_link' );` I think this should work but your saying it does not?

If that doesn't work the function it hooks is overloadable so you could add this to your child theme to prevent it's behaviour:

	/**
	 * Overrides the parent themes function.
	 *
	 * @param string $post_excerpt Posts's excerpt.
	 *
	 * @return string
	 */
	function understrap_all_excerpts_get_more_link( $post_excerpt ) {
		return $post_excerpt;
	}

This is just a function that receives and then returns the `$post_excerpt` without processing - so it results in default core behaviour.

**Comment by nmenescardi** [comment]
@pattonwebz overriding the function worked. Thank you so much!
