### ISSUE TITLE
Woocommerce 3.6.3 Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by jpmorandesign** [understrap/understrap#976]
- [X] a Bug Report
  - **WordPress Version:** 5.2
       WooCommerce 3.6.3 update

Upon updating to WoCommerce 3.6.3 I got the following error message and WooCommerce was deactivated

**Plugin could not be activated because it triggered a fatal error.**
Fatal error: Cannot redeclare wc_reviews_enabled() (previously declared in /nas/content/live/bc4less/wp-content/themes/understrap/inc/woocommerce.php:151) in /nas/content/live/bc4less/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php on line 430
![Screen Shot 1](https://user-images.githubusercontent.com/17971314/57960874-844de300-78c8-11e9-8dfa-6b60746d8a6e.png)

**Comment by IanDelMar** [comment]
#961

**Comment by Thomas-A-Reinert** [comment]
Is this fixed? Realibly and confirmed? Would like to close the issue if it´s in the _official / released_ codebase.

**Comment by jpmorandesign** [comment]
I have updated the file and WooCommerce wasn't automatically disabled, so I think it is resolved

**Comment by Thomas-A-Reinert** [comment]
Thanks for your feedback, @jpmorandesign ! Appreciated!
