### ISSUE TITLE
Cant install or update via npm

### ISSUE THREAD

**Issue by felix-berlin** [understrap/understrap#978]
## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [x] I need help

## Please tell us about your environment:

  - **OS Version:** [Windows 10]
  - **Node.js & NPM Versions:** Node.js [V 10.12.0] | NPM [V 6.90]

---
I tryed to install understrap via npm and i got this output.

## Console Output

PS D:\under> npm install understrap

> node-sass@4.12.0 install D:\under\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\XXX\AppData\Roaming\npm-cache\node-sass\4.12.0\win32-x64-64_binding.node

> node-sass@4.12.0 postinstall D:\under\node_modules\node-sass
> node scripts/build.js

Binary found at D:\under\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> gifsicle@4.0.1 postinstall D:\under\node_modules\gifsicle
> node lib/install.js

  √ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall D:\under\node_modules\jpegtran-bin
> node lib/install.js

  √ jpegtran pre-build test passed successfully

> optipng-bin@5.1.0 postinstall D:\under\node_modules\optipng-bin
> node lib/install.js

  √ optipng pre-build test passed successfully

> understrap@0.9.3 postinstall D:\under\node_modules\understrap
> gulp copy-assets

internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'gulp-babel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\under\node_modules\understrap\gulpfile.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
npm WARN enoent ENOENT: no such file or directory, open 'D:\under\package.json'
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN under No description
npm WARN under No repository field.
npm WARN under No README data
npm WARN under No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2019-05-21T08_43_18_587Z-debug.log

**Comment by SvenGeorge** [comment]
same here

**Comment by SvenGeorge** [comment]
Even if I run `npm install --save-dev understrap` (where the missing gulp deps are defined, i'll get an unhandled error.

`> gulp copy-assets

[15:54:55] Using gulpfile ~\test\test\node_modules\understrap\gulpfile.js
[15:54:55] Starting 'copy-assets'...
[15:54:55] Finished 'copy-assets' after 24 ms
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: File not found with singular glob: XXX/test/test/node_modules/understrap/node_modules/undescores-for-npm/js/skip-link-focus-fix.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (XXX\test\test\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:277:13)
    at Glob.emit (events.js:189:13)
    at Glob.EventEmitter.emit (domain.js:441:20)
    at Glob._finish (XXX\test\test\node_modules\glob\glob.js:197:8)
    at done (XXX\test\test\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (XXX\test\test\node_modules\glob\glob.js:688:12)
    at XXX\test\test\node_modules\glob\glob.js:676:10
    at Glob._stat2 (XXX\test\test\node_modules\glob\glob.js:772:12)
    at lstatcb_ (XXX\test\test\node_modules\glob\glob.js:764:12)
Emitted 'error' event at:
    at DestroyableTransform.EventEmitter.emit (domain.js:454:12)
    at Pumpify.emit (events.js:189:13)
    at Pumpify.EventEmitter.emit (domain.js:441:20)
    at Pumpify.Duplexify._destroy (XXX\test\test\node_modules\duplexify\index.js:191:15)
    at XXX\test\test\node_modules\duplexify\index.js:182:10
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by ericlammel** [comment]
I believe this error occurs because npm have some issues when are downloading dependencies. Delete the /node_modules directory and reinstall all dependencies again with `npm install`.

**Comment by jamiedoherty** [comment]
@ericlammel no such luck.  This happens on a brand new fresh install in an empty directory.

**Comment by 0dp** [comment]
Instead of trying to install the theme with npm. Have you tried downloading the latest version of understrap into your themes folder and execute `npm install` from within the understrap theme folder?

Per say, you can't really install understrap with `npm install understrap` even if its mentioned in the documentation.

#980

**Comment by felix-berlin** [comment]
@0dp when i download the last release and execute npm install it worked.

But npm install understrap in a brand new folder still does not work. The same by npm update in an existing project.

**Comment by extamus** [comment]
Here to echo the same issues. I'm on a mac, and even a fresh install isn't functioning correctly with 0.9.3.

**Comment by 0dp** [comment]
@extamus, that sounds like a completely different issue.
Please open a new issue and provide your own report.

@felix-berlin
As I said, npm is not supposed to work like that.
Npm is for dependency management, not theme installation or update.

**Comment by jamiedoherty** [comment]
@0dp I'm using the Understrap child theme and ideally would like to set the parent theme as a dependency on initial install.  npm install understrap works for version 0.9.1.  If there is no plan to continue to support this, the documentation should be updated.

**Comment by 0dp** [comment]
Npm install understrap will install the parent theme as a dependency, and it will work just fine even if post installation or other dependencies fail.

@jamiedoherty please post your install log

**Comment by 0dp** [comment]
@jamiedoherty 

v. 0.9.1 worked fine

v. 0.9.3 also worked fine
```
npm install understrap

> understrap@0.8.9 postinstall /Users/odp/Desktop/node_modules/understrap
> gulp copyAssets

[00:36:21] Requiring external module @babel/register
[00:36:23] Using gulpfile ~/Desktop/understrap/gulpfile.babel.js
[00:36:23] Starting 'copyAssets'...
[00:36:23] Finished 'copyAssets' after 17 ms
npm WARN saveError ENOENT: no such file or directory, open '/Users/odp/Desktop/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/odp/Desktop/package.json'
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.

+ understrap@0.8.9
updated 1 package and audited 96 packages in 8.224s
found 0 vulnerabilities

```

@felix-berlin 
Your error say's Error: `Cannot find module 'gulp-babel'` we need to investigate why gulp-babel was not installed in your end.

**Comment by 0dp** [comment]
Installing a package with npm, adds it as a project dependency.
That means it will ignore the devDependencies listed in the package `package.json`
Since the devDependencies are needed to run the gulp tasks, it all fails.

A quick fix would be to move all the devDependiences up into the package.json dependencies.

> I'm using the Understrap child theme and ideally would like to set the parent theme as a dependency on initial install. 

This happens by default, but the child-theme is not up to date with the new gulp4 setup, so you will probably have to install the missing parent themes dev dependencies manually before executing npm install. Just as a temporary fix

For now my recommendation is to download the themes manually and execute npm install from within the directory.

@understrap/child-theme-team 
@understrap/accessibility-quality 
@KenEucker

**Comment by Thomas-A-Reinert** [comment]
I agree to @0dp - understrap at it´s current status is NOT meant to be _INSTALLED_ via NPM. I cannot even say if it´s packages are currently updated - but it seems as if not. We´ll dig into that as soon as some other things are ironed out.

Even if I´m not personally "responsible" for the issues involved, I really feel sorry for any inconveniences and totally understand you, the community, worrying.

I can´t even say why the npm package is still getting released. We´ll iron out that issue too.

The recommended way using understrap at the current time is to _download_ or _clone_  the repo, rename it to _understrap_ instead of _understrap-master_ and do an `npm install` in that dir. I know - and feel sorry about it! - that the docs actually suck a lot and do not reflect the current state. We´re working on that.

Cannot / will not say more about that, but hopefully things are going to change soon. :)

Sidenote: Alle deutschen Anwender können mich auch gerne direkt kontaktieren. Ich versuche gerne, zeitnah weiter zu helfen.

**Comment by axlright** [comment]
I'm not a npm ninja but I can say I do not start new projects from npm. I essentially go the route of cloning the parent and child themes. 

What my team actually does is have an install on a WP Engine server that I keep up-to-date along with a bunch of starter customizations and starter plugins and Advanced Custom Fields starter setups and Custom Post Types and whatnot, then I clone this into a new WP Engine install, further customize per the client's needs then export the whole thing - code and database - to my local environment and all my developers' local environments **then** we all run `npm install` locally, ignore `node_modules` and push back to a new common GitHub repo. Works like a charm.

This is a long winded way of saying I don't use or have much knowledge of installing parent and child themes via npm, and I see a much better route of cloning actual WordPress installs as it makes it possible to start off with both an updated set of parent and child themes **and** common plugins and other setups.

**Comment by axlright** [comment]
I'm getting a similar issue related to `Cannot find module 'gulp-babel'` when updating an existing project.

I've updated the parent understrap to 0.9.3 and am in the process of updating the child to 0.5.5 and I get 

```
> understrap@0.9.3 postinstall /Users/alexwright/Sites/XXX/web/wp-content/themes/XXX/node_modules/understrap
> gulp copy-assets

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'gulp-babel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/alexwright/Sites/sneed-vine/web/wp-content/themes/sneed-vine/node_modules/understrap/gulpfile.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: `gulp copy-assets`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexwright/.npm/_logs/2019-06-14T19_39_52_311Z-debug.log
```
`node_modules` doesn't have an `understrap` directory

If I change the dependencies in the child theme `package.json` from `"understrap": "^0.9.1",` to `    "understrap": "0.9.1",` it works fine and the `understrap` directory loads in the `node_modeles` directory. but `"understrap": "^0.9.1",` and `"understrap": "0.9.2",` and `"understrap": "0.9.3",` don't work.

**Comment by 0dp** [comment]
@axlright
You can always fix it by manually installing the missing deps.

But I would say the best fix would be to remove the understrap npm dependency all together from the project. I don't see the meaning of having itself as a dependency.

Instead we could consider introducing the npm version as a npx package. That would make sense to me

**Comment by Thomas-A-Reinert** [comment]
@0dp , @axlright , @holger1411 - you´re keeping this issue on your radar?!

I´m going to close this issue, because due to https://github.com/understrap/understrap/issues/978#issuecomment-496989264 it has - kinda - been resolved.

**Comment by shikkaba** [comment]
@Thomas-A-Reinert Not really sure why this is closed if it isn't fixed. This still happens. Just had it happen now. Manually installing the files isn't the same as using npm, even if it does the same thing pretty much. If that is considered a fix, then the npm installation should be removed from the docs as having it there makes people assume that this works.

**Comment by IanDelMar** [comment]
@shikkaba which version of UnderStrap are you using?

**Comment by shikkaba** [comment]
@IanDelMar `npm install understrap` uses 0.9.3 still from the looks of it.

Using the manual files worked fine, but trying to use npm to get the files throws similar error to what the original poster had, hence not opening a new issue.

```
Error: Cannot find module 'gulp-babel'
Require stack:
- /Users/lisacerilli/node_modules/understrap/gulpfile.js
- /Users/lisacerilli/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
- /Users/lisacerilli/node_modules/gulp/node_modules/gulp-cli/index.js
- /Users/lisacerilli/node_modules/gulp/bin/gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/lisacerilli/node_modules/understrap/gulpfile.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lisacerilli/node_modules/understrap/gulpfile.js',
    '/Users/lisacerilli/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
    '/Users/lisacerilli/node_modules/gulp/node_modules/gulp-cli/index.js',
    '/Users/lisacerilli/node_modules/gulp/bin/gulp.js'
  ]
}
npm WARN enoent ENOENT: no such file or directory, open '/Users/lisacerilli/package.json'
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.
npm WARN lisacerilli No description
npm WARN lisacerilli No repository field.
npm WARN lisacerilli No README data
npm WARN lisacerilli No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap@0.9.3 postinstall: 'gulp copy-assets'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the understrap@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lisacerilli/.npm/_logs/2020-05-05T18_08_26_277Z-debug.log
```

**Comment by felix-berlin** [comment]
Hey @shikkaba since this problem i am using understrap 0.9.1. This works fine for me.

**Comment by shikkaba** [comment]
@felix-berlin how do you install the newest version with `npm install understrap`? It's not in the documentation. Installing manually is fine, but that wasn't your original issue. The issue you had before was with installing directly through npm.

**Comment by felix-berlin** [comment]
I dont use the newest version. My original problem was to update the parent theme.

Iam using the understrap child theme and the understrap parent theme as dependency. In my packages.json i wrote `"understrap": "0.9.1"`.

**Comment by shikkaba** [comment]
@felix-berlin  Ah, but I'm referring to what you had originally pointed out in [this comment](https://github.com/understrap/understrap/issues/978#issuecomment-496989264) as this is what I tried, and that it still doesn't work but is in the documentation as an installation option.

**Comment by yushanwebdev** [comment]
@felix-berlin still getting an error like this even I wrote `"understrap": "0.9.1"`

> `npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
> npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> 
> > understrap@0.9.1 postinstall C:\xampp\htdocs\lymited\lym\wp\wp-content\themes\lymited-child\node_modules\understrap
> > gulp copy-assets
> 
> fs.js:36
> } = primordials;
>     ^
> 
> ReferenceError: primordials is not defined
>     at fs.js:36:5
>     at req_ (C:\xampp\htdocs\lymited\lym\wp\wp-content\themes\lymited-child\node_modules\natives\index.js:143:24)
>     at Object.req [as require] (C:\xampp\htdocs\lymited\lym\wp\wp-content\themes\lymited-child\node_modules\natives\index.js:55:10)
>     at Object.<anonymous> (C:\xampp\htdocs\lymited\lym\wp\wp-content\themes\lymited-child\node_modules\understrap\node_modules\graceful-fs\fs.js:1:37)
>     at Module._compile (internal/modules/cjs/loader.js:1015:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
>     at Module.load (internal/modules/cjs/loader.js:879:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
>     at Module.require (internal/modules/cjs/loader.js:903:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\glob-watcher\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})    
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})     
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\gulp-watch\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})    
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! understrap@0.9.1 postinstall: `gulp copy-assets`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the understrap@0.9.1 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by felix-berlin** [comment]
@yushanwebdev witch node js version do you use?
