### ISSUE TITLE
win32-x64-64_binding.node not found

### ISSUE THREAD

**Issue by Javier-Esteban** [understrap/understrap#980]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.5
  - **OS Version:**  Windows 10
  - **Language:**  PHP 
  - **Node.js & NPM Versions:** Node.js [v10.15.3] | NPM [6.4.1]

### Other Comments
When I try t oexecute:
 npm install understrap
I get a lot of errors, the first one is:

> node-sass@4.7.2 install C:\wamp64\www\openmind\wp-content\themes\openmind\node_modules\node-sass

> node scripts/install.js

 

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node

Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

I can see in the section "releases" that actually win32-x64-64_binding.node does not exist.

**Comment by 0dp** [comment]
Instead of trying to install the theme with npm. Have you tried downloading the latest version of understrap into your themes folder and execute `npm install` from within the understrap theme folder?

Per say, you can't really install understrap with `npm install understrap` even if its mentioned in the documentation.

**Comment by Thomas-A-Reinert** [comment]
Well, according documentation.. 
We almost had most of it complete. But to me it doesn´t seem as it was ever going to be included/referenced or whatever by the project maintainer. Correct me, if I´m wrong.

**Comment by Thomas-A-Reinert** [comment]
No Feedback received to a question within (nearly) a fortnight.
Closing this issue though due to housekeeping.
