### ISSUE TITLE
using gulp dist-product

### ISSUE THREAD

**Issue by redknite** [understrap/understrap#982]
## Issue is about..
  - [x] a Question
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.1
  - **OS Version:** Linux [Distribution / Version] 
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

this is in relation to this issue I reviewed:  https://github.com/understrap/understrap/issues/417

I believe I have my development setup properly.

I am running understrap and a child theme on a local dev. Everything is going great. I have my node watching my child theme directory and everything seems to be working.

I am ready to go live and was considering what actually needed to be copied to the live server.

The issue link mentioned above stated gulp dist-product should provide the correct folder with the correct contents.

When I run this command it does create the right directory, but the dist-product directory includes sass and node_modules directories.  Obviously it doesn't include the original understrap directory either.

I don't see in the documentation what exactly I'm supposed to do at this point.

**Comment by 0dp** [comment]
You say you are working on a child theme?
In that case you should probably have posted in the child theme repo.

Anyways, try execute `gulp dist` instead of `gulp dist-product`

This should compile all files into the dist folder ready to publish

**Comment by axlright** [comment]
Yes to what @0dp said about posting in the child theme repo if you're using a child theme.

I just copy everything in the child and parent theme directories except `node-modules`. We use git push to the server, so this is easy with a .gitignore` in the parent and child theme directories. But regardless, it's nice to have a working copy of everything in case your local has some kind of meltdown. Copying all files doesn't take much space as long as you exclude `node-modules`. You don't *need* to use `gulp dist` or gulp dist-product` - you can just copy filed directly to the server if you want.

**Comment by 0dp** [comment]
What alex said, you can just copy everything except node_modules. EASY 😸

**Comment by redknite** [comment]
thanks guys I really appreciate the help..  I didn't see a repo for the base child theme.  Did I miss it?

**Comment by 0dp** [comment]
https://github.com/understrap/understrap-child
