### ISSUE TITLE
Error during activate WooCommerce 

### ISSUE THREAD

**Issue by awezobli** [understrap/understrap#983]
Please delete anything that does not apply for you!

## Issue is about..
  - [x] a Bug Report
  - [ ] a Feature Request
  - [ ] a Suggestion
  - [ ] a Question
  - [ ] I need help

## Please tell us about your environment:

  - **WordPress Version:** 4.9.x
  - **OS Version:** [Windows 7 | Windows 8 | Windows 10] | Linux [Distribution / Version] | MacOS [Version] | Android [Version] | iOS [Version]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [ all | PHP | SQL | HTML | S/CSS | Javascript | jQuery | ES6 | JSON | XML]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports

## Expected behavior

# Todos

 * Test
 * Documentation

**Comment by awezobli** [comment]
WordPress Version: 5.2.1
WooCommerce: 3.6.3 (or 3.7.0-dev)
Understrap: 0.9.3
No other active plugins

I can't activate WooCommerce. After activate I see this error:

Fatal error: Cannot redeclare wc_review_ratings_enabled() (previously declared in /home/[******]/wp-content/themes/understrap/inc/woocommerce.php:172) in /home/globalmedia/websites/dev1.htm.pl/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php on line 439

Would you help?

**Comment by IanDelMar** [comment]
See #977
