### ISSUE TITLE
Active position in menu

### ISSUE THREAD

**Issue by webstoria** [understrap/understrap#984]
I can't find active class in menu. So I want to change color and give border into active class in css, but I really don't know how to find active class

I was trying with .nav-link> .active>a { border 1 px solid; } and nothing

**Comment by axlright** [comment]
@webstoria you can inspect elements to see how active classes are applied by the navwalker. It's all there.

To test, you can set custom variables for `$navbar-light-active-color` or `$navbar-dark-active-color` depending on whether you're using `.navbar-light` or `.navbar-dark` and see it working.

If you want more customization, you can do that in your Sass styles. For this kind of thing, I look to how Bootstrap sets classes in their Sass for guidance. You can see their setup in `_navbar.scss` around lines 220 and 276.

This isn't a broken issue with the theme.

**Comment by webstoria** [comment]
Thx a lot I've just looking for this :
.show > .nav-link,
.active > .nav-link,
.nav-link.show,
.nav-link.active
