### ISSUE TITLE
ES6 / Babel don't seem to work in custom-javascript.js

### ISSUE THREAD

**Issue by jweston491** [understrap/understrap#987]
## Issue is about..
  - [x] a Bug Report
  - [x] I need help

## Please tell us about your environment:

  - **WordPress Version:** 5.2.1
  - **OS Version:** MacOS 10.14.5
---

# Issue Overview for Bugreports

## Steps to reproduce?

- Create `custom-javascript.js` file in `src/js`, run `gulp scripts`
- Compiler doesn't recognize ES6 code. 

https://github.com/understrap/understrap/commit/b179eaffe4fea988c881e8c182c4b16032d43b39 seems to indicate Babel was added to the `package.json` and `gulpfile.js`, but I'm unclear if further configuration steps are needed to do transpile.

**Comment by 0dp** [comment]
Could you maybe include an example of a script that won't compile and errors you are getting?

**Comment by jweston491** [comment]
Sure thing. Here's what I did to recreate the steps: 

1. Create new local WP install (I'm using Local by Flywheel, MacOS 10.14.5 and WP 5.2.1)
2. `git clone https://github.com/understrap/understrap`
     `cd understrap`
      `npm install`
3. Create `custom-javascript.js` in `src/js/`
4. Add the following code:
```
const dropdowns = document.getElementsByClassName('dropdown-toggle');

for (let dropdown of [...dropdowns]) {
  dropdown.addEventListener('click', (e) => {
      e.preventDefault();
      e.stopPropagation();
      e.target.closest('a.nav-link').classList.toggle('show');
  })
}
```
I verified the above code compiles in https://babeljs.io/repl

5. Run `gulp scripts`
6. Get Error:
```
Starting 'scripts'...
[08:28:39] 'scripts' errored after 1.94 s
[08:28:39] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword «const»
File: /Users/myUser/Local Sites/understrap-test/app/public/wp-content/themes/understrap/src/js/theme.min.js
Line: 7034
```
When I change my `const`s to `var` above, I get another error: 

```
Starting 'scripts'...
[08:30:11] 'scripts' errored after 1.71 s
[08:30:11] GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: name «of», expected: punc «;»
File: /Users/myUser/Local Sites/understrap-test/app/public/wp-content/themes/understrap/src/js/theme.min.js
Line: 7036
Col: 18
```

**Comment by 0dp** [comment]
Could you please try this,

In gulpfile in script task.

Edit

```
.pipe(babel()
```

To

```
.pipe(babel({
	presets: ['@babel/preset-env']
}))
```

Also install
`npm install @babel/preset-env`

**Comment by jweston491** [comment]
@0dp Looks like that solved the compile error, thanks!

**Comment by 0dp** [comment]
@holger1411 @Thomas-A-Reinert @understrap/accessibility-quality 
We need to update the script task and package.json

I'm not at my computer right now so can't make pr

**Comment by Thomas-A-Reinert** [comment]
Seems to work like a charm, @0dp and @jweston491, so I´ll merge that at once.

Only problem that remains and should be fixed is that the same ES6 JS doesn´t compile at all (_without any error message!_) when I write it in a script tag before the end of `footer.php` - and probably neither within `head.php` or wherever.

That´s a thing that should be taken seriously. IF we support compiling ES6 it should be compiled EVERYWHERE. That´s just my opinion and yes you may say that JS shouln´t be mingled with HTML and yes, you´re right.. but ;)

@jweston491 : Just want to thank you very much and personally for your issue report and fixing that thing within no time.

**Comment by Thomas-A-Reinert** [comment]
BTW: Would be nice if you could confirm that the latest commit solves that issue.
