### ISSUE TITLE
How can i solved it? Its the problem of Bootstrap 4

### ISSUE THREAD

**Issue by guddumodok** [understrap/understrap#989]
alert.js:62 Uncaught TypeError: Cannot read property 'fn' of undefined
    at alert.js:62
    at bootstrap.min.js:6
    at bootstrap.min.js:6
(anonymous) @ alert.js:62
(anonymous) @ bootstrap.min.js:6
(anonymous) @ bootstrap.min.js:6

**Comment by Thomas-A-Reinert** [comment]
This problem should´ve been solved since AGES - depending on your US-Version. Please do a research for BootStrap in general and UnderStrap specificially.

Closing this issue as it never has been an issue with the latest releases.
