### ISSUE TITLE
Missing Col on Product

### ISSUE THREAD

**Issue by jchrislemmer** [understrap/understrap#991]
Hey all,

There seems to be a line missing here, just a normal "<div class="col">. The col adds the required padding on mobile when viewing the products. Please let me know if you agree?

https://github.com/understrap/understrap/blob/369a06d18255a58dbc3da6320eb81bebf479981f/inc/woocommerce.php#L47k

Thanks
Chris

**Comment by Thomas-A-Reinert** [comment]
Hi @jchrislemmer : Some of your code seems to be missing. Can you please double-check and repost?

File, Line number, and original code as well as edited code would help

**Comment by Thomas-A-Reinert** [comment]
No updates, so If the problem remains, please feel free to re-open that issue.
