### ISSUE TITLE
Nav walker: blog title left, links centered, button on the right

### ISSUE THREAD

**Issue by Guillaume-Tnk** [understrap/understrap#992]
## Issue is about..
  - [ Nav walker ] I need help to modify nav walker trying to have blog title on the left, links centered and a button on the right.

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:**  MacOS [10.14.03] 

I need help to modify the nav walker: trying to have blog title on the left, links centered and a button on the right like in this example:
```
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="d-flex w-50 order-0">
        <a class="navbar-brand mr-1" href="#">Blog title</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse justify-content-center order-2" id="collapsingNavbar">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Link1 <span class="sr-only">Home</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link3</a>
            </li>
        </ul>
    </div>
    <span class="mt-1 w-50 text-right order-1 order-md-last"><button type="button" class="btn btn-secondary">Primary</button></span>
</nav>

but I don't know how to modify in header.php to achieve this.

**Comment by Thomas-A-Reinert** [comment]
Generic BootStrap issue. Sorry, this is not really UnderStrap related. This is a BootStrap problem you should do a research for. 

Have a look at that possible solution maybe: https://stackoverflow.com/questions/19733447/bootstrap-navbar-with-left-center-or-right-aligned-items/26574870

I´ll close this as this is a non-UnderStrap-issue.
