### ISSUE TITLE
CSS styling gravity form.

### ISSUE THREAD

**Issue by Guillaume-Tnk** [understrap/understrap#993]
## Issue is about..
 
  - [ ] I need help To customise gravity form with css.

## Please tell us about your environment:

  - **WordPress Version:** 5.2.2
  - **OS Version:** MacOS [10.14.3] 

## Steps to reproduce?
Install wordpress
install understrap
install and activate understrap child theme
Install and activate gravity forms
Install and activate ACF

## *How* do we replicate the issue?

Create a form in gravity form
Create an acf text field and paste gravity form short code
use get_field() to display the form.

in _child_theme.scss

add css to gravity form classes.

## Expected behavior

Expecting css to apply to the form

### Other Comments

When adding css from google inspector, the css is being applied for example 
.gform_button{
background-color: red;
}
However if I paste the same css in _child_theme.scss it doesnt work.

Could it be due to the css being loaded before the form or something like that?

**Comment by Thomas-A-Reinert** [comment]
As I cannot look into the code I can just assume that your CSS-rules are just not specific enough to overwrite any styles injected by GF. Try to be more specific or try to add `!important` after the css rule, which is really bad coding-style but nevertheless... should work.

**Comment by Bare-Guillaume** [comment]
@Thomas-A-Reinert Thank you for your fast reply. Even with !important it's not working I'm pretty sure i'm targeting the right class I even tried with targeting by id and it doesn't work either. 
I'm activating a live link if you want to look at the code http://7d37681d.ngrok.io/

**Comment by gaelgerard** [comment]
@Bare-Guillaume does your child-theme.min.css file updates when you save your _child_theme.scss ?

**Comment by Bare-Guillaume** [comment]
@gaelgerard Savior !!! My gulp had stop running and the css wasn't getting minified, hours that I'm looking left and right to find what was the problem. Thank you very much is working :D

**Comment by Thomas-A-Reinert** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen if the problem persists.
