### ISSUE TITLE
Smooth scrolling: $ is not a function.

### ISSUE THREAD

**Issue by Bare-Guillaume** [understrap/understrap#996]
I'm trying to implement smooth scrolling on a one pager.

I have created /child-theme/src/js/custom-javascript.js

```
$(document).ready(function () {
    // Add smooth scrolling to all links
    $("a").on('click', function (event) {

        // Make sure this.hash has a value before overriding default behavior
        if (this.hash !== "") {
            // Prevent default anchor click behavior
            event.preventDefault();

            // Store hash
            var hash = this.hash;

            // Using jQuery's animate() method to add smooth page scroll
            // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
            $('html, body').animate({
                scrollTop: $(hash).offset().top
            }, 800, function () {

                // Add hash (#) to URL when done scrolling (default click behavior)
                window.location.hash = hash;
            });
        } // End if
    });
});
```
from

https://www.w3schools.com/howto/howto_css_smooth_scroll.asp

The debug gives:

Uncaught TypeError: $ is not a function
http://bobeauspa.local/wp-content/themes/understrap-child/js/child-theme.min.js?ver=0.5.3 line 1

As bootstrap is using jquery, I thought it should work.

What am I missing?

**Comment by ffdmatt** [comment]
WordPress doesn't allow the "$" as it conflicts with their code. For jQuery
on WordPress, change "$" to "jQuery" and the code will work.

Test in the browser console to confirm.

**Comment by Bare-Guillaume** [comment]
@ffdmatt That easy !? Thank you very much! Working :)
