### ISSUE TITLE
Woocommerce will not activate

### ISSUE THREAD

**Issue by FalsePozitive** [understrap/understrap#997]
Please delete anything that does not apply for you!

## Issue is about..
  - [ ] a Bug Report
 

  - **WordPress Version:** 4.9.x
  - **OS Version:**  Windows 10
  - **Browser:** [ all ]
  - **Language:** [ PHP]
  - **Node.js & NPM Versions:** Node.js [V X.XX] | NPM [V X.XX]

---

# Issue Overview for Bugreports
Woocommerce installation fails to activate.
line 143 creates a conflict with new woocommerce version and is fixed as per below
In inc/woocommerce.php replace

if ( ! function_exists( 'wc_review_ratings_enabled' ) ) {

with

if ( ! is_admin() && ! function_exists( 'wc_review_ratings_enabled' ) ) {
## Steps to reproduce?
install woocommerce and activate
## *Who* is the bug affecting?
everyone installing latest woocommerce
## *What* is affected by this bug?
activation of woocommerce
## *When* does this occur?
at activation of plugin
## *Where* on the platform does it happen?
plugins dashboard
## *How* do we replicate the issue?
install woocommerce and activate
## Are there any related Issues and/or PRs?
n/a
## Screenshots / Video
n/a
## Expected behavior
woocommmerce would install
# Todos
replace line 142 in inc/woocommerce.php with :

if ( ! is_admin() && ! function_exists( 'wc_review_ratings_enabled' ) ) {

 * Test
 * Documentation

### Other Comments
I've applied this on my own local install and woocommerce now operates as expected.

**Comment by FalsePozitive** [comment]
I had a look at the source and it was already applied. Please update the website with the latest version. Thank you  for this excellent theme.

**Comment by holger1411** [comment]
Thx for reporting. Yes, was already fixed. Will close this. Fix will be part of next version.
